<div id="1Jn_1_1" style="display:none;" class="ver_select"><b>1Jn 1:1</b>  Lo que era desde el principio, lo que hemos oído, lo que hemos visto con nuestros ojos, lo que hemos contemplado y palparon nuestras manos, tocante al Verbo de vida </div>
<div id="1Jn_1_2" style="display:none;" class="ver_select"><b>1Jn 1:2</b>  (porque la vida fue manifestada, y la vimos, y testificamos, y os anunciamos aquella vida eterna, la cual estaba con el Padre, y se nos manifestó). </div>
<div id="1Jn_1_3" style="display:none;" class="ver_select"><b>1Jn 1:3</b>  Lo que hemos visto y oído, eso os anunciamos, para que también vosotros tengáis comunión con nosotros; y nuestra comunión verdaderamente es con el Padre, y con su Hijo Jesucristo. </div>
<div id="1Jn_1_4" style="display:none;" class="ver_select"><b>1Jn 1:4</b>  Y estas cosas os escribimos, para que vuestro gozo sea cumplido. </div>
<div id="1Jn_1_5" style="display:none;" class="ver_select"><b>1Jn 1:5</b>  Y éste es el mensaje que oímos de Él, y os anunciamos; que Dios es luz, y en Él no hay ningunas tinieblas. </div>
<div id="1Jn_1_6" style="display:none;" class="ver_select"><b>1Jn 1:6</b>  Si decimos que tenemos comunión con Él, y andamos en tinieblas, mentimos, y no practicamos la verdad; </div>
<div id="1Jn_1_7" style="display:none;" class="ver_select"><b>1Jn 1:7</b>  mas si andamos en luz, como Él está en luz, tenemos comunión unos con otros, y la sangre de Jesucristo su Hijo nos limpia de todo pecado. </div>
<div id="1Jn_1_8" style="display:none;" class="ver_select"><b>1Jn 1:8</b>  Si decimos que no tenemos pecado, nos engañamos a nosotros mismos, y la verdad no está en nosotros. </div>
<div id="1Jn_1_9" style="display:none;" class="ver_select"><b>1Jn 1:9</b>  Si confesamos nuestros pecados, Él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad. </div>
<div id="1Jn_1_10" style="display:none;" class="ver_select"><b>1Jn 1:10</b>  Si decimos que no hemos pecado, le hacemos a Él mentiroso, y su palabra no está en nosotros. </div>
<div id="1Jn_2_1" style="display:none;" class="ver_select"><b>1Jn 2:1</b>  Hijitos míos, estas cosas os escribo para que no pequéis; y si alguno hubiere pecado, abogado tenemos para con el Padre, a Jesucristo el justo. </div>
<div id="1Jn_2_2" style="display:none;" class="ver_select"><b>1Jn 2:2</b>  Y Él es la propiciación por nuestros pecados; y no solamente por los nuestros, sino también por los de todo el mundo. </div>
<div id="1Jn_2_3" style="display:none;" class="ver_select"><b>1Jn 2:3</b>  Y en esto sabemos que nosotros le conocemos, si guardamos sus mandamientos. </div>
<div id="1Jn_2_4" style="display:none;" class="ver_select"><b>1Jn 2:4</b>  El que dice: Yo le conozco, y no guarda sus mandamientos, el tal es mentiroso, y la verdad no está en él; </div>
<div id="1Jn_2_5" style="display:none;" class="ver_select"><b>1Jn 2:5</b>  pero el que guarda su palabra, verdaderamente el amor de Dios se ha perfeccionado en él; por esto sabemos que estamos en Él. </div>
<div id="1Jn_2_6" style="display:none;" class="ver_select"><b>1Jn 2:6</b>  El que dice que permanece en Él, debe andar como Él anduvo. </div>
<div id="1Jn_2_7" style="display:none;" class="ver_select"><b>1Jn 2:7</b>  Hermanos, no os escribo un mandamiento nuevo, sino el mandamiento antiguo que habéis tenido desde el principio; el mandamiento antiguo es la palabra que habéis oído desde el principio. </div>
<div id="1Jn_2_8" style="display:none;" class="ver_select"><b>1Jn 2:8</b>  Otra vez, os escribo un mandamiento nuevo, que es verdadero en Él y en vosotros; porque las tinieblas han pasado, y la luz verdadera ya alumbra. </div>
<div id="1Jn_2_9" style="display:none;" class="ver_select"><b>1Jn 2:9</b>  El que dice que está en luz, y aborrece a su hermano, está todavía en tinieblas. </div>
<div id="1Jn_2_10" style="display:none;" class="ver_select"><b>1Jn 2:10</b>  El que ama a su hermano, está en luz, y no hay tropiezo en él. </div>
<div id="1Jn_2_11" style="display:none;" class="ver_select"><b>1Jn 2:11</b>  Pero el que aborrece a su hermano, está en tinieblas, y anda en tinieblas, y no sabe a dónde va; porque las tinieblas le han cegado sus ojos. </div>
<div id="1Jn_2_12" style="display:none;" class="ver_select"><b>1Jn 2:12</b>  Os escribo a vosotros, hijitos, porque vuestros pecados os son perdonados por su nombre. </div>
<div id="1Jn_2_13" style="display:none;" class="ver_select"><b>1Jn 2:13</b>  Os escribo a vosotros, padres, porque habéis conocido a Aquél que es desde el principio. Os escribo a vosotros, jóvenes, porque habéis vencido al maligno. Os escribo a vosotros, hijitos, porque habéis conocido al Padre. </div>
<div id="1Jn_2_14" style="display:none;" class="ver_select"><b>1Jn 2:14</b>  Os he escrito a vosotros, padres, porque habéis conocido al que es desde el principio. Os he escrito a vosotros, jóvenes, porque sois fuertes, y la palabra de Dios mora en vosotros, y habéis vencido al maligno. </div>
<div id="1Jn_2_15" style="display:none;" class="ver_select"><b>1Jn 2:15</b>  No améis al mundo, ni las cosas que están en el mundo. Si alguno ama al mundo, el amor del Padre no está en él. </div>
<div id="1Jn_2_16" style="display:none;" class="ver_select"><b>1Jn 2:16</b>  Porque todo lo que hay en el mundo, la concupiscencia de la carne, y la concupiscencia de los ojos, y la soberbia de la vida, no es del Padre, sino del mundo. </div>
<div id="1Jn_2_17" style="display:none;" class="ver_select"><b>1Jn 2:17</b>  Y el mundo pasa, y su concupiscencia; pero el que hace la voluntad de Dios, permanece para siempre. </div>
<div id="1Jn_2_18" style="display:none;" class="ver_select"><b>1Jn 2:18</b>  Hijitos, ya es el último tiempo; y como vosotros habéis oído que el anticristo ha de venir, así también al presente hay muchos anticristos; por lo cual sabemos que es el último tiempo. </div>
<div id="1Jn_2_19" style="display:none;" class="ver_select"><b>1Jn 2:19</b>  Salieron de nosotros, pero no eran de nosotros; porque si hubiesen sido de nosotros, habrían permanecido con nosotros; pero salieron para que se manifestase que no todos son de nosotros. </div>
<div id="1Jn_2_20" style="display:none;" class="ver_select"><b>1Jn 2:20</b>  Mas vosotros tenéis la unción del Santo, y conocéis todas las cosas. </div>
<div id="1Jn_2_21" style="display:none;" class="ver_select"><b>1Jn 2:21</b>  No os he escrito porque ignoréis la verdad, sino porque la conocéis, y porque ninguna mentira es de la verdad. </div>
<div id="1Jn_2_22" style="display:none;" class="ver_select"><b>1Jn 2:22</b>  ¿Quién es mentiroso, sino el que niega que Jesús es el Cristo? Éste es anticristo, que niega al Padre y al Hijo. </div>
<div id="1Jn_2_23" style="display:none;" class="ver_select"><b>1Jn 2:23</b>  Todo aquel que niega al Hijo, tampoco tiene al Padre. El que confiesa al Hijo tiene también al Padre. </div>
<div id="1Jn_2_24" style="display:none;" class="ver_select"><b>1Jn 2:24</b>  Lo que habéis oído desde el principio, permanezca, pues, en vosotros. Si lo que oísteis desde el principio permaneciere en vosotros, también vosotros permaneceréis en el Hijo y en el Padre. </div>
<div id="1Jn_2_25" style="display:none;" class="ver_select"><b>1Jn 2:25</b>  Y ésta es la promesa que Él nos hizo; la vida eterna. </div>
<div id="1Jn_2_26" style="display:none;" class="ver_select"><b>1Jn 2:26</b>  Os he escrito esto acerca de los que os engañan. </div>
<div id="1Jn_2_27" style="display:none;" class="ver_select"><b>1Jn 2:27</b>  Pero la unción que vosotros habéis recibido de Él permanece en vosotros, y no tenéis necesidad de que alguien os enseñe; sino que como la unción misma os enseña acerca de todas las cosas, y es verdadera, y no es mentira, y así como os ha enseñado, vosotros permaneceréis en Él. </div>
<div id="1Jn_2_28" style="display:none;" class="ver_select"><b>1Jn 2:28</b>  Y ahora, hijitos, permaneced en Él; para que cuando Él apareciere, tengamos confianza, y no seamos avergonzados delante de Él en su venida. </div>
<div id="1Jn_2_29" style="display:none;" class="ver_select"><b>1Jn 2:29</b>  Si sabéis que Él es justo, sabed también que todo el que hace justicia es nacido de Él. </div>
<div id="1Jn_3_1" style="display:none;" class="ver_select"><b>1Jn 3:1</b>  Mirad cuál amor nos ha dado el Padre, que seamos llamados hijos de Dios; por esto el mundo no nos conoce, porque no le conoció a Él. </div>
<div id="1Jn_3_2" style="display:none;" class="ver_select"><b>1Jn 3:2</b>  Amados, ahora somos hijos de Dios, y aún no se ha manifestado lo que hemos de ser; pero sabemos que cuando Él apareciere, seremos semejantes a Él, porque le veremos como Él es. </div>
<div id="1Jn_3_3" style="display:none;" class="ver_select"><b>1Jn 3:3</b>  Y cualquiera que tiene esta esperanza en Él, se purifica a sí mismo, así como Él es puro. </div>
<div id="1Jn_3_4" style="display:none;" class="ver_select"><b>1Jn 3:4</b>  Cualquiera que comete pecado, traspasa también la ley; pues el pecado es transgresión de la ley. </div>
<div id="1Jn_3_5" style="display:none;" class="ver_select"><b>1Jn 3:5</b>  Y sabéis que Él apareció para quitar nuestros pecados, y no hay pecado en Él. </div>
<div id="1Jn_3_6" style="display:none;" class="ver_select"><b>1Jn 3:6</b>  Todo aquel que permanece en Él, no peca; todo aquel que peca, no le ha visto, ni le ha conocido. </div>
<div id="1Jn_3_7" style="display:none;" class="ver_select"><b>1Jn 3:7</b>  Hijitos, nadie os engañe; el que hace justicia, es justo, como también Él es justo. </div>
<div id="1Jn_3_8" style="display:none;" class="ver_select"><b>1Jn 3:8</b>  El que hace pecado, es del diablo; porque el diablo peca desde el principio. Para esto apareció el Hijo de Dios, para deshacer las obras del diablo. </div>
<div id="1Jn_3_9" style="display:none;" class="ver_select"><b>1Jn 3:9</b>  Todo aquel que es nacido de Dios, no peca, porque su simiente permanece en él; y no puede pecar, porque es nacido de Dios. </div>
<div id="1Jn_3_10" style="display:none;" class="ver_select"><b>1Jn 3:10</b>  En esto son manifiestos los hijos de Dios, y los hijos del diablo; todo el que no hace justicia, y que no ama a su hermano, no es de Dios. </div>
<div id="1Jn_3_11" style="display:none;" class="ver_select"><b>1Jn 3:11</b>  Porque, éste es el mensaje que habéis oído desde el principio: Que nos amemos unos a otros. </div>
<div id="1Jn_3_12" style="display:none;" class="ver_select"><b>1Jn 3:12</b>  No como Caín, que era del maligno, y mató a su hermano. ¿Y por qué causa le mató? Porque sus obras eran malas, y las de su hermano justas. </div>
<div id="1Jn_3_13" style="display:none;" class="ver_select"><b>1Jn 3:13</b>  Hermanos míos, no os maravilléis si el mundo os aborrece. </div>
<div id="1Jn_3_14" style="display:none;" class="ver_select"><b>1Jn 3:14</b>  Nosotros sabemos que hemos pasado de muerte a vida, en que amamos a los hermanos. El que no ama a su hermano, permanece en muerte. </div>
<div id="1Jn_3_15" style="display:none;" class="ver_select"><b>1Jn 3:15</b>  Todo aquel que aborrece a su hermano, es homicida; y sabéis que ningún homicida tiene vida eterna morando en sí. </div>
<div id="1Jn_3_16" style="display:none;" class="ver_select"><b>1Jn 3:16</b>  En esto conocemos el amor de Dios, en que Él puso su vida por nosotros; también nosotros debemos poner nuestras vidas por los hermanos. </div>
<div id="1Jn_3_17" style="display:none;" class="ver_select"><b>1Jn 3:17</b>  Pero el que tiene bienes de este mundo, y ve a su hermano tener necesidad, y le cierra sus entrañas, ¿cómo mora el amor de Dios en él? </div>
<div id="1Jn_3_18" style="display:none;" class="ver_select"><b>1Jn 3:18</b>  Hijitos míos, no amemos de palabra ni de lengua, sino de hecho y en verdad. </div>
<div id="1Jn_3_19" style="display:none;" class="ver_select"><b>1Jn 3:19</b>  Y en esto conocemos que somos de la verdad, y aseguraremos nuestros corazones delante de Él. </div>
<div id="1Jn_3_20" style="display:none;" class="ver_select"><b>1Jn 3:20</b>  Porque si nuestro corazón nos reprende, mayor es Dios que nuestro corazón, y Él conoce todas las cosas. </div>
<div id="1Jn_3_21" style="display:none;" class="ver_select"><b>1Jn 3:21</b>  Amados, si nuestro corazón no nos reprende, confianza tenemos para con Dios; </div>
<div id="1Jn_3_22" style="display:none;" class="ver_select"><b>1Jn 3:22</b>  y cualquier cosa que pidiéremos, la recibiremos de Él, porque guardamos sus mandamientos y hacemos las cosas que son agradables delante de Él. </div>
<div id="1Jn_3_23" style="display:none;" class="ver_select"><b>1Jn 3:23</b>  Y éste es su mandamiento: Que creamos en el nombre de su Hijo Jesucristo, y nos amemos unos a otros como nos lo ha mandado. </div>
<div id="1Jn_3_24" style="display:none;" class="ver_select"><b>1Jn 3:24</b>  Y el que guarda sus mandamientos, permanece en Él, y Él en él. Y en esto sabemos que Él permanece en nosotros, por el Espíritu que nos ha dado. </div>
<div id="1Jn_4_1" style="display:none;" class="ver_select"><b>1Jn 4:1</b>  Amados, no creáis a todo espíritu, sino probad los espíritus si son de Dios; porque muchos falsos profetas han salido por el mundo. </div>
<div id="1Jn_4_2" style="display:none;" class="ver_select"><b>1Jn 4:2</b>  En esto conoced el Espíritu de Dios: Todo espíritu que confiesa que Jesucristo ha venido en carne, es de Dios; </div>
<div id="1Jn_4_3" style="display:none;" class="ver_select"><b>1Jn 4:3</b>  y todo espíritu que no confiesa que Jesucristo ha venido en carne, no es de Dios; y éste es el espíritu del anticristo, del cual vosotros habéis oído que ha de venir, y que ahora ya está en el mundo. </div>
<div id="1Jn_4_4" style="display:none;" class="ver_select"><b>1Jn 4:4</b>  Hijitos, vosotros sois de Dios, y los habéis vencido; porque mayor es el que está en vosotros, que el que está en el mundo. </div>
<div id="1Jn_4_5" style="display:none;" class="ver_select"><b>1Jn 4:5</b>  Ellos son del mundo; por eso hablan del mundo, y el mundo los oye. </div>
<div id="1Jn_4_6" style="display:none;" class="ver_select"><b>1Jn 4:6</b>  Nosotros somos de Dios; el que conoce a Dios, nos oye; el que no es de Dios, no nos oye. En esto conocemos el espíritu de verdad y el espíritu de error. </div>
<div id="1Jn_4_7" style="display:none;" class="ver_select"><b>1Jn 4:7</b>  Amados, amémonos unos a otros; porque el amor es de Dios. Todo el que ama, es nacido de Dios, y conoce a Dios. </div>
<div id="1Jn_4_8" style="display:none;" class="ver_select"><b>1Jn 4:8</b>  El que no ama no conoce a Dios, porque Dios es amor. </div>
<div id="1Jn_4_9" style="display:none;" class="ver_select"><b>1Jn 4:9</b>  En esto se mostró el amor de Dios para con nosotros, en que Dios envió a su Hijo unigénito al mundo, para que vivamos por Él. </div>
<div id="1Jn_4_10" style="display:none;" class="ver_select"><b>1Jn 4:10</b>  En esto consiste el amor; no en que nosotros hayamos amado a Dios, sino que Él nos amó a nosotros, y envió a su Hijo en propiciación por nuestros pecados. </div>
<div id="1Jn_4_11" style="display:none;" class="ver_select"><b>1Jn 4:11</b>  Amados, si Dios así nos ha amado, debemos también nosotros amarnos unos a otros. </div>
<div id="1Jn_4_12" style="display:none;" class="ver_select"><b>1Jn 4:12</b>  A Dios nadie le vio jamás. Si nos amamos unos a otros, Dios permanece en nosotros, y su amor se perfecciona en nosotros. </div>
<div id="1Jn_4_13" style="display:none;" class="ver_select"><b>1Jn 4:13</b>  En esto conocemos que permanecemos en Él, y Él en nosotros, en que nos ha dado de su Espíritu. </div>
<div id="1Jn_4_14" style="display:none;" class="ver_select"><b>1Jn 4:14</b>  Y nosotros hemos visto y testificamos que el Padre ha enviado al Hijo para ser el Salvador del mundo. </div>
<div id="1Jn_4_15" style="display:none;" class="ver_select"><b>1Jn 4:15</b>  Todo aquel que confiese que Jesús es el Hijo de Dios, Dios permanece en él, y él en Dios. </div>
<div id="1Jn_4_16" style="display:none;" class="ver_select"><b>1Jn 4:16</b>  Y nosotros hemos conocido y creído el amor que Dios tiene para con nosotros. Dios es amor; y el que permanece en amor, permanece en Dios, y Dios en él. </div>
<div id="1Jn_4_17" style="display:none;" class="ver_select"><b>1Jn 4:17</b>  En esto es perfeccionado el amor en nosotros, para que tengamos confianza en el día del juicio; pues como Él es, así somos nosotros en este mundo. </div>
<div id="1Jn_4_18" style="display:none;" class="ver_select"><b>1Jn 4:18</b>  En el amor no hay temor; mas el perfecto amor echa fuera el temor, porque el temor conlleva castigo. Y el que teme no ha sido perfeccionado en el amor. </div>
<div id="1Jn_4_19" style="display:none;" class="ver_select"><b>1Jn 4:19</b>  Nosotros le amamos a Él, porque Él nos amó primero. </div>
<div id="1Jn_4_20" style="display:none;" class="ver_select"><b>1Jn 4:20</b>  Si alguno dice: Yo amo a Dios, y aborrece a su hermano, es mentiroso; porque el que no ama a su hermano a quien ha visto, ¿cómo puede amar a Dios a quien no ha visto? </div>
<div id="1Jn_4_21" style="display:none;" class="ver_select"><b>1Jn 4:21</b>  Y nosotros tenemos este mandamiento de Él: Que el que ama a Dios, ame también a su hermano. </div>
<div id="1Jn_5_1" style="display:none;" class="ver_select"><b>1Jn 5:1</b>  Todo aquel que cree que Jesús es el Cristo, es nacido de Dios; y todo aquel que ama al que engendró, ama también al que es engendrado por Él. </div>
<div id="1Jn_5_2" style="display:none;" class="ver_select"><b>1Jn 5:2</b>  En esto conocemos que amamos a los hijos de Dios, cuando amamos a Dios y guardamos sus mandamientos. </div>
<div id="1Jn_5_3" style="display:none;" class="ver_select"><b>1Jn 5:3</b>  Porque éste es el amor de Dios, que guardemos sus mandamientos; y sus mandamientos no son gravosos. </div>
<div id="1Jn_5_4" style="display:none;" class="ver_select"><b>1Jn 5:4</b>  Porque todo lo que es nacido de Dios vence al mundo; y ésta es la victoria que ha vencido al mundo, nuestra fe. </div>
<div id="1Jn_5_5" style="display:none;" class="ver_select"><b>1Jn 5:5</b>  ¿Quién es el que vence al mundo, sino el que cree que Jesús es el Hijo de Dios? </div>
<div id="1Jn_5_6" style="display:none;" class="ver_select"><b>1Jn 5:6</b>  Éste es el que vino mediante agua y sangre, Jesucristo; no mediante agua solamente, sino mediante agua y sangre. Y el Espíritu es el que da testimonio; porque el Espíritu es la verdad. </div>
<div id="1Jn_5_7" style="display:none;" class="ver_select"><b>1Jn 5:7</b>  Porque tres son los que dan testimonio en el cielo, el Padre, el Verbo y el Espíritu Santo; y estos tres son uno. </div>
<div id="1Jn_5_8" style="display:none;" class="ver_select"><b>1Jn 5:8</b>  Y tres son los que dan testimonio en la tierra; el Espíritu, el agua, y la sangre; y estos tres concuerdan en uno. </div>
<div id="1Jn_5_9" style="display:none;" class="ver_select"><b>1Jn 5:9</b>  Si recibimos el testimonio de los hombres, el testimonio de Dios es mayor; porque éste es el testimonio de Dios que Él ha dado acerca de su Hijo. </div>
<div id="1Jn_5_10" style="display:none;" class="ver_select"><b>1Jn 5:10</b>  El que cree en el Hijo de Dios, tiene el testimonio en sí mismo; el que no cree a Dios, le ha hecho mentiroso; porque no ha creído en el testimonio que Dios ha dado de su Hijo. </div>
<div id="1Jn_5_11" style="display:none;" class="ver_select"><b>1Jn 5:11</b>  Y éste es el testimonio: Que Dios nos ha dado vida eterna; y esta vida está en su Hijo. </div>
<div id="1Jn_5_12" style="display:none;" class="ver_select"><b>1Jn 5:12</b>  El que tiene al Hijo, tiene la vida; el que no tiene al Hijo de Dios, no tiene la vida. </div>
<div id="1Jn_5_13" style="display:none;" class="ver_select"><b>1Jn 5:13</b>  Estas cosas os he escrito a vosotros que creéis en el nombre del Hijo de Dios, para que sepáis que tenéis vida eterna, y para que creáis en el nombre del Hijo de Dios. </div>
<div id="1Jn_5_14" style="display:none;" class="ver_select"><b>1Jn 5:14</b>  Y ésta es la confianza que tenemos en Él, que si pedimos alguna cosa conforme a su voluntad, Él nos oye. </div>
<div id="1Jn_5_15" style="display:none;" class="ver_select"><b>1Jn 5:15</b>  Y si sabemos que Él nos oye en cualquier cosa que pidamos, sabemos que tenemos las peticiones que le hayamos hecho. </div>
<div id="1Jn_5_16" style="display:none;" class="ver_select"><b>1Jn 5:16</b>  Si alguno ve a su hermano cometer pecado no de muerte, pedirá, y Dios le dará vida; digo a los que pecan no de muerte. Hay pecado de muerte, por el cual yo no digo que se pida. </div>
<div id="1Jn_5_17" style="display:none;" class="ver_select"><b>1Jn 5:17</b>  Toda maldad es pecado; mas hay pecado no de muerte. </div>
<div id="1Jn_5_18" style="display:none;" class="ver_select"><b>1Jn 5:18</b>  Sabemos que cualquiera que es nacido de Dios, no peca, porque el que es engendrado de Dios, se guarda a sí mismo, y el maligno no le toca. </div>
<div id="1Jn_5_19" style="display:none;" class="ver_select"><b>1Jn 5:19</b>  Sabemos que somos de Dios, y el mundo entero yace en maldad. </div>
<div id="1Jn_5_20" style="display:none;" class="ver_select"><b>1Jn 5:20</b>  Y sabemos que el Hijo de Dios ha venido, y nos ha dado entendimiento para conocer al que es verdadero; y estamos en el verdadero, en su Hijo Jesucristo. Éste es el verdadero Dios, y la vida eterna. </div>
<div id="1Jn_5_21" style="display:none;" class="ver_select"><b>1Jn 5:21</b>  Hijitos, guardaos de los ídolos. Amén. </div>
