<div id="1Pe_1_1" style="display:none;" class="ver_select"><b>1Pe 1:1</b>  Pedro, apóstol de Jesucristo, a los expatriados esparcidos por todo Ponto, Galacia, Capadocia, Asia y Bitinia, </div>
<div id="1Pe_1_2" style="display:none;" class="ver_select"><b>1Pe 1:2</b>  elegidos según la presciencia de Dios Padre en santificación del Espíritu, para obedecer y ser rociados con la sangre de Jesucristo: Gracia y paz os sean multiplicadas. </div>
<div id="1Pe_1_3" style="display:none;" class="ver_select"><b>1Pe 1:3</b>  Bendito sea el Dios y Padre de nuestro Señor Jesucristo, que según su grande misericordia nos hizo renacer para una esperanza viva, por la resurrección de Jesucristo de los muertos; </div>
<div id="1Pe_1_4" style="display:none;" class="ver_select"><b>1Pe 1:4</b>  para una herencia incorruptible, incontaminada e inmarcesible, reservada en el cielo para vosotros, </div>
<div id="1Pe_1_5" style="display:none;" class="ver_select"><b>1Pe 1:5</b>  que sois guardados por el poder de Dios mediante la fe, para la salvación que está lista para ser manifestada en el tiempo postrero. </div>
<div id="1Pe_1_6" style="display:none;" class="ver_select"><b>1Pe 1:6</b>  En lo cual vosotros mucho os alegráis, aunque al presente por un poco de tiempo, si es necesario, estéis afligidos por diversas pruebas, </div>
<div id="1Pe_1_7" style="display:none;" class="ver_select"><b>1Pe 1:7</b>  para que la prueba de vuestra fe, mucho más preciosa que el oro que perece, aunque sea probado con fuego, sea hallada en alabanza, gloria y honra, en la manifestación de Jesucristo, </div>
<div id="1Pe_1_8" style="display:none;" class="ver_select"><b>1Pe 1:8</b>  a quien amáis sin haberle visto; en quien creyendo, aunque al presente no le veáis, os alegráis con gozo inefable y glorioso; </div>
<div id="1Pe_1_9" style="display:none;" class="ver_select"><b>1Pe 1:9</b>  obteniendo el fin de vuestra fe, que es la salvación de vuestras almas. </div>
<div id="1Pe_1_10" style="display:none;" class="ver_select"><b>1Pe 1:10</b>  Acerca de esta salvación inquirieron y diligentemente indagaron los profetas que profetizaron de la gracia que había de venir a vosotros, </div>
<div id="1Pe_1_11" style="display:none;" class="ver_select"><b>1Pe 1:11</b>  escudriñando cuándo o en qué punto de tiempo indicaba el Espíritu de Cristo que estaba en ellos, cuando prenunciaba los sufrimientos de Cristo, y las glorias después de ellos. </div>
<div id="1Pe_1_12" style="display:none;" class="ver_select"><b>1Pe 1:12</b>  A los cuales fue revelado, que no para sí mismos, sino para nosotros, administraban las cosas que ahora os son anunciadas por los que os han predicado el evangelio por el Espíritu Santo enviado del cielo; cosas en las cuales desean mirar los ángeles. </div>
<div id="1Pe_1_13" style="display:none;" class="ver_select"><b>1Pe 1:13</b>  Por lo cual, ceñid los lomos de vuestro entendimiento, sed sobrios, esperad por completo en la gracia que se os traerá en la manifestación de Jesucristo. </div>
<div id="1Pe_1_14" style="display:none;" class="ver_select"><b>1Pe 1:14</b>  Como hijos obedientes, no os conforméis a las concupiscencias que antes teníais estando en vuestra ignorancia; </div>
<div id="1Pe_1_15" style="display:none;" class="ver_select"><b>1Pe 1:15</b>  sino que, así como Aquél que os llamó es santo, así también vosotros sed santos en toda vuestra manera de vivir; </div>
<div id="1Pe_1_16" style="display:none;" class="ver_select"><b>1Pe 1:16</b>  porque escrito está: Sed santos, porque yo soy santo. </div>
<div id="1Pe_1_17" style="display:none;" class="ver_select"><b>1Pe 1:17</b>  Y si invocáis al Padre, que sin acepción de personas juzga según la obra de cada uno, conducíos en temor todo el tiempo de vuestra peregrinación; </div>
<div id="1Pe_1_18" style="display:none;" class="ver_select"><b>1Pe 1:18</b>  sabiendo que fuisteis redimidos de vuestra vana manera de vivir, la cual recibisteis por tradición de vuestros padres, no con cosas corruptibles, como oro o plata; </div>
<div id="1Pe_1_19" style="display:none;" class="ver_select"><b>1Pe 1:19</b>  sino con la sangre preciosa de Cristo, como de un cordero sin mancha y sin contaminación; </div>
<div id="1Pe_1_20" style="display:none;" class="ver_select"><b>1Pe 1:20</b>  ya preordinado desde antes de la fundación del mundo, pero manifestado en los postreros tiempos por amor a vosotros, </div>
<div id="1Pe_1_21" style="display:none;" class="ver_select"><b>1Pe 1:21</b>  quienes por Él creéis en Dios, el cual le resucitó de los muertos, y le ha dado gloria, para que vuestra fe y esperanza sean en Dios. </div>
<div id="1Pe_1_22" style="display:none;" class="ver_select"><b>1Pe 1:22</b>  Habiendo purificado vuestras almas en la obediencia de la verdad, mediante el Espíritu, para el amor fraternal no fingido, amaos unos a otros entrañablemente, de corazón puro; </div>
<div id="1Pe_1_23" style="display:none;" class="ver_select"><b>1Pe 1:23</b>  siendo renacidos, no de simiente corruptible, sino de incorruptible, por la palabra de Dios que vive y permanece para siempre. </div>
<div id="1Pe_1_24" style="display:none;" class="ver_select"><b>1Pe 1:24</b>  Porque toda carne es como la hierba, y toda la gloria del hombre como la flor de la hierba. La hierba se seca, y la flor se cae; </div>
<div id="1Pe_1_25" style="display:none;" class="ver_select"><b>1Pe 1:25</b>  mas la palabra del Señor permanece para siempre. Y ésta es la palabra que por el evangelio os ha sido predicada. </div>
<div id="1Pe_2_1" style="display:none;" class="ver_select"><b>1Pe 2:1</b>  Desechando, pues, toda malicia, y todo engaño, e hipocresía, y envidia, y toda maledicencia, </div>
<div id="1Pe_2_2" style="display:none;" class="ver_select"><b>1Pe 2:2</b>  desead, como niños recién nacidos, la leche no adulterada de la palabra, para que por ella crezcáis; </div>
<div id="1Pe_2_3" style="display:none;" class="ver_select"><b>1Pe 2:3</b>  si es que habéis gustado la benignidad del Señor; </div>
<div id="1Pe_2_4" style="display:none;" class="ver_select"><b>1Pe 2:4</b>  al cual acercándoos, piedra viva, desechada ciertamente por los hombres, mas escogida y preciosa para Dios. </div>
<div id="1Pe_2_5" style="display:none;" class="ver_select"><b>1Pe 2:5</b>  Vosotros también, como piedras vivas, sois edificados como casa espiritual y sacerdocio santo, para ofrecer sacrificios espirituales, agradables a Dios por Jesucristo. </div>
<div id="1Pe_2_6" style="display:none;" class="ver_select"><b>1Pe 2:6</b>  Por lo cual también contiene la Escritura: He aquí, pongo en Sión la principal piedra del ángulo, escogida, preciosa; Y el que creyere en Él, no será avergonzado. </div>
<div id="1Pe_2_7" style="display:none;" class="ver_select"><b>1Pe 2:7</b>  Para vosotros, pues, los que creéis; Él es precioso; mas para los desobedientes, la piedra que los edificadores desecharon; ésta fue hecha la cabeza del ángulo; </div>
<div id="1Pe_2_8" style="display:none;" class="ver_select"><b>1Pe 2:8</b>  Y: Piedra de tropiezo, y roca de escándalo a los que tropiezan en la palabra, siendo desobedientes; para lo cual fueron también ordenados. </div>
<div id="1Pe_2_9" style="display:none;" class="ver_select"><b>1Pe 2:9</b>  Mas vosotros sois linaje escogido, real sacerdocio, nación santa, pueblo adquirido; para que anunciéis las virtudes de Aquel que os llamó de las tinieblas a su luz admirable. </div>
<div id="1Pe_2_10" style="display:none;" class="ver_select"><b>1Pe 2:10</b>  Vosotros, que en tiempo pasado no erais pueblo, mas ahora sois el pueblo de Dios; que no habíais alcanzado misericordia, pero ahora habéis alcanzado misericordia. </div>
<div id="1Pe_2_11" style="display:none;" class="ver_select"><b>1Pe 2:11</b>  Amados, yo os ruego como a extranjeros y peregrinos, que os abstengáis de las concupiscencias carnales que batallan contra el alma; </div>
<div id="1Pe_2_12" style="display:none;" class="ver_select"><b>1Pe 2:12</b>  manteniendo vuestra honesta manera de vivir entre los gentiles; para que, en lo que ellos murmuran de vosotros como de malhechores, al ver vuestras buenas obras, glorifiquen a Dios en el día de la visitación. </div>
<div id="1Pe_2_13" style="display:none;" class="ver_select"><b>1Pe 2:13</b>  Sujetaos a toda ordenación humana por causa del Señor; ya sea al rey, como a superior, </div>
<div id="1Pe_2_14" style="display:none;" class="ver_select"><b>1Pe 2:14</b>  ya a los gobernadores, como por Él enviados para castigo de los malhechores y alabanza de los que hacen bien. </div>
<div id="1Pe_2_15" style="display:none;" class="ver_select"><b>1Pe 2:15</b>  Porque ésta es la voluntad de Dios; que haciendo el bien, hagáis callar la ignorancia de los hombres vanos. </div>
<div id="1Pe_2_16" style="display:none;" class="ver_select"><b>1Pe 2:16</b>  Como libres, mas no usando la libertad para cobertura de malicia, sino como siervos de Dios. </div>
<div id="1Pe_2_17" style="display:none;" class="ver_select"><b>1Pe 2:17</b>  Honrad a todos. Amad la hermandad. Temed a Dios. Honrad al rey. </div>
<div id="1Pe_2_18" style="display:none;" class="ver_select"><b>1Pe 2:18</b>  Siervos, sujetaos con todo temor a vuestros amos; no solamente a los buenos y amables, sino también a los que son severos. </div>
<div id="1Pe_2_19" style="display:none;" class="ver_select"><b>1Pe 2:19</b>  Porque esto es loable, si alguno a causa de la conciencia delante de Dios, sufre molestias padeciendo injustamente. </div>
<div id="1Pe_2_20" style="display:none;" class="ver_select"><b>1Pe 2:20</b>  Porque ¿qué gloria es, si pecando vosotros sois abofeteados, y lo sufrís? Pero si haciendo bien sois afligidos, y lo sufrís, esto ciertamente es agradable delante de Dios. </div>
<div id="1Pe_2_21" style="display:none;" class="ver_select"><b>1Pe 2:21</b>  Porque para esto fuisteis llamados; pues que también Cristo padeció por nosotros, dejándonos ejemplo, para que vosotros sigáis sus pisadas: </div>
<div id="1Pe_2_22" style="display:none;" class="ver_select"><b>1Pe 2:22</b>  El cual no hizo pecado; ni fue hallado engaño en su boca: </div>
<div id="1Pe_2_23" style="display:none;" class="ver_select"><b>1Pe 2:23</b>  Quien cuando le maldecían no respondía con maldición; cuando padecía, no amenazaba, sino que se encomendaba a Aquél que juzga justamente: </div>
<div id="1Pe_2_24" style="display:none;" class="ver_select"><b>1Pe 2:24</b>  Quien llevó Él mismo nuestros pecados en su cuerpo sobre el madero, para que nosotros, siendo muertos a los pecados, vivamos a la justicia; por las heridas del cual habéis sido sanados. </div>
<div id="1Pe_2_25" style="display:none;" class="ver_select"><b>1Pe 2:25</b>  Porque vosotros erais como ovejas descarriadas; mas ahora habéis vuelto al Pastor y Obispo de vuestras almas. </div>
<div id="1Pe_3_1" style="display:none;" class="ver_select"><b>1Pe 3:1</b>  Asimismo vosotras, esposas, sujetaos a vuestros propios maridos; para que también los que no creen a la palabra, sean ganados sin palabra por la conducta de sus esposas, </div>
<div id="1Pe_3_2" style="display:none;" class="ver_select"><b>1Pe 3:2</b>  al observar ellos vuestra casta conducta que es en temor. </div>
<div id="1Pe_3_3" style="display:none;" class="ver_select"><b>1Pe 3:3</b>  Que vuestro adorno no sea exterior, con encrespamiento del cabello y atavío de oro, ni vestidos costosos; </div>
<div id="1Pe_3_4" style="display:none;" class="ver_select"><b>1Pe 3:4</b>  sino el del hombre interior, el del corazón, en incorruptible ornato de espíritu humilde y apacible, lo cual es de grande estima delante de Dios. </div>
<div id="1Pe_3_5" style="display:none;" class="ver_select"><b>1Pe 3:5</b>  Porque así también se ataviaban en el tiempo antiguo aquellas santas mujeres que esperaban en Dios, siendo sujetas a sus maridos; </div>
<div id="1Pe_3_6" style="display:none;" class="ver_select"><b>1Pe 3:6</b>  como Sara obedecía a Abraham, llamándole señor; de la cual vosotras sois hechas hijas, haciendo el bien, y no teniendo temor de ninguna amenaza. </div>
<div id="1Pe_3_7" style="display:none;" class="ver_select"><b>1Pe 3:7</b>  Asimismo, vosotros, maridos, habitad con ellas sabiamente, dando honor a la esposa como a vaso más frágil, y como a coherederas de la gracia de vida; para que vuestras oraciones no sean estorbadas. </div>
<div id="1Pe_3_8" style="display:none;" class="ver_select"><b>1Pe 3:8</b>  Finalmente, sed todos de un mismo sentir, compasivos, amándoos fraternalmente, misericordiosos, amigables; </div>
<div id="1Pe_3_9" style="display:none;" class="ver_select"><b>1Pe 3:9</b>  no devolviendo mal por mal, ni maldición por maldición, sino por el contrario, bendiciendo; sabiendo que vosotros sois llamados para que heredaseis bendición. </div>
<div id="1Pe_3_10" style="display:none;" class="ver_select"><b>1Pe 3:10</b>  Porque el que quiera amar la vida, y ver días buenos, refrene su lengua de mal, y sus labios no hablen engaño; </div>
<div id="1Pe_3_11" style="display:none;" class="ver_select"><b>1Pe 3:11</b>  apártese del mal, y haga el bien; busque la paz, y sígala. </div>
<div id="1Pe_3_12" style="display:none;" class="ver_select"><b>1Pe 3:12</b>  Porque los ojos del Señor están sobre los justos, y sus oídos atentos a sus oraciones: Pero el rostro del Señor está contra aquellos que hacen el mal. </div>
<div id="1Pe_3_13" style="display:none;" class="ver_select"><b>1Pe 3:13</b>  ¿Y quién es aquel que os podrá dañar, si vosotros seguís el bien? </div>
<div id="1Pe_3_14" style="display:none;" class="ver_select"><b>1Pe 3:14</b>  Mas también si alguna cosa padecéis por la justicia, sois bienaventurados. Por tanto, no os amedrentéis por temor de ellos, ni seáis turbados; </div>
<div id="1Pe_3_15" style="display:none;" class="ver_select"><b>1Pe 3:15</b>  sino santificad al Señor Dios en vuestros corazones, y estad siempre preparados para responder con mansedumbre y temor a todo el que os demande razón de la esperanza que hay en vosotros; </div>
<div id="1Pe_3_16" style="display:none;" class="ver_select"><b>1Pe 3:16</b>  teniendo buena conciencia, para que en lo que murmuran de vosotros como de malhechores, sean avergonzados los que calumnian vuestra buena conducta en Cristo. </div>
<div id="1Pe_3_17" style="display:none;" class="ver_select"><b>1Pe 3:17</b>  Porque mejor es que padezcáis haciendo el bien, si la voluntad de Dios así lo quiere, que haciendo el mal. </div>
<div id="1Pe_3_18" style="display:none;" class="ver_select"><b>1Pe 3:18</b>  Porque también Cristo padeció una sola vez por los pecados, el justo por los injustos, para llevarnos a Dios, siendo a la verdad muerto en la carne, pero vivificado por el Espíritu; </div>
<div id="1Pe_3_19" style="display:none;" class="ver_select"><b>1Pe 3:19</b>  en el cual también fue y predicó a los espíritus encarcelados; </div>
<div id="1Pe_3_20" style="display:none;" class="ver_select"><b>1Pe 3:20</b>  los cuales en tiempo pasado fueron desobedientes, cuando una vez esperaba la paciencia de Dios en los días de Noé, mientras se aparejaba el arca; en la cual pocas, es decir, ocho almas fueron salvadas por agua. </div>
<div id="1Pe_3_21" style="display:none;" class="ver_select"><b>1Pe 3:21</b>  A la figura de lo cual el bautismo que ahora corresponde nos salva (no quitando las inmundicias de la carne, sino como testimonio de una buena conciencia delante de Dios) por la resurrección de Jesucristo, </div>
<div id="1Pe_3_22" style="display:none;" class="ver_select"><b>1Pe 3:22</b>  el cual habiendo subido al cielo, está a la diestra de Dios; estando sujetos a Él, ángeles, autoridades y potestades. </div>
<div id="1Pe_4_1" style="display:none;" class="ver_select"><b>1Pe 4:1</b>  Puesto que Cristo ha padecido por nosotros en la carne, vosotros también armaos del mismo pensamiento; porque el que ha padecido en la carne, cesó de pecado; </div>
<div id="1Pe_4_2" style="display:none;" class="ver_select"><b>1Pe 4:2</b>  para que ya el tiempo que queda en la carne, viva, no en las concupiscencias de los hombres, sino en la voluntad de Dios. </div>
<div id="1Pe_4_3" style="display:none;" class="ver_select"><b>1Pe 4:3</b>  Baste ya el tiempo pasado de nuestra vida para haber hecho la voluntad de los gentiles, andando en lascivias, concupiscencias, embriagueces, desenfrenos, banquetes y abominables idolatrías. </div>
<div id="1Pe_4_4" style="display:none;" class="ver_select"><b>1Pe 4:4</b>  En lo cual les parece cosa extraña que vosotros no corráis con ellos en el mismo desenfreno de disolución, y os ultrajan; </div>
<div id="1Pe_4_5" style="display:none;" class="ver_select"><b>1Pe 4:5</b>  pero ellos darán cuenta al que está preparado para juzgar a los vivos y a los muertos. </div>
<div id="1Pe_4_6" style="display:none;" class="ver_select"><b>1Pe 4:6</b>  Porque por esto también ha sido predicado el evangelio a los muertos; para que sean juzgados en la carne según los hombres, pero vivan en el espíritu según Dios. </div>
<div id="1Pe_4_7" style="display:none;" class="ver_select"><b>1Pe 4:7</b>  Mas el fin de todas las cosas se acerca; sed, pues, sobrios, y velad en oración. </div>
<div id="1Pe_4_8" style="display:none;" class="ver_select"><b>1Pe 4:8</b>  Y sobre todo, tened entre vosotros ferviente amor; porque el amor cubrirá multitud de pecados. </div>
<div id="1Pe_4_9" style="display:none;" class="ver_select"><b>1Pe 4:9</b>  Hospedaos los unos a los otros sin murmuraciones. </div>
<div id="1Pe_4_10" style="display:none;" class="ver_select"><b>1Pe 4:10</b>  Cada uno según el don que ha recibido, minístrelo a los otros, como buenos administradores de la multiforme gracia de Dios. </div>
<div id="1Pe_4_11" style="display:none;" class="ver_select"><b>1Pe 4:11</b>  Si alguno habla, hable conforme a la palabra de Dios; si alguno ministra, ministre conforme al poder que Dios da; para que en todo Dios sea glorificado por Jesucristo, al cual sea gloria e imperio para siempre jamás. Amén. </div>
<div id="1Pe_4_12" style="display:none;" class="ver_select"><b>1Pe 4:12</b>  Amados, no os extrañéis acerca de la prueba de fuego la cual se hace para probaros, como si alguna cosa extraña os aconteciese; </div>
<div id="1Pe_4_13" style="display:none;" class="ver_select"><b>1Pe 4:13</b>  antes bien regocijaos en que sois participantes de los padecimientos de Cristo; para que cuando su gloria sea revelada, os regocijéis con gran alegría. </div>
<div id="1Pe_4_14" style="display:none;" class="ver_select"><b>1Pe 4:14</b>  Si sois vituperados por el nombre de Cristo, sois bienaventurados; porque el Espíritu de gloria y de Dios reposa sobre vosotros. Cierto según ellos, Él es blasfemado, mas según vosotros Él es glorificado. </div>
<div id="1Pe_4_15" style="display:none;" class="ver_select"><b>1Pe 4:15</b>  Así que, ninguno de vosotros padezca como homicida, o ladrón, o malhechor, o por entremeterse en asuntos ajenos. </div>
<div id="1Pe_4_16" style="display:none;" class="ver_select"><b>1Pe 4:16</b>  Pero si alguno padece como cristiano, no se avergüence; antes glorifique a Dios por ello. </div>
<div id="1Pe_4_17" style="display:none;" class="ver_select"><b>1Pe 4:17</b>  Porque es tiempo de que el juicio comience por la casa de Dios; y si primero comienza por nosotros, ¿cuál será el fin de aquellos que no obedecen al evangelio de Dios? </div>
<div id="1Pe_4_18" style="display:none;" class="ver_select"><b>1Pe 4:18</b>  Y si el justo con dificultad es salvo; ¿en dónde aparecerá el impío y el pecador? </div>
<div id="1Pe_4_19" style="display:none;" class="ver_select"><b>1Pe 4:19</b>  Por tanto, los que padecen según la voluntad de Dios, encomienden a Él sus almas, como a fiel Creador, haciendo el bien. </div>
<div id="1Pe_5_1" style="display:none;" class="ver_select"><b>1Pe 5:1</b>  Ruego a los ancianos que están entre vosotros, yo anciano también con ellos, y testigo de los padecimientos de Cristo, que soy también participante de la gloria que ha de ser revelada: </div>
<div id="1Pe_5_2" style="display:none;" class="ver_select"><b>1Pe 5:2</b>  Apacentad la grey de Dios que está entre vosotros, cuidando de ella, no por fuerza, sino voluntariamente; no por ganancia deshonesta, sino de ánimo pronto; </div>
<div id="1Pe_5_3" style="display:none;" class="ver_select"><b>1Pe 5:3</b>  y no como teniendo señorío sobre la heredad de Dios, sino siendo ejemplos de la grey. </div>
<div id="1Pe_5_4" style="display:none;" class="ver_select"><b>1Pe 5:4</b>  Y cuando apareciere el Príncipe de los pastores, vosotros recibiréis la corona incorruptible de gloria. </div>
<div id="1Pe_5_5" style="display:none;" class="ver_select"><b>1Pe 5:5</b>  Igualmente, jóvenes, sujetaos a los ancianos; y todos sujetaos unos a otros, y vestíos de humildad; porque Dios resiste a los soberbios, y da gracia a los humildes. </div>
<div id="1Pe_5_6" style="display:none;" class="ver_select"><b>1Pe 5:6</b>  Humillaos, pues, bajo la poderosa mano de Dios, para que Él os exalte cuando fuere tiempo; </div>
<div id="1Pe_5_7" style="display:none;" class="ver_select"><b>1Pe 5:7</b>  echando toda vuestra ansiedad sobre Él, porque Él tiene cuidado de vosotros. </div>
<div id="1Pe_5_8" style="display:none;" class="ver_select"><b>1Pe 5:8</b>  Sed sobrios, y velad; porque vuestro adversario el diablo, cual león rugiente, anda alrededor buscando a quien devorar; </div>
<div id="1Pe_5_9" style="display:none;" class="ver_select"><b>1Pe 5:9</b>  al cual resistid firmes en la fe, sabiendo que las mismas aflicciones han de ser cumplidas en vuestros hermanos que están en el mundo. </div>
<div id="1Pe_5_10" style="display:none;" class="ver_select"><b>1Pe 5:10</b>  Y el Dios de toda gracia, que nos ha llamado a su gloria eterna por Cristo Jesús, después que hubiereis padecido un poco de tiempo, Él mismo os perfeccione, afirme, corrobore y establezca. </div>
<div id="1Pe_5_11" style="display:none;" class="ver_select"><b>1Pe 5:11</b>  A Él sea gloria e imperio para siempre. Amén. </div>
<div id="1Pe_5_12" style="display:none;" class="ver_select"><b>1Pe 5:12</b>  Os he escrito por conducto de Silvano, a quien considero un hermano fiel a vosotros, exhortándoos, y testificando que ésta es la verdadera gracia de Dios, en la cual estáis. </div>
<div id="1Pe_5_13" style="display:none;" class="ver_select"><b>1Pe 5:13</b>  La iglesia que está en Babilonia, juntamente elegida con vosotros, os saluda, y Marcos mi hijo. </div>
<div id="1Pe_5_14" style="display:none;" class="ver_select"><b>1Pe 5:14</b>  Saludaos unos a otros con ósculo de amor. Paz a todos vosotros los que estáis en Cristo Jesús. Amén. </div>
