<div id="2Co_1_1" style="display:none;" class="ver_select"><b>2Co 1:1</b>  Pablo, apóstol de Jesucristo por la voluntad de Dios, y nuestro hermano Timoteo, a la iglesia de Dios que está en Corinto, con todos los santos que están por toda Acaya: </div>
<div id="2Co_1_2" style="display:none;" class="ver_select"><b>2Co 1:2</b>  Gracia sea a vosotros, y paz de Dios nuestro Padre, y del Señor Jesucristo. </div>
<div id="2Co_1_3" style="display:none;" class="ver_select"><b>2Co 1:3</b>  Bendito sea el Dios y Padre de nuestro Señor Jesucristo, el Padre de misericordias, y el Dios de toda consolación, </div>
<div id="2Co_1_4" style="display:none;" class="ver_select"><b>2Co 1:4</b>  el cual nos consuela en todas nuestras tribulaciones, para que podamos nosotros consolar a los que están en cualquier angustia, con la consolación con que nosotros mismos somos consolados de Dios. </div>
<div id="2Co_1_5" style="display:none;" class="ver_select"><b>2Co 1:5</b>  Porque de la manera que abundan en nosotros las aflicciones de Cristo, así abunda también por Cristo nuestra consolación. </div>
<div id="2Co_1_6" style="display:none;" class="ver_select"><b>2Co 1:6</b>  Pues si somos atribulados, es por vuestra consolación y salvación; la cual es eficaz para soportar las mismas aflicciones que nosotros también padecemos; o si somos consolados, es por vuestra consolación y salvación. </div>
<div id="2Co_1_7" style="display:none;" class="ver_select"><b>2Co 1:7</b>  Y nuestra esperanza de vosotros es firme; sabiendo que como sois partícipes de las aflicciones, así también lo seréis de la consolación. </div>
<div id="2Co_1_8" style="display:none;" class="ver_select"><b>2Co 1:8</b>  Porque hermanos, no queremos que ignoréis acerca de nuestra tribulación que nos aconteció en Asia; que en sobremanera fuimos cargados sobre nuestras fuerzas, de tal manera que perdimos la esperanza aun de seguir con vida. </div>
<div id="2Co_1_9" style="display:none;" class="ver_select"><b>2Co 1:9</b>  Pero tuvimos en nosotros mismos sentencia de muerte, para que no confiásemos en nosotros mismos, sino en Dios que resucita a los muertos; </div>
<div id="2Co_1_10" style="display:none;" class="ver_select"><b>2Co 1:10</b>  el cual nos libró, y nos libra; y en quien confiamos que aún nos librará de tan grande muerte; </div>
<div id="2Co_1_11" style="display:none;" class="ver_select"><b>2Co 1:11</b>  ayudándonos vosotros también con oración por nosotros, para que por el don concedido a nosotros por medio de muchas personas, por muchas sean dadas gracias en nuestro favor. </div>
<div id="2Co_1_12" style="display:none;" class="ver_select"><b>2Co 1:12</b>  Porque ésta es nuestra gloria; el testimonio de nuestra conciencia, que con simplicidad y sinceridad de Dios, no con sabiduría carnal, sino por la gracia de Dios, nos hemos conducido en el mundo, y más abundantemente con vosotros. </div>
<div id="2Co_1_13" style="display:none;" class="ver_select"><b>2Co 1:13</b>  Porque no os escribimos otras cosas de las que leéis, o también reconocéis; y espero que aun hasta el fin las reconoceréis; </div>
<div id="2Co_1_14" style="display:none;" class="ver_select"><b>2Co 1:14</b>  como también en parte nos habéis reconocido, que somos vuestra gloria, así como también vosotros seréis la nuestra en el día del Señor Jesús. </div>
<div id="2Co_1_15" style="display:none;" class="ver_select"><b>2Co 1:15</b>  Y con esta confianza quise ir primero a vosotros, para que tuvieseis una segunda gracia; </div>
<div id="2Co_1_16" style="display:none;" class="ver_select"><b>2Co 1:16</b>  y de vosotros pasar a Macedonia, y de Macedonia venir otra vez a vosotros, y ser encaminado de vosotros a Judea. </div>
<div id="2Co_1_17" style="display:none;" class="ver_select"><b>2Co 1:17</b>  Así que, cuando me propuse esto, ¿usé quizá de ligereza? ¿O lo que me propongo, me propongo según la carne, para que haya en mí Sí, Sí, y No, No? </div>
<div id="2Co_1_18" style="display:none;" class="ver_select"><b>2Co 1:18</b>  Pero como Dios es fiel, nuestra palabra para con vosotros no fue Sí y No. </div>
<div id="2Co_1_19" style="display:none;" class="ver_select"><b>2Co 1:19</b>  Porque el Hijo de Dios, Jesucristo, que entre vosotros ha sido predicado por nosotros, por mí y Silvano y Timoteo, no ha sido Sí y No; mas ha sido Sí en Él. </div>
<div id="2Co_1_20" style="display:none;" class="ver_select"><b>2Co 1:20</b>  Porque todas las promesas de Dios son Sí en Él, y Amén en Él, por medio de nosotros, para la gloria de Dios. </div>
<div id="2Co_1_21" style="display:none;" class="ver_select"><b>2Co 1:21</b>  Y el que nos confirma con vosotros en Cristo, y el que nos ungió, es Dios; </div>
<div id="2Co_1_22" style="display:none;" class="ver_select"><b>2Co 1:22</b>  el cual también nos ha sellado, y nos ha dado las arras del Espíritu en nuestros corazones. </div>
<div id="2Co_1_23" style="display:none;" class="ver_select"><b>2Co 1:23</b>  Mas yo invoco a Dios por testigo sobre mi alma, que por ser indulgente con vosotros no he pasado todavía a Corinto. </div>
<div id="2Co_1_24" style="display:none;" class="ver_select"><b>2Co 1:24</b>  No que tengamos dominio sobre vuestra fe, mas somos ayudadores de vuestro gozo; porque por la fe estáis firmes. </div>
<div id="2Co_2_1" style="display:none;" class="ver_select"><b>2Co 2:1</b>  Esto, pues, determiné para conmigo, no venir otra vez a vosotros con tristeza. </div>
<div id="2Co_2_2" style="display:none;" class="ver_select"><b>2Co 2:2</b>  Porque si yo os contristo, ¿quién será luego el que me alegrará, sino aquel a quien yo contristare? </div>
<div id="2Co_2_3" style="display:none;" class="ver_select"><b>2Co 2:3</b>  Y esto mismo os escribí, para que cuando viniere no tenga tristeza de aquellos de quienes me debiera alegrar; confiando en vosotros todos que mi gozo es el de todos vosotros. </div>
<div id="2Co_2_4" style="display:none;" class="ver_select"><b>2Co 2:4</b>  Porque por la mucha tribulación y angustia del corazón os escribí con muchas lágrimas; no para que fueseis contristados, sino para que supieseis cuán grande amor tengo para con vosotros. </div>
<div id="2Co_2_5" style="display:none;" class="ver_select"><b>2Co 2:5</b>  Que si alguno ha causado tristeza, no me ha entristecido a mí sino en parte; para no sobrecargaros a todos vosotros. </div>
<div id="2Co_2_6" style="display:none;" class="ver_select"><b>2Co 2:6</b>  Bástele al tal el castigo que le fue impuesto por muchos; </div>
<div id="2Co_2_7" style="display:none;" class="ver_select"><b>2Co 2:7</b>  así que, al contrario, vosotros más bien debierais perdonarle y consolarle, para que el tal no sea consumido de demasiada tristeza. </div>
<div id="2Co_2_8" style="display:none;" class="ver_select"><b>2Co 2:8</b>  Por lo cual os ruego que confirméis vuestro amor para con él. </div>
<div id="2Co_2_9" style="display:none;" class="ver_select"><b>2Co 2:9</b>  Porque también por este fin os escribí, para saber la prueba de si vosotros sois obedientes en todo. </div>
<div id="2Co_2_10" style="display:none;" class="ver_select"><b>2Co 2:10</b>  Y al que vosotros perdonareis algo, yo también; porque si algo he perdonado, a quien lo he perdonado, por vosotros lo he hecho en la persona de Cristo; </div>
<div id="2Co_2_11" style="display:none;" class="ver_select"><b>2Co 2:11</b>  para que no nos gane Satanás; pues no ignoramos sus maquinaciones. </div>
<div id="2Co_2_12" style="display:none;" class="ver_select"><b>2Co 2:12</b>  Y cuando vine a Troas para predicar el evangelio de Cristo, y una puerta me fue abierta en el Señor, </div>
<div id="2Co_2_13" style="display:none;" class="ver_select"><b>2Co 2:13</b>  no tuve reposo en mi espíritu, por no haber hallado a Tito mi hermano; mas despidiéndome de ellos, partí para Macedonia. </div>
<div id="2Co_2_14" style="display:none;" class="ver_select"><b>2Co 2:14</b>  Mas a Dios gracias, el cual hace que siempre triunfemos en Cristo, y manifiesta la fragancia de su conocimiento por nosotros en todo lugar. </div>
<div id="2Co_2_15" style="display:none;" class="ver_select"><b>2Co 2:15</b>  Porque para Dios somos de Cristo grata fragancia en los que son salvos, y en los que se pierden; </div>
<div id="2Co_2_16" style="display:none;" class="ver_select"><b>2Co 2:16</b>  a éstos ciertamente olor de muerte para muerte; y a aquéllos fragancia de vida para vida. Y para estas cosas, ¿quién es suficiente? </div>
<div id="2Co_2_17" style="display:none;" class="ver_select"><b>2Co 2:17</b>  Porque no somos como muchos que adulteran la palabra de Dios; antes con sinceridad, como de parte de Dios, delante de Dios hablamos en Cristo. </div>
<div id="2Co_3_1" style="display:none;" class="ver_select"><b>2Co 3:1</b>  ¿Comenzamos otra vez a recomendarnos a nosotros mismos? ¿O tenemos necesidad como algunos, de cartas de recomendación para vosotros, o de recomendación de vosotros? </div>
<div id="2Co_3_2" style="display:none;" class="ver_select"><b>2Co 3:2</b>  Nuestra carta sois vosotros, escrita en nuestros corazones, sabida y leída de todos los hombres; </div>
<div id="2Co_3_3" style="display:none;" class="ver_select"><b>2Co 3:3</b>  siendo manifiesto que sois carta de Cristo ministrada por nosotros, escrita no con tinta, sino con el Espíritu del Dios vivo; no en tablas de piedra, sino en tablas de carne del corazón. </div>
<div id="2Co_3_4" style="display:none;" class="ver_select"><b>2Co 3:4</b>  Y tal confianza tenemos mediante Cristo para con Dios; </div>
<div id="2Co_3_5" style="display:none;" class="ver_select"><b>2Co 3:5</b>  no que seamos suficientes de nosotros mismos para pensar algo como de nosotros mismos, sino que nuestra suficiencia viene de Dios; </div>
<div id="2Co_3_6" style="display:none;" class="ver_select"><b>2Co 3:6</b>  el cual también nos ha hecho ministros suficientes del nuevo testamento; no de la letra, sino del espíritu; porque la letra mata, mas el espíritu vivifica. </div>
<div id="2Co_3_7" style="display:none;" class="ver_select"><b>2Co 3:7</b>  Y si el ministerio de muerte escrito y grabado en piedras fue glorioso, tanto que los hijos de Israel no podían fijar los ojos en el rostro de Moisés a causa de la gloria de su parecer, la cual había de fenecer, </div>
<div id="2Co_3_8" style="display:none;" class="ver_select"><b>2Co 3:8</b>  ¿cómo no será más glorioso el ministerio del espíritu? </div>
<div id="2Co_3_9" style="display:none;" class="ver_select"><b>2Co 3:9</b>  Porque si el ministerio de condenación fue glorioso, mucho más abundará en gloria el ministerio de la justificación. </div>
<div id="2Co_3_10" style="display:none;" class="ver_select"><b>2Co 3:10</b>  Porque aun lo que fue glorioso, no es glorioso en este respecto, en comparación a la gloria más excelente. </div>
<div id="2Co_3_11" style="display:none;" class="ver_select"><b>2Co 3:11</b>  Porque si lo que perece fue glorioso, mucho más glorioso será lo que permanece. </div>
<div id="2Co_3_12" style="display:none;" class="ver_select"><b>2Co 3:12</b>  Así que, teniendo tal esperanza, hablamos con mucha confianza; </div>
<div id="2Co_3_13" style="display:none;" class="ver_select"><b>2Co 3:13</b>  y no como Moisés, que ponía un velo sobre su rostro, para que los hijos de Israel no pusiesen los ojos en el fin de aquello que había de ser abolido. </div>
<div id="2Co_3_14" style="display:none;" class="ver_select"><b>2Co 3:14</b>  Pero sus mentes fueron cegadas; porque hasta el día de hoy cuando leen el antiguo testamento, permanece sin ser quitado el mismo velo, el cual Cristo abolió. </div>
<div id="2Co_3_15" style="display:none;" class="ver_select"><b>2Co 3:15</b>  Y aun hasta el día de hoy, cuando Moisés es leído, el velo está puesto sobre el corazón de ellos. </div>
<div id="2Co_3_16" style="display:none;" class="ver_select"><b>2Co 3:16</b>  Pero cuando se conviertan al Señor, el velo será quitado. </div>
<div id="2Co_3_17" style="display:none;" class="ver_select"><b>2Co 3:17</b>  Porque el Señor es el Espíritu; y donde está el Espíritu del Señor, allí hay libertad. </div>
<div id="2Co_3_18" style="display:none;" class="ver_select"><b>2Co 3:18</b>  Por tanto, nosotros todos, mirando con cara descubierta como en un espejo la gloria del Señor, somos transformados en la misma imagen, de gloria en gloria, como por el Espíritu del Señor. </div>
<div id="2Co_4_1" style="display:none;" class="ver_select"><b>2Co 4:1</b>  Por tanto, teniendo nosotros este ministerio según la misericordia que hemos recibido, no desmayamos; </div>
<div id="2Co_4_2" style="display:none;" class="ver_select"><b>2Co 4:2</b>  antes bien hemos renunciado a lo oculto y deshonesto, no andando con astucia, ni usando la palabra de Dios con engaño, sino que por la manifestación de la verdad, nos recomendamos a la conciencia de todo hombre delante de Dios. </div>
<div id="2Co_4_3" style="display:none;" class="ver_select"><b>2Co 4:3</b>  Que si nuestro evangelio está aún encubierto, para los que se pierden está encubierto; </div>
<div id="2Co_4_4" style="display:none;" class="ver_select"><b>2Co 4:4</b>  en los cuales el dios de este mundo cegó la mente de los incrédulos, para que no les resplandezca la luz del glorioso evangelio de Cristo, el cual es la imagen de Dios. </div>
<div id="2Co_4_5" style="display:none;" class="ver_select"><b>2Co 4:5</b>  Porque no nos predicamos a nosotros mismos, sino a Jesucristo el Señor; y nosotros vuestros siervos por Jesús. </div>
<div id="2Co_4_6" style="display:none;" class="ver_select"><b>2Co 4:6</b>  Porque Dios, que mandó que de las tinieblas resplandeciese la luz, es el que resplandeció en nuestros corazones, para iluminación del conocimiento de la gloria de Dios en la faz de Jesucristo. </div>
<div id="2Co_4_7" style="display:none;" class="ver_select"><b>2Co 4:7</b>  Pero tenemos este tesoro en vasos de barro, para que la excelencia del poder sea de Dios, y no de nosotros; </div>
<div id="2Co_4_8" style="display:none;" class="ver_select"><b>2Co 4:8</b>  Que estamos atribulados en todo, pero no angustiados; en apuros, pero no desesperados; </div>
<div id="2Co_4_9" style="display:none;" class="ver_select"><b>2Co 4:9</b>  perseguidos, pero no desamparados; derribados, pero no destruidos; </div>
<div id="2Co_4_10" style="display:none;" class="ver_select"><b>2Co 4:10</b>  llevando siempre por todas partes en el cuerpo la muerte del Señor Jesús, para que también la vida de Jesús se manifieste en nuestros cuerpos. </div>
<div id="2Co_4_11" style="display:none;" class="ver_select"><b>2Co 4:11</b>  Porque nosotros que vivimos, siempre estamos entregados a muerte por Jesús, para que también la vida de Jesús sea manifestada en nuestra carne mortal. </div>
<div id="2Co_4_12" style="display:none;" class="ver_select"><b>2Co 4:12</b>  De manera que la muerte obra en nosotros, y en vosotros la vida. </div>
<div id="2Co_4_13" style="display:none;" class="ver_select"><b>2Co 4:13</b>  Pero teniendo el mismo espíritu de fe, conforme a lo que está escrito: Creí, por lo cual también hablé; nosotros también creemos, por lo cual también hablamos; </div>
<div id="2Co_4_14" style="display:none;" class="ver_select"><b>2Co 4:14</b>  sabiendo que el que resucitó al Señor Jesús, a nosotros también nos resucitará por Jesús, y nos presentará con vosotros. </div>
<div id="2Co_4_15" style="display:none;" class="ver_select"><b>2Co 4:15</b>  Porque todas las cosas son hechas por amor a vosotros, para que la abundante gracia, mediante la acción de gracias de muchos, redunde para la gloria de Dios. </div>
<div id="2Co_4_16" style="display:none;" class="ver_select"><b>2Co 4:16</b>  Por tanto, no desmayamos; antes aunque este nuestro hombre exterior se va desgastando, el interior no obstante se renueva de día en día. </div>
<div id="2Co_4_17" style="display:none;" class="ver_select"><b>2Co 4:17</b>  Porque nuestra leve aflicción, la cual es momentánea, produce en nosotros un inmensurable y eterno peso de gloria; </div>
<div id="2Co_4_18" style="display:none;" class="ver_select"><b>2Co 4:18</b>  no mirando nosotros a las cosas que se ven, sino a las que no se ven; porque las cosas que se ven son temporales, mas las que no se ven son eternas. </div>
<div id="2Co_5_1" style="display:none;" class="ver_select"><b>2Co 5:1</b>  Porque sabemos que si nuestra casa terrenal, este tabernáculo, se deshiciere, tenemos de Dios un edificio, una casa no hecha de manos, eterna, en el cielo. </div>
<div id="2Co_5_2" style="display:none;" class="ver_select"><b>2Co 5:2</b>  Y por esto también gemimos, deseando ser revestidos de aquella nuestra habitación celestial; </div>
<div id="2Co_5_3" style="display:none;" class="ver_select"><b>2Co 5:3</b>  y si así estamos vestidos, no seremos hallados desnudos. </div>
<div id="2Co_5_4" style="display:none;" class="ver_select"><b>2Co 5:4</b>  Porque nosotros que estamos en este tabernáculo gemimos con angustia; porque no quisiéramos ser desnudados, sino revestidos, para que lo mortal sea absorbido por la vida. </div>
<div id="2Co_5_5" style="display:none;" class="ver_select"><b>2Co 5:5</b>  Mas el que nos hizo para esto mismo es Dios, el cual también nos ha dado las arras del Espíritu. </div>
<div id="2Co_5_6" style="display:none;" class="ver_select"><b>2Co 5:6</b>  Por tanto vivimos confiados siempre, sabiendo que entre tanto que estamos en el cuerpo, ausentes estamos del Señor </div>
<div id="2Co_5_7" style="display:none;" class="ver_select"><b>2Co 5:7</b>  (porque por fe andamos, no por vista): </div>
<div id="2Co_5_8" style="display:none;" class="ver_select"><b>2Co 5:8</b>  Estamos confiados, y más quisiéramos estar ausentes del cuerpo, y presentes con el Señor. </div>
<div id="2Co_5_9" style="display:none;" class="ver_select"><b>2Co 5:9</b>  Por tanto procuramos también, o presentes, o ausentes, serle agradables. </div>
<div id="2Co_5_10" style="display:none;" class="ver_select"><b>2Co 5:10</b>  Porque es menester que todos nosotros comparezcamos ante el tribunal de Cristo, para que cada uno reciba según lo que haya hecho mientras estaba en el cuerpo, ya sea bueno o sea malo. </div>
<div id="2Co_5_11" style="display:none;" class="ver_select"><b>2Co 5:11</b>  Conociendo, pues, el temor del Señor, persuadimos a los hombres, mas a Dios somos manifiestos; y espero que también en vuestras conciencias seamos manifiestos. </div>
<div id="2Co_5_12" style="display:none;" class="ver_select"><b>2Co 5:12</b>  Pues no nos recomendamos otra vez a vosotros, sino os damos ocasión de gloriaros por nosotros, para que tengáis qué responder a los que se glorían en la apariencia y no en el corazón. </div>
<div id="2Co_5_13" style="display:none;" class="ver_select"><b>2Co 5:13</b>  Porque si estamos locos, es para Dios; y si somos cuerdos, es para vosotros. </div>
<div id="2Co_5_14" style="display:none;" class="ver_select"><b>2Co 5:14</b>  Porque el amor de Cristo nos constriñe, pensando esto: Que si uno murió por todos, luego todos murieron; </div>
<div id="2Co_5_15" style="display:none;" class="ver_select"><b>2Co 5:15</b>  y por todos murió, para que los que viven, ya no vivan para sí, sino para Aquél que murió y resucitó por ellos. </div>
<div id="2Co_5_16" style="display:none;" class="ver_select"><b>2Co 5:16</b>  De manera que nosotros de aquí en adelante a nadie conocemos según la carne; y aun si a Cristo conocimos según la carne, ahora ya no le conocemos así. </div>
<div id="2Co_5_17" style="display:none;" class="ver_select"><b>2Co 5:17</b>  De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas. </div>
<div id="2Co_5_18" style="display:none;" class="ver_select"><b>2Co 5:18</b>  Y todo esto proviene de Dios, quien nos reconcilió consigo mismo por Jesucristo; y nos dio el ministerio de la reconciliación. </div>
<div id="2Co_5_19" style="display:none;" class="ver_select"><b>2Co 5:19</b>  De manera que Dios estaba en Cristo reconciliando consigo al mundo, no imputándole sus pecados, y nos encomendó a nosotros la palabra de la reconciliación. </div>
<div id="2Co_5_20" style="display:none;" class="ver_select"><b>2Co 5:20</b>  Así que, somos embajadores de Cristo, como si Dios rogase por medio de nosotros; os rogamos en nombre de Cristo: Reconciliaos con Dios. </div>
<div id="2Co_5_21" style="display:none;" class="ver_select"><b>2Co 5:21</b>  Al que no conoció pecado, lo hizo pecado por nosotros, para que nosotros fuésemos hechos justicia de Dios en Él. </div>
<div id="2Co_6_1" style="display:none;" class="ver_select"><b>2Co 6:1</b>  Así, pues, nosotros, como sus colaboradores, os exhortamos también a que no recibáis en vano la gracia de Dios. </div>
<div id="2Co_6_2" style="display:none;" class="ver_select"><b>2Co 6:2</b>  Porque dice: En tiempo aceptable te he oído, y en día de salvación te he socorrido. He aquí ahora el tiempo aceptable, he aquí ahora el día de salvación. </div>
<div id="2Co_6_3" style="display:none;" class="ver_select"><b>2Co 6:3</b>  No dando a nadie ninguna ocasión de tropiezo, para que el ministerio no sea vituperado; </div>
<div id="2Co_6_4" style="display:none;" class="ver_select"><b>2Co 6:4</b>  antes, aprobándonos en todo como ministros de Dios, en mucha paciencia, en tribulaciones, en necesidades, en angustias; </div>
<div id="2Co_6_5" style="display:none;" class="ver_select"><b>2Co 6:5</b>  en azotes, en cárceles, en tumultos, en trabajos, en vigilias, en ayunos; </div>
<div id="2Co_6_6" style="display:none;" class="ver_select"><b>2Co 6:6</b>  en pureza, en ciencia, en longanimidad, en bondad, en el Espíritu Santo, en amor no fingido; </div>
<div id="2Co_6_7" style="display:none;" class="ver_select"><b>2Co 6:7</b>  en palabra de verdad, en poder de Dios, con armas de justicia a derecha e izquierda; </div>
<div id="2Co_6_8" style="display:none;" class="ver_select"><b>2Co 6:8</b>  por honra y por deshonra, por mala fama, y por buena fama; como engañadores, pero veraces; </div>
<div id="2Co_6_9" style="display:none;" class="ver_select"><b>2Co 6:9</b>  como desconocidos, pero bien conocidos; como moribundos, mas he aquí vivimos; como castigados, mas no muertos; </div>
<div id="2Co_6_10" style="display:none;" class="ver_select"><b>2Co 6:10</b>  como entristecidos, mas siempre gozosos; como pobres, mas enriqueciendo a muchos; como no teniendo nada, mas poseyéndolo todo. </div>
<div id="2Co_6_11" style="display:none;" class="ver_select"><b>2Co 6:11</b>  Nuestra boca está abierta a vosotros, oh corintios; nuestro corazón se ha ensanchado. </div>
<div id="2Co_6_12" style="display:none;" class="ver_select"><b>2Co 6:12</b>  No estáis estrechos en nosotros, mas estáis estrechos en vuestras propias entrañas. </div>
<div id="2Co_6_13" style="display:none;" class="ver_select"><b>2Co 6:13</b>  Pues, para corresponder del mismo modo (como a hijos hablo), ensanchaos también vosotros. </div>
<div id="2Co_6_14" style="display:none;" class="ver_select"><b>2Co 6:14</b>  No os unáis en yugo desigual con los incrédulos; porque ¿qué compañerismo tiene la justicia con la injusticia? ¿Y qué comunión la luz con las tinieblas? </div>
<div id="2Co_6_15" style="display:none;" class="ver_select"><b>2Co 6:15</b>  ¿Y qué concordia Cristo con Belial? ¿O qué parte el creyente con el incrédulo? </div>
<div id="2Co_6_16" style="display:none;" class="ver_select"><b>2Co 6:16</b>  ¿Y qué concierto tiene el templo de Dios con los ídolos? Porque vosotros sois el templo del Dios viviente, como Dios dijo: Habitaré y andaré entre ellos; y seré su Dios, y ellos serán mi pueblo. </div>
<div id="2Co_6_17" style="display:none;" class="ver_select"><b>2Co 6:17</b>  Por lo cual salid de en medio de ellos, y apartaos, dice el Señor, y no toquéis lo inmundo; y yo os recibiré, </div>
<div id="2Co_6_18" style="display:none;" class="ver_select"><b>2Co 6:18</b>  y seré Padre a vosotros, y vosotros me seréis hijos e hijas, dice el Señor Todopoderoso. </div>
<div id="2Co_7_1" style="display:none;" class="ver_select"><b>2Co 7:1</b>  Así que, amados, teniendo tales promesas, limpiémonos de toda inmundicia de la carne y del espíritu, perfeccionando la santidad en el temor de Dios. </div>
<div id="2Co_7_2" style="display:none;" class="ver_select"><b>2Co 7:2</b>  Admitidnos; a nadie hemos dañado, a nadie hemos corrompido, a nadie hemos defraudado. </div>
<div id="2Co_7_3" style="display:none;" class="ver_select"><b>2Co 7:3</b>  No lo digo para condenaros; porque ya he dicho antes, que estáis en nuestros corazones, para morir y para vivir juntamente. </div>
<div id="2Co_7_4" style="display:none;" class="ver_select"><b>2Co 7:4</b>  Grande es mi franqueza para con vosotros; grande es mi gloria de vosotros; lleno estoy de consolación, sobreabundo de gozo en todas nuestras tribulaciones. </div>
<div id="2Co_7_5" style="display:none;" class="ver_select"><b>2Co 7:5</b>  Porque cuando vinimos a Macedonia, ningún reposo tuvo nuestra carne; antes en todo fuimos atribulados; de fuera, contiendas; de dentro, temores. </div>
<div id="2Co_7_6" style="display:none;" class="ver_select"><b>2Co 7:6</b>  Mas Dios, que consuela a los abatidos, nos consoló con la venida de Tito; </div>
<div id="2Co_7_7" style="display:none;" class="ver_select"><b>2Co 7:7</b>  y no sólo con su venida, sino también con la consolación con que él fue consolado de vosotros, haciéndonos saber vuestro gran deseo, vuestro llanto, vuestro celo por mí, para que así yo más me regocijara. </div>
<div id="2Co_7_8" style="display:none;" class="ver_select"><b>2Co 7:8</b>  Porque aunque os contristé con la carta, no me arrepiento, bien que me arrepentí; porque veo que aquella carta, aunque por un poco de tiempo, os contristó. </div>
<div id="2Co_7_9" style="display:none;" class="ver_select"><b>2Co 7:9</b>  Ahora me gozo, no porque hayáis sido contristados, sino porque fuisteis contristados para arrepentimiento; porque habéis sido contristados según Dios, para que ninguna pérdida padecieseis por nosotros. </div>
<div id="2Co_7_10" style="display:none;" class="ver_select"><b>2Co 7:10</b>  Porque la tristeza que es según Dios produce arrepentimiento para salvación, de que no hay que arrepentirse; mas la tristeza del mundo produce muerte. </div>
<div id="2Co_7_11" style="display:none;" class="ver_select"><b>2Co 7:11</b>  Porque he aquí, esto mismo que os contristó según Dios; ¡cuánta solicitud ha obrado en vosotros, y qué defensa, y qué indignación, y qué temor, y qué gran deseo, y qué celo, y aun vindicación! En todo os habéis mostrado limpios en este asunto. </div>
<div id="2Co_7_12" style="display:none;" class="ver_select"><b>2Co 7:12</b>  Así que, aunque os escribí, no fue por causa del que hizo la injuria, ni por causa del que padeció la injuria, sino para que os fuese manifiesta nuestra solicitud que tenemos por vosotros delante de Dios. </div>
<div id="2Co_7_13" style="display:none;" class="ver_select"><b>2Co 7:13</b>  Por tanto, tomamos consolación de vuestra consolación; pero mucho más nos gozamos por el gozo de Tito, de que haya sido recreado su espíritu por todos vosotros. </div>
<div id="2Co_7_14" style="display:none;" class="ver_select"><b>2Co 7:14</b>  Que si de algo me he gloriado con él acerca de vosotros, no me avergüenzo; pues como os hemos hablado todo con verdad, así también nuestra gloria delante de Tito fue hallada verdadera. </div>
<div id="2Co_7_15" style="display:none;" class="ver_select"><b>2Co 7:15</b>  Y su entrañable afecto es más abundante para con vosotros, cuando se acuerda de la obediencia de todos vosotros, de cómo lo recibisteis con temor y temblor. </div>
<div id="2Co_7_16" style="display:none;" class="ver_select"><b>2Co 7:16</b>  Me gozo de que en todo tengo confianza en vosotros. </div>
<div id="2Co_8_1" style="display:none;" class="ver_select"><b>2Co 8:1</b>  Asimismo, hermanos, os hacemos saber la gracia de Dios que ha sido dada a las iglesias de Macedonia; </div>
<div id="2Co_8_2" style="display:none;" class="ver_select"><b>2Co 8:2</b>  que en grande prueba de tribulación, la abundancia de su gozo y su profunda pobreza abundaron en riquezas de su generosidad. </div>
<div id="2Co_8_3" style="display:none;" class="ver_select"><b>2Co 8:3</b>  Porque de su voluntad han dado conforme a sus fuerzas, yo testifico, y aun más allá de sus fuerzas; </div>
<div id="2Co_8_4" style="display:none;" class="ver_select"><b>2Co 8:4</b>  pidiéndonos con muchos ruegos que aceptásemos la ofrenda y la comunicación del servicio para los santos. </div>
<div id="2Co_8_5" style="display:none;" class="ver_select"><b>2Co 8:5</b>  Y esto hicieron, no como lo esperábamos, sino que primero se dieron a sí mismos al Señor, y a nosotros por la voluntad de Dios. </div>
<div id="2Co_8_6" style="display:none;" class="ver_select"><b>2Co 8:6</b>  De manera que exhortamos a Tito, que como comenzó, así también acabe esta gracia entre vosotros también. </div>
<div id="2Co_8_7" style="display:none;" class="ver_select"><b>2Co 8:7</b>  Por tanto, como en todo abundáis, en fe, y en palabra, y en ciencia, y en toda solicitud, y en vuestro amor para con nosotros, mirad que también abundéis en esta gracia. </div>
<div id="2Co_8_8" style="display:none;" class="ver_select"><b>2Co 8:8</b>  No hablo como quien manda, sino por causa de la diligencia de otros, y para probar la sinceridad de vuestro amor. </div>
<div id="2Co_8_9" style="display:none;" class="ver_select"><b>2Co 8:9</b>  Porque ya sabéis la gracia de nuestro Señor Jesucristo, que por amor de vosotros, siendo rico se hizo pobre; para que vosotros con su pobreza fueseis enriquecidos. </div>
<div id="2Co_8_10" style="display:none;" class="ver_select"><b>2Co 8:10</b>  Y en esto doy mi consejo; porque esto os conviene a vosotros, que comenzasteis antes, no sólo a hacerlo, sino también a quererlo, desde el año pasado. </div>
<div id="2Co_8_11" style="display:none;" class="ver_select"><b>2Co 8:11</b>  Ahora, pues, llevad también a cabo el hecho, para que como estuvisteis prestos a querer, así también lo estéis en cumplir conforme a lo que tenéis. </div>
<div id="2Co_8_12" style="display:none;" class="ver_select"><b>2Co 8:12</b>  Porque si primero hay la disposición, será acepta según lo que uno tiene, no según lo que no tiene. </div>
<div id="2Co_8_13" style="display:none;" class="ver_select"><b>2Co 8:13</b>  Pero no digo esto para que haya abundancia para otros, y para vosotros escasez; </div>
<div id="2Co_8_14" style="display:none;" class="ver_select"><b>2Co 8:14</b>  sino para que con igualdad, ahora en este tiempo, vuestra abundancia supla lo que a ellos falta, para que también la abundancia de ellos supla lo que a vosotros falta, de modo que haya igualdad; </div>
<div id="2Co_8_15" style="display:none;" class="ver_select"><b>2Co 8:15</b>  como está escrito: El que recogió mucho, no tuvo más; y el que poco, no tuvo menos. </div>
<div id="2Co_8_16" style="display:none;" class="ver_select"><b>2Co 8:16</b>  Mas gracias sean dadas a Dios, que puso en el corazón de Tito la misma solicitud por vosotros. </div>
<div id="2Co_8_17" style="display:none;" class="ver_select"><b>2Co 8:17</b>  Pues a la verdad aceptó la exhortación; y estando también muy solícito, de su voluntad partió para ir a vosotros. </div>
<div id="2Co_8_18" style="display:none;" class="ver_select"><b>2Co 8:18</b>  Y enviamos juntamente con él al hermano cuya alabanza en el evangelio es por todas las iglesias; </div>
<div id="2Co_8_19" style="display:none;" class="ver_select"><b>2Co 8:19</b>  y no sólo esto, sino también fue escogido por las iglesias para viajar con nosotros con esta gracia, que es administrada por nosotros para gloria del Señor mismo, y para demostrar vuestra buena disposición; </div>
<div id="2Co_8_20" style="display:none;" class="ver_select"><b>2Co 8:20</b>  evitando que nadie nos difame en esta abundancia que administramos; </div>
<div id="2Co_8_21" style="display:none;" class="ver_select"><b>2Co 8:21</b>  procurando hacer lo honesto, no sólo delante del Señor, sino también delante de los hombres. </div>
<div id="2Co_8_22" style="display:none;" class="ver_select"><b>2Co 8:22</b>  Y enviamos con ellos a nuestro hermano, la diligencia del cual hemos comprobado muchas veces en muchas cosas, y ahora mucho más diligente por la mucha confianza que tengo en vosotros. </div>
<div id="2Co_8_23" style="display:none;" class="ver_select"><b>2Co 8:23</b>  Si alguno preguntare acerca de Tito, él es mi compañero y colaborador para con vosotros; o acerca de nuestros hermanos; ellos son mensajeros de las iglesias, y la gloria de Cristo. </div>
<div id="2Co_8_24" style="display:none;" class="ver_select"><b>2Co 8:24</b>  Mostrad, pues, para con ellos y ante las iglesias la prueba de vuestro amor, y de nuestro gloriarnos acerca de vosotros. </div>
<div id="2Co_9_1" style="display:none;" class="ver_select"><b>2Co 9:1</b>  Pero en cuanto a la suministración para los santos, por demás me es escribiros; </div>
<div id="2Co_9_2" style="display:none;" class="ver_select"><b>2Co 9:2</b>  pues conozco vuestra buena disposición, de la cual me glorío entre los de Macedonia, que Acaya está preparada desde el año pasado; y vuestro celo ha estimulado a muchos. </div>
<div id="2Co_9_3" style="display:none;" class="ver_select"><b>2Co 9:3</b>  Mas he enviado a los hermanos, para que nuestra gloria de vosotros no sea vana en esta parte; para que, como lo he dicho, estéis preparados; </div>
<div id="2Co_9_4" style="display:none;" class="ver_select"><b>2Co 9:4</b>  no sea que si vinieren conmigo los de Macedonia, y os hallaren desprevenidos, nos avergoncemos nosotros, por no decir vosotros, de este firme gloriar. </div>
<div id="2Co_9_5" style="display:none;" class="ver_select"><b>2Co 9:5</b>  Por tanto, consideré necesario exhortar a los hermanos a que fuesen antes a vosotros, y preparasen primero vuestra bendición antes prometida para que esté preparada como de bendición, y no como de mezquindad. </div>
<div id="2Co_9_6" style="display:none;" class="ver_select"><b>2Co 9:6</b>  Pero esto digo: El que siembra escasamente, también segará escasamente; y el que siembra abundantemente, abundantemente también segará. </div>
<div id="2Co_9_7" style="display:none;" class="ver_select"><b>2Co 9:7</b>  Cada uno dé como propuso en su corazón; no con tristeza, o por necesidad, porque Dios ama al dador alegre. </div>
<div id="2Co_9_8" style="display:none;" class="ver_select"><b>2Co 9:8</b>  Y poderoso es Dios para hacer que abunde en vosotros toda gracia; a fin de que, teniendo siempre toda suficiencia en todas las cosas, abundéis para toda buena obra; </div>
<div id="2Co_9_9" style="display:none;" class="ver_select"><b>2Co 9:9</b>  como está escrito: Esparció, dio a los pobres: Su justicia permanece para siempre. </div>
<div id="2Co_9_10" style="display:none;" class="ver_select"><b>2Co 9:10</b>  Y el que da semilla al que siembra, también dará pan para comer, y multiplicará vuestra sementera, y aumentará los frutos de vuestra justicia; </div>
<div id="2Co_9_11" style="display:none;" class="ver_select"><b>2Co 9:11</b>  para que enriquecidos en todo abundéis en toda liberalidad, la cual produce por medio de nosotros agradecimiento a Dios. </div>
<div id="2Co_9_12" style="display:none;" class="ver_select"><b>2Co 9:12</b>  Porque la suministración de este servicio, suple no sólo lo que a los santos falta, sino también abunda en muchas acciones de gracias a Dios; </div>
<div id="2Co_9_13" style="display:none;" class="ver_select"><b>2Co 9:13</b>  Pues por la experiencia de esta suministración glorifican a Dios por la obediencia que profesáis al evangelio de Cristo, y por vuestra liberal contribución para ellos y para todos; </div>
<div id="2Co_9_14" style="display:none;" class="ver_select"><b>2Co 9:14</b>  y por la oración de ellos a favor vuestro, los cuales os quieren a causa de la supereminente gracia de Dios en vosotros. </div>
<div id="2Co_9_15" style="display:none;" class="ver_select"><b>2Co 9:15</b>  Gracias a Dios por su don inefable. </div>
<div id="2Co_10_1" style="display:none;" class="ver_select"><b>2Co 10:1</b>  Y yo, Pablo mismo, os ruego por la mansedumbre y bondad de Cristo; yo que estando presente soy humilde entre vosotros, mas ausente soy osado para con vosotros; </div>
<div id="2Co_10_2" style="display:none;" class="ver_select"><b>2Co 10:2</b>  ruego, pues, que cuando estuviere presente, no tenga que ser atrevido con la confianza con que pienso ser osado contra algunos, que nos tienen como si anduviésemos según la carne. </div>
<div id="2Co_10_3" style="display:none;" class="ver_select"><b>2Co 10:3</b>  Pues aunque andamos en la carne, no militamos según la carne; </div>
<div id="2Co_10_4" style="display:none;" class="ver_select"><b>2Co 10:4</b>  porque las armas de nuestra milicia no son carnales, sino poderosas en Dios para la destrucción de fortalezas; </div>
<div id="2Co_10_5" style="display:none;" class="ver_select"><b>2Co 10:5</b>  derribando argumentos y toda altivez que se levanta contra el conocimiento de Dios, y trayendo cautivo todo pensamiento a la obediencia de Cristo; </div>
<div id="2Co_10_6" style="display:none;" class="ver_select"><b>2Co 10:6</b>  y estando prestos para castigar toda desobediencia, cuando vuestra obediencia fuere perfecta. </div>
<div id="2Co_10_7" style="display:none;" class="ver_select"><b>2Co 10:7</b>  ¿Miráis las cosas según la apariencia? Si alguno está confiado en sí mismo que es de Cristo, esto también piense por sí mismo, que como él es de Cristo, así también nosotros somos de Cristo. </div>
<div id="2Co_10_8" style="display:none;" class="ver_select"><b>2Co 10:8</b>  Porque aunque me gloríe algo más de nuestra autoridad, la cual el Señor nos dio para edificación y no para vuestra destrucción, no me avergonzaré; </div>
<div id="2Co_10_9" style="display:none;" class="ver_select"><b>2Co 10:9</b>  para que no parezca como que os quiero amedrentar por cartas. </div>
<div id="2Co_10_10" style="display:none;" class="ver_select"><b>2Co 10:10</b>  Porque a la verdad, dicen: Sus cartas son gravosas y fuertes; mas su presencia corporal es débil, y su palabra es menospreciable. </div>
<div id="2Co_10_11" style="display:none;" class="ver_select"><b>2Co 10:11</b>  Esto piense el tal, que como somos en la palabra por carta estando ausentes, tales seremos también de hecho estando presentes. </div>
<div id="2Co_10_12" style="display:none;" class="ver_select"><b>2Co 10:12</b>  Porque no osamos contarnos, o compararnos con algunos que se alaban a sí mismos; mas ellos, midiéndose a sí mismos por sí mismos, y comparándose consigo mismos, no son sabios. </div>
<div id="2Co_10_13" style="display:none;" class="ver_select"><b>2Co 10:13</b>  Mas nosotros, no nos gloriaremos desmedidamente, sino conforme a la medida de la regla que Dios nos dio por medida, para llegar aun hasta vosotros. </div>
<div id="2Co_10_14" style="display:none;" class="ver_select"><b>2Co 10:14</b>  Porque no nos extendemos más de nuestra medida, como si no alcanzásemos hasta vosotros; porque también hasta vosotros hemos llegado con el evangelio de Cristo. </div>
<div id="2Co_10_15" style="display:none;" class="ver_select"><b>2Co 10:15</b>  No gloriándonos desmedidamente en trabajos ajenos; mas teniendo esperanza de que cuando vuestra fe crezca, seremos mucho más engrandecidos entre vosotros, conforme a nuestra regla. </div>
<div id="2Co_10_16" style="display:none;" class="ver_select"><b>2Co 10:16</b>  Para predicar el evangelio en las regiones más allá de vosotros, sin entrar en el campo de otro para gloriarnos en lo que ya estaba preparado. </div>
<div id="2Co_10_17" style="display:none;" class="ver_select"><b>2Co 10:17</b>  Mas el que se gloría, gloríese en el Señor. </div>
<div id="2Co_10_18" style="display:none;" class="ver_select"><b>2Co 10:18</b>  Porque no el que se alaba a sí mismo, es aprobado; sino el que el Señor alaba. </div>
<div id="2Co_11_1" style="display:none;" class="ver_select"><b>2Co 11:1</b>  ¡Quiera Dios que toleraseis un poco mi locura! En verdad, toleradme. </div>
<div id="2Co_11_2" style="display:none;" class="ver_select"><b>2Co 11:2</b>  Porque os celo con celo de Dios; porque os he desposado a un esposo, para presentaros como una virgen pura a Cristo. </div>
<div id="2Co_11_3" style="display:none;" class="ver_select"><b>2Co 11:3</b>  Mas temo que en alguna manera, como la serpiente engañó a Eva con su astucia, así sean corrompidas vuestras mentes, de la simplicidad que es en Cristo. </div>
<div id="2Co_11_4" style="display:none;" class="ver_select"><b>2Co 11:4</b>  Porque si alguno viene y predica otro Jesús que el que os hemos predicado, o recibís otro espíritu del que habéis recibido, u otro evangelio del que habéis aceptado, bien lo toleráis. </div>
<div id="2Co_11_5" style="display:none;" class="ver_select"><b>2Co 11:5</b>  Mas yo pienso que en nada he sido inferior a aquellos grandes apóstoles. </div>
<div id="2Co_11_6" style="display:none;" class="ver_select"><b>2Co 11:6</b>  Porque aunque soy rudo en la palabra, no así en el conocimiento; y en todo hemos sido enteramente manifiestos entre vosotros. </div>
<div id="2Co_11_7" style="display:none;" class="ver_select"><b>2Co 11:7</b>  ¿Acaso pequé humillándome a mí mismo (para que vosotros fueseis ensalzados), porque os he predicado el evangelio de Dios de balde? </div>
<div id="2Co_11_8" style="display:none;" class="ver_select"><b>2Co 11:8</b>  He despojado a otras iglesias, tomando salario de ellas, para serviros a vosotros. </div>
<div id="2Co_11_9" style="display:none;" class="ver_select"><b>2Co 11:9</b>  Y estando con vosotros y teniendo necesidad, a ninguno fui carga; porque lo que me faltaba, lo suplieron los hermanos que vinieron de Macedonia; y en todo me guardé de seros carga, y me guardaré. </div>
<div id="2Co_11_10" style="display:none;" class="ver_select"><b>2Co 11:10</b>  Como la verdad de Cristo está en mí; nadie me impedirá esta gloria en las regiones de Acaya. </div>
<div id="2Co_11_11" style="display:none;" class="ver_select"><b>2Co 11:11</b>  ¿Por qué? ¿Porque no os amo? Dios lo sabe. </div>
<div id="2Co_11_12" style="display:none;" class="ver_select"><b>2Co 11:12</b>  Mas lo que hago, haré aún, para cortar la ocasión de aquellos que la desean, a fin de que en aquello que se glorían, sean hallados semejantes a nosotros. </div>
<div id="2Co_11_13" style="display:none;" class="ver_select"><b>2Co 11:13</b>  Porque éstos son falsos apóstoles, obreros fraudulentos, disfrazándose como apóstoles de Cristo. </div>
<div id="2Co_11_14" style="display:none;" class="ver_select"><b>2Co 11:14</b>  Y no es de maravillarse, porque el mismo Satanás se disfraza como ángel de luz. </div>
<div id="2Co_11_15" style="display:none;" class="ver_select"><b>2Co 11:15</b>  Así que, no es gran cosa si también sus ministros se disfrazan como ministros de justicia; cuyo fin será conforme a sus obras. </div>
<div id="2Co_11_16" style="display:none;" class="ver_select"><b>2Co 11:16</b>  Otra vez digo: Que nadie me tenga por loco; de otra manera, recibidme aun como a loco, para que me gloríe yo un poquito. </div>
<div id="2Co_11_17" style="display:none;" class="ver_select"><b>2Co 11:17</b>  Lo que hablo, no lo hablo según el Señor, sino como en locura, con esta confianza de gloria. </div>
<div id="2Co_11_18" style="display:none;" class="ver_select"><b>2Co 11:18</b>  Puesto que muchos se glorían según la carne, también yo me gloriaré. </div>
<div id="2Co_11_19" style="display:none;" class="ver_select"><b>2Co 11:19</b>  Porque de buena gana toleráis a los necios, siendo vosotros sabios: </div>
<div id="2Co_11_20" style="display:none;" class="ver_select"><b>2Co 11:20</b>  Porque toleráis si alguno os pone en servidumbre, si alguno os devora, si alguno toma de vosotros, si alguno se ensalza, si alguno os hiere en la cara. </div>
<div id="2Co_11_21" style="display:none;" class="ver_select"><b>2Co 11:21</b>  Lo digo en cuanto a la afrenta, como si nosotros hubiésemos sido débiles. Pero en lo que otro tuviere osadía (hablo con locura), también yo tengo osadía. </div>
<div id="2Co_11_22" style="display:none;" class="ver_select"><b>2Co 11:22</b>  ¿Son hebreos? Yo también. ¿Son israelitas? Yo también. ¿Son simiente de Abraham? También yo. </div>
<div id="2Co_11_23" style="display:none;" class="ver_select"><b>2Co 11:23</b>  ¿Son ministros de Cristo? (como poco sabio hablo) Yo más; en trabajos más abundante; en azotes sin medida; en cárceles más; en peligros de muerte muchas veces. </div>
<div id="2Co_11_24" style="display:none;" class="ver_select"><b>2Co 11:24</b>  De los judíos cinco veces he recibido cuarenta azotes menos uno. </div>
<div id="2Co_11_25" style="display:none;" class="ver_select"><b>2Co 11:25</b>  Tres veces fui azotado con varas; una vez apedreado; tres veces padecí naufragio; una noche y un día estuve en las profundidades; </div>
<div id="2Co_11_26" style="display:none;" class="ver_select"><b>2Co 11:26</b>  en jornadas muchas veces; peligros de ríos, peligros de ladrones, peligros de los de mi nación, peligros entre los gentiles, peligros en la ciudad, peligros en el desierto, peligros en el mar, peligros entre falsos hermanos; </div>
<div id="2Co_11_27" style="display:none;" class="ver_select"><b>2Co 11:27</b>  en trabajo y fatiga, en muchas vigilias, en hambre y sed, en muchos ayunos, en frío y en desnudez. </div>
<div id="2Co_11_28" style="display:none;" class="ver_select"><b>2Co 11:28</b>  Además de esto, lo que sobre mí se agolpa cada día, la carga de todas las iglesias. </div>
<div id="2Co_11_29" style="display:none;" class="ver_select"><b>2Co 11:29</b>  ¿Quién enferma, y yo no enfermo? ¿A quién se le hace caer, y yo no me enfurezco? </div>
<div id="2Co_11_30" style="display:none;" class="ver_select"><b>2Co 11:30</b>  Si es necesario gloriarme, me gloriaré en mis flaquezas. </div>
<div id="2Co_11_31" style="display:none;" class="ver_select"><b>2Co 11:31</b>  El Dios y Padre de nuestro Señor Jesucristo, que es bendito por siempre, sabe que no miento. </div>
<div id="2Co_11_32" style="display:none;" class="ver_select"><b>2Co 11:32</b>  En Damasco, el gobernador bajo el rey Aretas guardaba la ciudad de los damascenos para prenderme; </div>
<div id="2Co_11_33" style="display:none;" class="ver_select"><b>2Co 11:33</b>  y fui descolgado del muro en un canasto por una ventana, y escapé de sus manos. </div>
<div id="2Co_12_1" style="display:none;" class="ver_select"><b>2Co 12:1</b>  Ciertamente no me conviene gloriarme; mas vendré a las visiones y a las revelaciones del Señor. </div>
<div id="2Co_12_2" style="display:none;" class="ver_select"><b>2Co 12:2</b>  Conozco a un hombre en Cristo, que hace catorce años (si en el cuerpo, no lo sé; si fuera del cuerpo, no lo sé: Dios lo sabe) fue arrebatado hasta el tercer cielo. </div>
<div id="2Co_12_3" style="display:none;" class="ver_select"><b>2Co 12:3</b>  Y conozco al tal hombre (si en el cuerpo, o fuera del cuerpo, no lo sé; Dios lo sabe), </div>
<div id="2Co_12_4" style="display:none;" class="ver_select"><b>2Co 12:4</b>  que fue arrebatado al paraíso, donde oyó palabras inefables, que al hombre no le es lícito expresar. </div>
<div id="2Co_12_5" style="display:none;" class="ver_select"><b>2Co 12:5</b>  De tal hombre me gloriaré, mas de mí mismo no me gloriaré, sino en mis debilidades. </div>
<div id="2Co_12_6" style="display:none;" class="ver_select"><b>2Co 12:6</b>  Por lo cual si quisiera gloriarme, no sería insensato; porque diría verdad; pero lo dejo, para que nadie piense de mí más de lo que en mí ve, u oye de mí. </div>
<div id="2Co_12_7" style="display:none;" class="ver_select"><b>2Co 12:7</b>  Y para que no me enaltezca desmedidamente por la grandeza de las revelaciones, me es dado un aguijón en mi carne, un mensajero de Satanás que me abofetee, para que no me enaltezca sobremanera. </div>
<div id="2Co_12_8" style="display:none;" class="ver_select"><b>2Co 12:8</b>  Por lo cual tres veces he rogado al Señor, que lo quite de mí; </div>
<div id="2Co_12_9" style="display:none;" class="ver_select"><b>2Co 12:9</b>  y me ha dicho: Bástate mi gracia; porque mi poder se perfecciona en la debilidad. Por tanto, de buena gana me gloriaré más bien en mis debilidades, para que habite en mí el poder de Cristo. </div>
<div id="2Co_12_10" style="display:none;" class="ver_select"><b>2Co 12:10</b>  Por lo cual me gozo en las debilidades, en afrentas, en necesidades, en persecuciones, en angustias por amor a Cristo; porque cuando soy débil, entonces soy poderoso. </div>
<div id="2Co_12_11" style="display:none;" class="ver_select"><b>2Co 12:11</b>  Me he hecho un necio al gloriarme; vosotros me obligasteis; pues yo debía de ser alabado por vosotros; porque en nada soy menos que aquellos grandes apóstoles, aunque nada soy. </div>
<div id="2Co_12_12" style="display:none;" class="ver_select"><b>2Co 12:12</b>  Ciertamente las señales de apóstol han sido hechas entre vosotros en toda paciencia, en señales, y en maravillas y prodigios. </div>
<div id="2Co_12_13" style="display:none;" class="ver_select"><b>2Co 12:13</b>  Porque ¿qué hay en que hayáis sido menos que las otras iglesias, sino en que yo mismo no os he sido carga? Perdonadme este agravio. </div>
<div id="2Co_12_14" style="display:none;" class="ver_select"><b>2Co 12:14</b>  He aquí estoy preparado para ir a vosotros la tercera vez, y no os seré gravoso; porque no busco lo vuestro, sino a vosotros: porque no han de atesorar los hijos para los padres, sino los padres para los hijos. </div>
<div id="2Co_12_15" style="display:none;" class="ver_select"><b>2Co 12:15</b>  Y yo de buena gana gastaré y seré desgastado por vuestras almas, aunque amándoos más, sea amado menos, </div>
<div id="2Co_12_16" style="display:none;" class="ver_select"><b>2Co 12:16</b>  mas sea así: Yo no fui carga a vosotros; sino que, como soy astuto, os he tomado con engaño. </div>
<div id="2Co_12_17" style="display:none;" class="ver_select"><b>2Co 12:17</b>  ¿Acaso os he engañado por alguno de los que os he enviado? </div>
<div id="2Co_12_18" style="display:none;" class="ver_select"><b>2Co 12:18</b>  Rogué a Tito, y envié con él un hermano. ¿Os engañó quizá Tito? ¿No hemos procedido con el mismo espíritu, y en las mismas pisadas? </div>
<div id="2Co_12_19" style="display:none;" class="ver_select"><b>2Co 12:19</b>  ¿Pensáis aún que nos excusamos con vosotros? Delante de Dios en Cristo hablamos; mas todo lo hacemos, muy amados, para vuestra edificación. </div>
<div id="2Co_12_20" style="display:none;" class="ver_select"><b>2Co 12:20</b>  Pues temo que cuando llegare, no os halle tales como quiero, y yo sea hallado de vosotros cual no queréis; que haya entre vosotros contiendas, envidias, iras, disensiones, insidias, murmuraciones, presunciones, desórdenes. </div>
<div id="2Co_12_21" style="display:none;" class="ver_select"><b>2Co 12:21</b>  No sea que cuando volviere, mi Dios me humille entre vosotros, y haya de llorar por muchos de los que antes han pecado, y no se han arrepentido de la inmundicia y fornicación, y la lascivia que han cometido </div>
<div id="2Co_13_1" style="display:none;" class="ver_select"><b>2Co 13:1</b>  Ésta es la tercera vez que voy a vosotros. Por boca de dos o de tres testigos toda palabra será establecida. </div>
<div id="2Co_13_2" style="display:none;" class="ver_select"><b>2Co 13:2</b>  Os he dicho antes, y ahora os digo otra vez como si estuviera presente, y ahora ausente lo escribo a los que antes pecaron, y a todos los demás, que si vengo otra vez, no seré indulgente; </div>
<div id="2Co_13_3" style="display:none;" class="ver_select"><b>2Co 13:3</b>  pues que buscáis una prueba de que Cristo habla en mí, el cual no es débil para con vosotros, antes es poderoso en vosotros. </div>
<div id="2Co_13_4" style="display:none;" class="ver_select"><b>2Co 13:4</b>  Porque aunque fue crucificado en flaqueza, sin embargo vive por el poder de Dios. Pues también nosotros somos débiles en Él, mas viviremos con Él por el poder de Dios para con vosotros. </div>
<div id="2Co_13_5" style="display:none;" class="ver_select"><b>2Co 13:5</b>  Examinaos a vosotros mismos si estáis en la fe; probaos a vosotros mismos. ¿No os conocéis a vosotros mismos, que Jesucristo está en vosotros, a menos que seáis reprobados? </div>
<div id="2Co_13_6" style="display:none;" class="ver_select"><b>2Co 13:6</b>  Pero confío que sabréis que nosotros no somos reprobados. </div>
<div id="2Co_13_7" style="display:none;" class="ver_select"><b>2Co 13:7</b>  Y oro a Dios que ninguna cosa mala hagáis; no para que nosotros aparezcamos aprobados, sino para que vosotros hagáis lo que es bueno, aunque nosotros seamos como reprobados. </div>
<div id="2Co_13_8" style="display:none;" class="ver_select"><b>2Co 13:8</b>  Porque nada podemos contra la verdad, sino por la verdad. </div>
<div id="2Co_13_9" style="display:none;" class="ver_select"><b>2Co 13:9</b>  Por lo cual nos gozamos en que seamos débiles, y que vosotros seáis fuertes; y aun deseamos vuestra perfección. </div>
<div id="2Co_13_10" style="display:none;" class="ver_select"><b>2Co 13:10</b>  Por tanto os escribo esto estando ausente, no sea que estando presente os trate con dureza, conforme a la potestad que el Señor me ha dado para edificación, y no para destrucción. </div>
<div id="2Co_13_11" style="display:none;" class="ver_select"><b>2Co 13:11</b>  Finalmente, hermanos, gozaos, sed perfectos, tened consolación, sed de una misma mente, tened paz; y el Dios de amor y paz será con vosotros. </div>
<div id="2Co_13_12" style="display:none;" class="ver_select"><b>2Co 13:12</b>  Saludaos los unos a los otros con ósculo santo. </div>
<div id="2Co_13_13" style="display:none;" class="ver_select"><b>2Co 13:13</b>  Todos los santos os saludan. </div>
<div id="2Co_13_14" style="display:none;" class="ver_select"><b>2Co 13:14</b>  La gracia del Señor Jesucristo, y el amor de Dios, y la comunión del Espíritu Santo sea con todos vosotros. Amén. </div>
