<div id="2Pe_1_1" style="display:none;" class="ver_select"><b>2Pe 1:1</b>  Simón Pedro, siervo y apóstol de Jesucristo, a los que habéis alcanzado fe igualmente preciosa con nosotros, por la justicia de nuestro Dios y Salvador Jesucristo. </div>
<div id="2Pe_1_2" style="display:none;" class="ver_select"><b>2Pe 1:2</b>  Gracia y paz os sean multiplicadas en el conocimiento de Dios, y de Jesús nuestro Señor. </div>
<div id="2Pe_1_3" style="display:none;" class="ver_select"><b>2Pe 1:3</b>  Como todas las cosas que pertenecen a la vida y a la piedad nos han sido dadas por su divino poder, mediante el conocimiento de Aquél que nos ha llamado a gloria y virtud; </div>
<div id="2Pe_1_4" style="display:none;" class="ver_select"><b>2Pe 1:4</b>  por medio de las cuales nos ha dado preciosas y grandísimas promesas, para que por ellas fuésemos hechos participantes de la naturaleza divina, habiendo huido de la corrupción que hay en el mundo por la concupiscencia. </div>
<div id="2Pe_1_5" style="display:none;" class="ver_select"><b>2Pe 1:5</b>  Vosotros también, poniendo toda diligencia en esto mismo, añadid a vuestra fe, virtud, y a la virtud, conocimiento; </div>
<div id="2Pe_1_6" style="display:none;" class="ver_select"><b>2Pe 1:6</b>  y al conocimiento, templanza, y a la templanza, paciencia, y a la paciencia, piedad; </div>
<div id="2Pe_1_7" style="display:none;" class="ver_select"><b>2Pe 1:7</b>  y a la piedad, amor fraternal, y al amor fraternal, caridad. </div>
<div id="2Pe_1_8" style="display:none;" class="ver_select"><b>2Pe 1:8</b>  Porque si en vosotros hay estas cosas, y abundan, no os dejarán estar ociosos, ni estériles en cuanto al conocimiento de nuestro Señor Jesucristo. </div>
<div id="2Pe_1_9" style="display:none;" class="ver_select"><b>2Pe 1:9</b>  Pero el que no tiene estas cosas tiene la vista muy corta, es ciego, y se ha olvidado que fue purificado de sus antiguos pecados. </div>
<div id="2Pe_1_10" style="display:none;" class="ver_select"><b>2Pe 1:10</b>  Por lo cual, hermanos, procurad tanto más hacer firme vuestro llamamiento y elección; porque haciendo estas cosas, no caeréis jamás. </div>
<div id="2Pe_1_11" style="display:none;" class="ver_select"><b>2Pe 1:11</b>  Porque de esta manera os será abundantemente administrada la entrada en el reino eterno de nuestro Señor y Salvador Jesucristo. </div>
<div id="2Pe_1_12" style="display:none;" class="ver_select"><b>2Pe 1:12</b>  Por esto, yo no dejaré de recordaros siempre estas cosas, aunque vosotros las sepáis, y estéis afirmados en la verdad presente. </div>
<div id="2Pe_1_13" style="display:none;" class="ver_select"><b>2Pe 1:13</b>  Porque tengo por justo, en tanto que estoy en este tabernáculo, el incitaros con amonestación; </div>
<div id="2Pe_1_14" style="display:none;" class="ver_select"><b>2Pe 1:14</b>  sabiendo que en breve debo dejar mi tabernáculo, como nuestro Señor Jesucristo me ha declarado. </div>
<div id="2Pe_1_15" style="display:none;" class="ver_select"><b>2Pe 1:15</b>  También yo procuraré con diligencia, que después de mi muerte, vosotros podáis en todo momento tener memoria de estas cosas. </div>
<div id="2Pe_1_16" style="display:none;" class="ver_select"><b>2Pe 1:16</b>  Porque no os hemos dado a conocer el poder y la venida de nuestro Señor Jesucristo, siguiendo fábulas artificiosas; sino como habiendo visto con nuestros propios ojos su majestad. </div>
<div id="2Pe_1_17" style="display:none;" class="ver_select"><b>2Pe 1:17</b>  Porque Él recibió de Dios Padre honor y gloria, cuando le fue enviada desde la magnífica gloria una gran voz que decía: Éste es mi Hijo amado, en el cual tengo contentamiento. </div>
<div id="2Pe_1_18" style="display:none;" class="ver_select"><b>2Pe 1:18</b>  Y nosotros oímos esta voz enviada del cielo, cuando estábamos con Él en el monte santo. </div>
<div id="2Pe_1_19" style="display:none;" class="ver_select"><b>2Pe 1:19</b>  Tenemos además la palabra profética más segura, a la cual hacéis bien de estar atentos como a una lámpara que alumbra en lugar oscuro hasta que el día esclarezca, y la estrella de la mañana salga en vuestros corazones; </div>
<div id="2Pe_1_20" style="display:none;" class="ver_select"><b>2Pe 1:20</b>  entendiendo primero esto, que ninguna profecía de la Escritura es de interpretación privada; </div>
<div id="2Pe_1_21" style="display:none;" class="ver_select"><b>2Pe 1:21</b>  porque la profecía no vino en tiempo pasado por la voluntad del hombre; sino que los santos hombres de Dios hablaron siendo guiados por el Espíritu Santo. </div>
<div id="2Pe_2_1" style="display:none;" class="ver_select"><b>2Pe 2:1</b>  Pero hubo también falsos profetas entre el pueblo, como habrá entre vosotros falsos maestros, que introducirán encubiertamente herejías destructoras, y aun negarán al Señor que los rescató, atrayendo sobre sí mismos destrucción repentina. </div>
<div id="2Pe_2_2" style="display:none;" class="ver_select"><b>2Pe 2:2</b>  Y muchos seguirán sus caminos perniciosos, y por causa de ellos el camino de la verdad será blasfemado; </div>
<div id="2Pe_2_3" style="display:none;" class="ver_select"><b>2Pe 2:3</b>  y por avaricia harán mercadería de vosotros con palabras fingidas, sobre los cuales la condenación ya de largo tiempo no se tarda, y su perdición no se duerme. </div>
<div id="2Pe_2_4" style="display:none;" class="ver_select"><b>2Pe 2:4</b>  Porque si Dios no perdonó a los ángeles que pecaron, sino que los arrojó al infierno y los entregó a prisiones de oscuridad, a ser reservados para el juicio; </div>
<div id="2Pe_2_5" style="display:none;" class="ver_select"><b>2Pe 2:5</b>  y si no perdonó al mundo antiguo, sino que guardó a Noé, la octava persona, pregonero de justicia, trayendo el diluvio sobre el mundo de los impíos; </div>
<div id="2Pe_2_6" style="display:none;" class="ver_select"><b>2Pe 2:6</b>  y si condenó por destrucción las ciudades de Sodoma y de Gomorra, tornándolas en ceniza, y poniéndolas de ejemplo a los que habían de vivir impíamente, </div>
<div id="2Pe_2_7" style="display:none;" class="ver_select"><b>2Pe 2:7</b>  y libró al justo Lot, abrumado por la nefanda conducta de los malvados </div>
<div id="2Pe_2_8" style="display:none;" class="ver_select"><b>2Pe 2:8</b>  (porque este justo, morando entre ellos, afligía cada día su alma justa, viendo y oyendo los hechos inicuos de ellos). </div>
<div id="2Pe_2_9" style="display:none;" class="ver_select"><b>2Pe 2:9</b>  Sabe el Señor librar de tentación a los piadosos, y reservar a los injustos para ser castigados en el día del juicio; </div>
<div id="2Pe_2_10" style="display:none;" class="ver_select"><b>2Pe 2:10</b>  y principalmente a aquellos que siguen la carne en la concupiscencia de inmundicia, y menosprecian todo gobierno. Atrevidos, contumaces, que no temen decir mal de las potestades superiores. </div>
<div id="2Pe_2_11" style="display:none;" class="ver_select"><b>2Pe 2:11</b>  Mientras que los ángeles, que son mayores en fuerza y en potencia, no pronuncian juicio de maldición contra ellas delante del Señor. </div>
<div id="2Pe_2_12" style="display:none;" class="ver_select"><b>2Pe 2:12</b>  Pero éstos, como bestias brutas naturalmente nacidas para presa y destrucción, hablan mal de cosas que no entienden, y perecerán en su propia corrupción, </div>
<div id="2Pe_2_13" style="display:none;" class="ver_select"><b>2Pe 2:13</b>  y recibirán la recompensa de su injusticia, ya que tienen por delicia el gozar del placer en pleno día. Éstos son suciedades y manchas, quienes aun mientras comen con vosotros, se recrean en sus engaños. </div>
<div id="2Pe_2_14" style="display:none;" class="ver_select"><b>2Pe 2:14</b>  Tienen los ojos llenos de adulterio, y no pueden dejar de pecar. Seducen a las almas inestables, tienen un corazón ejercitado en la codicia; son hijos de maldición. </div>
<div id="2Pe_2_15" style="display:none;" class="ver_select"><b>2Pe 2:15</b>  Han dejado el camino recto, y se han extraviado, siguiendo el camino de Balaam, hijo de Bosor, el cual amó la paga de la maldad. </div>
<div id="2Pe_2_16" style="display:none;" class="ver_select"><b>2Pe 2:16</b>  Mas fue reprendido por su iniquidad; una asna muda, hablando con voz de hombre, refrenó la locura del profeta. </div>
<div id="2Pe_2_17" style="display:none;" class="ver_select"><b>2Pe 2:17</b>  Éstos son fuentes sin agua, y nubes empujadas por la tempestad; para los cuales está guardada la oscuridad de las tinieblas para siempre. </div>
<div id="2Pe_2_18" style="display:none;" class="ver_select"><b>2Pe 2:18</b>  Porque hablando palabras arrogantes de vanidad, seducen con las concupiscencias de la carne mediante lascivias a los que verdaderamente habían escapado de los que viven en error; </div>
<div id="2Pe_2_19" style="display:none;" class="ver_select"><b>2Pe 2:19</b>  prometiéndoles libertad, siendo ellos mismos esclavos de corrupción. Porque el que es vencido de alguno, es hecho esclavo de aquel que lo venció. </div>
<div id="2Pe_2_20" style="display:none;" class="ver_select"><b>2Pe 2:20</b>  Porque si habiendo ellos escapado de las contaminaciones del mundo, por el conocimiento del Señor y Salvador Jesucristo, y otra vez se enredan en ellas y son vencidos, su postrimería viene a ser peor que su principio. </div>
<div id="2Pe_2_21" style="display:none;" class="ver_select"><b>2Pe 2:21</b>  Porque mejor les hubiera sido no haber conocido el camino de la justicia, que después de haberlo conocido, tornarse atrás del santo mandamiento que les fue dado. </div>
<div id="2Pe_2_22" style="display:none;" class="ver_select"><b>2Pe 2:22</b>  Pero les ha acontecido lo del verdadero proverbio: El perro volvió a su vómito, y la puerca lavada a revolcarse en el cieno. </div>
<div id="2Pe_3_1" style="display:none;" class="ver_select"><b>2Pe 3:1</b>  Carísimos, esta segunda carta escribo ahora a vosotros; en la cual despierto vuestro sincero entendimiento, por recordatorio; </div>
<div id="2Pe_3_2" style="display:none;" class="ver_select"><b>2Pe 3:2</b>  para que tengáis memoria de las palabras que antes han sido dichas por los santos profetas, y del mandamiento de nosotros los apóstoles del Señor y Salvador; </div>
<div id="2Pe_3_3" style="display:none;" class="ver_select"><b>2Pe 3:3</b>  sabiendo primero esto, que en los postreros días vendrán burladores, andando según sus propias concupiscencias, </div>
<div id="2Pe_3_4" style="display:none;" class="ver_select"><b>2Pe 3:4</b>  y diciendo: ¿Dónde está la promesa de su venida? Porque desde que los padres durmieron, todas las cosas permanecen así como estaban desde el principio de la creación. </div>
<div id="2Pe_3_5" style="display:none;" class="ver_select"><b>2Pe 3:5</b>  Porque ellos ignoran voluntariamente esto; que por la palabra de Dios fueron creados los cielos en el tiempo antiguo, y la tierra, que por agua y en agua está asentada; </div>
<div id="2Pe_3_6" style="display:none;" class="ver_select"><b>2Pe 3:6</b>  por lo cual el mundo de entonces pereció anegado en agua. </div>
<div id="2Pe_3_7" style="display:none;" class="ver_select"><b>2Pe 3:7</b>  Pero los cielos que son ahora, y la tierra, son reservados por la misma palabra, guardados para el fuego en el día del juicio y de la perdición de los hombres impíos. </div>
<div id="2Pe_3_8" style="display:none;" class="ver_select"><b>2Pe 3:8</b>  Mas, amados, no ignoréis esto: Que un día delante del Señor es como mil años, y mil años como un día. </div>
<div id="2Pe_3_9" style="display:none;" class="ver_select"><b>2Pe 3:9</b>  El Señor no tarda su promesa, como algunos la tienen por tardanza; sino que es paciente para con nosotros, no queriendo que ninguno perezca, sino que todos vengan al arrepentimiento. </div>
<div id="2Pe_3_10" style="display:none;" class="ver_select"><b>2Pe 3:10</b>  Pero el día del Señor vendrá como ladrón en la noche; en el cual los cielos pasarán con grande estruendo, y los elementos ardiendo serán deshechos, y la tierra y las obras que en ella hay serán quemadas. </div>
<div id="2Pe_3_11" style="display:none;" class="ver_select"><b>2Pe 3:11</b>  Puesto que todas estas cosas han de ser deshechas, ¿cómo no debéis vosotros de conduciros en santa y piadosa manera de vivir? </div>
<div id="2Pe_3_12" style="display:none;" class="ver_select"><b>2Pe 3:12</b>  Esperando y apresurándoos para la venida del día de Dios, en el cual los cielos, siendo encendidos, serán deshechos, y los elementos siendo quemados, se fundirán. </div>
<div id="2Pe_3_13" style="display:none;" class="ver_select"><b>2Pe 3:13</b>  Pero nosotros esperamos según su promesa, cielos nuevos y tierra nueva, en los cuales mora la justicia. </div>
<div id="2Pe_3_14" style="display:none;" class="ver_select"><b>2Pe 3:14</b>  Por lo cual, amados, estando en espera de estas cosas, procurad con diligencia que seáis hallados de Él en paz, sin mácula y sin reprensión. </div>
<div id="2Pe_3_15" style="display:none;" class="ver_select"><b>2Pe 3:15</b>  Y considerad la paciencia de nuestro Señor por salvación; como también nuestro amado hermano Pablo, según la sabiduría que le ha sido dada, os ha escrito, </div>
<div id="2Pe_3_16" style="display:none;" class="ver_select"><b>2Pe 3:16</b>  como también en todas sus epístolas, hablando en ellas de estas cosas; entre las cuales hay algunas difíciles de entender, las cuales los indoctos e inconstantes tuercen, como también las otras Escrituras, para su propia perdición. </div>
<div id="2Pe_3_17" style="display:none;" class="ver_select"><b>2Pe 3:17</b>  Así que vosotros, amados, sabiéndolo de antemano, guardaos, no sea que siendo desviados con el error de los inicuos, caigáis de vuestra firmeza. </div>
<div id="2Pe_3_18" style="display:none;" class="ver_select"><b>2Pe 3:18</b>  Mas creced en la gracia y en el conocimiento de nuestro Señor y Salvador Jesucristo. A Él sea gloria ahora y para siempre. Amén. </div>
