<div id="Amo_1_1" style="display:none;" class="ver_select"><b>Amo 1:1</b>  Las palabras de Amós, que fue entre los pastores de Tecoa, las cuales vio acerca de Israel en días de Uzías rey de Judá, y en días de Jeroboam hijo de Joás rey de Israel, dos años antes del terremoto. </div>
<div id="Amo_1_2" style="display:none;" class="ver_select"><b>Amo 1:2</b>  Y dijo: Jehová rugirá desde Sión, y dará su voz desde Jerusalén; y las habitaciones de los pastores se enlutarán, y se secará la cumbre del Carmelo. </div>
<div id="Amo_1_3" style="display:none;" class="ver_select"><b>Amo 1:3</b>  Así dice Jehová: Por tres pecados de Damasco, y por el cuarto, no revocaré su castigo; porque trillaron a Galaad con trillos de hierro. </div>
<div id="Amo_1_4" style="display:none;" class="ver_select"><b>Amo 1:4</b>  Y meteré fuego en la casa de Hazael, y consumirá los palacios de Benadad. </div>
<div id="Amo_1_5" style="display:none;" class="ver_select"><b>Amo 1:5</b>  Y quebraré la barra de Damasco, y cortaré a los moradores del valle de Avén, y al que empuña el cetro de Bet-edén; y el pueblo de Aram será trasportado a Kir, dice Jehová. </div>
<div id="Amo_1_6" style="display:none;" class="ver_select"><b>Amo 1:6</b>  Así dice Jehová: Por tres pecados de Gaza, y por el cuarto, no revocaré su castigo; porque llevó cautiva toda la cautividad, para entregarlos a Edom. </div>
<div id="Amo_1_7" style="display:none;" class="ver_select"><b>Amo 1:7</b>  Y meteré fuego en el muro de Gaza, y quemará sus palacios. </div>
<div id="Amo_1_8" style="display:none;" class="ver_select"><b>Amo 1:8</b>  Y cortaré a los moradores de Asdod, y al que empuña el cetro de Ascalón; y volveré mi mano contra Ecrón y el remanente de los filisteos perecerá, dice Jehová el Señor. </div>
<div id="Amo_1_9" style="display:none;" class="ver_select"><b>Amo 1:9</b>  Así dice Jehová: Por tres pecados de Tiro, y por el cuarto, no revocaré su castigo; porque entregaron la cautividad entera a Edom, y no se acordaron del pacto de hermanos. </div>
<div id="Amo_1_10" style="display:none;" class="ver_select"><b>Amo 1:10</b>  Y meteré fuego en el muro de Tiro, y consumirá sus palacios. </div>
<div id="Amo_1_11" style="display:none;" class="ver_select"><b>Amo 1:11</b>  Así dice Jehová: Por tres pecados de Edom, y por el cuarto, no revocaré su castigo; porque persiguió a espada a su hermano, y desechó la misericordia; y con su furor siempre le ha destrozado, y perpetuamente ha guardado el enojo. </div>
<div id="Amo_1_12" style="display:none;" class="ver_select"><b>Amo 1:12</b>  Y meteré fuego en Temán, y consumirá los palacios de Bosra. </div>
<div id="Amo_1_13" style="display:none;" class="ver_select"><b>Amo 1:13</b>  Así dice Jehová: Por tres pecados de los hijos de Amón, y por el cuarto, no revocaré su castigo; porque para ensanchar su término abrieron a las mujeres de Galaad que estaban encintas. </div>
<div id="Amo_1_14" style="display:none;" class="ver_select"><b>Amo 1:14</b>  Y encenderé fuego en el muro de Rabá, y consumirá sus palacios con estruendo en el día de la batalla, con tempestad en día tempestuoso; </div>
<div id="Amo_1_15" style="display:none;" class="ver_select"><b>Amo 1:15</b>  y su rey irá en cautiverio, él y todos sus príncipes, dice Jehová. </div>
<div id="Amo_2_1" style="display:none;" class="ver_select"><b>Amo 2:1</b>  Así dice Jehová: Por tres pecados de Moab, y por el cuarto, no revocaré su castigo; porque quemó los huesos del rey de Idumea hasta calcinarlos. </div>
<div id="Amo_2_2" style="display:none;" class="ver_select"><b>Amo 2:2</b>  Y meteré fuego en Moab, y consumirá los palacios de Queriot; y morirá Moab en alboroto, en estrépito y sonido de trompeta. </div>
<div id="Amo_2_3" style="display:none;" class="ver_select"><b>Amo 2:3</b>  Y quitaré el juez de en medio de él, y mataré con él a todos sus príncipes, dice Jehová. </div>
<div id="Amo_2_4" style="display:none;" class="ver_select"><b>Amo 2:4</b>  Así dice Jehová: Por tres pecados de Judá, y por el cuarto, no revocaré su castigo; porque despreciaron la ley de Jehová, y no guardaron sus ordenanzas; y los hicieron errar sus mentiras, en pos de las cuales anduvieron sus padres. </div>
<div id="Amo_2_5" style="display:none;" class="ver_select"><b>Amo 2:5</b>  Meteré por tanto fuego en Judá, el cual consumirá los palacios de Jerusalén. </div>
<div id="Amo_2_6" style="display:none;" class="ver_select"><b>Amo 2:6</b>  Así dice Jehová: Por tres pecados de Israel, y por el cuarto, no revocaré su castigo; porque vendieron por dinero al justo, y al pobre por un par de zapatos: </div>
<div id="Amo_2_7" style="display:none;" class="ver_select"><b>Amo 2:7</b>  Que codician aun el polvo de la tierra sobre la cabeza de los pobres, y tuercen el camino de los humildes; y el hombre y su padre entran a la misma joven, profanando mi santo nombre. </div>
<div id="Amo_2_8" style="display:none;" class="ver_select"><b>Amo 2:8</b>  Y sobre las ropas empeñadas se acuestan junto a cualquier altar; y beben el vino de los condenados en la casa de sus dioses. </div>
<div id="Amo_2_9" style="display:none;" class="ver_select"><b>Amo 2:9</b>  Y yo destruí delante de ellos al amorreo, cuya altura era como la altura de los cedros, y fuerte como un alcornoque; y destruí su fruto arriba, sus raíces abajo. </div>
<div id="Amo_2_10" style="display:none;" class="ver_select"><b>Amo 2:10</b>  Y yo os hice a vosotros subir de la tierra de Egipto, y os traje por el desierto cuarenta años, para que poseyeseis la tierra del amorreo. </div>
<div id="Amo_2_11" style="display:none;" class="ver_select"><b>Amo 2:11</b>  Y levanté de vuestros hijos para profetas, y de vuestros jóvenes para que fuesen nazareos. ¿No es esto así, dice Jehová, hijos de Israel? </div>
<div id="Amo_2_12" style="display:none;" class="ver_select"><b>Amo 2:12</b>  Mas vosotros disteis de beber vino a los nazareos; y a los profetas mandasteis, diciendo: No profeticéis. </div>
<div id="Amo_2_13" style="display:none;" class="ver_select"><b>Amo 2:13</b>  Pues he aquí, yo os apretaré en vuestro lugar, como se aprieta el carro lleno de gavillas; </div>
<div id="Amo_2_14" style="display:none;" class="ver_select"><b>Amo 2:14</b>  y la huida perecerá del ligero, y al fuerte no le ayudará su fuerza, ni el valiente librará su vida; </div>
<div id="Amo_2_15" style="display:none;" class="ver_select"><b>Amo 2:15</b>  y el que toma el arco no resistirá, ni escapará el ligero de pies, ni el que cabalga en caballo salvará su vida. </div>
<div id="Amo_2_16" style="display:none;" class="ver_select"><b>Amo 2:16</b>  El esforzado entre los valientes huirá desnudo aquel día, dice Jehová. </div>
<div id="Amo_3_1" style="display:none;" class="ver_select"><b>Amo 3:1</b>  Oíd esta palabra que ha hablado Jehová contra vosotros, hijos de Israel, contra toda la familia que hice subir de la tierra de Egipto. Dice así: </div>
<div id="Amo_3_2" style="display:none;" class="ver_select"><b>Amo 3:2</b>  A vosotros solamente he conocido de todas las familias de la tierra; por tanto visitaré contra vosotros todas vuestras maldades. </div>
<div id="Amo_3_3" style="display:none;" class="ver_select"><b>Amo 3:3</b>  ¿Andarán dos juntos, si no estuvieren de acuerdo? </div>
<div id="Amo_3_4" style="display:none;" class="ver_select"><b>Amo 3:4</b>  ¿Rugirá el león en la selva sin haber presa? ¿Dará el leoncillo su rugido desde su guarida, sin haber apresado algo? </div>
<div id="Amo_3_5" style="display:none;" class="ver_select"><b>Amo 3:5</b>  ¿Caerá el ave en el lazo en la tierra, sin haber cazador? ¿Se alzará el lazo de la tierra, si no se ha atrapado nada? </div>
<div id="Amo_3_6" style="display:none;" class="ver_select"><b>Amo 3:6</b>  ¿Se tocará la trompeta en la ciudad, y no se alborotará el pueblo? ¿Habrá algún mal en la ciudad, el cual Jehová no haya hecho? </div>
<div id="Amo_3_7" style="display:none;" class="ver_select"><b>Amo 3:7</b>  Porque no hará nada el Señor Jehová, sin que revele su secreto a sus siervos los profetas. </div>
<div id="Amo_3_8" style="display:none;" class="ver_select"><b>Amo 3:8</b>  Rugiendo el león, ¿quién no temerá? Hablando Jehová el Señor, ¿quién no profetizará? </div>
<div id="Amo_3_9" style="display:none;" class="ver_select"><b>Amo 3:9</b>  Haced pregonar sobre los palacios de Asdod, y sobre los palacios de tierra de Egipto, y decid: Reuníos sobre los montes de Samaria, y ved muchas opresiones en medio de ella, y violencias en medio de ella. </div>
<div id="Amo_3_10" style="display:none;" class="ver_select"><b>Amo 3:10</b>  Y no saben hacer lo recto, dice Jehová, atesorando rapiñas y despojos en sus palacios. </div>
<div id="Amo_3_11" style="display:none;" class="ver_select"><b>Amo 3:11</b>  Por tanto, así dice Jehová el Señor: Un enemigo vendrá aún por todos lados de la tierra, y derribará de ti tu fortaleza, y tus palacios serán saqueados. </div>
<div id="Amo_3_12" style="display:none;" class="ver_select"><b>Amo 3:12</b>  Así dice Jehová: De la manera que el pastor libra de la boca del león dos piernas, o la punta de una oreja, así escaparán los hijos de Israel que moran en Samaria en el rincón de una cama, y al lado de un lecho. </div>
<div id="Amo_3_13" style="display:none;" class="ver_select"><b>Amo 3:13</b>  Oíd y testificad en la casa de Jacob, dice el Señor Jehová, el Dios de los ejércitos: </div>
<div id="Amo_3_14" style="display:none;" class="ver_select"><b>Amo 3:14</b>  Que el día que visite las rebeliones de Israel sobre él, visitaré también sobre los altares de Betel; y serán cortados los cuernos del altar, y caerán a tierra. </div>
<div id="Amo_3_15" style="display:none;" class="ver_select"><b>Amo 3:15</b>  Y heriré la casa de invierno con la casa de verano, y las casas de marfil perecerán; y las grandes casas serán destruidas, dice Jehová. </div>
<div id="Amo_4_1" style="display:none;" class="ver_select"><b>Amo 4:1</b>  Oíd esta palabra, vacas de Basán, que estáis en el monte de Samaria, que oprimís a los pobres, que quebrantáis a los menesterosos, que decís a sus señores: Traed, y beberemos. </div>
<div id="Amo_4_2" style="display:none;" class="ver_select"><b>Amo 4:2</b>  Jehová el Señor juró por su santidad: He aquí, vienen días sobre vosotros en que os llevará con ganchos, y a vuestros descendientes con anzuelos de pescar. </div>
<div id="Amo_4_3" style="display:none;" class="ver_select"><b>Amo 4:3</b>  Y saldréis por las brechas la una en pos de la otra, y seréis echadas del palacio, dice Jehová. </div>
<div id="Amo_4_4" style="display:none;" class="ver_select"><b>Amo 4:4</b>  Id a Betel, y prevaricad; en Gilgal aumentad la rebelión, y traed de mañana vuestros sacrificios, y vuestros diezmos cada tres años. </div>
<div id="Amo_4_5" style="display:none;" class="ver_select"><b>Amo 4:5</b>  Y ofreced sacrificio de alabanza con leudo, y pregonad, publicad ofrendas voluntarias; pues que así lo queréis, hijos de Israel, dice Jehová el Señor. </div>
<div id="Amo_4_6" style="display:none;" class="ver_select"><b>Amo 4:6</b>  Yo también os di limpieza de dientes en todas vuestras ciudades, y falta de pan en todos vuestros pueblos; pero no os volvisteis a mí, dice Jehová. </div>
<div id="Amo_4_7" style="display:none;" class="ver_select"><b>Amo 4:7</b>  Y también yo os detuve la lluvia tres meses antes de la siega; e hice llover sobre una ciudad, y sobre otra ciudad no hice llover; sobre una parte llovió; la parte sobre la cual no llovió, se secó. </div>
<div id="Amo_4_8" style="display:none;" class="ver_select"><b>Amo 4:8</b>  Y venían dos o tres ciudades a una ciudad para beber agua, y no se saciaban; con todo no os volvisteis a mí, dice Jehová. </div>
<div id="Amo_4_9" style="display:none;" class="ver_select"><b>Amo 4:9</b>  Os herí con viento solano y oruga; vuestros muchos huertos y vuestras viñas, y vuestros higuerales y vuestros olivares comió la langosta; pero nunca os volvisteis a mí, dice Jehová. </div>
<div id="Amo_4_10" style="display:none;" class="ver_select"><b>Amo 4:10</b>  Envié entre vosotros mortandad tal como en Egipto; maté a espada a vuestros jóvenes, con cautiverio de vuestros caballos; e hice subir el hedor de vuestros campamentos hasta vuestras narices; pero no os volvisteis a mí, dice Jehová. </div>
<div id="Amo_4_11" style="display:none;" class="ver_select"><b>Amo 4:11</b>  Os trastorné, como cuando Dios trastornó a Sodoma y a Gomorra, y fuisteis como tizón escapado del fuego; mas no os volvisteis a mí, dice Jehová. </div>
<div id="Amo_4_12" style="display:none;" class="ver_select"><b>Amo 4:12</b>  Por tanto, de esta manera haré a ti, oh Israel; y porque te he de hacer esto, prepárate para venir al encuentro de tu Dios, oh Israel. </div>
<div id="Amo_4_13" style="display:none;" class="ver_select"><b>Amo 4:13</b>  Porque he aquí, el que forma los montes, y crea el viento, y declara al hombre su pensamiento; el que hace a las tinieblas mañana, y pasa sobre las alturas de la tierra; Jehová, Dios de los ejércitos es su nombre. </div>
<div id="Amo_5_1" style="display:none;" class="ver_select"><b>Amo 5:1</b>  Oíd esta palabra que yo levanto por lamentación  sobre vosotros, oh casa de Israel. </div>
<div id="Amo_5_2" style="display:none;" class="ver_select"><b>Amo 5:2</b>  Cayó la virgen de Israel, y no podrá levantarse ya más; fue dejada sobre su tierra, no hay quien la levante. </div>
<div id="Amo_5_3" style="display:none;" class="ver_select"><b>Amo 5:3</b>  Porque así ha dicho el Señor Jehová a la casa de Israel: La ciudad que salía con mil, quedará con cien; y la que salía con cien, quedará con diez. </div>
<div id="Amo_5_4" style="display:none;" class="ver_select"><b>Amo 5:4</b>  Mas así dice Jehová a la casa de Israel: Buscadme, y viviréis; </div>
<div id="Amo_5_5" style="display:none;" class="ver_select"><b>Amo 5:5</b>  y no busquéis a Betel ni entréis en Gilgal, ni paséis a Beerseba: porque ciertamente Gilgal será llevada en cautiverio, y Betel será deshecha. </div>
<div id="Amo_5_6" style="display:none;" class="ver_select"><b>Amo 5:6</b>  Buscad a Jehová, y vivid; no sea que Él acometa como fuego a la casa de José y la consuma, sin haber en Betel quien lo apague. </div>
<div id="Amo_5_7" style="display:none;" class="ver_select"><b>Amo 5:7</b>  Los que convertís en ajenjo el juicio, y echáis por tierra la justicia, </div>
<div id="Amo_5_8" style="display:none;" class="ver_select"><b>Amo 5:8</b>  buscad al que hace las Pléyades y el Orión, y las tinieblas vuelve en mañana, y hace oscurecer el día en noche; el que llama a las aguas del mar, y las derrama sobre la faz de la tierra: Jehová es su nombre. </div>
<div id="Amo_5_9" style="display:none;" class="ver_select"><b>Amo 5:9</b>  Que da fuerzas al despojador sobre el fuerte, de modo que el despojador venga contra la fortaleza. </div>
<div id="Amo_5_10" style="display:none;" class="ver_select"><b>Amo 5:10</b>  Ellos aborrecen en la puerta de la ciudad al que reprende, y abominan al que habla lo recto. </div>
<div id="Amo_5_11" style="display:none;" class="ver_select"><b>Amo 5:11</b>  Por tanto, pues que vejáis al pobre y recibís de él carga de trigo; edificasteis casas de piedra labrada, mas no las habitaréis; plantasteis hermosas viñas, mas no beberéis el vino de ellas. </div>
<div id="Amo_5_12" style="display:none;" class="ver_select"><b>Amo 5:12</b>  Porque he sabido vuestras muchas rebeliones, y vuestros grandes pecados: que afligen al justo, y reciben cohecho, y a los pobres en la puerta hacen perder su causa. </div>
<div id="Amo_5_13" style="display:none;" class="ver_select"><b>Amo 5:13</b>  Por tanto, el prudente en tal tiempo calla, porque el tiempo es malo. </div>
<div id="Amo_5_14" style="display:none;" class="ver_select"><b>Amo 5:14</b>  Buscad lo bueno, y no lo malo, para que viváis; porque así Jehová Dios de los ejércitos será con vosotros, como decís. </div>
<div id="Amo_5_15" style="display:none;" class="ver_select"><b>Amo 5:15</b>  Aborreced el mal, y amad el bien, y poned juicio en la puerta; quizá Jehová, Dios de los ejércitos, tendrá piedad del remanente de José. </div>
<div id="Amo_5_16" style="display:none;" class="ver_select"><b>Amo 5:16</b>  Por tanto, así dice Jehová Dios de los ejércitos, el Señor: En todas las plazas habrá llanto, y en todas las calles dirán: ¡Ay! ¡Ay!, y al labrador llamarán a lloro, y a endecha a los que saben endechar. </div>
<div id="Amo_5_17" style="display:none;" class="ver_select"><b>Amo 5:17</b>  Y en todas las viñas habrá llanto; porque pasaré por en medio de ti, dice Jehová. </div>
<div id="Amo_5_18" style="display:none;" class="ver_select"><b>Amo 5:18</b>  ¡Ay de los que desean el día de Jehová! ¿Para qué queréis este día de Jehová? Será de tinieblas, y no de luz: </div>
<div id="Amo_5_19" style="display:none;" class="ver_select"><b>Amo 5:19</b>  Como el que huye de delante del león, y se topa con el oso; o el que entra en casa y arrima su mano a la pared, y le muerda una serpiente. </div>
<div id="Amo_5_20" style="display:none;" class="ver_select"><b>Amo 5:20</b>  ¿No será el día de Jehová tinieblas, y no luz; oscuridad, que no tiene resplandor? </div>
<div id="Amo_5_21" style="display:none;" class="ver_select"><b>Amo 5:21</b>  Aborrecí, abominé vuestras solemnidades, y no me darán buen olor vuestras asambleas. </div>
<div id="Amo_5_22" style="display:none;" class="ver_select"><b>Amo 5:22</b>  Aunque me ofrezcáis holocaustos y vuestros presentes, no los aceptaré; ni miraré a las ofrendas de paz de vuestros animales engordados. </div>
<div id="Amo_5_23" style="display:none;" class="ver_select"><b>Amo 5:23</b>  Aleja de mí el ruido de tus cantos, que no escucharé las salmodias de tus instrumentos. </div>
<div id="Amo_5_24" style="display:none;" class="ver_select"><b>Amo 5:24</b>  Pero corra el juicio como las aguas, y la justicia como impetuoso arroyo. </div>
<div id="Amo_5_25" style="display:none;" class="ver_select"><b>Amo 5:25</b>  ¿Me habéis ofrecido sacrificios y presentes en el desierto en cuarenta años, casa de Israel? </div>
<div id="Amo_5_26" style="display:none;" class="ver_select"><b>Amo 5:26</b>  Mas llevabais el tabernáculo de vuestro Moloc y Quiún, ídolos vuestros, la estrella de vuestros dioses que os hicisteis. </div>
<div id="Amo_5_27" style="display:none;" class="ver_select"><b>Amo 5:27</b>  Por tanto, os haré trasportar más allá de Damasco, ha dicho Jehová, cuyo nombre es Dios de los ejércitos. </div>
<div id="Amo_6_1" style="display:none;" class="ver_select"><b>Amo 6:1</b>  ¡Ay de los reposados en Sión, y de los confiados en el monte de Samaria, los que son llamados príncipes de las naciones, ante quienes acude la casa de Israel! </div>
<div id="Amo_6_2" style="display:none;" class="ver_select"><b>Amo 6:2</b>  Pasad a Calne, y mirad; y de allí id a la gran Hamat; descended luego a Gat de los filisteos; ved si son aquellos reinos mejores que estos reinos, si su término es mayor que vuestro término. </div>
<div id="Amo_6_3" style="display:none;" class="ver_select"><b>Amo 6:3</b>  Vosotros que dilatáis el día malo, y acercáis la silla de la iniquidad. </div>
<div id="Amo_6_4" style="display:none;" class="ver_select"><b>Amo 6:4</b>  Duermen en camas de marfil, y se extienden sobre sus lechos; y comen los corderos del rebaño, y los becerros de en medio del engordadero; </div>
<div id="Amo_6_5" style="display:none;" class="ver_select"><b>Amo 6:5</b>  gorjean al son de la flauta, e inventan instrumentos de música, como David; </div>
<div id="Amo_6_6" style="display:none;" class="ver_select"><b>Amo 6:6</b>  beben vino en tazones, y se ungen con los ungüentos más preciosos; y no se afligen por el quebrantamiento de José. </div>
<div id="Amo_6_7" style="display:none;" class="ver_select"><b>Amo 6:7</b>  Por tanto, ahora irán cautivos, a la cabeza de los que van en cautiverio, y el banquete de los disolutos será removido. </div>
<div id="Amo_6_8" style="display:none;" class="ver_select"><b>Amo 6:8</b>  Jehová el Señor juró por su alma, Jehová Dios de los ejércitos ha dicho: Tengo en abominación la grandeza de Jacob, y aborrezco sus palacios; y la ciudad y su plenitud entregaré al enemigo. </div>
<div id="Amo_6_9" style="display:none;" class="ver_select"><b>Amo 6:9</b>  Y acontecerá que si diez hombres quedaren en una casa, morirán. </div>
<div id="Amo_6_10" style="display:none;" class="ver_select"><b>Amo 6:10</b>  Y su tío tomará a cada uno, y le quemará para sacar los huesos de casa; y dirá al que estará en los rincones de la casa: ¿Hay aún alguno contigo? Y dirá: No. Entonces dirá aquél: Calla que no podemos hacer mención del nombre de Jehová. </div>
<div id="Amo_6_11" style="display:none;" class="ver_select"><b>Amo 6:11</b>  Porque he aquí, Jehová mandará, y herirá con hendiduras la casa mayor, y la casa menor con aberturas. </div>
<div id="Amo_6_12" style="display:none;" class="ver_select"><b>Amo 6:12</b>  ¿Correrán los caballos por las peñas? ¿Ararán en ellas con bueyes? Porque vosotros habéis tornado el juicio en veneno, y el fruto de justicia en ajenjo. </div>
<div id="Amo_6_13" style="display:none;" class="ver_select"><b>Amo 6:13</b>  Vosotros que os alegráis en nada, que decís: ¿No nos hemos tomado poderíos con nuestra propia fuerza? </div>
<div id="Amo_6_14" style="display:none;" class="ver_select"><b>Amo 6:14</b>  Pues he aquí, levantaré yo sobre vosotros, oh casa de Israel, dice Jehová Dios de los ejércitos, gente que os oprimirá desde la entrada de Hamat hasta el arroyo del desierto. </div>
<div id="Amo_7_1" style="display:none;" class="ver_select"><b>Amo 7:1</b>  Así me ha mostrado el Señor Jehová; y he aquí, Él criaba langostas al principio que comenzaba a crecer el heno tardío; y he aquí, era el heno tardío después de las siegas del rey. </div>
<div id="Amo_7_2" style="display:none;" class="ver_select"><b>Amo 7:2</b>  Y aconteció que cuando acabó de comer la hierba de la tierra, yo dije: Oh Señor DIOS, perdona, te ruego; ¿quién levantará a Jacob? Porque es pequeño. </div>
<div id="Amo_7_3" style="display:none;" class="ver_select"><b>Amo 7:3</b>  Se arrepintió Jehová de esto: No será así, dice Jehová. </div>
<div id="Amo_7_4" style="display:none;" class="ver_select"><b>Amo 7:4</b>  El Señor Jehová me mostró así; y he aquí, llamaba para juzgar por fuego el Señor Jehová; y consumió un gran abismo, y consumió una parte de la tierra. </div>
<div id="Amo_7_5" style="display:none;" class="ver_select"><b>Amo 7:5</b>  Y dije: Señor Jehová, cesa ahora; ¿quién levantará a Jacob? Porque es pequeño. </div>
<div id="Amo_7_6" style="display:none;" class="ver_select"><b>Amo 7:6</b>  Se arrepintió Jehová de esto: No será esto tampoco, dijo el Señor Jehová. </div>
<div id="Amo_7_7" style="display:none;" class="ver_select"><b>Amo 7:7</b>  Me enseñó así: He aquí, el Señor estaba sobre un muro hecho a plomo, y en su mano una plomada de albañil. </div>
<div id="Amo_7_8" style="display:none;" class="ver_select"><b>Amo 7:8</b>  Jehová entonces me dijo: ¿Qué ves, Amós? Y dije: Una plomada de albañil. Y el Señor dijo: He aquí, yo pongo plomada de albañil en medio de mi pueblo Israel: No le pasaré más: </div>
<div id="Amo_7_9" style="display:none;" class="ver_select"><b>Amo 7:9</b>  Y los altares de Isaac serán destruidos, y los santuarios de Israel serán asolados; y me levantaré con espada sobre la casa de Jeroboam. </div>
<div id="Amo_7_10" style="display:none;" class="ver_select"><b>Amo 7:10</b>  Entonces Amasías sacerdote de Betel envió a decir a Jeroboam, rey de Israel: Amós ha conspirado contra ti en medio de la casa de Israel; la tierra no puede soportar todas sus palabras. </div>
<div id="Amo_7_11" style="display:none;" class="ver_select"><b>Amo 7:11</b>  Porque así ha dicho Amós: Jeroboam morirá a espada, e Israel pasará de su tierra en cautiverio. </div>
<div id="Amo_7_12" style="display:none;" class="ver_select"><b>Amo 7:12</b>  Y Amasías dijo a Amós: Vidente, vete, y huye a tierra de Judá, y come allá tu pan, y profetiza allí: </div>
<div id="Amo_7_13" style="display:none;" class="ver_select"><b>Amo 7:13</b>  Y no profetices más en Betel, porque es santuario del rey, y cabecera del reino. </div>
<div id="Amo_7_14" style="display:none;" class="ver_select"><b>Amo 7:14</b>  Entonces respondió Amós, y dijo a Amasías: Yo no era profeta, ni hijo de profeta, sino que era boyero, y recogía higos silvestres. </div>
<div id="Amo_7_15" style="display:none;" class="ver_select"><b>Amo 7:15</b>  Y Jehová me tomó de detrás del ganado, y me dijo Jehová: Ve, y profetiza a mi pueblo Israel. </div>
<div id="Amo_7_16" style="display:none;" class="ver_select"><b>Amo 7:16</b>  Ahora, pues, oye palabra de Jehová. Tú dices: No profetices contra Israel, ni hables contra la casa de Isaac. </div>
<div id="Amo_7_17" style="display:none;" class="ver_select"><b>Amo 7:17</b>  Por tanto, así dice Jehová: Tu esposa será ramera en la ciudad, y tus hijos y tus hijas caerán a espada, y tu tierra será repartida a cordel; y tú morirás en tierra inmunda, e Israel será llevado cautivo lejos de su tierra. </div>
<div id="Amo_8_1" style="display:none;" class="ver_select"><b>Amo 8:1</b>  Así me ha mostrado Jehová; y he aquí un canastillo de fruta de verano. </div>
<div id="Amo_8_2" style="display:none;" class="ver_select"><b>Amo 8:2</b>  Y dijo: ¿Qué ves, Amós? Y dije: Un canastillo de fruta de verano. Y me dijo Jehová: Ha venido el fin sobre mi pueblo Israel; no le pasaré más. </div>
<div id="Amo_8_3" style="display:none;" class="ver_select"><b>Amo 8:3</b>  Y los cantores del templo aullarán en aquel día, dice Jehová el Señor; muchos serán los cuerpos muertos; en todo lugar serán echados en silencio. </div>
<div id="Amo_8_4" style="display:none;" class="ver_select"><b>Amo 8:4</b>  Oíd esto, los que devoráis a los menesterosos, y arruináis a los pobres de la tierra, </div>
<div id="Amo_8_5" style="display:none;" class="ver_select"><b>Amo 8:5</b>  diciendo: ¿Cuándo pasará la luna nueva, para que vendamos el grano; y el sábado, para que abramos los alfolíes del trigo, para que achiquemos la medida, y aumentemos el precio, y falseemos con engaño la balanza; </div>
<div id="Amo_8_6" style="display:none;" class="ver_select"><b>Amo 8:6</b>  para comprar a los pobres por dinero, y a los necesitados por un par de zapatos, y para vender los desechos del trigo? </div>
<div id="Amo_8_7" style="display:none;" class="ver_select"><b>Amo 8:7</b>  Jehová juró por la gloria de Jacob: Ciertamente yo no me olvidaré de ninguna de sus obras. </div>
<div id="Amo_8_8" style="display:none;" class="ver_select"><b>Amo 8:8</b>  ¿No se estremecerá por esto la tierra? ¿No llorará todo aquel que habite en ella? Y subirá toda como un río, y será arrojada, y se hundirá como el río de Egipto. </div>
<div id="Amo_8_9" style="display:none;" class="ver_select"><b>Amo 8:9</b>  Y acontecerá en aquel día, dice el Señor Jehová, que haré que se ponga el sol al mediodía, y la tierra cubriré de tinieblas en el día claro. </div>
<div id="Amo_8_10" style="display:none;" class="ver_select"><b>Amo 8:10</b>  Y tornaré vuestras fiestas en lloro, y todos vuestros cantares en endechas; y pondré cilicio sobre todo lomo, y calvicie sobre toda cabeza; y haré que sea como duelo por hijo único, y su postrimería como día de amargura. </div>
<div id="Amo_8_11" style="display:none;" class="ver_select"><b>Amo 8:11</b>  He aquí vienen días, dice el Señor Jehová, en los cuales enviaré hambre a la tierra, no hambre de pan, ni sed de agua, sino de oír la palabra de Jehová. </div>
<div id="Amo_8_12" style="display:none;" class="ver_select"><b>Amo 8:12</b>  E irán errantes de mar a mar: desde el norte hasta el oriente discurrirán buscando palabra de Jehová, y no la hallarán. </div>
<div id="Amo_8_13" style="display:none;" class="ver_select"><b>Amo 8:13</b>  En aquel tiempo las doncellas hermosas y los jóvenes desmayarán de sed. </div>
<div id="Amo_8_14" style="display:none;" class="ver_select"><b>Amo 8:14</b>  Los que juran por el pecado de Samaria, y dicen: Vive tu dios, oh Dan: y: Vive el camino de Beerseba, caerán, y nunca más se levantarán. </div>
<div id="Amo_9_1" style="display:none;" class="ver_select"><b>Amo 9:1</b>  Vi al Señor que estaba sobre el altar, y dijo: Hiere el umbral, y estremézcanse las puertas: y córtales en piezas la cabeza de todos; y el postrero de ellos mataré a espada; no habrá de ellos quien se fugue, ni quien escape. </div>
<div id="Amo_9_2" style="display:none;" class="ver_select"><b>Amo 9:2</b>  Aunque caven hasta el infierno, de allá los tomará mi mano; y si subieren hasta el cielo, de allá los haré descender. </div>
<div id="Amo_9_3" style="display:none;" class="ver_select"><b>Amo 9:3</b>  Y si se escondieren en la cumbre del Carmelo, allí los buscaré y los tomaré; y aunque se escondieren de delante de mis ojos en lo profundo del mar, allí mandaré a la serpiente y los morderá. </div>
<div id="Amo_9_4" style="display:none;" class="ver_select"><b>Amo 9:4</b>  Y si fueren en cautiverio, delante de sus enemigos, allí mandaré la espada, y los matará; y pondré sobre ellos mis ojos para mal, y no para bien. </div>
<div id="Amo_9_5" style="display:none;" class="ver_select"><b>Amo 9:5</b>  El Señor Jehová de los ejércitos es el que toca esta tierra, y se derretirá, y llorarán todos los que en ella moran; y subirá toda como un río, y menguará luego como el río de Egipto. </div>
<div id="Amo_9_6" style="display:none;" class="ver_select"><b>Amo 9:6</b>  El que edifica en el cielo sus cámaras, y ha establecido su expansión sobre la tierra; El que llama a las aguas del mar, y las derrama sobre la faz de la tierra: Jehová es su nombre. </div>
<div id="Amo_9_7" style="display:none;" class="ver_select"><b>Amo 9:7</b>  Hijos de Israel, ¿no me sois vosotros, dice Jehová, como hijos de etíopes? ¿No hice yo subir a Israel de la tierra de Egipto, y a los filisteos de Caftor, y de Kir a los arameos? </div>
<div id="Amo_9_8" style="display:none;" class="ver_select"><b>Amo 9:8</b>  He aquí los ojos del Señor Jehová están contra el reino pecador, y yo lo asolaré de la faz de la tierra; mas no destruiré del todo a la casa de Jacob, dice Jehová. </div>
<div id="Amo_9_9" style="display:none;" class="ver_select"><b>Amo 9:9</b>  Porque he aquí yo mandaré, y haré que la casa de Israel sea zarandeada entre todas las naciones, como se zarandea el grano en un harnero, y no cae un granito en la tierra. </div>
<div id="Amo_9_10" style="display:none;" class="ver_select"><b>Amo 9:10</b>  A espada morirán todos los pecadores de mi pueblo, que dicen: No se acercará, ni nos alcanzará el mal. </div>
<div id="Amo_9_11" style="display:none;" class="ver_select"><b>Amo 9:11</b>  En aquel día yo levantaré el tabernáculo caído de David, y cerraré sus portillos, y levantaré sus ruinas, y lo edificaré como en el tiempo pasado; </div>
<div id="Amo_9_12" style="display:none;" class="ver_select"><b>Amo 9:12</b>  para que aquellos sobre los cuales es invocado mi nombre, posean el resto de Idumea, y a todas las naciones, dice Jehová que hace esto. </div>
<div id="Amo_9_13" style="display:none;" class="ver_select"><b>Amo 9:13</b>  He aquí vienen días, dice Jehová en que el que ara alcanzará al segador, y el pisador de las uvas al que lleva la semilla; y los montes destilarán mosto, y todos los collados se derretirán. </div>
<div id="Amo_9_14" style="display:none;" class="ver_select"><b>Amo 9:14</b>  Y yo traeré el cautiverio de mi pueblo Israel, y ellos edificarán las ciudades asoladas, y las habitarán; y plantarán viñas, y beberán el vino de ellas; y harán huertos, y comerán el fruto de ellos. </div>
<div id="Amo_9_15" style="display:none;" class="ver_select"><b>Amo 9:15</b>  Pues los plantaré sobre su tierra, y nunca más serán arrancados de su tierra que yo les di, dice Jehová Dios tuyo. </div>
