<div id="Dan_1_1" style="display:none;" class="ver_select"><b>Dan 1:1</b>  En el año tercero del reinado de Joacim rey de Judá, vino Nabucodonosor rey de Babilonia a Jerusalén, y la sitió. </div>
<div id="Dan_1_2" style="display:none;" class="ver_select"><b>Dan 1:2</b>  Y el Señor entregó en sus manos a Joacim rey de Judá, y parte de los vasos de la casa de Dios, y los trajo a tierra de Sinar, a la casa de su dios; y metió los vasos en la casa del tesoro de su dios. </div>
<div id="Dan_1_3" style="display:none;" class="ver_select"><b>Dan 1:3</b>  Y dijo el rey a Aspenaz, príncipe de sus eunucos, que trajese de los hijos de Israel, del linaje real de los príncipes, </div>
<div id="Dan_1_4" style="display:none;" class="ver_select"><b>Dan 1:4</b>  muchachos en quienes no hubiese tacha alguna, y de buen parecer, e instruidos en toda sabiduría, y sabios en ciencia, y de buen entendimiento, e idóneos para estar en el palacio del rey; y que les enseñase las letras y la lengua de los caldeos. </div>
<div id="Dan_1_5" style="display:none;" class="ver_select"><b>Dan 1:5</b>  Y el rey les señaló una porción para cada día de la comida del rey y del vino que él bebía; y que los criase tres años, para que al fin de ellos estuviesen delante del rey. </div>
<div id="Dan_1_6" style="display:none;" class="ver_select"><b>Dan 1:6</b>  Y estaban entre ellos, de los hijos de Judá, Daniel, Ananías, Misael y Azarías; </div>
<div id="Dan_1_7" style="display:none;" class="ver_select"><b>Dan 1:7</b>  a los cuales el príncipe de los eunucos puso nombres. A Daniel llamó Beltsasar; y a Ananías, Sadrac; y a Misael, Mesac; y a Azarías, Abed-nego. </div>
<div id="Dan_1_8" style="display:none;" class="ver_select"><b>Dan 1:8</b>  Y Daniel propuso en su corazón no contaminarse con la porción de la comida del rey, ni con el vino que él bebía; pidió, por tanto, al príncipe de los eunucos que se le permitiese no contaminarse. </div>
<div id="Dan_1_9" style="display:none;" class="ver_select"><b>Dan 1:9</b>  Y Dios puso a Daniel en gracia y en buena voluntad con el príncipe de los eunucos; </div>
<div id="Dan_1_10" style="display:none;" class="ver_select"><b>Dan 1:10</b>  y dijo el príncipe de los eunucos a Daniel: Tengo temor de mi señor el rey, que señaló vuestra comida y vuestra bebida; pues luego que él vea vuestros rostros más demacrados que los de los muchachos que son semejantes a vosotros, condenaréis para con el rey mi cabeza. </div>
<div id="Dan_1_11" style="display:none;" class="ver_select"><b>Dan 1:11</b>  Entonces dijo Daniel a Melsar, que estaba puesto por el príncipe de los eunucos sobre Daniel, Ananías, Misael, y Azarías: </div>
<div id="Dan_1_12" style="display:none;" class="ver_select"><b>Dan 1:12</b>  Prueba, te ruego, con tus siervos por diez días, y que nos den legumbres a comer, y agua a beber. </div>
<div id="Dan_1_13" style="display:none;" class="ver_select"><b>Dan 1:13</b>  Parezcan luego delante de ti nuestros rostros, y los rostros de los muchachos que comen de la porción de la comida del rey; y según lo que vieres, harás con tus siervos. </div>
<div id="Dan_1_14" style="display:none;" class="ver_select"><b>Dan 1:14</b>  Consintió, pues, con ellos en esto, y probó con ellos diez días. </div>
<div id="Dan_1_15" style="display:none;" class="ver_select"><b>Dan 1:15</b>  Y al cabo de los diez días pareció el rostro de ellos mejor y más robusto que el de los otros muchachos que comían de la porción de la comida del rey. </div>
<div id="Dan_1_16" style="display:none;" class="ver_select"><b>Dan 1:16</b>  Así fue que Melsar tomaba la porción de la comida de ellos, y el vino que habían de beber, y les daba legumbres. </div>
<div id="Dan_1_17" style="display:none;" class="ver_select"><b>Dan 1:17</b>  Y a estos cuatro muchachos Dios les dio conocimiento e inteligencia en todas las letras y sabiduría; mas Daniel tuvo entendimiento en toda visión y sueños. </div>
<div id="Dan_1_18" style="display:none;" class="ver_select"><b>Dan 1:18</b>  Pasados, pues, los días al fin de los cuales había dicho el rey que los trajesen, el príncipe de los eunucos los trajo delante de Nabucodonosor. </div>
<div id="Dan_1_19" style="display:none;" class="ver_select"><b>Dan 1:19</b>  Y el rey habló con ellos, y de entre todos ellos no se halló ninguno como Daniel, Ananías, Misael, y Azarías; y así estuvieron delante del rey. </div>
<div id="Dan_1_20" style="display:none;" class="ver_select"><b>Dan 1:20</b>  Y en todo asunto de sabiduría e inteligencia que el rey les demandó, los halló diez veces mejores que todos los magos y astrólogos que había en todo su reino. </div>
<div id="Dan_1_21" style="display:none;" class="ver_select"><b>Dan 1:21</b>  Y continuó Daniel hasta el año primero del rey Ciro. </div>
<div id="Dan_2_1" style="display:none;" class="ver_select"><b>Dan 2:1</b>  Y en el segundo año del reinado de Nabucodonosor, soñó Nabucodonosor sueños, y se perturbó su espíritu, y su sueño se fue de él. </div>
<div id="Dan_2_2" style="display:none;" class="ver_select"><b>Dan 2:2</b>  Y el rey mandó llamar a magos, astrólogos, encantadores y caldeos, para que declarasen al rey sus sueños. Vinieron, pues, y se presentaron delante del rey. </div>
<div id="Dan_2_3" style="display:none;" class="ver_select"><b>Dan 2:3</b>  Y el rey les dijo: He tenido un sueño, y mi espíritu se ha perturbado por saber del sueño. </div>
<div id="Dan_2_4" style="display:none;" class="ver_select"><b>Dan 2:4</b>  Entonces hablaron los caldeos al rey en lengua aramea: Rey, para siempre vive; di el sueño a tus siervos, y mostraremos la interpretación. </div>
<div id="Dan_2_5" style="display:none;" class="ver_select"><b>Dan 2:5</b>  Respondió el rey y dijo a los caldeos: El asunto se me fue; si no me mostráis el sueño y su interpretación, seréis descuartizados, y vuestras casas serán puestas por muladares. </div>
<div id="Dan_2_6" style="display:none;" class="ver_select"><b>Dan 2:6</b>  Y si mostrareis el sueño y su interpretación, recibiréis de mí dones y recompensas y grande honra; por tanto, mostradme el sueño y su interpretación. </div>
<div id="Dan_2_7" style="display:none;" class="ver_select"><b>Dan 2:7</b>  Respondieron la segunda vez, y dijeron: Diga el rey el sueño a sus siervos, y mostraremos su interpretación. </div>
<div id="Dan_2_8" style="display:none;" class="ver_select"><b>Dan 2:8</b>  El rey respondió, y dijo: Yo conozco ciertamente que vosotros ponéis dilaciones, porque veis que el asunto se me ha ido. </div>
<div id="Dan_2_9" style="display:none;" class="ver_select"><b>Dan 2:9</b>  Si no me mostráis el sueño, una sola sentencia será de vosotros. Ciertamente preparáis respuesta mentirosa y perversa que decir delante de mí, entre tanto que se pasa el tiempo; por tanto, decidme el sueño, para que yo entienda que me podéis mostrar su interpretación. </div>
<div id="Dan_2_10" style="display:none;" class="ver_select"><b>Dan 2:10</b>  Los caldeos respondieron delante del rey, y dijeron: No hay hombre sobre la tierra que pueda declarar el asunto del rey; pues ningún rey, príncipe, o señor, preguntó cosa semejante a ningún mago, ni astrólogo, ni caldeo. </div>
<div id="Dan_2_11" style="display:none;" class="ver_select"><b>Dan 2:11</b>  Finalmente, el asunto que el rey demanda, es singular, ni hay quien lo pueda declarar delante del rey, salvo los dioses cuya morada no es con la carne. </div>
<div id="Dan_2_12" style="display:none;" class="ver_select"><b>Dan 2:12</b>  Por esta causa el rey se enojó, y enfurecido, mandó que matasen a todos los sabios de Babilonia. </div>
<div id="Dan_2_13" style="display:none;" class="ver_select"><b>Dan 2:13</b>  Y se publicó el decreto, de que los sabios fueran llevados a la muerte; y buscaron a Daniel y a sus compañeros para matarlos. </div>
<div id="Dan_2_14" style="display:none;" class="ver_select"><b>Dan 2:14</b>  Entonces Daniel habló avisada y prudentemente a Arioc, capitán de la guarda del rey, que había salido para matar a los sabios de Babilonia. </div>
<div id="Dan_2_15" style="display:none;" class="ver_select"><b>Dan 2:15</b>  Habló y dijo a Arioc capitán del rey: ¿Cuál es la causa por la que este decreto se publique de parte del rey tan apresuradamente? Entonces Arioc declaró el asunto a Daniel. </div>
<div id="Dan_2_16" style="display:none;" class="ver_select"><b>Dan 2:16</b>  Y Daniel entró y pidió al rey que le diese tiempo, y que él mostraría al rey la interpretación. </div>
<div id="Dan_2_17" style="display:none;" class="ver_select"><b>Dan 2:17</b>  Se fue luego Daniel a su casa, y declaró el asunto a Ananías, Misael, y Azarías, sus compañeros, </div>
<div id="Dan_2_18" style="display:none;" class="ver_select"><b>Dan 2:18</b>  para que pidiesen misericordias del Dios del cielo sobre este misterio, y que Daniel y sus compañeros no pereciesen con los otros sabios de Babilonia. </div>
<div id="Dan_2_19" style="display:none;" class="ver_select"><b>Dan 2:19</b>  Entonces el secreto fue revelado a Daniel en visión de noche; por lo cual bendijo Daniel al Dios del cielo. </div>
<div id="Dan_2_20" style="display:none;" class="ver_select"><b>Dan 2:20</b>  Y Daniel habló, y dijo: Sea bendito el nombre de Dios desde la eternidad hasta la eternidad; porque suya es la sabiduría y el poder. </div>
<div id="Dan_2_21" style="display:none;" class="ver_select"><b>Dan 2:21</b>  Y Él cambia los tiempos y las sazones; quita reyes, y pone reyes; da la sabiduría a los sabios, y la ciencia a los entendidos. </div>
<div id="Dan_2_22" style="display:none;" class="ver_select"><b>Dan 2:22</b>  Él revela lo profundo y lo escondido; conoce lo que está en tinieblas, y la luz mora con Él. </div>
<div id="Dan_2_23" style="display:none;" class="ver_select"><b>Dan 2:23</b>  A ti, oh Dios de mis padres, te doy gracias y te alabo, que me diste sabiduría y fortaleza, y ahora me enseñaste lo que te pedimos; pues nos has enseñado el asunto del rey. </div>
<div id="Dan_2_24" style="display:none;" class="ver_select"><b>Dan 2:24</b>  Después de esto Daniel entró a Arioc, al cual el rey había puesto para matar a los sabios de Babilonia; fue, y le dijo así: No mates a los sabios de Babilonia; llévame delante del rey, que yo mostraré al rey la interpretación. </div>
<div id="Dan_2_25" style="display:none;" class="ver_select"><b>Dan 2:25</b>  Entonces Arioc llevó prestamente a Daniel delante del rey, y le dijo así: He hallado a un varón de los cautivos de Judá, el cual declarará al rey la interpretación. </div>
<div id="Dan_2_26" style="display:none;" class="ver_select"><b>Dan 2:26</b>  Respondió el rey, y dijo a Daniel, al cual llamaban Beltsasar: ¿Podrás tú hacerme entender el sueño que vi, y su interpretación? </div>
<div id="Dan_2_27" style="display:none;" class="ver_select"><b>Dan 2:27</b>  Daniel respondió delante del rey, y dijo: El misterio que el rey demanda, ni sabios, ni astrólogos, ni magos, ni adivinos lo pueden enseñar al rey. </div>
<div id="Dan_2_28" style="display:none;" class="ver_select"><b>Dan 2:28</b>  Mas hay un Dios en el cielo, el cual revela los misterios, y Él ha hecho saber al rey Nabucodonosor lo que ha de acontecer en los postreros días. Tu sueño, y las visiones de tu cabeza sobre tu cama, es esto: </div>
<div id="Dan_2_29" style="display:none;" class="ver_select"><b>Dan 2:29</b>  Estando tú, oh rey, en tu cama subieron tus pensamientos por saber lo que había de suceder en lo por venir; y el que revela los misterios te mostró lo que ha de suceder. </div>
<div id="Dan_2_30" style="display:none;" class="ver_select"><b>Dan 2:30</b>  Y a mí me ha sido revelado este misterio, no porque en mí haya más sabiduría que en todos los vivientes, sino por aquellos que debían de hacer saber al rey la interpretación, y para que tú entendieses los pensamientos de tu corazón. </div>
<div id="Dan_2_31" style="display:none;" class="ver_select"><b>Dan 2:31</b>  Tú, oh rey, veías, y he aquí una gran imagen. Esta imagen, que era muy grande, y cuya gloria era muy sublime, estaba en pie delante de ti, y su aspecto era terrible. </div>
<div id="Dan_2_32" style="display:none;" class="ver_select"><b>Dan 2:32</b>  La cabeza de esta imagen era de oro fino; su pecho y sus brazos, de plata; su vientre y sus muslos, de bronce; </div>
<div id="Dan_2_33" style="display:none;" class="ver_select"><b>Dan 2:33</b>  sus piernas de hierro; sus pies, en parte de hierro, y en parte de barro cocido. </div>
<div id="Dan_2_34" style="display:none;" class="ver_select"><b>Dan 2:34</b>  Estabas mirando, hasta que una piedra fue cortada, no con mano, la cual hirió a la imagen en sus pies de hierro y de barro cocido, y los desmenuzó. </div>
<div id="Dan_2_35" style="display:none;" class="ver_select"><b>Dan 2:35</b>  Entonces fue también desmenuzado el hierro, el barro cocido, el bronce, la plata y el oro, y se tornaron como tamo de las eras del verano; y los levantó el viento, y nunca más se les halló lugar. Mas la piedra que hirió a la imagen, vino a ser una gran montaña, que llenó toda la tierra. </div>
<div id="Dan_2_36" style="display:none;" class="ver_select"><b>Dan 2:36</b>  Éste es el sueño; también la interpretación de él diremos en presencia del rey. </div>
<div id="Dan_2_37" style="display:none;" class="ver_select"><b>Dan 2:37</b>  Tú, oh rey, eres rey de reyes; porque el Dios del cielo te ha dado reino, poder, fortaleza y majestad. </div>
<div id="Dan_2_38" style="display:none;" class="ver_select"><b>Dan 2:38</b>  Y todo lo que habitan los hijos de los hombres, bestias del campo y aves del cielo, Él los ha entregado en tu mano, y te ha dado dominio sobre todo; tú eres aquella cabeza de oro. </div>
<div id="Dan_2_39" style="display:none;" class="ver_select"><b>Dan 2:39</b>  Y después de ti se levantará otro reino menor que tú; y otro tercer reino de bronce, el cual dominará sobre toda la tierra. </div>
<div id="Dan_2_40" style="display:none;" class="ver_select"><b>Dan 2:40</b>  Y el cuarto reino será fuerte como hierro; y como el hierro desmenuza y pulveriza todas las cosas, y como el hierro que quebranta todas estas cosas, desmenuzará y quebrantará. </div>
<div id="Dan_2_41" style="display:none;" class="ver_select"><b>Dan 2:41</b>  Y lo que viste de los pies y los dedos, en parte de barro cocido de alfarero, y en parte de hierro, el reino será dividido; mas habrá en él algo de fortaleza de hierro, según que viste el hierro mezclado con el barro cocido. </div>
<div id="Dan_2_42" style="display:none;" class="ver_select"><b>Dan 2:42</b>  Y por ser los dedos de los pies en parte de hierro, y en parte de barro cocido, en parte será el reino fuerte, y en parte será frágil. </div>
<div id="Dan_2_43" style="display:none;" class="ver_select"><b>Dan 2:43</b>  En cuanto a lo que viste, el hierro mezclado con el barro, se mezclarán por medio de simiente humana, mas no se unirán el uno con el otro, como el hierro no se mezcla con el barro. </div>
<div id="Dan_2_44" style="display:none;" class="ver_select"><b>Dan 2:44</b>  Y en los días de estos reyes, el Dios del cielo levantará un reino que jamás será destruido, y este reino no será dejado a otro pueblo; desmenuzará y consumirá a todos estos reinos, y él permanecerá para siempre. </div>
<div id="Dan_2_45" style="display:none;" class="ver_select"><b>Dan 2:45</b>  De la manera que viste que del monte fue cortada una piedra, no con manos, la cual desmenuzó al hierro, al bronce, al barro, a la plata, y al oro; el gran Dios ha mostrado al rey lo que ha de acontecer en lo por venir; y el sueño es verdadero, y fiel su interpretación. </div>
<div id="Dan_2_46" style="display:none;" class="ver_select"><b>Dan 2:46</b>  Entonces el rey Nabucodonosor cayó sobre su rostro, y se humilló ante Daniel, y mandó que le ofreciesen presentes y perfumes. </div>
<div id="Dan_2_47" style="display:none;" class="ver_select"><b>Dan 2:47</b>  El rey habló a Daniel, y dijo: Ciertamente que el Dios vuestro es Dios de dioses, y Señor de los reyes, y el que revela los misterios, pues pudiste revelar este misterio. </div>
<div id="Dan_2_48" style="display:none;" class="ver_select"><b>Dan 2:48</b>  Entonces el rey engrandeció a Daniel, y le dio muchos y grandes dones, y lo puso por gobernador de toda la provincia de Babilonia, y por príncipe de los gobernadores sobre todos los sabios de Babilonia. </div>
<div id="Dan_2_49" style="display:none;" class="ver_select"><b>Dan 2:49</b>  Y Daniel solicitó del rey, y él puso sobre los negocios de la provincia de Babilonia a Sadrac, Mesac, y Abed-nego: y Daniel estaba a la puerta del rey. </div>
<div id="Dan_3_1" style="display:none;" class="ver_select"><b>Dan 3:1</b>  El rey Nabucodonosor hizo una estatua de oro, la altura de la cual era de sesenta codos, su anchura de seis codos; la levantó en el campo de Dura, en la provincia de Babilonia. </div>
<div id="Dan_3_2" style="display:none;" class="ver_select"><b>Dan 3:2</b>  Y envió el rey Nabucodonosor a juntar los grandes, los asistentes y capitanes, oidores, receptores, los del consejo, presidentes, y a todos los gobernadores de las provincias, para que viniesen a la dedicación de la estatua que el rey Nabucodonosor había levantado. </div>
<div id="Dan_3_3" style="display:none;" class="ver_select"><b>Dan 3:3</b>  Fueron, pues, reunidos los príncipes, los asistentes y capitanes, los jueces, los tesoreros, los consejeros, los presidentes, y todos los gobernadores de las provincias, a la dedicación de la estatua que el rey Nabucodonosor había levantado; y estaban en pie delante de la estatua que había levantado el rey Nabucodonosor. </div>
<div id="Dan_3_4" style="display:none;" class="ver_select"><b>Dan 3:4</b>  Y el pregonero anunciaba en alta voz: Se ordena a vosotros, oh pueblos, naciones, y lenguas, </div>
<div id="Dan_3_5" style="display:none;" class="ver_select"><b>Dan 3:5</b>  que al oír el son de la bocina, de la flauta, del tamboril, del arpa, del salterio, de la zampoña, y de todo instrumento de música, os postréis y adoréis la estatua de oro que el rey Nabucodonosor ha levantado; </div>
<div id="Dan_3_6" style="display:none;" class="ver_select"><b>Dan 3:6</b>  y cualquiera que no se postre y adore, en la misma hora será echado dentro de un horno de fuego ardiendo. </div>
<div id="Dan_3_7" style="display:none;" class="ver_select"><b>Dan 3:7</b>  Por lo cual, al oír todos los pueblos el son de la bocina, de la flauta, del tamboril, del arpa, del salterio, de la zampoña, y de todo instrumento de música, todos los pueblos, naciones, y lenguas, se postraron, y adoraron la estatua de oro que el rey Nabucodonosor había levantado. </div>
<div id="Dan_3_8" style="display:none;" class="ver_select"><b>Dan 3:8</b>  Por esto en aquel tiempo algunos varones caldeos vinieron, y denunciaron a los judíos. </div>
<div id="Dan_3_9" style="display:none;" class="ver_select"><b>Dan 3:9</b>  Hablando y diciendo al rey Nabucodonosor: Rey, para siempre vive. </div>
<div id="Dan_3_10" style="display:none;" class="ver_select"><b>Dan 3:10</b>  Tú, oh rey, diste una ley que todo hombre al oír el son de la bocina, de la flauta, del tamboril, del arpa, del salterio, de la zampoña, y de todo instrumento de música, se postrase y adorase la estatua de oro; </div>
<div id="Dan_3_11" style="display:none;" class="ver_select"><b>Dan 3:11</b>  y el que no se postrase y adorase, fuese echado dentro de un horno de fuego ardiendo. </div>
<div id="Dan_3_12" style="display:none;" class="ver_select"><b>Dan 3:12</b>  Hay unos varones judíos, los cuales pusiste tú sobre los negocios de la provincia de Babilonia; Sadrac, Mesac, y Abed-nego; estos varones, oh rey, no han hecho cuenta de ti; no adoran tus dioses, no adoran la estatua de oro que tú levantaste. </div>
<div id="Dan_3_13" style="display:none;" class="ver_select"><b>Dan 3:13</b>  Entonces Nabucodonosor con ira y con enojo mandó que trajesen a Sadrac, Mesac, y Abed-nego. Y al punto fueron traídos estos varones delante del rey. </div>
<div id="Dan_3_14" style="display:none;" class="ver_select"><b>Dan 3:14</b>  Habló Nabucodonosor, y les dijo: ¿Es verdad Sadrac, Mesac, y Abed-nego, que vosotros no honráis a mis dioses, ni adoráis la estatua de oro que he levantado? </div>
<div id="Dan_3_15" style="display:none;" class="ver_select"><b>Dan 3:15</b>  Ahora, pues, ¿estáis dispuestos para que al oír el son de la bocina, de la flauta, del tamboril, del arpa, del salterio, de la zampoña, y de todo instrumento de música, os postréis, y adoréis la estatua que he hecho? Porque si no la adorareis, en la misma hora seréis echados en medio de un horno de fuego ardiendo; ¿y quién será el Dios que os pueda librar de mis manos? </div>
<div id="Dan_3_16" style="display:none;" class="ver_select"><b>Dan 3:16</b>  Sadrac, Mesac, y Abed-nego respondieron y dijeron al rey Nabucodonosor: No tenemos necesidad de responderte sobre este asunto. </div>
<div id="Dan_3_17" style="display:none;" class="ver_select"><b>Dan 3:17</b>  He aquí nuestro Dios a quien servimos, puede librarnos del horno de fuego ardiendo; y de tu mano, oh rey, nos librará. </div>
<div id="Dan_3_18" style="display:none;" class="ver_select"><b>Dan 3:18</b>  Y si no, sepas, oh rey, que no serviremos a tus dioses, ni tampoco adoraremos la estatua de oro que has levantado. </div>
<div id="Dan_3_19" style="display:none;" class="ver_select"><b>Dan 3:19</b>  Entonces Nabucodonosor se llenó de ira, y se demudó el aspecto de su rostro contra Sadrac, Mesac, y Abed-nego; por lo cual habló, y ordenó que el horno se calentase siete veces más de lo que solían calentarlo. </div>
<div id="Dan_3_20" style="display:none;" class="ver_select"><b>Dan 3:20</b>  Y mandó a hombres muy vigorosos que tenía en su ejército, que atasen a Sadrac, Mesac, y Abed-nego, para echarlos en el horno de fuego ardiendo. </div>
<div id="Dan_3_21" style="display:none;" class="ver_select"><b>Dan 3:21</b>  Entonces estos varones fueron atados con sus mantos, y sus calzas, y sus mitras, y sus demás vestiduras, y fueron echados dentro del horno de fuego ardiendo. </div>
<div id="Dan_3_22" style="display:none;" class="ver_select"><b>Dan 3:22</b>  Y porque la orden del rey era apremiante, y habían calentado mucho el horno, la llama del fuego mató a aquellos que habían alzado a Sadrac, Mesac, y Abed-nego. </div>
<div id="Dan_3_23" style="display:none;" class="ver_select"><b>Dan 3:23</b>  Y estos tres varones, Sadrac, Mesac, y Abed-nego, cayeron atados dentro del horno de fuego ardiendo. </div>
<div id="Dan_3_24" style="display:none;" class="ver_select"><b>Dan 3:24</b>  Entonces el rey Nabucodonosor se espantó, y se levantó de prisa, y habló, y dijo a los de su consejo: ¿No echaron tres varones atados dentro del fuego? Ellos respondieron y dijeron al rey: Es verdad, oh rey. </div>
<div id="Dan_3_25" style="display:none;" class="ver_select"><b>Dan 3:25</b>  Respondió él y dijo: He aquí yo veo cuatro varones sueltos, que se pasean en medio del fuego, y ningún daño hay en ellos; y el parecer del cuarto es semejante al Hijo de Dios. </div>
<div id="Dan_3_26" style="display:none;" class="ver_select"><b>Dan 3:26</b>  Entonces Nabucodonosor se acercó a la puerta del horno de fuego ardiendo, y habló y dijo: Sadrac, Mesac, y Abed-nego, siervos del Dios Altísimo, salid y venid. Entonces Sadrac, Mesac, y Abed-nego salieron de en medio del fuego. </div>
<div id="Dan_3_27" style="display:none;" class="ver_select"><b>Dan 3:27</b>  Y se juntaron los grandes, los gobernadores, los capitanes, y los del consejo del rey, para mirar estos varones, cómo el fuego no se enseñoreó de sus cuerpos, ni cabello de sus cabezas fue quemado, ni sus ropas se mudaron, ni olor de fuego había pasado por ellos. </div>
<div id="Dan_3_28" style="display:none;" class="ver_select"><b>Dan 3:28</b>  Nabucodonosor habló y dijo: Bendito el Dios de ellos, de Sadrac, Mesac, y Abed-nego, que envió su Ángel, y libró sus siervos que esperaron en Él, y el mandamiento del rey mudaron, y entregaron sus cuerpos antes que servir o adorar a otro dios que su Dios. </div>
<div id="Dan_3_29" style="display:none;" class="ver_select"><b>Dan 3:29</b>  Por tanto, yo decreto que todo pueblo, nación, o lengua, que dijere blasfemia contra el Dios de Sadrac, Mesac y Abed-nego, sea descuartizado, y su casa sea puesta por muladar; por cuanto no hay otro Dios que pueda librar como Éste. </div>
<div id="Dan_3_30" style="display:none;" class="ver_select"><b>Dan 3:30</b>  Entonces el rey engrandeció a Sadrac, Mesac, y Abed-nego en la provincia de Babilonia. </div>
<div id="Dan_4_1" style="display:none;" class="ver_select"><b>Dan 4:1</b>  Nabucodonosor rey, a todos los pueblos, naciones, y lenguas, que moran en toda la tierra: Paz os sea multiplicada: </div>
<div id="Dan_4_2" style="display:none;" class="ver_select"><b>Dan 4:2</b>  Me ha parecido bien publicar las señales y milagros que el Dios Altísimo ha hecho conmigo. </div>
<div id="Dan_4_3" style="display:none;" class="ver_select"><b>Dan 4:3</b>  ¡Cuán grandes son sus señales, y cuán poderosas sus maravillas! Su reino, reino sempiterno, y su señorío de generación en generación. </div>
<div id="Dan_4_4" style="display:none;" class="ver_select"><b>Dan 4:4</b>  Yo Nabucodonosor estaba tranquilo en mi casa, y próspero en mi palacio. </div>
<div id="Dan_4_5" style="display:none;" class="ver_select"><b>Dan 4:5</b>  Vi un sueño que me espantó, y las imaginaciones y visiones de mi cabeza me turbaron en mi cama. </div>
<div id="Dan_4_6" style="display:none;" class="ver_select"><b>Dan 4:6</b>  Por lo cual yo di mandamiento para hacer venir delante de mí a todos los sabios de Babilonia, a fin de que me hiciesen saber la interpretación del sueño. </div>
<div id="Dan_4_7" style="display:none;" class="ver_select"><b>Dan 4:7</b>  Y vinieron magos, astrólogos, caldeos, y adivinos; y dije el sueño delante de ellos, mas ellos no me dieron a conocer su interpretación; </div>
<div id="Dan_4_8" style="display:none;" class="ver_select"><b>Dan 4:8</b>  Hasta que entró delante de mí Daniel, cuyo nombre es Beltsasar, como el nombre de mi dios, y en el cual hay espíritu de los dioses santos, y dije el sueño delante de él, diciendo: </div>
<div id="Dan_4_9" style="display:none;" class="ver_select"><b>Dan 4:9</b>  Beltsasar, príncipe de los magos, ya que he entendido que hay en ti espíritu de los dioses santos, y que ningún misterio se te esconde, dime las visiones de mi sueño que he visto, y su interpretación. </div>
<div id="Dan_4_10" style="display:none;" class="ver_select"><b>Dan 4:10</b>  Éstas son las visiones de mi cabeza cuando estaba en mi cama: Me parecía que veía un árbol en medio de la tierra, cuya altura era grande. </div>
<div id="Dan_4_11" style="display:none;" class="ver_select"><b>Dan 4:11</b>  Crecía este árbol, y se hacía fuerte, y su altura llegaba hasta el cielo, y su vista hasta el cabo de toda la tierra. </div>
<div id="Dan_4_12" style="display:none;" class="ver_select"><b>Dan 4:12</b>  Su follaje era hermoso, y su fruto en abundancia, y para todos había en él mantenimiento. Debajo de él se ponían a la sombra las bestias del campo, y en sus ramas hacían morada las aves del cielo, y se mantenía de él toda carne. </div>
<div id="Dan_4_13" style="display:none;" class="ver_select"><b>Dan 4:13</b>  Veía en las visiones de mi cabeza estando en mi cama, y he aquí que un vigilante y santo descendía del cielo. </div>
<div id="Dan_4_14" style="display:none;" class="ver_select"><b>Dan 4:14</b>  Y clamaba fuertemente y decía así: Derribad el árbol, y cortad sus ramas, quitadle su follaje, y derramad su fruto: váyanse las bestias que están debajo de él, y las aves de sus ramas. </div>
<div id="Dan_4_15" style="display:none;" class="ver_select"><b>Dan 4:15</b>  Mas la cepa de sus raíces dejaréis en la tierra, y con atadura de hierro y de bronce entre la hierba del campo; y sea mojado con el rocío del cielo, y su parte con las bestias en la hierba de la tierra. </div>
<div id="Dan_4_16" style="display:none;" class="ver_select"><b>Dan 4:16</b>  Sea mudado su corazón de hombre, y le sea dado corazón de bestia, y pasen sobre él siete tiempos. </div>
<div id="Dan_4_17" style="display:none;" class="ver_select"><b>Dan 4:17</b>  La sentencia es por decreto de los vigilantes, y por dicho de los santos la demanda: para que conozcan los vivientes que el Altísimo señorea en el reino de los hombres, y que a quien Él quiere lo da, y constituye sobre él al más bajo de los hombres. </div>
<div id="Dan_4_18" style="display:none;" class="ver_select"><b>Dan 4:18</b>  Yo el rey Nabucodonosor he visto este sueño. Tú, pues, Beltsasar, dirás la interpretación de él, porque todos los sabios de mi reino nunca pudieron mostrarme su interpretación; mas tú puedes, porque hay en ti espíritu de los dioses santos. </div>
<div id="Dan_4_19" style="display:none;" class="ver_select"><b>Dan 4:19</b>  Entonces Daniel, cuyo nombre era Beltsasar, estuvo atónito por una hora, y sus pensamientos lo espantaban: El rey habló, y dijo: Beltsasar, no te espante el sueño ni su interpretación. Respondió Beltsasar, y dijo: Señor mío, el sueño sea para los que te aborrecen, y su interpretación para tus enemigos. </div>
<div id="Dan_4_20" style="display:none;" class="ver_select"><b>Dan 4:20</b>  El árbol que viste, que crecía y se hacía fuerte, y que su altura llegaba hasta el cielo, y era visible a toda la tierra; </div>
<div id="Dan_4_21" style="display:none;" class="ver_select"><b>Dan 4:21</b>  y cuyo follaje era hermoso, y su fruto en abundancia, y que para todos había mantenimiento en él; debajo del cual moraban las bestias del campo, y en sus ramas habitaban las aves del cielo, </div>
<div id="Dan_4_22" style="display:none;" class="ver_select"><b>Dan 4:22</b>  eres tú mismo, oh rey, que creciste, y te hiciste fuerte, pues creció tu grandeza, y ha llegado hasta el cielo, y tu señorío hasta el cabo de la tierra. </div>
<div id="Dan_4_23" style="display:none;" class="ver_select"><b>Dan 4:23</b>  Y en cuanto a lo que vio el rey, un vigilante y santo que descendía del cielo, y decía: Cortad el árbol y destruidlo; mas la cepa de sus raíces dejaréis en la tierra, y con atadura de hierro y de bronce en la hierba del campo; y sea mojado con el rocío del cielo, y su parte sea con las bestias del campo, hasta que pasen sobre él siete tiempos; </div>
<div id="Dan_4_24" style="display:none;" class="ver_select"><b>Dan 4:24</b>  ésta es la interpretación, oh rey, y la sentencia del Altísimo, que ha venido sobre el rey mi señor: </div>
<div id="Dan_4_25" style="display:none;" class="ver_select"><b>Dan 4:25</b>  Que te echarán de entre los hombres, y con las bestias del campo será tu morada, y te harán comer hierba del campo, como a los bueyes, y con rocío del cielo serás bañado; y siete tiempos pasarán sobre ti, hasta que entiendas que el Altísimo señorea en el reino de los hombres, y que a quien Él quiere lo da. </div>
<div id="Dan_4_26" style="display:none;" class="ver_select"><b>Dan 4:26</b>  Y lo que dijeron, que dejasen en la tierra la cepa de las raíces del mismo árbol, significa que tu reino te quedará firme, luego que reconozcas que el señorío es de los cielos. </div>
<div id="Dan_4_27" style="display:none;" class="ver_select"><b>Dan 4:27</b>  Por tanto, oh rey, acepta mi consejo, y rompe con tus pecados mediante justicia, y con tus iniquidades mediante misericordias para con los pobres; que tal vez será eso una prolongación de tu tranquilidad. </div>
<div id="Dan_4_28" style="display:none;" class="ver_select"><b>Dan 4:28</b>  Todo esto vino sobre el rey Nabucodonosor. </div>
<div id="Dan_4_29" style="display:none;" class="ver_select"><b>Dan 4:29</b>  Al cabo de doce meses, paseando en el palacio del reino de Babilonia, </div>
<div id="Dan_4_30" style="display:none;" class="ver_select"><b>Dan 4:30</b>  habló el rey, y dijo: ¿No es ésta la gran Babilonia, que yo edifiqué para casa del reino, con la fuerza de mi poder, y para gloria de mi grandeza? </div>
<div id="Dan_4_31" style="display:none;" class="ver_select"><b>Dan 4:31</b>  Aún estaba la palabra en la boca del rey, cuando descendió una voz del cielo, diciendo: A ti se te dice, rey Nabucodonosor; el reino es traspasado de ti: </div>
<div id="Dan_4_32" style="display:none;" class="ver_select"><b>Dan 4:32</b>  Y de entre los hombres te echan, y con las bestias del campo será tu morada, y como a los bueyes te apacentarán: y siete tiempos pasarán sobre ti, hasta que reconozcas que el Altísimo señorea en el reino de los hombres, y que a quien Él quiere lo da. </div>
<div id="Dan_4_33" style="display:none;" class="ver_select"><b>Dan 4:33</b>  En la misma hora se cumplió la palabra sobre Nabucodonosor, y fue echado de entre los hombres; y comía hierba como los bueyes, y su cuerpo se bañaba con el rocío del cielo, hasta que su pelo creció como las plumas de águila, y sus uñas como de aves. </div>
<div id="Dan_4_34" style="display:none;" class="ver_select"><b>Dan 4:34</b>  Mas al fin del tiempo yo Nabucodonosor alcé mis ojos al cielo, y mi sentido me fue vuelto; y bendije al Altísimo, y alabé y glorifiqué al que vive para siempre; porque su señorío es eterno, y su reino por todas las edades. </div>
<div id="Dan_4_35" style="display:none;" class="ver_select"><b>Dan 4:35</b>  Y todos los moradores de la tierra son estimados como nada; y Él hace según su voluntad en el ejército del cielo, y en los habitantes de la tierra; no hay quien estorbe su mano, y le diga: ¿Qué haces? </div>
<div id="Dan_4_36" style="display:none;" class="ver_select"><b>Dan 4:36</b>  En el mismo tiempo mi sentido me fue vuelto, y la majestad de mi reino, mi dignidad y mi grandeza volvieron a mí, y mis gobernadores y mis grandes me buscaron; y fui restituido a mi reino, y mayor grandeza me fue añadida. </div>
<div id="Dan_4_37" style="display:none;" class="ver_select"><b>Dan 4:37</b>  Ahora yo Nabucodonosor alabo, engrandezco y glorifico al Rey del cielo, porque todas sus obras son verdad, y sus caminos juicio; y humillar puede a los que andan con soberbia. </div>
<div id="Dan_5_1" style="display:none;" class="ver_select"><b>Dan 5:1</b>  El rey Belsasar hizo un gran banquete a mil de sus príncipes, y en presencia de los mil bebía vino. </div>
<div id="Dan_5_2" style="display:none;" class="ver_select"><b>Dan 5:2</b>  Belsasar, con el gusto del vino, mandó que trajesen los vasos de oro y de plata que Nabucodonosor su padre había traído del templo de Jerusalén; para que bebiesen con ellos el rey y sus príncipes, sus esposas y sus concubinas. </div>
<div id="Dan_5_3" style="display:none;" class="ver_select"><b>Dan 5:3</b>  Entonces fueron traídos los vasos de oro que habían traído del templo de la casa de Dios que estaba en Jerusalén, y bebieron con ellos el rey y sus príncipes, sus esposas y sus concubinas. </div>
<div id="Dan_5_4" style="display:none;" class="ver_select"><b>Dan 5:4</b>  Bebieron vino, y alabaron a los dioses de oro y de plata, de bronce, de hierro, de madera y de piedra. </div>
<div id="Dan_5_5" style="display:none;" class="ver_select"><b>Dan 5:5</b>  En aquella misma hora salieron unos dedos de mano de hombre, y escribían delante del candelero sobre lo encalado de la pared del palacio real, y el rey veía la palma de la mano que escribía. </div>
<div id="Dan_5_6" style="display:none;" class="ver_select"><b>Dan 5:6</b>  Entonces demudó el semblante del rey, y sus pensamientos lo turbaron, y se desataron las ceñiduras de sus lomos, y sus rodillas se batían la una con la otra. </div>
<div id="Dan_5_7" style="display:none;" class="ver_select"><b>Dan 5:7</b>  El rey gritó en alta voz que hiciesen venir astrólogos, caldeos, y adivinos. Habló el rey, y dijo a los sabios de Babilonia: Cualquiera que leyere esta escritura, y me mostrare su interpretación, será vestido de púrpura, y tendrá collar de oro a su cuello; y gobernará como el tercero en el reino. </div>
<div id="Dan_5_8" style="display:none;" class="ver_select"><b>Dan 5:8</b>  Entonces fueron introducidos todos los sabios del rey, y no pudieron leer la escritura, ni mostrar al rey su interpretación. </div>
<div id="Dan_5_9" style="display:none;" class="ver_select"><b>Dan 5:9</b>  Entonces el rey Belsasar se turbó en gran manera, y se le demudó su semblante y sus príncipes quedaron atónitos. </div>
<div id="Dan_5_10" style="display:none;" class="ver_select"><b>Dan 5:10</b>  La reina, por las palabras del rey y de sus príncipes, entró a la sala del banquete. Y habló la reina, y dijo: Rey, para siempre vive, no te asombren tus pensamientos, ni demude tu semblante. </div>
<div id="Dan_5_11" style="display:none;" class="ver_select"><b>Dan 5:11</b>  En tu reino hay un varón, en el cual mora el espíritu de los dioses santos; y en los días de tu padre se halló en él luz e inteligencia y sabiduría, como la sabiduría de los dioses; al cual tu padre el rey Nabucodonosor, digo, tu padre el rey, constituyó príncipe sobre todos los magos, astrólogos, caldeos y adivinos; </div>
<div id="Dan_5_12" style="display:none;" class="ver_select"><b>Dan 5:12</b>  por cuanto fue hallado en él un mayor espíritu y conocimiento e inteligencia, para interpretar sueños, descifrar enigmas y deshacer dudas, es decir, en Daniel; al cual el rey puso por nombre Beltsasar. Llámese, pues, ahora a Daniel, y él mostrará la interpretación. </div>
<div id="Dan_5_13" style="display:none;" class="ver_select"><b>Dan 5:13</b>  Entonces Daniel fue traído delante del rey. Y habló el rey, y dijo a Daniel: ¿Eres tú aquel Daniel de los hijos de la cautividad de Judá, que mi padre trajo de Judea? </div>
<div id="Dan_5_14" style="display:none;" class="ver_select"><b>Dan 5:14</b>  Yo he oído de ti que el espíritu de los dioses santos está en ti, y que en ti se halló luz, y entendimiento y mayor sabiduría. </div>
<div id="Dan_5_15" style="display:none;" class="ver_select"><b>Dan 5:15</b>  Y ahora fueron traídos delante de mí, sabios, astrólogos, que leyesen esta escritura, y me mostrasen su interpretación: pero no han podido mostrar la declaración del asunto. </div>
<div id="Dan_5_16" style="display:none;" class="ver_select"><b>Dan 5:16</b>  Yo pues he oído de ti que puedes interpretar sueños y disolver las dudas. Si ahora pudieres leer esta escritura, y mostrarme su interpretación, serás vestido de púrpura, y collar de oro tendrás en tu cuello, y en el reino serás el tercer señor. </div>
<div id="Dan_5_17" style="display:none;" class="ver_select"><b>Dan 5:17</b>  Entonces Daniel respondió, y dijo delante del rey: Tus dones sean para ti, y tus presentes dalos a otro. La escritura yo la leeré al rey, y le declararé la interpretación. </div>
<div id="Dan_5_18" style="display:none;" class="ver_select"><b>Dan 5:18</b>  El Altísimo Dios, oh rey, dio a Nabucodonosor tu padre el reino, y la grandeza, y la gloria, y la honra. </div>
<div id="Dan_5_19" style="display:none;" class="ver_select"><b>Dan 5:19</b>  Y por la grandeza que le dio, todos los pueblos, naciones, y lenguas, temblaban y temían delante de él. A quien quería, mataba, y a quien quería, dejaba con vida; a quien quería, engrandecía, y a quien quería, humillaba. </div>
<div id="Dan_5_20" style="display:none;" class="ver_select"><b>Dan 5:20</b>  Mas cuando su corazón se ensoberbeció, y su espíritu se endureció en altivez, fue depuesto del trono de su reino, y traspasaron de él la gloria: </div>
<div id="Dan_5_21" style="display:none;" class="ver_select"><b>Dan 5:21</b>  Y fue echado de entre los hijos de los hombres; y su corazón fue puesto con las bestias, y con los asnos monteses fue su morada. Hierba le hicieron comer, como a buey, y su cuerpo fue bañado con el rocío del cielo, hasta que reconoció que el Altísimo Dios señorea en el reino de los hombres, y que pone sobre él a quien le place. </div>
<div id="Dan_5_22" style="display:none;" class="ver_select"><b>Dan 5:22</b>  Y tú, su hijo Belsasar, no has humillado tu corazón, sabiendo todo esto: </div>
<div id="Dan_5_23" style="display:none;" class="ver_select"><b>Dan 5:23</b>  sino que contra el Señor del cielo te has ensoberbecido, e hiciste traer delante de ti los vasos de su casa, y tú y tus príncipes, tus esposas y tus concubinas habéis bebido vino en ellos; además de esto diste alabanza a dioses de plata y de oro, de bronce, de hierro, de madera y de piedra, que ni vn, ni oyen, ni saben; y al Dios en cuya mano está tu vida, y de quien son todos tus caminos, no honraste. </div>
<div id="Dan_5_24" style="display:none;" class="ver_select"><b>Dan 5:24</b>  Entonces de su presencia fue enviada la palma de la mano que esculpió esta escritura. </div>
<div id="Dan_5_25" style="display:none;" class="ver_select"><b>Dan 5:25</b>  Y la escritura que esculpió es: MENE, MENE, TEKEL, UPARSIN. </div>
<div id="Dan_5_26" style="display:none;" class="ver_select"><b>Dan 5:26</b>  Ésta es la interpretación del asunto: MENE: Contó Dios tu reino, y le ha puesto fin. </div>
<div id="Dan_5_27" style="display:none;" class="ver_select"><b>Dan 5:27</b>  TEKEL: Pesado has sido en balanza y fuiste hallado falto. </div>
<div id="Dan_5_28" style="display:none;" class="ver_select"><b>Dan 5:28</b>  PERES: Tu reino ha sido dividido, y dado a los medos y a los persas. </div>
<div id="Dan_5_29" style="display:none;" class="ver_select"><b>Dan 5:29</b>  Entonces, mandándolo Belsasar, vistieron a Daniel de púrpura, y en su cuello fue puesto un collar de oro, y pregonaron de él que fuese el tercer señor en el reino. </div>
<div id="Dan_5_30" style="display:none;" class="ver_select"><b>Dan 5:30</b>  La misma noche fue muerto Belsasar, rey de los caldeos. </div>
<div id="Dan_5_31" style="display:none;" class="ver_select"><b>Dan 5:31</b>  Y Darío de Media tomó el reino, siendo de sesenta y dos años. </div>
<div id="Dan_6_1" style="display:none;" class="ver_select"><b>Dan 6:1</b>  Pareció bien a Darío constituir sobre el reino ciento veinte gobernadores, que estuviesen en todo el reino. </div>
<div id="Dan_6_2" style="display:none;" class="ver_select"><b>Dan 6:2</b>  Y sobre ellos tres presidentes (de los cuales Daniel era el primero), a quienes estos gobernadores diesen cuenta, para que el rey no recibiese daño. </div>
<div id="Dan_6_3" style="display:none;" class="ver_select"><b>Dan 6:3</b>  Pero el mismo Daniel era más estimado que estos gobernadores y presidentes, porque en él había un espíritu excelente; y el rey pensaba en ponerlo sobre todo el reino. </div>
<div id="Dan_6_4" style="display:none;" class="ver_select"><b>Dan 6:4</b>  Entonces los presidentes y gobernadores buscaban ocasiones contra Daniel por parte del reino; mas no podían hallar alguna ocasión o falta, porque él era fiel, y ningún vicio ni falta fue hallado en él. </div>
<div id="Dan_6_5" style="display:none;" class="ver_select"><b>Dan 6:5</b>  Entonces dijeron aquellos hombres: No hallaremos contra este Daniel ocasión alguna, si no la hallamos contra él en relación a la ley de su Dios. </div>
<div id="Dan_6_6" style="display:none;" class="ver_select"><b>Dan 6:6</b>  Entonces estos gobernadores y presidentes se juntaron delante del rey, y le dijeron así: Rey Darío, para siempre vive: </div>
<div id="Dan_6_7" style="display:none;" class="ver_select"><b>Dan 6:7</b>  Todos los presidentes del reino, magistrados, gobernadores, grandes y capitanes, han acordado por consejo promulgar un real edicto, y confirmarlo, que cualquiera que demandare petición de cualquier dios u hombre en el espacio de treinta días, excepto de ti, oh rey, sea echado en el foso de los leones. </div>
<div id="Dan_6_8" style="display:none;" class="ver_select"><b>Dan 6:8</b>  Ahora, oh rey, confirma el edicto, y firma la escritura, para que no pueda ser cambiada, conforme a la ley de Media y de Persia, la cual no puede ser revocada. </div>
<div id="Dan_6_9" style="display:none;" class="ver_select"><b>Dan 6:9</b>  Firmó, pues, el rey Darío la escritura y el edicto. </div>
<div id="Dan_6_10" style="display:none;" class="ver_select"><b>Dan 6:10</b>  Y Daniel, cuando supo que la escritura estaba firmada, entró en su casa, y abiertas las ventanas de su cámara que estaban hacia Jerusalén, se hincaba de rodillas tres veces al día, y oraba, y daba gracias delante de su Dios, como lo solía hacer antes. </div>
<div id="Dan_6_11" style="display:none;" class="ver_select"><b>Dan 6:11</b>  Entonces se juntaron aquellos hombres, y hallaron a Daniel orando y suplicando delante de su Dios. </div>
<div id="Dan_6_12" style="display:none;" class="ver_select"><b>Dan 6:12</b>  Se llegaron luego, y hablaron delante del rey acerca del edicto real: ¿No has confirmado edicto que cualquiera que pidiere a cualquier dios u hombre en el espacio de treinta días, excepto a ti, oh rey, fuese echado en el foso de los leones? Respondió el rey y dijo: Verdad es, conforme a la ley de Media y de Persia, la cual no se abroga. </div>
<div id="Dan_6_13" style="display:none;" class="ver_select"><b>Dan 6:13</b>  Entonces respondieron y dijeron delante del rey: Ese Daniel, que es de los hijos de la cautividad de los judíos, no ha hecho cuenta de ti, oh rey, ni del edicto que confirmaste; antes tres veces al día hace su petición. </div>
<div id="Dan_6_14" style="display:none;" class="ver_select"><b>Dan 6:14</b>  Entonces el rey, al oír estas palabras, le pesó en gran manera, y sobre Daniel puso cuidado para librarlo; y hasta la puesta del sol trabajó para librarle. </div>
<div id="Dan_6_15" style="display:none;" class="ver_select"><b>Dan 6:15</b>  Pero aquellos hombres se reunieron cerca del rey, y dijeron al rey: Sepas, oh rey, que es ley de Media y de Persia, que ningún decreto u ordenanza que el rey confirmare puede ser cambiado. </div>
<div id="Dan_6_16" style="display:none;" class="ver_select"><b>Dan 6:16</b>  Entonces el rey mandó, y trajeron a Daniel, y le echaron en el foso de los leones. Y hablando el rey dijo a Daniel: El Dios tuyo, a quien tú continuamente sirves, Él te librará. </div>
<div id="Dan_6_17" style="display:none;" class="ver_select"><b>Dan 6:17</b>  Y fue traída una piedra, y puesta sobre la puerta del foso, la cual selló el rey con su anillo, y con el anillo de sus príncipes, para que el acuerdo acerca de Daniel no se cambiase. </div>
<div id="Dan_6_18" style="display:none;" class="ver_select"><b>Dan 6:18</b>  Se fue luego el rey a su palacio, y pasó la noche en ayuno; ni instrumentos de música fueron traídos delante de él, y se le fue el sueño. </div>
<div id="Dan_6_19" style="display:none;" class="ver_select"><b>Dan 6:19</b>  Entonces el rey se levantó muy de mañana, y fue aprisa al foso de los leones: </div>
<div id="Dan_6_20" style="display:none;" class="ver_select"><b>Dan 6:20</b>  y llegándose cerca del foso llamó a voces a Daniel con voz triste. Y el rey habló a Daniel y le dijo: Daniel, siervo del Dios viviente, el Dios tuyo, a quien tú continuamente sirves ¿te ha podido librar de los leones? </div>
<div id="Dan_6_21" style="display:none;" class="ver_select"><b>Dan 6:21</b>  Entonces habló Daniel con el rey: Oh rey, para siempre vive. </div>
<div id="Dan_6_22" style="display:none;" class="ver_select"><b>Dan 6:22</b>  El Dios mío envió su ángel, el cual cerró la boca de los leones, para que no me hiciesen mal: porque delante de Él fui hallado inocente; y aun delante de ti, oh rey, yo no he hecho ningún mal. </div>
<div id="Dan_6_23" style="display:none;" class="ver_select"><b>Dan 6:23</b>  Entonces se alegró el rey en gran manera a causa de él, y mandó sacar a Daniel del foso. Y Daniel fue sacado del foso, y ninguna lesión se halló en él, porque creyó en su Dios. </div>
<div id="Dan_6_24" style="display:none;" class="ver_select"><b>Dan 6:24</b>  Y el rey ordenó que fueran traídos aquellos hombres que habían acusado a Daniel, y fueron echados en el foso de los leones, ellos, sus hijos y sus esposas; y aún no habían llegado al suelo del foso, cuando los leones se apoderaron de ellos, y quebraron todos sus huesos. </div>
<div id="Dan_6_25" style="display:none;" class="ver_select"><b>Dan 6:25</b>  Entonces el rey Darío escribió a todos los pueblos, naciones, y lenguas, que habitan en toda la tierra: Paz os sea multiplicada: </div>
<div id="Dan_6_26" style="display:none;" class="ver_select"><b>Dan 6:26</b>  De parte mía es puesta ordenanza, que en todo el señorío de mi reino todos teman y tiemblen ante la presencia del Dios de Daniel; porque Él es el Dios viviente y permanece por la eternidad, y su reino no será destruido, y su señorío permanecerá hasta el fin. </div>
<div id="Dan_6_27" style="display:none;" class="ver_select"><b>Dan 6:27</b>  Que salva y libra, y hace señales y maravillas en el cielo y en la tierra; el cual libró a Daniel del poder de los leones. </div>
<div id="Dan_6_28" style="display:none;" class="ver_select"><b>Dan 6:28</b>  Y este Daniel fue prosperado durante el reinado de Darío, y durante el reinado de Ciro, el persa. </div>
<div id="Dan_7_1" style="display:none;" class="ver_select"><b>Dan 7:1</b>  En el primer año de Belsasar rey de Babilonia, tuvo Daniel un sueño y visiones de su cabeza estando en su cama; luego escribió el sueño, y relató la suma de los asuntos. </div>
<div id="Dan_7_2" style="display:none;" class="ver_select"><b>Dan 7:2</b>  Habló Daniel y dijo: Veía yo en mi visión de noche, y he aquí que los cuatro vientos del cielo combatían en el gran mar. </div>
<div id="Dan_7_3" style="display:none;" class="ver_select"><b>Dan 7:3</b>  Y cuatro bestias grandes, diferentes la una de la otra, subían del mar. </div>
<div id="Dan_7_4" style="display:none;" class="ver_select"><b>Dan 7:4</b>  La primera era como león, y tenía alas de águila. Yo estaba mirando hasta que sus alas fueron arrancadas, y fue quitada de la tierra; y se puso enhiesta sobre los pies a manera de hombre, y le fue dado corazón de hombre. </div>
<div id="Dan_7_5" style="display:none;" class="ver_select"><b>Dan 7:5</b>  Y he aquí otra segunda bestia, semejante a un oso, la cual se puso a un lado, y tenía en su boca tres costillas entre los dientes; y le fue dicho así: Levántate, traga mucha carne. </div>
<div id="Dan_7_6" style="display:none;" class="ver_select"><b>Dan 7:6</b>  Después de esto yo miraba, y he aquí otra, semejante a un leopardo, y tenía cuatro alas de ave en sus espaldas: tenía también esta bestia cuatro cabezas; y le fue dado dominio. </div>
<div id="Dan_7_7" style="display:none;" class="ver_select"><b>Dan 7:7</b>  Después de esto miraba yo en las visiones de la noche, y he aquí la cuarta bestia, espantosa y terrible, y en grande manera fuerte; la cual tenía unos dientes grandes de hierro: devoraba y desmenuzaba, y las sobras hollaba con sus pies: y era muy diferente de todas las bestias que habían sido antes de ella, y tenía diez cuernos. </div>
<div id="Dan_7_8" style="display:none;" class="ver_select"><b>Dan 7:8</b>  Y mientras yo contemplaba los cuernos, he aquí que otro cuerno pequeño subía entre ellos, y delante de él fueron arrancados tres cuernos de los primeros; y he aquí, en este cuerno había ojos como ojos de hombre, y una boca que hablaba grandezas. </div>
<div id="Dan_7_9" style="display:none;" class="ver_select"><b>Dan 7:9</b>  Estuve mirando hasta que fueron puestos unos tronos. Y el Anciano de días se sentó, cuya vestidura era blanca como la nieve, y el cabello de su cabeza como lana pura; su trono era como llama de fuego, y sus ruedas, como fuego ardiente. </div>
<div id="Dan_7_10" style="display:none;" class="ver_select"><b>Dan 7:10</b>  Un río de fuego procedía y salía de delante de Él: millares de millares le servían, y millones de millones asistían delante de Él: El Juez se sentó, y los libros fueron abiertos. </div>
<div id="Dan_7_11" style="display:none;" class="ver_select"><b>Dan 7:11</b>  Yo entonces miraba a causa de la voz de las grandes palabras que hablaba el cuerno; miré hasta que mataron a la bestia, y su cuerpo fue destrozado y entregado para ser quemado en el fuego. </div>
<div id="Dan_7_12" style="display:none;" class="ver_select"><b>Dan 7:12</b>  Habían también quitado a las otras bestias su dominio, y les había sido dada prolongación de vida hasta cierto tiempo. </div>
<div id="Dan_7_13" style="display:none;" class="ver_select"><b>Dan 7:13</b>  Miraba yo en la visión de la noche, y he aquí en las nubes del cielo uno como el Hijo del Hombre que venía, y llegó hasta el Anciano de días, y le hicieron llegar delante de Él. </div>
<div id="Dan_7_14" style="display:none;" class="ver_select"><b>Dan 7:14</b>  Y le fue dado dominio, gloria y reino, para que todos los pueblos, naciones y lenguas le sirvieran; su dominio es dominio eterno, que no pasará, y su reino uno que no será destruido. </div>
<div id="Dan_7_15" style="display:none;" class="ver_select"><b>Dan 7:15</b>  Yo Daniel, fui turbado en mi espíritu en medio de mi cuerpo, y las visiones de mi cabeza me asombraron. </div>
<div id="Dan_7_16" style="display:none;" class="ver_select"><b>Dan 7:16</b>  Me acerqué a uno de los que asistían, y le pregunté la verdad acerca de todo esto. Y me habló, y me dio a conocer la interpretación de las cosas. </div>
<div id="Dan_7_17" style="display:none;" class="ver_select"><b>Dan 7:17</b>  Estas cuatro grandes bestias, son cuatro reyes que se levantarán en la tierra. </div>
<div id="Dan_7_18" style="display:none;" class="ver_select"><b>Dan 7:18</b>  Después tomarán el reino los santos del Altísimo, y poseerán el reino por siempre, eternamente y para siempre. </div>
<div id="Dan_7_19" style="display:none;" class="ver_select"><b>Dan 7:19</b>  Entonces quise saber la verdad acerca de la cuarta bestia, que tan diferente era de todas las otras, espantosa en gran manera, que tenía dientes de hierro, y sus uñas de bronce, que devoraba y desmenuzaba, y las sobras hollaba con sus pies: </div>
<div id="Dan_7_20" style="display:none;" class="ver_select"><b>Dan 7:20</b>  Asimismo acerca de los diez cuernos que tenía en su cabeza, y del otro que había subido, de delante del cual habían caído tres; y este mismo cuerno tenía ojos, y boca que hablaba grandezas, y parecía más grande que sus compañeros. </div>
<div id="Dan_7_21" style="display:none;" class="ver_select"><b>Dan 7:21</b>  Y veía yo que este cuerno hacía guerra contra los santos, y los vencía, </div>
<div id="Dan_7_22" style="display:none;" class="ver_select"><b>Dan 7:22</b>  hasta tanto que vino el Anciano de días, y se dio el juicio a los santos del Altísimo; y vino el tiempo, y los santos poseyeron el reino. </div>
<div id="Dan_7_23" style="display:none;" class="ver_select"><b>Dan 7:23</b>  Dijo así: La cuarta bestia será un cuarto reino en la tierra, el cual será diferente de todos los otros reinos, y a toda la tierra devorará, y la hollará, y la despedazará. </div>
<div id="Dan_7_24" style="display:none;" class="ver_select"><b>Dan 7:24</b>  Y los diez cuernos significan que de aquel reino se levantarán diez reyes; y tras ellos se levantará otro, el cual será mayor que los primeros, y a tres reyes subyugará. </div>
<div id="Dan_7_25" style="display:none;" class="ver_select"><b>Dan 7:25</b>  Y hablará palabras contra el Altísimo, y a los santos del Altísimo afligirá, y pensará en mudar los tiempos y la ley: y entregados serán en su mano hasta un tiempo, y tiempos, y el medio de un tiempo. </div>
<div id="Dan_7_26" style="display:none;" class="ver_select"><b>Dan 7:26</b>  Pero se sentará el Juez, y le quitarán su dominio, para que sea destruido y arruinado hasta el extremo; </div>
<div id="Dan_7_27" style="display:none;" class="ver_select"><b>Dan 7:27</b>  y que el reino, el dominio y la majestad de los reinos debajo de todo el cielo, sea dado al pueblo de los santos del Altísimo; cuyo reino es reino eterno, y todos los dominios le servirán y obedecerán. </div>
<div id="Dan_7_28" style="display:none;" class="ver_select"><b>Dan 7:28</b>  Hasta aquí fue el fin del asunto. En cuanto a mí, Daniel, mucho me turbaron mis pensamientos, y mi rostro se demudó, pero guardé el asunto en mi corazón. </div>
<div id="Dan_8_1" style="display:none;" class="ver_select"><b>Dan 8:1</b>  En el año tercero del reinado del rey Belsasar, me apareció una visión a mí, Daniel, después de aquella que me había aparecido antes. </div>
<div id="Dan_8_2" style="display:none;" class="ver_select"><b>Dan 8:2</b>  Vi en visión, y sucedió cuando la vi, que yo estaba en Susán, que es cabecera del reino en la provincia de Elam; vi, pues, en visión, estando junto al río Ulai. </div>
<div id="Dan_8_3" style="display:none;" class="ver_select"><b>Dan 8:3</b>  Y alcé mis ojos, y miré, y he aquí un carnero que estaba delante del río, el cual tenía dos cuernos; y los dos cuernos eran altos, pero uno era más alto que el otro; y el más alto subió a la postre. </div>
<div id="Dan_8_4" style="display:none;" class="ver_select"><b>Dan 8:4</b>  Vi que el carnero hería con los cuernos al poniente, al norte, y al sur, y que ninguna bestia podía mantenerse de pie delante de él, ni había quien librara de su mano; y hacía conforme a su voluntad, y se engrandecía. </div>
<div id="Dan_8_5" style="display:none;" class="ver_select"><b>Dan 8:5</b>  Y mientras yo consideraba, he aquí un macho cabrío venía de la parte del poniente sobre la faz de toda la tierra, el cual no tocaba la tierra; y aquel macho cabrío tenía un cuerno notable entre sus ojos. </div>
<div id="Dan_8_6" style="display:none;" class="ver_select"><b>Dan 8:6</b>  Y vino hasta el carnero que tenía los dos cuernos, al cual yo había visto que estaba delante del río, y corrió contra él con la ira de su poder. </div>
<div id="Dan_8_7" style="display:none;" class="ver_select"><b>Dan 8:7</b>  Y lo vi que llegó junto al carnero, y se levantó contra él, y lo hirió, y quebró sus dos cuernos, porque en el carnero no había fuerzas para pararse delante de él; lo derribó por tanto en tierra, y lo pisoteó; y no hubo quien librase al carnero de su mano. </div>
<div id="Dan_8_8" style="display:none;" class="ver_select"><b>Dan 8:8</b>  Y el macho cabrío se engrandeció en gran manera; y estando en su mayor fuerza, aquel gran cuerno fue quebrado, y en su lugar subieron otros cuatro cuernos notables hacia los cuatro vientos del cielo. </div>
<div id="Dan_8_9" style="display:none;" class="ver_select"><b>Dan 8:9</b>  Y de uno de ellos salió un cuerno pequeño, el cual creció mucho al sur, y al oriente, y hacia la tierra gloriosa. </div>
<div id="Dan_8_10" style="display:none;" class="ver_select"><b>Dan 8:10</b>  Y se engrandeció hasta el ejército del cielo; y parte del ejército y de las estrellas echó por tierra, y las pisoteó. </div>
<div id="Dan_8_11" style="display:none;" class="ver_select"><b>Dan 8:11</b>  Aun contra el príncipe de la fortaleza se engrandeció, y por él fue quitado el continuo sacrificio, y el lugar de su santuario fue echado por tierra. </div>
<div id="Dan_8_12" style="display:none;" class="ver_select"><b>Dan 8:12</b>  Y el ejército le fue entregado a causa de la prevaricación sobre el continuo sacrificio; y echó por tierra la verdad, e hizo cuanto quiso, y prosperó. </div>
<div id="Dan_8_13" style="display:none;" class="ver_select"><b>Dan 8:13</b>  Y oí a un santo que hablaba; y otro de los santos dijo a aquél que hablaba: ¿Hasta cuándo durará la visión del continuo sacrificio, y la prevaricación asoladora que pone el santuario y el ejército para ser hollados? </div>
<div id="Dan_8_14" style="display:none;" class="ver_select"><b>Dan 8:14</b>  Y él me dijo: Hasta dos mil trescientas tardes y mañanas; y el santuario será purificado. </div>
<div id="Dan_8_15" style="display:none;" class="ver_select"><b>Dan 8:15</b>  Y aconteció que mientras yo Daniel consideraba la visión, y buscaba su significado, he aquí uno con apariencia de hombre se puso delante de mí. </div>
<div id="Dan_8_16" style="display:none;" class="ver_select"><b>Dan 8:16</b>  Y oí una voz de hombre entre las riberas de Ulai, que gritó y dijo: Gabriel, enseña a éste la visión. </div>
<div id="Dan_8_17" style="display:none;" class="ver_select"><b>Dan 8:17</b>  Vino luego cerca de donde yo estaba; y con su venida me asombré, y caí sobre mi rostro. Pero él me dijo: Entiende, hijo de hombre, porque la visión será para el tiempo del fin. </div>
<div id="Dan_8_18" style="display:none;" class="ver_select"><b>Dan 8:18</b>  Y mientras él hablaba conmigo, caí dormido en tierra sobre mi rostro; y él me tocó, y me hizo estar en pie. </div>
<div id="Dan_8_19" style="display:none;" class="ver_select"><b>Dan 8:19</b>  Y dijo: He aquí yo te enseñaré lo que ha de venir en el fin de la ira; porque al tiempo señalado el fin se cumplirá. </div>
<div id="Dan_8_20" style="display:none;" class="ver_select"><b>Dan 8:20</b>  Aquel carnero que viste, que tenía dos cuernos, son los reyes de Media y de Persia. </div>
<div id="Dan_8_21" style="display:none;" class="ver_select"><b>Dan 8:21</b>  Y el macho cabrío es el rey de Grecia; y el cuerno grande que tenía entre sus ojos es el rey primero. </div>
<div id="Dan_8_22" style="display:none;" class="ver_select"><b>Dan 8:22</b>  Y en cuanto al cuerno que fue quebrado y sucedieron cuatro en su lugar, significa que cuatro reinos se levantarán de esa nación, mas no con la fuerza de él. </div>
<div id="Dan_8_23" style="display:none;" class="ver_select"><b>Dan 8:23</b>  Y al fin del reinado de éstos, cuando los transgresores hayan llegado a su colmo, se levantará un rey altivo de rostro, y entendido en enigmas. </div>
<div id="Dan_8_24" style="display:none;" class="ver_select"><b>Dan 8:24</b>  Y su poder se fortalecerá, mas no por su propio poder, y destruirá maravillosamente, y prosperará; y hará arbitrariamente, y destruirá a los fuertes y al pueblo de los santos. </div>
<div id="Dan_8_25" style="display:none;" class="ver_select"><b>Dan 8:25</b>  Y con su sagacidad hará prosperar el engaño en su mano; y en su corazón se engrandecerá, y con paz destruirá a muchos; y contra el Príncipe de los príncipes se levantará; mas sin mano será quebrantado. </div>
<div id="Dan_8_26" style="display:none;" class="ver_select"><b>Dan 8:26</b>  Y la visión de la tarde y la mañana que está dicha, es verdadera; y tú guarda la visión, porque es para muchos días. </div>
<div id="Dan_8_27" style="display:none;" class="ver_select"><b>Dan 8:27</b>  Y yo Daniel fui quebrantado, y estuve enfermo algunos días; y cuando convalecí, atendí el asunto del rey; mas estaba espantado acerca de la visión, y no había quien la entendiese. </div>
<div id="Dan_9_1" style="display:none;" class="ver_select"><b>Dan 9:1</b>  En el año primero de Darío hijo de Asuero, de la nación de los medos, el cual fue puesto por rey sobre el reino de los caldeos; </div>
<div id="Dan_9_2" style="display:none;" class="ver_select"><b>Dan 9:2</b>  en el año primero de su reinado, yo Daniel miré atentamente en los libros el número de los años, de los cuales vino palabra de Jehová al profeta Jeremías, que había de concluir la asolación de Jerusalén en setenta años. </div>
<div id="Dan_9_3" style="display:none;" class="ver_select"><b>Dan 9:3</b>  Y volví mi rostro al Señor Dios, buscándole en oración y ruego, en ayuno, y cilicio y ceniza. </div>
<div id="Dan_9_4" style="display:none;" class="ver_select"><b>Dan 9:4</b>  Y oré a Jehová mi Dios, y confesé, y dije: Oh Señor, Dios grande, digno de ser temido, que guardas el pacto y la misericordia con los que te aman y guardan tus mandamientos; </div>
<div id="Dan_9_5" style="display:none;" class="ver_select"><b>Dan 9:5</b>  Hemos pecado, hemos hecho iniquidad, hemos obrado impíamente, hemos sido rebeldes y nos hemos apartado de tus mandamientos y de tus juicios. </div>
<div id="Dan_9_6" style="display:none;" class="ver_select"><b>Dan 9:6</b>  No hemos obedecido a tus siervos los profetas, que en tu nombre hablaron a nuestros reyes, y a nuestros príncipes, a nuestros padres y a todo el pueblo de la tierra. </div>
<div id="Dan_9_7" style="display:none;" class="ver_select"><b>Dan 9:7</b>  Tuya es, Señor, la justicia, y nuestra la confusión de rostro, como sucede en el día de hoy a todo hombre de Judá, y a los moradores de Jerusalén, y a todo Israel, a los de cerca y a los de lejos, en todas las tierras a donde los has echado a causa de su rebelión con que contra ti se rebelaron. </div>
<div id="Dan_9_8" style="display:none;" class="ver_select"><b>Dan 9:8</b>  Oh Jehová, nuestra es la confusión de rostro, de nuestros reyes, de nuestros príncipes, y de nuestros padres; porque contra ti pecamos. </div>
<div id="Dan_9_9" style="display:none;" class="ver_select"><b>Dan 9:9</b>  De Jehová nuestro Dios es el tener misericordia, y el perdonar, aunque contra Él nos hemos rebelado; </div>
<div id="Dan_9_10" style="display:none;" class="ver_select"><b>Dan 9:10</b>  y no obedecimos a la voz de Jehová nuestro Dios, para andar en sus leyes, las cuales Él puso delante de nosotros por medio de sus siervos los profetas. </div>
<div id="Dan_9_11" style="display:none;" class="ver_select"><b>Dan 9:11</b>  Y todo Israel traspasó tu ley apartándose para no oír tu voz: por lo cual ha caído sobre nosotros la maldición, y el juramento que está escrito en la ley de Moisés, siervo de Dios; porque contra Él pecamos. </div>
<div id="Dan_9_12" style="display:none;" class="ver_select"><b>Dan 9:12</b>  Y Él ha confirmado su palabra que habló sobre nosotros, y sobre nuestros jueces que nos gobernaron, trayendo sobre nosotros tan grande mal; que nunca fue hecho debajo del cielo como el que fue hecho en Jerusalén. </div>
<div id="Dan_9_13" style="display:none;" class="ver_select"><b>Dan 9:13</b>  Según está escrito en la ley de Moisés, todo este mal vino sobre nosotros; y no hemos rogado a la faz de Jehová nuestro Dios, para convertirnos de nuestras maldades, y entender tu verdad. </div>
<div id="Dan_9_14" style="display:none;" class="ver_select"><b>Dan 9:14</b>  Por tanto, Jehová veló sobre el mal, y lo trajo sobre nosotros; porque justo es Jehová nuestro Dios en todas sus obras que Él hace, porque no obedecimos a su voz. </div>
<div id="Dan_9_15" style="display:none;" class="ver_select"><b>Dan 9:15</b>  Ahora pues, Señor Dios nuestro, que sacaste a tu pueblo de la tierra de Egipto con mano poderosa, y te hiciste renombre cual en este día; hemos pecado, impíamente hemos hecho. </div>
<div id="Dan_9_16" style="display:none;" class="ver_select"><b>Dan 9:16</b>  Oh Señor, según todas tus justicias, apártese ahora tu ira y tu furor de sobre tu ciudad Jerusalén, tu santo monte: porque a causa de nuestros pecados, y por la maldad de nuestros padres, Jerusalén y tu pueblo son el oprobio de todos en derredor nuestro. </div>
<div id="Dan_9_17" style="display:none;" class="ver_select"><b>Dan 9:17</b>  Ahora pues, Dios nuestro, oye la oración de tu siervo, y sus súplicas, y haz que tu rostro resplandezca sobre tu santuario asolado, por amor del Señor. </div>
<div id="Dan_9_18" style="display:none;" class="ver_select"><b>Dan 9:18</b>  Inclina, oh Dios mío, tu oído, y oye; abre tus ojos, y mira nuestros asolamientos, y la ciudad sobre la cual es llamado tu nombre: porque no derramamos nuestros ruegos ante tu presencia confiados en nuestras justicias, sino en tus muchas misericordias. </div>
<div id="Dan_9_19" style="display:none;" class="ver_select"><b>Dan 9:19</b>  Oye, Señor; oh Señor, perdona; presta oído, Señor, y haz; no pongas dilación, por amor de ti mismo, Dios mío: porque tu nombre es invocado sobre tu ciudad y sobre tu pueblo. </div>
<div id="Dan_9_20" style="display:none;" class="ver_select"><b>Dan 9:20</b>  Aun estaba yo hablando, y orando, y confesando mi pecado y el pecado de mi pueblo Israel, y presentaba mi súplica delante de Jehová mi Dios por el monte santo de mi Dios; </div>
<div id="Dan_9_21" style="display:none;" class="ver_select"><b>Dan 9:21</b>  y todavía estaba yo hablando en oración, cuando aquel varón Gabriel, al cual había visto en visión al principio, volando con presteza, me tocó como a la hora del sacrificio de la tarde. </div>
<div id="Dan_9_22" style="display:none;" class="ver_select"><b>Dan 9:22</b>  Y me hizo entender, y habló conmigo, y dijo: Daniel, ahora he salido para darte sabiduría y entendimiento. </div>
<div id="Dan_9_23" style="display:none;" class="ver_select"><b>Dan 9:23</b>  Al principio de tus súplicas fue dada la orden, y yo he venido para enseñártela, porque tú eres muy amado. Entiende, pues, el asunto, y considera la visión. </div>
<div id="Dan_9_24" style="display:none;" class="ver_select"><b>Dan 9:24</b>  Setenta semanas están determinadas sobre tu pueblo y sobre tu santa ciudad, para acabar la prevaricación, y concluir el pecado, y expiar la iniquidad; y para traer la justicia eterna, y sellar la visión y la profecía, y ungir al Santo de los santos. </div>
<div id="Dan_9_25" style="display:none;" class="ver_select"><b>Dan 9:25</b>  Sabe, pues, y entiende, que desde la salida de la orden para restaurar y edificar a Jerusalén hasta el Mesías Príncipe, habrá siete semanas, y sesenta y dos semanas; la plaza volverá a ser edificada, y el muro, en tiempos angustiosos. </div>
<div id="Dan_9_26" style="display:none;" class="ver_select"><b>Dan 9:26</b>  Y después de las sesenta y dos semanas se quitará la vida al Mesías, mas no por sí; y el pueblo del príncipe que ha de venir, destruirá la ciudad y el santuario; con inundación será el fin de ella, y hasta el fin de la guerra las asolaciones están determinadas. </div>
<div id="Dan_9_27" style="display:none;" class="ver_select"><b>Dan 9:27</b>  Y por una semana confirmará el pacto con muchos, y a la mitad de la semana hará cesar el sacrificio y la ofrenda. Después con la muchedumbre de las abominaciones vendrá el desolar, aun hasta una entera consumación; y lo que está determinado se derramará sobre el pueblo asolado. </div>
<div id="Dan_10_1" style="display:none;" class="ver_select"><b>Dan 10:1</b>  En el tercer año de Ciro rey de Persia, fue revelada palabra a Daniel, cuyo nombre era Beltsasar; y la palabra era verdadera, mas el tiempo fijado era largo; pero él comprendió la palabra, y tuvo inteligencia en la visión. </div>
<div id="Dan_10_2" style="display:none;" class="ver_select"><b>Dan 10:2</b>  En aquellos días yo Daniel me contristé por espacio de tres semanas. </div>
<div id="Dan_10_3" style="display:none;" class="ver_select"><b>Dan 10:3</b>  No comí pan delicado, ni entró carne ni vino en mi boca, ni me ungí con ungüento, hasta que se cumplieron tres semanas. </div>
<div id="Dan_10_4" style="display:none;" class="ver_select"><b>Dan 10:4</b>  Y a los veinticuatro días del mes primero estaba yo a la orilla del gran río Hidekel; </div>
<div id="Dan_10_5" style="display:none;" class="ver_select"><b>Dan 10:5</b>  Y alzando mis ojos miré, y he aquí un varón vestido de lino, y ceñidos sus lomos de oro de Ufaz: </div>
<div id="Dan_10_6" style="display:none;" class="ver_select"><b>Dan 10:6</b>  Y su cuerpo era como el berilo, y su rostro parecía un relámpago, y sus ojos como antorchas de fuego, y sus brazos y sus pies como de color de bronce resplandeciente, y la voz de sus palabras como la voz de una multitud. </div>
<div id="Dan_10_7" style="display:none;" class="ver_select"><b>Dan 10:7</b>  Y sólo yo, Daniel, vi aquella visión, y no la vieron los hombres que estaban conmigo; sino que cayó sobre ellos un gran temor y huyeron a esconderse. </div>
<div id="Dan_10_8" style="display:none;" class="ver_select"><b>Dan 10:8</b>  Quedé, pues, yo solo, y vi esta gran visión, y no quedó fuerza en mí; antes mi fuerza se me cambió en debilidad, sin retener vigor alguno. </div>
<div id="Dan_10_9" style="display:none;" class="ver_select"><b>Dan 10:9</b>  Pero oí la voz de sus palabras; y oyendo la voz de sus palabras, estaba yo adormecido sobre mi rostro, y mi rostro en tierra. </div>
<div id="Dan_10_10" style="display:none;" class="ver_select"><b>Dan 10:10</b>  Y he aquí una mano me tocó, e hizo que me pusiese sobre mis rodillas y sobre las palmas de mis manos. </div>
<div id="Dan_10_11" style="display:none;" class="ver_select"><b>Dan 10:11</b>  Y me dijo: Daniel, varón muy amado, está atento a las palabras que te hablaré, y levántate sobre tus pies; porque a ti he sido enviado ahora. Y cuando él hablaba conmigo estas palabras, yo estaba temblando. </div>
<div id="Dan_10_12" style="display:none;" class="ver_select"><b>Dan 10:12</b>  Entonces me dijo: Daniel, no temas; porque desde el primer día que diste tu corazón a entender, y a afligirte en la presencia de tu Dios, fueron oídas tus palabras; y a causa de tus palabras yo he venido. </div>
<div id="Dan_10_13" style="display:none;" class="ver_select"><b>Dan 10:13</b>  Mas el príncipe del reino de Persia se puso contra mí veintiún días; y he aquí, Miguel, uno de los principales príncipes, vino para ayudarme, y yo quedé allí con los reyes de Persia. </div>
<div id="Dan_10_14" style="display:none;" class="ver_select"><b>Dan 10:14</b>  Yo he venido para hacerte saber lo que ha de venir a tu pueblo en los postreros días; porque la visión es aún para muchos días; </div>
<div id="Dan_10_15" style="display:none;" class="ver_select"><b>Dan 10:15</b>  y cuando él habló conmigo estas palabras, puse mi rostro en tierra, y enmudecí. </div>
<div id="Dan_10_16" style="display:none;" class="ver_select"><b>Dan 10:16</b>  Mas he aquí, como una semejanza de hijo de hombre tocó mis labios. Entonces abrí mi boca, y hablé, y dije a aquel que estaba delante de mí: Señor mío, con la visión se revolvieron mis dolores sobre mí, y no me quedó fuerza. </div>
<div id="Dan_10_17" style="display:none;" class="ver_select"><b>Dan 10:17</b>  ¿Cómo, pues, podrá el siervo de mi señor hablar con este mi señor? Porque al instante me faltó la fuerza, y no me ha quedado aliento. </div>
<div id="Dan_10_18" style="display:none;" class="ver_select"><b>Dan 10:18</b>  Y aquella como semejanza de hombre me tocó otra vez, y me fortaleció; </div>
<div id="Dan_10_19" style="display:none;" class="ver_select"><b>Dan 10:19</b>  y me dijo: Varón muy amado, no temas; paz a ti; ten buen ánimo, y esfuérzate. Y hablando él conmigo recobré las fuerzas, y dije: Hable mi señor, porque me has fortalecido. </div>
<div id="Dan_10_20" style="display:none;" class="ver_select"><b>Dan 10:20</b>  Y dijo: ¿Sabes por qué he venido a ti? Porque luego tengo que volver para pelear con el príncipe de Persia; y saliendo yo, he aquí, el príncipe de Grecia vendrá. </div>
<div id="Dan_10_21" style="display:none;" class="ver_select"><b>Dan 10:21</b>  Pero yo te declararé lo que está anotado en la Escritura de la verdad. Y ninguno hay que se esfuerce conmigo en estas cosas, sino Miguel vuestro príncipe. </div>
<div id="Dan_11_1" style="display:none;" class="ver_select"><b>Dan 11:1</b>  Y en el año primero de Darío el medo, yo estuve para animarlo y fortalecerlo. </div>
<div id="Dan_11_2" style="display:none;" class="ver_select"><b>Dan 11:2</b>  Y ahora yo te mostraré la verdad. He aquí que aún habrá tres reyes en Persia, y el cuarto se hará de grandes riquezas más que todos; y fortificándose con sus riquezas, incitará a todos contra el reino de Grecia. </div>
<div id="Dan_11_3" style="display:none;" class="ver_select"><b>Dan 11:3</b>  Se levantará luego un rey poderoso, el cual señoreará con gran dominio, y hará según su voluntad. </div>
<div id="Dan_11_4" style="display:none;" class="ver_select"><b>Dan 11:4</b>  Pero cuando se haya levantado, su reino será quebrantado, y repartido por los cuatro vientos del cielo; y no a sus descendientes, ni según el señorío con que él señoreó; porque su reino será arrancado, y será para otros fuera de ellos. </div>
<div id="Dan_11_5" style="display:none;" class="ver_select"><b>Dan 11:5</b>  Y se hará fuerte el rey del sur; mas uno de los príncipes de aquél le sobrepujará, y se hará poderoso; su dominio será gran dominio. </div>
<div id="Dan_11_6" style="display:none;" class="ver_select"><b>Dan 11:6</b>  Y al cabo de años harán alianza entre ellos, y la hija del rey del sur vendrá al rey del norte para hacer un convenio. Pero ella no podrá retener la fuerza del brazo; ni permanecerá él, ni su brazo; porque será entregada ella, y los que la habían traído, asimismo su hijo, y los que estaban de parte de ella en aquellos tiempos. </div>
<div id="Dan_11_7" style="display:none;" class="ver_select"><b>Dan 11:7</b>  Mas del renuevo de sus raíces se levantará uno en su lugar, y vendrá con ejército, y entrará en la fortaleza del rey del norte, y hará en ellos a su arbitrio, y predominará. </div>
<div id="Dan_11_8" style="display:none;" class="ver_select"><b>Dan 11:8</b>  Y aun los dioses de ellos, con sus príncipes, con sus vasos preciosos de plata y de oro, llevará cautivos a Egipto; y por muchos años se mantendrá él contra el rey del norte. </div>
<div id="Dan_11_9" style="display:none;" class="ver_select"><b>Dan 11:9</b>  Así entrará en su reino el rey del sur, y volverá a su tierra. </div>
<div id="Dan_11_10" style="display:none;" class="ver_select"><b>Dan 11:10</b>  Mas los hijos de aquél se airarán y reunirán multitud de grandes ejércitos: y vendrá a gran prisa, e inundará, y pasará, y tornará, y llegará con ira hasta su fortaleza. </div>
<div id="Dan_11_11" style="display:none;" class="ver_select"><b>Dan 11:11</b>  Por lo cual se enfurecerá el rey del sur, y saldrá, y peleará con el mismo rey del norte; y pondrá en campo gran multitud, y toda aquella multitud será entregada en su mano. </div>
<div id="Dan_11_12" style="display:none;" class="ver_select"><b>Dan 11:12</b>  Y la multitud se ensoberbecerá, se elevará su corazón, y derribará muchos millares; mas no prevalecerá. </div>
<div id="Dan_11_13" style="display:none;" class="ver_select"><b>Dan 11:13</b>  Y el rey del norte volverá a poner en campaña una multitud mayor que la primera, y al cabo de algunos años vendrá a gran prisa con grande ejército y con muchas riquezas. </div>
<div id="Dan_11_14" style="display:none;" class="ver_select"><b>Dan 11:14</b>  Y en aquellos tiempos se levantarán muchos contra el rey del sur; e hijos de disipadores de tu pueblo se levantarán para confirmar la profecía, pero caerán. </div>
<div id="Dan_11_15" style="display:none;" class="ver_select"><b>Dan 11:15</b>  Vendrá, pues, el rey del norte, y fundará baluartes, y tomará la ciudad fuerte; y los brazos del sur no podrán permanecer, ni su pueblo escogido, ni habrá fortaleza que pueda resistir. </div>
<div id="Dan_11_16" style="display:none;" class="ver_select"><b>Dan 11:16</b>  Y el que vendrá contra él, hará a su voluntad, y no habrá quien se pueda parar delante de él; y estará en la tierra gloriosa, la cual será consumida en su poder. </div>
<div id="Dan_11_17" style="display:none;" class="ver_select"><b>Dan 11:17</b>  Pondrá luego su rostro para venir con el poder de todo su reino; y hará con aquél cosas rectas, y le dará una hija de mujeres para corromperle; pero no le respaldará ni estará de su lado. </div>
<div id="Dan_11_18" style="display:none;" class="ver_select"><b>Dan 11:18</b>  Volverá después su rostro a las islas, y tomará muchas; mas un príncipe le hará parar su afrenta, y aun tornará sobre él su oprobio. </div>
<div id="Dan_11_19" style="display:none;" class="ver_select"><b>Dan 11:19</b>  Luego volverá su rostro a las fortalezas de su tierra; mas tropezará y caerá, y no será hallado. </div>
<div id="Dan_11_20" style="display:none;" class="ver_select"><b>Dan 11:20</b>  Entonces se levantará en su lugar un recaudador de impuestos en la gloria del reino; pero a los pocos días será destruido, no en enojo, ni en batalla. </div>
<div id="Dan_11_21" style="display:none;" class="ver_select"><b>Dan 11:21</b>  Y en su lugar se levantará un hombre vil, al cual no darán la honra del reino; pero vendrá con paz, y tomará el reino con halagos. </div>
<div id="Dan_11_22" style="display:none;" class="ver_select"><b>Dan 11:22</b>  Y con los brazos de inundación serán inundados delante de él, y serán quebrantados; y aun también el príncipe del pacto. </div>
<div id="Dan_11_23" style="display:none;" class="ver_select"><b>Dan 11:23</b>  Y después de la alianza hecha con él, él hará engaño, y subirá, y saldrá vencedor con poca gente. </div>
<div id="Dan_11_24" style="display:none;" class="ver_select"><b>Dan 11:24</b>  Estando la provincia en paz y en abundancia, entrará y hará lo que no hicieron sus padres, ni los padres de sus padres; presa, y despojos, y riquezas repartirá a sus soldados; y contra las fortalezas formará sus designios: y esto por tiempo. </div>
<div id="Dan_11_25" style="display:none;" class="ver_select"><b>Dan 11:25</b>  Y despertará sus fuerzas y su corazón contra el rey del sur con grande ejército; y el rey del sur se moverá a la guerra con grande y muy fuerte ejército; mas no prevalecerá, porque le harán traición. </div>
<div id="Dan_11_26" style="display:none;" class="ver_select"><b>Dan 11:26</b>  Aun los que comen de su pan, le destruirán; y su ejército será destruido, y caerán muchos muertos. </div>
<div id="Dan_11_27" style="display:none;" class="ver_select"><b>Dan 11:27</b>  Y el corazón de estos dos reyes será para hacer mal, y en una misma mesa tratarán mentira; mas no servirá de nada, porque el plazo aún ha de venir al tiempo señalado. </div>
<div id="Dan_11_28" style="display:none;" class="ver_select"><b>Dan 11:28</b>  Y se volverá a su tierra con grande riqueza, y su corazón será contra el pacto santo; actuará, pues, contra éste, y se volverá a su tierra. </div>
<div id="Dan_11_29" style="display:none;" class="ver_select"><b>Dan 11:29</b>  Al tiempo señalado volverá, y vendrá hacia el sur; mas no será la postrera venida como la primera. </div>
<div id="Dan_11_30" style="display:none;" class="ver_select"><b>Dan 11:30</b>  Porque vendrán contra él naves de Quitim, y él se contristará, y volverá, y se enojará contra el pacto santo, y actuará contra éste; volverá, pues, y se entenderá con los que abandonan el santo pacto. </div>
<div id="Dan_11_31" style="display:none;" class="ver_select"><b>Dan 11:31</b>  Y se levantarán brazos de su parte; y contaminarán el santuario de fortaleza, y quitarán el continuo sacrificio, y pondrán la abominación desoladora. </div>
<div id="Dan_11_32" style="display:none;" class="ver_select"><b>Dan 11:32</b>  Y con lisonjas hará pecar a los violadores del pacto; mas el pueblo que conoce a su Dios, se esforzará y hará proezas. </div>
<div id="Dan_11_33" style="display:none;" class="ver_select"><b>Dan 11:33</b>  Y los sabios del pueblo instruirán a muchos; pero caerán a espada y a fuego, en cautividad y despojo, por muchos días. </div>
<div id="Dan_11_34" style="display:none;" class="ver_select"><b>Dan 11:34</b>  Y en su caer serán ayudados de pequeño socorro; y muchos se juntarán a ellos con lisonjas. </div>
<div id="Dan_11_35" style="display:none;" class="ver_select"><b>Dan 11:35</b>  Y algunos de los sabios caerán para ser purificados, y limpiados, y emblanquecidos, hasta el tiempo determinado; porque aun para esto hay plazo. </div>
<div id="Dan_11_36" style="display:none;" class="ver_select"><b>Dan 11:36</b>  Y el rey hará a su voluntad; y se enaltecerá y se engrandecerá sobre todo dios; y contra el Dios de los dioses hablará maravillas, y prosperará, hasta que sea consumada la ira; porque lo que está determinado se cumplirá. </div>
<div id="Dan_11_37" style="display:none;" class="ver_select"><b>Dan 11:37</b>  No hará caso del Dios de sus padres, ni del amor de las mujeres: ni se cuidará de dios alguno, porque sobre todo se engrandecerá. </div>
<div id="Dan_11_38" style="display:none;" class="ver_select"><b>Dan 11:38</b>  Mas honrará en su lugar al dios de las fortalezas, dios que sus padres no conocieron; lo honrará con oro, y plata, y piedras preciosas, y con cosas de gran precio. </div>
<div id="Dan_11_39" style="display:none;" class="ver_select"><b>Dan 11:39</b>  Y actuará contra los baluartes más fuertes con el dios ajeno que él reconocerá y colmará de honores; y los hará señorear sobre muchos, y por interés repartirá la tierra. </div>
<div id="Dan_11_40" style="display:none;" class="ver_select"><b>Dan 11:40</b>  Pero al cabo del tiempo el rey del sur se enfrentará con él; y el rey del norte se levantará contra él como una tempestad, con carros y gente de a caballo, y muchos navíos; y entrará por las tierras, e inundará, y pasará. </div>
<div id="Dan_11_41" style="display:none;" class="ver_select"><b>Dan 11:41</b>  Y vendrá a la tierra gloriosa, y muchas naciones caerán; mas éstas escaparán de su mano: Edom, y Moab, y lo mejor de los hijos de Amón. </div>
<div id="Dan_11_42" style="display:none;" class="ver_select"><b>Dan 11:42</b>  Asimismo extenderá su mano a las otras tierras, y no escapará el país de Egipto. </div>
<div id="Dan_11_43" style="display:none;" class="ver_select"><b>Dan 11:43</b>  Y se apoderará de los tesoros de oro y plata, y de todas las cosas preciosas de Egipto. Libios y etíopes seguirán sus pasos. </div>
<div id="Dan_11_44" style="display:none;" class="ver_select"><b>Dan 11:44</b>  Pero noticias del oriente y del norte lo estremecerán; y saldrá con grande ira para destruir y matar a muchos. </div>
<div id="Dan_11_45" style="display:none;" class="ver_select"><b>Dan 11:45</b>  Y plantará las tiendas de su palacio entre los mares, en el monte deseable del santuario; y vendrá hasta su fin, y no tendrá quien le ayude. </div>
<div id="Dan_12_1" style="display:none;" class="ver_select"><b>Dan 12:1</b>  Y en aquel tiempo se levantará Miguel, el gran príncipe que está por los hijos de tu pueblo; y será tiempo de angustia, cual nunca fue después que hubo gente hasta entonces; mas en aquel tiempo será libertado tu pueblo, todos los que se hallen escritos en el libro. </div>
<div id="Dan_12_2" style="display:none;" class="ver_select"><b>Dan 12:2</b>  Y muchos de los que duermen en el polvo de la tierra serán despertados, unos para vida eterna, y otros para vergüenza y confusión perpetua. </div>
<div id="Dan_12_3" style="display:none;" class="ver_select"><b>Dan 12:3</b>  Y los entendidos resplandecerán como el resplandor del firmamento; y los que guiaron a muchos a la justicia, como las estrellas, a perpetua eternidad. </div>
<div id="Dan_12_4" style="display:none;" class="ver_select"><b>Dan 12:4</b>  Pero tú Daniel, cierra las palabras y sella el libro hasta el tiempo del fin: Muchos correrán de un lado a otro, y la ciencia se aumentará. </div>
<div id="Dan_12_5" style="display:none;" class="ver_select"><b>Dan 12:5</b>  Y yo, Daniel, miré, y he aquí otros dos que estaban de pie, el uno a este lado del río, y el otro al otro lado del río. </div>
<div id="Dan_12_6" style="display:none;" class="ver_select"><b>Dan 12:6</b>  Y dijo uno al varón vestido de lino, que estaba sobre las aguas del río: ¿Cuándo será el fin de estas maravillas? </div>
<div id="Dan_12_7" style="display:none;" class="ver_select"><b>Dan 12:7</b>  Y oí al varón vestido de lino, que estaba sobre las aguas del río, el cual alzó su mano derecha y su mano izquierda al cielo, y juró por Aquél que vive por siempre, que será por tiempo, tiempos, y la mitad de un tiempo. Y cuando él acabe de dispersar el poder del pueblo santo, todas estas cosas serán cumplidas. </div>
<div id="Dan_12_8" style="display:none;" class="ver_select"><b>Dan 12:8</b>  Y yo oí, mas no entendí. Y dije: Señor mío, ¿cuál será el fin de estas cosas? </div>
<div id="Dan_12_9" style="display:none;" class="ver_select"><b>Dan 12:9</b>  Y dijo: Anda, Daniel, que estas palabras están cerradas y selladas hasta el tiempo del fin. </div>
<div id="Dan_12_10" style="display:none;" class="ver_select"><b>Dan 12:10</b>  Muchos serán limpios, y emblanquecidos, y purificados; mas los impíos obrarán impíamente, y ninguno de los impíos entenderá, pero entenderán los entendidos. </div>
<div id="Dan_12_11" style="display:none;" class="ver_select"><b>Dan 12:11</b>  Y desde el tiempo que fuere quitado el continuo sacrificio hasta la abominación desoladora, habrá mil doscientos noventa días. </div>
<div id="Dan_12_12" style="display:none;" class="ver_select"><b>Dan 12:12</b>  Bienaventurado el que espere, y llegue hasta mil trescientos treinta y cinco días. </div>
<div id="Dan_12_13" style="display:none;" class="ver_select"><b>Dan 12:13</b>  Pero tú sigue hasta el fin. Porque tú te levantarás y reposarás en tu heredad al fin de los días. </div>
