<div id="Ecc_1_1" style="display:none;" class="ver_select"><b>Ecc 1:1</b>  Palabras del Predicador, hijo de David, rey en Jerusalén. </div>
<div id="Ecc_1_2" style="display:none;" class="ver_select"><b>Ecc 1:2</b>  Vanidad de vanidades, dijo el Predicador; vanidad de vanidades, todo es vanidad. </div>
<div id="Ecc_1_3" style="display:none;" class="ver_select"><b>Ecc 1:3</b>  ¿Qué provecho tiene el hombre de todo su trabajo con que se afana debajo del sol? </div>
<div id="Ecc_1_4" style="display:none;" class="ver_select"><b>Ecc 1:4</b>  Generación va, y generación viene; mas la tierra siempre permanece. </div>
<div id="Ecc_1_5" style="display:none;" class="ver_select"><b>Ecc 1:5</b>  Y sale el sol, y se pone el sol, y se apresura a volver al lugar de donde nace. </div>
<div id="Ecc_1_6" style="display:none;" class="ver_select"><b>Ecc 1:6</b>  El viento tira hacia el sur, y rodea al norte; va girando de continuo, y a sus giros vuelve el viento de nuevo. </div>
<div id="Ecc_1_7" style="display:none;" class="ver_select"><b>Ecc 1:7</b>  Los ríos todos van al mar, y el mar no se llena; al lugar de donde los ríos vinieron, allí tornan para correr de nuevo. </div>
<div id="Ecc_1_8" style="display:none;" class="ver_select"><b>Ecc 1:8</b>  Todas las cosas son fatigosas, más de lo que el hombre puede expresar. No se sacia el ojo de ver, ni el oído se harta de oír. </div>
<div id="Ecc_1_9" style="display:none;" class="ver_select"><b>Ecc 1:9</b>  Lo que fue, es lo que será, y lo que ha sido hecho, es lo mismo que se hará; y nada hay nuevo debajo del sol. </div>
<div id="Ecc_1_10" style="display:none;" class="ver_select"><b>Ecc 1:10</b>  ¿Hay algo de que se pueda decir: He aquí esto es nuevo? Ya fue en los siglos que nos han precedido. </div>
<div id="Ecc_1_11" style="display:none;" class="ver_select"><b>Ecc 1:11</b>  No hay memoria de lo que precedió, ni tampoco de lo que sucederá habrá memoria en los que serán después. </div>
<div id="Ecc_1_12" style="display:none;" class="ver_select"><b>Ecc 1:12</b>  Yo el Predicador fui rey sobre Israel en Jerusalén. </div>
<div id="Ecc_1_13" style="display:none;" class="ver_select"><b>Ecc 1:13</b>  Y di mi corazón a inquirir y buscar con sabiduría sobre todo lo que se hace debajo del cielo; este penoso trabajo dio Dios a los hijos de los hombres, para que se ocupen en él. </div>
<div id="Ecc_1_14" style="display:none;" class="ver_select"><b>Ecc 1:14</b>  Yo miré todas las obras que se hacen debajo del sol; y he aquí, todo ello es vanidad y aflicción de espíritu. </div>
<div id="Ecc_1_15" style="display:none;" class="ver_select"><b>Ecc 1:15</b>  Lo torcido no se puede enderezar; y lo incompleto no puede numerarse. </div>
<div id="Ecc_1_16" style="display:none;" class="ver_select"><b>Ecc 1:16</b>  Hablé yo con mi corazón, diciendo: He aquí yo me hallo engrandecido, y he crecido en sabiduría sobre todos los que fueron antes de mí en Jerusalén; y mi corazón ha percibido mucha sabiduría y ciencia. </div>
<div id="Ecc_1_17" style="display:none;" class="ver_select"><b>Ecc 1:17</b>  Y di mi corazón a conocer la sabiduría, y también a entender las locuras y los desvaríos; conocí que aun esto era aflicción de espíritu. </div>
<div id="Ecc_1_18" style="display:none;" class="ver_select"><b>Ecc 1:18</b>  Porque en la mucha sabiduría hay mucha molestia; y quien añade conocimiento, añade dolor. </div>
<div id="Ecc_2_1" style="display:none;" class="ver_select"><b>Ecc 2:1</b>  Dije yo en mi corazón: Ven ahora, te probaré con alegría, y gozarás del placer. Mas he aquí esto también era vanidad. </div>
<div id="Ecc_2_2" style="display:none;" class="ver_select"><b>Ecc 2:2</b>  A la risa dije: Enloqueces; y al placer: ¿De qué sirve esto? </div>
<div id="Ecc_2_3" style="display:none;" class="ver_select"><b>Ecc 2:3</b>  Propuse en mi corazón agasajar mi carne con vino, y que anduviese mi corazón en sabiduría, con retención de la necedad, hasta ver cuál fuese el bien de los hijos de los hombres, en el cual se ocuparan debajo del cielo todos los días de su vida. </div>
<div id="Ecc_2_4" style="display:none;" class="ver_select"><b>Ecc 2:4</b>  Engrandecí mis obras, me edifiqué casas, me planté viñas; </div>
<div id="Ecc_2_5" style="display:none;" class="ver_select"><b>Ecc 2:5</b>  me hice huertos y jardines, y planté en ellos árboles de toda clase de fruto; </div>
<div id="Ecc_2_6" style="display:none;" class="ver_select"><b>Ecc 2:6</b>  Me hice estanques de aguas, para regar de ellos el bosque donde los árboles crecían. </div>
<div id="Ecc_2_7" style="display:none;" class="ver_select"><b>Ecc 2:7</b>  Poseí siervos y siervas, y tuve siervos nacidos en casa; también tuve posesión grande de vacas y ovejas, más que todos los que fueron antes de mí en Jerusalén; </div>
<div id="Ecc_2_8" style="display:none;" class="ver_select"><b>Ecc 2:8</b>  Acumulé también plata y oro, y tesoro preciado de reyes y de provincias; me hice de cantores y cantoras, y de los deleites de los hijos de los hombres, y de toda clase de instrumentos de música. </div>
<div id="Ecc_2_9" style="display:none;" class="ver_select"><b>Ecc 2:9</b>  Y fui engrandecido y aumentado más que todos los que fueron antes de mí en Jerusalén; también permaneció conmigo mi sabiduría. </div>
<div id="Ecc_2_10" style="display:none;" class="ver_select"><b>Ecc 2:10</b>  No negué a mis ojos ninguna cosa que desearan, ni aparté mi corazón de placer alguno, porque mi corazón gozó de todo mi trabajo: y ésta fue mi parte de toda mi faena. </div>
<div id="Ecc_2_11" style="display:none;" class="ver_select"><b>Ecc 2:11</b>  Miré yo luego todas las obras que habían hecho mis manos, y el trabajo que tomé para hacerlas; y he aquí, todo era vanidad y aflicción de espíritu, y sin provecho debajo del sol. </div>
<div id="Ecc_2_12" style="display:none;" class="ver_select"><b>Ecc 2:12</b>  Después torné yo a mirar para ver la sabiduría y los desvaríos y la necedad; porque ¿qué podrá hacer el hombre que venga después del rey, sino lo que ya ha sido hecho? </div>
<div id="Ecc_2_13" style="display:none;" class="ver_select"><b>Ecc 2:13</b>  Y he visto que la sabiduría sobrepasa a la necedad, como la luz a las tinieblas. </div>
<div id="Ecc_2_14" style="display:none;" class="ver_select"><b>Ecc 2:14</b>  El sabio tiene sus ojos en su cabeza, mas el necio anda en tinieblas; pero también entendí yo que un mismo suceso acontecerá al uno como al otro. </div>
<div id="Ecc_2_15" style="display:none;" class="ver_select"><b>Ecc 2:15</b>  Entonces dije yo en mi corazón: Como sucederá al necio me sucederá también a mí: ¿Para qué, pues, he trabajado hasta ahora por hacerme más sabio? Y dije en mi corazón que también esto era vanidad. </div>
<div id="Ecc_2_16" style="display:none;" class="ver_select"><b>Ecc 2:16</b>  Porque ni del sabio ni del necio habrá memoria para siempre; pues en los días venideros ya todo será olvidado, y también morirá el sabio como el necio. </div>
<div id="Ecc_2_17" style="display:none;" class="ver_select"><b>Ecc 2:17</b>  Aborrecí por tanto la vida, porque la obra que se hace debajo del sol me era fastidiosa; por cuanto todo es vanidad y aflicción de espíritu. </div>
<div id="Ecc_2_18" style="display:none;" class="ver_select"><b>Ecc 2:18</b>  Asimismo aborrecí todo mi trabajo que había puesto por obra debajo del sol; el cual tendré que dejar a otro que vendrá después de mí. </div>
<div id="Ecc_2_19" style="display:none;" class="ver_select"><b>Ecc 2:19</b>  ¿Y quién sabe si será sabio, o necio, el que señoreará sobre todo mi trabajo en que yo me afané, y en que ocupé debajo del sol mi sabiduría? Esto también es vanidad. </div>
<div id="Ecc_2_20" style="display:none;" class="ver_select"><b>Ecc 2:20</b>  Por tanto, volví a desesperanzar mi corazón acerca de todo el trabajo en que me afané, y en que había ocupado debajo del sol mi sabiduría. </div>
<div id="Ecc_2_21" style="display:none;" class="ver_select"><b>Ecc 2:21</b>  ¡Que el hombre trabaje con sabiduría, y con ciencia, y con rectitud, y que haya de dar su hacienda a hombre que nunca trabajó en ello! También esto es vanidad y mal grande. </div>
<div id="Ecc_2_22" style="display:none;" class="ver_select"><b>Ecc 2:22</b>  Porque ¿qué tiene el hombre de todo su trabajo, y de la fatiga de su corazón, con que se afana debajo del sol? </div>
<div id="Ecc_2_23" style="display:none;" class="ver_select"><b>Ecc 2:23</b>  Porque todos sus días no son sino dolores, y sus trabajos molestias; aun de noche su corazón no reposa. Esto también es vanidad. </div>
<div id="Ecc_2_24" style="display:none;" class="ver_select"><b>Ecc 2:24</b>  No hay cosa mejor para el hombre sino que coma y beba, y que su alma vea el bien de su trabajo. También he visto que esto es de la mano de Dios. </div>
<div id="Ecc_2_25" style="display:none;" class="ver_select"><b>Ecc 2:25</b>  Porque ¿quién comerá, y quién se cuidará, mejor que yo? </div>
<div id="Ecc_2_26" style="display:none;" class="ver_select"><b>Ecc 2:26</b>  Porque al hombre que le agrada, Dios le da sabiduría, ciencia y gozo; mas al pecador da el trabajo de recoger y amontonar, para darlo al que agrada a Dios. También esto es vanidad y aflicción de espíritu. </div>
<div id="Ecc_3_1" style="display:none;" class="ver_select"><b>Ecc 3:1</b>  Para todo hay sazón, y todo lo que se quiere debajo del cielo tiene su tiempo: </div>
<div id="Ecc_3_2" style="display:none;" class="ver_select"><b>Ecc 3:2</b>  Tiempo de nacer, y tiempo de morir; tiempo de plantar, y tiempo de arrancar lo plantado; </div>
<div id="Ecc_3_3" style="display:none;" class="ver_select"><b>Ecc 3:3</b>  Tiempo de matar, y tiempo de curar; tiempo de destruir, y tiempo de edificar; </div>
<div id="Ecc_3_4" style="display:none;" class="ver_select"><b>Ecc 3:4</b>  Tiempo de llorar, y tiempo de reír; tiempo de endechar, y tiempo de bailar; </div>
<div id="Ecc_3_5" style="display:none;" class="ver_select"><b>Ecc 3:5</b>  Tiempo de esparcir piedras, y tiempo de juntar piedras; tiempo de abrazar, y tiempo de abstenerse de abrazar; </div>
<div id="Ecc_3_6" style="display:none;" class="ver_select"><b>Ecc 3:6</b>  Tiempo de buscar, y tiempo de perder; tiempo de guardar, y tiempo de desechar; </div>
<div id="Ecc_3_7" style="display:none;" class="ver_select"><b>Ecc 3:7</b>  Tiempo de romper, y tiempo de coser; tiempo de callar, y tiempo de hablar; </div>
<div id="Ecc_3_8" style="display:none;" class="ver_select"><b>Ecc 3:8</b>  Tiempo de amar, y tiempo de aborrecer; tiempo de guerra, y tiempo de paz. </div>
<div id="Ecc_3_9" style="display:none;" class="ver_select"><b>Ecc 3:9</b>  ¿Qué provecho tiene el que trabaja en lo que trabaja? </div>
<div id="Ecc_3_10" style="display:none;" class="ver_select"><b>Ecc 3:10</b>  Yo he visto el trabajo que Dios ha dado a los hijos de los hombres para que en él se ocupen. </div>
<div id="Ecc_3_11" style="display:none;" class="ver_select"><b>Ecc 3:11</b>  Todo lo hizo hermoso en su tiempo; y aun puso un mundo en su corazón, de tal manera que no alcance el hombre la obra de Dios desde el principio hasta el fin. </div>
<div id="Ecc_3_12" style="display:none;" class="ver_select"><b>Ecc 3:12</b>  Yo he conocido que no hay para ellos cosa mejor que alegrarse, y hacer bien en su vida; </div>
<div id="Ecc_3_13" style="display:none;" class="ver_select"><b>Ecc 3:13</b>  Y también que es don de Dios que todo hombre coma y beba, y goce el bien de toda su labor. </div>
<div id="Ecc_3_14" style="display:none;" class="ver_select"><b>Ecc 3:14</b>  Yo he entendido que todo lo que Dios hace será perpetuo: sobre aquello no se añadirá, ni de ello se disminuirá; y lo hace Dios, para que delante de Él teman los hombres. </div>
<div id="Ecc_3_15" style="display:none;" class="ver_select"><b>Ecc 3:15</b>  Aquello que fue, ya es: y lo que ha de ser, fue ya; y Dios demanda lo que pasó. </div>
<div id="Ecc_3_16" style="display:none;" class="ver_select"><b>Ecc 3:16</b>  Vi más debajo del sol: en lugar del juicio, allí la impiedad; y en lugar de la justicia, allí la iniquidad. </div>
<div id="Ecc_3_17" style="display:none;" class="ver_select"><b>Ecc 3:17</b>  Y dije yo en mi corazón: Al justo y al impío juzgará Dios; porque allí hay un tiempo para todo lo que se quiere y sobre todo lo que se hace. </div>
<div id="Ecc_3_18" style="display:none;" class="ver_select"><b>Ecc 3:18</b>  Dije en mi corazón: En cuanto a la condición de los hijos de los hombres, que Dios los pruebe, para que ellos mismos vean que son semejantes a las bestias. </div>
<div id="Ecc_3_19" style="display:none;" class="ver_select"><b>Ecc 3:19</b>  Porque lo que sucede a los hijos de los hombres, y lo que sucede a las bestias, un mismo suceso es; como mueren los unos, así mueren los otros; y una misma respiración tienen todos; ni tiene más el hombre que la bestia; porque todo es vanidad. </div>
<div id="Ecc_3_20" style="display:none;" class="ver_select"><b>Ecc 3:20</b>  Todo va a un mismo lugar; todo es hecho del polvo, y todo volverá al mismo polvo. </div>
<div id="Ecc_3_21" style="display:none;" class="ver_select"><b>Ecc 3:21</b>  ¿Quién sabe que el espíritu de los hijos de los hombres sube arriba, y que el espíritu del animal desciende abajo a la tierra? </div>
<div id="Ecc_3_22" style="display:none;" class="ver_select"><b>Ecc 3:22</b>  Así que he visto que no hay cosa mejor que alegrarse el hombre con lo que hiciere; porque ésta es su parte; porque ¿quién lo llevará para que vea lo que ha de ser después de él? </div>
<div id="Ecc_4_1" style="display:none;" class="ver_select"><b>Ecc 4:1</b>  Y me volví yo, y vi todas las violencias que se hacen debajo del sol; y he aquí las lágrimas de los oprimidos, sin tener quien los consuele; y la fuerza estaba en la mano de sus opresores, y para ellos no había consolador. </div>
<div id="Ecc_4_2" style="display:none;" class="ver_select"><b>Ecc 4:2</b>  Y alabé yo a los muertos, los que ya murieron, más que a los vivientes, los que aún están con vida. </div>
<div id="Ecc_4_3" style="display:none;" class="ver_select"><b>Ecc 4:3</b>  Y tuve por mejor que unos y otros, al que no ha sido aún, que no ha visto las malas obras que debajo del sol se hacen. </div>
<div id="Ecc_4_4" style="display:none;" class="ver_select"><b>Ecc 4:4</b>  He visto asimismo que todo trabajo y toda excelencia de obra despierta la envidia del hombre contra su prójimo. También esto es vanidad y aflicción de espíritu. </div>
<div id="Ecc_4_5" style="display:none;" class="ver_select"><b>Ecc 4:5</b>  El necio dobla sus manos y come su propia carne. </div>
<div id="Ecc_4_6" style="display:none;" class="ver_select"><b>Ecc 4:6</b>  Mas vale un puño lleno con descanso, que ambos puños llenos con trabajo y aflicción de espíritu. </div>
<div id="Ecc_4_7" style="display:none;" class="ver_select"><b>Ecc 4:7</b>  Yo me torné otra vez, y vi vanidad debajo del sol. </div>
<div id="Ecc_4_8" style="display:none;" class="ver_select"><b>Ecc 4:8</b>  Está un hombre solo y sin sucesor; que ni tiene hijo ni hermano; mas nunca cesa de trabajar, ni sus ojos se sacian de sus riquezas, ni se pregunta: ¿Para quién trabajo yo, y privo mi alma del bien? También esto es vanidad, y duro trabajo. </div>
<div id="Ecc_4_9" style="display:none;" class="ver_select"><b>Ecc 4:9</b>  Mejores son dos que uno; porque tienen mejor paga de su trabajo. </div>
<div id="Ecc_4_10" style="display:none;" class="ver_select"><b>Ecc 4:10</b>  Porque si cayeren, el uno levantará a su compañero. Pero ¡ay del solo cuando cayere! Pues no habrá segundo que lo levante. </div>
<div id="Ecc_4_11" style="display:none;" class="ver_select"><b>Ecc 4:11</b>  También si dos durmieren juntos, se calentarán; mas ¿cómo se calentará uno solo? </div>
<div id="Ecc_4_12" style="display:none;" class="ver_select"><b>Ecc 4:12</b>  Y si alguno prevaleciere contra el uno, dos estarán contra él; y cordón de tres dobleces no presto se rompe. </div>
<div id="Ecc_4_13" style="display:none;" class="ver_select"><b>Ecc 4:13</b>  Mejor es el muchacho pobre y sabio, que el rey viejo y fatuo que no admite consejo. </div>
<div id="Ecc_4_14" style="display:none;" class="ver_select"><b>Ecc 4:14</b>  Porque de la cárcel salió para reinar; mientras el nacido en su reino se hizo pobre. </div>
<div id="Ecc_4_15" style="display:none;" class="ver_select"><b>Ecc 4:15</b>  Vi a todos los vivientes debajo del sol caminando con el muchacho, sucesor, que estará en lugar de aquél. </div>
<div id="Ecc_4_16" style="display:none;" class="ver_select"><b>Ecc 4:16</b>  No tenía fin la muchedumbre de pueblo que fue antes de ellos; aun los que vendrán después tampoco estarán contentos con él. Y esto es también vanidad y aflicción de espíritu. </div>
<div id="Ecc_5_1" style="display:none;" class="ver_select"><b>Ecc 5:1</b>  Cuando fueres a la casa de Dios, guarda tu pie; y acércate más para oír que para dar el sacrificio de los necios, porque no saben que hacen mal. </div>
<div id="Ecc_5_2" style="display:none;" class="ver_select"><b>Ecc 5:2</b>  No te des prisa con tu boca, ni tu corazón se apresure a proferir palabra delante de Dios; porque Dios está en el cielo, y tú en la tierra; por tanto, sean pocas tus palabras. </div>
<div id="Ecc_5_3" style="display:none;" class="ver_select"><b>Ecc 5:3</b>  Porque de la mucha ocupación viene el sueño, y de la multitud de las palabras la voz del necio. </div>
<div id="Ecc_5_4" style="display:none;" class="ver_select"><b>Ecc 5:4</b>  Cuando a Dios hicieres promesa, no tardes en cumplirla; porque Él no se agrada de los insensatos. Cumple lo que prometes. </div>
<div id="Ecc_5_5" style="display:none;" class="ver_select"><b>Ecc 5:5</b>  Mejor es que no prometas, a que prometas y no cumplas. </div>
<div id="Ecc_5_6" style="display:none;" class="ver_select"><b>Ecc 5:6</b>  No sueltes tu boca para hacer pecar a tu carne; ni digas delante del ángel, que fue ignorancia. ¿Por qué harás que Dios se enoje a causa de tu voz, y que destruya la obra de tus manos? </div>
<div id="Ecc_5_7" style="display:none;" class="ver_select"><b>Ecc 5:7</b>  Donde los sueños son en multitud, también lo son las vanidades y las muchas palabras; mas tú, teme a Dios. </div>
<div id="Ecc_5_8" style="display:none;" class="ver_select"><b>Ecc 5:8</b>  Si opresión de pobres, y extorsión de derecho y de justicia vieres en la provincia, no te maravilles de ello; porque sobre el alto está mirando otro más alto, y uno más alto está sobre ellos. </div>
<div id="Ecc_5_9" style="display:none;" class="ver_select"><b>Ecc 5:9</b>  Además el provecho de la tierra es para todos; el rey mismo está sujeto a los campos. </div>
<div id="Ecc_5_10" style="display:none;" class="ver_select"><b>Ecc 5:10</b>  El que ama el dinero, no se saciará de dinero; y el que ama el mucho tener, no sacará fruto. También esto es vanidad. </div>
<div id="Ecc_5_11" style="display:none;" class="ver_select"><b>Ecc 5:11</b>  Cuando los bienes aumentan, también aumentan los que los consumen. ¿Qué bien, pues, tendrá su dueño, sino verlos con sus ojos? </div>
<div id="Ecc_5_12" style="display:none;" class="ver_select"><b>Ecc 5:12</b>  Dulce es el sueño del trabajador, ya sea que coma mucho o poco; mas al rico no le deja dormir la abundancia. </div>
<div id="Ecc_5_13" style="display:none;" class="ver_select"><b>Ecc 5:13</b>  Hay un grave mal que he visto debajo del sol; las riquezas guardadas por sus dueños para su propio mal; </div>
<div id="Ecc_5_14" style="display:none;" class="ver_select"><b>Ecc 5:14</b>  Las cuales se pierden en malas ocupaciones, y a los hijos que engendraron nada les queda en la mano. </div>
<div id="Ecc_5_15" style="display:none;" class="ver_select"><b>Ecc 5:15</b>  Como salió del vientre de su madre, desnudo, así volverá, yéndose tal como vino; y nada tomará de su trabajo para llevar en su mano. </div>
<div id="Ecc_5_16" style="display:none;" class="ver_select"><b>Ecc 5:16</b>  Éste también es un grave mal, que como vino, así haya de volver. ¿Y de qué le aprovechó trabajar al viento? </div>
<div id="Ecc_5_17" style="display:none;" class="ver_select"><b>Ecc 5:17</b>  Además de esto, todos los días de su vida comerá en tinieblas, con mucho enojo y dolor y miseria. </div>
<div id="Ecc_5_18" style="display:none;" class="ver_select"><b>Ecc 5:18</b>  He aquí, pues, el bien que yo he visto: Que es bueno comer y beber, y gozarse uno del bien de todo su trabajo con que se afana debajo del sol, todos los días de su vida que Dios le da; porque ésta es su porción. </div>
<div id="Ecc_5_19" style="display:none;" class="ver_select"><b>Ecc 5:19</b>  Igualmente, a todo hombre a quien Dios le da riquezas y bienes, y le da también facultad para que coma de ellos y tome su porción y goce de su trabajo. Esto es don de Dios. </div>
<div id="Ecc_5_20" style="display:none;" class="ver_select"><b>Ecc 5:20</b>  Porque no se acordará mucho de los días de su vida; pues Dios le responderá con alegría de su corazón. </div>
<div id="Ecc_6_1" style="display:none;" class="ver_select"><b>Ecc 6:1</b>  Hay un mal que he visto debajo del cielo, y muy común entre los hombres: </div>
<div id="Ecc_6_2" style="display:none;" class="ver_select"><b>Ecc 6:2</b>  Un hombre a quien Dios da riquezas, bienes y honra, y nada le falta de todo lo que su alma desea; mas Dios no le da facultad de comer de ello, sino que los extraños se lo comen. Esto es vanidad y penosa enfermedad. </div>
<div id="Ecc_6_3" style="display:none;" class="ver_select"><b>Ecc 6:3</b>  Si el hombre engendrare cien hijos, y viviere muchos años, y los días de su edad fueren numerosos; si su alma no se sació del bien, y también careció de sepultura, yo digo que el abortivo es mejor que él. </div>
<div id="Ecc_6_4" style="display:none;" class="ver_select"><b>Ecc 6:4</b>  Porque en vano vino, y a tinieblas va, y con tinieblas será cubierto su nombre. </div>
<div id="Ecc_6_5" style="display:none;" class="ver_select"><b>Ecc 6:5</b>  Aunque no haya visto el sol, ni conocido nada, más reposo tiene éste que aquél. </div>
<div id="Ecc_6_6" style="display:none;" class="ver_select"><b>Ecc 6:6</b>  Aunque aquél viviere mil años dos veces, sin haber gozado del bien, ¿no van todos a un mismo lugar? </div>
<div id="Ecc_6_7" style="display:none;" class="ver_select"><b>Ecc 6:7</b>  Todo el trabajo del hombre es para su boca, y con todo eso su alma no se sacia. </div>
<div id="Ecc_6_8" style="display:none;" class="ver_select"><b>Ecc 6:8</b>  Porque ¿qué más tiene el sabio que el necio? ¿Qué más tiene el pobre que supo caminar entre los vivos? </div>
<div id="Ecc_6_9" style="display:none;" class="ver_select"><b>Ecc 6:9</b>  Más vale vista de ojos que deseo que pasa. Y también esto es vanidad y aflicción de espíritu. </div>
<div id="Ecc_6_10" style="display:none;" class="ver_select"><b>Ecc 6:10</b>  El que es, ya su nombre ha sido nombrado; y se sabe que es hombre, y que no podrá contender con Aquél que es más poderoso que él. </div>
<div id="Ecc_6_11" style="display:none;" class="ver_select"><b>Ecc 6:11</b>  Ciertamente las muchas palabras multiplican la vanidad. ¿Qué más tiene el hombre? </div>
<div id="Ecc_6_12" style="display:none;" class="ver_select"><b>Ecc 6:12</b>  Porque ¿quién sabe cuál es el bien del hombre en la vida, todos los días de la vida de su vanidad, los cuales él pasa como sombra? Porque ¿quién enseñará al hombre qué será después de él debajo del sol? </div>
<div id="Ecc_7_1" style="display:none;" class="ver_select"><b>Ecc 7:1</b>  Mejor es la buena fama que el buen ungüento; y el día de la muerte que el día del nacimiento. </div>
<div id="Ecc_7_2" style="display:none;" class="ver_select"><b>Ecc 7:2</b>  Mejor es ir a la casa del luto que a la casa del banquete; porque aquello es el fin de todos los hombres, y el que vive lo pondrá en su corazón. </div>
<div id="Ecc_7_3" style="display:none;" class="ver_select"><b>Ecc 7:3</b>  Mejor es el pesar que la risa; porque con la tristeza del rostro se enmendará el corazón. </div>
<div id="Ecc_7_4" style="display:none;" class="ver_select"><b>Ecc 7:4</b>  El corazón de los sabios, está en la casa del luto, mas el corazón de los insensatos, en la casa del placer. </div>
<div id="Ecc_7_5" style="display:none;" class="ver_select"><b>Ecc 7:5</b>  Mejor es oír la reprensión del sabio, que la canción de los necios. </div>
<div id="Ecc_7_6" style="display:none;" class="ver_select"><b>Ecc 7:6</b>  Porque la risa del necio es como el estrépito de las espinas debajo de la olla. Y también esto es vanidad. </div>
<div id="Ecc_7_7" style="display:none;" class="ver_select"><b>Ecc 7:7</b>  Ciertamente la opresión hace enloquecer al sabio; y el soborno corrompe el corazón. </div>
<div id="Ecc_7_8" style="display:none;" class="ver_select"><b>Ecc 7:8</b>  Mejor es el fin del asunto que su principio; mejor es el sufrido de espíritu que el altivo de espíritu. </div>
<div id="Ecc_7_9" style="display:none;" class="ver_select"><b>Ecc 7:9</b>  No te apresures en tu espíritu a enojarte, porque la ira en el seno de los necios reposa. </div>
<div id="Ecc_7_10" style="display:none;" class="ver_select"><b>Ecc 7:10</b>  Nunca digas: ¿Cuál es la causa que los tiempos pasados fueron mejores que éstos? Porque nunca de esto preguntarás con sabiduría. </div>
<div id="Ecc_7_11" style="display:none;" class="ver_select"><b>Ecc 7:11</b>  Buena es la sabiduría con herencia; y más a los que ven el sol. </div>
<div id="Ecc_7_12" style="display:none;" class="ver_select"><b>Ecc 7:12</b>  Porque escudo es la sabiduría, y escudo es el dinero; mas la excelencia del conocimiento, es que la sabiduría da vida a los que la poseen. </div>
<div id="Ecc_7_13" style="display:none;" class="ver_select"><b>Ecc 7:13</b>  Considera la obra de Dios; porque ¿quién podrá enderezar lo que Él torció? </div>
<div id="Ecc_7_14" style="display:none;" class="ver_select"><b>Ecc 7:14</b>  En el día del bien goza del bien; y en el día del mal considera. Dios también hizo esto delante de lo otro, para que el hombre no descubra nada después de él. </div>
<div id="Ecc_7_15" style="display:none;" class="ver_select"><b>Ecc 7:15</b>  Todo esto he visto en los días de mi vanidad. Justo hay que perece por su justicia, y hay impío que por su maldad alarga sus días. </div>
<div id="Ecc_7_16" style="display:none;" class="ver_select"><b>Ecc 7:16</b>  No seas demasiado justo, ni seas sabio en exceso; ¿por qué habrás de destruirte? </div>
<div id="Ecc_7_17" style="display:none;" class="ver_select"><b>Ecc 7:17</b>  No hagas mucho mal, ni seas insensato; ¿por qué habrás de morir antes de tu tiempo? </div>
<div id="Ecc_7_18" style="display:none;" class="ver_select"><b>Ecc 7:18</b>  Bueno es que tomes esto, y también de esto otro no apartes tu mano; porque el que teme a Dios, saldrá con todo. </div>
<div id="Ecc_7_19" style="display:none;" class="ver_select"><b>Ecc 7:19</b>  La sabiduría fortalece al sabio más que diez poderosos que haya en la ciudad. </div>
<div id="Ecc_7_20" style="display:none;" class="ver_select"><b>Ecc 7:20</b>  Ciertamente no hay hombre justo en la tierra, que haga el bien y nunca peque. </div>
<div id="Ecc_7_21" style="display:none;" class="ver_select"><b>Ecc 7:21</b>  Tampoco apliques tu corazón a todas las cosas que se dicen, no sea que oigas a tu siervo que habla mal de ti: </div>
<div id="Ecc_7_22" style="display:none;" class="ver_select"><b>Ecc 7:22</b>  Pues tu corazón sabe que muchas veces tú también has hablado mal de otros. </div>
<div id="Ecc_7_23" style="display:none;" class="ver_select"><b>Ecc 7:23</b>  Todas estas cosas probé con sabiduría, diciendo: Me haré sabio; pero la sabiduría estaba lejos de mí. </div>
<div id="Ecc_7_24" style="display:none;" class="ver_select"><b>Ecc 7:24</b>  Lejos está lo que fue; y lo muy profundo, ¿quién lo hallará? </div>
<div id="Ecc_7_25" style="display:none;" class="ver_select"><b>Ecc 7:25</b>  Apliqué mi corazón al saber y a examinar; a inquirir la sabiduría y la razón; para conocer la maldad de la insensatez, y la necedad de la locura. </div>
<div id="Ecc_7_26" style="display:none;" class="ver_select"><b>Ecc 7:26</b>  Y he hallado más amarga que la muerte a la mujer cuyo corazón es lazos y redes, y sus manos son como ataduras. El que agrada a Dios escapará de ella; mas el pecador será apresado por ella. </div>
<div id="Ecc_7_27" style="display:none;" class="ver_select"><b>Ecc 7:27</b>  He aquí, esto he hallado, dice el Predicador, pesando las cosas una por una para hallar la razón. </div>
<div id="Ecc_7_28" style="display:none;" class="ver_select"><b>Ecc 7:28</b>  Lo que aún busca mi alma, y no lo encuentra: Un hombre entre mil he hallado; pero mujer entre todas éstas nunca hallé. </div>
<div id="Ecc_7_29" style="display:none;" class="ver_select"><b>Ecc 7:29</b>  He aquí, solamente esto he hallado; que Dios hizo al hombre recto, mas ellos buscaron muchas imaginaciones. </div>
<div id="Ecc_8_1" style="display:none;" class="ver_select"><b>Ecc 8:1</b>  ¿Quién como el sabio? ¿Y quién como el que sabe la declaración de las cosas? La sabiduría del hombre iluminará su rostro, y la tosquedad de su semblante se mudará. </div>
<div id="Ecc_8_2" style="display:none;" class="ver_select"><b>Ecc 8:2</b>  Yo te aconsejo que guardes el mandamiento del rey y la palabra del juramento de Dios. </div>
<div id="Ecc_8_3" style="display:none;" class="ver_select"><b>Ecc 8:3</b>  No te apresures a irte de delante de él, ni en cosa mala persistas; porque él hará todo lo que le plazca. </div>
<div id="Ecc_8_4" style="display:none;" class="ver_select"><b>Ecc 8:4</b>  Pues la palabra del rey es con potestad, ¿y quién le dirá: ¿Qué haces? </div>
<div id="Ecc_8_5" style="display:none;" class="ver_select"><b>Ecc 8:5</b>  El que guarda el mandamiento no experimentará mal; y el corazón del sabio discierne el tiempo y el juicio. </div>
<div id="Ecc_8_6" style="display:none;" class="ver_select"><b>Ecc 8:6</b>  Porque para todo lo que quisieres hay tiempo y juicio; mas el trabajo del hombre es grande sobre él; </div>
<div id="Ecc_8_7" style="display:none;" class="ver_select"><b>Ecc 8:7</b>  Porque no sabe lo que ha de ser; y el cuándo haya de ser, ¿quién se lo enseñará? </div>
<div id="Ecc_8_8" style="display:none;" class="ver_select"><b>Ecc 8:8</b>  No hay hombre que tenga potestad sobre el espíritu para retener el espíritu, ni potestad sobre el día de la muerte; y no se da de baja en tal guerra, ni la impiedad librará al que se entregue a ella. </div>
<div id="Ecc_8_9" style="display:none;" class="ver_select"><b>Ecc 8:9</b>  Todo esto he visto, y he puesto mi corazón en todo lo que debajo del sol se hace; hay tiempo en que el hombre se enseñorea del hombre para su propio mal. </div>
<div id="Ecc_8_10" style="display:none;" class="ver_select"><b>Ecc 8:10</b>  También he visto a los impíos ser sepultados, los cuáles entraban y salían del lugar santo, y ser olvidados en la ciudad donde esto hicieron. Esto también es vanidad. </div>
<div id="Ecc_8_11" style="display:none;" class="ver_select"><b>Ecc 8:11</b>  Por cuanto no se ejecuta luego sentencia sobre la mala obra, el corazón de los hijos de los hombres está entregado para hacer el mal. </div>
<div id="Ecc_8_12" style="display:none;" class="ver_select"><b>Ecc 8:12</b>  Bien que el pecador haga mal cien veces, y sus días le sean prolongados, con todo yo también sé que los que a Dios temen tendrán bien, los que temen ante su presencia; </div>
<div id="Ecc_8_13" style="display:none;" class="ver_select"><b>Ecc 8:13</b>  Pero no le irá bien al impío, ni le serán prolongados sus días, que son como sombra; por cuanto no teme ante la presencia de Dios. </div>
<div id="Ecc_8_14" style="display:none;" class="ver_select"><b>Ecc 8:14</b>  Hay vanidad que se hace sobre la tierra; que hay justos a quienes sucede como si hicieran obras de impíos; y hay impíos a quienes acontece como si hicieran obras de justos. Digo que esto también es vanidad. </div>
<div id="Ecc_8_15" style="display:none;" class="ver_select"><b>Ecc 8:15</b>  Por tanto, alabé yo la alegría; pues el hombre no tiene mejor bien debajo del sol, que comer y beber y alegrarse; y que esto le quede de su trabajo los días de su vida que Dios le concede debajo del sol. </div>
<div id="Ecc_8_16" style="display:none;" class="ver_select"><b>Ecc 8:16</b>  Yo pues di mi corazón a conocer sabiduría, y a ver la faena que se hace sobre la tierra (porque hay quien ni de noche ni de día ve sueño en sus ojos); </div>
<div id="Ecc_8_17" style="display:none;" class="ver_select"><b>Ecc 8:17</b>  Y he visto todas las obras de Dios, que el hombre no puede alcanzar la obra que debajo del sol se hace; por mucho que se afane el hombre buscándola, no la hallará: aunque diga el sabio que la sabe, no por eso podrá alcanzarla. </div>
<div id="Ecc_9_1" style="display:none;" class="ver_select"><b>Ecc 9:1</b>  Ciertamente he dado mi corazón a todas estas cosas, para declarar todo esto; que los justos y los sabios, y sus obras, están en la mano de Dios; y que no saben los hombres ni el amor ni el odio; todo está delante de ellos. </div>
<div id="Ecc_9_2" style="display:none;" class="ver_select"><b>Ecc 9:2</b>  Todo acontece de la misma manera a todos; un mismo suceso acontece al justo y al impío; al bueno, al limpio y al no limpio; al que sacrifica, y al que no sacrifica; como el bueno, así el que peca; el que jura, como el que teme el juramento. </div>
<div id="Ecc_9_3" style="display:none;" class="ver_select"><b>Ecc 9:3</b>  Este mal hay entre todo lo que se hace debajo del sol, que todos tengan un mismo suceso, y también que el corazón de los hijos de los hombres esté lleno de mal y de enloquecimiento en su corazón durante su vida; y después, se van a los muertos. </div>
<div id="Ecc_9_4" style="display:none;" class="ver_select"><b>Ecc 9:4</b>  Aún hay esperanza para todo aquél que está entre los vivos; porque mejor es perro vivo que león muerto. </div>
<div id="Ecc_9_5" style="display:none;" class="ver_select"><b>Ecc 9:5</b>  Porque los que viven saben que han de morir; pero los muertos nada saben, ni tienen más paga; porque su memoria es puesta en olvido. </div>
<div id="Ecc_9_6" style="display:none;" class="ver_select"><b>Ecc 9:6</b>  También su amor, su odio y su envidia, fenecieron ya; y nunca más tendrán parte en todo lo que se hace debajo del sol. </div>
<div id="Ecc_9_7" style="display:none;" class="ver_select"><b>Ecc 9:7</b>  Anda, y come tu pan con gozo, y bebe tu vino con alegre corazón; porque tus obras ya son agradables a Dios. </div>
<div id="Ecc_9_8" style="display:none;" class="ver_select"><b>Ecc 9:8</b>  En todo tiempo sean blancas tus vestiduras, y nunca falte ungüento sobre tu cabeza. </div>
<div id="Ecc_9_9" style="display:none;" class="ver_select"><b>Ecc 9:9</b>  Goza de la vida con la esposa que amas, todos los días de la vida de tu vanidad, que te son dados debajo del sol, todos los días de tu vanidad; porque ésta es tu parte en la vida, y en tu trabajo con que te afanas debajo del sol. </div>
<div id="Ecc_9_10" style="display:none;" class="ver_select"><b>Ecc 9:10</b>  Todo lo que te viniere a la mano para hacer, hazlo según tus fuerzas; porque en el sepulcro, adonde tú vas, no hay obra, ni industria, ni conocimiento, ni sabiduría. </div>
<div id="Ecc_9_11" style="display:none;" class="ver_select"><b>Ecc 9:11</b>  Me volví, y vi debajo del sol, que ni es de los ligeros la carrera, ni la guerra de los fuertes, ni aun de los sabios el pan, ni de los prudentes las riquezas, ni de los elocuentes el favor; sino que tiempo y ocasión acontece a todos. </div>
<div id="Ecc_9_12" style="display:none;" class="ver_select"><b>Ecc 9:12</b>  Porque el hombre tampoco conoce su tiempo; como los peces que son presos en la mala red, y como las aves que se prenden en lazo, así son enlazados los hijos de los hombres en el tiempo malo, cuando éste cae de repente sobre ellos. </div>
<div id="Ecc_9_13" style="display:none;" class="ver_select"><b>Ecc 9:13</b>  También vi esta sabiduría debajo del sol, la cual me parece grande: </div>
<div id="Ecc_9_14" style="display:none;" class="ver_select"><b>Ecc 9:14</b>  Había una pequeña ciudad, y pocos hombres en ella; y vino contra ella un gran rey, y la sitió, y edificó contra ella grandes baluartes; </div>
<div id="Ecc_9_15" style="display:none;" class="ver_select"><b>Ecc 9:15</b>  y se halló en ella un hombre pobre, sabio, el cual libró la ciudad con su sabiduría; sin embargo, nadie se acordó de aquel hombre pobre. </div>
<div id="Ecc_9_16" style="display:none;" class="ver_select"><b>Ecc 9:16</b>  Entonces dije yo: Mejor es la sabiduría que la fortaleza; aunque la sabiduría del pobre sea menospreciada, y no sean escuchadas sus palabras. </div>
<div id="Ecc_9_17" style="display:none;" class="ver_select"><b>Ecc 9:17</b>  Las palabras del sabio dichas en quietud son oídas, más que los gritos del que gobierna entre los necios. </div>
<div id="Ecc_9_18" style="display:none;" class="ver_select"><b>Ecc 9:18</b>  Mejor es la sabiduría que las armas de guerra; pero un pecador destruye mucho bien. </div>
<div id="Ecc_10_1" style="display:none;" class="ver_select"><b>Ecc 10:1</b>  Las moscas muertas hacen que el perfume del perfumista dé mal olor; así una pequeña locura, al estimado como sabio y honorable. </div>
<div id="Ecc_10_2" style="display:none;" class="ver_select"><b>Ecc 10:2</b>  El corazón del sabio está a su mano derecha; mas el corazón del necio a su mano izquierda. </div>
<div id="Ecc_10_3" style="display:none;" class="ver_select"><b>Ecc 10:3</b>  Y aun mientras va el necio por el camino, le falta la cordura, y va diciendo a todos, que es necio. </div>
<div id="Ecc_10_4" style="display:none;" class="ver_select"><b>Ecc 10:4</b>  Si el espíritu del príncipe se exaltare contra ti, no dejes tu lugar; porque el ceder hará cesar grandes ofensas. </div>
<div id="Ecc_10_5" style="display:none;" class="ver_select"><b>Ecc 10:5</b>  Hay un mal que he visto debajo del sol, como el error emanado del príncipe; </div>
<div id="Ecc_10_6" style="display:none;" class="ver_select"><b>Ecc 10:6</b>  la necedad está colocada en grandes alturas, y los ricos están sentados en lugar bajo. </div>
<div id="Ecc_10_7" style="display:none;" class="ver_select"><b>Ecc 10:7</b>  Vi siervos a caballo, y príncipes caminando como siervos sobre la tierra. </div>
<div id="Ecc_10_8" style="display:none;" class="ver_select"><b>Ecc 10:8</b>  El que hiciere el hoyo caerá en él; y al que rompiere el vallado, le morderá la serpiente. </div>
<div id="Ecc_10_9" style="display:none;" class="ver_select"><b>Ecc 10:9</b>  El que remueve las piedras, se herirá con ellas; el que parte la leña, en ello peligrará. </div>
<div id="Ecc_10_10" style="display:none;" class="ver_select"><b>Ecc 10:10</b>  Si se embotare el hierro, y su filo no fuere amolado, hay que añadir entonces más fuerza; pero la sabiduría es provechosa para dirigir. </div>
<div id="Ecc_10_11" style="display:none;" class="ver_select"><b>Ecc 10:11</b>  Muerde la serpiente cuando no está encantada, y el lenguaraz no es mejor. </div>
<div id="Ecc_10_12" style="display:none;" class="ver_select"><b>Ecc 10:12</b>  Las palabras de la boca del sabio son gracia; mas los labios del necio causan su propia ruina. </div>
<div id="Ecc_10_13" style="display:none;" class="ver_select"><b>Ecc 10:13</b>  El principio de las palabras de su boca es necedad; y el fin de su charla, nocivo desvarío. </div>
<div id="Ecc_10_14" style="display:none;" class="ver_select"><b>Ecc 10:14</b>  El necio multiplica las palabras; el hombre no sabe lo que ha de ser; ¿y quién le hará saber lo que después de él será? </div>
<div id="Ecc_10_15" style="display:none;" class="ver_select"><b>Ecc 10:15</b>  El trabajo de los necios los fatiga; porque no saben por dónde ir a la ciudad. </div>
<div id="Ecc_10_16" style="display:none;" class="ver_select"><b>Ecc 10:16</b>  ¡Ay de ti, tierra, cuando tu rey es muchacho, y tus príncipes banquetean de mañana! </div>
<div id="Ecc_10_17" style="display:none;" class="ver_select"><b>Ecc 10:17</b>  ¡Bienaventurada, tú, tierra, cuando tu rey es hijo de nobles, y tus príncipes comen a su hora, para reponer sus fuerzas y no para embriagarse! </div>
<div id="Ecc_10_18" style="display:none;" class="ver_select"><b>Ecc 10:18</b>  Por la pereza se cae la techumbre, y por la flojedad de manos se llueve la casa. </div>
<div id="Ecc_10_19" style="display:none;" class="ver_select"><b>Ecc 10:19</b>  Por el placer se hace el convite, y el vino alegra a los vivos; y el dinero responde a todo. </div>
<div id="Ecc_10_20" style="display:none;" class="ver_select"><b>Ecc 10:20</b>  Ni aun en tu pensamiento digas mal del rey, ni en los secretos de tu cámara digas mal del rico; porque las aves del cielo llevarán la voz, y las que tienen alas harán saber la palabra. </div>
<div id="Ecc_11_1" style="display:none;" class="ver_select"><b>Ecc 11:1</b>  Echa tu pan sobre las aguas; que después de muchos días lo hallarás. </div>
<div id="Ecc_11_2" style="display:none;" class="ver_select"><b>Ecc 11:2</b>  Reparte a siete, y aun a ocho; porque no sabes el mal que vendrá sobre la tierra. </div>
<div id="Ecc_11_3" style="display:none;" class="ver_select"><b>Ecc 11:3</b>  Si las nubes fueren llenas de agua, sobre la tierra la derramarán; y si el árbol cayere al sur, o al norte, en el lugar que el árbol cayere, allí quedará. </div>
<div id="Ecc_11_4" style="display:none;" class="ver_select"><b>Ecc 11:4</b>  El que al viento mira, no sembrará; y el que mira a las nubes, no segará. </div>
<div id="Ecc_11_5" style="display:none;" class="ver_select"><b>Ecc 11:5</b>  Como tú no sabes cuál es el camino del viento, o cómo crecen los huesos en el vientre de la mujer encinta, así ignoras la obra de Dios, el cual hace todas las cosas. </div>
<div id="Ecc_11_6" style="display:none;" class="ver_select"><b>Ecc 11:6</b>  Por la mañana siembra tu semilla, y a la tarde no dejes reposar tu mano; porque tú no sabes cuál es lo mejor, si esto o aquello, o si ambas cosas son igualmente buenas. </div>
<div id="Ecc_11_7" style="display:none;" class="ver_select"><b>Ecc 11:7</b>  Suave ciertamente es la luz, y agradable a los ojos ver el sol: </div>
<div id="Ecc_11_8" style="display:none;" class="ver_select"><b>Ecc 11:8</b>  Porque aunque un hombre viviere muchos años, y se alegrase en todos ellos; acuérdese sin embargo, que los días de las tinieblas serán muchos. Todo cuanto viene es vanidad. </div>
<div id="Ecc_11_9" style="display:none;" class="ver_select"><b>Ecc 11:9</b>  Alégrate, joven, en tu adolescencia, y tome placer tu corazón en los días de tu juventud; y anda en los caminos de tu corazón, y en la vista de tus ojos; mas sabe, que sobre todas estas cosas te traerá Dios a juicio. </div>
<div id="Ecc_11_10" style="display:none;" class="ver_select"><b>Ecc 11:10</b>  Quita, pues, de tu corazón el enojo, y aparta de tu carne el mal; porque la adolescencia y la juventud son vanidad. </div>
<div id="Ecc_12_1" style="display:none;" class="ver_select"><b>Ecc 12:1</b>  Acuérdate de tu Creador en los días de tu juventud, antes que vengan los días malos, y lleguen los años, de los cuales digas: No tengo en ellos contentamiento; </div>
<div id="Ecc_12_2" style="display:none;" class="ver_select"><b>Ecc 12:2</b>  antes que se oscurezca el sol, y la luz, y la luna y las estrellas, y las nubes se vuelvan tras la lluvia; </div>
<div id="Ecc_12_3" style="display:none;" class="ver_select"><b>Ecc 12:3</b>  cuando temblarán los guardas de la casa, y se encorvarán los hombres fuertes, y cesarán las muelas, porque han disminuido, y se oscurecerán los que miran por las ventanas; </div>
<div id="Ecc_12_4" style="display:none;" class="ver_select"><b>Ecc 12:4</b>  Y las puertas de afuera se cerrarán, por lo bajo del ruido de la muela; cuando se levantará al canto del ave, y todas las hijas del canto serán abatidas; </div>
<div id="Ecc_12_5" style="display:none;" class="ver_select"><b>Ecc 12:5</b>  cuando también temerán de la altura, y de los terrores en el camino; y florecerá el almendro, y la langosta será una carga, y se perderá el apetito; porque el hombre va a su morada eterna, y los que endechan andarán al derredor de las calles. </div>
<div id="Ecc_12_6" style="display:none;" class="ver_select"><b>Ecc 12:6</b>  Antes que la cadena de plata se quiebre, y se rompa el cuenco de oro, y el cántaro se quiebre junto a la fuente, y la rueda sea rota sobre el pozo; </div>
<div id="Ecc_12_7" style="display:none;" class="ver_select"><b>Ecc 12:7</b>  y el polvo vuelva a la tierra, como era, y el espíritu vuelva a Dios que lo dio. </div>
<div id="Ecc_12_8" style="display:none;" class="ver_select"><b>Ecc 12:8</b>  Vanidad de vanidades, dijo el Predicador, todo es vanidad. </div>
<div id="Ecc_12_9" style="display:none;" class="ver_select"><b>Ecc 12:9</b>  Y cuanto más sabio fue el Predicador, tanto más enseñó sabiduría al pueblo; e hizo escuchar, e hizo escudriñar, y compuso muchos proverbios. </div>
<div id="Ecc_12_10" style="display:none;" class="ver_select"><b>Ecc 12:10</b>  Procuró el Predicador hallar palabras agradables, y escritura recta, palabras de verdad. </div>
<div id="Ecc_12_11" style="display:none;" class="ver_select"><b>Ecc 12:11</b>  Las palabras de los sabios son como aguijones; y como clavos hincados, las de los maestros de las congregaciones, dadas por un Pastor. </div>
<div id="Ecc_12_12" style="display:none;" class="ver_select"><b>Ecc 12:12</b>  Ahora, hijo mío, a más de esto, sé avisado. No hay fin de hacer muchos libros; y el mucho estudio es fatiga de la carne. </div>
<div id="Ecc_12_13" style="display:none;" class="ver_select"><b>Ecc 12:13</b>  El fin de todo el discurso oído es éste: Teme a Dios, y guarda sus mandamientos; porque esto es el todo del hombre. </div>
<div id="Ecc_12_14" style="display:none;" class="ver_select"><b>Ecc 12:14</b>  Porque Dios traerá toda obra a juicio, juntamente con toda cosa encubierta, ya sea buena o sea mala. </div>
