<div id="Est_1_1" style="display:none;" class="ver_select"><b>Est 1:1</b>  Y aconteció en los días de Asuero (el Asuero que reinó desde la India hasta Etiopía sobre ciento veintisiete provincias); </div>
<div id="Est_1_2" style="display:none;" class="ver_select"><b>Est 1:2</b>  que en aquellos días, cuando el rey Asuero fue afirmado en el trono de su reino, el cual estaba en Susán capital del reino, </div>
<div id="Est_1_3" style="display:none;" class="ver_select"><b>Est 1:3</b>  en el tercer año de su reinado hizo banquete a todos sus príncipes y siervos, teniendo delante de él a los más poderosos de Persia y de Media, gobernadores y príncipes de provincias, </div>
<div id="Est_1_4" style="display:none;" class="ver_select"><b>Est 1:4</b>  para mostrar él las riquezas de la gloria de su reino, y el esplendor de su gloriosa majestad, por muchos días, ciento ochenta días. </div>
<div id="Est_1_5" style="display:none;" class="ver_select"><b>Est 1:5</b>  Y cumplidos estos días, el rey hizo un banquete por siete días en el patio del huerto del palacio real para todo el pueblo, desde el mayor hasta el menor que se hallaba en Susán capital del reino. </div>
<div id="Est_1_6" style="display:none;" class="ver_select"><b>Est 1:6</b>  El pabellón era de blanco, verde y azul, atado por cordones de lino y púrpura a anillos de plata y a columnas de mármol; los reclinatorios de oro y de plata, sobre losado de pórfido y de mármol, y de alabastro y de jacinto. </div>
<div id="Est_1_7" style="display:none;" class="ver_select"><b>Est 1:7</b>  Y daban a beber en vasos de oro, y vasos diferentes unos de otros, y mucho vino real, conforme a la generosidad del rey. </div>
<div id="Est_1_8" style="display:none;" class="ver_select"><b>Est 1:8</b>  Y la bebida era según la ley: Sin ninguna obligación; porque así lo había mandado el rey a todos los mayordomos de su casa; que se hiciese según la voluntad de cada uno. </div>
<div id="Est_1_9" style="display:none;" class="ver_select"><b>Est 1:9</b>  Asimismo la reina Vasti hizo banquete de mujeres, en la casa real del rey Asuero. </div>
<div id="Est_1_10" style="display:none;" class="ver_select"><b>Est 1:10</b>  El séptimo día, estando el corazón del rey alegre del vino, mandó a Mehumán, y a Bizta, y a Harbona, y a Bigta, y a Abagta, y a Zetar, y a Carcas, siete eunucos que servían delante del rey Asuero, </div>
<div id="Est_1_11" style="display:none;" class="ver_select"><b>Est 1:11</b>  que trajesen a la reina Vasti delante del rey con la corona regia, para mostrar a los pueblos y a los príncipes su belleza; porque ella era de hermosa apariencia. </div>
<div id="Est_1_12" style="display:none;" class="ver_select"><b>Est 1:12</b>  Mas la reina Vasti no quiso comparecer a la orden del rey, enviada por medio de los eunucos; y el rey se enojó mucho, y se encendió en él su ira. </div>
<div id="Est_1_13" style="display:none;" class="ver_select"><b>Est 1:13</b>  Preguntó entonces el rey a los sabios que conocían los tiempos (porque así era la costumbre del rey para con todos los que sabían la ley y el derecho; </div>
<div id="Est_1_14" style="display:none;" class="ver_select"><b>Est 1:14</b>  y estaban junto a él, Carsena, y Setar, y Admata, y Tarsis, y Meres, y Marsena, y Memucán, siete príncipes de Persia y de Media que veían la cara del rey, y se sentaban los primeros del reino); </div>
<div id="Est_1_15" style="display:none;" class="ver_select"><b>Est 1:15</b>  Según la ley, ¿qué se ha de hacer con la reina Vasti, por cuanto no ha cumplido la orden del rey Asuero, enviada por medio de los eunucos? </div>
<div id="Est_1_16" style="display:none;" class="ver_select"><b>Est 1:16</b>  Y dijo Memucán delante del rey y de los príncipes: No solamente contra el rey ha pecado la reina Vasti, sino contra todos los príncipes, y contra todos los pueblos que hay en todas las provincias del rey Asuero. </div>
<div id="Est_1_17" style="display:none;" class="ver_select"><b>Est 1:17</b>  Porque este hecho de la reina llegará a oídos de todas las mujeres, para hacerles tener en poca estima a sus maridos, diciendo: El rey Asuero mandó traer delante de sí a la reina Vasti, y ella no vino. </div>
<div id="Est_1_18" style="display:none;" class="ver_select"><b>Est 1:18</b>  Y entonces dirán esto las señoras de Persia y de Media que oyeren el hecho de la reina, a todos los príncipes del rey; y habrá mucho menosprecio y enojo. </div>
<div id="Est_1_19" style="display:none;" class="ver_select"><b>Est 1:19</b>  Si parece bien al rey, salga mandamiento real delante de él, y escríbase entre las leyes de Persia y de Media, y no sea traspasado: Que no venga más Vasti delante del rey Asuero: y dé el rey su reino a su compañera que sea mejor que ella. </div>
<div id="Est_1_20" style="display:none;" class="ver_select"><b>Est 1:20</b>  Y el mandamiento que hará el rey será oído en todo su reino, aunque es grande, y todas las esposas darán honra a sus maridos, desde el mayor hasta el menor. </div>
<div id="Est_1_21" style="display:none;" class="ver_select"><b>Est 1:21</b>  Y agradó esta palabra en ojos del rey y de los príncipes, e hizo el rey conforme al dicho de Memucán; </div>
<div id="Est_1_22" style="display:none;" class="ver_select"><b>Est 1:22</b>  pues envió cartas a todas las provincias del rey, a cada provincia conforme a su lenguaje, y a cada pueblo conforme a su lenguaje, diciendo que todo hombre fuese señor en su casa; y que se publicase esto según la lengua de cada pueblo. </div>
<div id="Est_2_1" style="display:none;" class="ver_select"><b>Est 2:1</b>  Pasadas estas cosas, sosegada ya la ira del rey Asuero, se acordó de Vasti, y de lo que hizo, y de lo que fue sentenciado contra ella. </div>
<div id="Est_2_2" style="display:none;" class="ver_select"><b>Est 2:2</b>  Entonces dijeron los siervos del rey, sus oficiales: Busquen para él jóvenes vírgenes de buen parecer; </div>
<div id="Est_2_3" style="display:none;" class="ver_select"><b>Est 2:3</b>  y ponga el rey personas en todas las provincias de su reino, que junte todas las jóvenes vírgenes de buen parecer en Susán residencia regia, en la casa de las mujeres, al cuidado de Hegai, eunuco del rey, guarda de las mujeres, y que les den sus atavíos para purificarse; </div>
<div id="Est_2_4" style="display:none;" class="ver_select"><b>Est 2:4</b>  y la joven que agradare a los ojos del rey, reine en lugar de Vasti. Y esto agradó a los ojos del rey, y lo hizo así. </div>
<div id="Est_2_5" style="display:none;" class="ver_select"><b>Est 2:5</b>  Había un varón judío en Susán residencia regia, cuyo nombre era Mardoqueo, hijo de Jair, hijo de Simi, hijo de Cis, benjamita; </div>
<div id="Est_2_6" style="display:none;" class="ver_select"><b>Est 2:6</b>  el cual había sido trasportado de Jerusalén con los cautivos que fueron llevados con Jeconías rey de Judá, a quien hizo trasportar Nabucodonosor rey de Babilonia. </div>
<div id="Est_2_7" style="display:none;" class="ver_select"><b>Est 2:7</b>  Y había criado a Hadasa, que es Esther, hija de su tío, porque no tenía padre ni madre; y la joven era de hermosa figura y de buen parecer; y como su padre y su madre murieron, Mardoqueo la había tomado por hija suya. </div>
<div id="Est_2_8" style="display:none;" class="ver_select"><b>Est 2:8</b>  Sucedió, pues, que como se divulgó el mandamiento del rey y su acuerdo, y siendo reunidas muchas jóvenes en Susán residencia regia, a cargo de Hegai, Esther también fue llevada para la casa del rey, al cuidado de Hegai, guarda de las mujeres. </div>
<div id="Est_2_9" style="display:none;" class="ver_select"><b>Est 2:9</b>  Y la joven agradó en sus ojos, y halló gracia delante de él; por lo que hizo que prestamente se le diesen sus atavíos para purificarse y sus raciones, y siete doncellas escogidas de la casa del rey; y la llevó con sus doncellas a lo mejor de la casa de las mujeres. </div>
<div id="Est_2_10" style="display:none;" class="ver_select"><b>Est 2:10</b>  Esther no declaró cuál era su pueblo ni su parentela; porque Mardoqueo le había mandado que no lo declarase. </div>
<div id="Est_2_11" style="display:none;" class="ver_select"><b>Est 2:11</b>  Y cada día Mardoqueo se paseaba delante del patio de la casa de las mujeres, por saber cómo le iba a Esther, y qué se hacía de ella. </div>
<div id="Est_2_12" style="display:none;" class="ver_select"><b>Est 2:12</b>  Y cuando llegaba el tiempo de cada una de las doncellas para venir al rey Asuero, después de haber estado ya doce meses conforme a la ley acerca de las mujeres (porque así se cumplía el tiempo de sus purificaciones, esto es, seis meses con óleo de mirra, y seis meses con perfumes aromáticos y afeites de mujeres), </div>
<div id="Est_2_13" style="display:none;" class="ver_select"><b>Est 2:13</b>  entonces la doncella venía así al rey. Todo lo que ella pedía se le daba, para venir con ello de la casa de las mujeres hasta la casa del rey. </div>
<div id="Est_2_14" style="display:none;" class="ver_select"><b>Est 2:14</b>  Ella venía por la tarde, y a la mañana se volvía a la casa segunda de las mujeres, al cargo de Saasgaz eunuco del rey, guarda de las concubinas; no venía más al rey, salvo si el rey la quería, y era llamada por nombre. </div>
<div id="Est_2_15" style="display:none;" class="ver_select"><b>Est 2:15</b>  Y llegado que fue el tiempo de Esther, hija de Abihail tío de Mardoqueo, que él se había tomado por hija, para venir al rey, ninguna cosa procuró sino lo que dijo Hegai eunuco del rey, guarda de las mujeres; y ganaba Esther el favor de todos los que la veían. </div>
<div id="Est_2_16" style="display:none;" class="ver_select"><b>Est 2:16</b>  Fue, pues, Esther llevada al rey Asuero a su casa real en el mes décimo, que es el mes de Tebet, en el año séptimo de su reinado. </div>
<div id="Est_2_17" style="display:none;" class="ver_select"><b>Est 2:17</b>  Y el rey amó a Esther sobre todas las mujeres, y halló gracia y benevolencia delante de él más que todas las vírgenes; y puso la corona real en su cabeza, y la hizo reina en lugar de Vasti. </div>
<div id="Est_2_18" style="display:none;" class="ver_select"><b>Est 2:18</b>  Hizo luego el rey gran banquete a todos sus príncipes y siervos, el banquete de Esther; y alivió de impuestos a las provincias, e hizo y dio mercedes conforme a la generosidad del rey. </div>
<div id="Est_2_19" style="display:none;" class="ver_select"><b>Est 2:19</b>  Y cuando fueron reunidas las vírgenes la segunda vez, Mardoqueo estaba sentado a la puerta del rey. </div>
<div id="Est_2_20" style="display:none;" class="ver_select"><b>Est 2:20</b>  Y Esther, según le tenía mandado Mardoqueo, aún no había declarado su nación ni su pueblo; porque Esther hacía lo que decía Mardoqueo, como cuando con él se educaba. </div>
<div id="Est_2_21" style="display:none;" class="ver_select"><b>Est 2:21</b>  En aquellos días, estando Mardoqueo sentado a la puerta del rey, se enojaron Bigtán y Teres, dos eunucos del rey, de la guardia de la puerta, y procuraban poner mano en el rey Asuero. </div>
<div id="Est_2_22" style="display:none;" class="ver_select"><b>Est 2:22</b>  Mas entendido que fue esto por Mardoqueo, él lo denunció a la reina Esther, y Esther lo dijo al rey en nombre de Mardoqueo. </div>
<div id="Est_2_23" style="display:none;" class="ver_select"><b>Est 2:23</b>  Se hizo entonces indagación del asunto, y fue hallado cierto; por lo que ambos fueron colgados en una horca. Y fue escrito en el libro de las crónicas, en presencia del rey. </div>
<div id="Est_3_1" style="display:none;" class="ver_select"><b>Est 3:1</b>  Después de estas cosas, el rey Asuero engrandeció a Amán hijo de Amadata agageo, y lo enalteció, y puso su silla sobre todos los príncipes que estaban con él. </div>
<div id="Est_3_2" style="display:none;" class="ver_select"><b>Est 3:2</b>  Y todos los siervos del rey que estaban a la puerta del rey, se arrodillaban e inclinaban a Amán, porque así lo había mandado el rey; pero Mardoqueo, ni se arrodillaba ni se humillaba. </div>
<div id="Est_3_3" style="display:none;" class="ver_select"><b>Est 3:3</b>  Y los siervos del rey que estaban a la puerta, dijeron a Mardoqueo: ¿Por qué traspasas el mandamiento del rey? </div>
<div id="Est_3_4" style="display:none;" class="ver_select"><b>Est 3:4</b>  Y aconteció que, hablándole cada día de esta manera, y no escuchándolos él, lo denunciaron a Amán, para ver si las palabras de Mardoqueo se mantendrían firmes; porque ya él les había declarado que era judío. </div>
<div id="Est_3_5" style="display:none;" class="ver_select"><b>Est 3:5</b>  Y vio Amán que Mardoqueo ni se arrodillaba ni se humillaba delante de él; y se llenó de ira. </div>
<div id="Est_3_6" style="display:none;" class="ver_select"><b>Est 3:6</b>  Pero tuvo en poco meter mano sólo en Mardoqueo; pues ya le habían declarado el pueblo de Mardoqueo; y procuró Amán destruir a todos los judíos que había en el reino de Asuero, al pueblo de Mardoqueo. </div>
<div id="Est_3_7" style="display:none;" class="ver_select"><b>Est 3:7</b>  En el mes primero, que es el mes de Nisán, en el año duodécimo del rey Asuero, fue echada Pur, esto es, la suerte, delante de Amán, de día en día y de mes en mes; y salió el mes duodécimo, que es el mes de Adar. </div>
<div id="Est_3_8" style="display:none;" class="ver_select"><b>Est 3:8</b>  Y dijo Amán al rey Asuero: Hay un pueblo esparcido y dividido entre los pueblos en todas las provincias de tu reino, y sus leyes son diferentes de las de todo pueblo, y no observan las leyes del rey; y al rey nada le beneficia el dejarlos vivir. </div>
<div id="Est_3_9" style="display:none;" class="ver_select"><b>Est 3:9</b>  Si place al rey, escríbase que sean destruidos; y yo pesaré diez mil talentos de plata en manos de los que manejan la hacienda, para que sean traídos a los tesoros del rey. </div>
<div id="Est_3_10" style="display:none;" class="ver_select"><b>Est 3:10</b>  Entonces el rey quitó su anillo de su mano, y lo dio a Amán hijo de Amadata agageo, enemigo de los judíos, </div>
<div id="Est_3_11" style="display:none;" class="ver_select"><b>Est 3:11</b>  y le dijo: La plata propuesta sea para ti, y asimismo el pueblo, para que hagas de él lo que bien te pareciere. </div>
<div id="Est_3_12" style="display:none;" class="ver_select"><b>Est 3:12</b>  Entonces fueron llamados los escribanos del rey en el mes primero, a trece del mismo, y fue escrito conforme a todo lo que mandó Amán, a los príncipes del rey, y a los capitanes que estaban sobre cada provincia, y a los príncipes de cada pueblo, a cada provincia según su lenguaje, y a cada pueblo según su lengua; en nombre del rey Asuero fue escrito, y sellado con el anillo del rey. </div>
<div id="Est_3_13" style="display:none;" class="ver_select"><b>Est 3:13</b>  Y fueron enviadas cartas por medio de los correos a todas las provincias del rey, para destruir, y matar, y exterminar a todos los judíos, jóvenes y ancianos, niños y mujeres, en un mismo día, en el día trece del mes duodécimo, que es el mes de Adar, y para apoderarse de su despojo. </div>
<div id="Est_3_14" style="display:none;" class="ver_select"><b>Est 3:14</b>  La copia del escrito que se diese por mandamiento en cada provincia, fue publicada a todos los pueblos, a fin de que estuviesen apercibidos para aquel día. </div>
<div id="Est_3_15" style="display:none;" class="ver_select"><b>Est 3:15</b>  Y salieron los correos de prisa por mandato del rey, y el edicto fue dado en Susán capital del reino. Y el rey y Amán se sentaron a beber, y la ciudad de Susán estaba conmovida. </div>
<div id="Est_4_1" style="display:none;" class="ver_select"><b>Est 4:1</b>  Luego que supo Mardoqueo todo lo que se había hecho, rasgó sus vestiduras, y se vistió de cilicio y de ceniza, y se fue por medio de la ciudad clamando con grande y amargo clamor. </div>
<div id="Est_4_2" style="display:none;" class="ver_select"><b>Est 4:2</b>  Y vino hasta delante de la puerta del rey; porque no era lícito pasar adentro de la puerta del rey vestido de cilicio. </div>
<div id="Est_4_3" style="display:none;" class="ver_select"><b>Est 4:3</b>  Y en cada provincia y lugar donde el mandamiento del rey y su decreto llegaba, tenían los judíos gran duelo, y ayuno, y lloro, y lamentación; cilicio y ceniza era la cama de muchos. </div>
<div id="Est_4_4" style="display:none;" class="ver_select"><b>Est 4:4</b>  Y vinieron las doncellas de Esther y sus eunucos, y se lo dijeron; y la reina tuvo gran dolor, y envió vestiduras para hacer vestir a Mardoqueo, y hacerle quitar el cilicio de sobre él; mas él no las recibió. </div>
<div id="Est_4_5" style="display:none;" class="ver_select"><b>Est 4:5</b>  Entonces Esther llamó a Atac, uno de los eunucos del rey, que él había hecho estar delante de ella, y lo mandó a Mardoqueo, con orden de saber qué era aquello, y por qué. </div>
<div id="Est_4_6" style="display:none;" class="ver_select"><b>Est 4:6</b>  Salió, pues, Atac a Mardoqueo, a la plaza de la ciudad que estaba delante de la puerta del rey. </div>
<div id="Est_4_7" style="display:none;" class="ver_select"><b>Est 4:7</b>  Y Mardoqueo le declaró todo lo que le había acontecido, y de la suma de la plata que Amán había prometido que pagaría a los tesoros del rey por la destrucción de los judíos. </div>
<div id="Est_4_8" style="display:none;" class="ver_select"><b>Est 4:8</b>  También le dio la copia de la escritura del decreto que había sido dado en Susán para que fuesen destruidos, a fin de que la mostrara a Esther y se lo declarase, y le encargara que fuese al rey a suplicarle, y a pedir delante de él por su pueblo. </div>
<div id="Est_4_9" style="display:none;" class="ver_select"><b>Est 4:9</b>  Y vino Atac, y contó a Esther las palabras de Mardoqueo. </div>
<div id="Est_4_10" style="display:none;" class="ver_select"><b>Est 4:10</b>  Entonces Esther dijo a Atac, y le mandó decir a Mardoqueo: </div>
<div id="Est_4_11" style="display:none;" class="ver_select"><b>Est 4:11</b>  Todos los siervos del rey, y el pueblo de las provincias del rey saben, que cualquier hombre o mujer que entra al rey al patio de adentro sin ser llamado, hay una sola ley para él: Debe morir; salvo aquel a quien el rey extendiere el cetro de oro, el cual vivirá; y yo no he sido llamada para entrar al rey estos treinta días. </div>
<div id="Est_4_12" style="display:none;" class="ver_select"><b>Est 4:12</b>  Y dijeron a Mardoqueo las palabras de Esther. </div>
<div id="Est_4_13" style="display:none;" class="ver_select"><b>Est 4:13</b>  Entonces dijo Mardoqueo que respondiesen a Esther: No pienses en tu alma, que escaparás en la casa del rey más que todos los judíos. </div>
<div id="Est_4_14" style="display:none;" class="ver_select"><b>Est 4:14</b>  Porque si callas absolutamente en este tiempo, respiro y liberación se levantará para los judíos de otro lugar; mas tú y la casa de tu padre pereceréis. ¿Y quién sabe si has llegado al reino, para un tiempo como éste? </div>
<div id="Est_4_15" style="display:none;" class="ver_select"><b>Est 4:15</b>  Y Esther dijo que respondiesen a Mardoqueo: </div>
<div id="Est_4_16" style="display:none;" class="ver_select"><b>Est 4:16</b>  Ve, y junta a todos los judíos que se hallan en Susán, y ayunad por mí, y no comáis ni bebáis en tres días, noche y día; yo también con mis doncellas ayunaré igualmente, y así entraré al rey, aunque no sea conforme a la ley; y si perezco, que perezca. </div>
<div id="Est_4_17" style="display:none;" class="ver_select"><b>Est 4:17</b>  Entonces se fue Mardoqueo, e hizo conforme a todo lo que le mandó Esther. </div>
<div id="Est_5_1" style="display:none;" class="ver_select"><b>Est 5:1</b>  Y aconteció que al tercer día se vistió Esther su vestido real, y se puso en el patio interior de la casa del rey, frente al aposento del rey; y el rey estaba sentado en su trono regio en el aposento real, frente a la puerta del aposento. </div>
<div id="Est_5_2" style="display:none;" class="ver_select"><b>Est 5:2</b>  Y fue que cuando el rey vio a la reina Esther que estaba en el patio, ella obtuvo gracia en sus ojos; y el rey extendió a Esther el cetro de oro que tenía en su mano. Entonces se acercó Esther y tocó la punta del cetro. </div>
<div id="Est_5_3" style="display:none;" class="ver_select"><b>Est 5:3</b>  Y dijo el rey: ¿Qué tienes, reina Esther, y cuál es tu petición? Hasta la mitad del reino se te dará. </div>
<div id="Est_5_4" style="display:none;" class="ver_select"><b>Est 5:4</b>  Y Esther dijo: Si al rey place, venga hoy el rey con Amán al banquete que le he hecho. </div>
<div id="Est_5_5" style="display:none;" class="ver_select"><b>Est 5:5</b>  Y respondió el rey: Daos prisa, llamad a Amán, para hacer lo que Esther ha dicho. Vino, pues, el rey con Amán al banquete que Esther dispuso. </div>
<div id="Est_5_6" style="display:none;" class="ver_select"><b>Est 5:6</b>  Y dijo el rey a Esther en el banquete del vino: ¿Cuál es tu petición, y te será otorgada? ¿Cuál es tu deseo? Aunque sea la mitad del reino, te será concedido. </div>
<div id="Est_5_7" style="display:none;" class="ver_select"><b>Est 5:7</b>  Entonces respondió Esther, y dijo: Mi petición y mi demanda es: </div>
<div id="Est_5_8" style="display:none;" class="ver_select"><b>Est 5:8</b>  Si he hallado gracia en los ojos del rey, y si place al rey otorgar mi petición y conceder lo que pido, que venga el rey con Amán al banquete que yo les prepararé; y mañana haré conforme a lo que el rey ha mandado. </div>
<div id="Est_5_9" style="display:none;" class="ver_select"><b>Est 5:9</b>  Y salió Amán aquel día contento y alegre de corazón; pero cuando vio a Mardoqueo a la puerta del rey, que no se levantaba ni se movía de su lugar, se llenó de ira contra Mardoqueo. </div>
<div id="Est_5_10" style="display:none;" class="ver_select"><b>Est 5:10</b>  Mas se refrenó Amán y vino a su casa, y mandó llamar a sus amigos y a Zeres su esposa. </div>
<div id="Est_5_11" style="display:none;" class="ver_select"><b>Est 5:11</b>  Y les refirió Amán la gloria de sus riquezas, y la multitud de sus hijos, y todas las cosas con que el rey le había engrandecido y con que le había enaltecido sobre los príncipes y siervos del rey. </div>
<div id="Est_5_12" style="display:none;" class="ver_select"><b>Est 5:12</b>  Y añadió Amán: También la reina Esther a ninguno hizo venir con el rey al banquete que ella preparó, sino a mí; y aun para mañana estoy convidado por ella con el rey. </div>
<div id="Est_5_13" style="display:none;" class="ver_select"><b>Est 5:13</b>  Mas todo esto de nada me sirve cada vez que veo al judío Mardoqueo sentado a la puerta del rey. </div>
<div id="Est_5_14" style="display:none;" class="ver_select"><b>Est 5:14</b>  Y le dijo Zeres su esposa, y todos sus amigos: Hagan una horca alta de cincuenta codos, y mañana di al rey que cuelguen a Mardoqueo en ella; y entra alegre con el rey al banquete. Y el consejo agradó a Amán, e hizo preparar la horca. </div>
<div id="Est_6_1" style="display:none;" class="ver_select"><b>Est 6:1</b>  Aquella noche se le fue el sueño al rey, y dijo que le trajesen el libro de las memorias y las crónicas; y las leyeron delante del rey. </div>
<div id="Est_6_2" style="display:none;" class="ver_select"><b>Est 6:2</b>  Y se halló escrito que Mardoqueo había denunciado el complot de Bigtán y Teres, dos eunucos del rey, de la guardia de la puerta, que habían procurado poner mano en el rey Asuero. </div>
<div id="Est_6_3" style="display:none;" class="ver_select"><b>Est 6:3</b>  Y dijo el rey: ¿Qué honra o qué distinción se hizo a Mardoqueo por esto? Y los siervos que ministraban al rey, respondieron: Nada se ha hecho por él. </div>
<div id="Est_6_4" style="display:none;" class="ver_select"><b>Est 6:4</b>  Entonces dijo el rey: ¿Quién está en el patio? Y Amán había venido al patio de afuera de la casa del rey, para decir al rey que hiciese colgar a Mardoqueo en la horca que él le tenía preparada. </div>
<div id="Est_6_5" style="display:none;" class="ver_select"><b>Est 6:5</b>  Y los servidores del rey le respondieron: He aquí Amán está en el patio. Y el rey dijo: Que entre. </div>
<div id="Est_6_6" style="display:none;" class="ver_select"><b>Est 6:6</b>  Entró, pues, Amán, y el rey le dijo: ¿Qué se hará al hombre cuya honra desea el rey? Y dijo Amán en su corazón: ¿A quién deseará el rey hacer honra más que a mí? </div>
<div id="Est_6_7" style="display:none;" class="ver_select"><b>Est 6:7</b>  Y respondió Amán al rey: Para el varón cuya honra desea el rey, </div>
<div id="Est_6_8" style="display:none;" class="ver_select"><b>Est 6:8</b>  traigan la vestidura real de que el rey se viste, y el caballo en que el rey cabalga, y la corona real que está puesta en su cabeza; </div>
<div id="Est_6_9" style="display:none;" class="ver_select"><b>Est 6:9</b>  y den la vestidura y el caballo en mano de alguno de los príncipes más nobles del rey, y vistan a aquel varón cuya honra desea el rey, y llévenlo en el caballo por la plaza de la ciudad, y pregonen delante de él: Así se hará al varón cuya honra desea el rey. </div>
<div id="Est_6_10" style="display:none;" class="ver_select"><b>Est 6:10</b>  Entonces el rey dijo a Amán: Date prisa, toma la vestidura y el caballo, como tú has dicho, y hazlo así con el judío Mardoqueo, que se sienta a la puerta del rey; no omitas nada de todo lo que has dicho. </div>
<div id="Est_6_11" style="display:none;" class="ver_select"><b>Est 6:11</b>  Y Amán tomó la vestidura y el caballo, y vistió a Mardoqueo, y lo llevó a caballo por la plaza de la ciudad, e hizo pregonar delante de él: Así se hará al varón cuya honra desea el rey. </div>
<div id="Est_6_12" style="display:none;" class="ver_select"><b>Est 6:12</b>  Después de esto Mardoqueo se volvió a la puerta del rey, y Amán se fue corriendo a su casa, apesadumbrado y cubierta su cabeza. </div>
<div id="Est_6_13" style="display:none;" class="ver_select"><b>Est 6:13</b>  Contó luego Amán a Zeres su esposa, y a todos sus amigos, todo lo que le había acontecido; y le dijeron sus sabios, y Zeres su esposa: Si Mardoqueo, delante de quien has comenzado a caer, es de la simiente de los judíos, no lo vencerás; antes caerás por cierto delante de él. </div>
<div id="Est_6_14" style="display:none;" class="ver_select"><b>Est 6:14</b>  Aún estaban ellos hablando con él, cuando los eunucos del rey llegaron apresurados, para hacer venir a Amán al banquete que Esther había dispuesto. </div>
<div id="Est_7_1" style="display:none;" class="ver_select"><b>Est 7:1</b>  Vino, pues, el rey con Amán al banquete con la reina Esther. </div>
<div id="Est_7_2" style="display:none;" class="ver_select"><b>Est 7:2</b>  Y también el segundo día dijo el rey a Esther en el convite del vino: ¿Cuál es tu petición, reina Esther, y se te concederá? ¿Cuál es tu demanda? Aunque sea la mitad del reino, y te será hecho. </div>
<div id="Est_7_3" style="display:none;" class="ver_select"><b>Est 7:3</b>  Entonces la reina Esther respondió y dijo: Oh rey, si he hallado gracia en tus ojos, y si place al rey, me sea dada mi vida por mi petición, y mi pueblo por mi demanda. </div>
<div id="Est_7_4" style="display:none;" class="ver_select"><b>Est 7:4</b>  Porque vendidos estamos yo y mi pueblo para ser destruidos, para ser muertos y exterminados. Y si para ser siervos y siervas fuéramos vendidos, yo callaría, aunque el enemigo no compensaría el daño del rey. </div>
<div id="Est_7_5" style="display:none;" class="ver_select"><b>Est 7:5</b>  Y respondió el rey Asuero, y dijo a la reina Esther: ¿Quién es, y dónde está, aquél que ha concebido en su corazón hacer tal cosa? </div>
<div id="Est_7_6" style="display:none;" class="ver_select"><b>Est 7:6</b>  Y Esther dijo: El enemigo y adversario es este malvado Amán. Entonces se turbó Amán delante del rey y de la reina. </div>
<div id="Est_7_7" style="display:none;" class="ver_select"><b>Est 7:7</b>  Y se levantó el rey del banquete del vino, y enfurecido se fue al huerto del palacio; y se quedó Amán para rogar a la reina Esther por su vida; porque vio que estaba resuelto para él el mal de parte del rey. </div>
<div id="Est_7_8" style="display:none;" class="ver_select"><b>Est 7:8</b>  Volvió después el rey del huerto del palacio al aposento del banquete del vino, y Amán había caído sobre el lecho en que estaba Esther. Entonces dijo el rey: ¿Querrá también forzar a la reina estando yo en casa? Y al salir esta palabra de la boca del rey, cubrieron el rostro a Amán. </div>
<div id="Est_7_9" style="display:none;" class="ver_select"><b>Est 7:9</b>  Y dijo Harbona, uno de los eunucos de delante del rey: He aquí también la horca de cincuenta codos de altura que hizo Amán para Mardoqueo, el cual había hablado bien por el rey, está en casa de Amán. Entonces el rey dijo: Colgadlo en ella. </div>
<div id="Est_7_10" style="display:none;" class="ver_select"><b>Est 7:10</b>  Así colgaron a Amán en la horca que él había preparado para Mardoqueo; y se apaciguó la ira del rey. </div>
<div id="Est_8_1" style="display:none;" class="ver_select"><b>Est 8:1</b>  Ese mismo día el rey Asuero dio a la reina Esther la casa de Amán enemigo de los judíos; y Mardoqueo vino delante del rey, porque Esther le declaró lo que él era respecto de ella. </div>
<div id="Est_8_2" style="display:none;" class="ver_select"><b>Est 8:2</b>  Y se quitó el rey su anillo que había vuelto a tomar de Amán, y lo dio a Mardoqueo. Y Esther puso a Mardoqueo sobre la casa de Amán. </div>
<div id="Est_8_3" style="display:none;" class="ver_select"><b>Est 8:3</b>  Volvió luego Esther a hablar delante del rey, y se echó a sus pies, llorando y rogándole que hiciese nula la maldad de Amán agageo, y su designio que había formado contra los judíos. </div>
<div id="Est_8_4" style="display:none;" class="ver_select"><b>Est 8:4</b>  Entonces el rey extendió a Esther el cetro de oro, y Esther se levantó, y se puso en pie delante del rey. </div>
<div id="Est_8_5" style="display:none;" class="ver_select"><b>Est 8:5</b>  Y dijo: Si place al rey, y si he hallado gracia delante de él, y si la cosa es recta delante del rey, y agradable yo en sus ojos, sea escrito para revocar las cartas del designio de Amán hijo de Amadata agageo, que escribió para destruir a los judíos que están en todas las provincias del rey. </div>
<div id="Est_8_6" style="display:none;" class="ver_select"><b>Est 8:6</b>  Porque ¿cómo podré yo ver el mal que vendrá sobre mi pueblo? ¿Y cómo podré yo ver la destrucción de mi gente? </div>
<div id="Est_8_7" style="display:none;" class="ver_select"><b>Est 8:7</b>  Y respondió el rey Asuero a la reina Esther, y a Mardoqueo el judío: He aquí yo he dado a Esther la casa de Amán, y a él han colgado en la horca, por cuanto extendió su mano contra los judíos. </div>
<div id="Est_8_8" style="display:none;" class="ver_select"><b>Est 8:8</b>  Escribid, pues, vosotros a los judíos como bien os pareciere en el nombre del rey, y selladlo con el anillo del rey; porque el escrito que se escribe en el nombre del rey y se sella con el anillo del rey, no puede ser revocado. </div>
<div id="Est_8_9" style="display:none;" class="ver_select"><b>Est 8:9</b>  Entonces fueron llamados los escribanos del rey en el mes tercero, que es Siván, a veintitrés del mismo; y se escribió conforme a todo lo que mandó Mardoqueo, a los judíos, a los sátrapas, a los capitanes y a los príncipes de las provincias que había desde la India hasta Etiopía, ciento veintisiete provincias; a cada provincia según su escritura, y a cada pueblo conforme a su lengua, a los judíos también conforme a su escritura y lengua. </div>
<div id="Est_8_10" style="display:none;" class="ver_select"><b>Est 8:10</b>  Y escribió en nombre del rey Asuero, y lo selló con el anillo del rey, y envió cartas por correos montados en caballos, en mulos, en camellos y en dromedarios. </div>
<div id="Est_8_11" style="display:none;" class="ver_select"><b>Est 8:11</b>  Y en ellas el rey daba facultad a los judíos que estaban en todas la ciudades, para que se juntasen y estuviesen a la defensa de su vida, prestos a destruir, y matar, y acabar con todo ejército de pueblo o provincia que viniese contra ellos, y aun niños y mujeres, y que tomaran de ellos el despojo, </div>
<div id="Est_8_12" style="display:none;" class="ver_select"><b>Est 8:12</b>  en un mismo día en todas las provincias del rey Asuero, en el día trece del mes duodécimo, que es el mes de Adar. </div>
<div id="Est_8_13" style="display:none;" class="ver_select"><b>Est 8:13</b>  La copia de la escritura que había de darse por ordenanza en cada provincia, para que fuese manifiesta a todos los pueblos, decía que los judíos estuviesen apercibidos para aquel día, para vengarse de sus enemigos. </div>
<div id="Est_8_14" style="display:none;" class="ver_select"><b>Est 8:14</b>  Los correos, pues, cabalgando en mulos y camellos, salieron a toda prisa impulsados por el mandato del rey; y el decreto fue dado en Susán capital del reino. </div>
<div id="Est_8_15" style="display:none;" class="ver_select"><b>Est 8:15</b>  Y Mardoqueo salió de delante del rey con una vestidura real de azul y blanco, y una gran corona de oro y un manto de lino fino y púrpura; y la ciudad de Susán se alegró y regocijó. </div>
<div id="Est_8_16" style="display:none;" class="ver_select"><b>Est 8:16</b>  Los judíos tuvieron luz y alegría, y gozo y honra. </div>
<div id="Est_8_17" style="display:none;" class="ver_select"><b>Est 8:17</b>  Y en cada provincia y en cada ciudad donde llegó el mandamiento del rey, los judíos tuvieron alegría y gozo, banquete y día de placer. Y muchos de los pueblos de la tierra se hacían judíos, porque el temor de los judíos había caído sobre ellos. </div>
<div id="Est_9_1" style="display:none;" class="ver_select"><b>Est 9:1</b>  Y en el mes duodécimo que es el mes de Adar, al día trece del mismo, en el que tocaba se ejecutase el mandamiento del rey y su ley, el mismo día en que esperaban los enemigos de los judíos enseñorearse de ellos, fue lo contrario; porque los judíos se enseñorearon de sus enemigos. </div>
<div id="Est_9_2" style="display:none;" class="ver_select"><b>Est 9:2</b>  Los judíos se juntaron en sus ciudades en todas las provincias del rey Asuero, para echar mano sobre los que habían procurado su mal; y nadie pudo contra ellos, porque el temor de ellos había caído sobre todos los pueblos. </div>
<div id="Est_9_3" style="display:none;" class="ver_select"><b>Est 9:3</b>  Y todos los príncipes de las provincias, los sátrapas, capitanes, y oficiales del rey ayudaban a los judíos; porque el temor de Mardoqueo había caído sobre ellos. </div>
<div id="Est_9_4" style="display:none;" class="ver_select"><b>Est 9:4</b>  Pues Mardoqueo era grande en la casa del rey, y su fama iba por todas las provincias; y el varón Mardoqueo iba engrandeciéndose más y más. </div>
<div id="Est_9_5" style="display:none;" class="ver_select"><b>Est 9:5</b>  E hirieron los judíos a todos sus enemigos a golpe de espada, de mortandad, de destrucción; e hicieron con los que los aborrecían lo que quisieron. </div>
<div id="Est_9_6" style="display:none;" class="ver_select"><b>Est 9:6</b>  Y en Susán capital del reino, los judíos mataron y destruyeron a quinientos hombres. </div>
<div id="Est_9_7" style="display:none;" class="ver_select"><b>Est 9:7</b>  Mataron entonces a Parsandata, a Dalfón, a Aspata, </div>
<div id="Est_9_8" style="display:none;" class="ver_select"><b>Est 9:8</b>  a Porata, a Ahalía, a Aridata, </div>
<div id="Est_9_9" style="display:none;" class="ver_select"><b>Est 9:9</b>  a Parmasta, a Arisai, a Aridai, y a Vaizata, </div>
<div id="Est_9_10" style="display:none;" class="ver_select"><b>Est 9:10</b>  diez hijos de Amán hijo de Amadata, enemigo de los judíos: mas en el despojo no metieron su mano. </div>
<div id="Est_9_11" style="display:none;" class="ver_select"><b>Est 9:11</b>  El mismo día vino la cuenta de los muertos en Susán residencia regia, delante del rey. </div>
<div id="Est_9_12" style="display:none;" class="ver_select"><b>Est 9:12</b>  Y dijo el rey a la reina Esther: En Susán, capital del reino, los judíos han matado y destruido a quinientos hombres, y a diez hijos de Amán; ¿qué habrán hecho en las otras provincias del rey? ¿Cuál, pues, es tu petición? Y te será concedida; ¿o qué más es tu demanda? y será hecho. </div>
<div id="Est_9_13" style="display:none;" class="ver_select"><b>Est 9:13</b>  Y respondió Esther: Si place al rey, concédase también mañana a los judíos en Susán, que hagan conforme al decreto de hoy; y que cuelguen en la horca a los diez hijos de Amán. </div>
<div id="Est_9_14" style="display:none;" class="ver_select"><b>Est 9:14</b>  Y mandó el rey que se hiciese así; y se dio la orden en Susán, y colgaron a los diez hijos de Amán. </div>
<div id="Est_9_15" style="display:none;" class="ver_select"><b>Est 9:15</b>  Y los judíos que estaban en Susán, se juntaron también el catorce del mes de Adar, y mataron en Susán a trescientos hombres; mas en el despojo no metieron su mano. </div>
<div id="Est_9_16" style="display:none;" class="ver_select"><b>Est 9:16</b>  En cuanto a los otros judíos que estaban en las provincias del rey, también se juntaron y se pusieron en defensa de su vida, y tuvieron reposo de sus enemigos, y mataron de sus contrarios a setenta y cinco mil; mas en el despojo no metieron su mano. </div>
<div id="Est_9_17" style="display:none;" class="ver_select"><b>Est 9:17</b>  Esto fue en el día trece del mes de Adar; y reposaron en el día catorce del mismo, y lo hicieron día de banquete y de alegría. </div>
<div id="Est_9_18" style="display:none;" class="ver_select"><b>Est 9:18</b>  Mas los judíos que estaban en Susán se juntaron en el día trece y en el catorce del mismo mes; y al día quince del mismo reposaron, y lo hicieron día de banquete y de regocijo. </div>
<div id="Est_9_19" style="display:none;" class="ver_select"><b>Est 9:19</b>  Por tanto los judíos aldeanos que habitan en las villas sin muro celebran a los catorce del mes de Adar el día de alegría y de banquete, un día de regocijo, y de enviar porciones cada uno a su vecino. </div>
<div id="Est_9_20" style="display:none;" class="ver_select"><b>Est 9:20</b>  Y escribió Mardoqueo estas cosas, y envió cartas a todos los judíos que estaban en todas las provincias del rey Asuero, cercanos y distantes, </div>
<div id="Est_9_21" style="display:none;" class="ver_select"><b>Est 9:21</b>  ordenándoles que celebrasen el día decimocuarto del mes de Adar, y el decimoquinto del mismo, cada año, </div>
<div id="Est_9_22" style="display:none;" class="ver_select"><b>Est 9:22</b>  como días en que los judíos tuvieron reposo de sus enemigos, y el mes que de tristeza se les volvió en alegría, y de luto en día bueno; que los hiciesen días de banquete y de gozo, y de enviar porciones cada uno a su vecino, y dádivas a los pobres. </div>
<div id="Est_9_23" style="display:none;" class="ver_select"><b>Est 9:23</b>  Y los judíos aceptaron hacer, según habían comenzado, lo que les escribió Mardoqueo. </div>
<div id="Est_9_24" style="display:none;" class="ver_select"><b>Est 9:24</b>  Porque Amán hijo de Amadata, agageo, enemigo de todos los judíos, había ideado contra los judíos para destruirlos, y echó Pur, que quiere decir suerte, para consumirlos y acabar con ellos. </div>
<div id="Est_9_25" style="display:none;" class="ver_select"><b>Est 9:25</b>  Mas cuando Esther vino a la presencia del rey, él ordenó por carta que el perverso designio que aquél trazó contra los judíos recayera sobre su cabeza; y que colgaran a él y a sus hijos en la horca. </div>
<div id="Est_9_26" style="display:none;" class="ver_select"><b>Est 9:26</b>  Por esto llamaron a estos días Purim, del nombre Pur. Por todas las palabras de esta carta, y por lo que ellos vieron sobre esto, y lo que les había acontecido. </div>
<div id="Est_9_27" style="display:none;" class="ver_select"><b>Est 9:27</b>  Establecieron y tomaron los judíos sobre sí, y sobre su simiente, y sobre todos los allegados a ellos, y no será traspasado, el celebrar estos dos días según está escrito tocante a ellos, conforme a su tiempo cada año; </div>
<div id="Est_9_28" style="display:none;" class="ver_select"><b>Est 9:28</b>  y que estos dos días serían recordados y celebrados por todas las generaciones, familias, provincias y ciudades; y que estos días de Purim no dejarían de celebrarse entre los judíos, ni su memoria cesaría entre su simiente. </div>
<div id="Est_9_29" style="display:none;" class="ver_select"><b>Est 9:29</b>  Y la reina Esther hija de Abihail, y Mardoqueo el judío, escribieron con toda autoridad, para confirmar esta segunda carta de Purim. </div>
<div id="Est_9_30" style="display:none;" class="ver_select"><b>Est 9:30</b>  Y envió Mardoqueo cartas a todos los judíos, a las ciento veintisiete provincias del rey Asuero, con palabras de paz y de verdad, </div>
<div id="Est_9_31" style="display:none;" class="ver_select"><b>Est 9:31</b>  para confirmar estos días de Purim en sus tiempos señalados, según les había constituido Mardoqueo el judío y la reina Esther, según ellos habían tomado sobre sí y sobre su simiente, para conmemorar el fin de los ayunos y de su clamor. </div>
<div id="Est_9_32" style="display:none;" class="ver_select"><b>Est 9:32</b>  Y el mandato de Esther confirmó estas palabras dadas acerca de Purim, y fue escrito en el libro. </div>
<div id="Est_10_1" style="display:none;" class="ver_select"><b>Est 10:1</b>  Y el rey Asuero impuso tributo sobre la tierra y las costas del mar. </div>
<div id="Est_10_2" style="display:none;" class="ver_select"><b>Est 10:2</b>  Y todos los hechos de su poder y autoridad, y la declaración de la grandeza de Mardoqueo, con que el rey le engrandeció, ¿no está escrito en el libro de las crónicas de los reyes de Media y de Persia? </div>
<div id="Est_10_3" style="display:none;" class="ver_select"><b>Est 10:3</b>  Porque Mardoqueo el judío fue segundo después del rey Asuero, y grande entre los judíos, y estimado por la multitud de sus hermanos, procurando el bien de su pueblo, y hablando paz para toda su simiente. </div>
