<div id="Ezr_1_1" style="display:none;" class="ver_select"><b>Ezr 1:1</b>  En el primer año de Ciro rey de Persia, para que se cumpliese la palabra de Jehová por boca de Jeremías, Jehová despertó el espíritu de Ciro rey de Persia, el cual hizo pregonar por todo su reino, y lo puso también por escrito, diciendo: </div>
<div id="Ezr_1_2" style="display:none;" class="ver_select"><b>Ezr 1:2</b>  Así ha dicho Ciro rey de Persia: Jehová Dios de los cielos me ha dado todos los reinos de la tierra, y me ha mandado que le edifique casa en Jerusalén, que está en Judá. </div>
<div id="Ezr_1_3" style="display:none;" class="ver_select"><b>Ezr 1:3</b>  ¿Quién hay entre vosotros de todo su pueblo? Sea Dios con él, y suba a Jerusalén que está en Judá, y edifique la casa a Jehová Dios de Israel (Él es el Dios), la cual está en Jerusalén. </div>
<div id="Ezr_1_4" style="display:none;" class="ver_select"><b>Ezr 1:4</b>  Y a cualquiera que hubiere quedado de todos los lugares donde peregrinare, los hombres de su lugar ayúdenle con plata y oro, bienes y ganado; además de ofrendas voluntarias para la casa de Dios, la cuál está en Jerusalén. </div>
<div id="Ezr_1_5" style="display:none;" class="ver_select"><b>Ezr 1:5</b>  Entonces se levantaron los jefes de las familias de Judá y de Benjamín, y los sacerdotes y levitas, todos aquellos cuyo espíritu despertó Dios para subir a edificar la casa de Jehová, la cual está en Jerusalén. </div>
<div id="Ezr_1_6" style="display:none;" class="ver_select"><b>Ezr 1:6</b>  Y todos los que estaban en sus alrededores corroboraron las manos de ellos con vasos de plata y de oro, con bienes y ganado, y con cosas preciosas, además de todo lo que se ofreció voluntariamente. </div>
<div id="Ezr_1_7" style="display:none;" class="ver_select"><b>Ezr 1:7</b>  Y el rey Ciro sacó los vasos de la casa de Jehová, que Nabucodonosor se había llevado de Jerusalén y había puesto en la casa de sus dioses. </div>
<div id="Ezr_1_8" style="display:none;" class="ver_select"><b>Ezr 1:8</b>  Los sacó, pues, Ciro rey de Persia, por mano de Mitrídates el tesorero, el cual los dio por cuenta a Sesbasar príncipe de Judá. </div>
<div id="Ezr_1_9" style="display:none;" class="ver_select"><b>Ezr 1:9</b>  Y ésta es la cuenta de ellos: treinta tazones de oro, mil tazones de plata, veintinueve cuchillos, </div>
<div id="Ezr_1_10" style="display:none;" class="ver_select"><b>Ezr 1:10</b>  treinta tazas de oro, otras cuatrocientas diez tazas de plata, y otros mil vasos. </div>
<div id="Ezr_1_11" style="display:none;" class="ver_select"><b>Ezr 1:11</b>  Todos los vasos de oro y de plata fueron cinco mil cuatrocientos. Todos los hizo llevar Sesbasar con los que subieron del cautiverio de Babilonia a Jerusalén. </div>
<div id="Ezr_2_1" style="display:none;" class="ver_select"><b>Ezr 2:1</b>  Y éstos son los hijos de la provincia que subieron de la cautividad, de los desterrados que Nabucodonosor, rey de Babilonia, había llevado cautivos a Babilonia, y que volvieron a Jerusalén y a Judá, cada uno a su ciudad; </div>
<div id="Ezr_2_2" style="display:none;" class="ver_select"><b>Ezr 2:2</b>  los cuales vinieron con Zorobabel, Jesúa, Nehemías, Seraías, Reelaías, Mardoqueo, Bilsán, Mispar, Bigvai, Rehum y Baana. La cuenta de los varones del pueblo de Israel: </div>
<div id="Ezr_2_3" style="display:none;" class="ver_select"><b>Ezr 2:3</b>  Los hijos de Paros, dos mil ciento setenta y dos. </div>
<div id="Ezr_2_4" style="display:none;" class="ver_select"><b>Ezr 2:4</b>  Los hijos de Sefatías, trescientos setenta y dos. </div>
<div id="Ezr_2_5" style="display:none;" class="ver_select"><b>Ezr 2:5</b>  Los hijos de Ara, setecientos setenta y cinco. </div>
<div id="Ezr_2_6" style="display:none;" class="ver_select"><b>Ezr 2:6</b>  Los hijos de Pahat-moab, de los hijos de Jesúa y de Joab, dos mil ochocientos doce. </div>
<div id="Ezr_2_7" style="display:none;" class="ver_select"><b>Ezr 2:7</b>  Los hijos de Elam, mil doscientos cincuenta y cuatro. </div>
<div id="Ezr_2_8" style="display:none;" class="ver_select"><b>Ezr 2:8</b>  Los hijos de Zatu, novecientos cuarenta y cinco. </div>
<div id="Ezr_2_9" style="display:none;" class="ver_select"><b>Ezr 2:9</b>  Los hijos de Zacai, setecientos sesenta. </div>
<div id="Ezr_2_10" style="display:none;" class="ver_select"><b>Ezr 2:10</b>  Los hijos de Bani, seiscientos cuarenta y dos. </div>
<div id="Ezr_2_11" style="display:none;" class="ver_select"><b>Ezr 2:11</b>  Los hijos de Bebai, seiscientos veintitrés. </div>
<div id="Ezr_2_12" style="display:none;" class="ver_select"><b>Ezr 2:12</b>  Los hijos de Azgad, mil doscientos veintidós. </div>
<div id="Ezr_2_13" style="display:none;" class="ver_select"><b>Ezr 2:13</b>  Los hijos de Adonicam, seiscientos sesenta y seis. </div>
<div id="Ezr_2_14" style="display:none;" class="ver_select"><b>Ezr 2:14</b>  Los hijos de Bigvai, dos mil cincuenta y seis. </div>
<div id="Ezr_2_15" style="display:none;" class="ver_select"><b>Ezr 2:15</b>  Los hijos de Adín, cuatrocientos cincuenta y cuatro. </div>
<div id="Ezr_2_16" style="display:none;" class="ver_select"><b>Ezr 2:16</b>  Los hijos de Ater, de Ezequías, noventa y ocho. </div>
<div id="Ezr_2_17" style="display:none;" class="ver_select"><b>Ezr 2:17</b>  Los hijos de Besai, trescientos veintitrés. </div>
<div id="Ezr_2_18" style="display:none;" class="ver_select"><b>Ezr 2:18</b>  Los hijos de Jora, ciento doce. </div>
<div id="Ezr_2_19" style="display:none;" class="ver_select"><b>Ezr 2:19</b>  Los hijos de Hasum, doscientos veintitrés. </div>
<div id="Ezr_2_20" style="display:none;" class="ver_select"><b>Ezr 2:20</b>  Los hijos de Gibar, noventa y cinco. </div>
<div id="Ezr_2_21" style="display:none;" class="ver_select"><b>Ezr 2:21</b>  Los hijos de Belén, ciento veintitrés; </div>
<div id="Ezr_2_22" style="display:none;" class="ver_select"><b>Ezr 2:22</b>  Los varones de Netofa, cincuenta y seis. </div>
<div id="Ezr_2_23" style="display:none;" class="ver_select"><b>Ezr 2:23</b>  Los varones de Anatot, ciento veintiocho. </div>
<div id="Ezr_2_24" style="display:none;" class="ver_select"><b>Ezr 2:24</b>  Los hijos de Azmavet, cuarenta y dos. </div>
<div id="Ezr_2_25" style="display:none;" class="ver_select"><b>Ezr 2:25</b>  Los hijos de Quiriat-jearim, Cefira, y Beerot, setecientos cuarenta y tres. </div>
<div id="Ezr_2_26" style="display:none;" class="ver_select"><b>Ezr 2:26</b>  Los hijos de Ramá y Geba, seiscientos veintiuno. </div>
<div id="Ezr_2_27" style="display:none;" class="ver_select"><b>Ezr 2:27</b>  Los varones de Micmas, ciento veintidós. </div>
<div id="Ezr_2_28" style="display:none;" class="ver_select"><b>Ezr 2:28</b>  Los varones de Betel y Hai, doscientos veintitrés. </div>
<div id="Ezr_2_29" style="display:none;" class="ver_select"><b>Ezr 2:29</b>  Los hijos de Nebo, cincuenta y dos. </div>
<div id="Ezr_2_30" style="display:none;" class="ver_select"><b>Ezr 2:30</b>  Los hijos de Magbis, ciento cincuenta y seis. </div>
<div id="Ezr_2_31" style="display:none;" class="ver_select"><b>Ezr 2:31</b>  Los hijos del otro Elam, mil doscientos cincuenta y cuatro. </div>
<div id="Ezr_2_32" style="display:none;" class="ver_select"><b>Ezr 2:32</b>  Los hijos de Harim, trescientos veinte. </div>
<div id="Ezr_2_33" style="display:none;" class="ver_select"><b>Ezr 2:33</b>  Los hijos de Lod, Hadid, y Ono, setecientos veinticinco. </div>
<div id="Ezr_2_34" style="display:none;" class="ver_select"><b>Ezr 2:34</b>  Los hijos de Jericó, trescientos cuarenta y cinco. </div>
<div id="Ezr_2_35" style="display:none;" class="ver_select"><b>Ezr 2:35</b>  Los hijos de Senaa, tres mil seiscientos treinta. </div>
<div id="Ezr_2_36" style="display:none;" class="ver_select"><b>Ezr 2:36</b>  Los sacerdotes; los hijos de Jedaías, de la casa de Jesúa, novecientos setenta y tres. </div>
<div id="Ezr_2_37" style="display:none;" class="ver_select"><b>Ezr 2:37</b>  Los hijos de Imer, mil cincuenta y dos. </div>
<div id="Ezr_2_38" style="display:none;" class="ver_select"><b>Ezr 2:38</b>  Los hijos de Pasur, mil doscientos cuarenta y siete. </div>
<div id="Ezr_2_39" style="display:none;" class="ver_select"><b>Ezr 2:39</b>  Los hijos de Harim, mil diecisiete. </div>
<div id="Ezr_2_40" style="display:none;" class="ver_select"><b>Ezr 2:40</b>  Los levitas: los hijos de Jesúa y de Cadmiel, de los hijos de Odavías, setenta y cuatro. </div>
<div id="Ezr_2_41" style="display:none;" class="ver_select"><b>Ezr 2:41</b>  Los cantores; los hijos de Asaf, ciento veintiocho. </div>
<div id="Ezr_2_42" style="display:none;" class="ver_select"><b>Ezr 2:42</b>  Los hijos de los porteros: los hijos de Salum, los hijos de Ater, los hijos de Talmón, los hijos de Acub, los hijos de Hatita, los hijos de Sobai; por todos, ciento treinta y nueve. </div>
<div id="Ezr_2_43" style="display:none;" class="ver_select"><b>Ezr 2:43</b>  Los sirvientes del templo; los hijos de Siha, los hijos de Hasufa, los hijos de Tabaot, </div>
<div id="Ezr_2_44" style="display:none;" class="ver_select"><b>Ezr 2:44</b>  los hijos de Queros, los hijos de Siaha, los hijos de Padón; </div>
<div id="Ezr_2_45" style="display:none;" class="ver_select"><b>Ezr 2:45</b>  los hijos de Lebana, los hijos de Hagaba, los hijos de Acub. </div>
<div id="Ezr_2_46" style="display:none;" class="ver_select"><b>Ezr 2:46</b>  Los hijos de Hagab, los hijos de Samlai, los hijos de Hanán. </div>
<div id="Ezr_2_47" style="display:none;" class="ver_select"><b>Ezr 2:47</b>  Los hijos de Gidel, los hijos de Gahar, los hijos de Reaías. </div>
<div id="Ezr_2_48" style="display:none;" class="ver_select"><b>Ezr 2:48</b>  Los hijos de Rezín, los hijos de Necoda, los hijos de Gazam. </div>
<div id="Ezr_2_49" style="display:none;" class="ver_select"><b>Ezr 2:49</b>  Los hijos de Uza, los hijos de Pasea, los hijos de Besai. </div>
<div id="Ezr_2_50" style="display:none;" class="ver_select"><b>Ezr 2:50</b>  Los hijos de Asná, los hijos de Meunim, los hijos de Nefusim. </div>
<div id="Ezr_2_51" style="display:none;" class="ver_select"><b>Ezr 2:51</b>  Los hijos de Bacbuc, los hijos de Hacufa, los hijos de Harhur. </div>
<div id="Ezr_2_52" style="display:none;" class="ver_select"><b>Ezr 2:52</b>  Los hijos de Bazlut, los hijos de Mehída, los hijos de Harsa. </div>
<div id="Ezr_2_53" style="display:none;" class="ver_select"><b>Ezr 2:53</b>  Los hijos de Barcos, los hijos de Sísara, los hijos de Tema. </div>
<div id="Ezr_2_54" style="display:none;" class="ver_select"><b>Ezr 2:54</b>  Los hijos de Nesía, los hijos de Hatifa. </div>
<div id="Ezr_2_55" style="display:none;" class="ver_select"><b>Ezr 2:55</b>  Los hijos de los siervos de Salomón; los hijos de Sotai, los hijos de Soferet, los hijos de Peruda. </div>
<div id="Ezr_2_56" style="display:none;" class="ver_select"><b>Ezr 2:56</b>  Los hijos de Jaala, los hijos de Darcón, los hijos de Gidel. </div>
<div id="Ezr_2_57" style="display:none;" class="ver_select"><b>Ezr 2:57</b>  Los hijos de Sefatías, los hijos de Hatil, los hijos de Poqueret-hazebaim, los hijos de Ami. </div>
<div id="Ezr_2_58" style="display:none;" class="ver_select"><b>Ezr 2:58</b>  Todos los sirvientes del templo, e hijos de los siervos de Salomón, trescientos noventa y dos. </div>
<div id="Ezr_2_59" style="display:none;" class="ver_select"><b>Ezr 2:59</b>  Y éstos fueron los que subieron de Tel-mela, Tel-harsa, Querub, Adán, e Imer, los cuales no pudieron demostrar la casa de sus padres, ni su linaje, si eran de Israel. </div>
<div id="Ezr_2_60" style="display:none;" class="ver_select"><b>Ezr 2:60</b>  Los hijos de Delaías, los hijos de Tobías, los hijos de Necoda, seiscientos cincuenta y dos. </div>
<div id="Ezr_2_61" style="display:none;" class="ver_select"><b>Ezr 2:61</b>  Y de los hijos de los sacerdotes: los hijos de Habaías, los hijos de Cos, los hijos de Barzilai, el cual tomó esposa de las hijas de Barzilai galaadita, y fue llamado del nombre de ellas. </div>
<div id="Ezr_2_62" style="display:none;" class="ver_select"><b>Ezr 2:62</b>  Éstos buscaron su registro de genealogías, y no fue hallado; y fueron excluidos del sacerdocio. </div>
<div id="Ezr_2_63" style="display:none;" class="ver_select"><b>Ezr 2:63</b>  Y el Tirsata les dijo que no comiesen de las cosas más santas, hasta que hubiese sacerdote con Urim y Tumim. </div>
<div id="Ezr_2_64" style="display:none;" class="ver_select"><b>Ezr 2:64</b>  Toda la congregación, unida como un solo hombre, era de cuarenta y dos mil trescientos sesenta, </div>
<div id="Ezr_2_65" style="display:none;" class="ver_select"><b>Ezr 2:65</b>  además de sus siervos y siervas, los cuales eran siete mil trescientos treinta y siete: y tenían doscientos cantores y cantoras. </div>
<div id="Ezr_2_66" style="display:none;" class="ver_select"><b>Ezr 2:66</b>  Sus caballos eran setecientos treinta y seis; sus mulos, doscientos cuarenta y cinco; </div>
<div id="Ezr_2_67" style="display:none;" class="ver_select"><b>Ezr 2:67</b>  sus camellos, cuatrocientos treinta y cinco; asnos, seis mil setecientos veinte. </div>
<div id="Ezr_2_68" style="display:none;" class="ver_select"><b>Ezr 2:68</b>  Y algunos de los jefes de los padres, cuando vinieron a la casa de Jehová la cual estaba en Jerusalén, ofrendaron voluntariamente para la casa de Dios, para levantarla en su mismo lugar. </div>
<div id="Ezr_2_69" style="display:none;" class="ver_select"><b>Ezr 2:69</b>  Según sus fuerzas dieron al tesorero de la obra sesenta y un mil dracmas de oro, y cinco mil libras de plata, y cien túnicas sacerdotales. </div>
<div id="Ezr_2_70" style="display:none;" class="ver_select"><b>Ezr 2:70</b>  Y habitaron los sacerdotes, y los levitas, y los del pueblo, y los cantores, y los porteros y los servidores del templo, en sus ciudades; y todo Israel en sus ciudades. </div>
<div id="Ezr_3_1" style="display:none;" class="ver_select"><b>Ezr 3:1</b>  Y cuando llegó el mes séptimo, y los hijos de Israel estaban ya en las ciudades, se reunió el pueblo como un solo hombre en Jerusalén. </div>
<div id="Ezr_3_2" style="display:none;" class="ver_select"><b>Ezr 3:2</b>  Entonces se levantó Jesúa hijo de Josadac, y sus hermanos los sacerdotes, y Zorobabel hijo de Salatiel, y sus hermanos, y edificaron el altar del Dios de Israel, para ofrecer sobre él holocaustos como está escrito en la ley de Moisés varón de Dios. </div>
<div id="Ezr_3_3" style="display:none;" class="ver_select"><b>Ezr 3:3</b>  Y asentaron el altar sobre sus bases, aunque tenían miedo de los pueblos de las tierras; y ofrecieron sobre él holocaustos a Jehová, holocaustos a la mañana y a la tarde. </div>
<div id="Ezr_3_4" style="display:none;" class="ver_select"><b>Ezr 3:4</b>  Celebraron también la fiesta de los tabernáculos, como está escrito, y holocaustos cada día por cuenta, conforme a lo establecido para cada día; </div>
<div id="Ezr_3_5" style="display:none;" class="ver_select"><b>Ezr 3:5</b>  y a más de esto, el holocausto continuo, y las nuevas lunas, y todas las fiestas santificadas de Jehová, y todo sacrificio espontáneo, toda ofrenda voluntaria a Jehová. </div>
<div id="Ezr_3_6" style="display:none;" class="ver_select"><b>Ezr 3:6</b>  Desde el primer día del mes séptimo comenzaron a ofrecer holocaustos a Jehová; pero los cimientos del templo de Jehová no se habían echado todavía. </div>
<div id="Ezr_3_7" style="display:none;" class="ver_select"><b>Ezr 3:7</b>  Y dieron dinero a los albañiles y carpinteros; asimismo comida y bebida y aceite a los sidonios y tirios, para que trajesen madera de cedro del Líbano por mar a Jope, conforme a la voluntad de Ciro rey de Persia acerca de esto. </div>
<div id="Ezr_3_8" style="display:none;" class="ver_select"><b>Ezr 3:8</b>  Y en el año segundo de su venida a la casa de Dios en Jerusalén, en el mes segundo, comenzaron Zorobabel hijo de Salatiel, y Jesúa hijo de Josadac, y los otros sus hermanos, los sacerdotes y los levitas, y todos los que habían venido de la cautividad a Jerusalén; y pusieron a los levitas de veinte años arriba para que tuviesen cargo de la obra de la casa de Jehová. </div>
<div id="Ezr_3_9" style="display:none;" class="ver_select"><b>Ezr 3:9</b>  Jesúa también, sus hijos y sus hermanos, Cadmiel y sus hijos, hijos de Judá, como un solo hombre asistían para dar prisa a los que hacían la obra en la casa de Dios: los hijos de Henadad, sus hijos y sus hermanos los levitas. </div>
<div id="Ezr_3_10" style="display:none;" class="ver_select"><b>Ezr 3:10</b>  Y cuando los albañiles del templo de Jehová echaban los cimientos, pusieron a los sacerdotes vestidos de sus ropas, con trompetas, y a los levitas hijos de Asaf con címbalos, para que alabasen a Jehová, según la ordenanza de David rey de Israel. </div>
<div id="Ezr_3_11" style="display:none;" class="ver_select"><b>Ezr 3:11</b>  Y cantaban, alabando y dando gracias a Jehová, y decían: Porque Él es bueno, porque para siempre es su misericordia sobre Israel. Y todo el pueblo aclamaba con gran júbilo, alabando a Jehová, porque se echaban los cimientos de la casa de Jehová. </div>
<div id="Ezr_3_12" style="display:none;" class="ver_select"><b>Ezr 3:12</b>  Y muchos de los sacerdotes y de los levitas y de los jefes de los padres, ancianos que habían visto la primera casa, al ver que se echaban los cimientos de esta casa, lloraban en alta voz, mientras muchos otros daban grandes gritos de alegría. </div>
<div id="Ezr_3_13" style="display:none;" class="ver_select"><b>Ezr 3:13</b>  Y no podía discernir el pueblo el clamor de los gritos de alegría, de la voz del lloro del pueblo; porque clamaba el pueblo con gran júbilo, y se oía el ruido hasta de lejos. </div>
<div id="Ezr_4_1" style="display:none;" class="ver_select"><b>Ezr 4:1</b>  Y cuando los enemigos de Judá y de Benjamín oyeron que los hijos de los de la cautividad edificaban el templo de Jehová Dios de Israel, </div>
<div id="Ezr_4_2" style="display:none;" class="ver_select"><b>Ezr 4:2</b>  vinieron a Zorobabel, y a los jefes de los padres, y les dijeron: Permitidnos edificar con vosotros, porque nosotros buscamos a vuestro Dios al igual que vosotros, y a Él hacemos sacrificios desde los días de Esar-hadón rey de Asiria, que nos hizo subir aquí. </div>
<div id="Ezr_4_3" style="display:none;" class="ver_select"><b>Ezr 4:3</b>  Pero Zorobabel, y Jesúa y los demás cabezas de los padres de Israel les dijeron: Vosotros nada tenéis que hacer edificando con nosotros casa a nuestro Dios, sino que nosotros unidos la edificaremos a Jehová Dios de Israel, como nos mandó el rey Ciro, rey de Persia. </div>
<div id="Ezr_4_4" style="display:none;" class="ver_select"><b>Ezr 4:4</b>  Entonces el pueblo de la tierra debilitaba las manos del pueblo de Judá, atemorizándolo para que no edificara. </div>
<div id="Ezr_4_5" style="display:none;" class="ver_select"><b>Ezr 4:5</b>  Y contrataron consejeros contra ellos para frustrar su propósito, todo el tiempo de Ciro rey de Persia, y hasta el reinado de Darío rey de Persia. </div>
<div id="Ezr_4_6" style="display:none;" class="ver_select"><b>Ezr 4:6</b>  Y en el reinado de Asuero, en el principio de su reinado, escribieron acusaciones contra los moradores de Judá y de Jerusalén. </div>
<div id="Ezr_4_7" style="display:none;" class="ver_select"><b>Ezr 4:7</b>  Y en días de Artajerjes, Bislam, Mitrídates, Tabeel, y los demás sus compañeros, escribieron a Artajerjes rey de Persia; y la escritura de la carta estaba hecha en arameo y traducida en arameo. </div>
<div id="Ezr_4_8" style="display:none;" class="ver_select"><b>Ezr 4:8</b>  Rehum el canciller y el escriba Simsai escribieron una carta contra Jerusalén al rey Artajerjes, de esta manera. </div>
<div id="Ezr_4_9" style="display:none;" class="ver_select"><b>Ezr 4:9</b>  En aquel tiempo escribieron el canciller Rehum y el escriba Simsai, y sus demás compañeros, los dineos, los aparsaqueos, los tarpelitas, los afarseos, los erqueos, los babilonios, los susasqueos, los dieveos y los elamitas; </div>
<div id="Ezr_4_10" style="display:none;" class="ver_select"><b>Ezr 4:10</b>  y los demás pueblos que el grande y glorioso Asnapar trasportó, e hizo habitar en las ciudades de Samaria, y los demás del otro lado del río. Y ahora: </div>
<div id="Ezr_4_11" style="display:none;" class="ver_select"><b>Ezr 4:11</b>  Ésta es la copia de la carta que enviaron: Al rey Artajerjes: Tus siervos del otro lado del río. Y ahora: </div>
<div id="Ezr_4_12" style="display:none;" class="ver_select"><b>Ezr 4:12</b>  Sea notorio al rey, que los judíos que subieron de ti a nosotros, vinieron a Jerusalén; y edifican la ciudad rebelde y mala, y han levantado los muros y reparado los fundamentos. </div>
<div id="Ezr_4_13" style="display:none;" class="ver_select"><b>Ezr 4:13</b>  Ahora sea notorio al rey, que si aquella ciudad fuere reedificada, y los muros fueren establecidos, ellos no pagarán tributo, ni impuesto, ni rentas, y el catastro de los reyes será menoscabado. </div>
<div id="Ezr_4_14" style="display:none;" class="ver_select"><b>Ezr 4:14</b>  Y ya que nos mantienen del palacio, no nos es justo ver el menosprecio del rey; hemos enviado por tanto, y lo hemos hecho saber al rey, </div>
<div id="Ezr_4_15" style="display:none;" class="ver_select"><b>Ezr 4:15</b>  para que busque en el libro de las historias de nuestros padres; y hallarás en el libro de las historias, y sabrás que esta ciudad es una ciudad rebelde y perjudicial a los reyes y a las provincias, y que de tiempo antiguo forman en medio de ella rebeliones; por lo que esta ciudad fue destruida. </div>
<div id="Ezr_4_16" style="display:none;" class="ver_select"><b>Ezr 4:16</b>  Hacemos saber al rey, que si esta ciudad fuere reedificada, y erigidos sus muros, la región de más allá del río no será tuya. </div>
<div id="Ezr_4_17" style="display:none;" class="ver_select"><b>Ezr 4:17</b>  El rey envió esta respuesta a Rehum el canciller, y al escriba Simsai, y a los demás sus compañeros que habitan en Samaria, y a los demás del otro lado del río: Paz ahora. </div>
<div id="Ezr_4_18" style="display:none;" class="ver_select"><b>Ezr 4:18</b>  La carta que nos enviasteis fue leída claramente delante de mí. </div>
<div id="Ezr_4_19" style="display:none;" class="ver_select"><b>Ezr 4:19</b>  Y por mí fue dado mandamiento, y buscaron; y hallaron que aquella ciudad de tiempo antiguo se ha levantado contra los reyes y se ha rebelado, y se ha formado en ella sedición; </div>
<div id="Ezr_4_20" style="display:none;" class="ver_select"><b>Ezr 4:20</b>  y que reyes fuertes hubo en Jerusalén, quienes señorearon en todas las provincias que están más allá del río; y que se les pagaba tributo, impuesto y rentas. </div>
<div id="Ezr_4_21" style="display:none;" class="ver_select"><b>Ezr 4:21</b>  Ahora, pues, dad orden que cesen aquellos hombres, y que no sea esa ciudad reedificada hasta que por mí sea dado mandamiento. </div>
<div id="Ezr_4_22" style="display:none;" class="ver_select"><b>Ezr 4:22</b>  Y mirad bien que no hagáis error en esto; ¿por qué habrá de crecer el daño para perjuicio de los reyes? </div>
<div id="Ezr_4_23" style="display:none;" class="ver_select"><b>Ezr 4:23</b>  Entonces, cuando la copia de la carta del rey Artajerjes fue leída delante de Rehum, y del escriba Simsai, y sus compañeros, fueron prestamente a Jerusalén a los judíos, y les hicieron cesar con poder y fuerza. </div>
<div id="Ezr_4_24" style="display:none;" class="ver_select"><b>Ezr 4:24</b>  Entonces cesó la obra de la casa de Dios, que estaba en Jerusalén. Y cesó hasta el año segundo del reinado de Darío rey de Persia. </div>
<div id="Ezr_5_1" style="display:none;" class="ver_select"><b>Ezr 5:1</b>  Y los profetas, Hageo profeta, y Zacarías hijo de Iddo, profetizaron en el nombre del Dios de Israel a los judíos, a aquellos que estaban en Judá y en Jerusalén. </div>
<div id="Ezr_5_2" style="display:none;" class="ver_select"><b>Ezr 5:2</b>  Entonces se levantaron Zorobabel hijo de Salatiel, y Jesúa hijo de Josadac; y comenzaron a reedificar la casa de Dios que estaba en Jerusalén; y los profetas de Dios estaban con ellos ayudándoles. </div>
<div id="Ezr_5_3" style="display:none;" class="ver_select"><b>Ezr 5:3</b>  En aquel tiempo vino a ellos Tatnai, capitán del otro lado del río, y Setar-boznai y sus compañeros, y les dijeron así: ¿Quién os dio mandamiento para edificar esta casa, y restablecer estos muros? </div>
<div id="Ezr_5_4" style="display:none;" class="ver_select"><b>Ezr 5:4</b>  Entonces les dijeron así: ¿Cuáles son los nombres de los varones que edifican este edificio? </div>
<div id="Ezr_5_5" style="display:none;" class="ver_select"><b>Ezr 5:5</b>  Pero los ojos de Dios fueron sobre los ancianos de los judíos, y no les hicieron cesar hasta que el asunto viniese a Darío; y entonces respondieron por carta sobre esto. </div>
<div id="Ezr_5_6" style="display:none;" class="ver_select"><b>Ezr 5:6</b>  Copia de la carta que Tatnai, gobernador de más allá del río, y Setar-boznai, y sus compañeros los aparsaqueos, que estaban al otro lado del río, enviaron al rey Darío. </div>
<div id="Ezr_5_7" style="display:none;" class="ver_select"><b>Ezr 5:7</b>  Le enviaron una carta, en la que estaba escrito de esta manera: Al rey Darío toda paz. </div>
<div id="Ezr_5_8" style="display:none;" class="ver_select"><b>Ezr 5:8</b>  Sea notorio al rey, que fuimos a la provincia de Judea, a la casa del gran Dios, la cual se edifica de piedras grandes; y los maderos son puestos en las paredes, y la obra se hace aprisa, y prospera en sus manos. </div>
<div id="Ezr_5_9" style="display:none;" class="ver_select"><b>Ezr 5:9</b>  Entonces preguntamos a los ancianos, diciéndoles así: ¿Quién os dio mandamiento para edificar esta casa, y para restablecer estos muros? </div>
<div id="Ezr_5_10" style="display:none;" class="ver_select"><b>Ezr 5:10</b>  Y también les preguntamos sus nombres para hacértelo saber, para escribirte los nombres de los varones que eran los jefes de ellos. </div>
<div id="Ezr_5_11" style="display:none;" class="ver_select"><b>Ezr 5:11</b>  Y nos respondieron, diciendo así: Nosotros somos siervos del Dios del cielo y de la tierra, y reedificamos la casa que ya muchos años antes había sido edificada, la cual edificó y terminó el gran rey de Israel. </div>
<div id="Ezr_5_12" style="display:none;" class="ver_select"><b>Ezr 5:12</b>  Mas después que nuestros padres provocaron a ira al Dios de los cielos, Él los entregó en mano de Nabucodonosor rey de Babilonia, caldeo, el cual destruyó esta casa, e hizo trasportar al pueblo a Babilonia. </div>
<div id="Ezr_5_13" style="display:none;" class="ver_select"><b>Ezr 5:13</b>  Pero en el año primero de Ciro rey de Babilonia, el mismo rey Ciro dio mandamiento para que esta casa de Dios fuese reedificada. </div>
<div id="Ezr_5_14" style="display:none;" class="ver_select"><b>Ezr 5:14</b>  Y también los vasos de oro y de plata de la casa de Dios, que Nabucodonosor había sacado del templo que estaba en Jerusalén, y los había metido en el templo de Babilonia, el rey Ciro los sacó del templo de Babilonia, y fueron entregados a Sesbasar, al cual había puesto por gobernador; </div>
<div id="Ezr_5_15" style="display:none;" class="ver_select"><b>Ezr 5:15</b>  y le dijo: Toma estos vasos, ve, y ponlos en el templo que está en Jerusalén; y la casa de Dios sea reedificada en su lugar. </div>
<div id="Ezr_5_16" style="display:none;" class="ver_select"><b>Ezr 5:16</b>  Entonces este Sesbasar vino, y puso los fundamentos de la casa de Dios que estaba en Jerusalén, y desde entonces hasta ahora se edifica, y aún no está terminada. </div>
<div id="Ezr_5_17" style="display:none;" class="ver_select"><b>Ezr 5:17</b>  Y ahora, si al rey parece bien, búsquese en la casa de los tesoros del rey que está allí en Babilonia, si es así que por el rey Ciro había sido dado mandamiento para reedificar esta casa de Dios en Jerusalén, y envíenos a decir la voluntad del rey sobre esto. </div>
<div id="Ezr_6_1" style="display:none;" class="ver_select"><b>Ezr 6:1</b>  Entonces el rey Darío dio mandamiento, y buscaron en la casa de los libros, donde guardaban los tesoros allí en Babilonia. </div>
<div id="Ezr_6_2" style="display:none;" class="ver_select"><b>Ezr 6:2</b>  Y fue hallado en Acmeta, en el palacio que está en la provincia de Media, un libro, en el que estaba escrito así: Memoria: </div>
<div id="Ezr_6_3" style="display:none;" class="ver_select"><b>Ezr 6:3</b>  En el año primero del rey Ciro, el mismo rey Ciro dio mandamiento acerca de la casa de Dios que estaba en Jerusalén, para que fuese edificada la casa, lugar donde se ofrecen sacrificios, y que sus paredes fuesen firmes; su altura de sesenta codos, y de sesenta codos su anchura; </div>
<div id="Ezr_6_4" style="display:none;" class="ver_select"><b>Ezr 6:4</b>  con tres hileras de piedras grandes, y una hilera de madera nueva y que los gastos sean pagados por la casa del rey. </div>
<div id="Ezr_6_5" style="display:none;" class="ver_select"><b>Ezr 6:5</b>  Y también los vasos de oro y de plata de la casa de Dios, que Nabucodonosor sacó del templo que estaba en Jerusalén y los pasó a Babilonia, sean devueltos y sean traídos al templo que está en Jerusalén, a su lugar, y sean puestos en la casa de Dios. </div>
<div id="Ezr_6_6" style="display:none;" class="ver_select"><b>Ezr 6:6</b>  Ahora pues, Tatnai, jefe de más allá del río, Setar-boznai, y sus compañeros los aparsaqueos que estáis al otro lado del río, apartaos de allí.  </div>
<div id="Ezr_6_7" style="display:none;" class="ver_select"><b>Ezr 6:7</b>  Dejad que se haga la obra de esta casa de Dios; que el principal de los judíos y a sus ancianos edifiquen esta casa de Dios en su lugar. </div>
<div id="Ezr_6_8" style="display:none;" class="ver_select"><b>Ezr 6:8</b>  Y por mí es dado mandamiento de lo que habéis de hacer con los ancianos de estos judíos, para edificar esta casa de Dios; que de la hacienda del rey, que tiene del tributo del otro lado del río, los gastos sean dados luego a aquellos varones, para que no cesen. </div>
<div id="Ezr_6_9" style="display:none;" class="ver_select"><b>Ezr 6:9</b>  Y lo que fuere necesario, becerros y carneros y corderos, para holocaustos al Dios del cielo, trigo, sal, vino y aceite, conforme a lo que dijeren los sacerdotes que están en Jerusalén, les sea dado cada día, sin falta; </div>
<div id="Ezr_6_10" style="display:none;" class="ver_select"><b>Ezr 6:10</b>  para que ofrezcan sacrificios de perfume grato al Dios del cielo, y oren por la vida del rey y por sus hijos. </div>
<div id="Ezr_6_11" style="display:none;" class="ver_select"><b>Ezr 6:11</b>  También es dado por mí mandamiento, que cualquiera que altere este decreto, le sea arrancado un madero de su casa, y alzado, sea colgado en él, y su casa sea hecha muladar por esto. </div>
<div id="Ezr_6_12" style="display:none;" class="ver_select"><b>Ezr 6:12</b>  Y el Dios que hizo habitar allí su nombre, destruya a todo rey y pueblo que pusiere su mano y lo altere para destruir esta casa de Dios, la cual está en Jerusalén. Yo Darío he dado el decreto; sea hecho prestamente. </div>
<div id="Ezr_6_13" style="display:none;" class="ver_select"><b>Ezr 6:13</b>  Entonces Tatnai, gobernador del otro lado del río, y Setar-boznai, y sus compañeros, hicieron prestamente según el rey Darío había enviado. </div>
<div id="Ezr_6_14" style="display:none;" class="ver_select"><b>Ezr 6:14</b>  Y los ancianos de los judíos edificaban y prosperaban, conforme a la profecía de Hageo profeta, y de Zacarías hijo de Iddo. Edificaron, pues, y acabaron, conforme al mandamiento del Dios de Israel, y por mandato de Ciro, y de Darío, y de Artajerjes rey de Persia. </div>
<div id="Ezr_6_15" style="display:none;" class="ver_select"><b>Ezr 6:15</b>  Y esta casa fue acabada al tercer día del mes de Adar, que era el sexto año del reinado del rey Darío. </div>
<div id="Ezr_6_16" style="display:none;" class="ver_select"><b>Ezr 6:16</b>  Y los hijos de Israel, los sacerdotes y los levitas, y los demás que habían venido de la cautividad, hicieron la dedicación de esta casa de Dios con gozo. </div>
<div id="Ezr_6_17" style="display:none;" class="ver_select"><b>Ezr 6:17</b>  Y ofrecieron en la dedicación de esta casa de Dios cien becerros, doscientos carneros y cuatrocientos corderos; y machos cabríos en expiación por todo Israel, doce, conforme al número de las tribus de Israel. </div>
<div id="Ezr_6_18" style="display:none;" class="ver_select"><b>Ezr 6:18</b>  Y pusieron a los sacerdotes en sus clases, y a los levitas en sus divisiones, sobre la obra de Dios que está en Jerusalén, conforme a lo escrito en el libro de Moisés. </div>
<div id="Ezr_6_19" style="display:none;" class="ver_select"><b>Ezr 6:19</b>  Y los hijos de la cautividad celebraron la pascua a los catorce del mes primero. </div>
<div id="Ezr_6_20" style="display:none;" class="ver_select"><b>Ezr 6:20</b>  Porque los sacerdotes y los levitas se habían purificado a una; todos fueron limpios; y sacrificaron la pascua por todos los hijos de la cautividad, y por sus hermanos los sacerdotes, y por sí mismos. </div>
<div id="Ezr_6_21" style="display:none;" class="ver_select"><b>Ezr 6:21</b>  Y comieron los hijos de Israel que habían vuelto de la cautividad, y todos los que se habían apartado a ellos de la inmundicia de las naciones de la tierra, para buscar a Jehová Dios de Israel. </div>
<div id="Ezr_6_22" style="display:none;" class="ver_select"><b>Ezr 6:22</b>  Y durante siete días con regocijo celebraron la fiesta de los panes sin levadura, porque Jehová los había alegrado, y había vuelto el corazón del rey de Asiria hacia ellos, para esforzar sus manos en la obra de la casa de Dios, del Dios de Israel. </div>
<div id="Ezr_7_1" style="display:none;" class="ver_select"><b>Ezr 7:1</b>  Pasadas estas cosas, en el reinado de Artajerjes rey de Persia, Esdras, hijo de Seraías, hijo de Azarías, hijo de Hilcías, </div>
<div id="Ezr_7_2" style="display:none;" class="ver_select"><b>Ezr 7:2</b>  hijo de Salum, hijo de Sadoc, hijo de Ahitob, </div>
<div id="Ezr_7_3" style="display:none;" class="ver_select"><b>Ezr 7:3</b>  hijo de Amarías, hijo de Azarías, hijo de Meraiot, </div>
<div id="Ezr_7_4" style="display:none;" class="ver_select"><b>Ezr 7:4</b>  hijo de Zeraías, hijo de Uzi, hijo de Buqui, </div>
<div id="Ezr_7_5" style="display:none;" class="ver_select"><b>Ezr 7:5</b>  hijo de Abisúa, hijo de Finees, hijo de Eleazar, hijo de Aarón, primer sacerdote. </div>
<div id="Ezr_7_6" style="display:none;" class="ver_select"><b>Ezr 7:6</b>  Este Esdras subió de Babilonia, el cual era escriba diligente en la ley de Moisés, que Jehová Dios de Israel había dado; y el rey le concedió todo lo que pidió, según la mano de Jehová su Dios era sobre él. </div>
<div id="Ezr_7_7" style="display:none;" class="ver_select"><b>Ezr 7:7</b>  Y subieron con él a Jerusalén de los hijos de Israel, y de los sacerdotes, y levitas, y cantores, y porteros, y servidores del templo, en el séptimo año del rey Artajerjes. </div>
<div id="Ezr_7_8" style="display:none;" class="ver_select"><b>Ezr 7:8</b>  Y llegó a Jerusalén en el mes quinto, el año séptimo del rey. </div>
<div id="Ezr_7_9" style="display:none;" class="ver_select"><b>Ezr 7:9</b>  Porque el día primero del primer mes fue el principio de la partida de Babilonia, y al primero del mes quinto llegó a Jerusalén, según la buena mano de su Dios sobre él. </div>
<div id="Ezr_7_10" style="display:none;" class="ver_select"><b>Ezr 7:10</b>  Porque Esdras había preparado su corazón para inquirir la ley de Jehová, y para hacer y enseñar a Israel mandamientos y juicios. </div>
<div id="Ezr_7_11" style="display:none;" class="ver_select"><b>Ezr 7:11</b>  Y ésta es la copia de la carta que dio el rey Artajerjes a Esdras, sacerdote escriba, escriba instruido en las palabras de los mandamientos de Jehová, y de sus estatutos a Israel: </div>
<div id="Ezr_7_12" style="display:none;" class="ver_select"><b>Ezr 7:12</b>  Artajerjes, rey de los reyes, a Esdras sacerdote, escriba de la ley del Dios del cielo: Perfecta paz, etcétera. </div>
<div id="Ezr_7_13" style="display:none;" class="ver_select"><b>Ezr 7:13</b>  Por mí es dado mandamiento, que cualquiera que quisiere en mi reino, del pueblo de Israel y de sus sacerdotes y levitas, ir contigo a Jerusalén, vaya. </div>
<div id="Ezr_7_14" style="display:none;" class="ver_select"><b>Ezr 7:14</b>  Porque de parte del rey y de sus siete consejeros eres enviado a visitar a Judea y a Jerusalén, conforme a la ley de tu Dios que está en tu mano; </div>
<div id="Ezr_7_15" style="display:none;" class="ver_select"><b>Ezr 7:15</b>  Y a llevar la plata y el oro que el rey y sus consultores voluntariamente ofrecen al Dios de Israel, cuya morada está en Jerusalén, </div>
<div id="Ezr_7_16" style="display:none;" class="ver_select"><b>Ezr 7:16</b>  y toda la plata y el oro que hallares en toda la provincia de Babilonia, con las ofrendas voluntarias del pueblo y de los sacerdotes, que de su voluntad ofrecieren para la casa de su Dios que está en Jerusalén. </div>
<div id="Ezr_7_17" style="display:none;" class="ver_select"><b>Ezr 7:17</b>  Comprarás, pues, prestamente con este dinero becerros, carneros, corderos, con sus presentes y sus libaciones, y los ofrecerás sobre el altar de la casa de vuestro Dios que está en Jerusalén. </div>
<div id="Ezr_7_18" style="display:none;" class="ver_select"><b>Ezr 7:18</b>  Y lo que a ti y a tus hermanos os parezca hacer con el resto de la plata y oro, hacedlo conforme a la voluntad de vuestro Dios. </div>
<div id="Ezr_7_19" style="display:none;" class="ver_select"><b>Ezr 7:19</b>  Y los vasos que te son entregados para el servicio de la casa de tu Dios, los restituirás delante de Dios en Jerusalén. </div>
<div id="Ezr_7_20" style="display:none;" class="ver_select"><b>Ezr 7:20</b>  Y lo demás que se requiera para la casa de tu Dios que te sea necesario dar, lo darás de la casa de los tesoros del rey. </div>
<div id="Ezr_7_21" style="display:none;" class="ver_select"><b>Ezr 7:21</b>  Y por mí el rey Artajerjes es dado mandamiento a todos los tesoreros que están al otro lado del río, que todo lo que os demandare Esdras sacerdote, escriba de la ley del Dios del cielo, se le conceda prestamente, </div>
<div id="Ezr_7_22" style="display:none;" class="ver_select"><b>Ezr 7:22</b>  hasta cien talentos de plata, y hasta cien coros de trigo, y hasta cien batos de vino, y hasta cien batos de aceite; y sal sin medida. </div>
<div id="Ezr_7_23" style="display:none;" class="ver_select"><b>Ezr 7:23</b>  Todo lo que es mandado por el Dios del cielo, sea hecho prestamente para la casa del Dios del cielo; pues, ¿por qué habría de ser su ira contra el reino del rey y de sus hijos? </div>
<div id="Ezr_7_24" style="display:none;" class="ver_select"><b>Ezr 7:24</b>  Y a vosotros os hacemos saber que a todos los sacerdotes y levitas, cantores, porteros, servidores del templo y ministros de la casa de Dios, ninguno pueda imponerles tributo, impuesto, o renta. </div>
<div id="Ezr_7_25" style="display:none;" class="ver_select"><b>Ezr 7:25</b>  Y tú, Esdras, conforme a la sabiduría que tienes de tu Dios, pon jueces y gobernadores, que gobiernen a todo el pueblo que está del otro lado del río, a todos los que conocen las leyes de tu Dios; y al que no las conoce, le enseñarás. </div>
<div id="Ezr_7_26" style="display:none;" class="ver_select"><b>Ezr 7:26</b>  Y cualquiera que no cumpliere la ley de tu Dios, y la ley del rey, prestamente sea juzgado, o a muerte, o a destierro, o a confiscación de bienes, o a prisión. </div>
<div id="Ezr_7_27" style="display:none;" class="ver_select"><b>Ezr 7:27</b>  Bendito Jehová, Dios de nuestros padres, que puso tal cosa en el corazón del rey, para honrar la casa de Jehová que está en Jerusalén, </div>
<div id="Ezr_7_28" style="display:none;" class="ver_select"><b>Ezr 7:28</b>  e inclinó hacia mí su misericordia delante del rey y de sus consejeros, y de todos los príncipes poderosos del rey. Y yo, fortalecido según la mano de mi Dios sobre mí, reuní a los principales de Israel para que subiesen conmigo. </div>
<div id="Ezr_8_1" style="display:none;" class="ver_select"><b>Ezr 8:1</b>  Y éstos son los jefes de sus padres, y la genealogía de los que subieron conmigo de Babilonia, cuando reinaba el rey Artajerjes. </div>
<div id="Ezr_8_2" style="display:none;" class="ver_select"><b>Ezr 8:2</b>  De los hijos de Finees, Gersón; de los hijos de Itamar, Daniel; de los hijos de David, Hatús; </div>
<div id="Ezr_8_3" style="display:none;" class="ver_select"><b>Ezr 8:3</b>  de los hijos de Secanías y de los hijos de Paros, Zacarías, y con él, en la línea de varones, ciento cincuenta; </div>
<div id="Ezr_8_4" style="display:none;" class="ver_select"><b>Ezr 8:4</b>  de los hijos de Pahat-moab, Elioenai, hijo de Zeraías, y con él doscientos varones; </div>
<div id="Ezr_8_5" style="display:none;" class="ver_select"><b>Ezr 8:5</b>  de los hijos de Secanías, el hijo de Jahaziel, y con él trescientos varones; </div>
<div id="Ezr_8_6" style="display:none;" class="ver_select"><b>Ezr 8:6</b>  de los hijos de Adín, Ebed, hijo de Jonatán, y con él cincuenta varones; </div>
<div id="Ezr_8_7" style="display:none;" class="ver_select"><b>Ezr 8:7</b>  de los hijos de Elam, Jesahías, hijo de Atalías, y con él setenta varones; </div>
<div id="Ezr_8_8" style="display:none;" class="ver_select"><b>Ezr 8:8</b>  y de los hijos de Sefatías, Zebadías, hijo de Micael, y con él ochenta varones; </div>
<div id="Ezr_8_9" style="display:none;" class="ver_select"><b>Ezr 8:9</b>  de los hijos de Joab, Abdías, hijo de Jehiel, y con él doscientos dieciocho varones; </div>
<div id="Ezr_8_10" style="display:none;" class="ver_select"><b>Ezr 8:10</b>  y de los hijos de Selomit, el hijo de Josifías, y con él ciento sesenta varones; </div>
<div id="Ezr_8_11" style="display:none;" class="ver_select"><b>Ezr 8:11</b>  y de los hijos de Bebai, Zacarías, hijo de Bebai, y con él veintiocho varones; </div>
<div id="Ezr_8_12" style="display:none;" class="ver_select"><b>Ezr 8:12</b>  y de los hijos de Azgad, Johanán, hijo de Catán, y con él ciento diez varones; </div>
<div id="Ezr_8_13" style="display:none;" class="ver_select"><b>Ezr 8:13</b>  y de los hijos de Adonicam, los postreros, cuyos nombres son estos, Elifelet, Jeiel, y Semaías, y con ellos sesenta varones; </div>
<div id="Ezr_8_14" style="display:none;" class="ver_select"><b>Ezr 8:14</b>  y de los hijos de Bigvai, Utai y Zabud, y con ellos setenta varones. </div>
<div id="Ezr_8_15" style="display:none;" class="ver_select"><b>Ezr 8:15</b>  Y los reuní junto al río que viene a Ahava, y acampamos allí tres días: y habiendo buscado entre el pueblo y entre los sacerdotes, no hallé allí de los hijos de Leví. </div>
<div id="Ezr_8_16" style="display:none;" class="ver_select"><b>Ezr 8:16</b>  Entonces mandé traer a Eliezer, a Ariel, a Semaías, a Elnatán, a Jarib, a Elnatán, a Natán, a Zacarías, y a Mesulam, principales; asimismo a Joiarib y a Elnatán, hombres doctos; </div>
<div id="Ezr_8_17" style="display:none;" class="ver_select"><b>Ezr 8:17</b>  y los envié a Iddo, jefe en el lugar de Casifia, y puse en boca de ellos las palabras que habían de hablar a Iddo, y a sus hermanos los sirvientes del templo en el lugar de Casifia, para que nos trajesen ministros para la casa de nuestro Dios. </div>
<div id="Ezr_8_18" style="display:none;" class="ver_select"><b>Ezr 8:18</b>  Y nos trajeron, según la buena mano de nuestro Dios sobre nosotros, un varón entendido de los hijos de Mahali, hijo de Leví, hijo de Israel; y a Serebías con sus hijos y sus hermanos, dieciocho; </div>
<div id="Ezr_8_19" style="display:none;" class="ver_select"><b>Ezr 8:19</b>  Y a Hasabías, y con él a Jesahías de los hijos de Merari, a sus hermanos y a sus hijos, veinte; </div>
<div id="Ezr_8_20" style="display:none;" class="ver_select"><b>Ezr 8:20</b>  Y de los sirvientes del templo, a quienes David puso con los príncipes para el ministerio de los levitas, doscientos veinte sirvientes del templo; todos los cuales fueron declarados por sus nombres. </div>
<div id="Ezr_8_21" style="display:none;" class="ver_select"><b>Ezr 8:21</b>  Y publiqué ayuno allí junto al río de Ahava, para afligirnos delante de nuestro Dios, para solicitar de Él camino derecho para nosotros, y para nuestros niños, y para toda nuestra hacienda. </div>
<div id="Ezr_8_22" style="display:none;" class="ver_select"><b>Ezr 8:22</b>  Porque tuve vergüenza de pedir al rey tropa y gente de a caballo que nos defendiesen del enemigo en el camino; porque habíamos hablado al rey, diciendo: La mano de nuestro Dios es para bien sobre todos los que le buscan; mas su poder y su furor contra todos los que le dejan. </div>
<div id="Ezr_8_23" style="display:none;" class="ver_select"><b>Ezr 8:23</b>  Ayunamos, pues, y pedimos a nuestro Dios sobre esto, y Él nos fue propicio. </div>
<div id="Ezr_8_24" style="display:none;" class="ver_select"><b>Ezr 8:24</b>  Aparté luego doce de los principales de los sacerdotes, a Serebías y a Hasabías, y con ellos diez de sus hermanos. </div>
<div id="Ezr_8_25" style="display:none;" class="ver_select"><b>Ezr 8:25</b>  Y les pesé la plata, y el oro, y los vasos, la ofrenda que para la casa de nuestro Dios habían ofrecido el rey, y sus consejeros, y sus príncipes, todos los que se hallaron en Israel. </div>
<div id="Ezr_8_26" style="display:none;" class="ver_select"><b>Ezr 8:26</b>  Pesé, pues, en manos de ellos seiscientos cincuenta talentos de plata, y vasos de plata por cien talentos, y cien talentos de oro; </div>
<div id="Ezr_8_27" style="display:none;" class="ver_select"><b>Ezr 8:27</b>  Además veinte tazones de oro, de mil dracmas; y dos vasos de bronce bruñido muy bueno, preciados como el oro. </div>
<div id="Ezr_8_28" style="display:none;" class="ver_select"><b>Ezr 8:28</b>  Y les dije: Vosotros estáis consagrados a Jehová, y los vasos también son santos; y la plata y el oro, ofrenda voluntaria a Jehová, Dios de nuestros padres. </div>
<div id="Ezr_8_29" style="display:none;" class="ver_select"><b>Ezr 8:29</b>  Velad, y guardadlos, hasta que los peséis delante de los príncipes de los sacerdotes y levitas, y de los jefes de los padres de Israel en Jerusalén, en las cámaras de la casa de Jehová. </div>
<div id="Ezr_8_30" style="display:none;" class="ver_select"><b>Ezr 8:30</b>  Los sacerdotes, pues, y levitas recibieron el peso de la plata y del oro y de los vasos, para traerlo a Jerusalén a la casa de nuestro Dios. </div>
<div id="Ezr_8_31" style="display:none;" class="ver_select"><b>Ezr 8:31</b>  Y partimos del río de Ahava el doce del mes primero, para ir a Jerusalén; y la mano de nuestro Dios fue sobre nosotros, y nos libró de mano del enemigo y del acechador en el camino. </div>
<div id="Ezr_8_32" style="display:none;" class="ver_select"><b>Ezr 8:32</b>  Y llegamos a Jerusalén, y reposamos allí tres días. </div>
<div id="Ezr_8_33" style="display:none;" class="ver_select"><b>Ezr 8:33</b>  Al cuarto día fue luego pesada la plata, y el oro, y los vasos, en la casa de nuestro Dios, por mano de Meremot hijo de Urías sacerdote, y con él Eleazar hijo de Finees; y con ellos Jozabad hijo de Jesúa, y Noadías hijo de Binúi, levitas. </div>
<div id="Ezr_8_34" style="display:none;" class="ver_select"><b>Ezr 8:34</b>  Por cuenta y por peso todo; y se apuntó todo aquel peso en aquel tiempo. </div>
<div id="Ezr_8_35" style="display:none;" class="ver_select"><b>Ezr 8:35</b>  También los hijos de los que habían sido llevados cautivos, y que habían venido de la cautividad, ofrecieron holocaustos al Dios de Israel, doce becerros por todo Israel, noventa y seis carneros, setenta y siete corderos, doce machos cabríos por expiación; todo el holocausto a Jehová. </div>
<div id="Ezr_8_36" style="display:none;" class="ver_select"><b>Ezr 8:36</b>  Y dieron los despachos del rey a sus gobernadores y capitanes del otro lado del río, los cuales favorecieron al pueblo y a la casa de Dios. </div>
<div id="Ezr_9_1" style="display:none;" class="ver_select"><b>Ezr 9:1</b>  Y acabadas estas cosas, los príncipes vinieron a mí, diciendo: El pueblo de Israel, y los sacerdotes y levitas, no se han apartado de los pueblos de las tierras, de los cananeos, heteos, ferezeos, jebuseos, amonitas, y moabitas, egipcios, y amorreos, y hacen conforme a sus abominaciones. </div>
<div id="Ezr_9_2" style="display:none;" class="ver_select"><b>Ezr 9:2</b>  Porque han tomado de sus hijas para sí y para sus hijos, y la simiente santa ha sido mezclada con los pueblos de las tierras; y la mano de los príncipes y de los gobernadores ha sido la primera en esta prevaricación. </div>
<div id="Ezr_9_3" style="display:none;" class="ver_select"><b>Ezr 9:3</b>  Lo cual oyendo yo, rasgué mi vestidura y mi manto, y arranqué pelo de mi cabeza y de mi barba, y me senté atónito. </div>
<div id="Ezr_9_4" style="display:none;" class="ver_select"><b>Ezr 9:4</b>  Y se reunieron delante mí todos los que temblaban ante las palabras del Dios de Israel, a causa de la prevaricación de los del cautiverio; y yo quedé atónito hasta el sacrificio de la tarde. </div>
<div id="Ezr_9_5" style="display:none;" class="ver_select"><b>Ezr 9:5</b>  Y a la hora del sacrificio de la tarde me levanté de mi aflicción; y habiendo rasgado mi vestidura y mi manto, me postré de rodillas, y extendí mis manos a Jehová mi Dios, </div>
<div id="Ezr_9_6" style="display:none;" class="ver_select"><b>Ezr 9:6</b>  y dije: Dios mío, confuso y avergonzado estoy para levantar, oh Dios mío, mi rostro a ti; porque nuestras iniquidades se han multiplicado sobre nuestra cabeza, y nuestros delitos han crecido hasta el cielo. </div>
<div id="Ezr_9_7" style="display:none;" class="ver_select"><b>Ezr 9:7</b>  Desde los días de nuestros padres hasta este día estamos en gran pecado; y por nuestras iniquidades nosotros, nuestros reyes, y nuestros sacerdotes, hemos sido entregados en manos de los reyes de las tierras, a espada, a cautiverio, a robo, y a confusión de rostro, como en este día. </div>
<div id="Ezr_9_8" style="display:none;" class="ver_select"><b>Ezr 9:8</b>  Y ahora por un breve momento se mostró la gracia de Jehová nuestro Dios, para hacer que nos quedase un remanente libre, y para darnos estaca en su lugar santo, a fin de alumbrar nuestros ojos nu.estro Dios y darnos un poco de vida en nuestra servidumbre. </div>
<div id="Ezr_9_9" style="display:none;" class="ver_select"><b>Ezr 9:9</b>  Porque siervos éramos; mas en nuestra servidumbre no nos desamparó nuestro Dios, antes extendió sobre nosotros su misericordia delante de los reyes de Persia, para que se nos diese vida para levantar la casa de nuestro Dios, y para restaurar sus ruinas, y para darnos muros en Judá y en Jerusalén. </div>
<div id="Ezr_9_10" style="display:none;" class="ver_select"><b>Ezr 9:10</b>  Mas ahora, ¿qué diremos, oh Dios nuestro, después de esto? porque nosotros hemos dejado tus mandamientos, </div>
<div id="Ezr_9_11" style="display:none;" class="ver_select"><b>Ezr 9:11</b>  los cuales prescribiste por medio de tus siervos los profetas, diciendo: La tierra a la cual entráis para poseerla, tierra inmunda es a causa de la inmundicia de los pueblos de aquellas regiones, por las abominaciones de que la han llenado de uno a otro extremo con su inmundicia. </div>
<div id="Ezr_9_12" style="display:none;" class="ver_select"><b>Ezr 9:12</b>  Ahora, pues, no daréis vuestras hijas a los hijos de ellos, ni sus hijas tomaréis para vuestros hijos, ni procuraréis su paz ni su bien para siempre; para que seáis fuertes, y comáis el bien de la tierra, y la dejéis por heredad a vuestros hijos para siempre. </div>
<div id="Ezr_9_13" style="display:none;" class="ver_select"><b>Ezr 9:13</b>  Mas después de todo lo que nos ha sobrevenido a causa de nuestras malas obras, y a causa de nuestro grande delito, ya que tú eres nuestro Dios, nos has castigado menos de lo que nuestras iniquidades merecieron, y nos has dado tan grande liberación: </div>
<div id="Ezr_9_14" style="display:none;" class="ver_select"><b>Ezr 9:14</b>  ¿Hemos de volver a infringir tus mandamientos, y a emparentar con los pueblos de estas abominaciones? ¿No te ensañarías contra nosotros hasta consumirnos, sin que quedara remanente ni quien escape? </div>
<div id="Ezr_9_15" style="display:none;" class="ver_select"><b>Ezr 9:15</b>  Jehová, Dios de Israel, tú eres justo; porque hemos quedado un remanente que ha escapado, como en este día, henos aquí delante de ti en nuestros delitos; porque no es posible estar en tu presencia a causa de esto. </div>
<div id="Ezr_10_1" style="display:none;" class="ver_select"><b>Ezr 10:1</b>  Y orando Esdras y confesando, llorando y postrándose delante de la casa de Dios, se juntó a él una muy grande multitud de Israel, hombres, mujeres y niños; y lloraba el pueblo con gran llanto. </div>
<div id="Ezr_10_2" style="display:none;" class="ver_select"><b>Ezr 10:2</b>  Entonces respondió Secanías hijo de Jehiel, de los hijos Elam, y dijo a Esdras: Nosotros hemos prevaricado contra nuestro Dios, pues tomamos esposas extranjeras de los pueblos de la tierra; pero aún hay esperanza para Israel sobre esto. </div>
<div id="Ezr_10_3" style="display:none;" class="ver_select"><b>Ezr 10:3</b>  Ahora, pues, hagamos pacto con nuestro Dios, que echaremos a todas las esposas extranjeras y a los nacidos de ellas, según el consejo de mi señor y de los que tiemblan ante el mandamiento de nuestro Dios; y hágase conforme a la ley. </div>
<div id="Ezr_10_4" style="display:none;" class="ver_select"><b>Ezr 10:4</b>  Levántate, porque a ti toca este asunto, y nosotros seremos contigo; esfuérzate, y ponlo por obra. </div>
<div id="Ezr_10_5" style="display:none;" class="ver_select"><b>Ezr 10:5</b>  Entonces se levantó Esdras, e hizo jurar a los príncipes de los sacerdotes y de los levitas, y a todo Israel, que harían conforme a esto; y ellos juraron. </div>
<div id="Ezr_10_6" style="display:none;" class="ver_select"><b>Ezr 10:6</b>  Se levantó luego Esdras de delante de la casa de Dios, y fue a la cámara de Johanán hijo de Eliasib; y llegado allí, no comió pan ni bebió agua, porque se entristeció a causa de la prevaricación de los de la cautividad. </div>
<div id="Ezr_10_7" style="display:none;" class="ver_select"><b>Ezr 10:7</b>  E hicieron pasar pregón por Judá y por Jerusalén a todos los hijos de la cautividad, que se juntasen en Jerusalén: </div>
<div id="Ezr_10_8" style="display:none;" class="ver_select"><b>Ezr 10:8</b>  Y que el que no viniese en un lapso de tres días, conforme al acuerdo de los príncipes y de los ancianos, perdiese toda su hacienda, y él fuese apartado de la congregación de aquellos que habían sido llevados en cautiverio. </div>
<div id="Ezr_10_9" style="display:none;" class="ver_select"><b>Ezr 10:9</b>  Así todos los hombres de Judá y de Benjamín se reunieron en Jerusalén dentro de los tres días, a los veinte del mes, el cual era el mes noveno; y se sentó todo el pueblo en la plaza de la casa de Dios, temblando con motivo de aquel asunto, y también por causa de la intensa lluvia. </div>
<div id="Ezr_10_10" style="display:none;" class="ver_select"><b>Ezr 10:10</b>  Y se levantó Esdras el sacerdote, y les dijo: Vosotros habéis prevaricado, por cuanto tomasteis esposas extranjeras, añadiendo así sobre el pecado de Israel. </div>
<div id="Ezr_10_11" style="display:none;" class="ver_select"><b>Ezr 10:11</b>  Ahora, pues, dad gloria a Jehová Dios de vuestros padres, y haced su voluntad, y apartaos de los pueblos de las tierras, y de las esposas extranjeras. </div>
<div id="Ezr_10_12" style="display:none;" class="ver_select"><b>Ezr 10:12</b>  Entonces toda la congregación respondió, y dijo en alta voz: Así se haga conforme a tu palabra. </div>
<div id="Ezr_10_13" style="display:none;" class="ver_select"><b>Ezr 10:13</b>  Mas el pueblo es mucho, y el tiempo lluvioso, y no podemos permanecer afuera; ni la obra es de un día ni de dos, porque somos muchos los que hemos prevaricado en esto. </div>
<div id="Ezr_10_14" style="display:none;" class="ver_select"><b>Ezr 10:14</b>  Dejad ahora que se queden nuestros príncipes, los de toda la congregación; y todos aquellos que en nuestras ciudades hubieren tomado esposas extranjeras, vengan en tiempos determinados, y con ellos los ancianos de cada ciudad, y los jueces de ellas, hasta que apartemos de nosotros el furor de la ira de nuestro Dios sobre esto. </div>
<div id="Ezr_10_15" style="display:none;" class="ver_select"><b>Ezr 10:15</b>  Solamente Jonatán hijo de Asael, y Jahazías hijo de Ticva fueron puestos sobre este asunto; y Mesulam y Sabetai, levitas, les ayudaron. </div>
<div id="Ezr_10_16" style="display:none;" class="ver_select"><b>Ezr 10:16</b>  E hicieron así los hijos de la cautividad. Y fueron apartados Esdras el sacerdote, y los varones jefes de familias en la casa de sus padres, todos ellos por sus nombres, se sentaron el primer día del mes décimo para inquirir el asunto. </div>
<div id="Ezr_10_17" style="display:none;" class="ver_select"><b>Ezr 10:17</b>  Y concluyeron, con todos aquellos que habían tomado esposas extranjeras, al primer día del mes primero. </div>
<div id="Ezr_10_18" style="display:none;" class="ver_select"><b>Ezr 10:18</b>  Y de los hijos de los sacerdotes que habían tomado esposas extranjeras, fueron hallados estos: De los hijos de Jesúa hijo de Josadac, y de sus hermanos: Maasías, Eliezer, Jarib y Gedalías; </div>
<div id="Ezr_10_19" style="display:none;" class="ver_select"><b>Ezr 10:19</b>  Y dieron su mano en promesa de echar a sus esposas extranjeras, y siendo culpables ofrecieron un carnero de los rebaños por su delito. </div>
<div id="Ezr_10_20" style="display:none;" class="ver_select"><b>Ezr 10:20</b>  Y de los hijos de Imer: Hanani y Zebadías. </div>
<div id="Ezr_10_21" style="display:none;" class="ver_select"><b>Ezr 10:21</b>  Y de los hijos de Harim, Maasías, Elías, Semaías, Jehiel y Uzías. </div>
<div id="Ezr_10_22" style="display:none;" class="ver_select"><b>Ezr 10:22</b>  Y de los hijos de Pasur: Elioenai, Maasías, Ismael, Natanael, Jozabad y Elasa. </div>
<div id="Ezr_10_23" style="display:none;" class="ver_select"><b>Ezr 10:23</b>  Y de los hijos de los levitas: Jozabad, Simeí, Kelaía (éste es Kelita), Petaías, Judá y Eliezer. </div>
<div id="Ezr_10_24" style="display:none;" class="ver_select"><b>Ezr 10:24</b>  Y de los cantores, Eliasib; y de los porteros: Selum, Telem y Uri. </div>
<div id="Ezr_10_25" style="display:none;" class="ver_select"><b>Ezr 10:25</b>  Asimismo de Israel: De los hijos de Paros: Ramía, Izías, Malquías, Miamín, Eleazar, Malquías y  Benaía. </div>
<div id="Ezr_10_26" style="display:none;" class="ver_select"><b>Ezr 10:26</b>  Y de los hijos de Elam: Matanías, Zacarías, Jehiel, Abdi, Jerimot y Elías. </div>
<div id="Ezr_10_27" style="display:none;" class="ver_select"><b>Ezr 10:27</b>  Y de los hijos de Zatu: Elioenai, Eliasib, Matanías, Jerimot, Zabad y Aziza. </div>
<div id="Ezr_10_28" style="display:none;" class="ver_select"><b>Ezr 10:28</b>  Y de los hijos de Bebai: Johanán, Hananías, Zabai y Atlai. </div>
<div id="Ezr_10_29" style="display:none;" class="ver_select"><b>Ezr 10:29</b>  Y de los hijos de Bani: Mesulam, Maluc, Adaías, Jasub, Seal y Ramot. </div>
<div id="Ezr_10_30" style="display:none;" class="ver_select"><b>Ezr 10:30</b>  Y de los hijos de Pahat-moab: Adna, Queleal, Benaía, Maasías, Matanías, Bezaleel, Binúi y Manasés. </div>
<div id="Ezr_10_31" style="display:none;" class="ver_select"><b>Ezr 10:31</b>  Y de los hijos de Harim: Eliezer, Isías, Malquías, Semaías, Simeón, </div>
<div id="Ezr_10_32" style="display:none;" class="ver_select"><b>Ezr 10:32</b>  Benjamín, Maluc y Semarías. </div>
<div id="Ezr_10_33" style="display:none;" class="ver_select"><b>Ezr 10:33</b>  De los hijos de Hasum: Matenai, Matata, Zabad, Elifelet, Jeremai, Manasés y Simeí. </div>
<div id="Ezr_10_34" style="display:none;" class="ver_select"><b>Ezr 10:34</b>  De los hijos de Bani: Maadi, Amram, Uel, </div>
<div id="Ezr_10_35" style="display:none;" class="ver_select"><b>Ezr 10:35</b>  Benaía, Bedías, Quelúhi, </div>
<div id="Ezr_10_36" style="display:none;" class="ver_select"><b>Ezr 10:36</b>  Vanías, Meremot, Eliasib, </div>
<div id="Ezr_10_37" style="display:none;" class="ver_select"><b>Ezr 10:37</b>  Matanías, Matenai, Jaasai, </div>
<div id="Ezr_10_38" style="display:none;" class="ver_select"><b>Ezr 10:38</b>  Bani, Binúi, Simeí, </div>
<div id="Ezr_10_39" style="display:none;" class="ver_select"><b>Ezr 10:39</b>  Selemías, Natán, Adaías, </div>
<div id="Ezr_10_40" style="display:none;" class="ver_select"><b>Ezr 10:40</b>  Macnadbai, Sasai, Sarai, </div>
<div id="Ezr_10_41" style="display:none;" class="ver_select"><b>Ezr 10:41</b>  Azareel, Selemías, Semarías, </div>
<div id="Ezr_10_42" style="display:none;" class="ver_select"><b>Ezr 10:42</b>  Salum, Amarías y José. </div>
<div id="Ezr_10_43" style="display:none;" class="ver_select"><b>Ezr 10:43</b>  Y de los hijos de Nebo: Jeiel, Matatías, Zabad, Zebina, Jadau, Joel y Benaía. </div>
<div id="Ezr_10_44" style="display:none;" class="ver_select"><b>Ezr 10:44</b>  Todos estos habían tomado esposas extranjeras; y algunos de ellos tenían esposas que les habían dado hijos. </div>
