<div id="Hab_1_1" style="display:none;" class="ver_select"><b>Hab 1:1</b>  La carga que vio Habacuc profeta. </div>
<div id="Hab_1_2" style="display:none;" class="ver_select"><b>Hab 1:2</b>  ¿Hasta cuándo, oh Jehová, clamaré, y no oirás; y daré voces a ti a causa de la violencia, y no salvarás? </div>
<div id="Hab_1_3" style="display:none;" class="ver_select"><b>Hab 1:3</b>  ¿Por qué me haces ver iniquidad, y haces que mire molestia, y saqueo y violencia delante de mí, habiendo además quien levante pleito y contienda? </div>
<div id="Hab_1_4" style="display:none;" class="ver_select"><b>Hab 1:4</b>  Por lo cual la ley es debilitada, y el juicio no sale verdadero; por cuanto el impío asedia al justo, por eso sale torcido el juicio. </div>
<div id="Hab_1_5" style="display:none;" class="ver_select"><b>Hab 1:5</b>  Mirad en las naciones, y ved, y maravillaos y asombraos; porque haré una obra en vuestros días, que aun cuando se os contare, no la creeréis. </div>
<div id="Hab_1_6" style="display:none;" class="ver_select"><b>Hab 1:6</b>  Porque he aquí, yo levanto a los caldeos, gente amarga y presurosa, que camina por la anchura de la tierra para poseer las habitaciones ajenas. </div>
<div id="Hab_1_7" style="display:none;" class="ver_select"><b>Hab 1:7</b>  Espantosa es y terrible; de ella misma saldrá su derecho y su grandeza. </div>
<div id="Hab_1_8" style="display:none;" class="ver_select"><b>Hab 1:8</b>  Y sus caballos serán más ligeros que leopardos, y más feroces que lobos nocturnos; y sus jinetes se multiplicarán; vendrán de lejos sus caballeros, y volarán como águila que se apresura a la comida. </div>
<div id="Hab_1_9" style="display:none;" class="ver_select"><b>Hab 1:9</b>  Toda ella vendrá a la presa; sus rostros hacia adelante como el viento solano; y recogerá cautivos como arena. </div>
<div id="Hab_1_10" style="display:none;" class="ver_select"><b>Hab 1:10</b>  Y escarnecerá a los reyes, y de los príncipes hará burla; se reirá de toda fortaleza, y levantará terraplén, y la tomará. </div>
<div id="Hab_1_11" style="display:none;" class="ver_select"><b>Hab 1:11</b>  Luego cambiará de parecer, y pasará adelante, y ofenderá atribuyendo este su poder a su dios. </div>
<div id="Hab_1_12" style="display:none;" class="ver_select"><b>Hab 1:12</b>  ¿No eres tú desde el principio, oh Jehová, Dios mío, Santo mío? ¡No moriremos! Oh Jehová, para juicio lo pusiste; y tú, oh Roca, lo fundaste para castigar. </div>
<div id="Hab_1_13" style="display:none;" class="ver_select"><b>Hab 1:13</b>  Muy limpio eres de ojos para ver el mal,  y no puedes ver el agravio. ¿Por qué, pues, ves a los traidores, y callas cuando el impío destruye al más justo que él, </div>
<div id="Hab_1_14" style="display:none;" class="ver_select"><b>Hab 1:14</b>  y haces que sean los hombres como los peces del mar, como reptiles que no tienen señor? </div>
<div id="Hab_1_15" style="display:none;" class="ver_select"><b>Hab 1:15</b>  Sacará a todos con anzuelo, los atrapará con su red, y los juntará en su malla; por lo cual se gozará y hará alegrías. </div>
<div id="Hab_1_16" style="display:none;" class="ver_select"><b>Hab 1:16</b>  Por esto hará sacrificios a su red, y quemará incienso a sus mallas; porque con ellos engordó su porción, y engrasó su comida. </div>
<div id="Hab_1_17" style="display:none;" class="ver_select"><b>Hab 1:17</b>  ¿Vaciará por eso su red, o tendrá piedad de matar gentes continuamente? </div>
<div id="Hab_2_1" style="display:none;" class="ver_select"><b>Hab 2:1</b>  Sobre mi guarda estaré, y sobre la fortaleza estaré firme; y velaré para ver qué habrá de decirme, y qué habré de responder cuando yo sea reprendido. </div>
<div id="Hab_2_2" style="display:none;" class="ver_select"><b>Hab 2:2</b>  Y Jehová me respondió, y dijo: Escribe la visión, y declárala en tablas, para que corra el que leyere en ella. </div>
<div id="Hab_2_3" style="display:none;" class="ver_select"><b>Hab 2:3</b>  Aunque la visión tardará aún por tiempo, mas al fin hablará, y no mentirá; aunque se tardare, espéralo, que sin duda vendrá; no tardará. </div>
<div id="Hab_2_4" style="display:none;" class="ver_select"><b>Hab 2:4</b>  He aquí se enorgullece aquel cuya alma no es recta en él; mas el justo por su fe vivirá. </div>
<div id="Hab_2_5" style="display:none;" class="ver_select"><b>Hab 2:5</b>  Y también, por cuanto peca por el vino, es un hombre soberbio, y no queda en casa; el cual ensancha como el infierno su alma, y es como la muerte, que no se sacia; antes reúne para sí todas las naciones, y amontona para sí todos los pueblos. </div>
<div id="Hab_2_6" style="display:none;" class="ver_select"><b>Hab 2:6</b>  ¿No han de levantar todos éstos refrán sobre él, y sarcasmos contra él? Y dirán: ¡Ay del que multiplicó lo que no era suyo! Y, ¿hasta cuándo había de amontonar sobre sí barro espeso? </div>
<div id="Hab_2_7" style="display:none;" class="ver_select"><b>Hab 2:7</b>  ¿No se levantarán de repente los que te han de morder, y se despertarán los que te han de quitar de tu lugar, y serás a ellos por rapiña? </div>
<div id="Hab_2_8" style="display:none;" class="ver_select"><b>Hab 2:8</b>  Porque tú has despojado a muchas naciones, todos los que han quedado de los pueblos te despojarán; a causa de la sangre de los hombres, y de la violencia de la tierra, de las ciudades y de todos los que moran en ellas. </div>
<div id="Hab_2_9" style="display:none;" class="ver_select"><b>Hab 2:9</b>  ¡Ay del que codicia ganancia deshonesta para su casa, para poner en alto su nido, para ser librado del poder del mal! </div>
<div id="Hab_2_10" style="display:none;" class="ver_select"><b>Hab 2:10</b>  Tomaste consejo vergonzoso para tu casa, asolaste muchos pueblos, y has pecado contra tu alma. </div>
<div id="Hab_2_11" style="display:none;" class="ver_select"><b>Hab 2:11</b>  Porque la piedra clamará desde el muro, y la tabla del enmaderado le responderá. </div>
<div id="Hab_2_12" style="display:none;" class="ver_select"><b>Hab 2:12</b>  ¡Ay del que edifica la ciudad con sangre, y del que funda una ciudad con iniquidad! </div>
<div id="Hab_2_13" style="display:none;" class="ver_select"><b>Hab 2:13</b>  ¿No es esto de Jehová de los ejércitos? Los pueblos pues, trabajarán para el fuego, y las gentes se fatigarán en vano. </div>
<div id="Hab_2_14" style="display:none;" class="ver_select"><b>Hab 2:14</b>  Porque la tierra será llena del conocimiento de la gloria de Jehová, como las aguas cubren el mar. </div>
<div id="Hab_2_15" style="display:none;" class="ver_select"><b>Hab 2:15</b>  ¡Ay del que da de beber a su compañero! ¡Ay de ti que le acercas tu odre y le embriagas, para mirar su desnudez! </div>
<div id="Hab_2_16" style="display:none;" class="ver_select"><b>Hab 2:16</b>  Te has llenado de deshonra más que de honra; bebe tú también, y serás descubierto; el cáliz de la mano derecha de Jehová volverá sobre ti, y vómito de afrenta sobre tu gloria. </div>
<div id="Hab_2_17" style="display:none;" class="ver_select"><b>Hab 2:17</b>  Porque la rapiña del Líbano caerá sobre ti, y la destrucción de las fieras lo quebrantará; a causa de la sangre de los hombres, y de la violencia de la tierra, de las ciudades, y de todos los que moran en ellas. </div>
<div id="Hab_2_18" style="display:none;" class="ver_select"><b>Hab 2:18</b>  ¿De qué sirve la escultura que esculpió el que la hizo? ¿La estatua de fundición, que enseña mentira, para que haciendo imágenes mudas confíe el hacedor en su obra? </div>
<div id="Hab_2_19" style="display:none;" class="ver_select"><b>Hab 2:19</b>  ¡Ay del que dice al palo; Despiértate; y a la piedra muda: Levántate! ¿Podrá él enseñar? He aquí él está cubierto de oro y plata, y no hay espíritu dentro de él. </div>
<div id="Hab_2_20" style="display:none;" class="ver_select"><b>Hab 2:20</b>  Mas Jehová está en su santo templo; calle delante de Él toda la tierra. </div>
<div id="Hab_3_1" style="display:none;" class="ver_select"><b>Hab 3:1</b>  Oración de Habacuc profeta, sobre Sigionot. </div>
<div id="Hab_3_2" style="display:none;" class="ver_select"><b>Hab 3:2</b>  Oh Jehová, he oído tu palabra, y temí: Oh Jehová, aviva tu obra en medio de los tiempos, en medio de los tiempos hazla conocer; En la ira acuérdate de la misericordia. </div>
<div id="Hab_3_3" style="display:none;" class="ver_select"><b>Hab 3:3</b>  Dios viene de Temán, y el Santo del monte de Parán (Selah). Su gloria cubrió los cielos, y la tierra se llenó de su alabanza. </div>
<div id="Hab_3_4" style="display:none;" class="ver_select"><b>Hab 3:4</b>  Su resplandor era como la luz, y cuernos salían de su mano; allí estaba escondido su poder. </div>
<div id="Hab_3_5" style="display:none;" class="ver_select"><b>Hab 3:5</b>  Delante de su rostro iba mortandad, y a sus pies salían carbones encendidos. </div>
<div id="Hab_3_6" style="display:none;" class="ver_select"><b>Hab 3:6</b>  Se paró, y midió la tierra; miró, e hizo temblar las naciones; y los montes antiguos fueron desmenuzados, los collados antiguos se humillaron. Sus caminos son eternos. </div>
<div id="Hab_3_7" style="display:none;" class="ver_select"><b>Hab 3:7</b>  He visto las tiendas de Cusán en aflicción; las tiendas de la tierra de Madián temblaron. </div>
<div id="Hab_3_8" style="display:none;" class="ver_select"><b>Hab 3:8</b>  ¿Se airó Jehová contra los ríos? ¿Contra los ríos fue tu enojo? ¿Tu ira contra el mar, cuando subiste sobre tus caballos, y sobre tus carros de salvación? </div>
<div id="Hab_3_9" style="display:none;" class="ver_select"><b>Hab 3:9</b>  Se descubrió enteramente tu arco, los juramentos a las tribus, palabra segura (Selah). Hendiste la tierra con ríos. </div>
<div id="Hab_3_10" style="display:none;" class="ver_select"><b>Hab 3:10</b>  Te vieron, y tuvieron temor los montes; pasó la inundación de las aguas; el abismo dio su voz, y a lo alto alzó sus manos. </div>
<div id="Hab_3_11" style="display:none;" class="ver_select"><b>Hab 3:11</b>  El sol y la luna se pararon en su estancia; a la luz de tus saetas anduvieron, y al resplandor de tu fulgente lanza. </div>
<div id="Hab_3_12" style="display:none;" class="ver_select"><b>Hab 3:12</b>  Con ira hollaste la tierra, con furor trillaste las naciones. </div>
<div id="Hab_3_13" style="display:none;" class="ver_select"><b>Hab 3:13</b>  Saliste para salvar a tu pueblo, para salvar con tu ungido. Traspasaste la cabeza de la casa del impío, desnudando el cimiento hasta el cuello (Selah). </div>
<div id="Hab_3_14" style="display:none;" class="ver_select"><b>Hab 3:14</b>  Horadaste con sus propias varas las cabezas de sus villas, que como tempestad acometieron para dispersarme; su regocijo era como para devorar al pobre encubiertamente. </div>
<div id="Hab_3_15" style="display:none;" class="ver_select"><b>Hab 3:15</b>  Hiciste camino en el mar a tus caballos, por montón de grandes aguas. </div>
<div id="Hab_3_16" style="display:none;" class="ver_select"><b>Hab 3:16</b>  Oí, y se conmovieron mis entrañas; a la voz temblaron mis labios; pudrición entró en mis huesos, y dentro de mí me estremecí; si bien estaré quieto en el día de la angustia, cuando suba al pueblo el que lo invadirá con sus tropas. </div>
<div id="Hab_3_17" style="display:none;" class="ver_select"><b>Hab 3:17</b>  Aunque la higuera no florezca, ni haya fruto en las vides; aunque falte el fruto del olivo, y los labrados no den mantenimiento; y las ovejas sean quitadas del redil, y no haya vacas en los corrales; </div>
<div id="Hab_3_18" style="display:none;" class="ver_select"><b>Hab 3:18</b>  con todo, yo me alegraré en Jehová, y me gozaré en el Dios de mi salvación. </div>
<div id="Hab_3_19" style="display:none;" class="ver_select"><b>Hab 3:19</b>  Jehová el Señor es mi fortaleza, Él hará mis pies como de ciervas, y me hará andar sobre mis alturas. (Al principal de los cantores, sobre mis instrumentos de cuerdas) </div>
