<div id="Hag_1_1" style="display:none;" class="ver_select"><b>Hag 1:1</b>  En el año segundo del rey Darío en el mes sexto, en el primer día del mes, vino palabra de Jehová, por medio del profeta Hageo, a Zorobabel hijo de Salatiel, gobernador de Judá, y a Josué hijo de Josadac, el sumo sacerdote, diciendo: </div>
<div id="Hag_1_2" style="display:none;" class="ver_select"><b>Hag 1:2</b>  Así habla Jehová de los ejércitos, diciendo: Este pueblo dice: El tiempo aún no ha venido, el tiempo de que la casa de Jehová sea reedificada. </div>
<div id="Hag_1_3" style="display:none;" class="ver_select"><b>Hag 1:3</b>  Vino, pues, palabra de Jehová por medio del profeta Hageo, diciendo: </div>
<div id="Hag_1_4" style="display:none;" class="ver_select"><b>Hag 1:4</b>  ¿Es para vosotros tiempo, para vosotros, de morar en vuestras casas artesonadas, y esta casa está desierta? </div>
<div id="Hag_1_5" style="display:none;" class="ver_select"><b>Hag 1:5</b>  Pues así dice Jehová de los ejércitos: Considerad vuestros caminos. </div>
<div id="Hag_1_6" style="display:none;" class="ver_select"><b>Hag 1:6</b>  Sembráis mucho, y encerráis poco; coméis, y no os saciáis; bebéis, y no estáis satisfechos; os vestís, y no os calentáis; y el que trabaja a jornal recibe su jornal en saco horadado. </div>
<div id="Hag_1_7" style="display:none;" class="ver_select"><b>Hag 1:7</b>  Así dice Jehová de los ejércitos: Considerad vuestros caminos. </div>
<div id="Hag_1_8" style="display:none;" class="ver_select"><b>Hag 1:8</b>  Subid al monte, y traed madera, y reedificad la casa; y pondré en ella, mi voluntad, y seré glorificado, dice Jehová. </div>
<div id="Hag_1_9" style="display:none;" class="ver_select"><b>Hag 1:9</b>  Buscáis mucho, y halláis poco; y encerráis en casa, y soplo en ello. ¿Por qué? dice Jehová de los ejércitos. Por cuanto mi casa está desierta, y cada uno de vosotros corre a su propia casa. </div>
<div id="Hag_1_10" style="display:none;" class="ver_select"><b>Hag 1:10</b>  Por eso se detuvo de los cielos sobre vosotros la lluvia, y la tierra detuvo sus frutos. </div>
<div id="Hag_1_11" style="display:none;" class="ver_select"><b>Hag 1:11</b>  Y llamé la sequía sobre esta tierra, y sobre los montes, y sobre el trigo, y sobre el vino, y sobre el aceite, y sobre todo lo que la tierra produce, y sobre los hombres y sobre el ganado, y sobre todo trabajo de manos. </div>
<div id="Hag_1_12" style="display:none;" class="ver_select"><b>Hag 1:12</b>  Y oyó Zorobabel hijo de Salatiel, y Josué hijo de Josadac, el sumo sacerdote, y todo el resto del pueblo, la voz de Jehová su Dios, y las palabras del profeta Hageo, como lo había enviado Jehová el Dios de ellos; y temió el pueblo delante de Jehová. </div>
<div id="Hag_1_13" style="display:none;" class="ver_select"><b>Hag 1:13</b>  Entonces Hageo, mensajero de Jehová, habló el mensaje de Jehová al pueblo, diciendo: Yo estoy con vosotros, dice Jehová. </div>
<div id="Hag_1_14" style="display:none;" class="ver_select"><b>Hag 1:14</b>  Y despertó Jehová el espíritu de Zorobabel hijo de Salatiel, gobernador de Judá, y el espíritu de Josué hijo de Josadac, sumo sacerdote, y el espíritu de todo el resto del pueblo; y vinieron y trabajaron en la casa de Jehová de los ejércitos, su Dios, </div>
<div id="Hag_1_15" style="display:none;" class="ver_select"><b>Hag 1:15</b>  en el día veinticuatro del mes sexto, en el segundo año del rey Darío. </div>
<div id="Hag_2_1" style="display:none;" class="ver_select"><b>Hag 2:1</b>  En el mes séptimo, a los veintiún días del mes, vino palabra de Jehová por medio del profeta Hageo, diciendo: </div>
<div id="Hag_2_2" style="display:none;" class="ver_select"><b>Hag 2:2</b>  Habla ahora a Zorobabel hijo de Salatiel, gobernador de Judá, y a Josué hijo de Josadac, sumo sacerdote, y al resto del pueblo, diciendo: </div>
<div id="Hag_2_3" style="display:none;" class="ver_select"><b>Hag 2:3</b>  ¿Quién ha quedado entre vosotros que haya visto esta casa en su primera gloria? ¿Y cómo la veis ahora? ¿No es ella como nada delante de vuestros ojos? </div>
<div id="Hag_2_4" style="display:none;" class="ver_select"><b>Hag 2:4</b>  Pues ahora, Zorobabel, esfuérzate, dice Jehová; esfuérzate también, Josué, hijo de Josadac, sumo sacerdote; y esforzaos, pueblo todo de la tierra, dice Jehová, y trabajad; porque yo estoy con vosotros, dice Jehová de los ejércitos. </div>
<div id="Hag_2_5" style="display:none;" class="ver_select"><b>Hag 2:5</b>  Según el pacto que hice con vosotros cuando salisteis de Egipto, así mi Espíritu estará en medio de vosotros: no temáis. </div>
<div id="Hag_2_6" style="display:none;" class="ver_select"><b>Hag 2:6</b>  Porque así dice Jehová de los ejércitos: De aquí a poco aún yo haré temblar los cielos y la tierra, y el mar y la tierra seca; </div>
<div id="Hag_2_7" style="display:none;" class="ver_select"><b>Hag 2:7</b>  y haré temblar a todas las naciones, y vendrá el Deseado de todas las naciones; y llenaré de gloria esta casa, dice Jehová de los ejércitos. </div>
<div id="Hag_2_8" style="display:none;" class="ver_select"><b>Hag 2:8</b>  Mía es la plata, y mío es el oro, dice Jehová de los ejércitos. </div>
<div id="Hag_2_9" style="display:none;" class="ver_select"><b>Hag 2:9</b>  La gloria de esta casa postrera será mayor que la de la primera, dice Jehová de los ejércitos; y daré paz en este lugar, dice Jehová de los ejércitos. </div>
<div id="Hag_2_10" style="display:none;" class="ver_select"><b>Hag 2:10</b>  El día veinticuatro del noveno mes, en el segundo año de Darío, vino palabra de Jehová por medio del profeta Hageo, diciendo: </div>
<div id="Hag_2_11" style="display:none;" class="ver_select"><b>Hag 2:11</b>  Así dice Jehová de los ejércitos: Pregunta ahora a los sacerdotes acerca de la ley, diciendo: </div>
<div id="Hag_2_12" style="display:none;" class="ver_select"><b>Hag 2:12</b>  Si llevare alguno las carnes santificadas en el extremo de su vestidura, y con el extremo de ella tocare pan, o vianda, o vino, o aceite, o cualquier otra comida, ¿será santificada? Y respondieron los sacerdotes, y dijeron: No. </div>
<div id="Hag_2_13" style="display:none;" class="ver_select"><b>Hag 2:13</b>  Y dijo Hageo: Si un inmundo a causa de cuerpo muerto tocare alguna cosa de éstas, ¿será inmunda? Y respondieron los sacerdotes, y dijeron: Inmunda será. </div>
<div id="Hag_2_14" style="display:none;" class="ver_select"><b>Hag 2:14</b>  Y respondió Hageo y dijo: Así es este pueblo, y esta nación delante de mí, dice Jehová; y así es toda obra de sus manos; y todo lo que aquí ofrecen es inmundo. </div>
<div id="Hag_2_15" style="display:none;" class="ver_select"><b>Hag 2:15</b>  Ahora, pues, Considerad esto en vuestro corazón desde este día en adelante, antes que pongáis piedra sobre piedra en el templo de Jehová. </div>
<div id="Hag_2_16" style="display:none;" class="ver_select"><b>Hag 2:16</b>  Antes que fuesen estas cosas, venían al montón de veinte, y había diez; venían al lagar para sacar cincuenta cántaros del lagar, y había veinte. </div>
<div id="Hag_2_17" style="display:none;" class="ver_select"><b>Hag 2:17</b>  Os herí con viento solano, y con tizoncillo, y con granizo en toda obra de vuestras manos; mas no os convertisteis a mí, dice Jehová. </div>
<div id="Hag_2_18" style="display:none;" class="ver_select"><b>Hag 2:18</b>  Considerad, pues, ahora en vuestro corazón desde este día en adelante, desde el día veinticuatro del noveno mes, desde el día que se echó el cimiento del templo de Jehová; Consideradlo. </div>
<div id="Hag_2_19" style="display:none;" class="ver_select"><b>Hag 2:19</b>  ¿Todavía está la semilla en el granero? Si bien, la vid, la higuera, el granado y el árbol del olivo no han florecido todavía; mas desde este día os daré bendición. </div>
<div id="Hag_2_20" style="display:none;" class="ver_select"><b>Hag 2:20</b>  Y vino otra vez palabra de Jehová a Hageo, el día veinticuatro del mes, diciendo: </div>
<div id="Hag_2_21" style="display:none;" class="ver_select"><b>Hag 2:21</b>  Habla a Zorobabel, gobernador de Judá, diciendo: Yo haré temblar los cielos y la tierra; </div>
<div id="Hag_2_22" style="display:none;" class="ver_select"><b>Hag 2:22</b>  y trastornaré el trono de los reinos, y destruiré la fuerza del reino de las naciones; y trastornaré el carro, y los que en él suben; y vendrán abajo los caballos y los que en ellos montan, cada cual por la espada de su hermano. </div>
<div id="Hag_2_23" style="display:none;" class="ver_select"><b>Hag 2:23</b>  En aquel día, dice Jehová de los ejércitos, te tomaré, oh Zorobabel, hijo de Salatiel, siervo mío, dice Jehová, y te pondré como anillo de sellar; porque yo te escogí, dice Jehová de los ejércitos. </div>
