<div id="Heb_1_1" style="display:none;" class="ver_select"><b>Heb 1:1</b>  Dios, habiendo hablado muchas veces y en muchas maneras en otro tiempo a los padres por los profetas, </div>
<div id="Heb_1_2" style="display:none;" class="ver_select"><b>Heb 1:2</b>  en estos postreros días nos ha hablado por su Hijo, a quien constituyó heredero de todo, por quien asimismo hizo el universo; </div>
<div id="Heb_1_3" style="display:none;" class="ver_select"><b>Heb 1:3</b>  el cual, siendo el resplandor de su gloria, y la imagen misma de su sustancia, y quien sustenta todas las cosas con la palabra de su poder, habiendo hecho la expiación de nuestros pecados por sí mismo, se sentó a la diestra de la Majestad en las alturas, </div>
<div id="Heb_1_4" style="display:none;" class="ver_select"><b>Heb 1:4</b>  hecho tanto más superior que los ángeles, cuanto heredó más excelente nombre que ellos. </div>
<div id="Heb_1_5" style="display:none;" class="ver_select"><b>Heb 1:5</b>  Porque ¿a cuál de los ángeles dijo Dios jamás: Mi Hijo eres tú, yo te he engendrado hoy, y otra vez: Yo seré a Él Padre, y Él me será a mí Hijo? </div>
<div id="Heb_1_6" style="display:none;" class="ver_select"><b>Heb 1:6</b>  Y otra vez, cuando introduce al Primogénito en el mundo, dice: Y adórenle todos los ángeles de Dios. </div>
<div id="Heb_1_7" style="display:none;" class="ver_select"><b>Heb 1:7</b>  Y ciertamente de los ángeles dice: El que hace a sus ángeles espíritus, y a sus ministros llama de fuego. </div>
<div id="Heb_1_8" style="display:none;" class="ver_select"><b>Heb 1:8</b>  Mas al Hijo dice: Tu trono, oh Dios, por siempre jamás: Cetro de equidad es el cetro de tu reino. </div>
<div id="Heb_1_9" style="display:none;" class="ver_select"><b>Heb 1:9</b>  Has amado la justicia, y aborrecido la maldad; Por tanto Dios, el Dios tuyo, te ha ungido con óleo de alegría más que a tus compañeros. </div>
<div id="Heb_1_10" style="display:none;" class="ver_select"><b>Heb 1:10</b>  Y: Tú, Señor, en el principio fundaste la tierra, y los cielos son obra de tus manos: </div>
<div id="Heb_1_11" style="display:none;" class="ver_select"><b>Heb 1:11</b>  Ellos perecerán, mas tú permaneces; y todos ellos se envejecerán como una vestidura; </div>
<div id="Heb_1_12" style="display:none;" class="ver_select"><b>Heb 1:12</b>  y como un manto los envolverás, y serán mudados; pero tú eres el mismo, y tus años no acabarán. </div>
<div id="Heb_1_13" style="display:none;" class="ver_select"><b>Heb 1:13</b>  Y, ¿a cuál de los ángeles dijo jamás: Siéntate a mi diestra, hasta que ponga a tus enemigos por estrado de tus pies? </div>
<div id="Heb_1_14" style="display:none;" class="ver_select"><b>Heb 1:14</b>  ¿No son todos espíritus ministradores, enviados para servicio a favor de los que serán herederos de salvación? </div>
<div id="Heb_2_1" style="display:none;" class="ver_select"><b>Heb 2:1</b>  Por tanto, es necesario que con más diligencia atendamos a las cosas que hemos oído, no sea que nos deslicemos. </div>
<div id="Heb_2_2" style="display:none;" class="ver_select"><b>Heb 2:2</b>  Porque si la palabra dicha por los ángeles fue firme, y toda transgresión y desobediencia recibió justa retribución, </div>
<div id="Heb_2_3" style="display:none;" class="ver_select"><b>Heb 2:3</b>  ¿cómo escaparemos nosotros, si tuviéremos en poco una salvación tan grande? La cual, habiendo sido publicada primeramente por el Señor, nos fue confirmada por los que le oyeron; </div>
<div id="Heb_2_4" style="display:none;" class="ver_select"><b>Heb 2:4</b>  testificando Dios juntamente con ellos, con señales y prodigios y diversos milagros, y dones del Espíritu Santo según su voluntad. </div>
<div id="Heb_2_5" style="display:none;" class="ver_select"><b>Heb 2:5</b>  Porque no sujetó a los ángeles el mundo venidero, del cual hablamos; </div>
<div id="Heb_2_6" style="display:none;" class="ver_select"><b>Heb 2:6</b>  pero alguien testificó en cierto lugar, diciendo: ¿Qué es el hombre, para que te acuerdes de él, o el hijo del hombre, para que le visites? </div>
<div id="Heb_2_7" style="display:none;" class="ver_select"><b>Heb 2:7</b>  Le hiciste un poco menor que los ángeles, le coronaste de gloria y de honra, y le pusiste sobre las obras de tus manos. </div>
<div id="Heb_2_8" style="display:none;" class="ver_select"><b>Heb 2:8</b>  Todo lo sujetaste bajo sus pies. Porque en cuanto le sujetó todas las cosas, nada dejó que no sea sujeto a Él; mas aún no vemos que todas las cosas le sean sujetas. </div>
<div id="Heb_2_9" style="display:none;" class="ver_select"><b>Heb 2:9</b>  Pero vemos a Jesús coronado de gloria y de honra, el cual fue hecho un poco menor que los ángeles, por el padecimiento de su muerte, para que por la gracia de Dios gustase la muerte por todos. </div>
<div id="Heb_2_10" style="display:none;" class="ver_select"><b>Heb 2:10</b>  Porque le era preciso a Aquél por cuya causa son todas las cosas y por quien todas las cosas subsisten, habiendo de llevar a la gloria a muchos hijos, perfeccionar por aflicciones al autor de la salvación de ellos. </div>
<div id="Heb_2_11" style="display:none;" class="ver_select"><b>Heb 2:11</b>  Porque el que santifica y los que son santificados, de uno son todos; por lo cual no se avergüenza de llamarlos hermanos, </div>
<div id="Heb_2_12" style="display:none;" class="ver_select"><b>Heb 2:12</b>  diciendo: Anunciaré tu nombre a mis hermanos, en medio de la iglesia te alabaré. </div>
<div id="Heb_2_13" style="display:none;" class="ver_select"><b>Heb 2:13</b>  Y otra vez: Yo en Él pondré mi confianza. Y otra vez: He aquí, yo y los hijos que Dios me dio. </div>
<div id="Heb_2_14" style="display:none;" class="ver_select"><b>Heb 2:14</b>  Así que, por cuanto los hijos participaron de carne y sangre, Él también participó de lo mismo, para destruir por medio de la muerte al que tenía el imperio de la muerte, esto es, al diablo, </div>
<div id="Heb_2_15" style="display:none;" class="ver_select"><b>Heb 2:15</b>  y librar a los que por el temor de la muerte estaban durante toda la vida sujetos a servidumbre. </div>
<div id="Heb_2_16" style="display:none;" class="ver_select"><b>Heb 2:16</b>  Porque ciertamente no tomó para sí la naturaleza de los ángeles, sino que tomó la de la simiente de Abraham. </div>
<div id="Heb_2_17" style="display:none;" class="ver_select"><b>Heb 2:17</b>  Por cuanto le era preciso ser en todo semejante a sus hermanos, para venir a ser misericordioso y fiel Sumo Sacerdote en lo que a Dios se refiere, para expiar los pecados del pueblo. </div>
<div id="Heb_2_18" style="display:none;" class="ver_select"><b>Heb 2:18</b>  Porque en cuanto Él mismo padeció siendo tentado, es poderoso para socorrer a los que son tentados. </div>
<div id="Heb_3_1" style="display:none;" class="ver_select"><b>Heb 3:1</b>  Por tanto, hermanos santos, participantes del llamamiento celestial, considerad al Apóstol y Sumo Sacerdote de nuestra profesión, Cristo Jesús; </div>
<div id="Heb_3_2" style="display:none;" class="ver_select"><b>Heb 3:2</b>  el cual fue fiel al que le constituyó, como también lo fue Moisés sobre toda su casa. </div>
<div id="Heb_3_3" style="display:none;" class="ver_select"><b>Heb 3:3</b>  Porque de tanto mayor gloria que Moisés Éste es estimado digno, cuanto tiene mayor dignidad que la casa el que la edificó. </div>
<div id="Heb_3_4" style="display:none;" class="ver_select"><b>Heb 3:4</b>  Porque toda casa es edificada por alguno; mas el que creó todas las cosas es Dios. </div>
<div id="Heb_3_5" style="display:none;" class="ver_select"><b>Heb 3:5</b>  Y Moisés a la verdad fue fiel sobre toda su casa, como siervo, para testimonio de lo que después se había de decir; </div>
<div id="Heb_3_6" style="display:none;" class="ver_select"><b>Heb 3:6</b>  pero Cristo, como hijo sobre su casa; la cual casa somos nosotros, si retenemos firme hasta el fin la confianza y la gloria de la esperanza. </div>
<div id="Heb_3_7" style="display:none;" class="ver_select"><b>Heb 3:7</b>  Por lo cual, como dice el Espíritu Santo: Si oyereis hoy su voz, </div>
<div id="Heb_3_8" style="display:none;" class="ver_select"><b>Heb 3:8</b>  no endurezcáis vuestros corazones, como en la provocación, en el día de la tentación en el desierto, </div>
<div id="Heb_3_9" style="display:none;" class="ver_select"><b>Heb 3:9</b>  donde me tentaron vuestros padres; me probaron, y vieron mis obras cuarenta años. </div>
<div id="Heb_3_10" style="display:none;" class="ver_select"><b>Heb 3:10</b>  A causa de lo cual me disgusté con aquella generación, y dije: Siempre divagan ellos de corazón, y no han conocido mis caminos. </div>
<div id="Heb_3_11" style="display:none;" class="ver_select"><b>Heb 3:11</b>  Así que, juré yo en mi ira: No entrarán en mi reposo. </div>
<div id="Heb_3_12" style="display:none;" class="ver_select"><b>Heb 3:12</b>  Mirad, hermanos, que en ninguno de vosotros haya corazón malo de incredulidad para apartarse del Dios vivo; </div>
<div id="Heb_3_13" style="display:none;" class="ver_select"><b>Heb 3:13</b>  antes exhortaos los unos a los otros cada día, entre tanto que se dice: Hoy; para que ninguno de vosotros se endurezca por el engaño del pecado. </div>
<div id="Heb_3_14" style="display:none;" class="ver_select"><b>Heb 3:14</b>  Porque somos hechos participantes de Cristo, si retenemos firme hasta el fin el principio de nuestra confianza; </div>
<div id="Heb_3_15" style="display:none;" class="ver_select"><b>Heb 3:15</b>  entre tanto que se dice: Si oyereis hoy su voz, no endurezcáis vuestros corazones, como en la provocación. </div>
<div id="Heb_3_16" style="display:none;" class="ver_select"><b>Heb 3:16</b>  Porque algunos de los que habían salido de Egipto con Moisés, habiendo oído, provocaron, aunque no todos. </div>
<div id="Heb_3_17" style="display:none;" class="ver_select"><b>Heb 3:17</b>  Mas ¿con quiénes estuvo enojado cuarenta años? ¿No fue con los que pecaron, cuyos cuerpos cayeron en el desierto? </div>
<div id="Heb_3_18" style="display:none;" class="ver_select"><b>Heb 3:18</b>  ¿Y a quiénes juró que no entrarían en su reposo, sino a aquellos que no creyeron? </div>
<div id="Heb_3_19" style="display:none;" class="ver_select"><b>Heb 3:19</b>  Y vemos que no pudieron entrar a causa de incredulidad. </div>
<div id="Heb_4_1" style="display:none;" class="ver_select"><b>Heb 4:1</b>  Temamos, pues, que quedando aún la promesa de entrar en su reposo, alguno de vosotros parezca no haberlo alcanzado. </div>
<div id="Heb_4_2" style="display:none;" class="ver_select"><b>Heb 4:2</b>  Porque también a nosotros se nos ha predicado el evangelio como a ellos; pero no les aprovechó la palabra predicada a los que la oyeron al no mezclarla con fe. </div>
<div id="Heb_4_3" style="display:none;" class="ver_select"><b>Heb 4:3</b>  Pero nosotros que hemos creído entramos en el reposo, de la manera que Él dijo: Por tanto juré en mi ira: No entrarán en mi reposo; aunque sus obras fueron acabadas desde el principio del mundo. </div>
<div id="Heb_4_4" style="display:none;" class="ver_select"><b>Heb 4:4</b>  Porque en cierto lugar dijo así del séptimo día: Y reposó Dios de todas sus obras en el séptimo día. </div>
<div id="Heb_4_5" style="display:none;" class="ver_select"><b>Heb 4:5</b>  Y otra vez aquí: No entrarán en mi reposo. </div>
<div id="Heb_4_6" style="display:none;" class="ver_select"><b>Heb 4:6</b>  Así que, puesto que falta que algunos entren en él, y aquellos a quienes primero fue predicado no entraron por causa de incredulidad, </div>
<div id="Heb_4_7" style="display:none;" class="ver_select"><b>Heb 4:7</b>  otra vez determina un cierto día, diciendo por medio de David: Hoy, después de tanto tiempo; como está dicho: Si oyereis hoy su voz, no endurezcáis vuestros corazones. </div>
<div id="Heb_4_8" style="display:none;" class="ver_select"><b>Heb 4:8</b>  Porque si Jesús les hubiera dado el reposo, no hablaría después de otro día. </div>
<div id="Heb_4_9" style="display:none;" class="ver_select"><b>Heb 4:9</b>  Por tanto, queda un reposo para el pueblo de Dios. </div>
<div id="Heb_4_10" style="display:none;" class="ver_select"><b>Heb 4:10</b>  Porque el que ha entrado en su reposo, también ha reposado de sus obras, como Dios de las suyas. </div>
<div id="Heb_4_11" style="display:none;" class="ver_select"><b>Heb 4:11</b>  Procuremos, pues, entrar en aquel reposo; que ninguno caiga en semejante ejemplo de incredulidad. </div>
<div id="Heb_4_12" style="display:none;" class="ver_select"><b>Heb 4:12</b>  Porque la palabra de Dios es viva y eficaz, y más penetrante que toda espada de dos filos, y penetra hasta partir el alma y el espíritu, y las coyunturas y los tuétanos, y discierne los pensamientos y las intenciones del corazón. </div>
<div id="Heb_4_13" style="display:none;" class="ver_select"><b>Heb 4:13</b>  Y no hay cosa creada que no sea manifiesta en su presencia; antes todas las cosas están desnudas y abiertas a los ojos de Aquél a quien tenemos que dar cuenta. </div>
<div id="Heb_4_14" style="display:none;" class="ver_select"><b>Heb 4:14</b>  Por tanto, teniendo un gran Sumo Sacerdote, que traspasó los cielos, Jesús el Hijo de Dios, retengamos nuestra profesión. </div>
<div id="Heb_4_15" style="display:none;" class="ver_select"><b>Heb 4:15</b>  Porque no tenemos un Sumo Sacerdote que no pueda compadecerse de nuestras flaquezas; sino uno que fue tentado en todo según nuestra semejanza, pero sin pecado. </div>
<div id="Heb_4_16" style="display:none;" class="ver_select"><b>Heb 4:16</b>  Acerquémonos, pues, confiadamente al trono de la gracia, para alcanzar misericordia y hallar gracia para el oportuno socorro. </div>
<div id="Heb_5_1" style="display:none;" class="ver_select"><b>Heb 5:1</b>  Porque todo sumo sacerdote tomado de entre los hombres, es constituido a favor de los hombres en lo que a Dios se refiere, para que presente también ofrendas y sacrificios por los pecados; </div>
<div id="Heb_5_2" style="display:none;" class="ver_select"><b>Heb 5:2</b>  que pueda compadecerse de los ignorantes y extraviados, puesto que él también está rodeado de flaqueza; </div>
<div id="Heb_5_3" style="display:none;" class="ver_select"><b>Heb 5:3</b>  y por causa de ella debe ofrecer por los pecados, tanto por el pueblo, como también por sí mismo. </div>
<div id="Heb_5_4" style="display:none;" class="ver_select"><b>Heb 5:4</b>  Y nadie toma para sí esta honra, sino el que es llamado de Dios, como lo fue Aarón. </div>
<div id="Heb_5_5" style="display:none;" class="ver_select"><b>Heb 5:5</b>  Así también Cristo no se glorificó a sí mismo haciéndose Sumo Sacerdote, sino el que le dijo: Tú eres mi Hijo, yo te he engendrado hoy; </div>
<div id="Heb_5_6" style="display:none;" class="ver_select"><b>Heb 5:6</b>  como también dice en otro lugar: Tú eres sacerdote para siempre, según el orden de Melquisedec. </div>
<div id="Heb_5_7" style="display:none;" class="ver_select"><b>Heb 5:7</b>  El cual en los días de su carne, habiendo ofrecido ruegos y súplicas con gran clamor y lágrimas al que le podía librar de la muerte, fue oído por su temor reverente. </div>
<div id="Heb_5_8" style="display:none;" class="ver_select"><b>Heb 5:8</b>  Y aunque era Hijo, por lo que padeció aprendió la obediencia; </div>
<div id="Heb_5_9" style="display:none;" class="ver_select"><b>Heb 5:9</b>  y habiendo sido hecho perfecto, vino a ser autor de eterna salvación a todos los que le obedecen; </div>
<div id="Heb_5_10" style="display:none;" class="ver_select"><b>Heb 5:10</b>  y fue llamado de Dios Sumo Sacerdote según el orden de Melquisedec. </div>
<div id="Heb_5_11" style="display:none;" class="ver_select"><b>Heb 5:11</b>  Del cual tenemos mucho que decir, y difícil de describir, por cuanto sois tardos para oír. </div>
<div id="Heb_5_12" style="display:none;" class="ver_select"><b>Heb 5:12</b>  Porque debiendo ser ya maestros, por causa del tiempo, tenéis necesidad de que se os vuelva enseñar cuáles son los primeros rudimentos de las palabras de Dios; y habéis llegado a ser tales que tenéis necesidad de leche, y no de alimento sólido. </div>
<div id="Heb_5_13" style="display:none;" class="ver_select"><b>Heb 5:13</b>  Y todo el que participa de la leche es inhábil en la palabra de la justicia, porque es niño; </div>
<div id="Heb_5_14" style="display:none;" class="ver_select"><b>Heb 5:14</b>  mas el alimento sólido es para los que han alcanzado madurez, para los que por el uso tienen los sentidos ejercitados en el discernimiento del bien y el mal. </div>
<div id="Heb_6_1" style="display:none;" class="ver_select"><b>Heb 6:1</b>  Por tanto, dejando los rudimentos de la doctrina de Cristo, vamos adelante a la perfección; no echando otra vez el fundamento del arrepentimiento de obras muertas, y de la fe en Dios, </div>
<div id="Heb_6_2" style="display:none;" class="ver_select"><b>Heb 6:2</b>  de la doctrina de bautismos, y de la imposición de manos, y de la resurrección de los muertos, y del juicio eterno. </div>
<div id="Heb_6_3" style="display:none;" class="ver_select"><b>Heb 6:3</b>  Y esto haremos a la verdad, si Dios lo permite. </div>
<div id="Heb_6_4" style="display:none;" class="ver_select"><b>Heb 6:4</b>  Porque es imposible que los que una vez fueron iluminados y gustaron el don celestial, y fueron hechos partícipes del Espíritu Santo, </div>
<div id="Heb_6_5" style="display:none;" class="ver_select"><b>Heb 6:5</b>  y asimismo gustaron la buena palabra de Dios, y los poderes del mundo venidero, </div>
<div id="Heb_6_6" style="display:none;" class="ver_select"><b>Heb 6:6</b>  y recayeron, sean otra vez renovados para arrepentimiento, crucificando de nuevo para sí mismos al Hijo de Dios y exponiéndole a vituperio. </div>
<div id="Heb_6_7" style="display:none;" class="ver_select"><b>Heb 6:7</b>  Porque la tierra que bebe la lluvia que muchas veces cae sobre ella, y produce hierba provechosa a aquellos por los cuales es labrada, recibe bendición de Dios; </div>
<div id="Heb_6_8" style="display:none;" class="ver_select"><b>Heb 6:8</b>  pero la que produce espinos y abrojos es reprobada, y cercana a ser maldecida; y su fin es el ser quemada. </div>
<div id="Heb_6_9" style="display:none;" class="ver_select"><b>Heb 6:9</b>  Pero en cuanto a vosotros, oh amados, estamos persuadidos de cosas mejores y que acompañan la salvación, aunque hablamos así. </div>
<div id="Heb_6_10" style="display:none;" class="ver_select"><b>Heb 6:10</b>  Porque Dios no es injusto para olvidar vuestra obra y el trabajo de amor que habéis mostrado a su nombre, habiendo ministrado a los santos y ministrándoles aún. </div>
<div id="Heb_6_11" style="display:none;" class="ver_select"><b>Heb 6:11</b>  Y deseamos que cada uno de vosotros muestre la misma diligencia hasta el fin, para la plena certeza de la esperanza: </div>
<div id="Heb_6_12" style="display:none;" class="ver_select"><b>Heb 6:12</b>  Que no os hagáis perezosos, sino que sigáis el ejemplo de aquellos que por la fe y la paciencia heredan las promesas. </div>
<div id="Heb_6_13" style="display:none;" class="ver_select"><b>Heb 6:13</b>  Porque cuando Dios hizo la promesa a Abraham, no pudiendo jurar por otro mayor, juró por sí mismo, </div>
<div id="Heb_6_14" style="display:none;" class="ver_select"><b>Heb 6:14</b>  diciendo: Ciertamente bendiciendo te bendeciré, y multiplicando te multiplicaré. </div>
<div id="Heb_6_15" style="display:none;" class="ver_select"><b>Heb 6:15</b>  Y así, esperando con paciencia, alcanzó la promesa. </div>
<div id="Heb_6_16" style="display:none;" class="ver_select"><b>Heb 6:16</b>  Porque los hombres ciertamente juran por el que es mayor; y el juramento para confirmación es para ellos el fin de toda controversia. </div>
<div id="Heb_6_17" style="display:none;" class="ver_select"><b>Heb 6:17</b>  Por lo cual, queriendo Dios mostrar más abundantemente a los herederos de la promesa la inmutabilidad de su consejo, lo confirmó con juramento; </div>
<div id="Heb_6_18" style="display:none;" class="ver_select"><b>Heb 6:18</b>  para que por dos cosas inmutables, en las cuales, es imposible que Dios mienta, tengamos un fortísimo consuelo, los que nos hemos refugiado asiéndonos de la esperanza puesta delante de nosotros. </div>
<div id="Heb_6_19" style="display:none;" class="ver_select"><b>Heb 6:19</b>  La cual tenemos como ancla del alma, segura y firme, y que penetra hasta dentro del velo; </div>
<div id="Heb_6_20" style="display:none;" class="ver_select"><b>Heb 6:20</b>  donde entró por nosotros Jesús, nuestro precursor, hecho Sumo Sacerdote para siempre según el orden de Melquisedec. </div>
<div id="Heb_7_1" style="display:none;" class="ver_select"><b>Heb 7:1</b>  Porque este Melquisedec, rey de Salem, sacerdote del Dios Altísimo, el cual salió a recibir a Abraham que volvía de la matanza de los reyes, y le bendijo, </div>
<div id="Heb_7_2" style="display:none;" class="ver_select"><b>Heb 7:2</b>  a quien asimismo dio Abraham los diezmos de todo; cuyo nombre significa primeramente Rey de justicia, y luego también Rey de Salem, que es, Rey de paz; </div>
<div id="Heb_7_3" style="display:none;" class="ver_select"><b>Heb 7:3</b>  sin padre, sin madre, sin genealogía; que ni tiene principio de días, ni fin de vida, sino hecho semejante al Hijo de Dios, permanece sacerdote para siempre. </div>
<div id="Heb_7_4" style="display:none;" class="ver_select"><b>Heb 7:4</b>  Considerad, pues, cuán grande era Éste, a quien aun Abraham el patriarca dio el diezmo de los despojos. </div>
<div id="Heb_7_5" style="display:none;" class="ver_select"><b>Heb 7:5</b>  Y ciertamente los que de entre los hijos de Leví reciben el sacerdocio, tienen mandamiento de tomar del pueblo los diezmos según la ley, es decir, de sus hermanos aunque también éstos hayan salido de los lomos de Abraham. </div>
<div id="Heb_7_6" style="display:none;" class="ver_select"><b>Heb 7:6</b>  Mas Aquél cuya genealogía no es contada entre ellos, tomó de Abraham los diezmos, y bendijo al que tenía las promesas. </div>
<div id="Heb_7_7" style="display:none;" class="ver_select"><b>Heb 7:7</b>  Y sin contradicción alguna, el menor es bendecido por el mayor. </div>
<div id="Heb_7_8" style="display:none;" class="ver_select"><b>Heb 7:8</b>  Y aquí ciertamente los hombres mortales toman los diezmos; pero allí, uno de quien se da testimonio de que vive. </div>
<div id="Heb_7_9" style="display:none;" class="ver_select"><b>Heb 7:9</b>  Y por decirlo así, también Leví, que recibe los diezmos, pagó diezmos en Abraham; </div>
<div id="Heb_7_10" style="display:none;" class="ver_select"><b>Heb 7:10</b>  porque aún estaba en los lomos de su padre cuando Melquisedec le salió al encuentro. </div>
<div id="Heb_7_11" style="display:none;" class="ver_select"><b>Heb 7:11</b>  Así que, si la perfección fuera por el sacerdocio levítico (porque bajo él recibió el pueblo la ley) ¿qué necesidad había aún de que se levantase otro sacerdote según el orden de Melquisedec, y que no fuese llamado según el orden de Aarón? </div>
<div id="Heb_7_12" style="display:none;" class="ver_select"><b>Heb 7:12</b>  Pues mudado el sacerdocio, necesario es que se haga también mudanza de la ley; </div>
<div id="Heb_7_13" style="display:none;" class="ver_select"><b>Heb 7:13</b>  porque Aquél de quien se dicen estas cosas, de otra tribu es, de la cual nadie atendió al altar. </div>
<div id="Heb_7_14" style="display:none;" class="ver_select"><b>Heb 7:14</b>  Porque manifiesto es que nuestro Señor nació de Judá, de cuya tribu nada habló Moisés tocante al sacerdocio. </div>
<div id="Heb_7_15" style="display:none;" class="ver_select"><b>Heb 7:15</b>  Y aun es mucho más manifiesto, si a semejanza de Melquisedec se levanta un sacerdote diferente; </div>
<div id="Heb_7_16" style="display:none;" class="ver_select"><b>Heb 7:16</b>  el cual no es hecho conforme a la ley del mandamiento carnal, sino según el poder de una vida que no tiene fin. </div>
<div id="Heb_7_17" style="display:none;" class="ver_select"><b>Heb 7:17</b>  Porque Él testifica: Tú eres sacerdote para siempre, según el orden de Melquisedec. </div>
<div id="Heb_7_18" style="display:none;" class="ver_select"><b>Heb 7:18</b>  Porque ciertamente el mandamiento precedente es abrogado por su debilidad e ineficacia. </div>
<div id="Heb_7_19" style="display:none;" class="ver_select"><b>Heb 7:19</b>  Porque la ley nada perfeccionó; mas lo hizo la introducción de mejor esperanza, por la cual nos acercamos a Dios. </div>
<div id="Heb_7_20" style="display:none;" class="ver_select"><b>Heb 7:20</b>  Y tanto más en cuanto no sin juramento fue hecho Él sacerdote; </div>
<div id="Heb_7_21" style="display:none;" class="ver_select"><b>Heb 7:21</b>  porque los otros ciertamente sin juramento fueron hechos sacerdotes; pero Éste, con juramento por Aquél que le dijo: Juró el Señor, y no se arrepentirá: Tú eres sacerdote para siempre según el orden de Melquisedec. </div>
<div id="Heb_7_22" style="display:none;" class="ver_select"><b>Heb 7:22</b>  Por tanto, Jesús es hecho fiador de un mejor testamento. </div>
<div id="Heb_7_23" style="display:none;" class="ver_select"><b>Heb 7:23</b>  Y los otros ciertamente fueron muchos sacerdotes, ya que por causa de la muerte no podían permanecer; </div>
<div id="Heb_7_24" style="display:none;" class="ver_select"><b>Heb 7:24</b>  mas Éste, por cuanto permanece para siempre, tiene un sacerdocio inmutable; </div>
<div id="Heb_7_25" style="display:none;" class="ver_select"><b>Heb 7:25</b>  por lo cual puede también salvar perpetuamente a los que por Él se acercan a Dios, viviendo siempre para interceder por ellos. </div>
<div id="Heb_7_26" style="display:none;" class="ver_select"><b>Heb 7:26</b>  Porque tal Sumo Sacerdote nos convenía; santo, inocente, limpio, apartado de los pecadores, y hecho más sublime que los cielos; </div>
<div id="Heb_7_27" style="display:none;" class="ver_select"><b>Heb 7:27</b>  que no tuviese necesidad cada día, como los otros sumos sacerdotes, de ofrecer primero sacrificios por sus propios pecados, y luego por los del pueblo; porque esto lo hizo una sola vez, ofreciéndose a sí mismo. </div>
<div id="Heb_7_28" style="display:none;" class="ver_select"><b>Heb 7:28</b>  Porque la ley constituye sumos sacerdotes a hombres débiles; mas la palabra del juramento, posterior a la ley, constituye al Hijo, quien es perfecto para siempre. </div>
<div id="Heb_8_1" style="display:none;" class="ver_select"><b>Heb 8:1</b>  Así que, la suma de lo que hemos dicho es: Tenemos tal Sumo Sacerdote el cual está sentado a la diestra del trono de la Majestad en los cielos; </div>
<div id="Heb_8_2" style="display:none;" class="ver_select"><b>Heb 8:2</b>  ministro del santuario, y del verdadero tabernáculo que el Señor levantó, y no el hombre. </div>
<div id="Heb_8_3" style="display:none;" class="ver_select"><b>Heb 8:3</b>  Porque todo sumo sacerdote es constituido para presentar ofrendas y sacrificios; por lo cual es necesario que también Éste tenga algo que ofrecer. </div>
<div id="Heb_8_4" style="display:none;" class="ver_select"><b>Heb 8:4</b>  Porque si Él estuviese sobre la tierra, ni siquiera sería sacerdote, habiendo aún sacerdotes que presentan ofrendas según la ley; </div>
<div id="Heb_8_5" style="display:none;" class="ver_select"><b>Heb 8:5</b>  los cuales sirven de ejemplo y sombra de las cosas celestiales, como fue advertido por Dios a Moisés cuando estaba por comenzar el tabernáculo: Mira, dice, haz todas las cosas conforme al modelo que te ha sido mostrado en el monte. </div>
<div id="Heb_8_6" style="display:none;" class="ver_select"><b>Heb 8:6</b>  Mas ahora tanto mejor ministerio es el suyo, por cuanto Él es el mediador de un mejor testamento, que ha sido establecido sobre mejores promesas. </div>
<div id="Heb_8_7" style="display:none;" class="ver_select"><b>Heb 8:7</b>  Porque si aquel primer pacto hubiera sido sin falta, no se hubiera procurado lugar para el segundo. </div>
<div id="Heb_8_8" style="display:none;" class="ver_select"><b>Heb 8:8</b>  Porque hallando falta en ellos, dice: He aquí vienen días, dice el Señor, cuando estableceré con la casa de Israel y con la casa de Judá un nuevo pacto; </div>
<div id="Heb_8_9" style="display:none;" class="ver_select"><b>Heb 8:9</b>  No como el pacto que hice con sus padres el día que los tomé por la mano para sacarlos de la tierra de Egipto: Porque ellos no permanecieron en mi pacto, y yo los desatendí, dice el Señor. </div>
<div id="Heb_8_10" style="display:none;" class="ver_select"><b>Heb 8:10</b>  Porque éste es el pacto que haré con la casa de Israel, después de aquellos días, dice el Señor: Pondré mis leyes en sus mentes, y sobre sus corazones las escribiré; y seré a ellos por Dios, y ellos me serán a mí por pueblo: </div>
<div id="Heb_8_11" style="display:none;" class="ver_select"><b>Heb 8:11</b>  Y ninguno enseñará a su prójimo, ni ninguno a su hermano, diciendo: Conoce al Señor: Porque todos me conocerán, desde el menor de ellos hasta el mayor. </div>
<div id="Heb_8_12" style="display:none;" class="ver_select"><b>Heb 8:12</b>  Porque seré propicio a sus injusticias, y de sus pecados y de sus iniquidades no me acordaré más. </div>
<div id="Heb_8_13" style="display:none;" class="ver_select"><b>Heb 8:13</b>  Y al decir: Nuevo pacto, da por viejo al primero; y lo que es dado por viejo y se envejece, cerca está a desvanecerse. </div>
<div id="Heb_9_1" style="display:none;" class="ver_select"><b>Heb 9:1</b>  Ahora bien, el primer pacto tenía en verdad ordenanzas de servicio a Dios y un santuario terrenal. </div>
<div id="Heb_9_2" style="display:none;" class="ver_select"><b>Heb 9:2</b>  Porque el tabernáculo fue edificado así; la primera parte, en donde estaba el candelero, y la mesa, y los panes de la proposición; el cual es llamado el Santuario. </div>
<div id="Heb_9_3" style="display:none;" class="ver_select"><b>Heb 9:3</b>  Y tras el segundo velo estaba la parte del tabernáculo que es llamado el Lugar Santísimo; </div>
<div id="Heb_9_4" style="display:none;" class="ver_select"><b>Heb 9:4</b>  el cual tenía el incensario de oro, y el arca del pacto cubierta de todas partes alrededor de oro; en la que estaba una urna de oro que contenía el maná, y la vara de Aarón que reverdeció, y las tablas del pacto; </div>
<div id="Heb_9_5" style="display:none;" class="ver_select"><b>Heb 9:5</b>  y sobre ella los querubines de gloria que cubrían con su sombra el propiciatorio; cosas de las cuales no podemos ahora hablar en particular. </div>
<div id="Heb_9_6" style="display:none;" class="ver_select"><b>Heb 9:6</b>  Y cuando estas cosas fueron así ordenadas, los sacerdotes siempre entraban en la primera parte del tabernáculo para hacer los oficios del servicio a Dios; </div>
<div id="Heb_9_7" style="display:none;" class="ver_select"><b>Heb 9:7</b>  pero en la segunda parte, sólo el sumo sacerdote una vez al año, no sin sangre, la cual ofrecía por sí mismo, y por los pecados de ignorancia del pueblo. </div>
<div id="Heb_9_8" style="display:none;" class="ver_select"><b>Heb 9:8</b>  Dando en esto a entender el Espíritu Santo, que aún no estaba descubierto el camino al lugar santísimo, entre tanto que el primer tabernáculo estuviese en pie. </div>
<div id="Heb_9_9" style="display:none;" class="ver_select"><b>Heb 9:9</b>  Lo cual era figura de aquel tiempo presente, en el cual se presentaban ofrendas y sacrificios que no podían hacer perfecto, en cuanto a la conciencia, al que servía con ellos; </div>
<div id="Heb_9_10" style="display:none;" class="ver_select"><b>Heb 9:10</b>  ya que consistía sólo en comidas y bebidas, y en diversos lavamientos y ordenanzas acerca de la carne, que les fueron impuestas hasta el tiempo de la restauración. </div>
<div id="Heb_9_11" style="display:none;" class="ver_select"><b>Heb 9:11</b>  Mas estando ya presente Cristo, Sumo Sacerdote de los bienes que habían de venir, por el más amplio y más perfecto tabernáculo, no hecho de manos, es decir, no de esta creación; </div>
<div id="Heb_9_12" style="display:none;" class="ver_select"><b>Heb 9:12</b>  y no por sangre de machos cabríos ni de becerros, sino por su propia sangre, entró una sola vez en el lugar santísimo, habiendo obtenido eterna redención. </div>
<div id="Heb_9_13" style="display:none;" class="ver_select"><b>Heb 9:13</b>  Porque si la sangre de los toros y de los machos cabríos, y las cenizas de una becerra, rociadas a los inmundos santifican para la purificación de la carne, </div>
<div id="Heb_9_14" style="display:none;" class="ver_select"><b>Heb 9:14</b>  ¿cuánto más la sangre de Cristo, el cual mediante el Espíritu eterno se ofreció a sí mismo sin mancha a Dios, limpiará vuestras conciencias de obras muertas para que sirváis al Dios vivo? </div>
<div id="Heb_9_15" style="display:none;" class="ver_select"><b>Heb 9:15</b>  Y por causa de esto Él es mediador del nuevo testamento, para que interviniendo muerte para la redención de las transgresiones que había bajo el primer testamento, los llamados reciban la promesa de la herencia eterna. </div>
<div id="Heb_9_16" style="display:none;" class="ver_select"><b>Heb 9:16</b>  Porque donde hay testamento, necesario es que intervenga muerte del testador. </div>
<div id="Heb_9_17" style="display:none;" class="ver_select"><b>Heb 9:17</b>  Porque el testamento con la muerte es confirmado; de otra manera no tiene validez entre tanto que el testador vive. </div>
<div id="Heb_9_18" style="display:none;" class="ver_select"><b>Heb 9:18</b>  De donde ni aun el primer testamento fue consagrado sin sangre. </div>
<div id="Heb_9_19" style="display:none;" class="ver_select"><b>Heb 9:19</b>  Porque habiendo hablado Moisés todos los mandamientos de la ley a todo el pueblo, tomando la sangre de los becerros y de los machos cabríos, con agua, y lana de grana, e hisopo, roció al mismo libro, y también a todo el pueblo, </div>
<div id="Heb_9_20" style="display:none;" class="ver_select"><b>Heb 9:20</b>  diciendo: Ésta es la sangre del testamento que Dios os ha mandado. </div>
<div id="Heb_9_21" style="display:none;" class="ver_select"><b>Heb 9:21</b>  Y además de esto roció también con sangre el tabernáculo y todos los vasos del ministerio. </div>
<div id="Heb_9_22" style="display:none;" class="ver_select"><b>Heb 9:22</b>  Y casi todo es purificado según la ley con sangre; y sin derramamiento de sangre no hay remisión. </div>
<div id="Heb_9_23" style="display:none;" class="ver_select"><b>Heb 9:23</b>  Fue, pues, necesario que las figuras de las cosas celestiales fuesen purificadas con estas cosas; pero las cosas celestiales mismas, con mejores sacrificios que éstos. </div>
<div id="Heb_9_24" style="display:none;" class="ver_select"><b>Heb 9:24</b>  Porque no entró Cristo en el santuario hecho de mano, figura del verdadero, sino en el mismo cielo para presentarse ahora por nosotros en la presencia de Dios. </div>
<div id="Heb_9_25" style="display:none;" class="ver_select"><b>Heb 9:25</b>  Y no para ofrecerse muchas veces a sí mismo, como entra el sumo sacerdote en el lugar santísimo cada año con sangre ajena; </div>
<div id="Heb_9_26" style="display:none;" class="ver_select"><b>Heb 9:26</b>  de otra manera le hubiera sido necesario padecer muchas veces desde el principio del mundo; pero ahora en la consumación de los siglos, se presentó una sola vez por el sacrificio de sí mismo para quitar el pecado. </div>
<div id="Heb_9_27" style="display:none;" class="ver_select"><b>Heb 9:27</b>  Y de la manera que está establecido a los hombres que mueran una sola vez, y después de esto el juicio; </div>
<div id="Heb_9_28" style="display:none;" class="ver_select"><b>Heb 9:28</b>  Así también Cristo fue ofrecido una sola vez, para llevar los pecados de muchos; y aparecerá por segunda vez, sin relación con el pecado, para salvación de los que le esperan. </div>
<div id="Heb_10_1" style="display:none;" class="ver_select"><b>Heb 10:1</b>  Porque la ley, teniendo la sombra de los bienes venideros, no la imagen misma de las cosas, nunca puede, por los mismos sacrificios que se ofrecen continuamente cada año, hacer perfectos a los que se acercan. </div>
<div id="Heb_10_2" style="display:none;" class="ver_select"><b>Heb 10:2</b>  De otra manera cesarían de ofrecerse, ya que los adoradores, limpios una vez, no tendrían más conciencia de pecado. </div>
<div id="Heb_10_3" style="display:none;" class="ver_select"><b>Heb 10:3</b>  Pero en estos sacrificios cada año se hace memoria de los pecados. </div>
<div id="Heb_10_4" style="display:none;" class="ver_select"><b>Heb 10:4</b>  Porque la sangre de los toros y de los machos cabríos no puede quitar los pecados. </div>
<div id="Heb_10_5" style="display:none;" class="ver_select"><b>Heb 10:5</b>  Por lo cual, entrando en el mundo, dice: sacrificio y ofrenda no quisiste; Mas me preparaste cuerpo: </div>
<div id="Heb_10_6" style="display:none;" class="ver_select"><b>Heb 10:6</b>  Holocaustos y sacrificios por el pecado no te agradaron. </div>
<div id="Heb_10_7" style="display:none;" class="ver_select"><b>Heb 10:7</b>  Entonces dije: He aquí que vengo (en la cabecera del libro está escrito de mí) para hacer, oh Dios, tu voluntad. </div>
<div id="Heb_10_8" style="display:none;" class="ver_select"><b>Heb 10:8</b>  Diciendo arriba: Sacrificio y ofrenda, y holocaustos y expiaciones por el pecado no quisiste, ni te agradaron (cuyas cosas se ofrecen según la ley). </div>
<div id="Heb_10_9" style="display:none;" class="ver_select"><b>Heb 10:9</b>  Entonces dijo: He aquí que vengo para hacer, oh Dios, tu voluntad. Quita lo primero, para establecer lo postrero. </div>
<div id="Heb_10_10" style="display:none;" class="ver_select"><b>Heb 10:10</b>  En esa voluntad nosotros somos santificados, mediante la ofrenda del cuerpo de Jesucristo hecha una sola vez. </div>
<div id="Heb_10_11" style="display:none;" class="ver_select"><b>Heb 10:11</b>  Y ciertamente todo sacerdote se presenta cada día ministrando y ofreciendo muchas veces los mismos sacrificios, que nunca pueden quitar los pecados. </div>
<div id="Heb_10_12" style="display:none;" class="ver_select"><b>Heb 10:12</b>  Pero Éste, habiendo ofrecido por los pecados un solo sacrificio para siempre, se ha sentado a la diestra de Dios, </div>
<div id="Heb_10_13" style="display:none;" class="ver_select"><b>Heb 10:13</b>  de aquí en adelante esperando hasta que sus enemigos sean puestos por estrado de sus pies. </div>
<div id="Heb_10_14" style="display:none;" class="ver_select"><b>Heb 10:14</b>  Porque con una sola ofrenda hizo perfectos para siempre a los santificados. </div>
<div id="Heb_10_15" style="display:none;" class="ver_select"><b>Heb 10:15</b>  Y el Espíritu Santo también nos da testimonio; porque después que había dicho: </div>
<div id="Heb_10_16" style="display:none;" class="ver_select"><b>Heb 10:16</b>  Éste es el pacto que haré con ellos: Después de aquellos días, dice el Señor: Daré mis leyes en sus corazones, y en sus mentes las escribiré; </div>
<div id="Heb_10_17" style="display:none;" class="ver_select"><b>Heb 10:17</b>  y nunca más me acordaré de sus pecados e iniquidades. </div>
<div id="Heb_10_18" style="display:none;" class="ver_select"><b>Heb 10:18</b>  Pues donde hay remisión de éstos, no hay más ofrenda por el pecado. </div>
<div id="Heb_10_19" style="display:none;" class="ver_select"><b>Heb 10:19</b>  Así que, hermanos, teniendo libertad para entrar en el lugar santísimo por la sangre de Jesús, </div>
<div id="Heb_10_20" style="display:none;" class="ver_select"><b>Heb 10:20</b>  por el camino nuevo y vivo que Él nos consagró a través del velo, esto es, por su carne; </div>
<div id="Heb_10_21" style="display:none;" class="ver_select"><b>Heb 10:21</b>  y teniendo un gran sacerdote sobre la casa de Dios, </div>
<div id="Heb_10_22" style="display:none;" class="ver_select"><b>Heb 10:22</b>  acerquémonos con corazón sincero, en plena certidumbre de fe, purificados los corazones de mala conciencia, y lavados los cuerpos con agua pura. </div>
<div id="Heb_10_23" style="display:none;" class="ver_select"><b>Heb 10:23</b>  Mantengamos firme, sin fluctuar, la profesión de nuestra fe; que fiel es el que prometió; </div>
<div id="Heb_10_24" style="display:none;" class="ver_select"><b>Heb 10:24</b>  y considerémonos unos a otros para provocarnos al amor y a las buenas obras; </div>
<div id="Heb_10_25" style="display:none;" class="ver_select"><b>Heb 10:25</b>  no dejando nuestra congregación, como algunos tienen por costumbre, sino exhortándonos unos a otros; y tanto más, cuanto veis que aquel día se acerca. </div>
<div id="Heb_10_26" style="display:none;" class="ver_select"><b>Heb 10:26</b>  Porque si pecáremos voluntariamente después de haber recibido el conocimiento de la verdad, ya no queda más sacrificio por el pecado, </div>
<div id="Heb_10_27" style="display:none;" class="ver_select"><b>Heb 10:27</b>  sino una horrenda expectación de juicio y hervor de fuego que ha de devorar a los adversarios. </div>
<div id="Heb_10_28" style="display:none;" class="ver_select"><b>Heb 10:28</b>  El que menospreciare la ley de Moisés, por el testimonio de dos o de tres testigos muere sin ninguna misericordia. </div>
<div id="Heb_10_29" style="display:none;" class="ver_select"><b>Heb 10:29</b>  ¿De cuánto mayor castigo pensáis que será digno, el que pisoteare al Hijo de Dios, y tuviere por inmunda la sangre del pacto en la cual fue santificado, e hiciere afrenta al Espíritu de gracia? </div>
<div id="Heb_10_30" style="display:none;" class="ver_select"><b>Heb 10:30</b>  Pues conocemos al que dijo: Mía es la venganza, yo daré el pago, dice el Señor. Y otra vez: El Señor juzgará a su pueblo. </div>
<div id="Heb_10_31" style="display:none;" class="ver_select"><b>Heb 10:31</b>  Horrenda cosa es caer en manos del Dios vivo. </div>
<div id="Heb_10_32" style="display:none;" class="ver_select"><b>Heb 10:32</b>  Pero traed a la memoria los días pasados, en los cuales, después de haber sido iluminados, sufristeis gran combate de aflicciones; </div>
<div id="Heb_10_33" style="display:none;" class="ver_select"><b>Heb 10:33</b>  por una parte, ciertamente, con vituperios y tribulaciones fuisteis hechos espectáculo; y por otra parte fuisteis hechos compañeros de los que han estado en igual situación. </div>
<div id="Heb_10_34" style="display:none;" class="ver_select"><b>Heb 10:34</b>  Y os compadecisteis de mí en mis cadenas, y el despojo de vuestros bienes padecisteis con gozo, sabiendo en vosotros que tenéis una mejor y perdurable sustancia en los cielos. </div>
<div id="Heb_10_35" style="display:none;" class="ver_select"><b>Heb 10:35</b>  No perdáis, pues, vuestra confianza, que tiene grande galardón; </div>
<div id="Heb_10_36" style="display:none;" class="ver_select"><b>Heb 10:36</b>  porque la paciencia os es necesaria; para que habiendo hecho la voluntad de Dios, obtengáis la promesa. </div>
<div id="Heb_10_37" style="display:none;" class="ver_select"><b>Heb 10:37</b>  Porque aún un poco de tiempo, y el que ha de venir vendrá, y no tardará. </div>
<div id="Heb_10_38" style="display:none;" class="ver_select"><b>Heb 10:38</b>  Mas el justo vivirá por fe; y si retrocediere, no agradará a mi alma. </div>
<div id="Heb_10_39" style="display:none;" class="ver_select"><b>Heb 10:39</b>  Pero nosotros no somos de los que retroceden para perdición, sino de los que creen para salvación del alma. </div>
<div id="Heb_11_1" style="display:none;" class="ver_select"><b>Heb 11:1</b>  Es, pues, la fe, la sustancia de las cosas que se esperan, la demostración de lo que no se ve. </div>
<div id="Heb_11_2" style="display:none;" class="ver_select"><b>Heb 11:2</b>  Porque por ella alcanzaron buen testimonio los antiguos. </div>
<div id="Heb_11_3" style="display:none;" class="ver_select"><b>Heb 11:3</b>  Por fe entendemos haber sido constituido el universo por la palabra de Dios, de manera que lo que se ve, fue hecho de lo que no se veía. </div>
<div id="Heb_11_4" style="display:none;" class="ver_select"><b>Heb 11:4</b>  Por fe Abel ofreció a Dios más excelente sacrificio que Caín, por lo cual alcanzó testimonio de que era justo, dando Dios testimonio de sus ofrendas; y muerto, aún habla por ella. </div>
<div id="Heb_11_5" style="display:none;" class="ver_select"><b>Heb 11:5</b>  Por fe Enoc fue traspuesto para no ver muerte, y no fue hallado, porque lo traspuso Dios. Y antes que fuese traspuesto, tuvo testimonio de haber agradado a Dios. </div>
<div id="Heb_11_6" style="display:none;" class="ver_select"><b>Heb 11:6</b>  Pero sin fe es imposible agradar a Dios; porque es necesario que el que a Dios se acerca, crea que le hay, y que es galardonador de los que le buscan. </div>
<div id="Heb_11_7" style="display:none;" class="ver_select"><b>Heb 11:7</b>  Por fe Noé, siendo advertido por Dios de cosas que aún no se veían, con temor preparó el arca en que su casa se salvase; y por esa fe condenó al mundo, y fue hecho heredero de la justicia que es por la fe. </div>
<div id="Heb_11_8" style="display:none;" class="ver_select"><b>Heb 11:8</b>  Por fe Abraham, siendo llamado, obedeció para salir al lugar que había de recibir por herencia; y salió sin saber a dónde iba. </div>
<div id="Heb_11_9" style="display:none;" class="ver_select"><b>Heb 11:9</b>  Por fe habitó en la tierra prometida como en tierra ajena, morando en tiendas con Isaac y Jacob, coherederos de la misma promesa: </div>
<div id="Heb_11_10" style="display:none;" class="ver_select"><b>Heb 11:10</b>  Porque esperaba la ciudad que tiene fundamentos, cuyo artífice y hacedor es Dios. </div>
<div id="Heb_11_11" style="display:none;" class="ver_select"><b>Heb 11:11</b>  Por fe también la misma Sara, siendo estéril, recibió fuerza para concebir simiente; y dio a luz aun fuera del tiempo de la edad, porque creyó ser fiel el que lo había prometido. </div>
<div id="Heb_11_12" style="display:none;" class="ver_select"><b>Heb 11:12</b>  Por lo cual también, de uno, y éste ya casi muerto, salieron como las estrellas del cielo en multitud, y como la arena innumerable que está a la orilla del mar. </div>
<div id="Heb_11_13" style="display:none;" class="ver_select"><b>Heb 11:13</b>  Conforme a la fe murieron todos éstos sin haber recibido las promesas, sino mirándolas de lejos, y creyéndolas, y saludándolas, y confesando que eran extranjeros y peregrinos sobre la tierra. </div>
<div id="Heb_11_14" style="display:none;" class="ver_select"><b>Heb 11:14</b>  Porque los que esto dicen, claramente dan a entender que buscan una patria. </div>
<div id="Heb_11_15" style="display:none;" class="ver_select"><b>Heb 11:15</b>  Que si hubiesen estado pensando en aquella de donde salieron, ciertamente tenían tiempo para volverse. </div>
<div id="Heb_11_16" style="display:none;" class="ver_select"><b>Heb 11:16</b>  Pero ahora anhelaban una mejor patria, esto es, la celestial; por lo cual Dios no se avergüenza de llamarse Dios de ellos; porque les había preparado una ciudad. </div>
<div id="Heb_11_17" style="display:none;" class="ver_select"><b>Heb 11:17</b>  Por fe Abraham cuando fue probado, ofreció a Isaac, y él que había recibido las promesas, ofreció a su hijo unigénito, </div>
<div id="Heb_11_18" style="display:none;" class="ver_select"><b>Heb 11:18</b>  habiéndole sido dicho: En Isaac te será llamada simiente; </div>
<div id="Heb_11_19" style="display:none;" class="ver_select"><b>Heb 11:19</b>  pensando que aun de los muertos es Dios poderoso para levantar; de donde también le volvió a recibir por figura. </div>
<div id="Heb_11_20" style="display:none;" class="ver_select"><b>Heb 11:20</b>  Por fe Isaac bendijo a Jacob y a Esaú acerca de cosas que habían de venir. </div>
<div id="Heb_11_21" style="display:none;" class="ver_select"><b>Heb 11:21</b>  Por fe Jacob, al morir, bendijo a cada uno de los hijos de José, y adoró apoyándose sobre el extremo de su bordón. </div>
<div id="Heb_11_22" style="display:none;" class="ver_select"><b>Heb 11:22</b>  Por fe José, al morir, hizo mención del éxodo de los hijos de Israel; y dio mandamiento acerca de sus huesos. </div>
<div id="Heb_11_23" style="display:none;" class="ver_select"><b>Heb 11:23</b>  Por fe Moisés, cuando nació, fue escondido de sus padres por tres meses, porque vieron que era niño hermoso; y no temieron el edicto del rey. </div>
<div id="Heb_11_24" style="display:none;" class="ver_select"><b>Heb 11:24</b>  Por fe Moisés, hecho ya grande, rehusó ser llamado hijo de la hija de Faraón; </div>
<div id="Heb_11_25" style="display:none;" class="ver_select"><b>Heb 11:25</b>  escogiendo antes ser afligido con el pueblo de Dios, que gozar de los placeres temporales de pecado. </div>
<div id="Heb_11_26" style="display:none;" class="ver_select"><b>Heb 11:26</b>  Teniendo por mayores riquezas el vituperio de Cristo que los tesoros en Egipto; porque tenía puesta su mirada en el galardón. </div>
<div id="Heb_11_27" style="display:none;" class="ver_select"><b>Heb 11:27</b>  Por fe dejó a Egipto, no temiendo la ira del rey; porque se sostuvo como viendo al Invisible. </div>
<div id="Heb_11_28" style="display:none;" class="ver_select"><b>Heb 11:28</b>  Por fe celebró la pascua y el rociamiento de la sangre, para que el que mataba a los primogénitos no los tocase a ellos. </div>
<div id="Heb_11_29" style="display:none;" class="ver_select"><b>Heb 11:29</b>  Por fe pasaron por el Mar Rojo como por tierra seca; lo cual probando los egipcios, fueron ahogados. </div>
<div id="Heb_11_30" style="display:none;" class="ver_select"><b>Heb 11:30</b>  Por fe cayeron los muros de Jericó después de rodearlos siete días. </div>
<div id="Heb_11_31" style="display:none;" class="ver_select"><b>Heb 11:31</b>  Por fe Rahab la ramera no pereció juntamente con los incrédulos, habiendo recibido a los espías en paz. </div>
<div id="Heb_11_32" style="display:none;" class="ver_select"><b>Heb 11:32</b>  ¿Y qué más digo? Porque el tiempo me faltaría contando de Gedeón, y de Barac, y de Sansón, y de Jefté; así como de David, y de Samuel y de los profetas; </div>
<div id="Heb_11_33" style="display:none;" class="ver_select"><b>Heb 11:33</b>  que por fe conquistaron reinos, hicieron justicia, alcanzaron promesas, taparon bocas de leones, </div>
<div id="Heb_11_34" style="display:none;" class="ver_select"><b>Heb 11:34</b>  apagaron fuegos impetuosos, evitaron filo de espada, sacaron fuerzas de flaqueza, fueron hechos fuertes en batallas, hicieron huir ejércitos extranjeros. </div>
<div id="Heb_11_35" style="display:none;" class="ver_select"><b>Heb 11:35</b>  Las mujeres recibieron sus muertos por resurrección; mas otros fueron torturados, no aceptando el rescate, a fin de obtener mejor resurrección. </div>
<div id="Heb_11_36" style="display:none;" class="ver_select"><b>Heb 11:36</b>  Otros experimentaron vituperios y azotes; y a más de esto cadenas y cárceles. </div>
<div id="Heb_11_37" style="display:none;" class="ver_select"><b>Heb 11:37</b>  Fueron apedreados, aserrados, probados, muertos a espada; anduvieron de acá para allá cubiertos de pieles de ovejas y pieles de cabras, pobres, angustiados, maltratados; </div>
<div id="Heb_11_38" style="display:none;" class="ver_select"><b>Heb 11:38</b>  de los cuales el mundo no era digno; errantes por los desiertos, por los montes, por las cuevas y por las cavernas de la tierra. </div>
<div id="Heb_11_39" style="display:none;" class="ver_select"><b>Heb 11:39</b>  Y todos éstos, aunque obtuvieron buen testimonio mediante la fe, no recibieron la promesa; </div>
<div id="Heb_11_40" style="display:none;" class="ver_select"><b>Heb 11:40</b>  proveyendo Dios alguna cosa mejor para nosotros, para que no fuesen ellos perfeccionados sin nosotros. </div>
<div id="Heb_12_1" style="display:none;" class="ver_select"><b>Heb 12:1</b>  Por tanto, nosotros también, teniendo en derredor nuestro tan grande nube de testigos, despojémonos de todo peso, y del pecado que nos asedia, y corramos con paciencia la carrera que tenemos por delante, </div>
<div id="Heb_12_2" style="display:none;" class="ver_select"><b>Heb 12:2</b>  puestos los ojos en Jesús, el autor y consumador de la fe, el cual, por el gozo puesto delante de Él sufrió la cruz, menospreciando la vergüenza, y se sentó a la diestra del trono de Dios. </div>
<div id="Heb_12_3" style="display:none;" class="ver_select"><b>Heb 12:3</b>  Considerad, pues, a Aquél que sufrió tal contradicción de pecadores contra sí mismo, para que no os fatiguéis ni desmayen vuestras almas. </div>
<div id="Heb_12_4" style="display:none;" class="ver_select"><b>Heb 12:4</b>  Porque aún no habéis resistido hasta la sangre, combatiendo contra el pecado. </div>
<div id="Heb_12_5" style="display:none;" class="ver_select"><b>Heb 12:5</b>  ¿Y habéis ya olvidado la exhortación que como a hijos se os dirige? Hijo mío, no menosprecies la corrección del Señor, ni desmayes cuando eres de Él reprendido. </div>
<div id="Heb_12_6" style="display:none;" class="ver_select"><b>Heb 12:6</b>  Porque el Señor al que ama castiga, y azota a todo el que recibe por hijo. </div>
<div id="Heb_12_7" style="display:none;" class="ver_select"><b>Heb 12:7</b>  Si soportáis el castigo, Dios os trata como a hijos; porque ¿qué hijo es aquel a quien el padre no castiga? </div>
<div id="Heb_12_8" style="display:none;" class="ver_select"><b>Heb 12:8</b>  Pero si estáis sin castigo, del cual todos son hechos partícipes, entonces sois bastardos, y no hijos. </div>
<div id="Heb_12_9" style="display:none;" class="ver_select"><b>Heb 12:9</b>  Por otra parte, tuvimos a los padres de nuestra carne que nos disciplinaban, y los reverenciábamos. ¿Por qué no obedeceremos mucho mejor al Padre de los espíritus, y viviremos? </div>
<div id="Heb_12_10" style="display:none;" class="ver_select"><b>Heb 12:10</b>  Y aquéllos, a la verdad, por pocos días nos castigaban como a ellos les parecía, mas Éste para lo que nos es provechoso, a fin de que participemos de su santidad. </div>
<div id="Heb_12_11" style="display:none;" class="ver_select"><b>Heb 12:11</b>  A la verdad ningún castigo al presente parece ser causa de gozo, sino de tristeza; pero después da fruto apacible de justicia a los que por él son ejercitados. </div>
<div id="Heb_12_12" style="display:none;" class="ver_select"><b>Heb 12:12</b>  Por lo cual alzad las manos caídas y las rodillas paralizadas; </div>
<div id="Heb_12_13" style="display:none;" class="ver_select"><b>Heb 12:13</b>  y haced sendas derechas para vuestros pies, para que lo cojo no se salga del camino, antes sea sanado. </div>
<div id="Heb_12_14" style="display:none;" class="ver_select"><b>Heb 12:14</b>  Seguid la paz con todos, y la santidad, sin la cual nadie verá al Señor. </div>
<div id="Heb_12_15" style="display:none;" class="ver_select"><b>Heb 12:15</b>  Mirando bien que ninguno se aparte de la gracia de Dios; no sea que brotando alguna raíz de amargura, os perturbe, y por ella muchos sean contaminados; </div>
<div id="Heb_12_16" style="display:none;" class="ver_select"><b>Heb 12:16</b>  que ninguno sea fornicario, o profano, como Esaú, que por un bocado vendió su primogenitura. </div>
<div id="Heb_12_17" style="display:none;" class="ver_select"><b>Heb 12:17</b>  Porque ya sabéis que aun después, deseando heredar la bendición, fue rechazado, y no halló lugar de arrepentimiento, aunque la procuró con lágrimas. </div>
<div id="Heb_12_18" style="display:none;" class="ver_select"><b>Heb 12:18</b>  Porque no os habéis acercado al monte que se podía tocar, que ardía con fuego, y al turbión, y a la oscuridad, y a la tempestad, </div>
<div id="Heb_12_19" style="display:none;" class="ver_select"><b>Heb 12:19</b>  y al sonido de la trompeta, y a la voz que les hablaba, la cual los que la oyeron rogaron que no se les hablase más; </div>
<div id="Heb_12_20" style="display:none;" class="ver_select"><b>Heb 12:20</b>  porque no podían soportar lo que se mandaba: Si aun una bestia tocare al monte, será apedreada, o pasada con dardo. </div>
<div id="Heb_12_21" style="display:none;" class="ver_select"><b>Heb 12:21</b>  Y tan terrible era lo que se veía, que Moisés dijo: Estoy espantado y temblando; </div>
<div id="Heb_12_22" style="display:none;" class="ver_select"><b>Heb 12:22</b>  sino que os habéis acercado al monte de Sión, y a la ciudad del Dios vivo, la Jerusalén celestial, y a una compañía innumerable de ángeles, </div>
<div id="Heb_12_23" style="display:none;" class="ver_select"><b>Heb 12:23</b>  a la congregación general e iglesia de los primogénitos que están inscritos en el cielo, y a Dios el Juez de todos, y a los espíritus de los justos hechos perfectos, </div>
<div id="Heb_12_24" style="display:none;" class="ver_select"><b>Heb 12:24</b>  y a Jesús el Mediador del nuevo pacto, y a la sangre del rociamiento que habla mejor que la de Abel. </div>
<div id="Heb_12_25" style="display:none;" class="ver_select"><b>Heb 12:25</b>  Mirad que no desechéis al que habla. Porque si no escaparon aquellos que desecharon al que hablaba en la tierra, mucho menos nosotros, si desecháramos al que habla desde el cielo. </div>
<div id="Heb_12_26" style="display:none;" class="ver_select"><b>Heb 12:26</b>  La voz del cual conmovió entonces la tierra; pero ahora ha prometido, diciendo: Aun una vez, y yo conmoveré no solamente la tierra, sino también el cielo. </div>
<div id="Heb_12_27" style="display:none;" class="ver_select"><b>Heb 12:27</b>  Y esta expresión: Aun una vez, significa la remoción de las cosas movibles, como de cosas hechas, para que permanezcan las que no pueden ser removidas. </div>
<div id="Heb_12_28" style="display:none;" class="ver_select"><b>Heb 12:28</b>  Así que, recibiendo nosotros un reino inconmovible, tengamos gracia, por la cual sirvamos a Dios agradándole con temor y reverencia; </div>
<div id="Heb_12_29" style="display:none;" class="ver_select"><b>Heb 12:29</b>  porque nuestro Dios es fuego consumidor. </div>
<div id="Heb_13_1" style="display:none;" class="ver_select"><b>Heb 13:1</b>  Permanezca el amor fraternal. </div>
<div id="Heb_13_2" style="display:none;" class="ver_select"><b>Heb 13:2</b>  No os olvidéis de la hospitalidad, porque por ella algunos, sin saberlo, hospedaron ángeles. </div>
<div id="Heb_13_3" style="display:none;" class="ver_select"><b>Heb 13:3</b>  Acordaos de los presos, como presos juntamente con ellos; y de los afligidos, como que también vosotros mismos estáis en el cuerpo. </div>
<div id="Heb_13_4" style="display:none;" class="ver_select"><b>Heb 13:4</b>  Honroso es en todo el matrimonio, y el lecho sin mancilla; mas a los fornicarios y a los adúlteros juzgará Dios. </div>
<div id="Heb_13_5" style="display:none;" class="ver_select"><b>Heb 13:5</b>  Sean vuestras costumbres sin avaricia; contentos con lo que tenéis; porque Él dijo: No te dejaré ni te desampararé. </div>
<div id="Heb_13_6" style="display:none;" class="ver_select"><b>Heb 13:6</b>  De manera que podemos decir confiadamente: El Señor es mi ayudador; y: No temeré lo que me pueda hacer el hombre. </div>
<div id="Heb_13_7" style="display:none;" class="ver_select"><b>Heb 13:7</b>  Acordaos de vuestros pastores, que os hablaron la palabra de Dios, y seguid el ejemplo de su fe, considerando cuál haya sido el éxito de su conducta. </div>
<div id="Heb_13_8" style="display:none;" class="ver_select"><b>Heb 13:8</b>  Jesucristo es el mismo ayer, y hoy, y por siempre. </div>
<div id="Heb_13_9" style="display:none;" class="ver_select"><b>Heb 13:9</b>  No seáis llevados de acá para allá por doctrinas diversas y extrañas; porque buena cosa es afirmar el corazón con la gracia, no con viandas, que nunca aprovecharon a los que se han ocupado en ellas. </div>
<div id="Heb_13_10" style="display:none;" class="ver_select"><b>Heb 13:10</b>  Tenemos un altar, del cual no tienen derecho de comer los que sirven al tabernáculo. </div>
<div id="Heb_13_11" style="display:none;" class="ver_select"><b>Heb 13:11</b>  Porque los cuerpos de aquellos animales, cuya sangre a causa del pecado es introducida en el santuario por el sumo sacerdote, son quemados fuera del campamento. </div>
<div id="Heb_13_12" style="display:none;" class="ver_select"><b>Heb 13:12</b>  Por lo cual también Jesús, para santificar al pueblo con su propia sangre, padeció fuera de la puerta. </div>
<div id="Heb_13_13" style="display:none;" class="ver_select"><b>Heb 13:13</b>  Salgamos, pues, a Él, fuera del campamento, llevando su vituperio. </div>
<div id="Heb_13_14" style="display:none;" class="ver_select"><b>Heb 13:14</b>  Porque no tenemos aquí ciudad permanente, mas buscamos la por venir. </div>
<div id="Heb_13_15" style="display:none;" class="ver_select"><b>Heb 13:15</b>  Así que, por medio de Él ofrezcamos siempre a Dios sacrificio de alabanza, es decir, el fruto de nuestros labios dando gracias a su nombre. </div>
<div id="Heb_13_16" style="display:none;" class="ver_select"><b>Heb 13:16</b>  Y de hacer bien y de la comunicación no os olvidéis; porque de tales sacrificios se agrada Dios. </div>
<div id="Heb_13_17" style="display:none;" class="ver_select"><b>Heb 13:17</b>  Obedeced a vuestros pastores, y sujetaos a ellos; porque ellos velan por vuestras almas, como quienes han de dar cuenta; para que lo hagan con alegría, y no gimiendo; porque esto no os es provechoso. </div>
<div id="Heb_13_18" style="display:none;" class="ver_select"><b>Heb 13:18</b>  Orad por nosotros; porque confiamos que tenemos buena conciencia; deseando conducirnos en todo con honestidad. </div>
<div id="Heb_13_19" style="display:none;" class="ver_select"><b>Heb 13:19</b>  Y más os ruego que lo hagáis así, para que yo os sea restituido más pronto. </div>
<div id="Heb_13_20" style="display:none;" class="ver_select"><b>Heb 13:20</b>  Y el Dios de paz que resucitó de entre los muertos a nuestro Señor Jesucristo, el gran pastor de las ovejas, por la sangre del pacto eterno, </div>
<div id="Heb_13_21" style="display:none;" class="ver_select"><b>Heb 13:21</b>  os haga perfectos para toda obra buena para que hagáis su voluntad, haciendo Él en vosotros lo que es agradable delante de Él por Jesucristo; al cual sea gloria para siempre jamás. Amén. </div>
<div id="Heb_13_22" style="display:none;" class="ver_select"><b>Heb 13:22</b>  Y os ruego, hermanos, que soportéis la palabra de exhortación; pues os he escrito brevemente. </div>
<div id="Heb_13_23" style="display:none;" class="ver_select"><b>Heb 13:23</b>  Sabed que nuestro hermano Timoteo ha sido puesto en libertad; con el cual, si viniere pronto, iré a veros. </div>
<div id="Heb_13_24" style="display:none;" class="ver_select"><b>Heb 13:24</b>  Saludad a todos vuestros pastores, y a todos los santos. Los de Italia os saludan. </div>
<div id="Heb_13_25" style="display:none;" class="ver_select"><b>Heb 13:25</b>  La gracia sea con todos vosotros. Amén. Escrita de Italia, traída por Timoteo. </div>
