<div id="Hos_1_1" style="display:none;" class="ver_select"><b>Hos 1:1</b>  Palabra de Jehová que vino a Oseas hijo de Beeri, en días de Uzías, Jotam, Acaz, y Ezequías, reyes de Judá, y en días de Jeroboam hijo de Joás, rey de Israel. </div>
<div id="Hos_1_2" style="display:none;" class="ver_select"><b>Hos 1:2</b>  El principio de la palabra de Jehová por medio de Oseas. Y dijo Jehová a Oseas: Ve, toma para ti a una esposa ramera, e hijos de prostitución; porque la tierra gravemente se ha prostituido, apartándose de Jehová. </div>
<div id="Hos_1_3" style="display:none;" class="ver_select"><b>Hos 1:3</b>  Fue, pues, y tomó a Gomer hija de Diblaim, la cual concibió y le dio a luz un hijo. </div>
<div id="Hos_1_4" style="display:none;" class="ver_select"><b>Hos 1:4</b>  Y le dijo Jehová: Ponle por nombre Jezreel; porque de aquí a poco yo vengaré la sangre de Jezreel sobre la casa de Jehú, y haré cesar el reino de la casa de Israel. </div>
<div id="Hos_1_5" style="display:none;" class="ver_select"><b>Hos 1:5</b>  Y acontecerá que en aquel día quebraré yo el arco de Israel en el valle de Jezreel. </div>
<div id="Hos_1_6" style="display:none;" class="ver_select"><b>Hos 1:6</b>  Y concibió otra vez, y dio a luz una hija. Y le dijo Dios: Ponle por nombre Lo-ruhama; porque ya no tendré misericordia de la casa de Israel, sino que los quitaré del todo. </div>
<div id="Hos_1_7" style="display:none;" class="ver_select"><b>Hos 1:7</b>  Mas de la casa de Judá tendré misericordia, y los salvaré en Jehová su Dios: y no los salvaré con arco, ni con espada, ni con batalla, ni con caballos ni jinetes. </div>
<div id="Hos_1_8" style="display:none;" class="ver_select"><b>Hos 1:8</b>  Y después de haber destetado a Lo-ruhama, concibió y dio a luz un hijo. </div>
<div id="Hos_1_9" style="display:none;" class="ver_select"><b>Hos 1:9</b>  Y dijo Dios: Ponle por nombre Lo-ammi, porque vosotros no sois mi pueblo, ni yo seré vuestro Dios. </div>
<div id="Hos_1_10" style="display:none;" class="ver_select"><b>Hos 1:10</b>  Con todo, el número de los hijos de Israel será como la arena del mar, que no se puede medir ni contar. Y sucederá que en el lugar donde se les ha dicho: Vosotros no sois mi pueblo, les será dicho: Sois hijos del Dios viviente. </div>
<div id="Hos_1_11" style="display:none;" class="ver_select"><b>Hos 1:11</b>  Y los hijos de Judá y los hijos de Israel serán congregados en uno, y levantarán para sí una cabeza, y subirán de la tierra: porque el día de Jezreel será grande. </div>
<div id="Hos_2_1" style="display:none;" class="ver_select"><b>Hos 2:1</b>  Decid a vuestros hermanos, Ammi, y a vuestras hermanas, Ruhama: </div>
<div id="Hos_2_2" style="display:none;" class="ver_select"><b>Hos 2:2</b>  Contended con vuestra madre, contended, porque ella no es mi esposa, y yo no soy su marido; quite, pues, de su rostro sus prostituciones, y sus adulterios de entre sus pechos; </div>
<div id="Hos_2_3" style="display:none;" class="ver_select"><b>Hos 2:3</b>  no sea que yo la despoje y desnude, y la deje como el día en que nació, y la ponga como un desierto, y la deje como tierra seca, y la mate de sed. </div>
<div id="Hos_2_4" style="display:none;" class="ver_select"><b>Hos 2:4</b>  Y no tendré misericordia de sus hijos, porque son hijos de prostitución. </div>
<div id="Hos_2_5" style="display:none;" class="ver_select"><b>Hos 2:5</b>  Porque su madre se prostituyó; la que los engendró se deshonró; porque dijo: Iré tras mis amantes, que me dan mi pan y mi agua, mi lana y mi lino, mi aceite y mi bebida. </div>
<div id="Hos_2_6" style="display:none;" class="ver_select"><b>Hos 2:6</b>  Por tanto, he aquí yo voy a cercar con espinos su camino, y le pondré vallado, para que no encuentre sus senderos. </div>
<div id="Hos_2_7" style="display:none;" class="ver_select"><b>Hos 2:7</b>  Y seguirá a sus amantes, y no los alcanzará; los buscará, y no los hallará. Entonces dirá: Iré, y me volveré a mi primer marido; porque mejor me iba entonces que ahora. </div>
<div id="Hos_2_8" style="display:none;" class="ver_select"><b>Hos 2:8</b>  Y ella no reconoció que yo le daba el trigo, el vino y el aceite, y que les multipliqué la plata y el oro que ofrecían a Baal. </div>
<div id="Hos_2_9" style="display:none;" class="ver_select"><b>Hos 2:9</b>  Por tanto yo volveré, y tomaré mi trigo a su tiempo, y mi vino a su sazón, y quitaré mi lana y mi lino que le había dado para cubrir su desnudez. </div>
<div id="Hos_2_10" style="display:none;" class="ver_select"><b>Hos 2:10</b>  Y ahora descubriré yo su locura delante de los ojos de sus amantes, y nadie la librará de mi mano. </div>
<div id="Hos_2_11" style="display:none;" class="ver_select"><b>Hos 2:11</b>  Y haré cesar todo su gozo, sus fiestas, sus nuevas lunas y sus sábados, y todas sus festividades. </div>
<div id="Hos_2_12" style="display:none;" class="ver_select"><b>Hos 2:12</b>  Y haré talar sus vides y sus higueras, de las cuales ha dicho: Mi pago son, que me han dado mis amantes. Y las reduciré a un matorral, y las comerán las bestias del campo. </div>
<div id="Hos_2_13" style="display:none;" class="ver_select"><b>Hos 2:13</b>  Y visitaré sobre ella los tiempos de los Baales, a los cuales incensaba, y se adornaba de sus zarcillos y de sus joyeles, y se iba tras sus amantes olvidándose de mí, dice Jehová. </div>
<div id="Hos_2_14" style="display:none;" class="ver_select"><b>Hos 2:14</b>  Pero he aquí, yo la atraeré, y la llevaré al desierto, y hablaré a su corazón. </div>
<div id="Hos_2_15" style="display:none;" class="ver_select"><b>Hos 2:15</b>  Y le daré sus viñas desde allí, y el valle de Acor por puerta de esperanza; y allí cantará como en los tiempos de su juventud, y como en el día de su subida de la tierra de Egipto. </div>
<div id="Hos_2_16" style="display:none;" class="ver_select"><b>Hos 2:16</b>  Y será que en aquel tiempo, dice Jehová, me llamarás Ishi, y nunca más me llamarás Baali. </div>
<div id="Hos_2_17" style="display:none;" class="ver_select"><b>Hos 2:17</b>  Porque quitaré de su boca los nombres de los Baales, y nunca más serán mencionados por sus nombres. </div>
<div id="Hos_2_18" style="display:none;" class="ver_select"><b>Hos 2:18</b>  Y en aquel tiempo haré para ellos pacto con las bestias del campo, con las aves del cielo y con los reptiles de la tierra; y quebraré arco y espada y la batalla de la tierra, y los haré dormir seguros. </div>
<div id="Hos_2_19" style="display:none;" class="ver_select"><b>Hos 2:19</b>  Y te desposaré conmigo para siempre; te desposaré conmigo en justicia, y juicio, en compasión, y en misericordias. </div>
<div id="Hos_2_20" style="display:none;" class="ver_select"><b>Hos 2:20</b>  Y te desposaré conmigo en fe, y conocerás a Jehová. </div>
<div id="Hos_2_21" style="display:none;" class="ver_select"><b>Hos 2:21</b>  Y será que en aquel tiempo responderé, dice Jehová, yo responderé a los cielos, y ellos responderán a la tierra; </div>
<div id="Hos_2_22" style="display:none;" class="ver_select"><b>Hos 2:22</b>  Y la tierra responderá al trigo, y al vino, y al aceite, y ellos responderán a Jezreel. </div>
<div id="Hos_2_23" style="display:none;" class="ver_select"><b>Hos 2:23</b>  Y la sembraré para mí en la tierra, y tendré misericordia de la que no ha obtenido misericordia; y diré al que no era mi pueblo: Tú eres mi pueblo, y él dirá: Tú eres mi Dios. </div>
<div id="Hos_3_1" style="display:none;" class="ver_select"><b>Hos 3:1</b>  Y me dijo otra vez Jehová: Ve, ama una mujer amada de su compañero (aunque adúltera), como el amor de Jehová para con los hijos de Israel; los cuales miran a dioses ajenos, y aman frascos de vino. </div>
<div id="Hos_3_2" style="display:none;" class="ver_select"><b>Hos 3:2</b>  La compré entonces para mí por quince piezas de plata, y un homer y medio de cebada. </div>
<div id="Hos_3_3" style="display:none;" class="ver_select"><b>Hos 3:3</b>  Y le dije: Tú te quedarás para mí muchos días; no fornicarás, ni tomarás otro varón; lo mismo haré yo por ti. </div>
<div id="Hos_3_4" style="display:none;" class="ver_select"><b>Hos 3:4</b>  Porque muchos días estarán los hijos de Israel sin rey, y sin príncipe, y sin sacrificio, y sin estatua, y sin efod, y sin terafim. </div>
<div id="Hos_3_5" style="display:none;" class="ver_select"><b>Hos 3:5</b>  Después volverán los hijos de Israel, y buscarán a Jehová su Dios, y a David su rey; y temerán a Jehová y a su bondad en el fin de los días. </div>
<div id="Hos_4_1" style="display:none;" class="ver_select"><b>Hos 4:1</b>  Oíd la palabra de Jehová, hijos de Israel, porque Jehová contiende con los moradores de la tierra; porque no hay verdad, ni misericordia, ni conocimiento de Dios en la tierra. </div>
<div id="Hos_4_2" style="display:none;" class="ver_select"><b>Hos 4:2</b>  Perjurar, mentir, matar, hurtar y adulterar prevalecen, y derramamiento de sangre tras derramamiento de sangre. </div>
<div id="Hos_4_3" style="display:none;" class="ver_select"><b>Hos 4:3</b>  Por lo cual, se enlutará la tierra, y se extenuará todo morador de ella, con las bestias del campo, y las aves del cielo: y aun los peces del mar fallecerán. </div>
<div id="Hos_4_4" style="display:none;" class="ver_select"><b>Hos 4:4</b>  Ciertamente hombre no contienda ni reprenda a hombre, porque tu pueblo es como los que resisten al sacerdote. </div>
<div id="Hos_4_5" style="display:none;" class="ver_select"><b>Hos 4:5</b>  Caerás por tanto en el día, y caerá también contigo el profeta de noche; y a tu madre talaré. </div>
<div id="Hos_4_6" style="display:none;" class="ver_select"><b>Hos 4:6</b>  Mi pueblo fue destruido porque le faltó conocimiento. Porque tú desechaste el conocimiento, yo te echaré del sacerdocio; y porque olvidaste la ley de tu Dios, también yo me olvidaré de tus hijos. </div>
<div id="Hos_4_7" style="display:none;" class="ver_select"><b>Hos 4:7</b>  Conforme a su grandeza así pecaron contra mí; por tanto, cambiaré su honra en afrenta. </div>
<div id="Hos_4_8" style="display:none;" class="ver_select"><b>Hos 4:8</b>  Comen del pecado de mi pueblo, y en su maldad levantan su alma. </div>
<div id="Hos_4_9" style="display:none;" class="ver_select"><b>Hos 4:9</b>  Tal será el pueblo como el sacerdote: y visitaré sobre él sus caminos, y le pagaré conforme a sus obras. </div>
<div id="Hos_4_10" style="display:none;" class="ver_select"><b>Hos 4:10</b>  Y comerán, mas no se saciarán; fornicarán, mas no se aumentarán; porque dejaron de escuchar a Jehová. </div>
<div id="Hos_4_11" style="display:none;" class="ver_select"><b>Hos 4:11</b>  Fornicación, vino, y mosto quitan el corazón. </div>
<div id="Hos_4_12" style="display:none;" class="ver_select"><b>Hos 4:12</b>  Mi pueblo a su ídolo de madera consulta, y su vara le responde; porque el espíritu de fornicaciones los ha engañado, y se han dado a la fornicación dejando a su Dios. </div>
<div id="Hos_4_13" style="display:none;" class="ver_select"><b>Hos 4:13</b>  Sobre las cabezas de los montes sacrificaron, e incensaron sobre los collados, debajo de encinas, y álamos, y olmos que tuviesen buena sombra; por tanto, vuestras hijas fornicarán, y adulterarán vuestras nueras. </div>
<div id="Hos_4_14" style="display:none;" class="ver_select"><b>Hos 4:14</b>  No visitaré sobre vuestras hijas cuando fornicaren, y sobre vuestras nueras cuando adulteraren: porque ellos ofrecen sacrificios con las rameras, y con las malas mujeres sacrifican; por tanto, el pueblo sin entendimiento caerá. </div>
<div id="Hos_4_15" style="display:none;" class="ver_select"><b>Hos 4:15</b>  Si fornicares tú, Israel, a lo menos no peque Judá; y no entréis en Gilgal, ni subáis a Betaven; ni juréis: Vive Jehová. </div>
<div id="Hos_4_16" style="display:none;" class="ver_select"><b>Hos 4:16</b>  Porque como becerra rebelde se apartó Israel: ¿los apacentará ahora Jehová como a carneros en lugar espacioso? </div>
<div id="Hos_4_17" style="display:none;" class="ver_select"><b>Hos 4:17</b>  Efraín es dado a ídolos; déjalo. </div>
<div id="Hos_4_18" style="display:none;" class="ver_select"><b>Hos 4:18</b>  Su bebida se corrompió; fornicaron pertinazmente; sus príncipes amaron lo que avergüenza. </div>
<div id="Hos_4_19" style="display:none;" class="ver_select"><b>Hos 4:19</b>  La ató el viento en sus alas, y se avergonzarán de sus sacrificios. </div>
<div id="Hos_5_1" style="display:none;" class="ver_select"><b>Hos 5:1</b>  Sacerdotes, oíd esto, y estad atentos, casa de Israel; y casa del rey, escuchad; porque contra vosotros es el juicio, pues habéis sido lazo en Mizpa, y red extendida sobre Tabor. </div>
<div id="Hos_5_2" style="display:none;" class="ver_select"><b>Hos 5:2</b>  Y haciendo víctimas han bajado hasta lo profundo; por tanto yo castigaré a todos ellos. </div>
<div id="Hos_5_3" style="display:none;" class="ver_select"><b>Hos 5:3</b>  Yo conozco a Efraín, e Israel no me es desconocido; porque ahora, oh Efraín, te has prostituido, y se ha contaminado Israel. </div>
<div id="Hos_5_4" style="display:none;" class="ver_select"><b>Hos 5:4</b>  No pondrán sus pensamientos en volverse a su Dios, porque espíritu de prostitución está en medio de ellos, y no conocen a Jehová. </div>
<div id="Hos_5_5" style="display:none;" class="ver_select"><b>Hos 5:5</b>  Y la soberbia de Israel le desmentirá en su cara; e Israel y Efraín tropezarán en su pecado; tropezará también Judá con ellos. </div>
<div id="Hos_5_6" style="display:none;" class="ver_select"><b>Hos 5:6</b>  Con sus ovejas y con sus vacas andarán buscando a Jehová, y no le hallarán; se apartó de ellos. </div>
<div id="Hos_5_7" style="display:none;" class="ver_select"><b>Hos 5:7</b>  Contra Jehová prevaricaron, porque hijos extraños han engendrado: ahora los devorará un mes con sus heredades. </div>
<div id="Hos_5_8" style="display:none;" class="ver_select"><b>Hos 5:8</b>  Tocad bocina en Gabaa, trompeta en Ramá; sonad alarma en Betaven; tras ti, oh Benjamín. </div>
<div id="Hos_5_9" style="display:none;" class="ver_select"><b>Hos 5:9</b>  Efraín será asolado el día del castigo; en las tribus de Israel hice conocer verdad. </div>
<div id="Hos_5_10" style="display:none;" class="ver_select"><b>Hos 5:10</b>  Los príncipes de Judá fueron como los que traspasan los linderos; derramaré sobre ellos como agua mi ira. </div>
<div id="Hos_5_11" style="display:none;" class="ver_select"><b>Hos 5:11</b>  Efraín es vejado, quebrantado en juicio, porque quiso andar en pos de mandatos de hombres. </div>
<div id="Hos_5_12" style="display:none;" class="ver_select"><b>Hos 5:12</b>  Yo, pues, seré como polilla a Efraín, y como carcoma a la casa de Judá. </div>
<div id="Hos_5_13" style="display:none;" class="ver_select"><b>Hos 5:13</b>  Y verá Efraín su enfermedad, y Judá su llaga; irá entonces Efraín a Asiria, y enviará al rey Jareb; mas él no os podrá sanar, ni os curará la llaga. </div>
<div id="Hos_5_14" style="display:none;" class="ver_select"><b>Hos 5:14</b>  Porque yo seré como león a Efraín, y como cachorro de león a la casa de Judá; yo, yo arrebataré, y andaré; tomaré, y no habrá quien liberte. </div>
<div id="Hos_5_15" style="display:none;" class="ver_select"><b>Hos 5:15</b>  Andaré, y volveré a mi lugar hasta que reconozcan su pecado, y busquen mi rostro. En su angustia temprano me buscarán. </div>
<div id="Hos_6_1" style="display:none;" class="ver_select"><b>Hos 6:1</b>  Venid y volvámonos a Jehová; porque Él arrebató, y nos curará; hirió, y nos vendará. </div>
<div id="Hos_6_2" style="display:none;" class="ver_select"><b>Hos 6:2</b>  Nos dará vida después de dos días; al tercer día nos resucitará y viviremos delante de Él. </div>
<div id="Hos_6_3" style="display:none;" class="ver_select"><b>Hos 6:3</b>  Y conoceremos, y proseguiremos en conocer a Jehová; su salida está dispuesta como el alba, y vendrá a nosotros como la lluvia, como la lluvia tardía y temprana a la tierra. </div>
<div id="Hos_6_4" style="display:none;" class="ver_select"><b>Hos 6:4</b>  ¿Qué haré a ti, Efraín? ¿Qué haré a ti, oh Judá? La piedad vuestra es como la nube de la mañana, y como el rocío que de madrugada viene. </div>
<div id="Hos_6_5" style="display:none;" class="ver_select"><b>Hos 6:5</b>  Por esta causa corté con los profetas, con las palabras de mi boca los maté; y tus juicios serán como luz que sale. </div>
<div id="Hos_6_6" style="display:none;" class="ver_select"><b>Hos 6:6</b>  Porque misericordia quise, y no sacrificio; y conocimiento de Dios más que holocaustos. </div>
<div id="Hos_6_7" style="display:none;" class="ver_select"><b>Hos 6:7</b>  Mas ellos, cual Adán, traspasaron el pacto; allí prevaricaron contra mí. </div>
<div id="Hos_6_8" style="display:none;" class="ver_select"><b>Hos 6:8</b>  Galaad, ciudad de obradores de iniquidad, ensuciada de sangre. </div>
<div id="Hos_6_9" style="display:none;" class="ver_select"><b>Hos 6:9</b>  Y como ladrones que esperan a algún hombre, así una compañía de sacerdotes asesina en el camino de Siquem; porque ponen en efecto la abominación. </div>
<div id="Hos_6_10" style="display:none;" class="ver_select"><b>Hos 6:10</b>  En la casa de Israel he visto suciedad; allí está la prostitución de Efraín, se ha contaminado Israel. </div>
<div id="Hos_6_11" style="display:none;" class="ver_select"><b>Hos 6:11</b>  También para ti oh Judá, está preparada una cosecha, cuando yo haga volver el cautiverio de mi pueblo. </div>
<div id="Hos_7_1" style="display:none;" class="ver_select"><b>Hos 7:1</b>  Mientras curaba yo a Israel, se descubrió la iniquidad de Efraín, y las maldades de Samaria; porque obran con engaño; y el ladrón entra, y los salteadores despojan por fuera. </div>
<div id="Hos_7_2" style="display:none;" class="ver_select"><b>Hos 7:2</b>  Y no consideran en su corazón que tengo en la memoria toda su maldad: ahora los rodearán sus obras; delante de mí están. </div>
<div id="Hos_7_3" style="display:none;" class="ver_select"><b>Hos 7:3</b>  Con su maldad alegran al rey, y a los príncipes con sus mentiras. </div>
<div id="Hos_7_4" style="display:none;" class="ver_select"><b>Hos 7:4</b>  Todos ellos son adúlteros; son como horno encendido por el hornero, el cual cesará de avivar después que esté hecha la masa, hasta que esté leuda. </div>
<div id="Hos_7_5" style="display:none;" class="ver_select"><b>Hos 7:5</b>  En el día de nuestro rey los príncipes lo hicieron enfermar con vasos de vino; extendió su mano con los escarnecedores. </div>
<div id="Hos_7_6" style="display:none;" class="ver_select"><b>Hos 7:6</b>  Porque aplicaron su corazón, semejante a un horno, a sus artificios: toda la noche duerme su hornero; a la mañana está encendido como llama de fuego. </div>
<div id="Hos_7_7" style="display:none;" class="ver_select"><b>Hos 7:7</b>  Todos ellos arden como un horno, y devoraron a sus jueces; cayeron todos sus reyes; no hay entre ellos quien a mí clame. </div>
<div id="Hos_7_8" style="display:none;" class="ver_select"><b>Hos 7:8</b>  Efraín se mezcló con los pueblos; Efraín es torta no volteada. </div>
<div id="Hos_7_9" style="display:none;" class="ver_select"><b>Hos 7:9</b>  Comieron extraños su sustancia, y él no lo supo; y aun vejez se ha esparcido por él, y él no lo entendió. </div>
<div id="Hos_7_10" style="display:none;" class="ver_select"><b>Hos 7:10</b>  Y la soberbia de Israel testificará contra él en su cara; y con todo esto, no se volvieron a Jehová su Dios, ni lo buscaron. </div>
<div id="Hos_7_11" style="display:none;" class="ver_select"><b>Hos 7:11</b>  Y Efraín es como paloma incauta, sin entendimiento; llama a Egipto, acude a Asiria. </div>
<div id="Hos_7_12" style="display:none;" class="ver_select"><b>Hos 7:12</b>  Cuando fueren, extenderé sobre ellos mi red, los haré caer como aves del cielo; los castigaré conforme a lo que se ha oído en sus congregaciones. </div>
<div id="Hos_7_13" style="display:none;" class="ver_select"><b>Hos 7:13</b>  ¡Ay de ellos! porque se apartaron de mí; destrucción vendrá sobre ellos, porque contra mí se rebelaron; yo los redimí, y ellos hablaron mentiras contra mí. </div>
<div id="Hos_7_14" style="display:none;" class="ver_select"><b>Hos 7:14</b>  Y no clamaron a mí con su corazón cuando aullaron sobre sus camas, para el trigo y el mosto se congregaron, se rebelaron contra mí. </div>
<div id="Hos_7_15" style="display:none;" class="ver_select"><b>Hos 7:15</b>  Aunque yo ceñí y fortalecí sus brazos, contra mí pensaron mal. </div>
<div id="Hos_7_16" style="display:none;" class="ver_select"><b>Hos 7:16</b>  Se vuelven, pero no al Altísimo; son como arco engañoso; sus príncipes caerán a espada por la soberbia de su lengua; esto será su escarnio en la tierra de Egipto. </div>
<div id="Hos_8_1" style="display:none;" class="ver_select"><b>Hos 8:1</b>  Pon a tu boca trompeta. Vendrá como águila contra la casa de Jehová, porque traspasaron mi pacto, y se rebelaron contra mi ley. </div>
<div id="Hos_8_2" style="display:none;" class="ver_select"><b>Hos 8:2</b>  Israel clamará a mí: Dios mío, te conocemos. </div>
<div id="Hos_8_3" style="display:none;" class="ver_select"><b>Hos 8:3</b>  Israel ha rechazado el bien; el enemigo lo perseguirá. </div>
<div id="Hos_8_4" style="display:none;" class="ver_select"><b>Hos 8:4</b>  Ellos hicieron reyes, mas no de parte mía; constituyeron príncipes, mas yo no lo supe: de su plata y de su oro hicieron ídolos para sí, para ser talados. </div>
<div id="Hos_8_5" style="display:none;" class="ver_select"><b>Hos 8:5</b>  Tu becerro, oh Samaria, te hizo alejar; se encendió mi enojo contra ellos, hasta que no pudieron alcanzar inocencia. </div>
<div id="Hos_8_6" style="display:none;" class="ver_select"><b>Hos 8:6</b>  Porque de Israel es, y artífice lo hizo; que no es Dios; por lo que en pedazos será deshecho el becerro de Samaria. </div>
<div id="Hos_8_7" style="display:none;" class="ver_select"><b>Hos 8:7</b>  Porque sembraron viento, y torbellino segarán; no tendrán mies, ni el fruto hará harina; si la hiciere, extraños la tragarán. </div>
<div id="Hos_8_8" style="display:none;" class="ver_select"><b>Hos 8:8</b>  Será devorado Israel; ahora serán entre los gentiles como vaso en que no hay placer. </div>
<div id="Hos_8_9" style="display:none;" class="ver_select"><b>Hos 8:9</b>  Porque ellos subieron a Asiria, como asno montés por sí solo: Efraín con salario alquiló amantes. </div>
<div id="Hos_8_10" style="display:none;" class="ver_select"><b>Hos 8:10</b>  Aunque alquilen entre las naciones, ahora los juntaré; y serán afligidos un poco por la carga del rey y de los príncipes. </div>
<div id="Hos_8_11" style="display:none;" class="ver_select"><b>Hos 8:11</b>  Porque multiplicó Efraín altares para pecar, tuvo altares para pecar. </div>
<div id="Hos_8_12" style="display:none;" class="ver_select"><b>Hos 8:12</b>  Le escribí las grandezas de mi ley, pero fueron tenidas como cosas extrañas. </div>
<div id="Hos_8_13" style="display:none;" class="ver_select"><b>Hos 8:13</b>  En los sacrificios de mis dones sacrificaron carne, y comieron, pero no los quiso Jehová; ahora se acordará de su iniquidad, y visitará su pecado; ellos se tornarán a Egipto. </div>
<div id="Hos_8_14" style="display:none;" class="ver_select"><b>Hos 8:14</b>  Olvidó, pues, Israel a su Hacedor, y edificó templos, y Judá multiplicó ciudades fortificadas; mas yo meteré fuego en sus ciudades, el cual devorará sus palacios. </div>
<div id="Hos_9_1" style="display:none;" class="ver_select"><b>Hos 9:1</b>  No te alegres, oh Israel, hasta saltar de gozo como los otros pueblos, pues te has prostituido apartándote de tu Dios; amaste salario por todas las eras de trigo. </div>
<div id="Hos_9_2" style="display:none;" class="ver_select"><b>Hos 9:2</b>  La era y el lagar no los mantendrán, y les fallará el mosto. </div>
<div id="Hos_9_3" style="display:none;" class="ver_select"><b>Hos 9:3</b>  No quedarán en la tierra de Jehová, sino que volverá Efraín a Egipto, y a Asiria, donde comerán vianda inmunda. </div>
<div id="Hos_9_4" style="display:none;" class="ver_select"><b>Hos 9:4</b>  No darán ofrendas de vino a Jehová, ni Él se agradará de ellos; sus sacrificios, como pan de enlutados les serán a ellos; todos los que comieren de él, serán inmundos. Será, pues, el pan de ellos para sí mismos; no entrará en la casa de Jehová. </div>
<div id="Hos_9_5" style="display:none;" class="ver_select"><b>Hos 9:5</b>  ¿Qué haréis en el día de la solemnidad, y en el día de la fiesta de Jehová? </div>
<div id="Hos_9_6" style="display:none;" class="ver_select"><b>Hos 9:6</b>  Porque, he aquí se fueron ellos a causa de la destrucción: Egipto los recogerá, Menfis los enterrará; espino poseerá por heredad lo deseable de su plata, ortiga crecerá en sus moradas. </div>
<div id="Hos_9_7" style="display:none;" class="ver_select"><b>Hos 9:7</b>  Vinieron los días de la visitación, vinieron los días de la paga; lo conocerá Israel; necio es el profeta, insensato es el varón de espíritu, a causa de la multitud de tu maldad, y el grande odio. </div>
<div id="Hos_9_8" style="display:none;" class="ver_select"><b>Hos 9:8</b>  Atalaya era Efraín para con mi Dios; Pero el profeta es lazo de cazador en todos sus caminos, y odio en la casa de su Dios. </div>
<div id="Hos_9_9" style="display:none;" class="ver_select"><b>Hos 9:9</b>  Profundamente se han corrompido, como en los días de Gabaa; ahora se acordará de su iniquidad; visitará su pecado. </div>
<div id="Hos_9_10" style="display:none;" class="ver_select"><b>Hos 9:10</b>  Como uvas en el desierto hallé a Israel; como la fruta temprana de la higuera en su principio vi a vuestros padres. Ellos entraron a Baal-peor, y se apartaron para vergüenza, y se hicieron abominables como aquello que amaron. </div>
<div id="Hos_9_11" style="display:none;" class="ver_select"><b>Hos 9:11</b>  Efraín, cual ave volará su gloria desde el nacimiento, aun desde el vientre y desde la concepción. </div>
<div id="Hos_9_12" style="display:none;" class="ver_select"><b>Hos 9:12</b>  Y si llegaren a grandes sus hijos, los quitaré de entre los hombres, porque ¡ay de ellos también, cuando de ellos me aparte! </div>
<div id="Hos_9_13" style="display:none;" class="ver_select"><b>Hos 9:13</b>  Efraín, según veo, es semejante a Tiro, plantado en lugar delicioso; mas Efraín sacará sus hijos al matador. </div>
<div id="Hos_9_14" style="display:none;" class="ver_select"><b>Hos 9:14</b>  Dales, oh Jehová, lo que les has de dar; dales matriz que aborte, y pechos enjutos. </div>
<div id="Hos_9_15" style="display:none;" class="ver_select"><b>Hos 9:15</b>  Toda la maldad de ellos fue en Gilgal; allí, pues, les tomé aversión; por la perversidad de sus obras los echaré de mi casa; no los amaré más; todos sus príncipes son desleales. </div>
<div id="Hos_9_16" style="display:none;" class="ver_select"><b>Hos 9:16</b>  Efraín fue herido, se secó su raíz, no dará más fruto; aunque engendren, yo mataré el amado fruto de su vientre. </div>
<div id="Hos_9_17" style="display:none;" class="ver_select"><b>Hos 9:17</b>  Mi Dios los desechará, porque ellos no le oyeron; y andarán errantes entre las naciones. </div>
<div id=""Hos_10_1 style="display:none;" class="ver_select"><b>Hos 10:1</b>  Israel es una viña vacía que da fruto para sí mismo; conforme a la multiplicación de su fruto multiplicó los altares, conforme a la bondad de su tierra aumentaron sus imágenes. </div>
<div id=""Hos_10_2 style="display:none;" class="ver_select"><b>Hos 10:2</b>  Su corazón está dividido. Ahora serán hallados culpables; Él quebrantará sus altares, asolará sus imágenes. </div>
<div id=""Hos_10_3 style="display:none;" class="ver_select"><b>Hos 10:3</b>  Porque dirán ahora: No tenemos rey, porque no temimos a Jehová: ¿y qué haría el rey por nosotros? </div>
<div id=""Hos_10_4 style="display:none;" class="ver_select"><b>Hos 10:4</b>  Han hablado palabras jurando en vano al hacer pacto; por tanto, el juicio florecerá como ajenjo en los surcos del campo. </div>
<div id=""Hos_10_5 style="display:none;" class="ver_select"><b>Hos 10:5</b>  Por las becerras de Betaven serán atemorizados los moradores de Samaria; porque su pueblo lamentará a causa del becerro, y sus sacerdotes que en él se regocijaban por su gloria, la cual será disipada. </div>
<div id=""Hos_10_6 style="display:none;" class="ver_select"><b>Hos 10:6</b>  Y aun será él llevado a Asiria como presente al rey Jareb: Efraín será avergonzado, e Israel se avergonzará de su propio consejo. </div>
<div id=""Hos_10_7 style="display:none;" class="ver_select"><b>Hos 10:7</b>  De Samaria fue cortado su rey como la espuma sobre la superficie de las aguas. </div>
<div id=""Hos_10_8 style="display:none;" class="ver_select"><b>Hos 10:8</b>  Y los altares de Avén serán destruidos, el pecado de Israel; crecerá sobre sus altares espino y cardo. Y dirán a los montes: Cubridnos; y a los collados: Caed sobre nosotros. </div>
<div id=""Hos_10_9 style="display:none;" class="ver_select"><b>Hos 10:9</b>  Desde los días de Gabaa has pecado, oh Israel; allí estuvieron; no los tomó la batalla en Gabaa contra los inicuos. </div>
<div id=""Hos_10_10 style="display:none;" class="ver_select"><b>Hos 10:10</b>  Cuando yo lo desee, los castigaré; y pueblos se juntarán contra ellos cuando sean atados en sus dos surcos. </div>
<div id=""Hos_10_11 style="display:none;" class="ver_select"><b>Hos 10:11</b>  Efraín es becerra domada, amadora del trillar; mas yo pasaré sobre su lozana cerviz; yo haré llevar yugo a Efraín; arará Judá, quebrará sus terrones Jacob. </div>
<div id=""Hos_10_12 style="display:none;" class="ver_select"><b>Hos 10:12</b>  Sembrad para vosotros en justicia, segad para vosotros en misericordia; arad para vosotros barbecho; porque es tiempo de buscar a Jehová, hasta que venga y os enseñe justicia. </div>
<div id=""Hos_10_13 style="display:none;" class="ver_select"><b>Hos 10:13</b>  Habéis arado impiedad, segasteis iniquidad; comeréis fruto de mentira; porque confiaste en tu camino, en la multitud de tus valientes. </div>
<div id=""Hos_10_14 style="display:none;" class="ver_select"><b>Hos 10:14</b>  Por tanto, en tus pueblos se levantará alboroto, y todas tus fortalezas serán destruidas, como destruyó Salmán a Betarbel el día de la batalla; cuando la madre fue arrojada sobre sus hijos. </div>
<div id=""Hos_10_15 style="display:none;" class="ver_select"><b>Hos 10:15</b>  Así hará a vosotros Betel por causa de vuestra gran maldad; al amanecer será del todo cortado el rey de Israel. </div>
<div id=""Hos_11_1 style="display:none;" class="ver_select"><b>Hos 11:1</b>  Cuando Israel era muchacho, yo lo amé, y de Egipto llamé a mi hijo. </div>
<div id=""Hos_11_2 style="display:none;" class="ver_select"><b>Hos 11:2</b>  Cuanto más los llamaban, así ellos se iban de su presencia; a los Baales sacrificaban, y a los ídolos quemaban incienso. </div>
<div id=""Hos_11_3 style="display:none;" class="ver_select"><b>Hos 11:3</b>  Yo con todo enseñé a caminar a Efraín, tomándolo de los brazos; y no conocieron que yo los cuidaba. </div>
<div id=""Hos_11_4 style="display:none;" class="ver_select"><b>Hos 11:4</b>  Con cuerdas de hombre los atraje, con cuerdas de amor; y fui para ellos como los que alzan el yugo de sobre su cerviz, y puse comida delante de ellos. </div>
<div id=""Hos_11_5 style="display:none;" class="ver_select"><b>Hos 11:5</b>  No volverá a la tierra de Egipto, sino que el asirio será su rey, porque no se quisieron convertir. </div>
<div id=""Hos_11_6 style="display:none;" class="ver_select"><b>Hos 11:6</b>  Y caerá espada sobre sus ciudades, y consumirá sus aldeas; las consumirá a causa de sus propios consejos. </div>
<div id=""Hos_11_7 style="display:none;" class="ver_select"><b>Hos 11:7</b>  Entre tanto, mi pueblo está inclinado a rebelarse contra mí; aunque ellos invocan al Altísimo, ninguno absolutamente quiere enaltecerle. </div>
<div id=""Hos_11_8 style="display:none;" class="ver_select"><b>Hos 11:8</b>  ¿Cómo he de dejarte, oh Efraín? ¿He de entregarte yo, Israel? ¿Cómo podré yo hacerte como Adma, o ponerte como a Zeboim? Mi corazón se conmueve dentro de mí, se inflama toda mi compasión. </div>
<div id=""Hos_11_9 style="display:none;" class="ver_select"><b>Hos 11:9</b>  No ejecutaré el furor de mi ira, no volveré para destruir a Efraín; porque Dios soy, y no hombre; el Santo en medio de ti; y no entraré en la ciudad. </div>
<div id=""Hos_11_10 style="display:none;" class="ver_select"><b>Hos 11:10</b>  En pos de Jehová caminarán; Él rugirá como león; cual león rugirá Él de cierto, y los hijos se moverán azorados del occidente. </div>
<div id=""Hos_11_11 style="display:none;" class="ver_select"><b>Hos 11:11</b>  Como ave se moverán velozmente de Egipto, y de la tierra de Asiria como paloma; y los pondré en sus casas, dice Jehová. </div>
<div id=""Hos_11_12 style="display:none;" class="ver_select"><b>Hos 11:12</b>  Efraín me ha rodeado con mentira, y la casa de Israel con engaño; mas Judá aún gobierna con Dios, y es fiel con los santos. </div>
<div id=""Hos_12_1 style="display:none;" class="ver_select"><b>Hos 12:1</b>  Efraín se apacienta de viento, y sigue al viento solano; mentira y destrucción aumenta continuamente; porque hicieron alianza con los asirios, y el aceite es llevado a Egipto. </div>
<div id=""Hos_12_2 style="display:none;" class="ver_select"><b>Hos 12:2</b>  Pleito tiene Jehová con Judá para castigar a Jacob conforme a sus caminos: le pagará conforme a sus obras. </div>
<div id=""Hos_12_3 style="display:none;" class="ver_select"><b>Hos 12:3</b>  En el vientre tomó por el calcañar a su hermano, y con su poder luchó con Dios. </div>
<div id=""Hos_12_4 style="display:none;" class="ver_select"><b>Hos 12:4</b>  Sí, luchó con el Ángel, y prevaleció; lloró, y le rogó; en Betel le encontró, y allí habló con nosotros. </div>
<div id=""Hos_12_5 style="display:none;" class="ver_select"><b>Hos 12:5</b>  Mas Jehová es Dios de los ejércitos: Jehová es su memorial. </div>
<div id=""Hos_12_6 style="display:none;" class="ver_select"><b>Hos 12:6</b>  Tú, pues, vuélvete a tu Dios; guarda misericordia y juicio, y en tu Dios espera siempre. </div>
<div id=""Hos_12_7 style="display:none;" class="ver_select"><b>Hos 12:7</b>  Es mercader que tiene en su mano peso falso, amador de opresión. </div>
<div id=""Hos_12_8 style="display:none;" class="ver_select"><b>Hos 12:8</b>  Y dijo Efraín: Ciertamente yo he enriquecido, he hallado riquezas para mí: nadie hallará en mí iniquidad, ni pecado en todos mis trabajos. </div>
<div id=""Hos_12_9 style="display:none;" class="ver_select"><b>Hos 12:9</b>  Pero yo soy Jehová tu Dios desde la tierra de Egipto; aún te haré morar en tiendas, como en los días de la fiesta. </div>
<div id=""Hos_12_10 style="display:none;" class="ver_select"><b>Hos 12:10</b>  Y he hablado a los profetas, y yo aumenté la profecía, y por medio de los profetas puse semejanzas. </div>
<div id=""Hos_12_11 style="display:none;" class="ver_select"><b>Hos 12:11</b>  ¿Hay iniquidad en Galaad? Ciertamente vanidad han sido; en Gilgal sacrificaron bueyes; y aún sus altares son como montones en los surcos del campo. </div>
<div id=""Hos_12_12 style="display:none;" class="ver_select"><b>Hos 12:12</b>  Mas Jacob huyó a tierra de Aram, y sirvió Israel por esposa, y por esposa fue pastor. </div>
<div id=""Hos_12_13 style="display:none;" class="ver_select"><b>Hos 12:13</b>  Y por un profeta hizo subir Jehová a Israel de Egipto, y por un profeta fue preservado. </div>
<div id=""Hos_12_14 style="display:none;" class="ver_select"><b>Hos 12:14</b>  Efraín ha provocado a Dios con amarguras; por tanto, su sangre se derramará sobre él, y su Señor le pagará su oprobio. </div>
<div id=""Hos_13_1 style="display:none;" class="ver_select"><b>Hos 13:1</b>  Cuando Efraín hablaba, hubo temor; se exaltó en Israel; mas pecó en Baal, y murió. </div>
<div id=""Hos_13_2 style="display:none;" class="ver_select"><b>Hos 13:2</b>  Y ahora añadieron a su pecado, y de su plata se han hecho según su entendimiento, estatuas de fundición, ídolos, toda obra de artífices; acerca de los cuales dicen a los hombres que sacrifican, que besen los becerros. </div>
<div id=""Hos_13_3 style="display:none;" class="ver_select"><b>Hos 13:3</b>  Por tanto serán como la niebla de la mañana, y como el rocío de la madrugada que se pasa; como el tamo que la tempestad arroja de la era, y como el humo que sale de la chimenea. </div>
<div id=""Hos_13_4 style="display:none;" class="ver_select"><b>Hos 13:4</b>  Mas yo soy Jehová tu Dios desde la tierra de Egipto; no conocerás dios fuera de mí, ni otro salvador sino a mí. </div>
<div id=""Hos_13_5 style="display:none;" class="ver_select"><b>Hos 13:5</b>  Yo te conocí en el desierto, en tierra seca. </div>
<div id=""Hos_13_6 style="display:none;" class="ver_select"><b>Hos 13:6</b>  En sus pastos se saciaron, se llenaron, y se ensoberbeció su corazón; por esta causa se olvidaron de mí. </div>
<div id=""Hos_13_7 style="display:none;" class="ver_select"><b>Hos 13:7</b>  Por tanto, yo seré para ellos como león; como un leopardo en el camino los espiaré. </div>
<div id=""Hos_13_8 style="display:none;" class="ver_select"><b>Hos 13:8</b>  Como osa que ha sido privada de sus cachorros los encontraré, y desgarraré las telas de su corazón, y allí los devoraré como león; fiera del campo los despedazará. 895 </div>
<div id=""Hos_13_9 style="display:none;" class="ver_select"><b>Hos 13:9</b>  Te destruiste a ti mismo, oh Israel, mas en mí está tu ayuda. </div>
<div id=""Hos_13_10 style="display:none;" class="ver_select"><b>Hos 13:10</b>  ¿Dónde está tu rey, para que te salve con todas tus ciudades; y tus jueces, de los cuales dijiste: Dame rey y príncipes? </div>
<div id=""Hos_13_11 style="display:none;" class="ver_select"><b>Hos 13:11</b>  Te di rey en mi furor, y lo quité en mi ira. </div>
<div id=""Hos_13_12 style="display:none;" class="ver_select"><b>Hos 13:12</b>  Atada está la maldad de Efraín; su pecado está guardado. </div>
<div id=""Hos_13_13 style="display:none;" class="ver_select"><b>Hos 13:13</b>  Dolores de mujer de parto le vendrán; es un hijo no sabio, que de otra manera no se detuviera tanto en el tiempo del nacimiento de los hijos. </div>
<div id=""Hos_13_14 style="display:none;" class="ver_select"><b>Hos 13:14</b>  De la mano del sepulcro los redimiré, los libraré de la muerte. Oh muerte, yo seré tu muerte; y seré tu destrucción, oh sepulcro; el arrepentimiento será escondido de mis ojos. </div>
<div id=""Hos_13_15 style="display:none;" class="ver_select"><b>Hos 13:15</b>  Aunque él fructifique entre sus hermanos, vendrá el solano, viento de Jehová, subiendo de la parte del desierto, y se secará su manantial, y se agotará su fuente; él saqueará el tesoro de todos los vasos preciosos. </div>
<div id=""Hos_13_16 style="display:none;" class="ver_select"><b>Hos 13:16</b>  Samaria será asolada, porque se rebeló contra su Dios; caerán a espada; sus niños serán estrellados, y sus mujeres encintas serán abiertas. </div>
<div id=""Hos_14_1 style="display:none;" class="ver_select"><b>Hos 14:1</b>  Vuelve, oh Israel, a Jehová tu Dios; pues por tu pecado has caído. </div>
<div id=""Hos_14_2 style="display:none;" class="ver_select"><b>Hos 14:2</b>  Tomad con vosotros palabras, y volved a Jehová, y decidle: Quita toda iniquidad, y acéptanos con gracia, y daremos becerros de nuestros labios. </div>
<div id=""Hos_14_3 style="display:none;" class="ver_select"><b>Hos 14:3</b>  No nos librará Asiria; no montaremos sobre caballos, ni nunca más diremos a la obra de nuestras manos: Vosotros sois nuestros dioses; porque en ti el huérfano alcanzará misericordia. </div>
<div id=""Hos_14_4 style="display:none;" class="ver_select"><b>Hos 14:4</b>  Yo sanaré su rebelión, los amaré de pura gracia; porque mi ira se apartó de ellos. </div>
<div id=""Hos_14_5 style="display:none;" class="ver_select"><b>Hos 14:5</b>  Yo seré a Israel como rocío; él florecerá como lirio, y extenderá sus raíces como el Líbano. </div>
<div id=""Hos_14_6 style="display:none;" class="ver_select"><b>Hos 14:6</b>  Se extenderán sus ramas, y será su gloria como la del olivo, y su fragancia como el Líbano. </div>
<div id=""Hos_14_7 style="display:none;" class="ver_select"><b>Hos 14:7</b>  Volverán, y se sentarán bajo su sombra; serán vivificados como trigo, y florecerán como la vid; su olor será como el del vino del Líbano. </div>
<div id=""Hos_14_8 style="display:none;" class="ver_select"><b>Hos 14:8</b>  Efraín dirá: ¿Qué más tendré ya con los ídolos? Yo lo oiré, y miraré; yo seré a él como el ciprés verde; de mí será hallado tu fruto. </div>
<div id=""Hos_14_9 style="display:none;" class="ver_select"><b>Hos 14:9</b>  ¿Quién es sabio para que entienda esto, y prudente para que lo sepa? Porque los caminos de Jehová son rectos, y los justos andarán por ellos; mas los rebeldes tropezarán en ellos. </div>
