<div id="Joe_1_1" style="display:none;" class="ver_select"><b>Joe 1:1</b>  Palabra de Jehová que vino a Joel hijo de Petuel. </div>
<div id="Joe_1_2" style="display:none;" class="ver_select"><b>Joe 1:2</b>  Oíd esto, ancianos, y escuchad, todos los moradores de la tierra. ¿Ha acontecido esto en vuestros días, o en los días de vuestros padres? </div>
<div id="Joe_1_3" style="display:none;" class="ver_select"><b>Joe 1:3</b>  De esto contaréis a vuestros hijos, y vuestros hijos a sus hijos, y sus hijos a la otra generación. </div>
<div id="Joe_1_4" style="display:none;" class="ver_select"><b>Joe 1:4</b>  Lo que quedó de la oruga comió la langosta, y lo que quedó de la langosta comió el pulgón; y el revoltón comió lo que del pulgón había quedado. </div>
<div id="Joe_1_5" style="display:none;" class="ver_select"><b>Joe 1:5</b>  Despertad, borrachos, y llorad; aullad todos los que bebéis vino, a causa del mosto, porque os es quitado de vuestra boca. </div>
<div id="Joe_1_6" style="display:none;" class="ver_select"><b>Joe 1:6</b>  Porque nación fuerte y sin número subió a mi tierra; sus dientes, dientes de león, y sus muelas, de león. </div>
<div id="Joe_1_7" style="display:none;" class="ver_select"><b>Joe 1:7</b>  Asoló mi vid, y descortezó mi higuera; del todo la desnudó y derribó: sus ramas quedaron blancas. </div>
<div id="Joe_1_8" style="display:none;" class="ver_select"><b>Joe 1:8</b>  Llora tú como virgen vestida de cilicio por el marido de su juventud. </div>
<div id="Joe_1_9" style="display:none;" class="ver_select"><b>Joe 1:9</b>  La ofrenda y la libación han desaparecido de la casa de Jehová; los sacerdotes ministros de Jehová están de duelo. </div>
<div id="Joe_1_10" style="display:none;" class="ver_select"><b>Joe 1:10</b>  El campo fue destruido, se enlutó la tierra; porque el trigo fue destruido, se secó el mosto, languideció el aceite. </div>
<div id="Joe_1_11" style="display:none;" class="ver_select"><b>Joe 1:11</b>  Confundíos, labradores, aullad, viñeros, por el trigo y la cebada; porque se perdió la mies del campo. </div>
<div id="Joe_1_12" style="display:none;" class="ver_select"><b>Joe 1:12</b>  Se secó la vid, se marchitó la higuera, el granado también, la palmera y el manzano; se secaron todos los árboles del campo; por lo cual se secó el gozo de los hijos de los hombres. </div>
<div id="Joe_1_13" style="display:none;" class="ver_select"><b>Joe 1:13</b>  Ceñíos y lamentad, sacerdotes; aullad, ministros del altar; venid, dormid en cilicio, ministros de mi Dios; porque quitada es de la casa de vuestro Dios la ofrenda y la libación. </div>
<div id="Joe_1_14" style="display:none;" class="ver_select"><b>Joe 1:14</b>  Pregonad ayuno, convocad a asamblea; congregad a los ancianos y a todos los moradores de la tierra en la casa de Jehová vuestro Dios, y clamad a Jehová. </div>
<div id="Joe_1_15" style="display:none;" class="ver_select"><b>Joe 1:15</b>  ¡Ay del día! porque cercano está el día de Jehová, y vendrá como destrucción por el Todopoderoso. </div>
<div id="Joe_1_16" style="display:none;" class="ver_select"><b>Joe 1:16</b>  ¿No fue quitado el alimento de delante de nuestros ojos, la alegría y el placer de la casa de nuestro Dios? </div>
<div id="Joe_1_17" style="display:none;" class="ver_select"><b>Joe 1:17</b>  El grano se pudrió debajo de los terrones, los graneros fueron asolados, los alfolíes destruidos; porque se secó el trigo. </div>
<div id="Joe_1_18" style="display:none;" class="ver_select"><b>Joe 1:18</b>  ¡Cómo gimieron las bestias! ¡Cuán turbados anduvieron los hatos de los bueyes, porque no tuvieron pastos! también fueron asolados los rebaños de las ovejas. </div>
<div id="Joe_1_19" style="display:none;" class="ver_select"><b>Joe 1:19</b>  A ti, oh Jehová, clamaré: porque fuego consumió los pastos del desierto, y llama abrasó todos los árboles del campo. </div>
<div id="Joe_1_20" style="display:none;" class="ver_select"><b>Joe 1:20</b>  Las bestias del campo braman también a ti; porque se secaron los arroyos de las aguas, y fuego consumió las praderías del desierto. </div>
<div id="Joe_2_1" style="display:none;" class="ver_select"><b>Joe 2:1</b>  Tocad trompeta en Sión, y pregonad en mi santo monte: tiemblen todos los moradores de la tierra; porque viene el día de Jehová, porque está cercano. </div>
<div id="Joe_2_2" style="display:none;" class="ver_select"><b>Joe 2:2</b>  Día de tinieblas y de oscuridad, día de nube y de sombra, que sobre los montes se extiende como el alba; un pueblo grande y fuerte; nunca desde el siglo fue semejante, ni después de él será jamás en años de generación en generación. </div>
<div id="Joe_2_3" style="display:none;" class="ver_select"><b>Joe 2:3</b>  Delante de él consumirá fuego, tras de él abrasará llama; como el huerto del Edén será la tierra delante de él, y detrás de él como desierto asolado; ni tampoco habrá quien de él escape. </div>
<div id="Joe_2_4" style="display:none;" class="ver_select"><b>Joe 2:4</b>  Su parecer, como parecer de caballos; y como gente de a caballo correrán. </div>
<div id="Joe_2_5" style="display:none;" class="ver_select"><b>Joe 2:5</b>  Como estruendo de carros saltarán sobre las cumbres de los montes; como sonido de llama de fuego que consume hojarascas, como pueblo fuerte dispuesto para la batalla. </div>
<div id="Joe_2_6" style="display:none;" class="ver_select"><b>Joe 2:6</b>  Delante de él temerán los pueblos, se pondrán mustios todos los semblantes. </div>
<div id="Joe_2_7" style="display:none;" class="ver_select"><b>Joe 2:7</b>  Como valientes correrán, como hombres de guerra subirán la muralla; y cada cual irá en sus caminos, y no torcerán sus sendas. </div>
<div id="Joe_2_8" style="display:none;" class="ver_select"><b>Joe 2:8</b>  Ninguno oprimirá a su compañero, cada uno irá por su sendero; y aun cayendo sobre la espada no se herirán. </div>
<div id="Joe_2_9" style="display:none;" class="ver_select"><b>Joe 2:9</b>  Irán por la ciudad, correrán por el muro, subirán por las casas, entrarán por las ventanas a manera de ladrones. </div>
<div id="Joe_2_10" style="display:none;" class="ver_select"><b>Joe 2:10</b>  Delante de él temblará la tierra, se estremecerán los cielos; el sol y la luna se oscurecerán, y las estrellas retraerán su resplandor. </div>
<div id="Joe_2_11" style="display:none;" class="ver_select"><b>Joe 2:11</b>  Y Jehová dará su voz delante de su ejército; porque muy grande es su campamento, fuerte es el que ejecuta su palabra; porque grande es el día de Jehová, y muy terrible; ¿y quién podrá soportarlo? </div>
<div id="Joe_2_12" style="display:none;" class="ver_select"><b>Joe 2:12</b>  Por eso pues, ahora, dice Jehová: Convertíos a mí con todo vuestro corazón, con ayuno y lloro y lamento. </div>
<div id="Joe_2_13" style="display:none;" class="ver_select"><b>Joe 2:13</b>  Rasgad vuestro corazón, y no vuestras vestiduras; y convertíos a Jehová vuestro Dios; porque Él es misericordioso y clemente, tardo para la ira, y grande en misericordia, y que se arrepiente del castigo. </div>
<div id="Joe_2_14" style="display:none;" class="ver_select"><b>Joe 2:14</b>  ¿Quién sabe si volverá y se apiadará y dejará bendición tras sí, es decir, ofrenda y libación para Jehová Dios vuestro? </div>
<div id="Joe_2_15" style="display:none;" class="ver_select"><b>Joe 2:15</b>  Tocad trompeta en Sión, pregonad ayuno, llamad a congregación. </div>
<div id="Joe_2_16" style="display:none;" class="ver_select"><b>Joe 2:16</b>  Reunid el pueblo, santificad la reunión, juntad a los ancianos, congregad a los niños y a los que maman; salga de su cámara el novio, y de su tálamo la novia. </div>
<div id="Joe_2_17" style="display:none;" class="ver_select"><b>Joe 2:17</b>  Entre la entrada y el altar, lloren los sacerdotes, ministros de Jehová, y digan: Perdona, oh Jehová, a tu pueblo, y no pongas en oprobio tu heredad, para que las gentes se enseñoreen de ella. ¿Por qué han de decir entre los pueblos: Dónde está su Dios? </div>
<div id="Joe_2_18" style="display:none;" class="ver_select"><b>Joe 2:18</b>  Entonces Jehová celará su tierra, y perdonará a su pueblo. </div>
<div id="Joe_2_19" style="display:none;" class="ver_select"><b>Joe 2:19</b>  Y responderá Jehová, y dirá a su pueblo: He aquí yo os enviaré trigo, mosto y aceite, y seréis saciados de ellos; y nunca más os pondré en oprobio entre las gentes. </div>
<div id="Joe_2_20" style="display:none;" class="ver_select"><b>Joe 2:20</b>  Y haré alejar de vosotros al ejército del norte, y lo echaré en la tierra seca y desierta: su faz será hacia el mar oriental, y su fin al mar occidental, y exhalará su hedor; y subirá su pudrición, porque hizo grandes cosas. </div>
<div id="Joe_2_21" style="display:none;" class="ver_select"><b>Joe 2:21</b>  Tierra, no temas; alégrate y gózate: porque Jehová ha de hacer grandes cosas. </div>
<div id="Joe_2_22" style="display:none;" class="ver_select"><b>Joe 2:22</b>  Animales del campo, no temáis; porque los pastos del desierto reverdecerán, porque los árboles llevarán su fruto, la higuera y la vid darán sus frutos. </div>
<div id="Joe_2_23" style="display:none;" class="ver_select"><b>Joe 2:23</b>  Vosotros también, hijos de Sión, alegraos y gozaos en Jehová vuestro Dios; porque os ha dado la primera lluvia moderadamente, y hará descender sobre vosotros lluvia temprana y tardía como al principio. </div>
<div id="Joe_2_24" style="display:none;" class="ver_select"><b>Joe 2:24</b>  Y las eras se llenarán de trigo, y los lagares rebosarán de vino y aceite. </div>
<div id="Joe_2_25" style="display:none;" class="ver_select"><b>Joe 2:25</b>  Y os restituiré los años que comió la oruga, la langosta, el pulgón, y el revoltón; mi grande ejército que envié contra vosotros. </div>
<div id="Joe_2_26" style="display:none;" class="ver_select"><b>Joe 2:26</b>  Y comeréis hasta saciaros, y alabaréis el nombre de Jehová vuestro Dios, el cual hizo maravillas con vosotros; y mi pueblo nunca más será avergonzado. </div>
<div id="Joe_2_27" style="display:none;" class="ver_select"><b>Joe 2:27</b>  Y conoceréis que en medio de Israel estoy yo, y que yo soy Jehová vuestro Dios, y no hay otro: y mi pueblo nunca más será avergonzado. </div>
<div id="Joe_2_28" style="display:none;" class="ver_select"><b>Joe 2:28</b>  Y será que después de esto, derramaré mi Espíritu sobre toda carne, y profetizarán vuestros hijos y vuestras hijas; vuestros viejos soñarán sueños, y vuestros jóvenes verán visiones. </div>
<div id="Joe_2_29" style="display:none;" class="ver_select"><b>Joe 2:29</b>  Y también sobre los siervos y sobre las siervas derramaré mi Espíritu en aquellos días. </div>
<div id="Joe_2_30" style="display:none;" class="ver_select"><b>Joe 2:30</b>  Y daré prodigios en el cielo y en la tierra, sangre, y fuego, y columnas de humo. </div>
<div id="Joe_2_31" style="display:none;" class="ver_select"><b>Joe 2:31</b>  El sol se tornará en tinieblas, y la luna en sangre, antes que venga el día grande y espantoso de Jehová. </div>
<div id="Joe_2_32" style="display:none;" class="ver_select"><b>Joe 2:32</b>  Y será que cualquiera que invocare el nombre de Jehová, será salvo; porque en el monte de Sión y en Jerusalén habrá salvación, como Jehová ha dicho, y en los que quedaren, a los cuales Jehová habrá llamado. </div>
<div id="Joe_3_1" style="display:none;" class="ver_select"><b>Joe 3:1</b>  Porque he aquí que en aquellos días, y en aquel tiempo en que haré volver la cautividad de Judá y de Jerusalén, </div>
<div id="Joe_3_2" style="display:none;" class="ver_select"><b>Joe 3:2</b>  reuniré a todas las naciones, y las haré descender al valle de Josafat, y allí entraré en juicio con ellas a causa de mi pueblo, y de Israel mi heredad, a los cuales esparcieron entre las naciones, y repartieron mi tierra; </div>
<div id="Joe_3_3" style="display:none;" class="ver_select"><b>Joe 3:3</b>  y echaron suertes sobre mi pueblo, y a los niños dieron por una ramera, y vendieron las niñas por vino para beber. </div>
<div id="Joe_3_4" style="display:none;" class="ver_select"><b>Joe 3:4</b>  Y también, ¿qué tengo yo con vosotras, Tiro y Sidón, y todos los términos de Filistea? ¿Queréis vengaros de mí? Y si de mí os vengáis, bien pronto haré yo recaer la paga sobre vuestra cabeza. </div>
<div id="Joe_3_5" style="display:none;" class="ver_select"><b>Joe 3:5</b>  Porque habéis llevado mi plata y mi oro, y mis cosas preciosas y hermosas metisteis en vuestros templos; </div>
<div id="Joe_3_6" style="display:none;" class="ver_select"><b>Joe 3:6</b>  y vendisteis los hijos de Judá y los hijos de Jerusalén a los hijos de los griegos, para alejarlos de sus términos. </div>
<div id="Joe_3_7" style="display:none;" class="ver_select"><b>Joe 3:7</b>  He aquí los levantaré yo del lugar donde los vendisteis, y volveré vuestra paga sobre vuestra cabeza. </div>
<div id="Joe_3_8" style="display:none;" class="ver_select"><b>Joe 3:8</b>  Y venderé vuestros hijos y vuestras hijas en la mano de los hijos de Judá, y ellos los venderán a los sabeos, nación lejana; porque Jehová ha hablado. </div>
<div id="Joe_3_9" style="display:none;" class="ver_select"><b>Joe 3:9</b>  Pregonad esto entre las naciones, proclamad guerra, despertad a los valientes, acérquense, vengan todos los hombres de guerra. </div>
<div id="Joe_3_10" style="display:none;" class="ver_select"><b>Joe 3:10</b>  Haced espadas de vuestros azadones, lanzas de vuestras hoces; diga el débil: Fuerte soy. </div>
<div id="Joe_3_11" style="display:none;" class="ver_select"><b>Joe 3:11</b>  Juntaos y venid, gentes todas de alrededor, y congregaos; haz venir allí, oh Jehová, tus fuertes. </div>
<div id="Joe_3_12" style="display:none;" class="ver_select"><b>Joe 3:12</b>  Las gentes se despierten, y suban al valle de Josafat; porque allí me sentaré para juzgar todas las gentes de alrededor. </div>
<div id="Joe_3_13" style="display:none;" class="ver_select"><b>Joe 3:13</b>  Echad la hoz, porque la mies está ya madura. Venid, descended; porque el lagar está lleno, rebosan las lagaretas; porque grande es la maldad de ellos. </div>
<div id="Joe_3_14" style="display:none;" class="ver_select"><b>Joe 3:14</b>  Multitudes, multitudes en el valle de la decisión; porque cercano está el día de Jehová en el valle de la decisión. </div>
<div id="Joe_3_15" style="display:none;" class="ver_select"><b>Joe 3:15</b>  El sol y la luna se oscurecerán, y las estrellas retraerán su resplandor. </div>
<div id="Joe_3_16" style="display:none;" class="ver_select"><b>Joe 3:16</b>  Jehová rugirá desde Sión, y dará su voz desde Jerusalén, y temblarán los cielos y la tierra; mas Jehová será la esperanza de su pueblo, y la fortaleza de los hijos de Israel. </div>
<div id="Joe_3_17" style="display:none;" class="ver_select"><b>Joe 3:17</b>  Y conoceréis que yo soy Jehová vuestro Dios, que habito en Sión, monte de mi santidad; y será Jerusalén santa, y extraños no pasarán más por ella. </div>
<div id="Joe_3_18" style="display:none;" class="ver_select"><b>Joe 3:18</b>  Y será en aquel tiempo, que los montes destilarán mosto, y los collados fluirán leche, y por todos los arroyos de Judá correrán aguas; y saldrá una fuente de la casa de Jehová, y regará el valle de Sitim. </div>
<div id="Joe_3_19" style="display:none;" class="ver_select"><b>Joe 3:19</b>  Egipto será destruido, y Edom será vuelto en desierto asolado, por la injuria hecha a los hijos de Judá; porque derramaron en su tierra la sangre inocente. </div>
<div id="Joe_3_20" style="display:none;" class="ver_select"><b>Joe 3:20</b>  Mas Judá para siempre será habitada, y Jerusalén por generación y generación. </div>
<div id="Joe_3_21" style="display:none;" class="ver_select"><b>Joe 3:21</b>  Y limpiaré su sangre que aún no he limpiado; y Jehová morará en Sión. </div>
