<div id="Jon_1_1" style="display:none;" class="ver_select"><b>Jon 1:1</b>  Y la palabra de Jehová vino a Jonás, hijo de Amitai, diciendo: </div>
<div id="Jon_1_2" style="display:none;" class="ver_select"><b>Jon 1:2</b>  Levántate, y ve a Nínive, la gran ciudad, y pregona contra ella; porque su maldad ha subido delante de mí. </div>
<div id="Jon_1_3" style="display:none;" class="ver_select"><b>Jon 1:3</b>  Y Jonás se levantó para huir de la presencia de Jehová a Tarsis, y descendió a Jope; y halló un navío que partía para Tarsis; y pagando su pasaje, entró en él para irse con ellos a Tarsis de delante de Jehová. </div>
<div id="Jon_1_4" style="display:none;" class="ver_select"><b>Jon 1:4</b>  Mas Jehová hizo levantar un gran viento en el mar, y se hizo una tan gran tempestad en el mar, que se pensó se rompería la nave. </div>
<div id="Jon_1_5" style="display:none;" class="ver_select"><b>Jon 1:5</b>  Y los marineros tuvieron miedo, y cada uno llamaba a su dios; y echaron al mar los enseres que había en la nave, para descargarla de ellos. Pero Jonás se había bajado a los lados del buque, y se había echado a dormir. </div>
<div id="Jon_1_6" style="display:none;" class="ver_select"><b>Jon 1:6</b>  Y el maestre de la nave vino a él y le dijo: ¿Qué tienes, dormilón? Levántate, y clama a tu Dios; quizá Dios tendrá compasión de nosotros, y no pereceremos. </div>
<div id="Jon_1_7" style="display:none;" class="ver_select"><b>Jon 1:7</b>  Y dijeron cada uno a su compañero: Venid, y echemos suertes, para saber por quién nos ha venido este mal. Y echaron suertes, y la suerte cayó sobre Jonás. </div>
<div id="Jon_1_8" style="display:none;" class="ver_select"><b>Jon 1:8</b>  Entonces le dijeron ellos: Decláranos ahora por qué nos ha venido este mal. ¿Qué oficio tienes, y de dónde vienes? ¿Cuál es tu tierra, y de qué pueblo eres? </div>
<div id="Jon_1_9" style="display:none;" class="ver_select"><b>Jon 1:9</b>  Y él les respondió: Soy hebreo, y temo a Jehová, Dios de los cielos, que hizo el mar y la tierra. </div>
<div id="Jon_1_10" style="display:none;" class="ver_select"><b>Jon 1:10</b>  Y aquellos hombres temieron sobremanera, y le dijeron: ¿Por qué has hecho esto? Porque ellos entendieron que huía de delante de Jehová, porque él se los había declarado. </div>
<div id="Jon_1_11" style="display:none;" class="ver_select"><b>Jon 1:11</b>  Y le dijeron: ¿Qué te haremos, para que el mar se nos aquiete? porque el mar se embravecía más y más. </div>
<div id="Jon_1_12" style="display:none;" class="ver_select"><b>Jon 1:12</b>  Él les respondió: Tomadme, y echadme al mar, y el mar se os aquietará; porque yo sé que por mi causa ha venido esta grande tempestad sobre vosotros. </div>
<div id="Jon_1_13" style="display:none;" class="ver_select"><b>Jon 1:13</b>  Y aquellos hombres trabajaron por tornar la nave a tierra; mas no pudieron, porque el mar iba a más, y se embravecía sobre ellos. </div>
<div id="Jon_1_14" style="display:none;" class="ver_select"><b>Jon 1:14</b>  Entonces clamaron a Jehová, y dijeron: Te rogamos oh Jehová, te rogamos, no dejes que perezcamos por la vida de este hombre, ni pongas sobre nosotros la sangre inocente: porque tú, oh Jehová, has hecho como has querido. </div>
<div id="Jon_1_15" style="display:none;" class="ver_select"><b>Jon 1:15</b>  Y tomaron a Jonás, y lo echaron al mar; y el mar se aquietó de su furia. </div>
<div id="Jon_1_16" style="display:none;" class="ver_select"><b>Jon 1:16</b>  Y temieron aquellos hombres a Jehová con gran temor; y ofrecieron sacrificio a Jehová, y prometieron votos. </div>
<div id="Jon_1_17" style="display:none;" class="ver_select"><b>Jon 1:17</b>  Pero Jehová había prevenido un gran pez que tragase a Jonás: y estuvo Jonás en el vientre del pez tres días y tres noches. </div>
<div id="Jon_2_1" style="display:none;" class="ver_select"><b>Jon 2:1</b>  Entonces oró Jonás a Jehová su Dios desde el vientre del pez, </div>
<div id="Jon_2_2" style="display:none;" class="ver_select"><b>Jon 2:2</b>  y dijo: Clamé de mi tribulación a Jehová, y Él me oyó; Del vientre del infierno clamé, y mi voz oíste. </div>
<div id="Jon_2_3" style="display:none;" class="ver_select"><b>Jon 2:3</b>  Me echaste en el profundo, en medio de los mares, y me rodeó la corriente; Todas tus ondas y tus olas pasaron sobre mí. </div>
<div id="Jon_2_4" style="display:none;" class="ver_select"><b>Jon 2:4</b>  Y yo dije: Echado soy de delante de tus ojos: Mas aun veré tu santo templo. </div>
<div id="Jon_2_5" style="display:none;" class="ver_select"><b>Jon 2:5</b>  Las aguas me rodearon hasta el alma, me rodeó el abismo; Las algas se enredaron a mi cabeza. </div>
<div id="Jon_2_6" style="display:none;" class="ver_select"><b>Jon 2:6</b>  Descendí a los cimientos de los montes; La tierra echó sus cerraduras sobre mí para siempre: Mas tú sacaste mi vida de la corrupción, oh Jehová Dios mío. </div>
<div id="Jon_2_7" style="display:none;" class="ver_select"><b>Jon 2:7</b>  Cuando mi alma desfallecía en mí, me acordé de Jehová; Y mi oración entró hasta ti en tu santo templo. </div>
<div id="Jon_2_8" style="display:none;" class="ver_select"><b>Jon 2:8</b>  Los que guardan las vanidades ilusorias, su misericordia abandonan. </div>
<div id="Jon_2_9" style="display:none;" class="ver_select"><b>Jon 2:9</b>  Pero yo con voz de acción de gracias te ofreceré sacrificios; Pagaré lo que prometí. La salvación pertenece a Jehová. </div>
<div id="Jon_2_10" style="display:none;" class="ver_select"><b>Jon 2:10</b>  Y mandó Jehová al pez, y vomitó a Jonás en tierra seca. </div>
<div id="Jon_3_1" style="display:none;" class="ver_select"><b>Jon 3:1</b>  Y vino palabra de Jehová segunda vez a Jonás, diciendo: </div>
<div id="Jon_3_2" style="display:none;" class="ver_select"><b>Jon 3:2</b>  Levántate, y ve a Nínive, aquella gran ciudad, y predica en ella el mensaje que yo te diré.  </div>
<div id="Jon_3_3" style="display:none;" class="ver_select"><b>Jon 3:3</b>  Y se levantó Jonás, y fue a Nínive, conforme a la palabra de Jehová. Y era Nínive ciudad sobremanera grande, de tres días de camino. </div>
<div id="Jon_3_4" style="display:none;" class="ver_select"><b>Jon 3:4</b>  Y comenzó Jonás a entrar por la ciudad, camino de un día, y pregonaba diciendo: De aquí a cuarenta días Nínive será destruida. </div>
<div id="Jon_3_5" style="display:none;" class="ver_select"><b>Jon 3:5</b>  Y los hombres de Nínive creyeron a Dios, y pregonaron ayuno, y se vistieron de cilicio desde el mayor de ellos hasta el menor de ellos. </div>
<div id="Jon_3_6" style="display:none;" class="ver_select"><b>Jon 3:6</b>  Y llegó la noticia hasta el rey de Nínive, y se levantó de su silla, y echó de sí su vestidura, y se cubrió de cilicio, y se sentó sobre ceniza. </div>
<div id="Jon_3_7" style="display:none;" class="ver_select"><b>Jon 3:7</b>  E hizo pregonar y anunciar en Nínive, por mandato del rey y de sus grandes, diciendo: Hombres y animales, bueyes y ovejas, no gusten cosa alguna, no se les dé alimento, ni beban agua; </div>
<div id="Jon_3_8" style="display:none;" class="ver_select"><b>Jon 3:8</b>  y que se cubran de cilicio los hombres y los animales, y clamen a Dios fuertemente: y conviértase cada uno de su mal camino, de la rapiña que está en sus manos. </div>
<div id="Jon_3_9" style="display:none;" class="ver_select"><b>Jon 3:9</b>  ¿Quién sabe si se volverá y arrepentirá Dios, y se apartará del furor de su ira, y no pereceremos? </div>
<div id="Jon_3_10" style="display:none;" class="ver_select"><b>Jon 3:10</b>  Y vio Dios lo que hicieron, que se convirtieron de su mal camino; y se arrepintió del mal que había dicho que les había de hacer, y no lo hizo. </div>
<div id="Jon_4_1" style="display:none;" class="ver_select"><b>Jon 4:1</b>  Pero esto desagradó a Jonás en gran manera, y se enojó. </div>
<div id="Jon_4_2" style="display:none;" class="ver_select"><b>Jon 4:2</b>  Y oró a Jehová, y dijo: Ahora, oh Jehová, ¿no es esto lo que yo decía estando aún en mi tierra? Por eso me precaví huyendo a Tarsis; porque sabía yo que tú eres Dios clemente y piadoso, tardo en enojarte, y de grande misericordia, y que te arrepientes del mal. </div>
<div id="Jon_4_3" style="display:none;" class="ver_select"><b>Jon 4:3</b>  Ahora pues, oh Jehová, te ruego que me quites la vida; porque mejor me es la muerte que la vida. </div>
<div id="Jon_4_4" style="display:none;" class="ver_select"><b>Jon 4:4</b>  Y Jehová le dijo: ¿Haces tú bien en enojarte tanto? </div>
<div id="Jon_4_5" style="display:none;" class="ver_select"><b>Jon 4:5</b>  Entonces salió Jonás de la ciudad, y asentó hacia el oriente de la ciudad, y se hizo allí un cobertizo, y se sentó debajo de él a la sombra, hasta ver qué sería de la ciudad. </div>
<div id="Jon_4_6" style="display:none;" class="ver_select"><b>Jon 4:6</b>  Y preparó Jehová Dios una calabacera, la cual creció sobre Jonás para que hiciese sombra sobre su cabeza, y le librase de su mal; y Jonás se alegró grandemente por la calabacera. </div>
<div id="Jon_4_7" style="display:none;" class="ver_select"><b>Jon 4:7</b>  Mas Dios preparó un gusano al venir la mañana del día siguiente, el cual hirió a la calabacera, y se secó. </div>
<div id="Jon_4_8" style="display:none;" class="ver_select"><b>Jon 4:8</b>  Y aconteció que al salir el sol, preparó Dios un recio viento solano; y el sol hirió a Jonás en la cabeza, y desmayaba; y deseaba la muerte, diciendo: Mejor sería para mí la muerte que la vida. </div>
<div id="Jon_4_9" style="display:none;" class="ver_select"><b>Jon 4:9</b>  Entonces dijo Dios a Jonás: ¿Tanto te enojas por la calabacera? Y él respondió: Mucho me enojo, hasta la muerte. </div>
<div id="Jon_4_10" style="display:none;" class="ver_select"><b>Jon 4:10</b>  Y dijo Jehová: Tuviste tú lástima de la calabacera, en la cual no trabajaste, ni tú la hiciste crecer; que en espacio de una noche nació, y en espacio de otra noche pereció: </div>
<div id="Jon_4_11" style="display:none;" class="ver_select"><b>Jon 4:11</b>  ¿Y no tendré yo piedad de Nínive, aquella grande ciudad donde hay más de ciento veinte mil personas que no pueden discernir entre su mano derecha y su mano izquierda, y muchos animales? </div>
