<div id="Jud_1_1" style="display:none;" class="ver_select"><b>Jud 1:1</b>  Judas, siervo de Jesucristo, y hermano de Jacobo, a los llamados, santificados por Dios el Padre y preservados en Jesucristo: </div>
<div id="Jud_1_2" style="display:none;" class="ver_select"><b>Jud 1:2</b>  Misericordia y paz y amor os sean multiplicados. </div>
<div id="Jud_1_3" style="display:none;" class="ver_select"><b>Jud 1:3</b>  Amados, por la gran solicitud que tenía de escribiros tocante a la común salvación, me ha sido necesario escribiros exhortándoos a que contendáis ardientemente por la fe que ha sido una vez dada a los santos. </div>
<div id="Jud_1_4" style="display:none;" class="ver_select"><b>Jud 1:4</b>  Porque ciertos hombres han entrado encubiertamente, los cuales desde antes fueron ordenados para esta condenación, hombres impíos, que cambian la gracia de nuestro Dios en libertinaje, negando al único Señor Dios, y a nuestro Señor Jesucristo. </div>
<div id="Jud_1_5" style="display:none;" class="ver_select"><b>Jud 1:5</b>  Quiero, pues, recordaros, ya que una vez lo habéis sabido, que el Señor, habiendo salvado al pueblo sacándolo de la tierra de Egipto, después destruyó a los que no creyeron. </div>
<div id="Jud_1_6" style="display:none;" class="ver_select"><b>Jud 1:6</b>  Y a los ángeles que no guardaron su dignidad, sino que dejaron su propia habitación, los ha reservado bajo oscuridad en cadenas eternas para el juicio del gran día. </div>
<div id="Jud_1_7" style="display:none;" class="ver_select"><b>Jud 1:7</b>  Como Sodoma y Gomorra, y las ciudades vecinas, las cuales de la misma manera que ellos, habiéndose dado a la fornicación e ido en pos de carne extraña, fueron puestas por ejemplo; sufriendo el castigo del fuego eterno. </div>
<div id="Jud_1_8" style="display:none;" class="ver_select"><b>Jud 1:8</b>  De la misma manera también estos soñadores mancillan la carne, rechazan la autoridad y maldicen a las potestades superiores. </div>
<div id="Jud_1_9" style="display:none;" class="ver_select"><b>Jud 1:9</b>  Pero cuando el arcángel Miguel contendía con el diablo, disputando acerca del cuerpo de Moisés, no se atrevió a usar juicio de maldición contra él, sino que dijo: El Señor te reprenda. </div>
<div id="Jud_1_10" style="display:none;" class="ver_select"><b>Jud 1:10</b>  Pero éstos maldicen las cosas que no conocen; y en las que por naturaleza conocen, se corrompen como bestias brutas. </div>
<div id="Jud_1_11" style="display:none;" class="ver_select"><b>Jud 1:11</b>  ¡Ay de ellos! porque han seguido el camino de Caín, y por recompensa, se lanzaron en el error de Balaam, y perecieron en la contradicción de Coré. </div>
<div id="Jud_1_12" style="display:none;" class="ver_select"><b>Jud 1:12</b>  Éstos son manchas en vuestros ágapes, que banquetean con vosotros, apacentándose a sí mismos sin temor; son nubes sin agua, las cuales son llevadas de acá para allá por los vientos; árboles otoñales, sin fruto, dos veces muertos y desarraigados; </div>
<div id="Jud_1_13" style="display:none;" class="ver_select"><b>Jud 1:13</b>  fieras ondas del mar, que espuman su propia vergüenza; estrellas erráticas, a las cuales está reservada la oscuridad de las tinieblas para siempre. </div>
<div id="Jud_1_14" style="display:none;" class="ver_select"><b>Jud 1:14</b>  De éstos también profetizó Enoc, séptimo desde Adán, diciendo: He aquí, el Señor viene con decenas de millares de sus santos, </div>
<div id="Jud_1_15" style="display:none;" class="ver_select"><b>Jud 1:15</b>  para ejecutar juicio contra todos, y convencer a todos los impíos de entre ellos, de todas sus obras impías que han cometido impíamente, y de toda palabra dura que los pecadores impíos han hablado contra Él. </div>
<div id="Jud_1_16" style="display:none;" class="ver_select"><b>Jud 1:16</b>  Éstos son murmuradores, querellosos, andando según sus concupiscencias; y su boca habla palabras infladas, adulando a las personas para sacar provecho. </div>
<div id="Jud_1_17" style="display:none;" class="ver_select"><b>Jud 1:17</b>  Pero vosotros, amados, acordaos de las palabras que antes fueron dichas por los apóstoles de nuestro Señor Jesucristo; </div>
<div id="Jud_1_18" style="display:none;" class="ver_select"><b>Jud 1:18</b>  de que os decían: En el postrer tiempo habrá burladores, que andarán según sus malvadas concupiscencias. </div>
<div id="Jud_1_19" style="display:none;" class="ver_select"><b>Jud 1:19</b>  Éstos son los que se separan a sí mismos, sensuales, no teniendo el Espíritu. </div>
<div id="Jud_1_20" style="display:none;" class="ver_select"><b>Jud 1:20</b>  Pero vosotros, amados, edificándoos sobre vuestra santísima fe, orando en el Espíritu Santo, </div>
<div id="Jud_1_21" style="display:none;" class="ver_select"><b>Jud 1:21</b>  conservaos en el amor de Dios, esperando la misericordia de nuestro Señor Jesucristo para vida eterna. </div>
<div id="Jud_1_22" style="display:none;" class="ver_select"><b>Jud 1:22</b>  Y de algunos tened compasión, haciendo diferencia. </div>
<div id="Jud_1_23" style="display:none;" class="ver_select"><b>Jud 1:23</b>  Y a otros salvad con temor, arrebatándolos del fuego; aborreciendo incluso la ropa que es contaminada por su carne. </div>
<div id="Jud_1_24" style="display:none;" class="ver_select"><b>Jud 1:24</b>  Y a Aquél que es poderoso para guardaros sin caída, y presentaros sin mancha delante de su gloria con gran alegría, </div>
<div id="Jud_1_25" style="display:none;" class="ver_select"><b>Jud 1:25</b>  al único sabio Dios Salvador nuestro, sea gloria y majestad, dominio y potestad, ahora y siempre. Amén. </div>
