<div id="Mal_1_1" style="display:none;" class="ver_select"><b>Mal 1:1</b>  Carga de la palabra de Jehová a Israel, por medio de Malaquías. </div>
<div id="Mal_1_2" style="display:none;" class="ver_select"><b>Mal 1:2</b>  Yo os he amado, dice Jehová; y dijisteis: ¿En qué nos amaste? ¿No era Esaú hermano de Jacob? dice Jehová. Pero amé a Jacob, </div>
<div id="Mal_1_3" style="display:none;" class="ver_select"><b>Mal 1:3</b>  y a Esaú aborrecí, y torné sus montes en asolamiento, y su posesión para los dragones del desierto. </div>
<div id="Mal_1_4" style="display:none;" class="ver_select"><b>Mal 1:4</b>  Aunque Edom dijere: Nos hemos empobrecido, pero volveremos y edificaremos lo arruinado; así dice Jehová de los ejércitos: Ellos edificarán, pero yo destruiré; y les llamarán provincia de Impiedad, y pueblo contra quien Jehová se indignó para siempre. </div>
<div id="Mal_1_5" style="display:none;" class="ver_select"><b>Mal 1:5</b>  Y vuestros ojos lo verán, y diréis: Sea Jehová engrandecido sobre la provincia de Israel. </div>
<div id="Mal_1_6" style="display:none;" class="ver_select"><b>Mal 1:6</b>  El hijo honra a su padre, y el siervo a su señor. Si, pues, soy yo Padre, ¿dónde está mi honra? y si soy Señor, ¿dónde está mi temor? dice Jehová de los ejércitos a vosotros, oh sacerdotes, que menospreciáis mi nombre. Y decís: ¿En qué hemos menospreciado tu nombre? </div>
<div id="Mal_1_7" style="display:none;" class="ver_select"><b>Mal 1:7</b>  En que ofrecéis sobre mi altar pan inmundo. Y dijisteis: ¿En qué te hemos deshonrado? En que decís: La mesa de Jehová es despreciable. </div>
<div id="Mal_1_8" style="display:none;" class="ver_select"><b>Mal 1:8</b>  Y cuando ofrecéis el animal ciego para el sacrificio, ¿no es malo? asimismo cuando ofrecéis el cojo o el enfermo, ¿no es malo? Ofrécelo, pues, a tu príncipe; ¿acaso se agradará de ti, o le serás acepto? dice Jehová de los ejércitos. </div>
<div id="Mal_1_9" style="display:none;" class="ver_select"><b>Mal 1:9</b>  Ahora pues, os pido, rogad que Dios tenga piedad de nosotros (esto de vuestra mano vino). ¿Le seréis agradables? dice Jehová de los ejércitos. </div>
<div id="Mal_1_10" style="display:none;" class="ver_select"><b>Mal 1:10</b>  ¿Quién también hay de vosotros que cierre las puertas o alumbre mi altar de balde? Yo no recibo contentamiento en vosotros, dice Jehová de los ejércitos, ni de vuestra mano aceptaré ofrenda. </div>
<div id="Mal_1_11" style="display:none;" class="ver_select"><b>Mal 1:11</b>  Porque desde donde el sol nace hasta donde se pone, será grande mi nombre entre los gentiles; y en todo lugar se ofrecerá incienso a mi nombre, y ofrenda limpia; porque mi nombre será grande entre las naciones, dice Jehová de los ejércitos. </div>
<div id="Mal_1_12" style="display:none;" class="ver_select"><b>Mal 1:12</b>  Y vosotros lo habéis profanado cuando decís: Inmunda es la mesa de Jehová; y cuando hablan que su alimento es despreciable. </div>
<div id="Mal_1_13" style="display:none;" class="ver_select"><b>Mal 1:13</b>  Además dijisteis: ¡Oh qué fastidio! y lo despreciasteis, dice Jehová de los ejércitos; y trajisteis lo hurtado, o cojo, o enfermo, y presentasteis ofrenda. ¿Aceptaré eso de vuestra mano? dice Jehová. </div>
<div id="Mal_1_14" style="display:none;" class="ver_select"><b>Mal 1:14</b>  Maldito el engañador, que tiene macho en su rebaño, y promete, y sacrifica lo dañado a Jehová; porque yo soy Gran Rey, dice Jehová de los ejércitos, y mi nombre es temible entre las naciones. </div>
<div id="Mal_2_1" style="display:none;" class="ver_select"><b>Mal 2:1</b>  Ahora pues, oh sacerdotes, para vosotros es este mandamiento. </div>
<div id="Mal_2_2" style="display:none;" class="ver_select"><b>Mal 2:2</b>  Si no oyereis, y si no pusiereis en vuestro corazón el dar gloria a mi nombre, dice Jehová de los ejércitos, yo enviaré maldición sobre vosotros, y maldeciré vuestras bendiciones; y ya las he maldecido, porque no lo ponéis en vuestro corazón. </div>
<div id="Mal_2_3" style="display:none;" class="ver_select"><b>Mal 2:3</b>  He aquí, yo os dañaré vuestra sementera, y arrojaré sobre vuestros rostros el estiércol, el estiércol de vuestras fiestas solemnes, y con él seréis removidos. </div>
<div id="Mal_2_4" style="display:none;" class="ver_select"><b>Mal 2:4</b>  Y sabréis que yo os envié este mandamiento, para que fuese mi pacto con Leví, dice Jehová de los ejércitos. </div>
<div id="Mal_2_5" style="display:none;" class="ver_select"><b>Mal 2:5</b>  Mi pacto fue con él de vida y de paz, y estas cosas yo le di por su temor; porque me temió, y delante de mi nombre estuvo humillado. </div>
<div id="Mal_2_6" style="display:none;" class="ver_select"><b>Mal 2:6</b>  La ley de verdad estuvo en su boca, e iniquidad no fue hallada en sus labios; en paz y en justicia anduvo conmigo, y a muchos hizo apartar de la iniquidad. </div>
<div id="Mal_2_7" style="display:none;" class="ver_select"><b>Mal 2:7</b>  Porque los labios del sacerdote han de guardar la sabiduría, y de su boca buscarán la ley; porque él es el mensajero de Jehová de los ejércitos. </div>
<div id="Mal_2_8" style="display:none;" class="ver_select"><b>Mal 2:8</b>  Mas vosotros os habéis apartado del camino; habéis hecho tropezar a muchos en la ley; habéis corrompido el pacto de Leví, dice Jehová de los ejércitos. </div>
<div id="Mal_2_9" style="display:none;" class="ver_select"><b>Mal 2:9</b>  Por tanto, yo también os he hecho despreciables y bajos ante todo el pueblo, así como vosotros no habéis guardado mis caminos, y en la ley hacéis acepción de personas. </div>
<div id="Mal_2_10" style="display:none;" class="ver_select"><b>Mal 2:10</b>  ¿No tenemos todos un mismo padre? ¿No nos ha creado un mismo Dios? ¿Por qué, pues, somos desleales cada uno contra su hermano, profanando el pacto de nuestros padres? </div>
<div id="Mal_2_11" style="display:none;" class="ver_select"><b>Mal 2:11</b>  Prevaricó Judá, y en Israel y en Jerusalén se ha cometido abominación; porque Judá ha profanado la santidad de Jehová, que él amó, y se casó con la hija de un dios extraño. </div>
<div id="Mal_2_12" style="display:none;" class="ver_select"><b>Mal 2:12</b>  Jehová cortará de las tiendas de Jacob al hombre que hiciere esto, al que vela, y al que responde, y al que ofrece ofrenda a Jehová de los ejércitos. </div>
<div id="Mal_2_13" style="display:none;" class="ver_select"><b>Mal 2:13</b>  Y esta otra vez haréis cubrir el altar de Jehová de lágrimas, de llanto, y de clamor; así que no miraré más a la ofrenda, para aceptarla con gusto de vuestra mano. </div>
<div id="Mal_2_14" style="display:none;" class="ver_select"><b>Mal 2:14</b>  Mas diréis: ¿Por qué? Porque Jehová ha sido testigo entre ti y la esposa de tu juventud, contra la cual tú has sido desleal, aun siendo ella tu compañera y la esposa de tu pacto. </div>
<div id="Mal_2_15" style="display:none;" class="ver_select"><b>Mal 2:15</b>  ¿No hizo Él uno, aunque tenía el remanente del espíritu? ¿Y por qué uno? Para que procurara una simiente de Dios. Guardaos, pues, en vuestro espíritu, y no seáis desleales contra la esposa de vuestra juventud. </div>
<div id="Mal_2_16" style="display:none;" class="ver_select"><b>Mal 2:16</b>  Porque Jehová Dios de Israel dice que Él aborrece el divorcio; y al que cubre la violencia con su vestidura, dice Jehová de los ejércitos. Guardaos, pues, en vuestro espíritu, y no seáis desleales. </div>
<div id="Mal_2_17" style="display:none;" class="ver_select"><b>Mal 2:17</b>  Habéis cansado a Jehová con vuestras palabras. Y diréis: ¿En qué le hemos cansado? Cuando decís: Cualquiera que hace mal agrada a Jehová, y en los tales Él toma contentamiento; de otra manera, ¿dónde está el Dios de juicio? </div>
<div id="Mal_3_1" style="display:none;" class="ver_select"><b>Mal 3:1</b>  He aquí, yo envío mi mensajero, el cual preparará el camino delante de mí; y vendrá repentinamente a su templo el Señor a quien vosotros buscáis, y el mensajero del pacto, a quien deseáis vosotros. He aquí viene, dice Jehová de los ejércitos. </div>
<div id="Mal_3_2" style="display:none;" class="ver_select"><b>Mal 3:2</b>  ¿Y quién podrá resistir en el día de su venida? o ¿quién podrá mantenerse en pie cuando Él se manifieste? Porque Él es como fuego purificador, y como jabón de lavadores. </div>
<div id="Mal_3_3" style="display:none;" class="ver_select"><b>Mal 3:3</b>  Y Él se sentará como refinador y purificador de plata, y purificará a los hijos de Leví y los refinará como a oro y como a plata, para que ofrezcan a Jehová ofrenda en justicia. </div>
<div id="Mal_3_4" style="display:none;" class="ver_select"><b>Mal 3:4</b>  Entonces será grata a Jehová la ofrenda de Judá y de Jerusalén, como en los días pasados, y como en los años antiguos. </div>
<div id="Mal_3_5" style="display:none;" class="ver_select"><b>Mal 3:5</b>  Y vendré a vosotros a juicio; y seré pronto testigo contra los hechiceros y adúlteros; y contra los que juran mentira, y los que defraudan en su salario al jornalero, a la viuda y al huérfano, y contra los que privan de su derecho al extranjero, no teniendo temor de mí, dice Jehová de los ejércitos. </div>
<div id="Mal_3_6" style="display:none;" class="ver_select"><b>Mal 3:6</b>  Porque yo Jehová, no cambio; por eso vosotros, hijos de Jacob, no habéis sido consumidos. </div>
<div id="Mal_3_7" style="display:none;" class="ver_select"><b>Mal 3:7</b>  Desde los días de vuestros padres os habéis apartado de mis leyes, y no las guardasteis. Volveos a mí, y yo me volveré a vosotros, dice Jehová de los ejércitos. Mas dijisteis: ¿En qué nos hemos de volver? </div>
<div id="Mal_3_8" style="display:none;" class="ver_select"><b>Mal 3:8</b>  ¿Robará el hombre a Dios? Pues vosotros me habéis robado. Y dijisteis: ¿En qué te hemos robado? En los diezmos y las ofrendas. </div>
<div id="Mal_3_9" style="display:none;" class="ver_select"><b>Mal 3:9</b>  Malditos sois con maldición, porque vosotros, la nación toda, me habéis robado. </div>
<div id="Mal_3_10" style="display:none;" class="ver_select"><b>Mal 3:10</b>  Traed todos los diezmos al alfolí, y haya alimento en mi casa; y probadme ahora en esto, dice Jehová de los ejércitos, si no os abriré las ventanas de los cielos, y derramaré sobre vosotros bendición hasta que sobreabunde. </div>
<div id="Mal_3_11" style="display:none;" class="ver_select"><b>Mal 3:11</b>  Reprenderé también por vosotros al devorador, y no os destruirá el fruto de la tierra; ni vuestra vid en el campo abortará, dice Jehová de los ejércitos. </div>
<div id="Mal_3_12" style="display:none;" class="ver_select"><b>Mal 3:12</b>  Y todas las naciones os dirán bienaventurados; porque seréis tierra deseable, dice Jehová de los ejércitos. </div>
<div id="Mal_3_13" style="display:none;" class="ver_select"><b>Mal 3:13</b>  Vuestras palabras han sido duras contra mí, dice Jehová. Y todavía decís: ¿Qué hemos hablado contra ti? </div>
<div id="Mal_3_14" style="display:none;" class="ver_select"><b>Mal 3:14</b>  Habéis dicho: Por demás es servir a Dios; ¿y qué aprovecha que guardemos su ley, y que andemos tristes delante de Jehová de los ejércitos? </div>
<div id="Mal_3_15" style="display:none;" class="ver_select"><b>Mal 3:15</b>  Decimos, pues, ahora, que son bienaventurados los soberbios, y también que los obreros de iniquidad son los prosperados; y aunque tentaron a Dios, escaparon. </div>
<div id="Mal_3_16" style="display:none;" class="ver_select"><b>Mal 3:16</b>  Entonces los que temen a Jehová hablaron cada uno a su compañero; y Jehová escuchó y oyó, y fue escrito libro de memoria delante de Él para los que temen a Jehová, y para los que piensan en su nombre. </div>
<div id="Mal_3_17" style="display:none;" class="ver_select"><b>Mal 3:17</b>  Y ellos serán míos, dice Jehová de los ejércitos, en el día que yo prepare mi especial tesoro; y los perdonaré como un hombre perdona a su hijo que le sirve. </div>
<div id="Mal_3_18" style="display:none;" class="ver_select"><b>Mal 3:18</b>  Entonces os volveréis, y discerniréis la diferencia entre el justo y el impío, entre el que sirve a Dios y el que no le sirve. </div>
<div id="Mal_4_1" style="display:none;" class="ver_select"><b>Mal 4:1</b>  Porque he aquí, viene el día ardiente como un horno; y todos los soberbios, y todos los que hacen maldad, serán estopa; y aquel día vendrá y los abrasará, dice Jehová de los ejércitos, el cual no les dejará ni raíz ni rama. </div>
<div id="Mal_4_2" style="display:none;" class="ver_select"><b>Mal 4:2</b>  Mas para vosotros los que teméis mi nombre, nacerá el Sol de justicia, y en sus alas traerá salvación; y saldréis, y saltaréis como becerros de la manada. </div>
<div id="Mal_4_3" style="display:none;" class="ver_select"><b>Mal 4:3</b>  Y hollaréis a los malos, los cuales serán ceniza bajo las plantas de vuestros pies, en el día en que yo haré esto, dice Jehová de los ejércitos. </div>
<div id="Mal_4_4" style="display:none;" class="ver_select"><b>Mal 4:4</b>  Acordaos de la ley de Moisés mi siervo, al cual encargué en Horeb ordenanzas y leyes para todo Israel. </div>
<div id="Mal_4_5" style="display:none;" class="ver_select"><b>Mal 4:5</b>  He aquí, yo os envío a Elías el profeta, antes que venga el día de Jehová grande y terrible. </div>
<div id="Mal_4_6" style="display:none;" class="ver_select"><b>Mal 4:6</b>  Él convertirá el corazón de los padres hacia los hijos, y el corazón de los hijos hacia los padres; no sea que yo venga y hiera la tierra con maldición. </div>
