<div id="Mic_1_1" style="display:none;" class="ver_select"><b>Mic 1:1</b>  Palabra de Jehová que vino a Miqueas el morastita en días de Jotam, Acaz, y Ezequías, reyes de Judá: lo que vio sobre Samaria y Jerusalén. </div>
<div id="Mic_1_2" style="display:none;" class="ver_select"><b>Mic 1:2</b>  Oíd, pueblos todos: está atenta, tierra, y todo lo que en ella hay: y el Señor Jehová, el Señor desde su santo templo sea testigo contra vosotros. </div>
<div id="Mic_1_3" style="display:none;" class="ver_select"><b>Mic 1:3</b>  Porque he aquí, Jehová sale de su lugar, y descenderá, y hollará sobre las alturas de la tierra. </div>
<div id="Mic_1_4" style="display:none;" class="ver_select"><b>Mic 1:4</b>  Y debajo de Él se derretirán los montes, y los valles se hendirán como la cera delante del fuego, como las aguas que corren por un precipicio. </div>
<div id="Mic_1_5" style="display:none;" class="ver_select"><b>Mic 1:5</b>  Todo esto por la rebelión de Jacob, y por los pecados de la casa de Israel. ¿Cuál es la rebelión de Jacob? ¿No es Samaria? ¿Y cuáles son los lugares altos de Judá? ¿No es Jerusalén? </div>
<div id="Mic_1_6" style="display:none;" class="ver_select"><b>Mic 1:6</b>  Haré pues, de Samaria un montón de ruinas, tierra de viñas; y derramaré sus piedras por el valle, y descubriré sus fundamentos. </div>
<div id="Mic_1_7" style="display:none;" class="ver_select"><b>Mic 1:7</b>  Y todas sus estatuas serán despedazadas, y todos sus dones serán quemados en fuego, y asolaré todos sus ídolos; porque de dones de rameras los juntó, y a dones de rameras volverán. </div>
<div id="Mic_1_8" style="display:none;" class="ver_select"><b>Mic 1:8</b>  Por tanto lamentaré y aullaré, y andaré despojado y desnudo; haré gemido como de dragones, y lamento como de búhos. </div>
<div id="Mic_1_9" style="display:none;" class="ver_select"><b>Mic 1:9</b>  Porque su llaga es dolorosa, que llegó hasta Judá; llegó hasta la puerta de mi pueblo, hasta Jerusalén. </div>
<div id="Mic_1_10" style="display:none;" class="ver_select"><b>Mic 1:10</b>  No lo digáis en Gat, ni lloréis del todo: revuélcate en el polvo de Bet-le-afra. </div>
<div id="Mic_1_11" style="display:none;" class="ver_select"><b>Mic 1:11</b>  Pásate desnuda con vergüenza, oh moradora de Safir: la moradora de Saanán no salió al llanto de Bet-esel: tomará de vosotros su tardanza. </div>
<div id="Mic_1_12" style="display:none;" class="ver_select"><b>Mic 1:12</b>  Porque la moradora de Marot tuvo dolor por el bien; por cuanto el mal descendió de Jehová hasta la puerta de Jerusalén. </div>
<div id="Mic_1_13" style="display:none;" class="ver_select"><b>Mic 1:13</b>  Unce al carro dromedarios, oh moradora de Laquis: Ella es el principio de pecado a la hija de Sión; porque en ti se encontraron las transgresiones de Israel. </div>
<div id="Mic_1_14" style="display:none;" class="ver_select"><b>Mic 1:14</b>  Por tanto, tú darás dones a Moreset-gat: las casas de Aczib serán en mentira a los reyes de Israel. </div>
<div id="Mic_1_15" style="display:none;" class="ver_select"><b>Mic 1:15</b>  Aun te traeré heredero, oh moradora de Maresa; la gloria de Israel vendrá hasta Adulam. </div>
<div id="Mic_1_16" style="display:none;" class="ver_select"><b>Mic 1:16</b>  Rápate y aféitate por los hijos de tus delicias; ensancha tu calva como águila; porque fueron llevados cautivos lejos de ti. </div>
<div id="Mic_2_1" style="display:none;" class="ver_select"><b>Mic 2:1</b>  ¡Ay de los que piensan iniquidad, y de los que fabrican el mal en sus camas! Cuando viene la mañana lo ponen en obra, porque tienen en su mano el poder. </div>
<div id="Mic_2_2" style="display:none;" class="ver_select"><b>Mic 2:2</b>  Y codiciaron las heredades, y las robaron; y casas, y las tomaron; oprimieron al hombre y a su casa, al hombre y a su heredad. </div>
<div id="Mic_2_3" style="display:none;" class="ver_select"><b>Mic 2:3</b>  Por tanto, así dice Jehová: He aquí, yo pienso sobre esta familia un mal del cual no sacaréis vuestros cuellos, ni andaréis erguidos; porque el tiempo será malo. </div>
<div id="Mic_2_4" style="display:none;" class="ver_select"><b>Mic 2:4</b>  En aquel tiempo se levantará sobre vosotros refrán, y se endechará una amarga lamentación, diciendo: Del todo fuimos destruidos; Él ha cambiado la porción de mi pueblo. ¡Cómo nos quitó nuestros campos! Los dio y los repartió a otros. </div>
<div id="Mic_2_5" style="display:none;" class="ver_select"><b>Mic 2:5</b>  Por tanto, no tendrás quien eche cordel para suerte en la congregación de Jehová. </div>
<div id="Mic_2_6" style="display:none;" class="ver_select"><b>Mic 2:6</b>  No profeticéis, dicen a los que profetizan; no les profetizarán, para no llevar la vergüenza </div>
<div id="Mic_2_7" style="display:none;" class="ver_select"><b>Mic 2:7</b>  Tú que te dices casa de Jacob, ¿se ha acortado el Espíritu de Jehová? ¿Son éstas sus obras? ¿Mis palabras no hacen bien al que camina rectamente? </div>
<div id="Mic_2_8" style="display:none;" class="ver_select"><b>Mic 2:8</b>  El que ayer era mi pueblo, se ha levantado como enemigo; tras las vestiduras quitasteis las capas atrevidamente a los que pasaban, como los que vuelven de la guerra. </div>
<div id="Mic_2_9" style="display:none;" class="ver_select"><b>Mic 2:9</b>  A las mujeres de mi pueblo echasteis fuera de las casas de sus delicias; a sus niños quitasteis mi perpetua alabanza. </div>
<div id="Mic_2_10" style="display:none;" class="ver_select"><b>Mic 2:10</b>  Levantaos, y andad, pues éste no es vuestro reposo; y porque está contaminado, os destruirá con grande destrucción. </div>
<div id="Mic_2_11" style="display:none;" class="ver_select"><b>Mic 2:11</b>  Si alguno que anda en el espíritu de falsedad mintiere, diciendo: Yo te profetizaré de vino y de sidra; este tal será profeta a este pueblo. </div>
<div id="Mic_2_12" style="display:none;" class="ver_select"><b>Mic 2:12</b>  De cierto te reuniré todo, oh Jacob; ciertamente recogeré el remanente de Israel; los reuniré como ovejas de Bosra, como rebaño en medio de su aprisco; harán estruendo por la multitud de hombres. </div>
<div id="Mic_2_13" style="display:none;" class="ver_select"><b>Mic 2:13</b>  Subirá rompedor delante de ellos; romperán y pasarán la puerta, y saldrán por ella: y su rey pasará delante de ellos, y a la cabeza de ellos Jehová. </div>
<div id="Mic_3_1" style="display:none;" class="ver_select"><b>Mic 3:1</b>  Y dije: Oíd ahora, príncipes de Jacob, y cabezas de la casa de Israel: ¿No pertenece a vosotros saber el derecho? </div>
<div id="Mic_3_2" style="display:none;" class="ver_select"><b>Mic 3:2</b>  A vosotros que aborrecéis lo bueno y amáis lo malo, que les arrancáis su piel y su carne de sobre sus huesos; </div>
<div id="Mic_3_3" style="display:none;" class="ver_select"><b>Mic 3:3</b>  que coméis asimismo la carne de mi pueblo, y les desolláis su piel de sobre ellos y les quebráis sus huesos, y los hacéis pedazos como para la olla, y como carne en caldero. </div>
<div id="Mic_3_4" style="display:none;" class="ver_select"><b>Mic 3:4</b>  Entonces clamarán a Jehová y no les responderá; antes esconderá de ellos su rostro en aquel tiempo, por cuanto hicieron malvadas obras. </div>
<div id="Mic_3_5" style="display:none;" class="ver_select"><b>Mic 3:5</b>  Así dice Jehová acerca de los profetas que hacen errar a mi pueblo, que muerden con sus dientes, y claman: Paz, y contra el que no les da de comer, declaran guerra. </div>
<div id="Mic_3_6" style="display:none;" class="ver_select"><b>Mic 3:6</b>  Por tanto, noche será para vosotros, no tendréis visión; os será oscuridad, de manera que no adivinéis, y sobre los profetas se pondrá el sol, y el día se oscurecerá sobre ellos. </div>
<div id="Mic_3_7" style="display:none;" class="ver_select"><b>Mic 3:7</b>  Y serán avergonzados los profetas, y se confundirán los adivinos; y ellos todos cubrirán su labio, porque no hay respuesta de Dios. </div>
<div id="Mic_3_8" style="display:none;" class="ver_select"><b>Mic 3:8</b>  Mas yo estoy lleno de poder del Espíritu de Jehová, y de juicio, y de fortaleza, para denunciar a Jacob su rebelión, y a Israel su pecado. </div>
<div id="Mic_3_9" style="display:none;" class="ver_select"><b>Mic 3:9</b>  Oíd ahora esto, cabezas de la casa de Jacob, y capitanes de la casa de Israel, que abomináis el juicio, y pervertís todo el derecho; </div>
<div id="Mic_3_10" style="display:none;" class="ver_select"><b>Mic 3:10</b>  Que edificáis a Sión con sangre, y a Jerusalén con injusticia; </div>
<div id="Mic_3_11" style="display:none;" class="ver_select"><b>Mic 3:11</b>  Sus cabezas juzgan por cohecho, y sus sacerdotes enseñan por precio, y sus profetas adivinan por dinero; y se apoyan en Jehová diciendo: ¿No está Jehová entre nosotros? No vendrá mal sobre nosotros. </div>
<div id="Mic_3_12" style="display:none;" class="ver_select"><b>Mic 3:12</b>  Por tanto, a causa de vosotros Sión será arada como un campo, y Jerusalén vendrá a ser un montón de ruinas, y el monte de la casa como las cumbres del bosque. </div>
<div id="Mic_4_1" style="display:none;" class="ver_select"><b>Mic 4:1</b>  Y acontecerá en los postreros días que el monte de la casa de Jehová será establecido por cabecera de montes, y será exaltado más que los collados, y los pueblos correrán a él. </div>
<div id="Mic_4_2" style="display:none;" class="ver_select"><b>Mic 4:2</b>  Y vendrán muchas naciones, y dirán: Venid, y subamos al monte de Jehová, y a la casa del Dios de Jacob; y Él nos enseñará en sus caminos, y andaremos por sus sendas; porque de Sión saldrá la ley, y de Jerusalén la palabra de Jehová. </div>
<div id="Mic_4_3" style="display:none;" class="ver_select"><b>Mic 4:3</b>  Y juzgará entre muchos pueblos, y corregirá a naciones poderosas hasta muy lejos; y martillarán sus espadas para azadones, y sus lanzas para hoces; no alzará espada nación contra nación, ni se adiestrarán más para la guerra. </div>
<div id="Mic_4_4" style="display:none;" class="ver_select"><b>Mic 4:4</b>  Y cada uno se sentará debajo de su vid y debajo de su higuera, y no habrá quien amedrente; porque la boca de Jehová de los ejércitos lo ha hablado. </div>
<div id="Mic_4_5" style="display:none;" class="ver_select"><b>Mic 4:5</b>  Bien que todos los pueblos anduvieren cada uno en el nombre de sus dioses, nosotros con todo andaremos en el nombre de Jehová nuestro Dios eternamente y para siempre. </div>
<div id="Mic_4_6" style="display:none;" class="ver_select"><b>Mic 4:6</b>  En aquel día, dice Jehová, juntaré a la que cojea, y recogeré a la descarriada, y a la que afligí: </div>
<div id="Mic_4_7" style="display:none;" class="ver_select"><b>Mic 4:7</b>  Y haré un remanente de la que cojea, y de la descarriada una nación poderosa; y Jehová reinará sobre ellos en el monte de Sión desde ahora para siempre. </div>
<div id="Mic_4_8" style="display:none;" class="ver_select"><b>Mic 4:8</b>  Y tú, oh torre del rebaño, la fortaleza de la hija de Sión vendrá hasta ti: y el señorío primero, el reino vendrá a la hija de Jerusalén. </div>
<div id="Mic_4_9" style="display:none;" class="ver_select"><b>Mic 4:9</b>  Ahora ¿por qué gritas tanto? ¿No hay rey en ti? ¿Pereció tu consejero, que te ha tomado dolor como de mujer de parto? </div>
<div id="Mic_4_10" style="display:none;" class="ver_select"><b>Mic 4:10</b>  Duélete y gime, hija de Sión como mujer de parto; porque ahora saldrás de la ciudad, y morarás en el campo, y llegarás hasta Babilonia; allí serás librada, allí te redimirá Jehová de la mano de tus enemigos. </div>
<div id="Mic_4_11" style="display:none;" class="ver_select"><b>Mic 4:11</b>  Ahora también muchas naciones se han juntado contra ti, y dicen: Sea profanada, y vean nuestros ojos su deseo sobre Sión. </div>
<div id="Mic_4_12" style="display:none;" class="ver_select"><b>Mic 4:12</b>  Mas ellos no conocieron los pensamientos de Jehová, ni entendieron su consejo; por lo cual los juntó como gavillas en la era. </div>
<div id="Mic_4_13" style="display:none;" class="ver_select"><b>Mic 4:13</b>  Levántate y trilla, hija de Sión, porque tu cuerno tornaré de hierro, y tus uñas de bronce, y desmenuzarás muchos pueblos; y consagrarás a Jehová su despojo, y sus riquezas al Señor de toda la tierra. </div>
<div id="Mic_5_1" style="display:none;" class="ver_select"><b>Mic 5:1</b>  Reúnete ahora en tropas, oh hija de guerreros; nos han sitiado; con vara herirán en la mejilla al Juez de Israel. </div>
<div id="Mic_5_2" style="display:none;" class="ver_select"><b>Mic 5:2</b>  Pero tú, Belén Efrata, aunque eres pequeña entre los millares de Judá, de ti me saldrá el que será Señor en Israel; y sus salidas han sido desde el principio, desde la eternidad. </div>
<div id="Mic_5_3" style="display:none;" class="ver_select"><b>Mic 5:3</b>  Pero los dejará hasta el tiempo que dé a luz la que ha de dar a luz; entonces el resto de sus hermanos volverán a los hijos de Israel. </div>
<div id="Mic_5_4" style="display:none;" class="ver_select"><b>Mic 5:4</b>  Y Él estará, y apacentará con el poder de Jehová, con la majestad del nombre de Jehová su Dios; y permanecerán; porque ahora Él será engrandecido hasta los fines de la tierra. </div>
<div id="Mic_5_5" style="display:none;" class="ver_select"><b>Mic 5:5</b>  Y Éste será nuestra paz. Cuando el asirio venga a nuestra tierra, y cuando pise nuestros palacios, entonces levantaremos contra él siete pastores, y ocho hombres principales; </div>
<div id="Mic_5_6" style="display:none;" class="ver_select"><b>Mic 5:6</b>  y destruirán la tierra de Asiria a espada, y la tierra de Nimrod con sus espadas; y Él nos librará del asirio, cuando viniere contra nuestra tierra y hollare nuestros términos. </div>
<div id="Mic_5_7" style="display:none;" class="ver_select"><b>Mic 5:7</b>  Y el remanente de Jacob será en medio de muchos pueblos, como el rocío de Jehová, como las lluvias sobre la hierba, las cuales no esperan a hombre, ni aguardan a los hijos de los hombres. </div>
<div id="Mic_5_8" style="display:none;" class="ver_select"><b>Mic 5:8</b>  Y el remanente de Jacob será entre los gentiles, en medio de muchos pueblos, como el león entre las bestias de la selva, como el cachorro del león entre los rebaños de ovejas, el cual si pasa, pisotea y desgarra, y no hay quien pueda librar. </div>
<div id="Mic_5_9" style="display:none;" class="ver_select"><b>Mic 5:9</b>  Tu mano se alzará sobre tus adversarios, y todos tus enemigos serán talados. </div>
<div id="Mic_5_10" style="display:none;" class="ver_select"><b>Mic 5:10</b>  Y acontecerá en aquel día, dice Jehová, que exterminaré tus caballos de en medio de ti, y destruiré tus carros. </div>
<div id="Mic_5_11" style="display:none;" class="ver_select"><b>Mic 5:11</b>  Y destruiré las ciudades de tu tierra, y derribaré todas tus fortalezas. </div>
<div id="Mic_5_12" style="display:none;" class="ver_select"><b>Mic 5:12</b>  Asimismo destruiré de tu mano las hechicerías, y no se hallarán en ti agoreros. </div>
<div id="Mic_5_13" style="display:none;" class="ver_select"><b>Mic 5:13</b>  Y destruiré tus esculturas y tus imágenes de en medio de ti, y nunca más adorarás la obra de tus manos. </div>
<div id="Mic_5_14" style="display:none;" class="ver_select"><b>Mic 5:14</b>  Y arrancaré tus imágenes de Asera de en medio de ti, y destruiré tus ciudades. </div>
<div id="Mic_5_15" style="display:none;" class="ver_select"><b>Mic 5:15</b>  Y con ira y con furor haré venganza en las gentes que no escucharon. </div>
<div id="Mic_6_1" style="display:none;" class="ver_select"><b>Mic 6:1</b>  Oíd ahora lo que dice Jehová: Levántate, pleitea con los montes, y oigan los collados tu voz. </div>
<div id="Mic_6_2" style="display:none;" class="ver_select"><b>Mic 6:2</b>  Oíd, montes, y fuertes fundamentos de la tierra, el pleito de Jehová; porque Jehová tiene controversia con su pueblo, y altercará con Israel. </div>
<div id="Mic_6_3" style="display:none;" class="ver_select"><b>Mic 6:3</b>  Pueblo mío, ¿qué te he hecho, o en qué te he molestado? Responde contra mí. </div>
<div id="Mic_6_4" style="display:none;" class="ver_select"><b>Mic 6:4</b>  Porque yo te hice subir de la tierra de Egipto, y de la casa de siervos te redimí; y envié delante de ti a Moisés, y a Aarón, y a Miriam. </div>
<div id="Mic_6_5" style="display:none;" class="ver_select"><b>Mic 6:5</b>  Pueblo mío, acuérdate ahora qué aconsejó Balac rey de Moab, y qué le respondió Balaam, hijo de Beor, desde Sitim hasta Gilgal, para que conozcas las justicias de Jehová. </div>
<div id="Mic_6_6" style="display:none;" class="ver_select"><b>Mic 6:6</b>  ¿Con qué me presentaré delante de Jehová, y adoraré al Dios Altísimo? ¿Vendré ante Él con holocaustos, con becerros de un año? </div>
<div id="Mic_6_7" style="display:none;" class="ver_select"><b>Mic 6:7</b>  ¿Se agradará Jehová de millares de carneros, o de diez mil arroyos de aceite? ¿Daré mi primogénito por mi rebelión, el fruto de mis entrañas por el pecado de mi alma? </div>
<div id="Mic_6_8" style="display:none;" class="ver_select"><b>Mic 6:8</b>  Oh hombre, Él te ha declarado lo que es bueno, y ¿qué pide Jehová de ti? Solamente hacer justicia, y amar misericordia, y caminar humildemente con tu Dios. </div>
<div id="Mic_6_9" style="display:none;" class="ver_select"><b>Mic 6:9</b>  La voz de Jehová clama a la ciudad, y el sabio mirará a tu nombre. Oíd la vara, y a quien lo ha establecido. </div>
<div id="Mic_6_10" style="display:none;" class="ver_select"><b>Mic 6:10</b>  ¿Hay aún tesoros de impiedad en casa del impío, y medida escasa que es detestable? </div>
<div id="Mic_6_11" style="display:none;" class="ver_select"><b>Mic 6:11</b>  ¿Tendré por inocente al que tiene balanza falsa, y bolsa de pesas engañosas? </div>
<div id="Mic_6_12" style="display:none;" class="ver_select"><b>Mic 6:12</b>  Con lo cual sus ricos se llenaron de rapiña, y sus moradores hablaron mentira, y su lengua es engañosa en su boca. </div>
<div id="Mic_6_13" style="display:none;" class="ver_select"><b>Mic 6:13</b>  Por eso yo también te haré enfermar, hiriéndote, asolándote por tus pecados. </div>
<div id="Mic_6_14" style="display:none;" class="ver_select"><b>Mic 6:14</b>  Tú comerás, y no te saciarás; y tu abatimiento estará en medio de ti: Recogerás, pero no conservarás; y lo que conservares, yo lo entregaré a la espada. </div>
<div id="Mic_6_15" style="display:none;" class="ver_select"><b>Mic 6:15</b>  Tú sembrarás, pero no segarás; pisarás aceitunas, pero no te ungirás con el aceite; y mosto, pero no beberás el vino. </div>
<div id="Mic_6_16" style="display:none;" class="ver_select"><b>Mic 6:16</b>  Porque los mandamientos de Omri se han guardado, y toda obra de la casa de Acab; y en los consejos de ellos anduvisteis, para que yo te pusiese en asolamiento, y a tus moradores para escarnio. Llevaréis, por tanto, el oprobio de mi pueblo. </div>
<div id="Mic_7_1" style="display:none;" class="ver_select"><b>Mic 7:1</b>  ¡Ay de mí! porque he venido a ser como cuando han recogido los frutos del verano, como cuando han rebuscado después de la vendimia, que no queda racimo para comer; mi alma desea los primeros frutos. </div>
<div id="Mic_7_2" style="display:none;" class="ver_select"><b>Mic 7:2</b>  Faltó el misericordioso de la tierra, y ninguno hay recto entre los hombres: todos acechan por sangre; cada cual arma red a su hermano. </div>
<div id="Mic_7_3" style="display:none;" class="ver_select"><b>Mic 7:3</b>  Para completar la maldad con ambas manos, el príncipe demanda, y el juez juzga por recompensa; el grande, habla el antojo de su alma, y lo confirman. </div>
<div id="Mic_7_4" style="display:none;" class="ver_select"><b>Mic 7:4</b>  El mejor de ellos es como el abrojo, y el más recto, como el zarzal; el día de tus atalayas y de tu visitación viene; ahora será su confusión. </div>
<div id="Mic_7_5" style="display:none;" class="ver_select"><b>Mic 7:5</b>  No creáis en amigo, ni confiéis en príncipe: de la que duerme a tu lado, guarda, no abras tu boca. </div>
<div id="Mic_7_6" style="display:none;" class="ver_select"><b>Mic 7:6</b>  Porque el hijo deshonra al padre, la hija se levanta contra la madre, la nuera contra su suegra; y los enemigos del hombre son los de su propia casa. </div>
<div id="Mic_7_7" style="display:none;" class="ver_select"><b>Mic 7:7</b>  Pero yo miraré a Jehová, esperaré en el Dios de mi salvación; el Dios mío me oirá. </div>
<div id="Mic_7_8" style="display:none;" class="ver_select"><b>Mic 7:8</b>  No te alegres de mí, oh enemiga mía, porque aunque caiga, me volveré a levantar; aunque more en tinieblas, Jehová será mi luz. </div>
<div id="Mic_7_9" style="display:none;" class="ver_select"><b>Mic 7:9</b>  La ira de Jehová soportaré, porque pequé contra Él, hasta que juzgue mi causa y haga mi juicio; Él me sacará a luz; veré su justicia. </div>
<div id="Mic_7_10" style="display:none;" class="ver_select"><b>Mic 7:10</b>  Entonces mi enemiga lo verá, y la cubrirá vergüenza; la que me decía: ¿Dónde está Jehová tu Dios? Mis ojos la verán; ahora será hollada como el lodo de las calles. </div>
<div id="Mic_7_11" style="display:none;" class="ver_select"><b>Mic 7:11</b>  El día en que se edificarán tus muros, aquel día será alejado el mandato. </div>
<div id="Mic_7_12" style="display:none;" class="ver_select"><b>Mic 7:12</b>  En ese día vendrán hasta ti desde Asiria y las ciudades fortificadas, y desde las ciudades fortificadas hasta el Río, y de mar a mar, y de monte a monte. </div>
<div id="Mic_7_13" style="display:none;" class="ver_select"><b>Mic 7:13</b>  Y la tierra con sus moradores será asolada por el fruto de sus obras. </div>
<div id="Mic_7_14" style="display:none;" class="ver_select"><b>Mic 7:14</b>  Apacienta a tu pueblo con tu cayado, el rebaño de tu heredad, que mora solo en el bosque, en medio del Carmelo; Que pasten en Basán y Galaad, como en el tiempo pasado. </div>
<div id="Mic_7_15" style="display:none;" class="ver_select"><b>Mic 7:15</b>  Yo les mostraré maravillas como el día que saliste de la tierra de Egipto. </div>
<div id="Mic_7_16" style="display:none;" class="ver_select"><b>Mic 7:16</b>  Las naciones verán, y quedarán confundidas de todo su poderío; pondrán la mano sobre su boca, ensordecerán sus oídos. </div>
<div id="Mic_7_17" style="display:none;" class="ver_select"><b>Mic 7:17</b>  Lamerán el polvo como la serpiente; saldrán de su agujeros como los gusanos de la tierra, temblarán en sus encierros; tendrán pavor de Jehová nuestro Dios, y temerán a causa de ti. </div>
<div id="Mic_7_18" style="display:none;" class="ver_select"><b>Mic 7:18</b>  ¿Qué Dios como tú, que perdonas la maldad, y olvidas el pecado del resto de su heredad? No retuvo para siempre su enojo, porque es amador de misericordia. </div>
<div id="Mic_7_19" style="display:none;" class="ver_select"><b>Mic 7:19</b>  Él volverá, Él tendrá misericordia de nosotros; Él sujetará nuestras iniquidades, y echará en lo profundo del mar todos nuestros pecados. </div>
<div id="Mic_7_20" style="display:none;" class="ver_select"><b>Mic 7:20</b>  Otorgarás a Jacob la verdad, y a Abraham la misericordia, que tú juraste a nuestros padres desde tiempos antiguos. </div>
