<div id="Nah_1_1" style="display:none;" class="ver_select"><b>Nah 1:1</b>  Carga de Nínive. Libro de la visión de Nahúm de Elcos. </div>
<div id="Nah_1_2" style="display:none;" class="ver_select"><b>Nah 1:2</b>  Dios celoso y vengador es Jehová; vengador es Jehová y lleno de indignación; Jehová tomará venganza de sus adversarios, y guarda ira para sus enemigos. </div>
<div id="Nah_1_3" style="display:none;" class="ver_select"><b>Nah 1:3</b>  Jehová es lento para la ira, y grande en poder, no tendrá por inocente al culpable. Jehová marcha en la tempestad y el torbellino, y las nubes son el polvo de sus pies. </div>
<div id="Nah_1_4" style="display:none;" class="ver_select"><b>Nah 1:4</b>  Él reprende al mar, y lo hace secar, y agosta todos los ríos: Languidecen Basán y el Carmelo, y la flor del Líbano se marchita. </div>
<div id="Nah_1_5" style="display:none;" class="ver_select"><b>Nah 1:5</b>  Los montes tiemblan delante de Él, y los collados se disuelven; y la tierra se enciende a su presencia, y el mundo, y todos los que en él habitan. </div>
<div id="Nah_1_6" style="display:none;" class="ver_select"><b>Nah 1:6</b>  ¿Quién permanecerá delante de su ira? ¿Y quién quedará en pie en el furor de su enojo? Su ira se derrama como fuego, y por Él las rocas son quebradas. </div>
<div id="Nah_1_7" style="display:none;" class="ver_select"><b>Nah 1:7</b>  Bueno es Jehová, es fortaleza en el día de la angustia; y conoce a los que en Él confían. </div>
<div id="Nah_1_8" style="display:none;" class="ver_select"><b>Nah 1:8</b>  Mas con inundación impetuosa hará consumación de su lugar, y tinieblas perseguirán a sus enemigos. </div>
<div id="Nah_1_9" style="display:none;" class="ver_select"><b>Nah 1:9</b>  ¿Qué tramáis contra Jehová? Él hará consumación; la tribulación no se levantará dos veces. </div>
<div id="Nah_1_10" style="display:none;" class="ver_select"><b>Nah 1:10</b>  Porque como espinas entretejidas, estando embriagados con su vino, serán consumidos como paja completamente seca. </div>
<div id="Nah_1_11" style="display:none;" class="ver_select"><b>Nah 1:11</b>  De ti salió el que tramó mal contra Jehová, un consejero perverso. </div>
<div id="Nah_1_12" style="display:none;" class="ver_select"><b>Nah 1:12</b>  Así dice Jehová: Aunque reposo tengan, y sean muchos, aun así serán talados, y él pasará. Aunque te he afligido, no te afligiré más. </div>
<div id="Nah_1_13" style="display:none;" class="ver_select"><b>Nah 1:13</b>  Porque ahora quebraré su yugo de sobre ti, y romperé tus coyundas. </div>
<div id="Nah_1_14" style="display:none;" class="ver_select"><b>Nah 1:14</b>  Mas acerca de ti mandará Jehová, que nunca más sea sembrado alguno de tu nombre; de la casa de tus dioses talaré escultura y estatua de fundición, la haré tu sepulcro; porque fuiste vil. </div>
<div id="Nah_1_15" style="display:none;" class="ver_select"><b>Nah 1:15</b>  He aquí sobre los montes los pies del que trae buenas nuevas, del que pregona la paz. Celebra, oh Judá, tus fiestas, cumple tus votos; porque nunca más pasará por ti el malvado; pereció del todo. </div>
<div id="Nah_2_1" style="display:none;" class="ver_select"><b>Nah 2:1</b>  Subió destruidor contra ti; guarda la fortaleza, mira el camino, fortifica los lomos, fortalece mucho la fuerza. </div>
<div id="Nah_2_2" style="display:none;" class="ver_select"><b>Nah 2:2</b>  Porque Jehová restituirá la gloria de Jacob como la gloria de Israel; porque vaciadores los vaciaron, y estropearon sus pámpanos. </div>
<div id="Nah_2_3" style="display:none;" class="ver_select"><b>Nah 2:3</b>  El escudo de sus valientes estará enrojecido, sus valientes vestidos de escarlata; los carros serán con fuego de antorchas en el día de su preparación, y las hayas temblarán. </div>
<div id="Nah_2_4" style="display:none;" class="ver_select"><b>Nah 2:4</b>  Los carros se precipitarán en las calles, discurrirán por las plazas; su parecer como antorchas encendidas; correrán como relámpagos. </div>
<div id="Nah_2_5" style="display:none;" class="ver_select"><b>Nah 2:5</b>  Él se acordará de sus valientes; andando tropezarán; se apresurarán a su muro; y se preparará la defensa. </div>
<div id="Nah_2_6" style="display:none;" class="ver_select"><b>Nah 2:6</b>  Las compuertas de los ríos se abrirán, y el palacio será destruido. </div>
<div id="Nah_2_7" style="display:none;" class="ver_select"><b>Nah 2:7</b>  Y la reina será llevada en cautividad; le mandarán que suba, y sus criadas la llevarán gimiendo como palomas, golpeándose su pecho. </div>
<div id="Nah_2_8" style="display:none;" class="ver_select"><b>Nah 2:8</b>  Y fue Nínive de tiempo antiguo como estanque de aguas; mas ellos huyen: Parad, parad; y ninguno mira. </div>
<div id="Nah_2_9" style="display:none;" class="ver_select"><b>Nah 2:9</b>  Saquead plata, saquead oro; no hay fin de las riquezas y suntuosidad de todos los objetos preciosos. </div>
<div id="Nah_2_10" style="display:none;" class="ver_select"><b>Nah 2:10</b>  Vacía, y agotada, y despedazada está, y el corazón derretido; temblor de rodillas, y dolor en todos los lomos, y los rostros de todos tomarán negrura. </div>
<div id="Nah_2_11" style="display:none;" class="ver_select"><b>Nah 2:11</b>  ¿Qué es de la guarida de los leones, y de la majada de los cachorros de los leones, donde se recogía el león, y la leona, y los cachorros del león, y no había quien los atemorizase? </div>
<div id="Nah_2_12" style="display:none;" class="ver_select"><b>Nah 2:12</b>  El león arrebataba en abundancia para sus cachorros, y ahogaba para sus leonas, y llenaba de presa sus cavernas, y de robo sus guaridas. </div>
<div id="Nah_2_13" style="display:none;" class="ver_select"><b>Nah 2:13</b>  Heme aquí contra ti, dice Jehová de los ejércitos. Encenderé y reduciré a humo tus carros, y espada devorará tus leoncillos; y raeré de la tierra tu robo, y nunca más se oirá la voz de tus embajadores. </div>
<div id="Nah_3_1" style="display:none;" class="ver_select"><b>Nah 3:1</b>  ¡Ay de la ciudad sanguinaria, toda llena de mentira y de rapiña, sin apartarse de ella el pillaje! </div>
<div id="Nah_3_2" style="display:none;" class="ver_select"><b>Nah 3:2</b>  Sonido de látigo, y estruendo de movimiento de ruedas; y caballo atropellador, y carro saltador; </div>
<div id="Nah_3_3" style="display:none;" class="ver_select"><b>Nah 3:3</b>  caballero enhiesto, y resplandor de espada, y resplandor de lanza; y multitud de muertos, y multitud de cadáveres; y de sus cadáveres no habrá fin, y en sus cadáveres tropezarán: </div>
<div id="Nah_3_4" style="display:none;" class="ver_select"><b>Nah 3:4</b>  A causa de la multitud de las fornicaciones de la ramera de hermosa gala, maestra de hechizos, que vende a las naciones con sus fornicaciones, y a los pueblos con sus hechizos. </div>
<div id="Nah_3_5" style="display:none;" class="ver_select"><b>Nah 3:5</b>  Heme aquí contra ti, dice Jehová de los ejércitos, y descubriré tus faldas en tu cara, y mostraré a las naciones tu desnudez, y a los reinos tu vergüenza. </div>
<div id="Nah_3_6" style="display:none;" class="ver_select"><b>Nah 3:6</b>  Y echaré sobre ti inmundicias, y te haré vil, y haré de ti un espectáculo. </div>
<div id="Nah_3_7" style="display:none;" class="ver_select"><b>Nah 3:7</b>  Y será que todos los que te vieren, se apartarán de ti, y dirán: Nínive es asolada: ¿quién se compadecerá de ella? ¿Dónde te buscaré consoladores? </div>
<div id="Nah_3_8" style="display:none;" class="ver_select"><b>Nah 3:8</b>  ¿Eres tú mejor que No-amón, que estaba asentada entre ríos, rodeada de aguas, cuyo baluarte era el mar, y el mar era su muralla? </div>
<div id="Nah_3_9" style="display:none;" class="ver_select"><b>Nah 3:9</b>  Etiopía era su fortaleza, y Egipto sin límite; Fut y Libia fueron en tu ayuda. </div>
<div id="Nah_3_10" style="display:none;" class="ver_select"><b>Nah 3:10</b>  También ella fue llevada en cautiverio; también sus chiquitos fueron estrellados en las encrucijadas de todas las calles; y sobre sus varones echaron suertes, y todos sus magnates fueron aprisionados con grillos. </div>
<div id="Nah_3_11" style="display:none;" class="ver_select"><b>Nah 3:11</b>  Tú también serás embriagada, serás encerrada; tú también buscarás fortaleza a causa del enemigo. </div>
<div id="Nah_3_12" style="display:none;" class="ver_select"><b>Nah 3:12</b>  Todas tus fortalezas cual higueras con brevas; que si las sacuden, caen en la boca del que las ha de comer. </div>
<div id="Nah_3_13" style="display:none;" class="ver_select"><b>Nah 3:13</b>  He aquí, tu pueblo será como mujeres en medio de ti; las puertas de tu tierra se abrirán de par en par a tus enemigos; fuego consumirá tus cerrojos. </div>
<div id="Nah_3_14" style="display:none;" class="ver_select"><b>Nah 3:14</b>  Provéete de agua para el asedio, refuerza tus fortalezas; entra en el lodo, pisa el barro, refuerza el horno. </div>
<div id="Nah_3_15" style="display:none;" class="ver_select"><b>Nah 3:15</b>  Allí te consumirá el fuego, te talará la espada, te devorará como pulgón; multiplícate como el pulgón, multiplícate como langosta. </div>
<div id="Nah_3_16" style="display:none;" class="ver_select"><b>Nah 3:16</b>  Multiplicaste tus mercaderes más que las estrellas del cielo; el pulgón hizo presa, y voló. </div>
<div id="Nah_3_17" style="display:none;" class="ver_select"><b>Nah 3:17</b>  Tus príncipes son como langostas, y tus grandes como nubes de langostas que se sientan en vallados en día de frío; salido el sol se van, y no se conoce el lugar donde están. </div>
<div id="Nah_3_18" style="display:none;" class="ver_select"><b>Nah 3:18</b>  Durmieron tus pastores, oh rey de Asiria, reposaron tus valientes; tu pueblo se derramó por los montes, y no hay quien lo junte. </div>
<div id="Nah_3_19" style="display:none;" class="ver_select"><b>Nah 3:19</b>  No hay alivio para tu quebradura; tu herida es incurable; todos los que oigan tu fama aplaudirán sobre ti, porque ¿sobre quién no pasó continuamente tu maldad? </div>
