<div id="Neh_1_1" style="display:none;" class="ver_select"><b>Neh 1:1</b>  Palabras de Nehemías, hijo de Hacalías. Aconteció en el mes de Quisleu, en el año veinte, estando yo en Susán, capital del reino, </div>
<div id="Neh_1_2" style="display:none;" class="ver_select"><b>Neh 1:2</b>  que vino Hanani, uno de mis hermanos, él y ciertos varones de Judá, y les pregunté por los judíos que habían escapado, que habían quedado de la cautividad, y por Jerusalén. </div>
<div id="Neh_1_3" style="display:none;" class="ver_select"><b>Neh 1:3</b>  Y me dijeron: El remanente, los que quedaron de la cautividad allí en la provincia, están en gran mal y afrenta, y el muro de Jerusalén derribado, y sus puertas quemadas a fuego. </div>
<div id="Neh_1_4" style="display:none;" class="ver_select"><b>Neh 1:4</b>  Y sucedió que, cuando yo oí estas palabras, me senté y lloré, e hice duelo por algunos días, y ayuné y oré delante del Dios del cielo. </div>
<div id="Neh_1_5" style="display:none;" class="ver_select"><b>Neh 1:5</b>  Y dije: Te ruego, oh Jehová, Dios del cielo, Dios grande y terrible, que guarda el pacto y la misericordia a los que le aman y guardan sus mandamientos; </div>
<div id="Neh_1_6" style="display:none;" class="ver_select"><b>Neh 1:6</b>  Esté ahora atento tu oído, y tus ojos abiertos, para oír la oración de tu siervo, que yo hago ahora delante de ti día y noche, por los hijos de Israel tus siervos; y confieso los pecados de los hijos de Israel que hemos contra ti cometido; sí, yo y la casa de mi padre hemos pecado. </div>
<div id="Neh_1_7" style="display:none;" class="ver_select"><b>Neh 1:7</b>  En extremo nos hemos corrompido contra ti, y no hemos guardado los mandamientos, y estatutos y juicios, que mandaste a Moisés tu siervo. </div>
<div id="Neh_1_8" style="display:none;" class="ver_select"><b>Neh 1:8</b>  Acuérdate ahora de la palabra que ordenaste a Moisés tu siervo, diciendo: Vosotros prevaricaréis, y yo os esparciré por los pueblos: </div>
<div id="Neh_1_9" style="display:none;" class="ver_select"><b>Neh 1:9</b>  Pero si os volviereis a mí, y guardareis mis mandamientos, y los pusiereis por obra, aunque vuestros desterrados estén hasta el extremo de los cielos, de allí os reuniré; y los traeré al lugar que escogí para hacer habitar allí mi nombre. </div>
<div id="Neh_1_10" style="display:none;" class="ver_select"><b>Neh 1:10</b>  Ellos, pues, son tus siervos y tu pueblo, los cuales redimiste con tu gran fortaleza, y con tu mano fuerte. </div>
<div id="Neh_1_11" style="display:none;" class="ver_select"><b>Neh 1:11</b>  Te ruego, oh Señor, esté ahora atento tu oído a la oración de tu siervo, y a la oración de tus siervos, quienes desean temer tu nombre. Prospera a tu siervo hoy, y concédele hallar misericordia delante de aquel varón. Porque yo servía de copero al rey. </div>
<div id="Neh_2_1" style="display:none;" class="ver_select"><b>Neh 2:1</b>  Y sucedió en el mes de Nisán, en el año veinte del rey Artajerjes, que estando ya el vino delante de él, tomé el vino, y lo di al rey. Y como yo no había estado antes triste en su presencia, </div>
<div id="Neh_2_2" style="display:none;" class="ver_select"><b>Neh 2:2</b>  me dijo el rey: ¿Por qué está triste tu rostro, pues no estás enfermo? No es esto sino quebranto de corazón. Entonces temí en gran manera. </div>
<div id="Neh_2_3" style="display:none;" class="ver_select"><b>Neh 2:3</b>  Y dije al rey: Viva el rey para siempre. ¿Cómo no ha de estar triste mi rostro, cuando la ciudad, casa de los sepulcros de mis padres, está desierta, y sus puertas consumidas por el fuego? </div>
<div id="Neh_2_4" style="display:none;" class="ver_select"><b>Neh 2:4</b>  Y me dijo el rey: ¿Qué cosa pides? Entonces oré al Dios de los cielos, </div>
<div id="Neh_2_5" style="display:none;" class="ver_select"><b>Neh 2:5</b>  y dije al rey: Si le place al rey, y si tu siervo ha hallado gracia delante de ti, envíame a Judá, a la ciudad de los sepulcros de mis padres, para que yo la reedifique. </div>
<div id="Neh_2_6" style="display:none;" class="ver_select"><b>Neh 2:6</b>  Entonces el rey me dijo (y la reina estaba sentada junto a él): ¿Cuánto durará tu viaje, y cuándo volverás? Y agradó al rey enviarme, y le señalé tiempo. </div>
<div id="Neh_2_7" style="display:none;" class="ver_select"><b>Neh 2:7</b>  Además dije al rey: Si place al rey, que se me den cartas para los gobernadores del otro lado del río, para que me franqueen el paso hasta que llegue a Judá; </div>
<div id="Neh_2_8" style="display:none;" class="ver_select"><b>Neh 2:8</b>  y carta para Asaf, guarda del bosque del rey, a fin que me dé madera para enmaderar los portales del palacio de la casa, y para el muro de la ciudad, y para la casa donde yo estaré. Y el rey me lo otorgó, según la bondadosa mano de mi Dios sobre mí. </div>
<div id="Neh_2_9" style="display:none;" class="ver_select"><b>Neh 2:9</b>  Y vine luego a los gobernadores del otro lado del río, y les di las cartas del rey. Y el rey envió conmigo capitanes del ejército y gente de a caballo. </div>
<div id="Neh_2_10" style="display:none;" class="ver_select"><b>Neh 2:10</b>  Y oyéndolo Sanbalat horonita, y Tobías, el siervo amonita, les desagradó en extremo que viniese alguno para procurar el bien de los hijos de Israel. </div>
<div id="Neh_2_11" style="display:none;" class="ver_select"><b>Neh 2:11</b>  Llegué, pues, a Jerusalén, y después de estar allí tres días, </div>
<div id="Neh_2_12" style="display:none;" class="ver_select"><b>Neh 2:12</b>  me levanté de noche, yo y unos cuantos varones conmigo, y no declaré a hombre alguno lo que Dios había puesto en mi corazón que hiciese en Jerusalén; ni había bestia conmigo, excepto la cabalgadura en que cabalgaba. </div>
<div id="Neh_2_13" style="display:none;" class="ver_select"><b>Neh 2:13</b>  Y salí de noche por la puerta del Valle hacia la fuente del Dragón y a la puerta del Muladar; y observé los muros de Jerusalén que estaban derribados, y sus puertas estaban consumidas por el fuego. </div>
<div id="Neh_2_14" style="display:none;" class="ver_select"><b>Neh 2:14</b>  Pasé luego a la puerta de la Fuente, y al estanque del Rey; pero no había lugar por donde pasase la cabalgadura en que iba. </div>
<div id="Neh_2_15" style="display:none;" class="ver_select"><b>Neh 2:15</b>  Y subí de noche por el torrente, y observé el muro, y regresando entré por la puerta del Valle, y regresé. </div>
<div id="Neh_2_16" style="display:none;" class="ver_select"><b>Neh 2:16</b>  Y no sabían los magistrados a dónde yo había ido, ni qué había hecho; ni hasta entonces lo había yo declarado a los judíos y sacerdotes, ni a los nobles y magistrados, ni a los demás que hacían la obra. </div>
<div id="Neh_2_17" style="display:none;" class="ver_select"><b>Neh 2:17</b>  Les dije, pues: Vosotros veis el mal en que estamos, que Jerusalén está desierta, y sus puertas consumidas por el fuego; venid, y edifiquemos el muro de Jerusalén, y no seamos más oprobio. </div>
<div id="Neh_2_18" style="display:none;" class="ver_select"><b>Neh 2:18</b>  Entonces les declaré cómo la mano de mi Dios era buena sobre mí, y asimismo las palabras del rey, que me había dicho. Y dijeron: Levantémonos y edifiquemos. Así esforzaron sus manos para bien. </div>
<div id="Neh_2_19" style="display:none;" class="ver_select"><b>Neh 2:19</b>  Mas habiéndolo oído Sanbalat horonita, y Tobías el siervo amonita, y Gesem el árabe, hicieron escarnio de nosotros, y nos despreciaron, diciendo: ¿Qué es esto que hacéis vosotros? ¿Os rebeláis contra el rey? </div>
<div id="Neh_2_20" style="display:none;" class="ver_select"><b>Neh 2:20</b>  Entonces les respondí, y les dije: El Dios del cielo, Él nos prosperará, y nosotros sus siervos nos levantaremos y edificaremos; porque vosotros no tenéis parte ni derecho, ni memoria en Jerusalén. </div>
<div id="Neh_3_1" style="display:none;" class="ver_select"><b>Neh 3:1</b>  Y se levantó Eliasib el sumo sacerdote con sus hermanos los sacerdotes, y edificaron la puerta de las Ovejas. Ellos aparejaron y levantaron sus puertas hasta la torre de Meah, aparejándola hasta la torre de Hananeel. </div>
<div id="Neh_3_2" style="display:none;" class="ver_select"><b>Neh 3:2</b>  Y junto a ella edificaron los varones de Jericó; y luego edificó Zacur hijo de Imri. </div>
<div id="Neh_3_3" style="display:none;" class="ver_select"><b>Neh 3:3</b>  Y los hijos de Senaa edificaron la puerta del Pescado; ellos la enmaderaron, y levantaron sus puertas, con sus cerraduras y sus cerrojos. </div>
<div id="Neh_3_4" style="display:none;" class="ver_select"><b>Neh 3:4</b>  Y junto a ellos restauró Meremot hijo de Urías, hijo de Cos, y al lado de ellos, restauró Mesulam hijo de Berequías, hijo de Mesezabeel. Junto a ellos restauró Sadoc hijo de Baana. </div>
<div id="Neh_3_5" style="display:none;" class="ver_select"><b>Neh 3:5</b>  E inmediato a ellos restauraron los tecoítas; pero sus nobles no prestaron su cerviz a la obra de su Señor. </div>
<div id="Neh_3_6" style="display:none;" class="ver_select"><b>Neh 3:6</b>  La puerta Antigua fue restaurada por Joiada hijo de Pasea, y Mesulam hijo de Besodías; ellos la enmaderaron, y levantaron sus puertas, con sus cerraduras y sus cerrojos. </div>
<div id="Neh_3_7" style="display:none;" class="ver_select"><b>Neh 3:7</b>  Junto a ellos restauró Melatías gabaonita, y Jadón meronotita, varones de Gabaón y de Mizpa, que estaban bajo el dominio del gobernador del otro lado del río. </div>
<div id="Neh_3_8" style="display:none;" class="ver_select"><b>Neh 3:8</b>  Y junto a ellos restauró Uziel hijo de Harhaía, de los plateros; junto al cual restauró también Hananías, hijo de un perfumista. Así dejaron reparada a Jerusalén hasta el muro ancho. </div>
<div id="Neh_3_9" style="display:none;" class="ver_select"><b>Neh 3:9</b>  Junto a ellos restauró también Refaías hijo de Hur, príncipe de la mitad de la región de Jerusalén. </div>
<div id="Neh_3_10" style="display:none;" class="ver_select"><b>Neh 3:10</b>  Asimismo restauró junto a ellos, y frente a su casa, Jedaía hijo de Harumaf; y junto a él restauró Hatús hijo de Hasabnías. </div>
<div id="Neh_3_11" style="display:none;" class="ver_select"><b>Neh 3:11</b>  Malquías hijo de Harim y Hasub hijo de Pahat-moab, restauraron la otra medida, y la torre de los Hornos. </div>
<div id="Neh_3_12" style="display:none;" class="ver_select"><b>Neh 3:12</b>  Junto a ellos restauró Salum hijo de Lohes, príncipe de la mitad de la región de Jerusalén, él con sus hijas. </div>
<div id="Neh_3_13" style="display:none;" class="ver_select"><b>Neh 3:13</b>  La puerta del Valle la restauró Hanún con los moradores de Zanoa; ellos la reedificaron, y levantaron sus puertas, con sus cerraduras y sus cerrojos, y mil codos en el muro hasta la puerta del Muladar. </div>
<div id="Neh_3_14" style="display:none;" class="ver_select"><b>Neh 3:14</b>  Y reedificó la puerta del Muladar, Malquías hijo de Recab, príncipe de la provincia de Bet-haquerem; él la reedificó, y levantó sus puertas, sus cerraduras y sus cerrojos. </div>
<div id="Neh_3_15" style="display:none;" class="ver_select"><b>Neh 3:15</b>  Y Salum hijo de Col-hoze, príncipe de la región de Mizpa, restauró la puerta de la Fuente; él la reedificó, y la enmaderó, y levantó sus puertas, sus cerraduras y sus cerrojos, y el muro del estanque de Siloé hacia la huerta del rey, y hasta las gradas que descienden de la ciudad de David. </div>
<div id="Neh_3_16" style="display:none;" class="ver_select"><b>Neh 3:16</b>  Después de él restauró Nehemías hijo de Azbuc, príncipe de la mitad de la región de Bet-zur, hasta delante de los sepulcros de David, y hasta el estanque labrado, y hasta la casa de los Valientes. </div>
<div id="Neh_3_17" style="display:none;" class="ver_select"><b>Neh 3:17</b>  Tras él restauraron los levitas, Rehum hijo de Bani; junto a él restauró Hasabías, príncipe de la mitad de la región de Keila en su región. </div>
<div id="Neh_3_18" style="display:none;" class="ver_select"><b>Neh 3:18</b>  Después de él restauraron sus hermanos, Bavai hijo de Henadad, príncipe de la mitad de la región de Keila. </div>
<div id="Neh_3_19" style="display:none;" class="ver_select"><b>Neh 3:19</b>  Y junto a él restauró Ezer hijo de Jesúa, príncipe de Mizpa, la otra medida frente a la subida de la armería de la esquina. </div>
<div id="Neh_3_20" style="display:none;" class="ver_select"><b>Neh 3:20</b>  Después de él Baruc hijo de Zabai con gran fervor restauró otro tramo, desde la esquina hasta la puerta de la casa de Eliasib sumo sacerdote. </div>
<div id="Neh_3_21" style="display:none;" class="ver_select"><b>Neh 3:21</b>  Tras él restauró Meremot hijo de Urías hijo de Cos otro tramo, desde la entrada de la casa de Eliasib, hasta el cabo de la casa de Eliasib. </div>
<div id="Neh_3_22" style="display:none;" class="ver_select"><b>Neh 3:22</b>  Después de él restauraron los sacerdotes, los varones de la llanura. </div>
<div id="Neh_3_23" style="display:none;" class="ver_select"><b>Neh 3:23</b>  Después de ellos restauraron Benjamín y Hasub, frente a su casa; y después de éstos restauró Azarías, hijo de Maasías hijo de Ananías, cerca de su casa. </div>
<div id="Neh_3_24" style="display:none;" class="ver_select"><b>Neh 3:24</b>  Después de él restauró Binúi hijo de Henadad el otro tramo, desde la casa de Azarías hasta la revuelta, y hasta la esquina. </div>
<div id="Neh_3_25" style="display:none;" class="ver_select"><b>Neh 3:25</b>  Paal hijo de Uzai, enfrente de la esquina y la torre alta que sale de la casa del rey, que está en el patio de la cárcel. Después de él, Pedaías hijo de Paros. </div>
<div id="Neh_3_26" style="display:none;" class="ver_select"><b>Neh 3:26</b>  Y los sirvientes del templo que estaban en Ofel restauraron hasta enfrente de la puerta de las Aguas al oriente, y la torre que sobresalía. </div>
<div id="Neh_3_27" style="display:none;" class="ver_select"><b>Neh 3:27</b>  Después de ellos restauraron los tecoítas otro tramo, enfrente de la grande torre que sobresale, hasta el muro de Ofel. </div>
<div id="Neh_3_28" style="display:none;" class="ver_select"><b>Neh 3:28</b>  Desde la puerta de los Caballos restauraron los sacerdotes, cada uno enfrente de su casa. </div>
<div id="Neh_3_29" style="display:none;" class="ver_select"><b>Neh 3:29</b>  Después de ellos restauró Sadoc hijo de Imer, enfrente de su casa: y después de él restauró Semaías hijo de Secanías, guarda de la puerta Oriental. </div>
<div id="Neh_3_30" style="display:none;" class="ver_select"><b>Neh 3:30</b>  Tras él restauró Hananías hijo de Selemías, y Hanún hijo sexto de Salaf, el otro tramo. Después de él restauró Mesulam, hijo de Berequías, enfrente de su cámara. </div>
<div id="Neh_3_31" style="display:none;" class="ver_select"><b>Neh 3:31</b>  Después de él restauró Malquías hijo del platero, hasta la casa de los sirvientes del templo y de los mercaderes, enfrente de la puerta del Juicio, y hasta la sala de la esquina. </div>
<div id="Neh_3_32" style="display:none;" class="ver_select"><b>Neh 3:32</b>  Y entre la sala de la esquina hasta la puerta de las Ovejas, restauraron los plateros, y los mercaderes. </div>
<div id="Neh_4_1" style="display:none;" class="ver_select"><b>Neh 4:1</b>  Y fue que como oyó Sanbalat que nosotros edificábamos el muro, se encolerizó y se enojó en gran manera, e hizo escarnio de los judíos. </div>
<div id="Neh_4_2" style="display:none;" class="ver_select"><b>Neh 4:2</b>  Y habló delante de sus hermanos y del ejército de Samaria, y dijo: ¿Qué hacen estos débiles judíos? ¿Se fortalecerán a sí mismos? ¿Han de sacrificar? ¿Han de acabar en un día? ¿Resucitarán las piedras de los montones de escombro que fueron quemados? </div>
<div id="Neh_4_3" style="display:none;" class="ver_select"><b>Neh 4:3</b>  Y estaba junto a él Tobías amonita, el cual dijo: Aun lo que ellos edifican, si sube una zorra, derribará su muro de piedra. </div>
<div id="Neh_4_4" style="display:none;" class="ver_select"><b>Neh 4:4</b>  Oye, oh Dios nuestro, que somos menospreciados, y vuelve el oprobio de ellos sobre su cabeza, y dalos en presa en la tierra de su cautiverio. </div>
<div id="Neh_4_5" style="display:none;" class="ver_select"><b>Neh 4:5</b>  No cubras su iniquidad, ni su pecado sea borrado delante de ti; porque te provocaron a ira delante de los que edificaban. </div>
<div id="Neh_4_6" style="display:none;" class="ver_select"><b>Neh 4:6</b>  Edificamos, pues, el muro, y toda la muralla fue unida hasta la mitad de su altura, porque el pueblo tuvo ánimo para trabajar. </div>
<div id="Neh_4_7" style="display:none;" class="ver_select"><b>Neh 4:7</b>  Mas aconteció que oyendo Sanbalat y Tobías, y los árabes, y los amonitas, y los de Asdod, que los muros de Jerusalén eran reparados, porque ya los portillos comenzaban a cerrarse, se encolerizaron mucho; </div>
<div id="Neh_4_8" style="display:none;" class="ver_select"><b>Neh 4:8</b>  y conspiraron todos a una para venir a combatir a Jerusalén, y a hacerle daño. </div>
<div id="Neh_4_9" style="display:none;" class="ver_select"><b>Neh 4:9</b>  Entonces oramos a nuestro Dios, y por causa de ellos pusimos guarda contra ellos de día y de noche. </div>
<div id="Neh_4_10" style="display:none;" class="ver_select"><b>Neh 4:10</b>  Y dijo Judá: Las fuerzas de los acarreadores se han debilitado, y el escombro es mucho, y no podemos edificar el muro. </div>
<div id="Neh_4_11" style="display:none;" class="ver_select"><b>Neh 4:11</b>  Y nuestros enemigos dijeron: No sepan, ni vean, hasta que entremos en medio de ellos, y los matemos, y hagamos cesar la obra. </div>
<div id="Neh_4_12" style="display:none;" class="ver_select"><b>Neh 4:12</b>  Pero sucedió que cuando vinieron los judíos que habitaban entre ellos, nos dijeron diez veces: De todos los lugares de donde volviereis a nosotros, ellos vendrán sobre vosotros. </div>
<div id="Neh_4_13" style="display:none;" class="ver_select"><b>Neh 4:13</b>  Entonces puse por los lugares bajos, detrás del muro, en los lugares altos, puse al pueblo por familias con sus espadas, con sus lanzas, y con sus arcos. </div>
<div id="Neh_4_14" style="display:none;" class="ver_select"><b>Neh 4:14</b>  Después miré, y me levanté, y dije a los principales y a los magistrados, y al resto del pueblo: No temáis delante de ellos: acordaos del Señor grande y terrible, y pelead por vuestros hermanos, por vuestros hijos y por vuestras hijas, por vuestras esposas y por vuestras casas. </div>
<div id="Neh_4_15" style="display:none;" class="ver_select"><b>Neh 4:15</b>  Y sucedió que cuando oyeron nuestros enemigos que nos habíamos enterado, y que Dios había desbaratado el consejo de ellos, nos volvimos todos al muro, cada uno a su obra. </div>
<div id="Neh_4_16" style="display:none;" class="ver_select"><b>Neh 4:16</b>  Mas fue que desde aquel día la mitad de los jóvenes trabajaba en la obra, y la otra mitad de ellos tenía lanzas y escudos, y arcos, y corazas; y los príncipes estaban tras toda la casa de Judá. </div>
<div id="Neh_4_17" style="display:none;" class="ver_select"><b>Neh 4:17</b>  Los que edificaban en el muro, y los que llevaban cargas y los que cargaban, con una mano trabajaban en la obra, y en la otra tenían la espada. </div>
<div id="Neh_4_18" style="display:none;" class="ver_select"><b>Neh 4:18</b>  Porque los que edificaban, cada uno tenía su espada ceñida a sus lomos, y así edificaban y el que tocaba la trompeta estaba junto a mí. </div>
<div id="Neh_4_19" style="display:none;" class="ver_select"><b>Neh 4:19</b>  Y dije a los principales, y a los magistrados y al resto del pueblo: La obra es grande y amplia, y nosotros estamos apartados en el muro, lejos los unos de los otros. </div>
<div id="Neh_4_20" style="display:none;" class="ver_select"><b>Neh 4:20</b>  En el lugar donde oyereis la voz de la trompeta, reuníos allí con nosotros. Nuestro Dios peleará por nosotros. </div>
<div id="Neh_4_21" style="display:none;" class="ver_select"><b>Neh 4:21</b>  Nosotros, pues, trabajábamos en la obra; y la mitad de ellos tenían lanzas desde la subida del alba hasta salir las estrellas. </div>
<div id="Neh_4_22" style="display:none;" class="ver_select"><b>Neh 4:22</b>  También dije entonces al pueblo: Cada uno con su criado se quede dentro de Jerusalén, para que de noche nos sirvan de centinelas, y de día en la obra. </div>
<div id="Neh_4_23" style="display:none;" class="ver_select"><b>Neh 4:23</b>  Y ni yo, ni mis hermanos, ni mis mozos, ni la gente de guardia que me seguía, desnudamos nuestra ropa; cada uno se desnudaba solamente para lavarse. </div>
<div id="Neh_5_1" style="display:none;" class="ver_select"><b>Neh 5:1</b>  Entonces fue grande el clamor del pueblo y de sus esposas contra los judíos sus hermanos. </div>
<div id="Neh_5_2" style="display:none;" class="ver_select"><b>Neh 5:2</b>  Y había quien decía: Nosotros, nuestros hijos y nuestras hijas, somos muchos; por tanto hemos tomado grano para comer y vivir. </div>
<div id="Neh_5_3" style="display:none;" class="ver_select"><b>Neh 5:3</b>  Y había quienes decían: Hemos empeñado nuestras tierras, y nuestras viñas, y nuestras casas, para comprar grano, por causa del hambre. </div>
<div id="Neh_5_4" style="display:none;" class="ver_select"><b>Neh 5:4</b>  Y había quienes decían: Hemos tomado prestado dinero para el tributo del rey, sobre nuestras tierras y viñas. </div>
<div id="Neh_5_5" style="display:none;" class="ver_select"><b>Neh 5:5</b>  Ahora bien, nuestra carne es como la carne de nuestros hermanos, nuestros hijos como sus hijos; y he aquí que nosotros estamos sometiendo a nuestros hijos y a nuestras hijas a servidumbre, y algunas de nuestras hijas ya están sujetas a servidumbre; y no tenemos poder para rescatarlas, porque nuestras tierras y nuestras viñas son de otros. </div>
<div id="Neh_5_6" style="display:none;" class="ver_select"><b>Neh 5:6</b>  Y me enojé en gran manera cuando oí su clamor y estas palabras. </div>
<div id="Neh_5_7" style="display:none;" class="ver_select"><b>Neh 5:7</b>  Entonces lo medité, y reprendí a los nobles y a los magistrados, y les dije: ¿Tomáis cada uno usura de vuestros hermanos? Y convoqué contra ellos una gran asamblea. </div>
<div id="Neh_5_8" style="display:none;" class="ver_select"><b>Neh 5:8</b>  Y les dije: Nosotros conforme a nuestras posibilidades rescatamos a nuestros hermanos judíos que habían sido vendidos a las naciones; ¿y vosotros venderéis aun a vuestros hermanos, o serán vendidos a nosotros? Y callaron, pues no tuvieron qué responder. </div>
<div id="Neh_5_9" style="display:none;" class="ver_select"><b>Neh 5:9</b>  Y dije: No está bien lo que hacéis, ¿no andaréis en temor de nuestro Dios, para no ser el oprobio de las naciones que son nuestras enemigas? </div>
<div id="Neh_5_10" style="display:none;" class="ver_select"><b>Neh 5:10</b>  También yo, y mis hermanos, y mis criados, les hemos prestado dinero y grano; absolvámosles ahora de este gravamen. </div>
<div id="Neh_5_11" style="display:none;" class="ver_select"><b>Neh 5:11</b>  Os ruego que les devolváis hoy sus tierras, sus viñas, sus olivares, y sus casas, y la centésima parte del dinero y grano, del vino y del aceite que demandáis de ellos. </div>
<div id="Neh_5_12" style="display:none;" class="ver_select"><b>Neh 5:12</b>  Y dijeron: Devolveremos, y nada les demandaremos; haremos así como tú dices. Entonces convoqué a los sacerdotes, y les hice jurar que harían conforme a esto. </div>
<div id="Neh_5_13" style="display:none;" class="ver_select"><b>Neh 5:13</b>  Además sacudí mi ropa, y dije: Así sacuda Dios de su casa y de su trabajo a todo hombre que no cumpliere esto, y así sea sacudido y vacío. Y respondió toda la congregación: ¡Amén! Y alabaron a Jehová. Y el pueblo hizo conforme a esto. </div>
<div id="Neh_5_14" style="display:none;" class="ver_select"><b>Neh 5:14</b>  También desde el día que me mandó el rey que fuese gobernador de ellos en la tierra de Judá, desde el año veinte del rey Artajerjes hasta el año treinta y dos, doce años, ni yo ni mis hermanos comimos el pan del gobernador. </div>
<div id="Neh_5_15" style="display:none;" class="ver_select"><b>Neh 5:15</b>  Mas los primeros gobernadores que fueron antes de mí, cargaron al pueblo, y tomaron de ellos por el pan y por el vino sobre cuarenta siclos de plata; a más de esto, sus criados se enseñoreaban sobre el pueblo; pero yo no hice así, a causa del temor de Dios. </div>
<div id="Neh_5_16" style="display:none;" class="ver_select"><b>Neh 5:16</b>  También continué en la obra de restauración de este muro, y no compramos heredad; y todos mis criados juntos estaban allí en la obra. </div>
<div id="Neh_5_17" style="display:none;" class="ver_select"><b>Neh 5:17</b>  Además ciento cincuenta hombres de los judíos y magistrados, y los que venían a nosotros de las naciones que están en nuestros alrededores. </div>
<div id="Neh_5_18" style="display:none;" class="ver_select"><b>Neh 5:18</b>  Y lo que se aderezaba para cada día era un buey, seis ovejas escogidas, y aves también se aparejaban para mí, y cada diez días vino en toda abundancia: y con todo esto nunca requerí el pan del gobernador, porque la servidumbre de este pueblo era grave. </div>
<div id="Neh_5_19" style="display:none;" class="ver_select"><b>Neh 5:19</b>  Acuérdate de mí para bien, Dios mío, y de todo lo que hice por este pueblo. </div>
<div id="Neh_6_1" style="display:none;" class="ver_select"><b>Neh 6:1</b>  Y aconteció que habiendo oído Sanbalat y Tobías y Gesem el árabe, y el resto de nuestros enemigos, que yo había edificado el muro, y que no quedaba en él portillo (aunque hasta aquel tiempo no había puesto las hojas en las puertas), </div>
<div id="Neh_6_2" style="display:none;" class="ver_select"><b>Neh 6:2</b>  Sanbalat y Gesem enviaron a decirme: Ven y reunámonos juntos en alguna de las aldeas en el campo de Ono. Pero ellos habían pensado hacerme mal. </div>
<div id="Neh_6_3" style="display:none;" class="ver_select"><b>Neh 6:3</b>  Y les envié mensajeros, diciendo: Yo hago una gran obra, y no puedo ir; porque cesaría la obra, dejándola yo para ir a vosotros. </div>
<div id="Neh_6_4" style="display:none;" class="ver_select"><b>Neh 6:4</b>  Y enviaron a mí con el mismo asunto por cuatro veces, y yo les respondí de la misma manera. </div>
<div id="Neh_6_5" style="display:none;" class="ver_select"><b>Neh 6:5</b>  Envió entonces Sanbalat a mí su criado, a decir lo mismo por quinta vez, con una carta abierta en su mano, </div>
<div id="Neh_6_6" style="display:none;" class="ver_select"><b>Neh 6:6</b>  en la cual estaba escrito: Se ha oído entre las naciones, y Gasmu lo dice, que tú y los judíos pensáis rebelaros; y que por eso edificas tú el muro, con la mira, según estas palabras, de ser tú su rey; </div>
<div id="Neh_6_7" style="display:none;" class="ver_select"><b>Neh 6:7</b>  Y que has puesto profetas que prediquen de ti en Jerusalén, diciendo: ¡Hay rey en Judá! Y ahora serán oídas del rey las tales palabras; ven por tanto, y consultemos juntos. </div>
<div id="Neh_6_8" style="display:none;" class="ver_select"><b>Neh 6:8</b>  Entonces envié yo a decirles: No hay tal cosa como dices, sino que de tu corazón tú lo inventas. </div>
<div id="Neh_6_9" style="display:none;" class="ver_select"><b>Neh 6:9</b>  Porque todos ellos nos intimidaban, diciendo: Se debilitarán las manos de ellos en la obra, y no será hecha. Ahora, pues, oh Dios, fortalece mis manos. </div>
<div id="Neh_6_10" style="display:none;" class="ver_select"><b>Neh 6:10</b>  Vine luego a casa de Semaías hijo de Delaías, hijo de Mehetabel, porque él estaba encerrado; el cual me dijo: Reunámonos en la casa de Dios dentro del templo, y cerremos las puertas del templo, porque vienen para matarte; sí, esta noche vendrán a matarte. </div>
<div id="Neh_6_11" style="display:none;" class="ver_select"><b>Neh 6:11</b>  Entonces dije: ¿Un hombre como yo ha de huir? ¿Y quién, que fuera como yo, entraría al templo para salvar su vida? ¡No entraré! </div>
<div id="Neh_6_12" style="display:none;" class="ver_select"><b>Neh 6:12</b>  Y entendí que Dios no lo había enviado, sino que hablaba aquella profecía contra mí, porque Tobías y Sanbalat le habían alquilado por salario. </div>
<div id="Neh_6_13" style="display:none;" class="ver_select"><b>Neh 6:13</b>  Porque fue sobornado para que yo fuese intimidado e hiciese así, y que pecase, y les sirviese de mal nombre con que fuera yo infamado. </div>
<div id="Neh_6_14" style="display:none;" class="ver_select"><b>Neh 6:14</b>  Acuérdate, Dios mío, de Tobías y de Sanbalat, conforme a estas sus obras, y también de Noadías profetisa, y de los otros profetas que trataban de intimidarme. </div>
<div id="Neh_6_15" style="display:none;" class="ver_select"><b>Neh 6:15</b>  Así que el muro fue terminado el veinticinco del mes de Elul, en cincuenta y dos días. </div>
<div id="Neh_6_16" style="display:none;" class="ver_select"><b>Neh 6:16</b>  Y sucedió que cuando lo oyeron todos nuestros enemigos, temieron todas las naciones que estaban en nuestros alrededores, y se sintieron muy humillados ante sus propios ojos, y conocieron que esta obra había sido hecha por nuestro Dios. </div>
<div id="Neh_6_17" style="display:none;" class="ver_select"><b>Neh 6:17</b>  Asimismo en aquellos días iban muchas cartas de los nobles de Judá a Tobías, y las de Tobías venían a ellos. </div>
<div id="Neh_6_18" style="display:none;" class="ver_select"><b>Neh 6:18</b>  Porque muchos en Judá se habían conjurado con él, porque era yerno de Secanías hijo de Ara; y Johanán su hijo había tomado la hija de Mesulam, hijo de Berequías. </div>
<div id="Neh_6_19" style="display:none;" class="ver_select"><b>Neh 6:19</b>  También contaban delante de mí las buenas obras de él, y a él le referían mis palabras. Y Tobías enviaba cartas para atemorizarme. </div>
<div id="Neh_7_1" style="display:none;" class="ver_select"><b>Neh 7:1</b>  Y aconteció que, cuando el muro fue edificado, y hube colocado las puertas, y que fueron señalados porteros y cantores y levitas, </div>
<div id="Neh_7_2" style="display:none;" class="ver_select"><b>Neh 7:2</b>  di a mi hermano Hanani, y a Ananás el príncipe del palacio, cargo sobre Jerusalén (porque éste era un hombre fiel y temeroso de Dios, más que muchos); </div>
<div id="Neh_7_3" style="display:none;" class="ver_select"><b>Neh 7:3</b>  y les dije: No se abran las puertas de Jerusalén hasta que caliente el sol; y aun ellos presentes, cierren las puertas, y atrancad. Y señalé guardas de los moradores de Jerusalén, cada cual en su guardia, y cada uno delante de su casa. </div>
<div id="Neh_7_4" style="display:none;" class="ver_select"><b>Neh 7:4</b>  Y la ciudad era espaciosa y grande, pero poco pueblo dentro de ella, y no había casas reedificadas. </div>
<div id="Neh_7_5" style="display:none;" class="ver_select"><b>Neh 7:5</b>  Y puso Dios en mi corazón que reuniese a los nobles, y a los magistrados, y al pueblo, para que fuesen empadronados por el orden de sus linajes: Y hallé el libro de la genealogía de los que habían subido antes, y encontré en él escrito: </div>
<div id="Neh_7_6" style="display:none;" class="ver_select"><b>Neh 7:6</b>  Éstos son los hijos de la provincia que subieron de la cautividad, de la transmigración que hizo pasar Nabucodonosor rey de Babilonia, y que volvieron a Jerusalén y a Judá cada uno a su ciudad; </div>
<div id="Neh_7_7" style="display:none;" class="ver_select"><b>Neh 7:7</b>  los cuales vinieron con Zorobabel, Jesúa, Nehemías, Azarías, Raamías, Nahamani, Mardoqueo, Bilsán, Misperet, Bigvai, Nehum, Baana. La cuenta de los varones del pueblo de Israel. </div>
<div id="Neh_7_8" style="display:none;" class="ver_select"><b>Neh 7:8</b>  Los hijos de Paros, dos mil ciento setenta y dos. </div>
<div id="Neh_7_9" style="display:none;" class="ver_select"><b>Neh 7:9</b>  Los hijos de Sefatías, trescientos setenta y dos. </div>
<div id="Neh_7_10" style="display:none;" class="ver_select"><b>Neh 7:10</b>  Los hijos de Ara, seiscientos cincuenta y dos. </div>
<div id="Neh_7_11" style="display:none;" class="ver_select"><b>Neh 7:11</b>  Los hijos de Pahat-moab, de los hijos de Jesúa y de Joab, dos mil ochocientos dieciocho. </div>
<div id="Neh_7_12" style="display:none;" class="ver_select"><b>Neh 7:12</b>  Los hijos de Elam, mil doscientos cincuenta y cuatro. </div>
<div id="Neh_7_13" style="display:none;" class="ver_select"><b>Neh 7:13</b>  Los hijos de Zatu, ochocientos cuarenta y cinco. </div>
<div id="Neh_7_14" style="display:none;" class="ver_select"><b>Neh 7:14</b>  Los hijos de Zacai, setecientos sesenta. </div>
<div id="Neh_7_15" style="display:none;" class="ver_select"><b>Neh 7:15</b>  Los hijos de Binúi, seiscientos cuarenta y ocho; </div>
<div id="Neh_7_16" style="display:none;" class="ver_select"><b>Neh 7:16</b>  Los hijos de Bebai, seiscientos veintiocho; </div>
<div id="Neh_7_17" style="display:none;" class="ver_select"><b>Neh 7:17</b>  Los hijos de Azgad, dos mil trescientos veintidós. </div>
<div id="Neh_7_18" style="display:none;" class="ver_select"><b>Neh 7:18</b>  Los hijos de Adonicam, seiscientos sesenta y siete. </div>
<div id="Neh_7_19" style="display:none;" class="ver_select"><b>Neh 7:19</b>  Los hijos de Bigvai, dos mil sesenta y siete. </div>
<div id="Neh_7_20" style="display:none;" class="ver_select"><b>Neh 7:20</b>  Los hijos de Adín, seiscientos cincuenta y cinco. </div>
<div id="Neh_7_21" style="display:none;" class="ver_select"><b>Neh 7:21</b>  Los hijos de Ater, de Ezequías, noventa y ocho. </div>
<div id="Neh_7_22" style="display:none;" class="ver_select"><b>Neh 7:22</b>  Los hijos de Hasum, trescientos veintiocho. </div>
<div id="Neh_7_23" style="display:none;" class="ver_select"><b>Neh 7:23</b>  Los hijos de Besai, trescientos veinticuatro. </div>
<div id="Neh_7_24" style="display:none;" class="ver_select"><b>Neh 7:24</b>  Los hijos de Harif, ciento doce. </div>
<div id="Neh_7_25" style="display:none;" class="ver_select"><b>Neh 7:25</b>  Los hijos de Gabaón, noventa y cinco. </div>
<div id="Neh_7_26" style="display:none;" class="ver_select"><b>Neh 7:26</b>  Los varones de Belén y de Netofa, ciento ochenta y ocho. </div>
<div id="Neh_7_27" style="display:none;" class="ver_select"><b>Neh 7:27</b>  Los varones de Anatot, ciento veintiocho. </div>
<div id="Neh_7_28" style="display:none;" class="ver_select"><b>Neh 7:28</b>  Los varones de Bet-azmavet, cuarenta y dos. </div>
<div id="Neh_7_29" style="display:none;" class="ver_select"><b>Neh 7:29</b>  Los varones de Quiriat-jearim, Cefira y Beerot, setecientos cuarenta y tres. </div>
<div id="Neh_7_30" style="display:none;" class="ver_select"><b>Neh 7:30</b>  Los varones de Ramá y de Geba, seiscientos veintiuno. </div>
<div id="Neh_7_31" style="display:none;" class="ver_select"><b>Neh 7:31</b>  Los varones de Micmas, ciento veintidós. </div>
<div id="Neh_7_32" style="display:none;" class="ver_select"><b>Neh 7:32</b>  Los varones de Betel y de Hai, ciento veintitrés. </div>
<div id="Neh_7_33" style="display:none;" class="ver_select"><b>Neh 7:33</b>  Los varones del otro Nebo, cincuenta y dos. </div>
<div id="Neh_7_34" style="display:none;" class="ver_select"><b>Neh 7:34</b>  Los hijos del otro Elam, mil doscientos cincuenta y cuatro. </div>
<div id="Neh_7_35" style="display:none;" class="ver_select"><b>Neh 7:35</b>  Los hijos de Harim, trescientos veinte. </div>
<div id="Neh_7_36" style="display:none;" class="ver_select"><b>Neh 7:36</b>  Los hijos de Jericó, trescientos cuarenta y cinco. </div>
<div id="Neh_7_37" style="display:none;" class="ver_select"><b>Neh 7:37</b>  Los hijos de Lod, de Hadid, y Ono, setecientos veintiuno. </div>
<div id="Neh_7_38" style="display:none;" class="ver_select"><b>Neh 7:38</b>  Los hijos de Senaa, tres mil novecientos treinta. </div>
<div id="Neh_7_39" style="display:none;" class="ver_select"><b>Neh 7:39</b>  Los sacerdotes: los hijos de Jedaías, de la casa de Jesúa, novecientos setenta y tres. </div>
<div id="Neh_7_40" style="display:none;" class="ver_select"><b>Neh 7:40</b>  Los hijos de Imer, mil cincuenta y dos. </div>
<div id="Neh_7_41" style="display:none;" class="ver_select"><b>Neh 7:41</b>  Los hijos de Pasur, mil doscientos cuarenta y siete. </div>
<div id="Neh_7_42" style="display:none;" class="ver_select"><b>Neh 7:42</b>  Los hijos de Harim, mil diecisiete. </div>
<div id="Neh_7_43" style="display:none;" class="ver_select"><b>Neh 7:43</b>  Levitas: los hijos de Jesúa, de Cadmiel, de los hijos de Odevía, setenta y cuatro. </div>
<div id="Neh_7_44" style="display:none;" class="ver_select"><b>Neh 7:44</b>  Cantores: los hijos de Asaf, ciento cuarenta y ocho. </div>
<div id="Neh_7_45" style="display:none;" class="ver_select"><b>Neh 7:45</b>  Porteros: los hijos de Salum, los hijos de Ater, los hijos de Talmón, los hijos de Acub, los hijos de Hatita, los hijos de Sobai, ciento treinta y ocho. </div>
<div id="Neh_7_46" style="display:none;" class="ver_select"><b>Neh 7:46</b>  Sirvientes del templo: los hijos de Siha, los hijos de Hasufa, los hijos de Tabaot, </div>
<div id="Neh_7_47" style="display:none;" class="ver_select"><b>Neh 7:47</b>  los hijos de Queros, los hijos de Siaha, los hijos de Padón, </div>
<div id="Neh_7_48" style="display:none;" class="ver_select"><b>Neh 7:48</b>  los hijos de Lebana, los hijos de Hagaba, los hijos de Salmai, </div>
<div id="Neh_7_49" style="display:none;" class="ver_select"><b>Neh 7:49</b>  los hijos de Hanán, los hijos de Gidel, los hijos de Gahar, </div>
<div id="Neh_7_50" style="display:none;" class="ver_select"><b>Neh 7:50</b>  los hijos de Reaías, los hijos de Rezín, los hijos de Necoda, </div>
<div id="Neh_7_51" style="display:none;" class="ver_select"><b>Neh 7:51</b>  los hijos de Gazam, los hijos de Uza, los hijos de Pasea, </div>
<div id="Neh_7_52" style="display:none;" class="ver_select"><b>Neh 7:52</b>  los hijos de Besai, los hijos de Meunim, los hijos de Nefisesim, </div>
<div id="Neh_7_53" style="display:none;" class="ver_select"><b>Neh 7:53</b>  los hijos de Bacbuc, los hijos de Hacufa, los hijos de Harhur, </div>
<div id="Neh_7_54" style="display:none;" class="ver_select"><b>Neh 7:54</b>  los hijos de Bazlut, los hijos de Mehída, los hijos de Harsa, </div>
<div id="Neh_7_55" style="display:none;" class="ver_select"><b>Neh 7:55</b>  los hijos de Barcos, los hijos de Sísara, los hijos de Tema, </div>
<div id="Neh_7_56" style="display:none;" class="ver_select"><b>Neh 7:56</b>  los hijos de Nesía, los hijos de Hatifa. </div>
<div id="Neh_7_57" style="display:none;" class="ver_select"><b>Neh 7:57</b>  Los hijos de los siervos de Salomón: los hijos de Sotai, los hijos de Soferet, los hijos de Perida, </div>
<div id="Neh_7_58" style="display:none;" class="ver_select"><b>Neh 7:58</b>  los hijos de Jaala, los hijos de Darcón, los hijos de Gidel, </div>
<div id="Neh_7_59" style="display:none;" class="ver_select"><b>Neh 7:59</b>  los hijos de Sefatías, los hijos de Hatil, los hijos de Poqueret-hazebaim, los hijos de Amón. </div>
<div id="Neh_7_60" style="display:none;" class="ver_select"><b>Neh 7:60</b>  Todos los sirvientes del templo, e hijos de los siervos de Salomón, trescientos noventa y dos. </div>
<div id="Neh_7_61" style="display:none;" class="ver_select"><b>Neh 7:61</b>  Y éstos son los que subieron de Tel-mela, Tel-harsa, Querub, Adón, e Imer, los cuales no pudieron mostrar la casa de sus padres, ni su linaje, si eran de Israel: </div>
<div id="Neh_7_62" style="display:none;" class="ver_select"><b>Neh 7:62</b>  Los hijos de Delaías, los hijos de Tobías, los hijos de Necoda, seiscientos cuarenta y dos. </div>
<div id="Neh_7_63" style="display:none;" class="ver_select"><b>Neh 7:63</b>  Y de los sacerdotes: los hijos de Habaías, los hijos de Cos, los hijos de Barzilai, el cual tomó esposa de las hijas de Barzilai galaadita, y se llamó del nombre de ellas. </div>
<div id="Neh_7_64" style="display:none;" class="ver_select"><b>Neh 7:64</b>  Éstos, buscaron su registro de genealogías, y no se halló; y como algo contaminado, fueron excluidos del sacerdocio. 462 </div>
<div id="Neh_7_65" style="display:none;" class="ver_select"><b>Neh 7:65</b>  Y el Tirsata les dijo que no comiesen de las cosas más santas, hasta que hubiese sacerdote con Urim y Tumim. </div>
<div id="Neh_7_66" style="display:none;" class="ver_select"><b>Neh 7:66</b>  La congregación toda junta era de cuarenta y dos mil trescientos sesenta, </div>
<div id="Neh_7_67" style="display:none;" class="ver_select"><b>Neh 7:67</b>  sin sus siervos y siervas, que eran siete mil trescientos treinta y siete; y entre ellos había doscientos cuarenta y cinco cantores y cantoras. </div>
<div id="Neh_7_68" style="display:none;" class="ver_select"><b>Neh 7:68</b>  Sus caballos, setecientos treinta y seis; sus mulos, doscientos cuarenta y cinco; </div>
<div id="Neh_7_69" style="display:none;" class="ver_select"><b>Neh 7:69</b>  camellos, cuatrocientos treinta y cinco; asnos, seis mil setecientos veinte. </div>
<div id="Neh_7_70" style="display:none;" class="ver_select"><b>Neh 7:70</b>  Y algunos de los príncipes de las familias dieron para la obra. El Tirsata dio para el tesoro mil dracmas de oro, cincuenta tazones, y quinientas treinta vestiduras sacerdotales. </div>
<div id="Neh_7_71" style="display:none;" class="ver_select"><b>Neh 7:71</b>  Y de los príncipes de las familias dieron para el tesoro de la obra, veinte mil dracmas de oro, y dos mil doscientas libras de plata. </div>
<div id="Neh_7_72" style="display:none;" class="ver_select"><b>Neh 7:72</b>  Y lo que dio el resto del pueblo fue veinte mil dracmas de oro, y dos mil libras de plata, y sesenta y siete vestiduras sacerdotales. </div>
<div id="Neh_7_73" style="display:none;" class="ver_select"><b>Neh 7:73</b>  Y habitaron los sacerdotes y los levitas, y los porteros, y los cantores, y los del pueblo, y los sirvientes del templo, y todo Israel en sus ciudades. Y venido el mes séptimo, los hijos de Israel estaban en sus ciudades. </div>
<div id="Neh_8_1" style="display:none;" class="ver_select"><b>Neh 8:1</b>  Y se juntó todo el pueblo como un solo hombre en la plaza que está delante de la puerta de las Aguas. Y dijeron al escriba Esdras que trajese el libro de la ley de Moisés, que Jehová mandó a Israel. </div>
<div id="Neh_8_2" style="display:none;" class="ver_select"><b>Neh 8:2</b>  Y Esdras el sacerdote, trajo la ley delante de la congregación, así de hombres como de mujeres, y de todo entendido para escuchar, el primer día del mes séptimo. </div>
<div id="Neh_8_3" style="display:none;" class="ver_select"><b>Neh 8:3</b>  Y leyó en el libro delante de la plaza que está delante de la puerta de las Aguas, desde el alba hasta el mediodía, en presencia de hombres y mujeres y entendidos; y los oídos de todo el pueblo estaban atentos al libro de la ley. </div>
<div id="Neh_8_4" style="display:none;" class="ver_select"><b>Neh 8:4</b>  Y Esdras el escriba estaba sobre un púlpito de madera, que habían hecho para ello; y junto a él, a su mano derecha, estaban Matatías, Sema, Anaías, Urías, Hilcías y Maasías; y a su mano izquierda, Pedaías, Misael, Malquías, Hasum, Hasbadana, Zacarías y Mesulam. </div>
<div id="Neh_8_5" style="display:none;" class="ver_select"><b>Neh 8:5</b>  Abrió, pues, Esdras el libro a ojos de todo el pueblo (porque estaba más alto que todo el pueblo); y como lo abrió, todo el pueblo estuvo atento. </div>
<div id="Neh_8_6" style="display:none;" class="ver_select"><b>Neh 8:6</b>  Bendijo entonces Esdras a Jehová, Dios grande. Y todo el pueblo respondió: ¡Amén! ¡Amén! alzando sus manos; y se humillaron, y adoraron a Jehová con el rostro a tierra. </div>
<div id="Neh_8_7" style="display:none;" class="ver_select"><b>Neh 8:7</b>  Y Jesúa, y Bani, y Serebías, Jamín, Acub, Sabetai, Odías, Maasías, Kelita, Azarías, Jozabad, Hanán, Pelaías, levitas, hacían entender al pueblo la ley; y el pueblo estaba en su lugar. </div>
<div id="Neh_8_8" style="display:none;" class="ver_select"><b>Neh 8:8</b>  Y leían en el libro de la ley de Dios claramente, y ponían el sentido, de modo que entendiesen la lectura. </div>
<div id="Neh_8_9" style="display:none;" class="ver_select"><b>Neh 8:9</b>  Y Nehemías el Tirsata, y el sacerdote Esdras, escriba, y los levitas que hacían entender al pueblo, dijeron a todo el pueblo: Día santo es a Jehová nuestro Dios; no os entristezcáis, ni lloréis: porque todo el pueblo lloraba oyendo las palabras de la ley. </div>
<div id="Neh_8_10" style="display:none;" class="ver_select"><b>Neh 8:10</b>  Luego les dijo: Id, comed grosuras, y bebed vino dulce, y enviad porciones a los que no tienen nada preparado; porque este día es santo a nuestro Señor; y no os entristezcáis, porque el gozo de Jehová es vuestra fortaleza. </div>
<div id="Neh_8_11" style="display:none;" class="ver_select"><b>Neh 8:11</b>  Los levitas, pues, hacían callar a todo el pueblo, diciendo: Callad, que es día santo, y no os entristezcáis. </div>
<div id="Neh_8_12" style="display:none;" class="ver_select"><b>Neh 8:12</b>  Y todo el pueblo se fue a comer y a beber, y a enviar porciones, y a gozar de grande alegría, porque habían entendido las palabras que les habían enseñado. </div>
<div id="Neh_8_13" style="display:none;" class="ver_select"><b>Neh 8:13</b>  Y al día siguiente se reunieron los príncipes de las familias de todo el pueblo, sacerdotes, y levitas, a Esdras escriba, para entender las palabras de la ley. </div>
<div id="Neh_8_14" style="display:none;" class="ver_select"><b>Neh 8:14</b>  Y hallaron escrito en la ley que Jehová había mandado por mano de Moisés, que habitasen los hijos de Israel en cabañas en la fiesta solemne del mes séptimo; </div>
<div id="Neh_8_15" style="display:none;" class="ver_select"><b>Neh 8:15</b>  Y que hiciesen saber, y pasar pregón por todas sus ciudades y por Jerusalén, diciendo: Salid al monte, y traed ramas de olivo, y ramas de pino, y ramas de arrayán, y ramas de palmas, y ramas de todo árbol frondoso, para hacer cabañas como está escrito. </div>
<div id="Neh_8_16" style="display:none;" class="ver_select"><b>Neh 8:16</b>  Salió, pues, el pueblo, y trajeron, y se hicieron cabañas, cada uno sobre su terrado, y en sus patios, y en los patios de la casa de Dios, y en la plaza de la puerta de las Aguas, y en la plaza de la puerta de Efraín. </div>
<div id="Neh_8_17" style="display:none;" class="ver_select"><b>Neh 8:17</b>  Y toda la congregación que volvió de la cautividad hicieron tabernáculos, y en tabernáculos habitaron; porque desde los días de Josué hijo de Nun hasta aquel día, no habían hecho así los hijos de Israel. Y hubo alegría muy grande. </div>
<div id="Neh_8_18" style="display:none;" class="ver_select"><b>Neh 8:18</b>  Y leyó Esdras en el libro de la ley de Dios cada día, desde el primer día hasta el postrero; y celebraron la fiesta por siete días, y el octavo día fue de solemne asamblea, según lo establecido. </div>
<div id="Neh_9_1" style="display:none;" class="ver_select"><b>Neh 9:1</b>  Y el día veinticuatro del mismo mes se reunieron los hijos de Israel en ayuno, y con cilicio y tierra sobre sí. </div>
<div id="Neh_9_2" style="display:none;" class="ver_select"><b>Neh 9:2</b>  Y la simiente de Israel ya se había apartado de todos los extranjeros; y estando en pie, confesaron sus pecados, y las iniquidades de sus padres. </div>
<div id="Neh_9_3" style="display:none;" class="ver_select"><b>Neh 9:3</b>  Y puestos de pie en su lugar, leyeron en el libro de la ley de Jehová su Dios la cuarta parte del día, y la cuarta parte confesaron y adoraron a Jehová su Dios. </div>
<div id="Neh_9_4" style="display:none;" class="ver_select"><b>Neh 9:4</b>  Luego se levantaron sobre la grada de los levitas, Jesúa y Bani, Cadmiel, Sebanías, Buni, Serebías, Bani y Quenani, y clamaron en voz alta a Jehová su Dios. </div>
<div id="Neh_9_5" style="display:none;" class="ver_select"><b>Neh 9:5</b>  Entonces los levitas, Jesúa y Cadmiel, Bani, Hasabnías, Serebías, Odías, Sebanías y Petaías, dijeron: Levantaos, bendecid a Jehová vuestro Dios desde la eternidad hasta la eternidad: Bendito sea tu glorioso nombre, el cual es exaltado sobre toda bendición y alabanza. </div>
<div id="Neh_9_6" style="display:none;" class="ver_select"><b>Neh 9:6</b>  Tú, sólo tú, oh Jehová; tú hiciste el cielo, y el cielo de los cielos, y todo su ejército, la tierra y todo lo que está en ella, los mares y todo lo que hay en ellos; y tú has preservado todas estas cosas, y el ejército del cielo te adora. </div>
<div id="Neh_9_7" style="display:none;" class="ver_select"><b>Neh 9:7</b>  Tú, eres oh Jehová, el Dios que escogiste a Abram, y lo sacaste de Ur de los caldeos, y le pusiste el nombre Abraham; </div>
<div id="Neh_9_8" style="display:none;" class="ver_select"><b>Neh 9:8</b>  Y hallaste fiel su corazón delante de ti, e hiciste pacto con él para darle la tierra del cananeo, del heteo, y del amorreo, y del ferezeo, y del jebuseo, y del gergeseo, para darla a su simiente: y cumpliste tu palabra, porque eres justo. </div>
<div id="Neh_9_9" style="display:none;" class="ver_select"><b>Neh 9:9</b>  Y miraste la aflicción de nuestros padres en Egipto, y oíste el clamor de ellos en el Mar Rojo; </div>
<div id="Neh_9_10" style="display:none;" class="ver_select"><b>Neh 9:10</b>  Y diste señales y maravillas en Faraón, y en todos sus siervos, y en todo el pueblo de su tierra; porque sabías que habían hecho soberbiamente contra ellos; y te hiciste nombre grande, como en este día. </div>
<div id="Neh_9_11" style="display:none;" class="ver_select"><b>Neh 9:11</b>  Y dividiste el mar delante de ellos, y así pasaron por medio de él en seco; y a sus perseguidores echaste en las profundidades, como una piedra en turbulentas aguas. </div>
<div id="Neh_9_12" style="display:none;" class="ver_select"><b>Neh 9:12</b>  Y con columna de nube los guiaste de día, y con columna de fuego de noche, para alumbrarles el camino por donde habían de ir. </div>
<div id="Neh_9_13" style="display:none;" class="ver_select"><b>Neh 9:13</b>  Y sobre el monte de Sinaí descendiste, y hablaste con ellos desde el cielo, y les diste juicios rectos, leyes verdaderas, y estatutos y mandamientos buenos: </div>
<div id="Neh_9_14" style="display:none;" class="ver_select"><b>Neh 9:14</b>  Y les hiciste conocer tu santo sábado, y por mano de Moisés tu siervo les prescribiste mandamientos, estatutos, y leyes. </div>
<div id="Neh_9_15" style="display:none;" class="ver_select"><b>Neh 9:15</b>  Y les diste pan del cielo en su hambre; y en su sed les sacaste aguas de la roca; y les prometiste que entrarían a poseer la tierra, por la cual alzaste tu mano y juraste que se la darías. </div>
<div id="Neh_9_16" style="display:none;" class="ver_select"><b>Neh 9:16</b>  Mas ellos y nuestros padres hicieron soberbiamente, y endurecieron su cerviz, y no escucharon tus mandamientos. </div>
<div id="Neh_9_17" style="display:none;" class="ver_select"><b>Neh 9:17</b>  No quisieron obedecer, ni se acordaron de tus maravillas que habías hecho con ellos; antes endurecieron su cerviz, y en su rebelión pensaron poner caudillo para volverse a su servidumbre. Pero tú que eres Dios perdonador, clemente y piadoso, tardo para la ira, y grande en misericordia, no los abandonaste. </div>
<div id="Neh_9_18" style="display:none;" class="ver_select"><b>Neh 9:18</b>  Además, cuando hicieron para sí becerro de fundición, y dijeron: Éste es tu Dios que te hizo subir de Egipto; y cometieron grandes abominaciones; </div>
<div id="Neh_9_19" style="display:none;" class="ver_select"><b>Neh 9:19</b>  Tú, con todo, por tus muchas misericordias no los abandonaste en el desierto. La columna de nube no se apartó de ellos de día, para guiarlos por el camino, ni la columna de fuego de noche, para alumbrarles el camino por el cual habían de ir. </div>
<div id="Neh_9_20" style="display:none;" class="ver_select"><b>Neh 9:20</b>  Y diste tu buen Espíritu para enseñarles, y no retiraste tu maná de su boca, y agua les diste en su sed. </div>
<div id="Neh_9_21" style="display:none;" class="ver_select"><b>Neh 9:21</b>  Y los sustentaste cuarenta años en el desierto; de ninguna cosa tuvieron necesidad; sus ropas no se envejecieron, ni se hincharon sus pies. </div>
<div id="Neh_9_22" style="display:none;" class="ver_select"><b>Neh 9:22</b>  Les diste reinos y pueblos, y los distribuiste por regiones: y poseyeron la tierra de Sehón, la tierra del rey de Hesbón, y la tierra de Og rey de Basán. </div>
<div id="Neh_9_23" style="display:none;" class="ver_select"><b>Neh 9:23</b>  Y multiplicaste sus hijos como las estrellas del cielo, y los metiste en la tierra, de la cual habías dicho a sus padres que habían de entrar a poseerla. </div>
<div id="Neh_9_24" style="display:none;" class="ver_select"><b>Neh 9:24</b>  Y los hijos vinieron y poseyeron la tierra, y humillaste delante de ellos a los moradores del país, a los cananeos, los cuales entregaste en su mano, y a sus reyes, y a los pueblos de la tierra, para que hiciesen de ellos a su voluntad. </div>
<div id="Neh_9_25" style="display:none;" class="ver_select"><b>Neh 9:25</b>  Y tomaron ciudades fortificadas y tierra fértil, y heredaron casas llenas de todo bien, cisternas hechas, viñas y olivares, y muchos árboles de comer; y comieron y se saciaron, se engordaron y se deleitaron en tu gran bondad. </div>
<div id="Neh_9_26" style="display:none;" class="ver_select"><b>Neh 9:26</b>  Pero fueron desobedientes y se rebelaron contra ti, y echaron tu ley tras sus espaldas, y mataron a tus profetas que protestaban contra ellos para convertirlos a ti; e hicieron grandes abominaciones. </div>
<div id="Neh_9_27" style="display:none;" class="ver_select"><b>Neh 9:27</b>  Y los entregaste en mano de sus enemigos, los cuales los afligieron. Pero en el tiempo de su tribulación clamaron a ti, y tú desde los cielos los oíste; y según tus muchas misericordias les diste libertadores para que los librasen de mano de sus enemigos. </div>
<div id="Neh_9_28" style="display:none;" class="ver_select"><b>Neh 9:28</b>  Pero una vez que tenían reposo, volvían a hacer lo malo delante de ti; por lo cual los abandonaste en mano de sus enemigos, que se enseñorearon de ellos; mas cuando se volvían y clamaban otra vez a ti, tú desde los cielos los oías, y muchas veces los libraste según tus misericordias. </div>
<div id="Neh_9_29" style="display:none;" class="ver_select"><b>Neh 9:29</b>  Y los amonestaste para que volviesen a tu ley; mas ellos fueron soberbios, y no oyeron tus mandamientos, sino que pecaron contra tus juicios, los cuales si el hombre hiciere, en ellos vivirá. Pero ellos dieron la espalda, y endurecieron su cerviz, y no escucharon. </div>
<div id="Neh_9_30" style="display:none;" class="ver_select"><b>Neh 9:30</b>  Los soportaste muchos años, y les amonestaste con tu Espíritu por medio de tus profetas, mas no escucharon; por lo cual los entregaste en mano de los pueblos de la tierra. </div>
<div id="Neh_9_31" style="display:none;" class="ver_select"><b>Neh 9:31</b>  Mas por tus muchas misericordias no los consumiste, ni los desamparaste; porque eres Dios clemente y misericordioso. </div>
<div id="Neh_9_32" style="display:none;" class="ver_select"><b>Neh 9:32</b>  Ahora, pues, Dios nuestro, Dios grande, fuerte, terrible, que guardas el pacto y la misericordia, no sea tenida en poco delante de ti toda la aflicción que nos ha alcanzando a nuestros reyes, a nuestros príncipes, a nuestros sacerdotes, y a nuestros profetas, y a nuestros padres, y a todo tu pueblo, desde los días de los reyes de Asiria hasta este día. </div>
<div id="Neh_9_33" style="display:none;" class="ver_select"><b>Neh 9:33</b>  Pero tú eres justo en todo lo que ha venido sobre nosotros; porque rectamente has hecho, mas nosotros hemos hecho lo malo: </div>
<div id="Neh_9_34" style="display:none;" class="ver_select"><b>Neh 9:34</b>  Y nuestros reyes, nuestros príncipes, nuestros sacerdotes, y nuestros padres, no pusieron por obra tu ley, ni atendieron a tus mandamientos y a tus testimonios, con que les amonestabas. </div>
<div id="Neh_9_35" style="display:none;" class="ver_select"><b>Neh 9:35</b>  Y ellos en su reino y en tu mucho bien que les diste, y en la tierra espaciosa y fértil que entregaste delante de ellos, no te sirvieron, ni se convirtieron de sus malas obras. </div>
<div id="Neh_9_36" style="display:none;" class="ver_select"><b>Neh 9:36</b>  He aquí que hoy somos siervos, henos aquí, siervos en la tierra que diste a nuestros padres para que comiesen su fruto y su bien. </div>
<div id="Neh_9_37" style="display:none;" class="ver_select"><b>Neh 9:37</b>  Y se multiplica su fruto para los reyes que has puesto sobre nosotros por nuestros pecados, quienes se enseñorean sobre nuestros cuerpos, y sobre nuestras bestias, conforme a su voluntad, y estamos en grande angustia. </div>
<div id="Neh_9_38" style="display:none;" class="ver_select"><b>Neh 9:38</b>  A causa, pues, de todo eso nosotros hacemos fiel pacto, y lo escribimos, signado de nuestros príncipes, de nuestros levitas, y de nuestros sacerdotes. </div>
<div id="Neh_10_1" style="display:none;" class="ver_select"><b>Neh 10:1</b>  Y los que firmaron fueron, Nehemías el Tirsata, hijo de Hacalías, y Sedequías, </div>
<div id="Neh_10_2" style="display:none;" class="ver_select"><b>Neh 10:2</b>  Seraías, Azarías, Jeremías, </div>
<div id="Neh_10_3" style="display:none;" class="ver_select"><b>Neh 10:3</b>  Pasur, Amarías, Malquías, </div>
<div id="Neh_10_4" style="display:none;" class="ver_select"><b>Neh 10:4</b>  Hatús, Sebanías, Maluc, </div>
<div id="Neh_10_5" style="display:none;" class="ver_select"><b>Neh 10:5</b>  Harim, Meremot, Abdías, </div>
<div id="Neh_10_6" style="display:none;" class="ver_select"><b>Neh 10:6</b>  Daniel, Ginetón, Baruc, </div>
<div id="Neh_10_7" style="display:none;" class="ver_select"><b>Neh 10:7</b>  Mesulam, Abías, Miamín, </div>
<div id="Neh_10_8" style="display:none;" class="ver_select"><b>Neh 10:8</b>  Maazías, Bilgai, Semaías; éstos eran sacerdotes. </div>
<div id="Neh_10_9" style="display:none;" class="ver_select"><b>Neh 10:9</b>  Y los levitas: Jesúa hijo de Azanías, Binúi de los hijos de Henadad, Cadmiel; </div>
<div id="Neh_10_10" style="display:none;" class="ver_select"><b>Neh 10:10</b>  y sus hermanos Sebanías, Odías, Kelita, Pelaías, Hanán; </div>
<div id="Neh_10_11" style="display:none;" class="ver_select"><b>Neh 10:11</b>  Micaías, Rehob, Hasabías, </div>
<div id="Neh_10_12" style="display:none;" class="ver_select"><b>Neh 10:12</b>  Zacur, Serebías, Sebanías, </div>
<div id="Neh_10_13" style="display:none;" class="ver_select"><b>Neh 10:13</b>  Odías, Bani, Beninu. </div>
<div id="Neh_10_14" style="display:none;" class="ver_select"><b>Neh 10:14</b>  Cabezas del pueblo: Paros, Pahat-moab, Elam, Zatu, Bani, </div>
<div id="Neh_10_15" style="display:none;" class="ver_select"><b>Neh 10:15</b>  Buni, Azgad, Bebai, </div>
<div id="Neh_10_16" style="display:none;" class="ver_select"><b>Neh 10:16</b>  Adonías, Bigvai, Adín, </div>
<div id="Neh_10_17" style="display:none;" class="ver_select"><b>Neh 10:17</b>  Ater, Ezequías, Azur, </div>
<div id="Neh_10_18" style="display:none;" class="ver_select"><b>Neh 10:18</b>  Odías, Hasum, Besai, </div>
<div id="Neh_10_19" style="display:none;" class="ver_select"><b>Neh 10:19</b>  Harif, Anatot, Nebai, </div>
<div id="Neh_10_20" style="display:none;" class="ver_select"><b>Neh 10:20</b>  Magpías, Mesulam, Hezir, </div>
<div id="Neh_10_21" style="display:none;" class="ver_select"><b>Neh 10:21</b>  Mesezabeel, Sadoc, Jadúa, </div>
<div id="Neh_10_22" style="display:none;" class="ver_select"><b>Neh 10:22</b>  Pelatías, Hanán, Anaías, </div>
<div id="Neh_10_23" style="display:none;" class="ver_select"><b>Neh 10:23</b>  Oseas, Hananías, Hasub, </div>
<div id="Neh_10_24" style="display:none;" class="ver_select"><b>Neh 10:24</b>  Lohes, Pilha, Sobec, </div>
<div id="Neh_10_25" style="display:none;" class="ver_select"><b>Neh 10:25</b>  Rehum, Hasabna, Maasías, </div>
<div id="Neh_10_26" style="display:none;" class="ver_select"><b>Neh 10:26</b>  y Ahías, Hanán, Anan, </div>
<div id="Neh_10_27" style="display:none;" class="ver_select"><b>Neh 10:27</b>  Maluc, Harim, Baana. </div>
<div id="Neh_10_28" style="display:none;" class="ver_select"><b>Neh 10:28</b>  Y el resto del pueblo, los sacerdotes, levitas, porteros, y cantores, sirvientes del templo y todos los que se habían apartado de los pueblos de las tierras a la ley de Dios, sus esposas, y sus hijos y sus hijas, todos los que podían comprender y discernir, </div>
<div id="Neh_10_29" style="display:none;" class="ver_select"><b>Neh 10:29</b>  se adhirieron a sus hermanos y sus principales, y entraron en protesta y juramento de que andarían en la ley de Dios, que fue dada por medio de Moisés siervo de Dios, y que guardarían y cumplirían todos los mandamientos de Jehová nuestro Señor, y sus juicios y sus estatutos. </div>
<div id="Neh_10_30" style="display:none;" class="ver_select"><b>Neh 10:30</b>  Y que no daríamos nuestras hijas a los pueblos de la tierra, ni tomaríamos sus hijas para nuestros hijos. </div>
<div id="Neh_10_31" style="display:none;" class="ver_select"><b>Neh 10:31</b>  Asimismo, que si los pueblos de la tierra trajesen a vender mercaderías y comestibles en día de sábado, nada tomaríamos de ellos en sábado, ni en día santo; y que el año séptimo dejaríamos reposar la tierra, y perdonaríamos toda deuda. </div>
<div id="Neh_10_32" style="display:none;" class="ver_select"><b>Neh 10:32</b>  Nos impusimos además por ley el cargo de contribuir cada año con la tercera parte de un siclo, para la obra de la casa de nuestro Dios; </div>
<div id="Neh_10_33" style="display:none;" class="ver_select"><b>Neh 10:33</b>  Para el pan de la proposición, y para la ofrenda continua, y para el holocausto continuo, de los sábados, y de las nuevas lunas, y de las festividades, y para las santificaciones y sacrificios por el pecado para expiar a Israel, y para toda la obra de la casa de nuestro Dios. </div>
<div id="Neh_10_34" style="display:none;" class="ver_select"><b>Neh 10:34</b>  Echamos también las suertes, los sacerdotes, los levitas, y el pueblo, acerca de la ofrenda de la leña, para traerla a la casa de nuestro Dios, según las casas de nuestros padres, en los tiempos determinados cada un año, para quemar sobre el altar de Jehová nuestro Dios, como está escrito en la ley. </div>
<div id="Neh_10_35" style="display:none;" class="ver_select"><b>Neh 10:35</b>  Y que cada año traeríamos las primicias de nuestra tierra, y las primicias de todo fruto de todo árbol, a la casa de Jehová. </div>
<div id="Neh_10_36" style="display:none;" class="ver_select"><b>Neh 10:36</b>  Asimismo los primogénitos de nuestros hijos y de nuestras bestias, como está escrito en la ley; y que traeríamos los primogénitos de nuestras vacas y de nuestras ovejas a la casa de nuestro Dios, a los sacerdotes que ministran en la casa de nuestro Dios: </div>
<div id="Neh_10_37" style="display:none;" class="ver_select"><b>Neh 10:37</b>  Que traeríamos también las primicias de nuestras masas, y nuestras ofrendas, y del fruto de todo árbol, del vino y del aceite, a los sacerdotes, a las cámaras de la casa de nuestro Dios, y el diezmo de nuestra tierra a los levitas; y que los levitas recibirían los diezmos de nuestras labores en todas las ciudades: </div>
<div id="Neh_10_38" style="display:none;" class="ver_select"><b>Neh 10:38</b>  Y que estaría el sacerdote hijo de Aarón con los levitas, cuando los levitas recibirían el diezmo: y que los levitas llevarían el diezmo del diezmo a la casa de nuestro Dios, a las cámaras en la casa del tesoro. </div>
<div id="Neh_10_39" style="display:none;" class="ver_select"><b>Neh 10:39</b>  Porque a las cámaras han de llevar los hijos de Israel y los hijos de Leví la ofrenda del grano, del vino, y del aceite; y allí estarán los vasos del santuario, y los sacerdotes que ministran, y los porteros, y los cantores; y no abandonaremos la casa de nuestro Dios.</div>
<div id="Neh_11_1" style="display:none;" class="ver_select"><b>Neh 11:1</b>  Y los príncipes del pueblo habitaron en Jerusalén; mas el resto del pueblo echó suertes para traer uno de diez que morase en Jerusalén, ciudad santa, y las nueve partes en las otras ciudades. </div>
<div id="Neh_11_2" style="display:none;" class="ver_select"><b>Neh 11:2</b>  Y bendijo el pueblo a todos los varones que voluntariamente se ofrecieron a morar en Jerusalén. </div>
<div id="Neh_11_3" style="display:none;" class="ver_select"><b>Neh 11:3</b>  Y éstos son los principales de la provincia que moraron en Jerusalén; mas en las ciudades de Judá habitaron cada uno en su posesión en sus ciudades, de Israel, de los sacerdotes, y levitas, y sirvientes del templo, y de los hijos de los siervos de Salomón. </div>
<div id="Neh_11_4" style="display:none;" class="ver_select"><b>Neh 11:4</b>  En Jerusalén pues habitaron de los hijos de Judá, y de los hijos de Benjamín. De los hijos de Judá: Ataías, hijo de Uzías, hijo de Zacarías, hijo de Amarías, hijo de Sefatías, hijo de Mahalaleel, de los hijos de Fares; </div>
<div id="Neh_11_5" style="display:none;" class="ver_select"><b>Neh 11:5</b>  y Maasías hijo de Baruc, hijo de Col-hoze, hijo de Hazaías, hijo de Adaías, hijo de Joiarib, hijo de Zacarías, hijo de Siloni. </div>
<div id="Neh_11_6" style="display:none;" class="ver_select"><b>Neh 11:6</b>  Todos los hijos de Fares que moraron en Jerusalén, fueron cuatrocientos sesenta y ocho hombres fuertes. </div>
<div id="Neh_11_7" style="display:none;" class="ver_select"><b>Neh 11:7</b>  Y éstos son los hijos de Benjamín: Salú hijo de Mesulam, hijo de Joed, hijo de Pedaías, hijo de Colaías, hijo de Maasías, hijo de Itiel, hijo de Jesahías. </div>
<div id="Neh_11_8" style="display:none;" class="ver_select"><b>Neh 11:8</b>  Y tras él, Gabai, Salai, novecientos veintiocho. </div>
<div id="Neh_11_9" style="display:none;" class="ver_select"><b>Neh 11:9</b>  Y Joel hijo de Zicri, era prefecto de ellos, y Judá hijo de Senúa, el segundo de la ciudad. </div>
<div id="Neh_11_10" style="display:none;" class="ver_select"><b>Neh 11:10</b>  De los sacerdotes: Jedaías hijo de Joiarib, Jaquín, </div>
<div id="Neh_11_11" style="display:none;" class="ver_select"><b>Neh 11:11</b>  Seraías hijo de Hilcías, hijo de Mesulam, hijo de Sadoc, hijo de Meraiot, hijo de Ahitob, príncipe de la casa de Dios, </div>
<div id="Neh_11_12" style="display:none;" class="ver_select"><b>Neh 11:12</b>  y sus hermanos los que hacían la obra de la casa, ochocientos veintidós; y Adaías hijo de Jeroham, hijo de Pelalías, hijo de Amsi, hijo de Zacarías, hijo de Pasur, hijo de Malquías, </div>
<div id="Neh_11_13" style="display:none;" class="ver_select"><b>Neh 11:13</b>  y sus hermanos, príncipes de familias, doscientos cuarenta y dos; y Amasai hijo de Azareel, hijo de Azai, hijo de Mesilemot, hijo de Imer, </div>
<div id="Neh_11_14" style="display:none;" class="ver_select"><b>Neh 11:14</b>  y sus hermanos, hombres de grande vigor, ciento veintiocho; jefe de los cuales era Zabdiel, hijo de un hombre grande. </div>
<div id="Neh_11_15" style="display:none;" class="ver_select"><b>Neh 11:15</b>  Y de los levitas: Semaías hijo de Hasub, hijo de Azricam, hijo de Hasabías, hijo de Buni; </div>
<div id="Neh_11_16" style="display:none;" class="ver_select"><b>Neh 11:16</b>  Y Sabetai y Jozabad, de los principales de los levitas, encargados de la obra exterior de la casa de Dios; </div>
<div id="Neh_11_17" style="display:none;" class="ver_select"><b>Neh 11:17</b>  y Matanías hijo de Micaías, hijo de Zabdi, hijo de Asaf, el principal, el que empezaba las alabanzas y acción de gracias al tiempo de la oración; y Bacbucías el segundo de entre sus hermanos; y Abda hijo de Samúa, hijo de Galal, hijo de Jedutún. </div>
<div id="Neh_11_18" style="display:none;" class="ver_select"><b>Neh 11:18</b>  Todos los levitas en la santa ciudad fueron doscientos ochenta y cuatro. </div>
<div id="Neh_11_19" style="display:none;" class="ver_select"><b>Neh 11:19</b>  Y los porteros, Acub, Talmón, y sus hermanos, guardas en las puertas, ciento setenta y dos. </div>
<div id="Neh_11_20" style="display:none;" class="ver_select"><b>Neh 11:20</b>  Y el resto de Israel, de los sacerdotes, de los levitas, en todas las ciudades de Judá, cada uno en su heredad. </div>
<div id="Neh_11_21" style="display:none;" class="ver_select"><b>Neh 11:21</b>  Y los sirvientes del templo habitaban en Ofel; y los sirvientes del templo estaban bajo el mando de Siha y Gispa. </div>
<div id="Neh_11_22" style="display:none;" class="ver_select"><b>Neh 11:22</b>  Y el prepósito de los levitas en Jerusalén era Uzi hijo de Bani, hijo de Hasabías, hijo de Matanías, hijo de Micaías de los cantores los hijos de Asaf, sobre la obra de la casa de Dios. </div>
<div id="Neh_11_23" style="display:none;" class="ver_select"><b>Neh 11:23</b>  Porque había mandamiento del rey acerca de ellos, y determinación acerca de los cantores para cada día. </div>
<div id="Neh_11_24" style="display:none;" class="ver_select"><b>Neh 11:24</b>  Y Petaías hijo de Mesezabeel, de los hijos de Zera hijo de Judá, estaba a la mano del rey en todos los asuntos del pueblo. </div>
<div id="Neh_11_25" style="display:none;" class="ver_select"><b>Neh 11:25</b>  Y tocante a las aldeas y sus tierras, algunos de los hijos de Judá habitaron en Quiriat-arba y sus aldeas, y en Dibón y sus aldeas, y en Jecabseel y sus aldeas; </div>
<div id="Neh_11_26" style="display:none;" class="ver_select"><b>Neh 11:26</b>  Y en Jesúa, Molada, y en Bet-pelet; </div>
<div id="Neh_11_27" style="display:none;" class="ver_select"><b>Neh 11:27</b>  y en Hasar-sual, y en Beerseba, y en sus aldeas; </div>
<div id="Neh_11_28" style="display:none;" class="ver_select"><b>Neh 11:28</b>  y en Siclag, y en Mecona y sus aldeas; </div>
<div id="Neh_11_29" style="display:none;" class="ver_select"><b>Neh 11:29</b>  y en Enrimón, y en Zora y en Jarmut; </div>
<div id="Neh_11_30" style="display:none;" class="ver_select"><b>Neh 11:30</b>  en Zanoa, en Adulam y sus aldeas; en Laquis y sus tierras, y en Azeca y sus aldeas. Y habitaron desde Beerseba hasta el valle de Hinom. </div>
<div id="Neh_11_31" style="display:none;" class="ver_select"><b>Neh 11:31</b>  Y los hijos de Benjamín desde Geba habitaron en Micmas, y Hai, y en Betel y sus aldeas; </div>
<div id="Neh_11_32" style="display:none;" class="ver_select"><b>Neh 11:32</b>  En Anatot, Nob, Ananías; </div>
<div id="Neh_11_33" style="display:none;" class="ver_select"><b>Neh 11:33</b>  Hazor, Ramá, Gitaim; </div>
<div id="Neh_11_34" style="display:none;" class="ver_select"><b>Neh 11:34</b>  Hadid, Zeboim, Nebalat; </div>
<div id="Neh_11_35" style="display:none;" class="ver_select"><b>Neh 11:35</b>  Lod, y Ono, valle de los artífices. </div>
<div id="Neh_11_36" style="display:none;" class="ver_select"><b>Neh 11:36</b>  Y algunos de los levitas, en los repartimientos de Judá y de Benjamín. </div>
<div id="Neh_12_1" style="display:none;" class="ver_select"><b>Neh 12:1</b>  Y éstos son los sacerdotes y levitas que subieron con Zorobabel hijo de Salatiel, y con Jesúa: Seraías, Jeremías, Esdras, </div>
<div id="Neh_12_2" style="display:none;" class="ver_select"><b>Neh 12:2</b>  Amarías, Maluc, Hatús, </div>
<div id="Neh_12_3" style="display:none;" class="ver_select"><b>Neh 12:3</b>  Secanías, Rehum, Meremot, </div>
<div id="Neh_12_4" style="display:none;" class="ver_select"><b>Neh 12:4</b>  Iddo, Gineto, Abías, </div>
<div id="Neh_12_5" style="display:none;" class="ver_select"><b>Neh 12:5</b>  Miamín, Maadías, Bilga, </div>
<div id="Neh_12_6" style="display:none;" class="ver_select"><b>Neh 12:6</b>  Semaías, y Joiarib, Jedaías, </div>
<div id="Neh_12_7" style="display:none;" class="ver_select"><b>Neh 12:7</b>  Salum, Amoc, Hilcías, Jedaías. Éstos eran los príncipes de los sacerdotes y sus hermanos en los días de Jesúa. </div>
<div id="Neh_12_8" style="display:none;" class="ver_select"><b>Neh 12:8</b>  Y los levitas: Jesúa, Binúi, Cadmiel, Serebías, Judá, y Matanías, que con sus hermanos oficiaba en los himnos. </div>
<div id="Neh_12_9" style="display:none;" class="ver_select"><b>Neh 12:9</b>  Y Bacbucías y Uni, sus hermanos, cada cual en su ministerio. </div>
<div id="Neh_12_10" style="display:none;" class="ver_select"><b>Neh 12:10</b>  Y Jesúa engendró a Joiacim, y Joiacim engendró a Eliasib y Eliasib engendró a Joiada, </div>
<div id="Neh_12_11" style="display:none;" class="ver_select"><b>Neh 12:11</b>  y Joiada engendró a Jonatán, y Jonatán engendró a Jadúa. </div>
<div id="Neh_12_12" style="display:none;" class="ver_select"><b>Neh 12:12</b>  Y en los días de Joiacim los sacerdotes cabezas de familias fueron: de Seraías, Meraías; de Jeremías, Hananías; </div>
<div id="Neh_12_13" style="display:none;" class="ver_select"><b>Neh 12:13</b>  de Esdras, Mesulam; de Amarías, Johanán; </div>
<div id="Neh_12_14" style="display:none;" class="ver_select"><b>Neh 12:14</b>  de Maluc, Jonatán; de Sebanías, José; </div>
<div id="Neh_12_15" style="display:none;" class="ver_select"><b>Neh 12:15</b>  de Harim, Adna; de Meraiot, Helcai; </div>
<div id="Neh_12_16" style="display:none;" class="ver_select"><b>Neh 12:16</b>  de Iddo, Zacarías; de Ginetón, Mesulam; </div>
<div id="Neh_12_17" style="display:none;" class="ver_select"><b>Neh 12:17</b>  de Abías, Zicri; de Miniamín, de Moadías, Piltai; </div>
<div id="Neh_12_18" style="display:none;" class="ver_select"><b>Neh 12:18</b>  de Bilga, Samúa; de Semaías, Jonatán; </div>
<div id="Neh_12_19" style="display:none;" class="ver_select"><b>Neh 12:19</b>  de Joiarib, Matenai; de Jedaías, Uzi; </div>
<div id="Neh_12_20" style="display:none;" class="ver_select"><b>Neh 12:20</b>  de Salai, Calai; de Amoc, Heber; </div>
<div id="Neh_12_21" style="display:none;" class="ver_select"><b>Neh 12:21</b>  de Hilcías, Hasabías; de Jedaías, Natanael. </div>
<div id="Neh_12_22" style="display:none;" class="ver_select"><b>Neh 12:22</b>  Los levitas en días de Eliasib, de Joiada, y de Johanán y Jadúa, fueron escritos por cabezas de familias; también los sacerdotes, hasta el reinado de Darío el persa. </div>
<div id="Neh_12_23" style="display:none;" class="ver_select"><b>Neh 12:23</b>  Los hijos de Leví, cabezas de familias, fueron escritos en el libro de las Crónicas hasta los días de Johanán, hijo de Eliasib. </div>
<div id="Neh_12_24" style="display:none;" class="ver_select"><b>Neh 12:24</b>  Y los principales de los levitas: Hasabías, Serebías, y Jesúa hijo de Cadmiel, y sus hermanos delante de ellos, para alabar y dar gracias, conforme al estatuto de David varón de Dios, guardando su turno. </div>
<div id="Neh_12_25" style="display:none;" class="ver_select"><b>Neh 12:25</b>  Matanías, y Bacbucías, Abdías, Mesulam, Talmón, Acub, guardas, eran porteros para la guardia a las entradas de las puertas. </div>
<div id="Neh_12_26" style="display:none;" class="ver_select"><b>Neh 12:26</b>  Éstos fueron en los días de Joiacim, hijo de Jesúa, hijo de Josadac, y en los días del gobernador Nehemías, y del sacerdote Esdras, escriba. </div>
<div id="Neh_12_27" style="display:none;" class="ver_select"><b>Neh 12:27</b>  Y para la dedicación del muro de Jerusalén buscaron a los levitas de todos los lugares, para traerlos a Jerusalén, para hacer la dedicación y la fiesta con alabanzas y con cánticos, con címbalos, salterios y cítaras. </div>
<div id="Neh_12_28" style="display:none;" class="ver_select"><b>Neh 12:28</b>  Y fueron reunidos los hijos de los cantores, así de la región de alrededor de Jerusalén como de las aldeas de Netofati; </div>
<div id="Neh_12_29" style="display:none;" class="ver_select"><b>Neh 12:29</b>  y de la casa de Gilgal, y de los campos de Geba, y de Azmavet; porque los cantores se habían edificado aldeas alrededor de Jerusalén. </div>
<div id="Neh_12_30" style="display:none;" class="ver_select"><b>Neh 12:30</b>  Y se purificaron los sacerdotes y los levitas; y purificaron al pueblo, y las puertas, y el muro. </div>
<div id="Neh_12_31" style="display:none;" class="ver_select"><b>Neh 12:31</b>  Hice luego subir a los príncipes de Judá sobre el muro, y puse dos coros grandes que daban gracias; el uno a la mano derecha sobre el muro hacia la puerta del Muladar. </div>
<div id="Neh_12_32" style="display:none;" class="ver_select"><b>Neh 12:32</b>  E iba tras de ellos Osaías, y la mitad de los príncipes de Judá, </div>
<div id="Neh_12_33" style="display:none;" class="ver_select"><b>Neh 12:33</b>  y Azarías, Esdras y Mesulam, </div>
<div id="Neh_12_34" style="display:none;" class="ver_select"><b>Neh 12:34</b>  Judá y Benjamín, y Semaías, y Jeremías. </div>
<div id="Neh_12_35" style="display:none;" class="ver_select"><b>Neh 12:35</b>  Y de los hijos de los sacerdotes iban con trompetas, Zacarías hijo de Jonatán, hijo de Semaías, hijo de Matanías, hijo de Micaías, hijo de Zacur, hijo de Asaf; </div>
<div id="Neh_12_36" style="display:none;" class="ver_select"><b>Neh 12:36</b>  y sus hermanos Semaías, y Azareel, Milalai, Gilalai, Maai, Natanael, Judá y Hanani, con los instrumentos musicales de David varón de Dios; y Esdras escriba, delante de ellos. </div>
<div id="Neh_12_37" style="display:none;" class="ver_select"><b>Neh 12:37</b>  Y a la puerta de la Fuente, en derecho delante de ellos, subieron por las gradas de la ciudad de David, por la subida del muro, desde la casa de David hasta la puerta de las Aguas al oriente. </div>
<div id="Neh_12_38" style="display:none;" class="ver_select"><b>Neh 12:38</b>  Y el segundo coro iba del lado opuesto, y yo en pos de él, con la mitad del pueblo sobre el muro, desde la torre de los Hornos hasta el muro ancho; </div>
<div id="Neh_12_39" style="display:none;" class="ver_select"><b>Neh 12:39</b>  y desde la puerta de Efraín hasta la puerta Antigua, y a la puerta del Pescado, y la torre de Hananeel, y la torre de Meah, hasta la puerta de las Ovejas; y pararon en la puerta de la Cárcel. </div>
<div id="Neh_12_40" style="display:none;" class="ver_select"><b>Neh 12:40</b>  Pararon luego los dos coros en la casa de Dios; y yo, y la mitad de los magistrados conmigo; </div>
<div id="Neh_12_41" style="display:none;" class="ver_select"><b>Neh 12:41</b>  y los sacerdotes, Eliaquim, Maasías, Miniamín, Micaías, Elioenai, Zacarías, y Hananías, con trompetas; </div>
<div id="Neh_12_42" style="display:none;" class="ver_select"><b>Neh 12:42</b>  y Maasías, y Semaías, y Eleazar, y Uzi, y Johanán, y Malquías, y Elam, y Ezer. Y los cantores cantaban alto, e Izrahías era el prefecto. </div>
<div id="Neh_12_43" style="display:none;" class="ver_select"><b>Neh 12:43</b>  Y sacrificaron aquel día grandes víctimas, e hicieron alegrías; porque Dios los había recreado con grande contentamiento; se alegraron también las mujeres y los niños; y el alborozo de Jerusalén fue oído desde lejos. </div>
<div id="Neh_12_44" style="display:none;" class="ver_select"><b>Neh 12:44</b>  Y en aquel día fueron puestos varones sobres las cámaras de los tesoros, de las ofrendas, de las primicias, y de los diezmos, para juntar en ellas de los campos de las ciudades las porciones legales para los sacerdotes y levitas; porque era grande el gozo de Judá con respecto a los sacerdotes y levitas que servían. </div>
<div id="Neh_12_45" style="display:none;" class="ver_select"><b>Neh 12:45</b>  Y los cantores y los porteros guardaron la ordenanza de su Dios y la ordenanza de la expiación conforme al estatuto de David y de Salomón su hijo. </div>
<div id="Neh_12_46" style="display:none;" class="ver_select"><b>Neh 12:46</b>  Porque desde el tiempo de David y de Asaf, ya de antiguo, había príncipes de cantores, y cántico y alabanza, y acción de gracias a Dios. </div>
<div id="Neh_12_47" style="display:none;" class="ver_select"><b>Neh 12:47</b>  Y todo Israel en días de Zorobabel, y en días de Nehemías, daba raciones a los cantores y a los porteros, cada cosa en su día: consagraban asimismo sus porciones a los levitas, y los levitas consagraban parte a los hijos de Aarón. </div>
<div id="Neh_13_1" style="display:none;" class="ver_select"><b>Neh 13:1</b>  Aquel día se leyó en el libro de Moisés oyéndolo el pueblo, y fue hallado escrito en él que los amonitas y moabitas no debían entrar jamás en la congregación de Dios; </div>
<div id="Neh_13_2" style="display:none;" class="ver_select"><b>Neh 13:2</b>  por cuanto no salieron a recibir a los hijos de Israel con pan y agua, antes alquilaron a Balaam contra ellos, para que los maldijese; mas nuestro Dios volvió la maldición en bendición. </div>
<div id="Neh_13_3" style="display:none;" class="ver_select"><b>Neh 13:3</b>  Y aconteció que cuando oyeron la ley, apartaron de Israel a todos los mezclados con extranjeros. </div>
<div id="Neh_13_4" style="display:none;" class="ver_select"><b>Neh 13:4</b>  Y antes de esto, Eliasib sacerdote, siendo superintendente de la cámara de la casa de nuestro Dios, había emparentado con Tobías, </div>
<div id="Neh_13_5" style="display:none;" class="ver_select"><b>Neh 13:5</b>  y le había hecho una grande cámara, en la cual guardaban antes las ofrendas, y el perfume, y los vasos, y el diezmo del grano, y del vino y del aceite, que estaba mandado darse a los levitas, a los cantores, y a los porteros, y la ofrenda de los sacerdotes. </div>
<div id="Neh_13_6" style="display:none;" class="ver_select"><b>Neh 13:6</b>  Mas a todo esto, yo no estaba en Jerusalén; porque el año treinta y dos de Artajerjes rey de Babilonia, vine al rey; y al cabo de días obtuve permiso del rey. </div>
<div id="Neh_13_7" style="display:none;" class="ver_select"><b>Neh 13:7</b>  Y vine a Jerusalén, entendí el mal que había hecho Eliasib en atención a Tobías, haciendo para él cámara en los patios de la casa de Dios. </div>
<div id="Neh_13_8" style="display:none;" class="ver_select"><b>Neh 13:8</b>  Y me dolió en gran manera; y eché todos los enseres de la casa de Tobías fuera de la cámara; </div>
<div id="Neh_13_9" style="display:none;" class="ver_select"><b>Neh 13:9</b>  y dije que limpiasen las cámaras, e hice volver allí los utensilios de la casa de Dios, las ofrendas y el perfume. </div>
<div id="Neh_13_10" style="display:none;" class="ver_select"><b>Neh 13:10</b>  Entendí asimismo que las porciones de los levitas no les habían sido dadas; y que los levitas y cantores que hacían el servicio se habían huido cada uno a su heredad. </div>
<div id="Neh_13_11" style="display:none;" class="ver_select"><b>Neh 13:11</b>  Y reprendí a los magistrados, y dije: ¿Por qué está la casa de Dios abandonada? Y los junté, y los puse en su lugar. </div>
<div id="Neh_13_12" style="display:none;" class="ver_select"><b>Neh 13:12</b>  Y todo Judá trajo el diezmo del grano, del vino y del aceite, a los almacenes. </div>
<div id="Neh_13_13" style="display:none;" class="ver_select"><b>Neh 13:13</b>  Y puse por sobrestantes de ellos a Selemías sacerdote, y a Sadoc escriba, y de los levitas, a Pedaías y a mano de ellos Hanán hijo de Zacur, hijo de Matanías; pues ellos eran tenidos por fieles, y de ellos eran el repartir a sus hermanos. </div>
<div id="Neh_13_14" style="display:none;" class="ver_select"><b>Neh 13:14</b>  Acuérdate de mí, oh Dios, en orden a esto, y no borres mis misericordias que hice en la casa de mi Dios, y en el servicio en ella. </div>
<div id="Neh_13_15" style="display:none;" class="ver_select"><b>Neh 13:15</b>  En aquellos días vi en Judá algunos que pisaban los lagares en sábado, y que acarreaban gavillas, y cargaban asnos con vino, y también de uvas, de higos, y toda clase de carga, y traían a Jerusalén en día de sábado; y les amonesté acerca del día que vendían el mantenimiento. </div>
<div id="Neh_13_16" style="display:none;" class="ver_select"><b>Neh 13:16</b>  También estaban en ella tirios que traían pescado y toda mercadería, y vendían en sábado a los hijos de Judá en Jerusalén. </div>
<div id="Neh_13_17" style="display:none;" class="ver_select"><b>Neh 13:17</b>  Y reprendí a los señores de Judá, y les dije: ¿Qué mala cosa es ésta que vosotros hacéis, profanando así el día del sábado? </div>
<div id="Neh_13_18" style="display:none;" class="ver_select"><b>Neh 13:18</b>  ¿No hicieron así vuestros padres, y trajo nuestro Dios sobre nosotros todo este mal, y sobre esta ciudad? ¿Y vosotros añadís ira sobre Israel profanando el sábado? </div>
<div id="Neh_13_19" style="display:none;" class="ver_select"><b>Neh 13:19</b>  Sucedió, pues, que cuando iba oscureciendo a las puertas de Jerusalén antes del sábado, dije que se cerrasen las puertas, y ordené que no las abriesen hasta después del sábado; y puse a las puertas algunos de mis criados, para que en día de sábado no introdujesen carga. </div>
<div id="Neh_13_20" style="display:none;" class="ver_select"><b>Neh 13:20</b>  Y se quedaron fuera de Jerusalén una y dos veces los negociantes, y los que vendían toda especie de mercancía. </div>
<div id="Neh_13_21" style="display:none;" class="ver_select"><b>Neh 13:21</b>  Y les amonesté y les dije: ¿Por qué os quedáis vosotros delante del muro? Si lo hacéis otra vez, os echaré mano. Desde entonces no vinieron en sábado. </div>
<div id="Neh_13_22" style="display:none;" class="ver_select"><b>Neh 13:22</b>  Y dije a los levitas que se purificasen, y viniesen a guardar las puertas, para santificar el día del sábado. También por esto acuérdate de mí, Dios mío, y perdóname según la muchedumbre de tu misericordia. </div>
<div id="Neh_13_23" style="display:none;" class="ver_select"><b>Neh 13:23</b>  Vi asimismo en aquellos días a judíos que habían tomado esposas de Asdod, amonitas, y moabitas. </div>
<div id="Neh_13_24" style="display:none;" class="ver_select"><b>Neh 13:24</b>  Y de sus hijos, la mitad hablaban la lengua de Asdod, y no podían hablar la lengua de los judíos, sino que hablaban conforme a la lengua de cada pueblo. </div>
<div id="Neh_13_25" style="display:none;" class="ver_select"><b>Neh 13:25</b>  Y reñí con ellos y los maldije, y herí algunos de ellos y les arranqué los cabellos, y les hice jurar por Dios, diciendo: No daréis vuestras hijas a sus hijos, ni tomaréis de sus hijas para vuestros hijos, ni para vosotros mismos. </div>
<div id="Neh_13_26" style="display:none;" class="ver_select"><b>Neh 13:26</b>  ¿No pecó por esto Salomón, rey de Israel? Bien que en muchas naciones no hubo rey como él, que era amado de su Dios y Dios lo había puesto por rey sobre todo Israel; y aun a él le hicieron pecar las esposas extranjeras. </div>
<div id="Neh_13_27" style="display:none;" class="ver_select"><b>Neh 13:27</b>  ¿Y obedeceremos a vosotros para cometer todo este mal tan grande de prevaricar contra nuestro Dios, tomando esposas extranjeras? </div>
<div id="Neh_13_28" style="display:none;" class="ver_select"><b>Neh 13:28</b>  Y uno de los hijos de Joiada, hijo de Eliasib el sumo sacerdote era yerno de Sanbalat horonita; por tanto lo ahuyenté de mí. </div>
<div id="Neh_13_29" style="display:none;" class="ver_select"><b>Neh 13:29</b>  Acuérdate de ellos, Dios mío, contra los que contaminan el sacerdocio, y el pacto del sacerdocio y de los levitas. </div>
<div id="Neh_13_30" style="display:none;" class="ver_select"><b>Neh 13:30</b>  Los limpié, pues, de todo extranjero, y puse a los sacerdotes y levitas por sus clases, a cada uno en su obra; </div>
<div id="Neh_13_31" style="display:none;" class="ver_select"><b>Neh 13:31</b>  Y para la ofrenda de la leña en los tiempos señalados, y para las primicias. Acuérdate de mí, Dios mío, para bien. </div>
