<div id="Oba_1_1" style="display:none;" class="ver_select"><b>Oba 1:1</b>  Visión de Abdías. Así dice Jehová el Señor en cuanto a Edom: Hemos oído el pregón de Jehová, y mensajero es enviado a las gentes. Levantaos, y levantémonos contra ella en batalla. </div>
<div id="Oba_1_2" style="display:none;" class="ver_select"><b>Oba 1:2</b>  He aquí, te he hecho pequeño entre las naciones; abatido eres tú en gran manera. </div>
<div id="Oba_1_3" style="display:none;" class="ver_select"><b>Oba 1:3</b>  La soberbia de tu corazón te ha engañado, tú que moras en las hendiduras de las peñas, en tu altísima morada; que dices en tu corazón: ¿Quién me derribará a tierra? </div>
<div id="Oba_1_4" style="display:none;" class="ver_select"><b>Oba 1:4</b>  Aunque te remontares como el águila, aunque entre las estrellas pusieres tu nido, de ahí te derribaré, dice Jehová. </div>
<div id="Oba_1_5" style="display:none;" class="ver_select"><b>Oba 1:5</b>  Si ladrones vinieran a ti, o robadores de noche (¡cómo has sido destruido!), ¿no hurtarán lo que les bastase? Si entraran a ti vendimiadores, ¿no dejarían algún rebusco? </div>
<div id="Oba_1_6" style="display:none;" class="ver_select"><b>Oba 1:6</b>  ¡Cómo fueron escudriñadas las cosas de Esaú! sus tesoros escondidos fueron buscados. </div>
<div id="Oba_1_7" style="display:none;" class="ver_select"><b>Oba 1:7</b>  Hasta el término te hicieron llegar todos tus aliados; aquellos que estaban en paz contigo te han engañado, y prevalecieron contra ti; los que comían tu pan, pusieron el lazo debajo de ti; no hay en él entendimiento. </div>
<div id="Oba_1_8" style="display:none;" class="ver_select"><b>Oba 1:8</b>  ¿No haré que perezcan en aquel día, dice Jehová, los sabios de Edom, y la prudencia del monte de Esaú? </div>
<div id="Oba_1_9" style="display:none;" class="ver_select"><b>Oba 1:9</b>  Y tus valientes, oh Temán, serán quebrantados; porque todo hombre será talado del monte de Esaú por el estrago. </div>
<div id="Oba_1_10" style="display:none;" class="ver_select"><b>Oba 1:10</b>  Por la injuria contra tu hermano Jacob te cubrirá vergüenza, y serás talado para siempre. </div>
<div id="Oba_1_11" style="display:none;" class="ver_select"><b>Oba 1:11</b>  El día que estando tú delante, el día que extraños llevaban cautivo su ejército, y los extranjeros entraban por sus puertas, y echaban suertes sobre Jerusalén, tú también eras como uno de ellos. </div>
<div id="Oba_1_12" style="display:none;" class="ver_select"><b>Oba 1:12</b>  Pues no debiste tú estar mirando en el día de tu hermano, el día en que fue traspasado; no debiste haberte alegrado de los hijos de Judá en el día de su ruina, ni debiste haber ensanchado tu boca en el día de la angustia: </div>
<div id="Oba_1_13" style="display:none;" class="ver_select"><b>Oba 1:13</b>  No habías de haber entrado por la puerta de mi pueblo en el día de su quebrantamiento; no, no habías tú de haber mirado su mal el día de su quebranto, ni haber echado mano a sus bienes el día de su calamidad. </div>
<div id="Oba_1_14" style="display:none;" class="ver_select"><b>Oba 1:14</b>  Tampoco habías de haberte parado en las encrucijadas, para matar a los que de ellos escapasen; ni habías tú de haber entregado a los que quedaban en el día de angustia. </div>
<div id="Oba_1_15" style="display:none;" class="ver_select"><b>Oba 1:15</b>  Porque cercano está el día de Jehová sobre todas las naciones; como tú hiciste se hará contigo; tu galardón volverá sobre tu cabeza. </div>
<div id="Oba_1_16" style="display:none;" class="ver_select"><b>Oba 1:16</b>  De la manera que vosotros bebisteis en mi santo monte, así beberán continuamente todas las gentes; beberán, y engullirán, y serán como si no hubieran sido. </div>
<div id="Oba_1_17" style="display:none;" class="ver_select"><b>Oba 1:17</b>  Mas en el monte de Sión habrá liberación, y habrá santidad, y la casa de Jacob, poseerá sus posesiones. </div>
<div id="Oba_1_18" style="display:none;" class="ver_select"><b>Oba 1:18</b>  Y la casa de Jacob será fuego, y la casa de José será llama, y la casa de Esaú estopa, y los quemarán, y los consumirán; y ni aun uno quedará de la casa de Esaú, porque Jehová lo habló. </div>
<div id="Oba_1_19" style="display:none;" class="ver_select"><b>Oba 1:19</b>  Y los del Neguev poseerán el monte de Esaú, y la llanura de los filisteos; poseerán también los campos de Efraín, y los campos de Samaria; y Benjamín a Galaad. </div>
<div id="Oba_1_20" style="display:none;" class="ver_select"><b>Oba 1:20</b>  Y los cautivos de este ejército de los hijos de Israel poseerán lo de los cananeos hasta Sarepta; y los cautivos de Jerusalén, que están en Sefarad, poseerán las ciudades del sur. </div>
<div id="Oba_1_21" style="display:none;" class="ver_select"><b>Oba 1:21</b>  Y vendrán salvadores al monte de Sión para juzgar al monte de Esaú; y el reino será de Jehová. </div>
