<div id="Rev_1_1" style="display:none;" class="ver_select"><b>Rev 1:1</b>  La revelación de Jesucristo, que Dios le dio, para manifestar a sus siervos las cosas que deben acontecer pronto; y la declaró, enviándola por su ángel a Juan su siervo, </div>
<div id="Rev_1_2" style="display:none;" class="ver_select"><b>Rev 1:2</b>  el cual ha dado testimonio de la palabra de Dios, y del testimonio de Jesucristo, y de todas las cosas que él vio. </div>
<div id="Rev_1_3" style="display:none;" class="ver_select"><b>Rev 1:3</b>  Bienaventurado el que lee, y los que oyen las palabras de esta profecía, y guardan las cosas en ella escritas; porque el tiempo está cerca. </div>
<div id="Rev_1_4" style="display:none;" class="ver_select"><b>Rev 1:4</b>  Juan, a las siete iglesias que están en Asia: Gracia sea a vosotros, y paz del que es y que era y que ha de venir, y de los siete Espíritus que están delante de su trono; </div>
<div id="Rev_1_5" style="display:none;" class="ver_select"><b>Rev 1:5</b>  y de Jesucristo, el testigo fiel, el primogénito de los muertos, y príncipe de los reyes de la tierra. Al que nos amó, y nos lavó de nuestros pecados con su propia sangre, </div>
<div id="Rev_1_6" style="display:none;" class="ver_select"><b>Rev 1:6</b>  y nos hizo reyes y sacerdotes para Dios y su Padre; a Él sea la gloria y el poder por siempre jamás. Amén. </div>
<div id="Rev_1_7" style="display:none;" class="ver_select"><b>Rev 1:7</b>  He aquí que viene con las nubes, y todo ojo le verá, y los que le traspasaron, y todos los linajes de la tierra harán lamentación a causa de Él. Así sea. Amén. </div>
<div id="Rev_1_8" style="display:none;" class="ver_select"><b>Rev 1:8</b>  Yo soy el Alfa y la Omega, el principio y el fin, dice el Señor, el que es y que era y que ha de venir, el Todopoderoso. </div>
<div id="Rev_1_9" style="display:none;" class="ver_select"><b>Rev 1:9</b>  Yo Juan, que también soy vuestro hermano y compañero en la tribulación y en el reino y en la paciencia de Jesucristo, estaba en la isla que es llamada Patmos, por la palabra de Dios y por el testimonio de Jesucristo. </div>
<div id="Rev_1_10" style="display:none;" class="ver_select"><b>Rev 1:10</b>  Yo fui en el Espíritu en el día del Señor, y oí detrás de mí una gran voz, como de trompeta, </div>
<div id="Rev_1_11" style="display:none;" class="ver_select"><b>Rev 1:11</b>  que decía: Yo soy el Alfa y la Omega, el primero y el último. Escribe en un libro lo que ves, y envíalo a las siete iglesias que están en Asia; a Éfeso, y a Esmirna, y a Pérgamo, y a Tiatira, y a Sardis, y a Filadelfia, y a Laodicea. </div>
<div id="Rev_1_12" style="display:none;" class="ver_select"><b>Rev 1:12</b>  Y me volví para ver la voz que hablaba conmigo; y vuelto, vi siete candeleros de oro; </div>
<div id="Rev_1_13" style="display:none;" class="ver_select"><b>Rev 1:13</b>  y en medio de los siete candeleros, a uno semejante al Hijo del Hombre, vestido de una ropa que llegaba hasta los pies, y ceñido por el pecho con un cinto de oro. </div>
<div id="Rev_1_14" style="display:none;" class="ver_select"><b>Rev 1:14</b>  Su cabeza y sus cabellos eran blancos como la lana, tan blancos como la nieve; y sus ojos como llama de fuego; </div>
<div id="Rev_1_15" style="display:none;" class="ver_select"><b>Rev 1:15</b>  y sus pies semejantes al latón fino, ardientes como en un horno; y su voz como el ruido de muchas aguas. </div>
<div id="Rev_1_16" style="display:none;" class="ver_select"><b>Rev 1:16</b>  Y tenía en su diestra siete estrellas; y de su boca salía una espada aguda de dos filos, y su rostro era como el sol cuando resplandece en su fuerza. </div>
<div id="Rev_1_17" style="display:none;" class="ver_select"><b>Rev 1:17</b>  Y cuando le vi, caí como muerto a sus pies. Y Él puso su diestra sobre mí, diciéndome: No temas; yo soy el primero y el último; </div>
<div id="Rev_1_18" style="display:none;" class="ver_select"><b>Rev 1:18</b>  y el que vivo, y estuve muerto; y he aquí que vivo para siempre, amén. Y tengo las llaves de la muerte y del infierno. </div>
<div id="Rev_1_19" style="display:none;" class="ver_select"><b>Rev 1:19</b>  Escribe las cosas que has visto, y las que son, y las que han de ser después de éstas. </div>
<div id="Rev_1_20" style="display:none;" class="ver_select"><b>Rev 1:20</b>  El misterio de las siete estrellas que viste en mi diestra, y de los siete candeleros de oro. Las siete estrellas son los ángeles de las siete iglesias; y los siete candeleros que viste, son las siete iglesias. </div>
<div id="Rev_2_1" style="display:none;" class="ver_select"><b>Rev 2:1</b>  Escribe al ángel de la iglesia de ÉFESO: El que tiene las siete estrellas en su diestra, el que anda en medio de los siete candeleros de oro, dice estas cosas: </div>
<div id="Rev_2_2" style="display:none;" class="ver_select"><b>Rev 2:2</b>  Yo conozco tus obras, y tu trabajo, y tu paciencia; y que no puedes soportar a los malos, y has probado a los que se dicen ser apóstoles y no lo son, y los has hallado mentirosos; </div>
<div id="Rev_2_3" style="display:none;" class="ver_select"><b>Rev 2:3</b>  y has sufrido, y tienes paciencia, y has trabajado por mi nombre, y no has desfallecido. </div>
<div id="Rev_2_4" style="display:none;" class="ver_select"><b>Rev 2:4</b>  Pero tengo contra ti, que has dejado tu primer amor. </div>
<div id="Rev_2_5" style="display:none;" class="ver_select"><b>Rev 2:5</b>  Recuerda, por tanto, de dónde has caído, y arrepiéntete, y haz las primeras obras; pues si no, vendré pronto a ti, y quitaré tu candelero de su lugar, si no te hubieres arrepentido. </div>
<div id="Rev_2_6" style="display:none;" class="ver_select"><b>Rev 2:6</b>  Pero tienes esto, que aborreces las obras de los nicolaítas, las cuales yo también aborrezco. </div>
<div id="Rev_2_7" style="display:none;" class="ver_select"><b>Rev 2:7</b>  El que tiene oído, oiga lo que el Espíritu dice a las iglesias. Al que venciere, le daré a comer del árbol de la vida, el cual está en medio del paraíso de Dios. </div>
<div id="Rev_2_8" style="display:none;" class="ver_select"><b>Rev 2:8</b>  Y escribe al ángel de la iglesia en ESMIRNA: El primero y el postrero, que estuvo muerto y vive, dice estas cosas: </div>
<div id="Rev_2_9" style="display:none;" class="ver_select"><b>Rev 2:9</b>  Yo conozco tus obras, y tu tribulación, y tu pobreza (pero tú eres rico), y la blasfemia de los que se dicen ser judíos, y no lo son, mas son sinagoga de Satanás. </div>
<div id="Rev_2_10" style="display:none;" class="ver_select"><b>Rev 2:10</b>  No tengas ningún temor de las cosas que has de padecer. He aquí, el diablo echará a algunos de vosotros a la cárcel, para que seáis probados; y tendréis tribulación de diez días. Sé fiel hasta la muerte, y yo te daré la corona de la vida. </div>
<div id="Rev_2_11" style="display:none;" class="ver_select"><b>Rev 2:11</b>  El que tiene oído, oiga lo que el Espíritu dice a las iglesias. El que venciere no recibirá daño de la muerte segunda. </div>
<div id="Rev_2_12" style="display:none;" class="ver_select"><b>Rev 2:12</b>  Y escribe al ángel de la iglesia en PÉRGAMO: El que tiene la espada aguda de dos filos, dice estas cosas: </div>
<div id="Rev_2_13" style="display:none;" class="ver_select"><b>Rev 2:13</b>  Yo conozco tus obras, y dónde moras, donde está la silla de Satanás; y retienes mi nombre, y no has negado mi fe, ni aun en los días en que Antipas fue mi fiel mártir, el cual fue muerto entre vosotros, donde Satanás mora. </div>
<div id="Rev_2_14" style="display:none;" class="ver_select"><b>Rev 2:14</b>  Pero tengo unas pocas cosas contra ti; que tú tienes ahí a los que retienen la doctrina de Balaam, el cual enseñaba a Balac a poner tropiezo delante de los hijos de Israel, a comer de cosas sacrificadas a los ídolos, y a cometer fornicación. </div>
<div id="Rev_2_15" style="display:none;" class="ver_select"><b>Rev 2:15</b>  Así también tú tienes a los que retienen la doctrina de los nicolaítas, la cual yo aborrezco. </div>
<div id="Rev_2_16" style="display:none;" class="ver_select"><b>Rev 2:16</b>  Arrepiéntete, porque si no, vendré pronto a ti, y pelearé contra ellos con la espada de mi boca. </div>
<div id="Rev_2_17" style="display:none;" class="ver_select"><b>Rev 2:17</b>  El que tiene oído, oiga lo que el Espíritu dice a las iglesias. Al que venciere, daré a comer del maná escondido, y le daré una piedrecita blanca, y en la piedrecita un nombre nuevo escrito, el cual ninguno conoce sino aquel que lo recibe. </div>
<div id="Rev_2_18" style="display:none;" class="ver_select"><b>Rev 2:18</b>  Y escribe al ángel de la iglesia en TIATIRA: El Hijo de Dios, que tiene sus ojos como llama de fuego, y sus pies semejantes al latón fino, dice estas cosas: </div>
<div id="Rev_2_19" style="display:none;" class="ver_select"><b>Rev 2:19</b>  Yo conozco tus obras, y caridad, y servicio, y fe, y tu paciencia, y que tus obras postreras son más que las primeras. </div>
<div id="Rev_2_20" style="display:none;" class="ver_select"><b>Rev 2:20</b>  Pero tengo unas pocas cosas contra ti; porque permites a esa mujer Jezabel, que se dice profetisa, enseñar y seducir a mis siervos a fornicar y a comer cosas sacrificadas a los ídolos. </div>
<div id="Rev_2_21" style="display:none;" class="ver_select"><b>Rev 2:21</b>  Y le he dado tiempo para que se arrepienta de su fornicación; y no se ha arrepentido. </div>
<div id="Rev_2_22" style="display:none;" class="ver_select"><b>Rev 2:22</b>  He aquí, yo la arrojaré en cama, y a los que adulteran con ella, en muy grande tribulación, si no se arrepienten de sus obras. </div>
<div id="Rev_2_23" style="display:none;" class="ver_select"><b>Rev 2:23</b>  Y heriré a sus hijos con muerte; y todas las iglesias sabrán que yo soy el que escudriño los riñones y los corazones; y daré a cada uno de vosotros según sus obras. </div>
<div id="Rev_2_24" style="display:none;" class="ver_select"><b>Rev 2:24</b>  Pero a vosotros digo, y a los demás en Tiatira, a cuantos no tienen esta doctrina, y no han conocido lo que ellos llaman las profundidades de Satanás. No pondré sobre vosotros otra carga. </div>
<div id="Rev_2_25" style="display:none;" class="ver_select"><b>Rev 2:25</b>  Pero lo que tenéis, retenedlo hasta que yo venga. </div>
<div id="Rev_2_26" style="display:none;" class="ver_select"><b>Rev 2:26</b>  Y al que venciere y guardare mis obras hasta el fin, yo le daré potestad sobre las naciones; </div>
<div id="Rev_2_27" style="display:none;" class="ver_select"><b>Rev 2:27</b>  y las regirá con vara de hierro, y serán quebradas como vaso de alfarero; como también yo he recibido de mi Padre; </div>
<div id="Rev_2_28" style="display:none;" class="ver_select"><b>Rev 2:28</b>  y le daré la estrella de la mañana. </div>
<div id="Rev_2_29" style="display:none;" class="ver_select"><b>Rev 2:29</b>  El que tiene oído, oiga lo que el Espíritu dice a las iglesias. </div>
<div id="Rev_3_1" style="display:none;" class="ver_select"><b>Rev 3:1</b>  Y escribe al ángel de la iglesia en SARDIS: El que tiene los siete Espíritus de Dios, y las siete estrellas, dice estas cosas: Yo conozco tus obras, que tienes nombre de que vives, y estás muerto. </div>
<div id="Rev_3_2" style="display:none;" class="ver_select"><b>Rev 3:2</b>  Sé vigilante, y afirma las otras cosas que están para morir; porque no he hallado tus obras perfectas delante de Dios. </div>
<div id="Rev_3_3" style="display:none;" class="ver_select"><b>Rev 3:3</b>  Acuérdate, pues, de lo que has recibido y oído, y guárdalo, y arrepiéntete. Pues si no velares, vendré sobre ti como ladrón, y no sabrás a qué hora vendré sobre ti. </div>
<div id="Rev_3_4" style="display:none;" class="ver_select"><b>Rev 3:4</b>  Pero aun tienes unas pocas personas en Sardis que no han contaminado sus vestiduras; y andarán conmigo en vestiduras blancas; porque son dignas. </div>
<div id="Rev_3_5" style="display:none;" class="ver_select"><b>Rev 3:5</b>  El que venciere será vestido de vestiduras blancas; y no borraré su nombre del libro de la vida, y confesaré su nombre delante de mi Padre, y delante de sus ángeles. </div>
<div id="Rev_3_6" style="display:none;" class="ver_select"><b>Rev 3:6</b>  El que tiene oído, oiga lo que el Espíritu dice a las iglesias. </div>
<div id="Rev_3_7" style="display:none;" class="ver_select"><b>Rev 3:7</b>  Y escribe al ángel de la iglesia en FILADELFIA: El Santo, el Verdadero, el que tiene la llave de David, el que abre y ninguno cierra, y cierra y ninguno abre, dice estas cosas: </div>
<div id="Rev_3_8" style="display:none;" class="ver_select"><b>Rev 3:8</b>  Yo conozco tus obras: he aquí, he dado una puerta abierta delante de ti, la cual ninguno puede cerrar; porque aún tienes un poco de fuerza, y has guardado mi palabra, y no has negado mi nombre. </div>
<div id="Rev_3_9" style="display:none;" class="ver_select"><b>Rev 3:9</b>  He aquí, yo entrego de la sinagoga de Satanás a los que se dicen ser judíos y no lo son, sino que mienten; he aquí, yo haré que vengan y adoren delante de tus pies, y que reconozcan que yo te he amado. </div>
<div id="Rev_3_10" style="display:none;" class="ver_select"><b>Rev 3:10</b>  Por cuanto has guardado la palabra de mi paciencia, yo también te guardaré de la hora de la prueba que ha de venir sobre todo el mundo, para probar a los que moran sobre la tierra. </div>
<div id="Rev_3_11" style="display:none;" class="ver_select"><b>Rev 3:11</b>  He aquí, yo vengo pronto; retén lo que tienes, para que ninguno tome tu corona. </div>
<div id="Rev_3_12" style="display:none;" class="ver_select"><b>Rev 3:12</b>  Al que venciere, yo lo haré columna en el templo de mi Dios, y nunca más saldrá de allí; y escribiré sobre él el nombre de mi Dios, y el nombre de la ciudad de mi Dios, la nueva Jerusalén, la cual desciende del cielo, de mi Dios, y mi nombre nuevo. </div>
<div id="Rev_3_13" style="display:none;" class="ver_select"><b>Rev 3:13</b>  El que tiene oído, oiga lo que el Espíritu dice a las iglesias. </div>
<div id="Rev_3_14" style="display:none;" class="ver_select"><b>Rev 3:14</b>  Y escribe al ángel de la iglesia de los LAODICENSES: Estas cosas dice el Amén, el testigo fiel y verdadero, el principio de la creación de Dios: </div>
<div id="Rev_3_15" style="display:none;" class="ver_select"><b>Rev 3:15</b>  Yo conozco tus obras, que ni eres frío, ni caliente. ¡Quisiera que fueses frío o caliente! </div>
<div id="Rev_3_16" style="display:none;" class="ver_select"><b>Rev 3:16</b>  Mas porque eres tibio, y no frío ni caliente, te vomitaré de mi boca. </div>
<div id="Rev_3_17" style="display:none;" class="ver_select"><b>Rev 3:17</b>  Porque tú dices: Yo soy rico, y estoy enriquecido, y no tengo necesidad de nada; y no conoces que tú eres un desventurado, y miserable, y pobre, y ciego, y desnudo. </div>
<div id="Rev_3_18" style="display:none;" class="ver_select"><b>Rev 3:18</b>  Yo te aconsejo que de mí compres oro refinado en fuego, para que seas rico, y vestiduras blancas para que te vistas, y no se descubra la vergüenza de tu desnudez; y unge tus ojos con colirio, para que veas. </div>
<div id="Rev_3_19" style="display:none;" class="ver_select"><b>Rev 3:19</b>  Yo reprendo y castigo a todos los que amo; sé, pues, celoso, y arrepiéntete. </div>
<div id="Rev_3_20" style="display:none;" class="ver_select"><b>Rev 3:20</b>  He aquí, yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo. </div>
<div id="Rev_3_21" style="display:none;" class="ver_select"><b>Rev 3:21</b>  Al que venciere, yo le daré que se siente conmigo en mi trono; así como también yo he vencido, y me he sentado con mi Padre en su trono. </div>
<div id="Rev_3_22" style="display:none;" class="ver_select"><b>Rev 3:22</b>  El que tiene oído, oiga lo que el Espíritu dice a las iglesias. </div>
<div id="Rev_4_1" style="display:none;" class="ver_select"><b>Rev 4:1</b>  Después de estas cosas miré, y he aquí una puerta abierta en el cielo; y la primera voz que oí, era como de trompeta que hablaba conmigo, diciendo: Sube acá, y yo te mostraré las cosas que han de ser después de éstas. </div>
<div id="Rev_4_2" style="display:none;" class="ver_select"><b>Rev 4:2</b>  Y al instante estaba yo en el Espíritu; y he aquí, un trono que estaba puesto en el cielo, y uno sentado sobre el trono. </div>
<div id="Rev_4_3" style="display:none;" class="ver_select"><b>Rev 4:3</b>  Y el que estaba sentado, era al parecer semejante al jaspe y a la piedra de sardonia; y había alrededor del trono un arco iris, semejante en aspecto a la esmeralda. </div>
<div id="Rev_4_4" style="display:none;" class="ver_select"><b>Rev 4:4</b>  Y alrededor del trono había veinticuatro sillas; y vi sobre las sillas veinticuatro ancianos sentados, vestidos de ropas blancas; y tenían sobre sus cabezas coronas de oro. </div>
<div id="Rev_4_5" style="display:none;" class="ver_select"><b>Rev 4:5</b>  Y del trono salían relámpagos y truenos y voces; y delante del trono ardían siete lámparas de fuego, las cuales son los siete Espíritus de Dios. </div>
<div id="Rev_4_6" style="display:none;" class="ver_select"><b>Rev 4:6</b>  Y delante del trono había un mar de vidrio semejante al cristal; y en medio del trono, y alrededor del trono, cuatro seres vivientes llenos de ojos delante y detrás. </div>
<div id="Rev_4_7" style="display:none;" class="ver_select"><b>Rev 4:7</b>  Y el primer ser viviente era semejante a un león; y el segundo ser viviente era semejante a un becerro; y el tercer ser viviente tenía la cara como de hombre; y el cuarto ser viviente era semejante a un águila volando. </div>
<div id="Rev_4_8" style="display:none;" class="ver_select"><b>Rev 4:8</b>  Y los cuatro seres vivientes tenían cada uno seis alas alrededor, y por dentro estaban llenos de ojos; y no reposaban día y noche, diciendo: Santo, santo, santo, Señor Dios Todopoderoso, que era, y que es, y que ha de venir. </div>
<div id="Rev_4_9" style="display:none;" class="ver_select"><b>Rev 4:9</b>  Y cuando aquellos seres vivientes dan gloria y honra y gracias al que está sentado en el trono, al que vive para siempre jamás, </div>
<div id="Rev_4_10" style="display:none;" class="ver_select"><b>Rev 4:10</b>  los veinticuatro ancianos se postran delante del que está sentado en el trono, y adoran al que vive para siempre jamás, y echan sus coronas delante del trono, diciendo: </div>
<div id="Rev_4_11" style="display:none;" class="ver_select"><b>Rev 4:11</b>  Señor, digno eres de recibir la gloria y la honra y el poder; porque tú creaste todas las cosas, y por tu placer existen y fueron creadas. </div>
<div id="Rev_5_1" style="display:none;" class="ver_select"><b>Rev 5:1</b>  Y vi en la mano derecha del que estaba sentado sobre el trono un libro escrito por dentro y por atrás, sellado con siete sellos. </div>
<div id="Rev_5_2" style="display:none;" class="ver_select"><b>Rev 5:2</b>  Y vi a un ángel fuerte proclamando en alta voz: ¿Quién es digno de abrir el libro, y de desatar sus sellos? </div>
<div id="Rev_5_3" style="display:none;" class="ver_select"><b>Rev 5:3</b>  Y ninguno, ni en el cielo ni en la tierra ni debajo de la tierra, podía abrir el libro, ni aun mirarlo. </div>
<div id="Rev_5_4" style="display:none;" class="ver_select"><b>Rev 5:4</b>  Y yo lloraba mucho, porque ninguno fue hallado digno de abrir el libro, ni de leerlo, ni de mirarlo. </div>
<div id="Rev_5_5" style="display:none;" class="ver_select"><b>Rev 5:5</b>  Y uno de los ancianos me dijo: No llores; he aquí el León de la tribu de Judá, la raíz de David, que ha vencido para abrir el libro y desatar sus siete sellos. </div>
<div id="Rev_5_6" style="display:none;" class="ver_select"><b>Rev 5:6</b>  Y miré; y, he aquí, en medio del trono y de los cuatro seres vivientes, y en medio de los ancianos, estaba en pie un Cordero como inmolado, que tenía siete cuernos, y siete ojos, que son los siete Espíritus de Dios enviados a toda la tierra. </div>
<div id="Rev_5_7" style="display:none;" class="ver_select"><b>Rev 5:7</b>  Y Él vino, y tomó el libro de la mano derecha de Aquél que estaba sentado en el trono. </div>
<div id="Rev_5_8" style="display:none;" class="ver_select"><b>Rev 5:8</b>  Y cuando hubo tomado el libro, los cuatro seres vivientes y los veinticuatro ancianos se postraron delante del Cordero, teniendo cada uno arpas, y tazones de oro llenos de perfumes, que son las oraciones de los santos. </div>
<div id="Rev_5_9" style="display:none;" class="ver_select"><b>Rev 5:9</b>  Y cantaban un cántico nuevo, diciendo: Digno eres de tomar el libro y de abrir sus sellos; porque tú fuiste inmolado, y nos has redimido para Dios con tu sangre, de todo linaje y lengua y pueblo y nación; </div>
<div id="Rev_5_10" style="display:none;" class="ver_select"><b>Rev 5:10</b>  y nos has hecho para nuestro Dios reyes y sacerdotes, y reinaremos sobre la tierra. </div>
<div id="Rev_5_11" style="display:none;" class="ver_select"><b>Rev 5:11</b>  Y miré, y oí la voz de muchos ángeles alrededor del trono, y de los seres vivientes, y de los ancianos; y el número de ellos era millones de millones, </div>
<div id="Rev_5_12" style="display:none;" class="ver_select"><b>Rev 5:12</b>  que decían en alta voz: El Cordero que fue inmolado es digno de recibir el poder, las riquezas, la sabiduría, la fortaleza, el honor, la gloria y la alabanza. </div>
<div id="Rev_5_13" style="display:none;" class="ver_select"><b>Rev 5:13</b>  Y oí a toda criatura que está en el cielo, y sobre la tierra, y debajo de la tierra, y que está en el mar, y todas las cosas que en ellos hay, diciendo: Al que está sentado en el trono, y al Cordero, sea la alabanza, y la honra, y la gloria y el poder, por siempre jamás. </div>
<div id="Rev_5_14" style="display:none;" class="ver_select"><b>Rev 5:14</b>  Y los cuatro seres vivientes decían: Amén. Y los veinticuatro ancianos se postraron y adoraron al que vive por siempre jamás. </div>
<div id="Rev_6_1" style="display:none;" class="ver_select"><b>Rev 6:1</b>  Y vi cuando el Cordero abrió uno de los sellos, y oí a uno de los cuatro seres vivientes, como con voz de trueno, diciendo: Ven y mira. </div>
<div id="Rev_6_2" style="display:none;" class="ver_select"><b>Rev 6:2</b>  Y miré, y he aquí un caballo blanco; y el que estaba sentado sobre él tenía un arco; y le fue dada una corona, y salió venciendo, y para vencer. </div>
<div id="Rev_6_3" style="display:none;" class="ver_select"><b>Rev 6:3</b>  Y cuando Él abrió el segundo sello, oí al segundo ser viviente decir: Ven y mira. </div>
<div id="Rev_6_4" style="display:none;" class="ver_select"><b>Rev 6:4</b>  Y salió otro caballo, bermejo; y al que estaba sentado sobre él le fue dado poder de quitar la paz de la tierra, y que se matasen unos a otros; y le fue dada una grande espada. </div>
<div id="Rev_6_5" style="display:none;" class="ver_select"><b>Rev 6:5</b>  Y cuando abrió el tercer sello, oí al tercer ser viviente, que decía: Ven y mira. Y miré, y he aquí un caballo negro; y el que estaba sentado sobre él tenía una balanza en su mano. </div>
<div id="Rev_6_6" style="display:none;" class="ver_select"><b>Rev 6:6</b>  Y oí una voz en medio de los cuatro seres vivientes, que decía: Una medida de trigo por un denario, y tres medidas de cebada por un denario; y no hagas daño al vino ni al aceite. </div>
<div id="Rev_6_7" style="display:none;" class="ver_select"><b>Rev 6:7</b>  Y cuando abrió el cuarto sello, oí la voz del cuarto ser viviente, que decía: Ven y mira. </div>
<div id="Rev_6_8" style="display:none;" class="ver_select"><b>Rev 6:8</b>  Y miré, y he aquí un caballo pálido; y el que estaba sentado sobre él tenía por nombre Muerte; y el infierno le seguía. Y le fue dada potestad sobre la cuarta parte de la tierra, para matar con espada, con hambre, con mortandad, y con las fieras de la tierra. </div>
<div id="Rev_6_9" style="display:none;" class="ver_select"><b>Rev 6:9</b>  Y cuando abrió el quinto sello, vi debajo del altar las almas de los que habían sido muertos por causa de la palabra de Dios y por el testimonio que ellos tenían. </div>
<div id="Rev_6_10" style="display:none;" class="ver_select"><b>Rev 6:10</b>  Y clamaban en alta voz diciendo: ¿Hasta cuándo, Señor, santo y verdadero, no juzgas y vengas nuestra sangre de los que moran en la tierra? </div>
<div id="Rev_6_11" style="display:none;" class="ver_select"><b>Rev 6:11</b>  Y les fueron dadas vestiduras blancas a cada uno de ellos, y les fue dicho que reposasen todavía un poco de tiempo, hasta que se completaran sus consiervos y sus hermanos, que también habían de ser muertos como ellos. </div>
<div id="Rev_6_12" style="display:none;" class="ver_select"><b>Rev 6:12</b>  Y miré cuando Él abrió el sexto sello, y he aquí fue hecho un gran terremoto; y el sol se puso negro como un saco de cilicio, y la luna se volvió como sangre; </div>
<div id="Rev_6_13" style="display:none;" class="ver_select"><b>Rev 6:13</b>  y las estrellas del cielo cayeron sobre la tierra, como caen los higos verdes de la higuera cuando es sacudida por un fuerte viento. </div>
<div id="Rev_6_14" style="display:none;" class="ver_select"><b>Rev 6:14</b>  Y el cielo se apartó como un pergamino que es enrollado; y toda montaña y toda isla fue movida de su lugar. </div>
<div id="Rev_6_15" style="display:none;" class="ver_select"><b>Rev 6:15</b>  Y los reyes de la tierra, y los magistrados, y los ricos, y los capitanes, y los poderosos, y todo siervo y todo libre, se escondieron en las cuevas y entre las peñas de las montañas; </div>
<div id="Rev_6_16" style="display:none;" class="ver_select"><b>Rev 6:16</b>  y decían a las montañas y a las peñas: Caed sobre nosotros, y escondednos del rostro de Aquél que está sentado sobre el trono, y de la ira del Cordero; </div>
<div id="Rev_6_17" style="display:none;" class="ver_select"><b>Rev 6:17</b>  porque el gran día de su ira ha llegado; ¿y quién podrá sostenerse en pie? </div>
<div id="Rev_7_1" style="display:none;" class="ver_select"><b>Rev 7:1</b>  Y después de estas cosas vi cuatro ángeles en pie sobre los cuatro ángulos de la tierra, deteniendo los cuatro vientos de la tierra, para que no soplase viento sobre la tierra, ni sobre el mar, ni sobre ningún árbol. </div>
<div id="Rev_7_2" style="display:none;" class="ver_select"><b>Rev 7:2</b>  Y vi otro ángel que subía de donde nace el sol, teniendo el sello del Dios viviente. Y clamó con gran voz a los cuatro ángeles, a los cuales era dado hacer daño a la tierra y al mar, </div>
<div id="Rev_7_3" style="display:none;" class="ver_select"><b>Rev 7:3</b>  diciendo: No hagáis daño a la tierra, ni al mar, ni a los árboles, hasta que hayamos sellado a los siervos de nuestro Dios en sus frentes. </div>
<div id="Rev_7_4" style="display:none;" class="ver_select"><b>Rev 7:4</b>  Y oí el número de los sellados; ciento cuarenta y cuatro mil sellados de todas las tribus de los hijos de Israel. </div>
<div id="Rev_7_5" style="display:none;" class="ver_select"><b>Rev 7:5</b>  De la tribu de Judá, doce mil sellados. De la tribu de Rubén, doce mil sellados. De la tribu de Gad, doce mil sellados. </div>
<div id="Rev_7_6" style="display:none;" class="ver_select"><b>Rev 7:6</b>  De la tribu de Aser, doce mil sellados. De la tribu de Neftalí, doce mil sellados. De la tribu de Manasés, doce mil sellados. </div>
<div id="Rev_7_7" style="display:none;" class="ver_select"><b>Rev 7:7</b>  De la tribu de Simeón, doce mil sellados. De la tribu de Leví, doce mil sellados. De la tribu de Isacar, doce mil sellados. </div>
<div id="Rev_7_8" style="display:none;" class="ver_select"><b>Rev 7:8</b>  De la tribu de Zabulón, doce mil sellados. De la tribu de José, doce mil sellados. De la tribu de Benjamín, doce mil sellados. </div>
<div id="Rev_7_9" style="display:none;" class="ver_select"><b>Rev 7:9</b>  Después de estas cosas miré, y he aquí una gran multitud, la cual ninguno podía contar, de todas las naciones y tribus y pueblos y lenguas, que estaban delante del trono y en la presencia del Cordero, vestidos de ropas blancas y con palmas en sus manos; </div>
<div id="Rev_7_10" style="display:none;" class="ver_select"><b>Rev 7:10</b>  y aclamaban en alta voz, diciendo: Salvación a nuestro Dios que está sentado sobre el trono, y al Cordero. </div>
<div id="Rev_7_11" style="display:none;" class="ver_select"><b>Rev 7:11</b>  Y todos los ángeles estaban en pie alrededor del trono, y de los ancianos y de los cuatro seres vivientes; y se postraron sobre sus rostros delante del trono, y adoraron a Dios, </div>
<div id="Rev_7_12" style="display:none;" class="ver_select"><b>Rev 7:12</b>  diciendo: Amén: La alabanza y la gloria y la sabiduría y la acción de gracias y la honra y el poder y la fortaleza, sean a nuestro Dios por siempre jamás. Amén. </div>
<div id="Rev_7_13" style="display:none;" class="ver_select"><b>Rev 7:13</b>  Y respondió uno de los ancianos, diciéndome: Estos que están vestidos de ropas blancas, ¿quiénes son, y de dónde han venido? </div>
<div id="Rev_7_14" style="display:none;" class="ver_select"><b>Rev 7:14</b>  Y yo le dije: Señor, tú lo sabes. Y él me dijo: Éstos son los que han salido de gran tribulación, y han lavado sus ropas, y las han emblanquecido en la sangre del Cordero. </div>
<div id="Rev_7_15" style="display:none;" class="ver_select"><b>Rev 7:15</b>  Por esto están delante del trono de Dios, y le sirven día y noche en su templo; y el que está sentado sobre el trono extenderá su tabernáculo sobre ellos. </div>
<div id="Rev_7_16" style="display:none;" class="ver_select"><b>Rev 7:16</b>  No tendrán más hambre, ni sed; y el sol no caerá más sobre ellos, ni ningún calor; </div>
<div id="Rev_7_17" style="display:none;" class="ver_select"><b>Rev 7:17</b>  porque el Cordero que está en medio del trono los pastoreará, y los guiará a fuentes vivas de aguas: Y Dios enjugará toda lágrima de los ojos de ellos. </div>
<div id="Rev_8_1" style="display:none;" class="ver_select"><b>Rev 8:1</b>  Y cuando abrió el séptimo sello, fue hecho silencio en el cielo como por media hora. </div>
<div id="Rev_8_2" style="display:none;" class="ver_select"><b>Rev 8:2</b>  Y vi los siete ángeles que estaban en pie delante de Dios; y les fueron dadas siete trompetas. </div>
<div id="Rev_8_3" style="display:none;" class="ver_select"><b>Rev 8:3</b>  Y otro ángel vino y se puso en pie delante del altar, teniendo un incensario de oro; y le fue dado mucho incienso para que lo ofreciese con las oraciones de todos los santos sobre el altar de oro que estaba delante del trono. </div>
<div id="Rev_8_4" style="display:none;" class="ver_select"><b>Rev 8:4</b>  Y el humo del incienso subió de la mano del ángel delante de Dios con las oraciones de los santos. </div>
<div id="Rev_8_5" style="display:none;" class="ver_select"><b>Rev 8:5</b>  Y el ángel tomó el incensario, y lo llenó del fuego del altar, y lo arrojó a la tierra; y hubo voces, y truenos, y relámpagos, y terremotos. </div>
<div id="Rev_8_6" style="display:none;" class="ver_select"><b>Rev 8:6</b>  Y los siete ángeles que tenían las siete trompetas se aprestaron para tocarlas. </div>
<div id="Rev_8_7" style="display:none;" class="ver_select"><b>Rev 8:7</b>  Y el primer ángel tocó la trompeta, y hubo granizo y fuego mezclados con sangre, y fueron arrojados sobre la tierra; y la tercera parte de los árboles fue quemada, y toda la hierba verde fue quemada. </div>
<div id="Rev_8_8" style="display:none;" class="ver_select"><b>Rev 8:8</b>  Y el segundo ángel tocó la trompeta, y como una gran montaña ardiendo con fuego fue lanzada en el mar; y la tercera parte del mar se convirtió en sangre. </div>
<div id="Rev_8_9" style="display:none;" class="ver_select"><b>Rev 8:9</b>  Y murió la tercera parte de las criaturas que estaban en el mar, las cuales tenían vida; y la tercera parte de los navíos fue destruida. </div>
<div id="Rev_8_10" style="display:none;" class="ver_select"><b>Rev 8:10</b>  Y el tercer ángel tocó la trompeta, y cayó del cielo una grande estrella, ardiendo como una antorcha, y cayó sobre la tercera parte de los ríos, y sobre las fuentes de las aguas. </div>
<div id="Rev_8_11" style="display:none;" class="ver_select"><b>Rev 8:11</b>  Y el nombre de la estrella se dice Ajenjo. Y la tercera parte de las aguas fue tornada en ajenjo; y muchos hombres murieron por las aguas, porque fueron hechas amargas. </div>
<div id="Rev_8_12" style="display:none;" class="ver_select"><b>Rev 8:12</b>  Y el cuarto ángel tocó la trompeta, y fue herida la tercera parte del sol, y la tercera parte de la luna, y la tercera parte de las estrellas; de tal manera que se oscureció la tercera parte de ellos, y no alumbraba la tercera parte del día, y lo mismo de la noche. </div>
<div id="Rev_8_13" style="display:none;" class="ver_select"><b>Rev 8:13</b>  Y miré, y oí un ángel volar por medio del cielo, diciendo en alta voz: ¡Ay, ay, ay de los que moran en la tierra! A causa de los otros sonidos de trompeta de los tres ángeles que están por tocar. </div>
<div id="Rev_9_1" style="display:none;" class="ver_select"><b>Rev 9:1</b>  Y el quinto ángel tocó la trompeta, y vi una estrella que cayó del cielo a la tierra; y le fue dada la llave del pozo del abismo. </div>
<div id="Rev_9_2" style="display:none;" class="ver_select"><b>Rev 9:2</b>  Y abrió el pozo del abismo, y subió humo del pozo como el humo de un gran horno; y se oscureció el sol y el aire por el humo del pozo. </div>
<div id="Rev_9_3" style="display:none;" class="ver_select"><b>Rev 9:3</b>  Y del humo salieron langostas sobre la tierra; y les fue dado poder, como tienen poder los escorpiones de la tierra. </div>
<div id="Rev_9_4" style="display:none;" class="ver_select"><b>Rev 9:4</b>  Y les fue mandado que no hiciesen daño a la hierba de la tierra, ni a ninguna cosa verde, ni a ningún árbol, sino solamente a los hombres que no tienen el sello de Dios en sus frentes. </div>
<div id="Rev_9_5" style="display:none;" class="ver_select"><b>Rev 9:5</b>  Y les fue dado que no los matasen, sino que los atormentasen cinco meses; y su tormento era como tormento de escorpión, cuando hiere al hombre. </div>
<div id="Rev_9_6" style="display:none;" class="ver_select"><b>Rev 9:6</b>  Y en aquellos días los hombres buscarán la muerte, y no la hallarán; y desearán morir, pero la muerte huirá de ellos. </div>
<div id="Rev_9_7" style="display:none;" class="ver_select"><b>Rev 9:7</b>  Y el parecer de las langostas era semejante a caballos preparados para la guerra; y sobre sus cabezas tenían como coronas semejantes al oro; y sus caras eran como caras de hombres; </div>
<div id="Rev_9_8" style="display:none;" class="ver_select"><b>Rev 9:8</b>  y tenían cabello como cabello de mujer; y sus dientes eran como dientes de leones; </div>
<div id="Rev_9_9" style="display:none;" class="ver_select"><b>Rev 9:9</b>  y tenían corazas como corazas de hierro; y el ruido de sus alas era como el estruendo de muchos carros de caballos corriendo a la batalla. </div>
<div id="Rev_9_10" style="display:none;" class="ver_select"><b>Rev 9:10</b>  Y tenían colas como de escorpiones, y tenían en sus colas aguijones, y el poder de hacer daño a los hombres cinco meses. </div>
<div id="Rev_9_11" style="display:none;" class="ver_select"><b>Rev 9:11</b>  Y tenían por rey sobre ellos al ángel del abismo, cuyo nombre en hebreo es Abadón, y en griego, Apolyón. </div>
<div id="Rev_9_12" style="display:none;" class="ver_select"><b>Rev 9:12</b>  El primer ay es pasado; he aquí, vienen aún dos ayes más después de estas cosas. </div>
<div id="Rev_9_13" style="display:none;" class="ver_select"><b>Rev 9:13</b>  Y el sexto ángel tocó la trompeta; y oí una voz de los cuatro cuernos del altar de oro que estaba delante de Dios, </div>
<div id="Rev_9_14" style="display:none;" class="ver_select"><b>Rev 9:14</b>  diciendo al sexto ángel que tenía la trompeta: Desata los cuatro ángeles que están atados en el gran río Éufrates. </div>
<div id="Rev_9_15" style="display:none;" class="ver_select"><b>Rev 9:15</b>  Y fueron desatados los cuatro ángeles que estaban preparados para la hora, y el día, y el mes y el año, para matar la tercera parte de los hombres. </div>
<div id="Rev_9_16" style="display:none;" class="ver_select"><b>Rev 9:16</b>  Y el número del ejército de los de a caballo era doscientos millones. Y oí el número de ellos. </div>
<div id="Rev_9_17" style="display:none;" class="ver_select"><b>Rev 9:17</b>  Y así vi en visión los caballos y a los que sobre ellos estaban sentados, los cuales tenían corazas de fuego, de jacinto, y de azufre. Y las cabezas de los caballos eran como cabezas de leones; y de su boca salía fuego y humo y azufre. </div>
<div id="Rev_9_18" style="display:none;" class="ver_select"><b>Rev 9:18</b>  Por estas tres plagas fue muerta la tercera parte de los hombres; por el fuego, y por el humo, y por el azufre que salía de su boca. </div>
<div id="Rev_9_19" style="display:none;" class="ver_select"><b>Rev 9:19</b>  Porque su poder está en su boca y en sus colas; porque sus colas eran semejantes a serpientes, y tenían cabezas, y con ellas dañan. </div>
<div id="Rev_9_20" style="display:none;" class="ver_select"><b>Rev 9:20</b>  Y los otros hombres que no fueron muertos con estas plagas, ni aun así se arrepintieron de las obras de sus manos, para que no adorasen a los demonios, y a las imágenes de oro, y plata, y bronce, y piedra, y de madera; las cuales no pueden ver, ni oír, ni andar, </div>
<div id="Rev_9_21" style="display:none;" class="ver_select"><b>Rev 9:21</b>  y no se arrepintieron de sus homicidios, ni de sus hechicerías, ni de su fornicación, ni de sus hurtos. </div>
<div id="Rev_10_1" style="display:none;" class="ver_select"><b>Rev 10:1</b>  Y vi otro ángel fuerte descender del cielo, envuelto en una nube, y un arco iris sobre su cabeza; y su rostro era como el sol, y sus pies como columnas de fuego. </div>
<div id="Rev_10_2" style="display:none;" class="ver_select"><b>Rev 10:2</b>  Y tenía en su mano un librito abierto; y puso su pie derecho sobre el mar, y el izquierdo sobre la tierra; </div>
<div id="Rev_10_3" style="display:none;" class="ver_select"><b>Rev 10:3</b>  y clamó con gran voz, como cuando un león ruge; y cuando hubo clamado, siete truenos emitieron sus voces. </div>
<div id="Rev_10_4" style="display:none;" class="ver_select"><b>Rev 10:4</b>  Y cuando los siete truenos hubieron emitido sus voces, yo iba a escribir; y oí una voz del cielo que me decía: Sella las cosas que los siete truenos han dicho, y no las escribas. </div>
<div id="Rev_10_5" style="display:none;" class="ver_select"><b>Rev 10:5</b>  Y el ángel que vi en pie sobre el mar y sobre la tierra, levantó su mano al cielo, </div>
<div id="Rev_10_6" style="display:none;" class="ver_select"><b>Rev 10:6</b>  y juró por el que vive para siempre jamás, que creó el cielo y las cosas que están en él, y la tierra y las cosas que están en ella, y el mar y las cosas que están en él, que el tiempo no sería más. </div>
<div id="Rev_10_7" style="display:none;" class="ver_select"><b>Rev 10:7</b>  Pero en los días de la voz del séptimo ángel, cuando él comience a tocar la trompeta, el misterio de Dios será consumado, como Él lo anunció a sus siervos los profetas. </div>
<div id="Rev_10_8" style="display:none;" class="ver_select"><b>Rev 10:8</b>  Y la voz que oí del cielo habló otra vez conmigo, y dijo: Ve y toma el librito que está abierto en la mano del ángel que está en pie sobre el mar y sobre la tierra. </div>
<div id="Rev_10_9" style="display:none;" class="ver_select"><b>Rev 10:9</b>  Y fui al ángel, y le dije: Dame el librito; y él me dijo: Toma, y cómetelo; y te amargará tu vientre, pero en tu boca será dulce como la miel. </div>
<div id="Rev_10_10" style="display:none;" class="ver_select"><b>Rev 10:10</b>  Y tomé el librito de la mano del ángel, y lo comí; y en mi boca fue dulce como la miel; y cuando lo hube comido, amargó mi vientre. </div>
<div id="Rev_10_11" style="display:none;" class="ver_select"><b>Rev 10:11</b>  Y él me dijo: Es necesario que profetices otra vez ante muchos pueblos, y naciones, y lenguas, y reyes. </div>
<div id="Rev_11_1" style="display:none;" class="ver_select"><b>Rev 11:1</b>  Y me fue dada una caña semejante a una vara, y el ángel se puso en pie diciendo: Levántate, y mide el templo de Dios, y el altar, y a los que adoran en él. </div>
<div id="Rev_11_2" style="display:none;" class="ver_select"><b>Rev 11:2</b>  Pero el patio que está fuera del templo, déjalo aparte, y no lo midas, porque es dado a los gentiles; y ellos hollarán la ciudad santa cuarenta y dos meses. </div>
<div id="Rev_11_3" style="display:none;" class="ver_select"><b>Rev 11:3</b>  Y daré potestad a mis dos testigos, y ellos profetizarán por mil doscientos sesenta días, vestidos de cilicio. </div>
<div id="Rev_11_4" style="display:none;" class="ver_select"><b>Rev 11:4</b>  Éstos son los dos olivos, y los dos candeleros que están en pie delante del Dios de la tierra. </div>
<div id="Rev_11_5" style="display:none;" class="ver_select"><b>Rev 11:5</b>  Y si alguno quisiere dañarles, sale fuego de la boca de ellos, y devora a sus enemigos; y si alguno quisiere hacerles daño, debe de ser muerto de la misma manera. </div>
<div id="Rev_11_6" style="display:none;" class="ver_select"><b>Rev 11:6</b>  Éstos tienen potestad de cerrar el cielo, para que no llueva en los días de su profecía, y tienen potestad sobre las aguas para tornarlas en sangre, y para herir la tierra con toda plaga cuantas veces quisieren. </div>
<div id="Rev_11_7" style="display:none;" class="ver_select"><b>Rev 11:7</b>  Y cuando ellos hubieren acabado su testimonio, la bestia que sube del abismo hará guerra contra ellos, y los vencerá, y los matará. </div>
<div id="Rev_11_8" style="display:none;" class="ver_select"><b>Rev 11:8</b>  Y sus cadáveres yacerán en la plaza de la gran ciudad, que espiritualmente es llamada Sodoma y Egipto, donde también nuestro Señor fue crucificado. </div>
<div id="Rev_11_9" style="display:none;" class="ver_select"><b>Rev 11:9</b>  Y los de los pueblos, y tribus, y lenguas, y naciones verán los cadáveres de ellos por tres días y medio, y no permitirán que sus cadáveres sean puestos en sepulcros. </div>
<div id="Rev_11_10" style="display:none;" class="ver_select"><b>Rev 11:10</b>  Y los moradores de la tierra se regocijarán sobre ellos, y se alegrarán, y se enviarán dones unos a otros; porque estos dos profetas han atormentado a los que moran sobre la tierra. </div>
<div id="Rev_11_11" style="display:none;" class="ver_select"><b>Rev 11:11</b>  Y después de tres días y medio el Espíritu de vida enviado de Dios, entró en ellos, y se alzaron sobre sus pies, y vino gran temor sobre los que los vieron. </div>
<div id="Rev_11_12" style="display:none;" class="ver_select"><b>Rev 11:12</b>  Y oyeron una gran voz del cielo, que les decía: Subid acá. Y subieron al cielo en una nube, y sus enemigos los vieron. </div>
<div id="Rev_11_13" style="display:none;" class="ver_select"><b>Rev 11:13</b>  Y en aquella hora fue hecho gran terremoto, y la décima parte de la ciudad se derrumbó, y siete mil hombres murieron en el terremoto; y los demás se espantaron, y dieron gloria al Dios del cielo. </div>
<div id="Rev_11_14" style="display:none;" class="ver_select"><b>Rev 11:14</b>  El segundo ay es pasado; he aquí, el tercer ay viene pronto. </div>
<div id="Rev_11_15" style="display:none;" class="ver_select"><b>Rev 11:15</b>  Y el séptimo ángel tocó la trompeta; y fueron hechas grandes voces en el cielo, que decían: Los reinos de este mundo han venido a ser de nuestro Señor, y de su Cristo; y reinará para siempre jamás. </div>
<div id="Rev_11_16" style="display:none;" class="ver_select"><b>Rev 11:16</b>  Y los veinticuatro ancianos que estaban sentados delante de Dios en sus sillas, se postraron sobre sus rostros, y adoraron a Dios, </div>
<div id="Rev_11_17" style="display:none;" class="ver_select"><b>Rev 11:17</b>  Diciendo: Te damos gracias, oh Señor Dios Todopoderoso, que eres y que eras y que has de venir, porque has tomado tu gran poder, y has reinado. </div>
<div id="Rev_11_18" style="display:none;" class="ver_select"><b>Rev 11:18</b>  Y se han airado las naciones, y tu ira ha venido, y el tiempo para que los muertos sean juzgados, y para que des el galardón a tus siervos los profetas, y a los santos, y a los que temen tu nombre, pequeños y grandes, y para que destruyas los que destruyen la tierra. </div>
<div id="Rev_11_19" style="display:none;" class="ver_select"><b>Rev 11:19</b>  Y el templo de Dios fue abierto en el cielo, y el arca de su pacto fue vista en su templo. Y hubo relámpagos, y voces, y truenos, y un terremoto, y grande granizo. </div>
<div id="Rev_12_1" style="display:none;" class="ver_select"><b>Rev 12:1</b>  Y apareció en el cielo una gran señal; una mujer vestida del sol, y la luna debajo de sus pies, y sobre su cabeza una corona de doce estrellas. </div>
<div id="Rev_12_2" style="display:none;" class="ver_select"><b>Rev 12:2</b>  Y estando embarazada, clamaba con dolores de parto, y angustia por dar a luz. </div>
<div id="Rev_12_3" style="display:none;" class="ver_select"><b>Rev 12:3</b>  Y fue vista otra señal en el cielo; y he aquí un gran dragón bermejo, que tenía siete cabezas y diez cuernos, y en sus cabezas siete diademas. </div>
<div id="Rev_12_4" style="display:none;" class="ver_select"><b>Rev 12:4</b>  Y su cola arrastró la tercera parte de las estrellas del cielo, y las arrojó sobre la tierra. Y el dragón se paró delante de la mujer que estaba para dar a luz, a fin de devorar a su hijo tan pronto como naciese. </div>
<div id="Rev_12_5" style="display:none;" class="ver_select"><b>Rev 12:5</b>  Y ella dio a luz un hijo varón, el cual había de regir todas las naciones con vara de hierro; y su hijo fue arrebatado para Dios y para su trono. </div>
<div id="Rev_12_6" style="display:none;" class="ver_select"><b>Rev 12:6</b>  Y la mujer huyó al desierto, donde tiene lugar preparado por Dios, para que allí la sustenten mil doscientos sesenta días. </div>
<div id="Rev_12_7" style="display:none;" class="ver_select"><b>Rev 12:7</b>  Y hubo una gran batalla en el cielo: Miguel y sus ángeles luchaban contra el dragón; y luchaban el dragón y sus ángeles, </div>
<div id="Rev_12_8" style="display:none;" class="ver_select"><b>Rev 12:8</b>  pero no prevalecieron, ni fue hallado ya el lugar de ellos en el cielo. </div>
<div id="Rev_12_9" style="display:none;" class="ver_select"><b>Rev 12:9</b>  Y fue lanzado fuera aquel gran dragón, la serpiente antigua, llamada Diablo y Satanás, el cual engaña a todo el mundo; fue arrojado en tierra, y sus ángeles fueron arrojados con él. </div>
<div id="Rev_12_10" style="display:none;" class="ver_select"><b>Rev 12:10</b>  Y oí una gran voz en el cielo que decía: Ahora ha venido la salvación, y el poder, y el reino de nuestro Dios, y la potestad de su Cristo; porque el acusador de nuestros hermanos ha sido derribado, el cual los acusaba delante de nuestro Dios día y noche. </div>
<div id="Rev_12_11" style="display:none;" class="ver_select"><b>Rev 12:11</b>  Y ellos le han vencido por la sangre del Cordero, y por la palabra de su testimonio; y no han amado sus vidas hasta la muerte. </div>
<div id="Rev_12_12" style="display:none;" class="ver_select"><b>Rev 12:12</b>  Por lo cual alegraos, cielos, y los que moráis en ellos. ¡Ay de los moradores de la tierra y del mar! porque el diablo ha descendido a vosotros, teniendo grande ira, sabiendo que le queda poco tiempo. </div>
<div id="Rev_12_13" style="display:none;" class="ver_select"><b>Rev 12:13</b>  Y cuando vio el dragón que había sido arrojado a la tierra, persiguió a la mujer que había dado a luz al hijo varón. </div>
<div id="Rev_12_14" style="display:none;" class="ver_select"><b>Rev 12:14</b>  Y fueron dadas a la mujer dos alas de grande águila, para que de la presencia de la serpiente volase al desierto, a su lugar, donde es sustentada por un tiempo, y tiempos, y la mitad de un tiempo. </div>
<div id="Rev_12_15" style="display:none;" class="ver_select"><b>Rev 12:15</b>  Y la serpiente echó de su boca, tras la mujer, agua como un río, a fin de hacer que fuese arrastrada por el río. </div>
<div id="Rev_12_16" style="display:none;" class="ver_select"><b>Rev 12:16</b>  Pero la tierra ayudó a la mujer, pues la tierra abrió su boca, y sorbió el río que el dragón había echado de su boca. </div>
<div id="Rev_12_17" style="display:none;" class="ver_select"><b>Rev 12:17</b>  Entonces el dragón se enfureció contra la mujer; y se fue a hacer guerra contra el remanente de la simiente de ella, los cuales guardan los mandamientos de Dios, y tienen el testimonio de Jesucristo. </div>
<div id="Rev_13_1" style="display:none;" class="ver_select"><b>Rev 13:1</b>  Y me paré sobre la arena del mar, y vi subir del mar una bestia que tenía siete cabezas y diez cuernos; y sobre sus cuernos diez diademas; y sobre sus cabezas un nombre de blasfemia. </div>
<div id="Rev_13_2" style="display:none;" class="ver_select"><b>Rev 13:2</b>  Y la bestia que vi, era semejante a un leopardo, y sus pies como de oso, y su boca como boca de león. Y el dragón le dio su poder y su trono, y grande autoridad. </div>
<div id="Rev_13_3" style="display:none;" class="ver_select"><b>Rev 13:3</b>  Y vi una de sus cabezas como herida de muerte, y su herida de muerte fue sanada; y se maravilló toda la tierra en pos de la bestia. </div>
<div id="Rev_13_4" style="display:none;" class="ver_select"><b>Rev 13:4</b>  Y adoraron al dragón que había dado autoridad a la bestia, y adoraron a la bestia, diciendo: ¿Quién es semejante a la bestia, y quién podrá luchar contra ella? </div>
<div id="Rev_13_5" style="display:none;" class="ver_select"><b>Rev 13:5</b>  Y le fue dada boca que hablaba grandes cosas y blasfemias; y le fue dada potestad de actuar cuarenta y dos meses. </div>
<div id="Rev_13_6" style="display:none;" class="ver_select"><b>Rev 13:6</b>  Y abrió su boca en blasfemias contra Dios, para blasfemar su nombre y su tabernáculo, y a los que moran en el cielo. </div>
<div id="Rev_13_7" style="display:none;" class="ver_select"><b>Rev 13:7</b>  Y le fue dado hacer guerra contra los santos, y vencerlos. También le fue dado poder sobre toda tribu, y lengua y nación. </div>
<div id="Rev_13_8" style="display:none;" class="ver_select"><b>Rev 13:8</b>  Y le adorarán todos los moradores de la tierra cuyos nombres no están escritos en el libro de la vida del Cordero, el cual fue inmolado desde la fundación del mundo. </div>
<div id="Rev_13_9" style="display:none;" class="ver_select"><b>Rev 13:9</b>  Si alguno tiene oído, oiga. </div>
<div id="Rev_13_10" style="display:none;" class="ver_select"><b>Rev 13:10</b>  El que lleva en cautividad, irá en cautividad; el que a espada matare, a espada debe ser muerto. Aquí está la paciencia y la fe de los santos. </div>
<div id="Rev_13_11" style="display:none;" class="ver_select"><b>Rev 13:11</b>  Después vi otra bestia que subía de la tierra; y tenía dos cuernos semejantes a los de un cordero, pero hablaba como un dragón. </div>
<div id="Rev_13_12" style="display:none;" class="ver_select"><b>Rev 13:12</b>  Y ejerce todo el poder de la primera bestia en presencia de ella; y hace a la tierra y a los moradores de ella adorar la primera bestia, cuya herida de muerte fue sanada. </div>
<div id="Rev_13_13" style="display:none;" class="ver_select"><b>Rev 13:13</b>  Y hace grandes señales, de tal manera que aun hace descender fuego del cielo a la tierra delante de los hombres. </div>
<div id="Rev_13_14" style="display:none;" class="ver_select"><b>Rev 13:14</b>  Y engaña a los moradores de la tierra con las señales que le ha sido dado hacer en presencia de la bestia, mandando a los moradores de la tierra que le hagan imagen a la bestia que tiene la herida de espada, y vivió. </div>
<div id="Rev_13_15" style="display:none;" class="ver_select"><b>Rev 13:15</b>  Y le fue dado que diese vida a la imagen de la bestia, para que la imagen de la bestia hablase; e hiciese que todos los que no adorasen la imagen de la bestia fuesen muertos. </div>
<div id="Rev_13_16" style="display:none;" class="ver_select"><b>Rev 13:16</b>  Y hace que a todos, pequeños y grandes, ricos y pobres, libres y siervos, se les ponga una marca en su mano derecha, o en su frente; </div>
<div id="Rev_13_17" style="display:none;" class="ver_select"><b>Rev 13:17</b>  y que ninguno pueda comprar o vender, sino el que tenga la marca, o el nombre de la bestia, o el número de su nombre. </div>
<div id="Rev_13_18" style="display:none;" class="ver_select"><b>Rev 13:18</b>  Aquí hay sabiduría. El que tiene entendimiento, cuente el número de la bestia; porque es el número del hombre; y su número es seiscientos sesenta y seis. </div>
<div id="Rev_14_1" style="display:none;" class="ver_select"><b>Rev 14:1</b>  Y miré, y he aquí un Cordero estaba en pie sobre el monte de Sión, y con Él ciento cuarenta y cuatro mil, que tenían el nombre de su Padre escrito en sus frentes. </div>
<div id="Rev_14_2" style="display:none;" class="ver_select"><b>Rev 14:2</b>  Y oí una voz del cielo como estruendo de muchas aguas, y como sonido de un gran trueno; y oí una voz de tañedores de arpas que tañían con sus arpas. </div>
<div id="Rev_14_3" style="display:none;" class="ver_select"><b>Rev 14:3</b>  Y cantaban como un cántico nuevo delante del trono, y delante de los cuatro seres vivientes, y de los ancianos; y ninguno podía aprender el cántico sino aquellos ciento cuarenta y cuatro mil, los cuales fueron redimidos de entre los de la tierra. </div>
<div id="Rev_14_4" style="display:none;" class="ver_select"><b>Rev 14:4</b>  Éstos son los que no fueron contaminados con mujeres; porque son vírgenes. Éstos son los que siguen al Cordero por dondequiera que Él va. Éstos fueron redimidos de entre los hombres por primicias para Dios y para el Cordero. </div>
<div id="Rev_14_5" style="display:none;" class="ver_select"><b>Rev 14:5</b>  Y en sus bocas no fue hallado engaño; porque ellos son sin mácula delante del trono de Dios. </div>
<div id="Rev_14_6" style="display:none;" class="ver_select"><b>Rev 14:6</b>  Y vi otro ángel volar en medio del cielo, que tenía el evangelio eterno, para predicarlo a los moradores de la tierra, y a toda nación y tribu y lengua y pueblo, </div>
<div id="Rev_14_7" style="display:none;" class="ver_select"><b>Rev 14:7</b>  diciendo en alta voz: Temed a Dios, y dadle gloria; porque la hora de su juicio ha venido; y adorad a Aquél que hizo el cielo y la tierra, y el mar y las fuentes de las aguas. </div>
<div id="Rev_14_8" style="display:none;" class="ver_select"><b>Rev 14:8</b>  Y otro ángel le siguió, diciendo: Ha caído, ha caído Babilonia, aquella gran ciudad, porque ella ha dado a beber a todas las naciones del vino de la ira de su fornicación. </div>
<div id="Rev_14_9" style="display:none;" class="ver_select"><b>Rev 14:9</b>  Y el tercer ángel los siguió, diciendo en alta voz: Si alguno adora a la bestia y a su imagen, y recibe la marca en su frente, o en su mano, </div>
<div id="Rev_14_10" style="display:none;" class="ver_select"><b>Rev 14:10</b>  él también beberá del vino de la ira de Dios, el cual es vaciado puro en el cáliz de su ira; y será atormentado con fuego y azufre delante de los santos ángeles, y delante del Cordero. </div>
<div id="Rev_14_11" style="display:none;" class="ver_select"><b>Rev 14:11</b>  Y el humo del tormento de ellos sube para siempre jamás; y los que adoran a la bestia y a su imagen no tienen reposo ni de día ni de noche, ni cualquiera que reciba la marca de su nombre. </div>
<div id="Rev_14_12" style="display:none;" class="ver_select"><b>Rev 14:12</b>  Aquí está la paciencia de los santos; aquí están los que guardan los mandamientos de Dios y la fe de Jesús. </div>
<div id="Rev_14_13" style="display:none;" class="ver_select"><b>Rev 14:13</b>  Y oí una voz del cielo que me decía: Escribe: Bienaventurados de aquí en adelante los muertos que mueren en el Señor. Sí, dice el Espíritu, porque descansan de sus trabajos; pero sus obras con ellos continúan. </div>
<div id="Rev_14_14" style="display:none;" class="ver_select"><b>Rev 14:14</b>  Y miré, y he aquí una nube blanca; y sobre la nube uno sentado semejante al Hijo del Hombre, que tenía en su cabeza una corona de oro, y en su mano una hoz aguda. </div>
<div id="Rev_14_15" style="display:none;" class="ver_select"><b>Rev 14:15</b>  Y otro ángel salió del templo, clamando en alta voz al que estaba sentado sobre la nube: Mete tu hoz, y siega; porque la hora de segar te es venida, porque la mies de la tierra está madura. </div>
<div id="Rev_14_16" style="display:none;" class="ver_select"><b>Rev 14:16</b>  Y el que estaba sentado sobre la nube metió su hoz en la tierra, y la tierra fue segada. </div>
<div id="Rev_14_17" style="display:none;" class="ver_select"><b>Rev 14:17</b>  Y salió otro ángel del templo que está en el cielo, teniendo también una hoz aguda. </div>
<div id="Rev_14_18" style="display:none;" class="ver_select"><b>Rev 14:18</b>  Y otro ángel salió del altar, el cual tenía poder sobre el fuego, y clamó con gran voz al que tenía la hoz aguda, diciendo: Mete tu hoz aguda, y vendimia los racimos de la tierra, porque sus uvas están maduras. </div>
<div id="Rev_14_19" style="display:none;" class="ver_select"><b>Rev 14:19</b>  Y el ángel metió su hoz aguda en la tierra, y vendimió la viña de la tierra, y la echó en el gran lagar de la ira de Dios. </div>
<div id="Rev_14_20" style="display:none;" class="ver_select"><b>Rev 14:20</b>  Y el lagar fue hollado fuera de la ciudad, y del lagar salió sangre hasta los frenos de los caballos, por mil seiscientos estadios. </div>
<div id="Rev_15_1" style="display:none;" class="ver_select"><b>Rev 15:1</b>  Y vi en el cielo otra señal, grande y admirable; siete ángeles que tenían las siete plagas postreras; porque en ellas es consumada la ira de Dios. </div>
<div id="Rev_15_2" style="display:none;" class="ver_select"><b>Rev 15:2</b>  Y vi como un mar de vidrio mezclado con fuego; y los que habían alcanzado la victoria sobre la bestia, y sobre su imagen, y sobre su marca, y sobre el número de su nombre, en pie sobre el mar de vidrio, teniendo las arpas de Dios. </div>
<div id="Rev_15_3" style="display:none;" class="ver_select"><b>Rev 15:3</b>  Y cantan el cántico de Moisés siervo de Dios, y el cántico del Cordero, diciendo: Grandes y maravillosas son tus obras, Señor Dios Todopoderoso; justos y verdaderos son tus caminos, Rey de los santos. </div>
<div id="Rev_15_4" style="display:none;" class="ver_select"><b>Rev 15:4</b>  ¿Quién no te temerá, oh Señor, y glorificará tu nombre? pues sólo tú eres santo; por lo cual todas las naciones vendrán, y adorarán delante de ti, porque tus juicios se han manifestado. </div>
<div id="Rev_15_5" style="display:none;" class="ver_select"><b>Rev 15:5</b>  Y después de estas cosas miré, y he aquí el templo del tabernáculo del testimonio fue abierto en el cielo; </div>
<div id="Rev_15_6" style="display:none;" class="ver_select"><b>Rev 15:6</b>  y salieron del templo los siete ángeles, que tenían las siete plagas, vestidos de un lino puro y resplandeciente, y ceñidos alrededor del pecho con cintos de oro. </div>
<div id="Rev_15_7" style="display:none;" class="ver_select"><b>Rev 15:7</b>  Y uno de los cuatro seres vivientes dio a los siete ángeles siete copas de oro, llenas de la ira de Dios, que vive por siempre jamás. </div>
<div id="Rev_15_8" style="display:none;" class="ver_select"><b>Rev 15:8</b>  Y el templo se llenó con el humo de la gloria de Dios, y de su poder; y nadie podía entrar en el templo, hasta que fuesen consumadas las siete plagas de los siete ángeles. </div>
<div id="Rev_16_1" style="display:none;" class="ver_select"><b>Rev 16:1</b>  Y oí una gran voz que decía desde el templo a los siete ángeles: Id, y derramad las copas de la ira de Dios sobre la tierra. </div>
<div id="Rev_16_2" style="display:none;" class="ver_select"><b>Rev 16:2</b>  Y fue el primero, y derramó su copa sobre la tierra; y vino una pestilente y maligna úlcera sobre los hombres que tenían la marca de la bestia y que adoraban su imagen. </div>
<div id="Rev_16_3" style="display:none;" class="ver_select"><b>Rev 16:3</b>  Y el segundo ángel derramó su copa sobre el mar, y éste se convirtió en sangre como de muerto; y murió todo ser viviente en el mar. </div>
<div id="Rev_16_4" style="display:none;" class="ver_select"><b>Rev 16:4</b>  Y el tercer ángel derramó su copa sobre los ríos, y sobre las fuentes de las aguas, y se tornaron en sangre. </div>
<div id="Rev_16_5" style="display:none;" class="ver_select"><b>Rev 16:5</b>  Y oí al ángel de las aguas, que decía: Justo eres tú, oh Señor, que eres y que eras, y serás, porque has juzgado así. </div>
<div id="Rev_16_6" style="display:none;" class="ver_select"><b>Rev 16:6</b>  Por cuanto ellos derramaron la sangre de santos y de profetas, y tú les has dado a beber sangre; pues lo merecen. </div>
<div id="Rev_16_7" style="display:none;" class="ver_select"><b>Rev 16:7</b>  Y oí a otro que desde el altar decía: Ciertamente, Señor Dios Todopoderoso, tus juicios son verdaderos y justos. </div>
<div id="Rev_16_8" style="display:none;" class="ver_select"><b>Rev 16:8</b>  Y el cuarto ángel derramó su copa sobre el sol; y le fue dado quemar a los hombres con fuego. </div>
<div id="Rev_16_9" style="display:none;" class="ver_select"><b>Rev 16:9</b>  Y los hombres se quemaron con el gran calor, y blasfemaron el nombre de Dios, que tiene potestad sobre estas plagas, y no se arrepintieron para darle gloria. </div>
<div id="Rev_16_10" style="display:none;" class="ver_select"><b>Rev 16:10</b>  Y el quinto ángel derramó su copa sobre la silla de la bestia; y su reino se cubrió de tinieblas, y se mordían sus lenguas de dolor; </div>
<div id="Rev_16_11" style="display:none;" class="ver_select"><b>Rev 16:11</b>  y blasfemaron contra el Dios del cielo por causa de sus dolores, y por sus plagas, y no se arrepintieron de sus obras. </div>
<div id="Rev_16_12" style="display:none;" class="ver_select"><b>Rev 16:12</b>  Y el sexto ángel derramó su copa sobre el gran río Éufrates; y el agua de éste se secó, para que fuese preparado el camino de los reyes del oriente. </div>
<div id="Rev_16_13" style="display:none;" class="ver_select"><b>Rev 16:13</b>  Y vi salir de la boca del dragón, y de la boca de la bestia, y de la boca del falso profeta, tres espíritus inmundos a manera de ranas; </div>
<div id="Rev_16_14" style="display:none;" class="ver_select"><b>Rev 16:14</b>  porque son espíritus de demonios, haciendo milagros, que van a los reyes de la tierra y a todo el mundo, para congregarlos para la batalla de aquel gran día del Dios Todopoderoso. </div>
<div id="Rev_16_15" style="display:none;" class="ver_select"><b>Rev 16:15</b>  He aquí, yo vengo como ladrón. Bienaventurado el que vela, y guarda sus vestiduras, para que no ande desnudo, y vean su vergüenza. </div>
<div id="Rev_16_16" style="display:none;" class="ver_select"><b>Rev 16:16</b>  Y los congregó en el lugar que en hebreo es llamado Armagedón. </div>
<div id="Rev_16_17" style="display:none;" class="ver_select"><b>Rev 16:17</b>  Y el séptimo ángel derramó su copa por el aire; y salió una gran voz del templo del cielo, del trono, diciendo: ¡Hecho está! </div>
<div id="Rev_16_18" style="display:none;" class="ver_select"><b>Rev 16:18</b>  Y hubo voces, y relámpagos y truenos; y hubo un gran temblor, un terremoto tan grande, cual no hubo jamás desde que los hombres han estado sobre la tierra. </div>
<div id="Rev_16_19" style="display:none;" class="ver_select"><b>Rev 16:19</b>  Y la gran ciudad fue partida en tres partes, y las ciudades de las naciones cayeron; y la gran Babilonia vino en memoria delante de Dios, para darle el cáliz del vino del furor de su ira. </div>
<div id="Rev_16_20" style="display:none;" class="ver_select"><b>Rev 16:20</b>  Y toda isla huyó, y los montes no fueron hallados. </div>
<div id="Rev_16_21" style="display:none;" class="ver_select"><b>Rev 16:21</b>  Y cayó del cielo sobre los hombres un grande granizo como del peso de un talento; y los hombres blasfemaron a Dios por la plaga del granizo; porque su plaga fue muy grande. </div>
<div id="Rev_17_1" style="display:none;" class="ver_select"><b>Rev 17:1</b>  Y vino uno de los siete ángeles que tenían las siete copas, y habló conmigo, diciéndome: Ven acá, y te mostraré la condenación de la gran ramera, la cual está sentada sobre muchas aguas; </div>
<div id="Rev_17_2" style="display:none;" class="ver_select"><b>Rev 17:2</b>  con la cual han fornicado los reyes de la tierra, y los que moran en la tierra se han embriagado con el vino de su fornicación. </div>
<div id="Rev_17_3" style="display:none;" class="ver_select"><b>Rev 17:3</b>  Y me llevó en el Espíritu al desierto; y vi una mujer sentada sobre una bestia escarlata llena de nombres de blasfemia y que tenía siete cabezas y diez cuernos. </div>
<div id="Rev_17_4" style="display:none;" class="ver_select"><b>Rev 17:4</b>  Y la mujer estaba vestida de púrpura y de escarlata, y adornada con oro, piedras preciosas y perlas, y tenía en su mano un cáliz de oro lleno de abominaciones y de la suciedad de su fornicación; </div>
<div id="Rev_17_5" style="display:none;" class="ver_select"><b>Rev 17:5</b>  y en su frente un nombre escrito: MISTERIO, BABILONIA LA GRANDE, LA MADRE DE LAS RAMERAS Y DE LAS ABOMINACIONES DE LA TIERRA. </div>
<div id="Rev_17_6" style="display:none;" class="ver_select"><b>Rev 17:6</b>  Y vi a la mujer embriagada de la sangre de los santos, y de la sangre de los mártires de Jesús; y cuando la vi, quedé maravillado con gran asombro. </div>
<div id="Rev_17_7" style="display:none;" class="ver_select"><b>Rev 17:7</b>  Y el ángel me dijo: ¿Por qué te maravillas? Yo te diré el misterio de la mujer, y de la bestia que la trae, la cual tiene siete cabezas y diez cuernos. </div>
<div id="Rev_17_8" style="display:none;" class="ver_select"><b>Rev 17:8</b>  La bestia que has visto, era, y no es; y ha de subir del abismo, y ha de ir a perdición; y los moradores de la tierra, cuyos nombres no están escritos en el libro de la vida desde la fundación del mundo, se maravillarán cuando vean la bestia, que era y no es, aunque es. </div>
<div id="Rev_17_9" style="display:none;" class="ver_select"><b>Rev 17:9</b>  Aquí hay mente que tiene sabiduría. Las siete cabezas son siete montes, sobre los cuales se sienta la mujer. </div>
<div id="Rev_17_10" style="display:none;" class="ver_select"><b>Rev 17:10</b>  Y son siete reyes. Cinco son caídos; uno es, el otro aún no ha venido; y cuando viniere, es necesario que dure breve tiempo. </div>
<div id="Rev_17_11" style="display:none;" class="ver_select"><b>Rev 17:11</b>  Y la bestia que era, y no es, es también el octavo, y es de los siete, y va a perdición. </div>
<div id="Rev_17_12" style="display:none;" class="ver_select"><b>Rev 17:12</b>  Y los diez cuernos que has visto, son diez reyes, que aún no han recibido reino; mas recibirán potestad por una hora como reyes con la bestia. </div>
<div id="Rev_17_13" style="display:none;" class="ver_select"><b>Rev 17:13</b>  Éstos tienen un mismo propósito, y darán su poder y autoridad a la bestia. </div>
<div id="Rev_17_14" style="display:none;" class="ver_select"><b>Rev 17:14</b>  Ellos pelearán contra el Cordero, y el Cordero los vencerá, porque Él es Señor de señores y Rey de reyes; y los que están con Él son llamados, y elegidos, y fieles. </div>
<div id="Rev_17_15" style="display:none;" class="ver_select"><b>Rev 17:15</b>  Y me dijo: Las aguas que viste, donde se sienta la ramera, son pueblos y multitudes y naciones y lenguas. </div>
<div id="Rev_17_16" style="display:none;" class="ver_select"><b>Rev 17:16</b>  Y los diez cuernos que viste en la bestia, éstos aborrecerán a la ramera, y la harán desolada y desnuda; y comerán sus carnes, y la quemarán con fuego; </div>
<div id="Rev_17_17" style="display:none;" class="ver_select"><b>Rev 17:17</b>  porque Dios ha puesto en sus corazones ejecutar su voluntad, y el ponerse de acuerdo, y dar su reino a la bestia, hasta que sean cumplidas las palabras de Dios. </div>
<div id="Rev_17_18" style="display:none;" class="ver_select"><b>Rev 17:18</b>  Y la mujer que has visto, es la gran ciudad que tiene reino sobre los reyes de la tierra. </div>
<div id="Rev_18_1" style="display:none;" class="ver_select"><b>Rev 18:1</b>  Y después de estas cosas vi otro ángel descender del cielo teniendo gran poder; y la tierra fue alumbrada de su gloria. </div>
<div id="Rev_18_2" style="display:none;" class="ver_select"><b>Rev 18:2</b>  Y clamó fuertemente en alta voz, diciendo: ¡Caída es, caída es Babilonia la grande! Y es hecha habitación de demonios, y guarida de todo espíritu inmundo, y albergue de toda ave inmunda y aborrecible. </div>
<div id="Rev_18_3" style="display:none;" class="ver_select"><b>Rev 18:3</b>  Porque todas las naciones han bebido del vino del furor de su fornicación; y los reyes de la tierra han fornicado con ella, y los mercaderes de la tierra se han enriquecido de la abundancia de sus deleites. </div>
<div id="Rev_18_4" style="display:none;" class="ver_select"><b>Rev 18:4</b>  Y oí otra voz del cielo, que decía: Salid de ella, pueblo mío, para que no seáis partícipes de sus pecados, y para que no recibáis de sus plagas; </div>
<div id="Rev_18_5" style="display:none;" class="ver_select"><b>Rev 18:5</b>  porque sus pecados han llegado hasta el cielo, y Dios se ha acordado de las maldades de ella. </div>
<div id="Rev_18_6" style="display:none;" class="ver_select"><b>Rev 18:6</b>  Dadle como ella os ha dado, y pagadle al doble según sus obras; en la copa que ella os preparó, preparadle el doble. </div>
<div id="Rev_18_7" style="display:none;" class="ver_select"><b>Rev 18:7</b>  Cuanto ella se ha glorificado, y ha vivido en deleites, tanto dadle de tormento y llanto; porque dice en su corazón: Yo estoy sentada como reina, y no soy viuda, y no veré llanto. </div>
<div id="Rev_18_8" style="display:none;" class="ver_select"><b>Rev 18:8</b>  Por lo cual en un día vendrán sus plagas, muerte, llanto y hambre, y será quemada con fuego; porque poderoso es el Señor Dios que la juzga. </div>
<div id="Rev_18_9" style="display:none;" class="ver_select"><b>Rev 18:9</b>  Y llorarán y se lamentarán sobre ella los reyes de la tierra, los cuales han fornicado con ella, y han vivido en deleites, cuando ellos vieren el humo de su incendio, </div>
<div id="Rev_18_10" style="display:none;" class="ver_select"><b>Rev 18:10</b>  parándose lejos por el temor de su tormento, diciendo: ¡Ay, ay, de la gran ciudad de Babilonia, la ciudad poderosa; porque en una hora vino tu juicio! </div>
<div id="Rev_18_11" style="display:none;" class="ver_select"><b>Rev 18:11</b>  Y los mercaderes de la tierra llorarán y se lamentarán sobre ella, porque ninguno compra más sus mercaderías; </div>
<div id="Rev_18_12" style="display:none;" class="ver_select"><b>Rev 18:12</b>  mercadería de oro, y plata, y piedras preciosas, y perlas, y lino fino, y púrpura, y seda, y escarlata, y toda madera olorosa, y todo artículo de marfil, y todo artículo de madera preciosa, y de bronce, y de hierro, y de mármol; </div>
<div id="Rev_18_13" style="display:none;" class="ver_select"><b>Rev 18:13</b>  y canela, y aromas, y ungüentos, e incienso, y vino, y aceite; y flor de harina y trigo, y bestias, y ovejas; y caballos, y carros, y esclavos, y almas de hombres. </div>
<div id="Rev_18_14" style="display:none;" class="ver_select"><b>Rev 18:14</b>  Y los frutos codiciados de tu alma se han ido de ti; y todas las cosas suntuosas y espléndidas se han ido de ti, y nunca más las hallarás. </div>
<div id="Rev_18_15" style="display:none;" class="ver_select"><b>Rev 18:15</b>  Los mercaderes de estas cosas, que se han enriquecido por ella, se pararán lejos por el temor de su tormento, llorando y lamentando, </div>
<div id="Rev_18_16" style="display:none;" class="ver_select"><b>Rev 18:16</b>  y diciendo: ¡Ay, ay, de aquella gran ciudad, que estaba vestida de lino fino y de púrpura y de escarlata, y adornada con oro y piedras preciosas y perlas! </div>
<div id="Rev_18_17" style="display:none;" class="ver_select"><b>Rev 18:17</b>  Porque en una hora ha sido desolada tanta riqueza. Y todo timonel, y todos los que navegan en barcos, y marineros, y todos los que trabajan en el mar, se pararon lejos; </div>
<div id="Rev_18_18" style="display:none;" class="ver_select"><b>Rev 18:18</b>  y viendo el humo de su incendio, dieron voces, diciendo: ¿Qué ciudad era semejante a esta gran ciudad? </div>
<div id="Rev_18_19" style="display:none;" class="ver_select"><b>Rev 18:19</b>  Y echaron polvo sobre sus cabezas; y dieron voces, llorando y lamentando, diciendo: ¡Ay, ay, de aquella gran ciudad, en la cual todos los que tenían navíos en el mar se habían enriquecido de sus riquezas; porque en una hora ha sido desolada! </div>
<div id="Rev_18_20" style="display:none;" class="ver_select"><b>Rev 18:20</b>  Alégrate sobre ella, cielo, y vosotros, santos apóstoles y profetas; porque Dios os ha vengado en ella. </div>
<div id="Rev_18_21" style="display:none;" class="ver_select"><b>Rev 18:21</b>  Y un ángel fuerte tomó una piedra como una gran piedra de molino, y la arrojó en el mar, diciendo: Con esta violencia será derribada Babilonia, aquella gran ciudad, y nunca más será hallada. </div>
<div id="Rev_18_22" style="display:none;" class="ver_select"><b>Rev 18:22</b>  Y voz de arpistas, y de músicos, y de flautistas, y de trompetistas, no se oirá más en ti; y ningún artífice de cualquier oficio, no se hallará más en ti; y el ruido de la piedra de molino no se oirá más en ti. </div>
<div id="Rev_18_23" style="display:none;" class="ver_select"><b>Rev 18:23</b>  Y luz de candelero no alumbrará más en ti; y voz de desposado y de desposada no se oirá más en ti; porque tus mercaderes eran los magnates de la tierra; porque por tus hechicerías fueron engañadas todas las naciones. </div>
<div id="Rev_18_24" style="display:none;" class="ver_select"><b>Rev 18:24</b>  Y en ella fue hallada la sangre de los profetas y de los santos, y de todos los que han sido muertos en la tierra. </div>
<div id="Rev_19_1" style="display:none;" class="ver_select"><b>Rev 19:1</b>  Y después de estas cosas oí una gran voz de gran multitud en el cielo, que decía: ¡Aleluya! Salvación y honra y gloria y poder al Señor nuestro Dios. </div>
<div id="Rev_19_2" style="display:none;" class="ver_select"><b>Rev 19:2</b>  Porque sus juicios son justos y verdaderos; porque Él ha juzgado a la gran ramera, que ha corrompido la tierra con su fornicación, y ha vengado la sangre de sus siervos de la mano de ella. </div>
<div id="Rev_19_3" style="display:none;" class="ver_select"><b>Rev 19:3</b>  Y otra vez dijeron: ¡Aleluya! Y su humo subió para siempre jamás. </div>
<div id="Rev_19_4" style="display:none;" class="ver_select"><b>Rev 19:4</b>  Y los veinticuatro ancianos y los cuatro seres vivientes se postraron en tierra, y adoraron a Dios que estaba sentado sobre el trono, diciendo: Amén: Aleluya. </div>
<div id="Rev_19_5" style="display:none;" class="ver_select"><b>Rev 19:5</b>  Y salió una voz del trono, que decía: Load a nuestro Dios todos sus siervos, y los que le teméis, así pequeños como grandes. </div>
<div id="Rev_19_6" style="display:none;" class="ver_select"><b>Rev 19:6</b>  Y oí como la voz de una gran multitud, y como el estruendo de muchas aguas, y como la voz de grandes truenos, diciendo: ¡Aleluya, porque reina el Señor Dios Todopoderoso! </div>
<div id="Rev_19_7" style="display:none;" class="ver_select"><b>Rev 19:7</b>  Gocémonos y alegrémonos y démosle gloria; porque han venido las bodas del Cordero, y su esposa se ha aparejado. </div>
<div id="Rev_19_8" style="display:none;" class="ver_select"><b>Rev 19:8</b>  Y a ella se le ha concedido que se vista de lino fino, limpio y resplandeciente; porque el lino fino es la justicia de los santos. </div>
<div id="Rev_19_9" style="display:none;" class="ver_select"><b>Rev 19:9</b>  Y él me dijo: Escribe: Bienaventurados los que son llamados a la cena del Cordero. Y me dijo: Éstas son palabras verdaderas de Dios. </div>
<div id="Rev_19_10" style="display:none;" class="ver_select"><b>Rev 19:10</b>  Y yo me postré a sus pies para adorarle. Y él me dijo: Mira, no lo hagas; yo soy consiervo tuyo, y de tus hermanos que tienen el testimonio de Jesús. Adora a Dios; porque el testimonio de Jesús es el espíritu de la profecía. </div>
<div id="Rev_19_11" style="display:none;" class="ver_select"><b>Rev 19:11</b>  Y vi el cielo abierto; y he aquí un caballo blanco, y el que estaba sentado sobre él, era llamado Fiel y Verdadero, y en justicia juzga y pelea. </div>
<div id="Rev_19_12" style="display:none;" class="ver_select"><b>Rev 19:12</b>  Y sus ojos eran como llama de fuego, y había en su cabeza muchas coronas; y tenía un nombre escrito que ninguno conocía sino Él mismo. </div>
<div id="Rev_19_13" style="display:none;" class="ver_select"><b>Rev 19:13</b>  Y estaba vestido de una ropa teñida en sangre; y su nombre es llamado EL VERBO DE DIOS. </div>
<div id="Rev_19_14" style="display:none;" class="ver_select"><b>Rev 19:14</b>  Y los ejércitos que están en el cielo le seguían en caballos blancos, vestidos de lino fino, blanco y limpio. </div>
<div id="Rev_19_15" style="display:none;" class="ver_select"><b>Rev 19:15</b>  Y de su boca sale una espada aguda, para herir con ella a las naciones; y Él las regirá con vara de hierro; y Él pisa el lagar del vino del furor y de la ira del Dios Todopoderoso. </div>
<div id="Rev_19_16" style="display:none;" class="ver_select"><b>Rev 19:16</b>  Y en su vestidura y en su muslo tiene escrito este nombre: REY DE REYES Y SEÑOR DE SEÑORES. </div>
<div id="Rev_19_17" style="display:none;" class="ver_select"><b>Rev 19:17</b>  Y vi a un ángel que estaba en pie en el sol, y clamó a gran voz, diciendo a todas las aves que volaban por medio del cielo: Venid, y congregaos a la cena del gran Dios, </div>
<div id="Rev_19_18" style="display:none;" class="ver_select"><b>Rev 19:18</b>  para que comáis carnes de reyes, y carnes de capitanes, y carnes de fuertes, y carnes de caballos, y de los que están sentados sobre ellos; y carnes de todos, libres y siervos, pequeños y grandes. </div>
<div id="Rev_19_19" style="display:none;" class="ver_select"><b>Rev 19:19</b>  Y vi a la bestia, a los reyes de la tierra y a sus ejércitos, reunidos para hacer guerra contra el que estaba sentado sobre el caballo, y contra su ejército. </div>
<div id="Rev_19_20" style="display:none;" class="ver_select"><b>Rev 19:20</b>  Y la bestia fue apresada, y con ella el falso profeta que había hecho los milagros delante de ella, con los cuales había engañado a los que recibieron la marca de la bestia, y habían adorado su imagen. Estos dos fueron lanzados vivos dentro de un lago de fuego ardiendo con azufre. </div>
<div id="Rev_19_21" style="display:none;" class="ver_select"><b>Rev 19:21</b>  Y los demás fueron muertos con la espada que salía de la boca del que estaba sentado sobre el caballo, y todas las aves fueron saciadas de las carnes de ellos. </div>
<div id="Rev_20_1" style="display:none;" class="ver_select"><b>Rev 20:1</b>  Y vi a un ángel descender del cielo, que tenía la llave del abismo, y una cadena grande en su mano. </div>
<div id="Rev_20_2" style="display:none;" class="ver_select"><b>Rev 20:2</b>  Y prendió al dragón, aquella serpiente antigua, que es el Diablo y Satanás, y le ató por mil años; </div>
<div id="Rev_20_3" style="display:none;" class="ver_select"><b>Rev 20:3</b>  y lo arrojó al abismo, y lo encerró, y puso sello sobre él, para que no engañase más a las naciones, hasta que los mil años fuesen cumplidos; y después de esto es necesario que sea desatado un poco de tiempo. </div>
<div id="Rev_20_4" style="display:none;" class="ver_select"><b>Rev 20:4</b>  Y vi tronos, y a los que se sentaron sobre ellos les fue dado juicio; y vi las almas de los decapitados por el testimonio de Jesús, y por la palabra de Dios, y que no habían adorado la bestia, ni a su imagen, y que no recibieron la marca en sus frentes ni en sus manos, y vivieron y reinaron con Cristo mil años. </div>
<div id="Rev_20_5" style="display:none;" class="ver_select"><b>Rev 20:5</b>  Mas los otros muertos no volvieron a vivir hasta que se cumplieron mil años. Ésta es la primera resurrección. </div>
<div id="Rev_20_6" style="display:none;" class="ver_select"><b>Rev 20:6</b>  Bienaventurado y santo el que tiene parte en la primera resurrección; la segunda muerte no tiene potestad sobre éstos; sino que serán sacerdotes de Dios y de Cristo, y reinarán con Él mil años. </div>
<div id="Rev_20_7" style="display:none;" class="ver_select"><b>Rev 20:7</b>  Y cuando los mil años fueren cumplidos, Satanás será suelto de su prisión, </div>
<div id="Rev_20_8" style="display:none;" class="ver_select"><b>Rev 20:8</b>  y saldrá para engañar a las naciones que están sobre los cuatro ángulos de la tierra, Gog y Magog, a fin de reunirlos para la batalla; el número de los cuales es como la arena del mar. </div>
<div id="Rev_20_9" style="display:none;" class="ver_select"><b>Rev 20:9</b>  Y subieron sobre la anchura de la tierra, y rodearon el campamento de los santos, y la ciudad amada; y de Dios descendió fuego del cielo, y los devoró. </div>
<div id="Rev_20_10" style="display:none;" class="ver_select"><b>Rev 20:10</b>  Y el diablo que los engañaba, fue lanzado en el lago de fuego y azufre, donde está la bestia y el falso profeta; y serán atormentados día y noche por siempre jamás. </div>
<div id="Rev_20_11" style="display:none;" class="ver_select"><b>Rev 20:11</b>  Y vi un gran trono blanco y al que estaba sentado sobre él, de delante del cual huyeron la tierra y el cielo; y no fue hallado lugar para ellos. </div>
<div id="Rev_20_12" style="display:none;" class="ver_select"><b>Rev 20:12</b>  Y vi los muertos, grandes y pequeños, de pie ante Dios; y los libros fueron abiertos; y otro libro fue abierto, el cual es el libro de la vida; y fueron juzgados los muertos por las cosas que estaban escritas en los libros, según sus obras. </div>
<div id="Rev_20_13" style="display:none;" class="ver_select"><b>Rev 20:13</b>  Y el mar dio los muertos que estaban en él; y la muerte y el infierno dieron los muertos que estaban en ellos; y fueron juzgados cada uno según sus obras. </div>
<div id="Rev_20_14" style="display:none;" class="ver_select"><b>Rev 20:14</b>  Y la muerte y el infierno fueron lanzados en el lago de fuego. Ésta es la muerte segunda. </div>
<div id="Rev_20_15" style="display:none;" class="ver_select"><b>Rev 20:15</b>  Y el que no fue hallado escrito en el libro de la vida fue lanzado en el lago de fuego. </div>
<div id="Rev_21_1" style="display:none;" class="ver_select"><b>Rev 21:1</b>  Y vi un cielo nuevo y una tierra nueva; porque el primer cielo y la primera tierra habían pasado, y el mar no existía ya más. </div>
<div id="Rev_21_2" style="display:none;" class="ver_select"><b>Rev 21:2</b>  Y yo Juan vi la santa ciudad, la nueva Jerusalén, que descendía del cielo, de Dios, dispuesta como una novia ataviada para su marido. </div>
<div id="Rev_21_3" style="display:none;" class="ver_select"><b>Rev 21:3</b>  Y oí una gran voz del cielo que decía: He aquí el tabernáculo de Dios con los hombres, y Él morará con ellos; y ellos serán su pueblo, y Dios mismo estará con ellos, y será su Dios. </div>
<div id="Rev_21_4" style="display:none;" class="ver_select"><b>Rev 21:4</b>  Y enjugará Dios toda lágrima de los ojos de ellos; y ya no habrá muerte, ni habrá más llanto, ni clamor, ni dolor; porque las primeras cosas pasaron. </div>
<div id="Rev_21_5" style="display:none;" class="ver_select"><b>Rev 21:5</b>  Y el que estaba sentado en el trono dijo: He aquí, yo hago nuevas todas las cosas. Y me dijo: Escribe; porque estas palabras son fieles y verdaderas. </div>
<div id="Rev_21_6" style="display:none;" class="ver_select"><b>Rev 21:6</b>  Y me dijo: Hecho es. Yo soy el Alfa y la Omega, el principio y el fin. Al que tuviere sed, yo le daré de la fuente del agua de vida gratuitamente. </div>
<div id="Rev_21_7" style="display:none;" class="ver_select"><b>Rev 21:7</b>  El que venciere, heredará todas las cosas; y yo seré su Dios, y él será mi hijo. </div>
<div id="Rev_21_8" style="display:none;" class="ver_select"><b>Rev 21:8</b>  Pero los temerosos e incrédulos, los abominables y homicidas, los fornicarios y hechiceros, los idólatras, y todos los mentirosos, tendrán su parte en el lago que arde con fuego y azufre, que es la muerte segunda. </div>
<div id="Rev_21_9" style="display:none;" class="ver_select"><b>Rev 21:9</b>  Y vino a mí uno de los siete ángeles que tenían las siete copas llenas de las siete plagas postreras, y habló conmigo, diciendo: Ven acá, yo te mostraré la desposada, la esposa del Cordero. </div>
<div id="Rev_21_10" style="display:none;" class="ver_select"><b>Rev 21:10</b>  Y me llevó en el Espíritu a un monte grande y alto, y me mostró la gran ciudad santa de Jerusalén, que descendía del cielo de Dios, </div>
<div id="Rev_21_11" style="display:none;" class="ver_select"><b>Rev 21:11</b>  teniendo la gloria de Dios; y su luz era semejante a una piedra preciosísima, como piedra de jaspe, diáfana como el cristal. </div>
<div id="Rev_21_12" style="display:none;" class="ver_select"><b>Rev 21:12</b>  Y tenía un muro grande y alto, y tenía doce puertas; y a las puertas, doce ángeles, y nombres escritos en ellas, que son los nombres de las doce tribus de los hijos de Israel. </div>
<div id="Rev_21_13" style="display:none;" class="ver_select"><b>Rev 21:13</b>  Al oriente tres puertas; al norte tres puertas; al sur tres puertas; al poniente tres puertas. </div>
<div id="Rev_21_14" style="display:none;" class="ver_select"><b>Rev 21:14</b>  Y el muro de la ciudad tenía doce fundamentos, y en ellos los nombres de los doce apóstoles del Cordero. </div>
<div id="Rev_21_15" style="display:none;" class="ver_select"><b>Rev 21:15</b>  Y el que hablaba conmigo, tenía una caña de oro para medir la ciudad, y sus puertas, y su muro. </div>
<div id="Rev_21_16" style="display:none;" class="ver_select"><b>Rev 21:16</b>  Y la ciudad está situada y puesta en cuadro, y su longitud es tanta como su anchura; y él midió la ciudad con la caña, doce mil estadios: La longitud y la altura y la anchura de ella son iguales. </div>
<div id="Rev_21_17" style="display:none;" class="ver_select"><b>Rev 21:17</b>  Y midió su muro, ciento cuarenta y cuatro codos de medida de hombre, la cual es de ángel. </div>
<div id="Rev_21_18" style="display:none;" class="ver_select"><b>Rev 21:18</b>  Y el material de su muro era de jaspe; y la ciudad era de oro puro, semejante al vidrio limpio; </div>
<div id="Rev_21_19" style="display:none;" class="ver_select"><b>Rev 21:19</b>  y los fundamentos del muro de la ciudad estaban adornados de toda piedra preciosa. El primer fundamento era jaspe; el segundo, zafiro; el tercero, calcedonia; el cuarto, esmeralda; </div>
<div id="Rev_21_20" style="display:none;" class="ver_select"><b>Rev 21:20</b>  el quinto, ónice; el sexto, sardio; el séptimo, crisólito; el octavo, berilo; el noveno, topacio; el décimo, crisopraso; el undécimo, jacinto; el duodécimo, amatista. </div>
<div id="Rev_21_21" style="display:none;" class="ver_select"><b>Rev 21:21</b>  Y las doce puertas eran doce perlas; cada una de las puertas era de una perla. Y la plaza de la ciudad era de oro puro, como vidrio transparente. </div>
<div id="Rev_21_22" style="display:none;" class="ver_select"><b>Rev 21:22</b>  Y no vi templo en ella; porque el Señor Dios Todopoderoso y el Cordero son el templo de ella. </div>
<div id="Rev_21_23" style="display:none;" class="ver_select"><b>Rev 21:23</b>  Y la ciudad no tenía necesidad de sol ni de luna para que resplandezcan en ella; porque la gloria de Dios la iluminaba, y el Cordero es su luz. </div>
<div id="Rev_21_24" style="display:none;" class="ver_select"><b>Rev 21:24</b>  Y las naciones de los que hubieren sido salvos andarán en la luz de ella; y los reyes de la tierra traerán su gloria y honor a ella. </div>
<div id="Rev_21_25" style="display:none;" class="ver_select"><b>Rev 21:25</b>  Y sus puertas nunca serán cerradas de día, pues allí no habrá noche. </div>
<div id="Rev_21_26" style="display:none;" class="ver_select"><b>Rev 21:26</b>  Y traerán la gloria y la honra de las naciones a ella. </div>
<div id="Rev_21_27" style="display:none;" class="ver_select"><b>Rev 21:27</b>  Y no entrará en ella ninguna cosa inmunda, o que hace abominación o mentira; sino sólo aquellos que están escritos en el libro de la vida del Cordero. </div>
<div id="Rev_22_1" style="display:none;" class="ver_select"><b>Rev 22:1</b>  Y me mostró un río puro de agua de vida, límpido como el cristal, que provenía del trono de Dios y del Cordero. </div>
<div id="Rev_22_2" style="display:none;" class="ver_select"><b>Rev 22:2</b>  En el medio de la calle de ella, y de uno y de otro lado del río, estaba el árbol de la vida, que lleva doce frutos, dando cada mes su fruto; y las hojas del árbol eran para la sanidad de las naciones. </div>
<div id="Rev_22_3" style="display:none;" class="ver_select"><b>Rev 22:3</b>  Y no habrá más maldición; y el trono de Dios y del Cordero estará en ella, y sus siervos le servirán; </div>
<div id="Rev_22_4" style="display:none;" class="ver_select"><b>Rev 22:4</b>  y verán su rostro, y su nombre estará en sus frentes. </div>
<div id="Rev_22_5" style="display:none;" class="ver_select"><b>Rev 22:5</b>  Y allí no habrá más noche; y no tienen necesidad de lámpara, ni de luz de sol, porque el Señor Dios los alumbrará; y reinarán por siempre jamás. </div>
<div id="Rev_22_6" style="display:none;" class="ver_select"><b>Rev 22:6</b>  Y me dijo: Estas palabras son fieles y verdaderas. Y el Señor Dios de los santos profetas ha enviado su ángel, para mostrar a sus siervos las cosas que deben acontecer en breve. </div>
<div id="Rev_22_7" style="display:none;" class="ver_select"><b>Rev 22:7</b>  He aquí, yo vengo pronto. Bienaventurado el que guarda las palabras de la profecía de este libro. </div>
<div id="Rev_22_8" style="display:none;" class="ver_select"><b>Rev 22:8</b>  Y yo Juan vi y oí estas cosas. Y después que las hube oído y visto, me postré para adorar a los pies del ángel que me mostraba estas cosas. </div>
<div id="Rev_22_9" style="display:none;" class="ver_select"><b>Rev 22:9</b>  Y él me dijo: Mira que no lo hagas; porque yo soy consiervo tuyo, y de tus hermanos los profetas, y de los que guardan las palabras de este libro. Adora a Dios. </div>
<div id="Rev_22_10" style="display:none;" class="ver_select"><b>Rev 22:10</b>  Y me dijo: No selles las palabras de la profecía de este libro, porque el tiempo está cerca. </div>
<div id="Rev_22_11" style="display:none;" class="ver_select"><b>Rev 22:11</b>  El que es injusto, sea injusto todavía; y el que es sucio, ensúciese todavía; y el que es justo, sea justo todavía; y el que es santo, santifíquese todavía. </div>
<div id="Rev_22_12" style="display:none;" class="ver_select"><b>Rev 22:12</b>  Y he aquí, yo vengo pronto, y mi galardón conmigo, para recompensar a cada uno según fuere su obra. </div>
<div id="Rev_22_13" style="display:none;" class="ver_select"><b>Rev 22:13</b>  Yo soy el Alfa y la Omega, el principio y el fin, el primero y el postrero. </div>
<div id="Rev_22_14" style="display:none;" class="ver_select"><b>Rev 22:14</b>  Bienaventurados los que guardan sus mandamientos, para tener derecho al árbol de la vida, y poder entrar por las puertas en la ciudad. </div>
<div id="Rev_22_15" style="display:none;" class="ver_select"><b>Rev 22:15</b>  Mas los perros estarán afuera, y los hechiceros, y los disolutos, y los homicidas, y los idólatras, y cualquiera que ama y hace mentira. </div>
<div id="Rev_22_16" style="display:none;" class="ver_select"><b>Rev 22:16</b>  Yo Jesús he enviado mi ángel para daros testimonio de estas cosas en las iglesias. Yo soy la raíz y el linaje de David, y la estrella resplandeciente de la mañana. </div>
<div id="Rev_22_17" style="display:none;" class="ver_select"><b>Rev 22:17</b>  Y el Espíritu y la esposa dicen: Ven. Y el que oye, diga: Ven. Y el que tiene sed, venga; y el que quiere, tome del agua de la vida gratuitamente. </div>
<div id="Rev_22_18" style="display:none;" class="ver_select"><b>Rev 22:18</b>  Porque yo testifico a cualquiera que oye las palabras de la profecía de este libro: Si alguno añadiere a estas cosas, Dios añadirá sobre él las plagas que están escritas en este libro. </div>
<div id="Rev_22_19" style="display:none;" class="ver_select"><b>Rev 22:19</b>  Y si alguno quitare de las palabras del libro de esta profecía, Dios quitará su parte del libro de la vida, y de la santa ciudad, y de las cosas que están escritas en este libro. </div>
<div id="Rev_22_20" style="display:none;" class="ver_select"><b>Rev 22:20</b>  El que da testimonio de estas cosas, dice: Ciertamente vengo en breve. Amén, así sea. Ven: Señor Jesús. </div>
<div id="Rev_22_21" style="display:none;" class="ver_select"><b>Rev 22:21</b>  La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén. </div>
