<div id="Rth_1_1" style="display:none;" class="ver_select"><b>Rth 1:1</b>  Y aconteció en los días que gobernaban los jueces, que hubo hambre en la tierra. Y un varón de Belén de Judá, fue a peregrinar en los campos de Moab, él y su esposa, y sus dos hijos. </div>
<div id="Rth_1_2" style="display:none;" class="ver_select"><b>Rth 1:2</b>  El nombre de aquel varón era Elimelec, y el de su esposa Noemí; y los nombres de sus dos hijos eran, Mahalón y Quilión, efrateos de Belén de Judá. Llegaron, pues, a los campos de Moab, y asentaron allí. </div>
<div id="Rth_1_3" style="display:none;" class="ver_select"><b>Rth 1:3</b>  Y murió Elimelec, marido de Noemí, y quedó ella con sus dos hijos, </div>
<div id="Rth_1_4" style="display:none;" class="ver_select"><b>Rth 1:4</b>  los cuales tomaron para sí esposas de las mujeres de Moab, el nombre de una era Orfa, y el nombre de la otra, Ruth; y habitaron allí unos diez años. </div>
<div id="Rth_1_5" style="display:none;" class="ver_select"><b>Rth 1:5</b>  Y murieron también los dos, Mahalón y Quilión, quedando así la mujer desamparada de sus dos hijos y de su marido. </div>
<div id="Rth_1_6" style="display:none;" class="ver_select"><b>Rth 1:6</b>  Entonces se levantó con sus nueras, y regresó de los campos de Moab, porque oyó en el campo de Moab que Jehová había visitado a su pueblo para darles pan. </div>
<div id="Rth_1_7" style="display:none;" class="ver_select"><b>Rth 1:7</b>  Salió, pues, del lugar donde había estado, y con ella sus dos nueras, y comenzaron a caminar para volverse a la tierra de Judá. </div>
<div id="Rth_1_8" style="display:none;" class="ver_select"><b>Rth 1:8</b>  Y Noemí dijo a sus dos nueras: Andad, volveos cada una a la casa de su madre: Jehová haga con vosotras misericordia, como la habéis hecho con los muertos y conmigo. </div>
<div id="Rth_1_9" style="display:none;" class="ver_select"><b>Rth 1:9</b>  Os conceda Jehová que halléis descanso, cada una en casa de su marido; las besó luego, y ellas alzaron su voz y lloraron. </div>
<div id="Rth_1_10" style="display:none;" class="ver_select"><b>Rth 1:10</b>  Y le dijeron: Ciertamente nosotras volveremos contigo a tu pueblo. </div>
<div id="Rth_1_11" style="display:none;" class="ver_select"><b>Rth 1:11</b>  Y Noemí respondió: Volveos, hijas mías: ¿Para qué habéis de ir conmigo? ¿Tengo yo más hijos en el vientre, que puedan ser vuestros maridos? </div>
<div id="Rth_1_12" style="display:none;" class="ver_select"><b>Rth 1:12</b>  Volveos, hijas mías, e idos; que yo ya soy vieja para ser para varón. Y aunque dijese: Esperanza tengo; y esta noche estuviese con marido, y aun diere a luz hijos; </div>
<div id="Rth_1_13" style="display:none;" class="ver_select"><b>Rth 1:13</b>  ¿habíais vosotras de esperarlos hasta que fuesen grandes? ¿Habíais vosotras de quedaros sin casar por amor de ellos? No, hijas mías; que mayor amargura tengo yo que vosotras, pues la mano de Jehová ha salido contra mí. </div>
<div id="Rth_1_14" style="display:none;" class="ver_select"><b>Rth 1:14</b>  Mas ellas alzando otra vez su voz, lloraron; y Orfa besó a su suegra, mas Ruth se quedó con ella. </div>
<div id="Rth_1_15" style="display:none;" class="ver_select"><b>Rth 1:15</b>  Y Noemí dijo: He aquí tu cuñada se ha vuelto a su pueblo y a sus dioses; vuélvete tú tras ella. </div>
<div id="Rth_1_16" style="display:none;" class="ver_select"><b>Rth 1:16</b>  Y Ruth respondió: No me ruegues que te deje, y que me aparte de ti; porque a dondequiera que tú vayas, iré yo; y dondequiera que vivas, viviré. Tu pueblo será mi pueblo, y tu Dios será mi Dios. </div>
<div id="Rth_1_17" style="display:none;" class="ver_select"><b>Rth 1:17</b>  Donde tú mueras, moriré yo, y allí seré sepultada; así me haga Jehová, y aun me añada, que sólo la muerte hará separación entre tú y yo. </div>
<div id="Rth_1_18" style="display:none;" class="ver_select"><b>Rth 1:18</b>  Y viendo Noemí que estaba tan resuelta a ir con ella, no dijo más. </div>
<div id="Rth_1_19" style="display:none;" class="ver_select"><b>Rth 1:19</b>  Anduvieron, pues, ellas dos hasta que llegaron a Belén. Y aconteció que entrando en Belén, toda la ciudad se conmovió por causa de ellas, y decían: ¿No es ésta Noemí? </div>
<div id="Rth_1_20" style="display:none;" class="ver_select"><b>Rth 1:20</b>  Y ella les respondía: No me llaméis Noemí, sino llamadme Mara; porque en grande amargura me ha puesto el Todopoderoso. </div>
<div id="Rth_1_21" style="display:none;" class="ver_select"><b>Rth 1:21</b>  Yo me fui llena, mas vacía me ha vuelto Jehová. ¿Por qué me llamaréis Noemí, ya que Jehová ha dado testimonio contra mí, y el Todopoderoso me ha afligido? </div>
<div id="Rth_1_22" style="display:none;" class="ver_select"><b>Rth 1:22</b>  Así volvió Noemí, y con ella su nuera Ruth la moabita, la cual venía de los campos de Moab; y llegaron a Belén en el principio de la siega de las cebadas. </div>
<div id="Rth_2_1" style="display:none;" class="ver_select"><b>Rth 2:1</b>  Y tenía Noemí un pariente de su marido, varón rico y poderoso, de la familia de Elimelec, el cual se llamaba Boaz. </div>
<div id="Rth_2_2" style="display:none;" class="ver_select"><b>Rth 2:2</b>  Y Ruth la moabita dijo a Noemí: Te ruego que me dejes ir al campo, y recogeré espigas en pos de aquel a cuyos ojos hallare gracia. Y ella le respondió: Ve, hija mía. </div>
<div id="Rth_2_3" style="display:none;" class="ver_select"><b>Rth 2:3</b>  Fue, pues, y llegando, espigó en el campo en pos de los segadores; y aconteció por ventura, que la parte del campo era de Boaz, el cual era de la parentela de Elimelec. </div>
<div id="Rth_2_4" style="display:none;" class="ver_select"><b>Rth 2:4</b>  Y he aquí que Boaz vino de Belén, y dijo a los segadores: Jehová sea con vosotros. Y ellos respondieron: Jehová te bendiga. </div>
<div id="Rth_2_5" style="display:none;" class="ver_select"><b>Rth 2:5</b>  Y Boaz dijo a su siervo el mayordomo de los segadores: ¿De quién es esta joven? </div>
<div id="Rth_2_6" style="display:none;" class="ver_select"><b>Rth 2:6</b>  Y el siervo, mayordomo de los segadores, respondió y dijo: Es la joven de Moab, que volvió con Noemí de los campos de Moab; </div>
<div id="Rth_2_7" style="display:none;" class="ver_select"><b>Rth 2:7</b>  y ha dicho: Te ruego que me dejes recoger y juntar tras los segadores entre las gavillas: Entró, pues, y está desde por la mañana hasta ahora, menos un poco que se detuvo en casa. </div>
<div id="Rth_2_8" style="display:none;" class="ver_select"><b>Rth 2:8</b>  Entonces Boaz dijo a Ruth: Oye, hija mía, no vayas a espigar a otro campo, ni pases de aquí; y aquí estarás junto a mis criadas. </div>
<div id="Rth_2_9" style="display:none;" class="ver_select"><b>Rth 2:9</b>  Mira bien el campo que ellas siegan, y síguelas; porque yo he mandado a los criados que no te toquen. Y si tuvieres sed, ve a los vasos, y bebe del agua que sacan los criados. </div>
<div id="Rth_2_10" style="display:none;" class="ver_select"><b>Rth 2:10</b>  Ella entonces bajando su rostro se inclinó a tierra, y le dijo: ¿Por qué he hallado gracia en tus ojos para que tú me reconozcas, siendo yo extranjera? </div>
<div id="Rth_2_11" style="display:none;" class="ver_select"><b>Rth 2:11</b>  Y respondiendo Boaz, le dijo: Por cierto se me ha contado todo lo que has hecho con tu suegra después de la muerte de tu marido, y que dejando a tu padre y a tu madre y la tierra donde naciste, has venido a un pueblo que no conociste antes. </div>
<div id="Rth_2_12" style="display:none;" class="ver_select"><b>Rth 2:12</b>  Jehová recompense tu obra, y tu remuneración sea completa por Jehová Dios de Israel, que has venido a refugiarte bajo sus alas. </div>
<div id="Rth_2_13" style="display:none;" class="ver_select"><b>Rth 2:13</b>  Y ella dijo: Señor mío, halle yo gracia delante de tus ojos; porque me has consolado, y porque has hablado al corazón de tu sierva, no siendo yo como una de tus criadas. </div>
<div id="Rth_2_14" style="display:none;" class="ver_select"><b>Rth 2:14</b>  Y Boaz le dijo a la hora de comer: Acércate aquí, y come del pan, y moja tu bocado en el vinagre. Y ella se sentó junto a los segadores, y él le dio del potaje, y comió hasta que se sació y le sobró. </div>
<div id="Rth_2_15" style="display:none;" class="ver_select"><b>Rth 2:15</b>  Luego se levantó para espigar. Y Boaz mandó a sus criados, diciendo: Que recoja también espigas entre las gavillas, y no la avergoncéis; </div>
<div id="Rth_2_16" style="display:none;" class="ver_select"><b>Rth 2:16</b>  y dejad caer algunos de los manojos, y la dejaréis que los recoja, y no la reprendáis. </div>
<div id="Rth_2_17" style="display:none;" class="ver_select"><b>Rth 2:17</b>  Y espigó en el campo hasta la tarde, y desgranó lo que había recogido, y fue como un efa de cebada. </div>
<div id="Rth_2_18" style="display:none;" class="ver_select"><b>Rth 2:18</b>  Y lo tomó, y se fue a la ciudad; y su suegra vio lo que había recogido. Sacó también luego lo que le había sobrado después de quedar saciada, y se lo dio. </div>
<div id="Rth_2_19" style="display:none;" class="ver_select"><b>Rth 2:19</b>  Y le dijo su suegra: ¿Dónde has espigado hoy? ¿Y dónde has trabajado? Bendito sea el que te ha reconocido. Y ella contó a su suegra con quién había trabajado, y dijo: El nombre del varón con quien hoy he trabajado es Boaz. </div>
<div id="Rth_2_20" style="display:none;" class="ver_select"><b>Rth 2:20</b>  Y dijo Noemí a su nuera: Sea él bendito de Jehová, pues que no ha rehusado a los vivos la benevolencia que tuvo para con los finados. Y Noemí le dijo: Nuestro pariente es aquel varón, y uno de nuestros redentores. </div>
<div id="Rth_2_21" style="display:none;" class="ver_select"><b>Rth 2:21</b>  Y Ruth la moabita dijo: Además de esto me ha dicho: Júntate con mis criadas, hasta que hayan acabado toda mi siega. </div>
<div id="Rth_2_22" style="display:none;" class="ver_select"><b>Rth 2:22</b>  Y Noemí respondió a Ruth su nuera: Mejor es, hija mía, que salgas con sus criadas, y no que te encuentren en otro campo. </div>
<div id="Rth_2_23" style="display:none;" class="ver_select"><b>Rth 2:23</b>  Estuvo, pues, junto con las criadas de Boaz espigando, hasta que la siega de las cebadas y la de los trigos fue acabada; y habitó con su suegra. </div>
<div id="Rth_3_1" style="display:none;" class="ver_select"><b>Rth 3:1</b>  Y su suegra Noemí le dijo: Hija mía, ¿no he de buscarte un hogar, para que estés bien? </div>
<div id="Rth_3_2" style="display:none;" class="ver_select"><b>Rth 3:2</b>  ¿No es Boaz nuestro pariente, con cuyas mozas tú has estado? He aquí que esta noche él avienta la parva de las cebadas. </div>
<div id="Rth_3_3" style="display:none;" class="ver_select"><b>Rth 3:3</b>  Te lavarás pues, y te ungirás, y te pondrás tu vestido y bajarás a la era; pero no te darás a conocer al varón hasta que él haya acabado de comer y de beber. </div>
<div id="Rth_3_4" style="display:none;" class="ver_select"><b>Rth 3:4</b>  Y cuando él se acostare, observa tú el lugar donde él se acuesta, e irás, y descubrirás sus pies, y te acostarás allí; y él te dirá lo que debes hacer. </div>
<div id="Rth_3_5" style="display:none;" class="ver_select"><b>Rth 3:5</b>  Y ella le respondió: Haré todo lo que tú me dices. </div>
<div id="Rth_3_6" style="display:none;" class="ver_select"><b>Rth 3:6</b>  Descendió, pues, a la era, e hizo todo lo que su suegra le había mandado. </div>
<div id="Rth_3_7" style="display:none;" class="ver_select"><b>Rth 3:7</b>  Y cuando Boaz hubo comido y bebido, y su corazón estuvo contento, se retiró a dormir a un lado del montón de grano. Entonces ella vino calladamente, y le descubrió los pies y se acostó. </div>
<div id="Rth_3_8" style="display:none;" class="ver_select"><b>Rth 3:8</b>  Y aconteció, que a la media noche se estremeció aquel hombre, y palpó; y he aquí, la mujer que estaba acostada a sus pies. </div>
<div id="Rth_3_9" style="display:none;" class="ver_select"><b>Rth 3:9</b>  Entonces él dijo: ¿Quién eres? Y ella respondió: Yo soy Ruth tu sierva; extiende el borde de tu capa sobre tu sierva, por cuanto eres pariente redentor. </div>
<div id="Rth_3_10" style="display:none;" class="ver_select"><b>Rth 3:10</b>  Y él dijo: Bendita seas tú de Jehová, hija mía; pues has hecho mejor tu postrera gracia que la primera, no yendo tras los jóvenes, sean pobres o ricos. </div>
<div id="Rth_3_11" style="display:none;" class="ver_select"><b>Rth 3:11</b>  Ahora, pues, no temas, hija mía: yo haré contigo lo que me pidas, pues toda la gente de mi pueblo sabe que eres una mujer virtuosa. </div>
<div id="Rth_3_12" style="display:none;" class="ver_select"><b>Rth 3:12</b>  Y ahora, aunque es cierto que yo soy tu pariente redentor, con todo eso hay un pariente redentor más cercano que yo. </div>
<div id="Rth_3_13" style="display:none;" class="ver_select"><b>Rth 3:13</b>  Quédate esta noche, y cuando sea de día, si él te redimiere, bien, que te redima; mas si él no te quisiere redimir, yo te redimiré, vive Jehová. Descansa, pues, hasta la mañana. </div>
<div id="Rth_3_14" style="display:none;" class="ver_select"><b>Rth 3:14</b>  Y ella durmió a sus pies hasta la mañana, y se levantó antes que alguno pudiese reconocer al otro. Y él dijo: Que no se sepa que vino mujer a la era. </div>
<div id="Rth_3_15" style="display:none;" class="ver_select"><b>Rth 3:15</b>  Después le dijo: Dame el lienzo que traes sobre ti, y sostenlo. Y sosteniéndolo ella, él midió seis medidas de cebada, y las puso sobre ella; y ella se fue a la ciudad. </div>
<div id="Rth_3_16" style="display:none;" class="ver_select"><b>Rth 3:16</b>  Y cuando llegó a donde estaba su suegra, ésta le dijo: ¿Qué, pues, hija mía? Y ella le contó todo lo que aquel varón había hecho por ella. </div>
<div id="Rth_3_17" style="display:none;" class="ver_select"><b>Rth 3:17</b>  Y dijo: Estas seis medidas de cebada me dio, diciéndome: Para que no vayas a tu suegra con las manos vacías. </div>
<div id="Rth_3_18" style="display:none;" class="ver_select"><b>Rth 3:18</b>  Entonces Noemí dijo: Reposa, hija mía, hasta que sepas cómo termina esto; porque aquel hombre no descansará hasta que concluya el asunto hoy. </div>
<div id="Rth_4_1" style="display:none;" class="ver_select"><b>Rth 4:1</b>  Y Boaz subió a la puerta y se sentó allí; y he aquí pasaba aquel pariente redentor del cual Boaz había hablado, y le dijo: Eh, fulano, ven acá y siéntate. Y él vino, y se sentó. </div>
<div id="Rth_4_2" style="display:none;" class="ver_select"><b>Rth 4:2</b>  Entonces él tomó diez varones de los ancianos de la ciudad, y dijo: Sentaos aquí. Y ellos se sentaron. </div>
<div id="Rth_4_3" style="display:none;" class="ver_select"><b>Rth 4:3</b>  Luego dijo al pariente redentor: Noemí, que ha vuelto del campo de Moab, vende una parte de las tierras que tuvo nuestro hermano Elimelec; </div>
<div id="Rth_4_4" style="display:none;" class="ver_select"><b>Rth 4:4</b>  y yo decidí hacértelo saber, y decirte que la tomes delante de los que están aquí sentados, y delante de los ancianos de mi pueblo. Si quieres redimir, redime; y si no quieres redimir, dímelo para que yo lo sepa; porque no hay otro que redima sino tú, y yo después de ti. Y él respondió: Yo redimiré. </div>
<div id="Rth_4_5" style="display:none;" class="ver_select"><b>Rth 4:5</b>  Entonces replicó Boaz: El mismo día que compres las tierras de mano de Noemí, debes tomar también a Ruth la moabita, esposa del difunto, para que restaures el nombre del muerto sobre su heredad. </div>
<div id="Rth_4_6" style="display:none;" class="ver_select"><b>Rth 4:6</b>  Y respondió el pariente: No puedo redimir para mí, porque dañaría mi heredad; redime tú, usando de mi derecho, porque yo no podré redimir. </div>
<div id="Rth_4_7" style="display:none;" class="ver_select"><b>Rth 4:7</b>  Y en tiempos pasados había esta costumbre en Israel tocante a la redención o contrato, que para confirmar cualquier asunto, uno se quitaba el zapato y lo daba a su compañero; y éste  era el testimonio en Israel. </div>
<div id="Rth_4_8" style="display:none;" class="ver_select"><b>Rth 4:8</b>  Entonces el pariente dijo a Boaz: Tómalo tú. Y se quitó su zapato. </div>
<div id="Rth_4_9" style="display:none;" class="ver_select"><b>Rth 4:9</b>  Y Boaz dijo a los ancianos y a todo el pueblo: Vosotros sois testigos hoy de que tomo todas las cosas que fueron de Elimelec, y todo lo que fue de Quilión y de Mahalón, de mano de Noemí. </div>
<div id="Rth_4_10" style="display:none;" class="ver_select"><b>Rth 4:10</b>  Y que también tomo por mi esposa a Ruth la moabita, esposa de Mahalón, para restaurar el nombre del difunto sobre su heredad, para que el nombre del muerto no se borre de entre sus hermanos y de la puerta de su lugar. Vosotros sois testigos hoy. </div>
<div id="Rth_4_11" style="display:none;" class="ver_select"><b>Rth 4:11</b>  Y dijeron todos los del pueblo que estaban a la puerta con los ancianos: Testigos somos. Jehová haga a la mujer que entra en tu casa como a Raquel y a Lea, las cuales edificaron la casa de Israel; y tú seas ilustre en Efrata, y seas de renombre en Belén; </div>
<div id="Rth_4_12" style="display:none;" class="ver_select"><b>Rth 4:12</b>  Y de la simiente que Jehová te diere de esta joven, sea tu casa como la casa de Fares, el que Tamar dio a luz a Judá. </div>
<div id="Rth_4_13" style="display:none;" class="ver_select"><b>Rth 4:13</b>  Boaz, pues, tomó a Ruth, y ella fue su esposa; y luego que entró a ella, Jehová le dio que concibiese y diese a luz un hijo. </div>
<div id="Rth_4_14" style="display:none;" class="ver_select"><b>Rth 4:14</b>  Y las mujeres decían a Noemí: Bendito sea Jehová, que hizo que no te faltase hoy pariente redentor, cuyo nombre será célebre en Israel. </div>
<div id="Rth_4_15" style="display:none;" class="ver_select"><b>Rth 4:15</b>  Y él será el restaurador de tu vida, y sustentará tu vejez; porque tu nuera, que te ama, y es de más valor para ti que siete hijos, lo ha dado a luz. </div>
<div id="Rth_4_16" style="display:none;" class="ver_select"><b>Rth 4:16</b>  Y Noemí tomó al niño y lo puso en su regazo, y le fue su aya. </div>
<div id="Rth_4_17" style="display:none;" class="ver_select"><b>Rth 4:17</b>  Y las vecinas le dieron un nombre, diciendo: A Noemí le ha nacido un hijo; y le llamaron Obed. Éste es el padre de Isaí, padre de David. </div>
<div id="Rth_4_18" style="display:none;" class="ver_select"><b>Rth 4:18</b>  Y éstas son las generaciones de Fares: Fares engendró a Hezrón; </div>
<div id="Rth_4_19" style="display:none;" class="ver_select"><b>Rth 4:19</b>  y Hezrón engendró a Ram, y Ram engendró a Aminadab; </div>
<div id="Rth_4_20" style="display:none;" class="ver_select"><b>Rth 4:20</b>  y Aminadab engendró a Naasón, y Naasón engendró a Salmón; </div>
<div id="Rth_4_21" style="display:none;" class="ver_select"><b>Rth 4:21</b>  y Salmón engendró a Boaz, y Boaz engendró a Obed; </div>
<div id="Rth_4_22" style="display:none;" class="ver_select"><b>Rth 4:22</b>  y Obed engendró a Isaí, e Isaí engendró a David. </div>
