<div id="Zec_1_1" style="display:none;" class="ver_select"><b>Zec 1:1</b>  En el mes octavo, en el año segundo de Darío, vino palabra de Jehová a Zacarías profeta, hijo de Berequías, hijo de Iddo, diciendo: </div>
<div id="Zec_1_2" style="display:none;" class="ver_select"><b>Zec 1:2</b>  Jehová está muy enojado contra vuestros padres. </div>
<div id="Zec_1_3" style="display:none;" class="ver_select"><b>Zec 1:3</b>  Por tanto, diles: Así dice Jehová de los ejércitos: Volveos a mí, dice Jehová de los ejércitos, y yo me volveré a vosotros, dice Jehová de los ejércitos. </div>
<div id="Zec_1_4" style="display:none;" class="ver_select"><b>Zec 1:4</b>  No seáis como vuestros padres, a los cuales hablaron los primeros profetas, diciendo: Así dice Jehová de los ejércitos: Volveos ahora de vuestros malos caminos, y de vuestras malas obras; pero no atendieron, ni me escucharon, dice Jehová. </div>
<div id="Zec_1_5" style="display:none;" class="ver_select"><b>Zec 1:5</b>  Vuestros padres, ¿dónde están? y los profetas ¿han de vivir para siempre? </div>
<div id="Zec_1_6" style="display:none;" class="ver_select"><b>Zec 1:6</b>  Pero mis palabras y mis ordenanzas que mandé a mis siervos los profetas, ¿no alcanzaron a vuestros padres? Por eso se volvieron ellos y dijeron: Así como Jehová de los ejércitos pensó hacer con nosotros conforme a nuestros caminos y conforme a nuestras obras, así ha hecho con nosotros. </div>
<div id="Zec_1_7" style="display:none;" class="ver_select"><b>Zec 1:7</b>  El día veinticuatro del mes undécimo, que es el mes de Sebat, en el año segundo de Darío, vino palabra de Jehová al profeta Zacarías, hijo de Berequías, hijo de Iddo, diciendo: </div>
<div id="Zec_1_8" style="display:none;" class="ver_select"><b>Zec 1:8</b>  Vi de noche, y he aquí un varón que cabalgaba sobre un caballo alazán, el cual estaba entre los mirtos que había en la hondura; y detrás de él había caballos alazanes, overos y blancos. </div>
<div id="Zec_1_9" style="display:none;" class="ver_select"><b>Zec 1:9</b>  Entonces dije: ¿Qué son éstos, Señor mío? Y me dijo el Ángel que hablaba conmigo: Yo te enseñaré qué son éstos. </div>
<div id="Zec_1_10" style="display:none;" class="ver_select"><b>Zec 1:10</b>  Y aquel varón que estaba entre los mirtos respondió, y dijo: Éstos son los que Jehová ha enviado a recorrer la tierra. </div>
<div id="Zec_1_11" style="display:none;" class="ver_select"><b>Zec 1:11</b>  Y ellos respondieron al Ángel de Jehová que estaba entre los mirtos, y dijeron: Hemos recorrido la tierra, y he aquí toda la tierra está reposada y quieta. </div>
<div id="Zec_1_12" style="display:none;" class="ver_select"><b>Zec 1:12</b>  Y respondió el Ángel de Jehová, y dijo: Oh Jehová de los ejércitos, ¿hasta cuándo no tendrás piedad de Jerusalén, y de las ciudades de Judá, con las cuales has estado indignado estos setenta años? </div>
<div id="Zec_1_13" style="display:none;" class="ver_select"><b>Zec 1:13</b>  Y Jehová respondió buenas palabras, palabras consoladoras, al Ángel que hablaba conmigo. </div>
<div id="Zec_1_14" style="display:none;" class="ver_select"><b>Zec 1:14</b>  Y me dijo el Ángel que hablaba conmigo: Clama, diciendo: Así dice Jehová de los ejércitos: Estoy celoso por Jerusalén y por Sión, con gran celo: </div>
<div id="Zec_1_15" style="display:none;" class="ver_select"><b>Zec 1:15</b>  Y estoy muy indignado contra las naciones que están reposadas; porque cuando yo estaba enojado un poco, ellos ayudaron para el mal. </div>
<div id="Zec_1_16" style="display:none;" class="ver_select"><b>Zec 1:16</b>  Por tanto, así dice Jehová: Yo me he vuelto a Jerusalén con misericordia; en ella será edificada mi casa, dice Jehová de los ejércitos, y el cordel será tendido sobre Jerusalén. </div>
<div id="Zec_1_17" style="display:none;" class="ver_select"><b>Zec 1:17</b>  Clama aún, diciendo: Así dice Jehová de los ejércitos: Aún serán ensanchadas mis ciudades por la abundancia del bien; y aún consolará Jehová a Sión, y escogerá todavía a Jerusalén. </div>
<div id="Zec_1_18" style="display:none;" class="ver_select"><b>Zec 1:18</b>  Después alcé mis ojos y miré, y he aquí cuatro cuernos. </div>
<div id="Zec_1_19" style="display:none;" class="ver_select"><b>Zec 1:19</b>  Y dije al Ángel que hablaba conmigo: ¿Qué son éstos? Y me respondió: Éstos son los cuernos que dispersaron a Judá, a Israel y a Jerusalén. </div>
<div id="Zec_1_20" style="display:none;" class="ver_select"><b>Zec 1:20</b>  Me mostró luego Jehová cuatro carpinteros. </div>
<div id="Zec_1_21" style="display:none;" class="ver_select"><b>Zec 1:21</b>  Y yo dije: ¿Qué vienen a hacer éstos? Y me respondió, diciendo: Éstos son los cuernos que dispersaron a Judá, tanto que ninguno alzó su cabeza; mas éstos han venido para hacerlos temblar, para derribar los cuernos de las naciones, que alzaron el cuerno sobre la tierra de Judá para dispersarla. </div>
<div id="Zec_2_1" style="display:none;" class="ver_select"><b>Zec 2:1</b>  Alcé después mis ojos, y miré y he aquí un varón que tenía en su mano un cordel de medir. </div>
<div id="Zec_2_2" style="display:none;" class="ver_select"><b>Zec 2:2</b>  Y le dije: ¿A dónde vas? Y Él me respondió: A medir a Jerusalén, para ver cuánta es su anchura, y cuánta su longitud. </div>
<div id="Zec_2_3" style="display:none;" class="ver_select"><b>Zec 2:3</b>  Y he aquí, salía aquel Ángel que hablaba conmigo, y otro ángel le salió al encuentro, </div>
<div id="Zec_2_4" style="display:none;" class="ver_select"><b>Zec 2:4</b>  y le dijo: Corre, habla a este joven, diciendo: Sin muros será habitada Jerusalén a causa de la multitud de hombres y de ganado en medio de ella. </div>
<div id="Zec_2_5" style="display:none;" class="ver_select"><b>Zec 2:5</b>  Yo seré para ella, dice Jehová, muro de fuego en derredor, y seré la gloria en medio de ella. </div>
<div id="Zec_2_6" style="display:none;" class="ver_select"><b>Zec 2:6</b>  Eh, eh, huid de la tierra del norte, dice Jehová, pues por los cuatro vientos de los cielos os esparcí, dice Jehová. </div>
<div id="Zec_2_7" style="display:none;" class="ver_select"><b>Zec 2:7</b>  Oh Sión, la que moras con la hija de Babilonia, escápate. </div>
<div id="Zec_2_8" style="display:none;" class="ver_select"><b>Zec 2:8</b>  Porque así dice Jehová de los ejércitos: Después de la gloria Él me ha enviado a las naciones que os despojaron; porque el que os toca, toca a la niña de su ojo. </div>
<div id="Zec_2_9" style="display:none;" class="ver_select"><b>Zec 2:9</b>  Porque he aquí yo alzo mi mano sobre ellos, y serán despojo a sus siervos, y sabréis que Jehová de los ejércitos me ha enviado. </div>
<div id="Zec_2_10" style="display:none;" class="ver_select"><b>Zec 2:10</b>  Canta y alégrate, hija de Sión: porque he aquí vengo, y moraré en medio de ti, dice Jehová. </div>
<div id="Zec_2_11" style="display:none;" class="ver_select"><b>Zec 2:11</b>  Y muchas naciones se unirán a Jehová en aquel día, y serán mi pueblo, y moraré en medio de ti; y entonces conocerás que Jehová de los ejércitos me ha enviado a ti. </div>
<div id="Zec_2_12" style="display:none;" class="ver_select"><b>Zec 2:12</b>  Y Jehová poseerá a Judá su heredad en la tierra santa, y escogerá aún a Jerusalén. </div>
<div id="Zec_2_13" style="display:none;" class="ver_select"><b>Zec 2:13</b>  Calle toda carne delante de Jehová, porque Él se ha levantado de su santa morada. </div>
<div id="Zec_3_1" style="display:none;" class="ver_select"><b>Zec 3:1</b>  Y me mostró a Josué, el sumo sacerdote, el cual estaba delante del Ángel de Jehová; y Satanás estaba a su mano derecha para serle adversario. </div>
<div id="Zec_3_2" style="display:none;" class="ver_select"><b>Zec 3:2</b>  Y dijo Jehová a Satanás: Jehová te reprenda, oh Satanás; Jehová, que ha escogido a Jerusalén, te reprenda. ¿No es éste un tizón arrebatado del fuego? </div>
<div id="Zec_3_3" style="display:none;" class="ver_select"><b>Zec 3:3</b>  Y Josué estaba vestido de vestiduras viles, y estaba delante del Ángel. </div>
<div id="Zec_3_4" style="display:none;" class="ver_select"><b>Zec 3:4</b>  Y habló el Ángel, y mandó a los que estaban delante de Él, diciendo: Quitadle esas vestiduras viles. Y a él dijo: Mira que he hecho pasar de ti tu pecado, y te vestiré con ropas de gala. </div>
<div id="Zec_3_5" style="display:none;" class="ver_select"><b>Zec 3:5</b>  Después dijo: Pongan mitra limpia sobre su cabeza. Y pusieron una mitra limpia sobre su cabeza, y le vistieron las ropas. Y el Ángel de Jehová estaba en pie. </div>
<div id="Zec_3_6" style="display:none;" class="ver_select"><b>Zec 3:6</b>  Y el Ángel de Jehová amonestó a Josué, diciendo: </div>
<div id="Zec_3_7" style="display:none;" class="ver_select"><b>Zec 3:7</b>  Así dice Jehová de los ejércitos: Si anduvieres por mis caminos, y si guardares mi ordenanza, también tú gobernarás mi casa, también tú guardarás mis atrios, y entre éstos que aquí están te daré plaza. </div>
<div id="Zec_3_8" style="display:none;" class="ver_select"><b>Zec 3:8</b>  Escucha pues, ahora, Josué sumo sacerdote, tú y tus compañeros que se sientan delante de ti; porque son varones admirables: He aquí, yo traigo a mi siervo, el Renuevo. </div>
<div id="Zec_3_9" style="display:none;" class="ver_select"><b>Zec 3:9</b>  Porque he aquí aquella piedra que puse delante de Josué; sobre esta única piedra hay siete ojos; he aquí, yo grabaré su escultura, dice Jehová de los ejércitos, y quitaré el pecado de la tierra en un día. </div>
<div id="Zec_3_10" style="display:none;" class="ver_select"><b>Zec 3:10</b>  En aquel día, dice Jehová de los ejércitos, cada uno de vosotros llamará a su compañero debajo de la vid, y debajo de la higuera. </div>
<div id="Zec_4_1" style="display:none;" class="ver_select"><b>Zec 4:1</b>  Y volvió el Ángel que hablaba conmigo, y me despertó como un hombre que es despertado de su sueño. </div>
<div id="Zec_4_2" style="display:none;" class="ver_select"><b>Zec 4:2</b>  Y me dijo: ¿Qué ves? Y respondí: He mirado, y he aquí un candelero todo de oro, con un tazón sobre la parte superior, y sus siete lámparas encima del candelero; y siete tubos para las lámparas que están encima de él; </div>
<div id="Zec_4_3" style="display:none;" class="ver_select"><b>Zec 4:3</b>  Y sobre él dos olivos, uno a la derecha del tazón, y el otro a su izquierda. </div>
<div id="Zec_4_4" style="display:none;" class="ver_select"><b>Zec 4:4</b>  Proseguí, y hablé a aquel Ángel que hablaba conmigo, diciendo: ¿Qué es esto, mi Señor? </div>
<div id="Zec_4_5" style="display:none;" class="ver_select"><b>Zec 4:5</b>  Y el Ángel que hablaba conmigo respondió, y me dijo: ¿No sabes qué es esto? Y dije: No, mi Señor. </div>
<div id="Zec_4_6" style="display:none;" class="ver_select"><b>Zec 4:6</b>  Entonces respondió y me habló, diciendo: Ésta es palabra de Jehová a Zorobabel, que dice: No con ejército, ni con fuerza, sino con mi Espíritu, dice Jehová de los ejércitos. </div>
<div id="Zec_4_7" style="display:none;" class="ver_select"><b>Zec 4:7</b>  ¿Quién eres tú, oh gran monte? Delante de Zorobabel serás reducido a llanura; él sacará la primera piedra con aclamaciones, diciendo: Gracia, gracia a ella. </div>
<div id="Zec_4_8" style="display:none;" class="ver_select"><b>Zec 4:8</b>  Entonces la palabra de Jehová vino a mí, diciendo: </div>
<div id="Zec_4_9" style="display:none;" class="ver_select"><b>Zec 4:9</b>  Las manos de Zorobabel echarán el fundamento a esta casa, y sus manos la acabarán; y conocerás que Jehová de los ejércitos me envió a vosotros. </div>
<div id="Zec_4_10" style="display:none;" class="ver_select"><b>Zec 4:10</b>  Porque, ¿quién ha menospreciado el día de las pequeñeces? Pues se alegrarán, y verán la plomada en la mano de Zorobabel. Estos siete son los ojos de Jehová que recorren por toda la tierra. </div>
<div id="Zec_4_11" style="display:none;" class="ver_select"><b>Zec 4:11</b>  Hablé más, y le dije: ¿Qué significan estos dos olivos a la derecha del candelero, y a su izquierda? </div>
<div id="Zec_4_12" style="display:none;" class="ver_select"><b>Zec 4:12</b>  Hablé aún de nuevo, y le dije: ¿Qué significan las dos ramas de olivo que por medio de dos tubos de oro vierten de sí aceite como oro? </div>
<div id="Zec_4_13" style="display:none;" class="ver_select"><b>Zec 4:13</b>  Y me respondió, diciendo: ¿No sabes qué es esto? Y dije: No, mi Señor. </div>
<div id="Zec_4_14" style="display:none;" class="ver_select"><b>Zec 4:14</b>  Entonces Él dijo: Éstos son los dos ungidos que están delante del Señor de toda la tierra. </div>
<div id="Zec_5_1" style="display:none;" class="ver_select"><b>Zec 5:1</b>  Y me volví, y alcé mis ojos, y miré, y he aquí un rollo que volaba. </div>
<div id="Zec_5_2" style="display:none;" class="ver_select"><b>Zec 5:2</b>  Y me dijo: ¿Qué ves? Y respondí: Veo un rollo que vuela, de veinte codos de largo, y diez codos de ancho. </div>
<div id="Zec_5_3" style="display:none;" class="ver_select"><b>Zec 5:3</b>  Me dijo entonces: Ésta es la maldición que sale sobre la faz de toda la tierra; porque todo aquel que hurta será destruido según lo escrito en un lado, y todo aquel que jura será destruido según lo escrito en el otro lado. </div>
<div id="Zec_5_4" style="display:none;" class="ver_select"><b>Zec 5:4</b>  Yo la haré salir, dice Jehová de los ejércitos, y vendrá a la casa del ladrón, y a la casa del que jura falsamente en mi nombre; y permanecerá en medio de su casa, y la consumirá, con su madera y sus piedras. </div>
<div id="Zec_5_5" style="display:none;" class="ver_select"><b>Zec 5:5</b>  Y salió aquel Ángel que hablaba conmigo, y me dijo: Alza ahora tus ojos, y mira qué es esto que sale. </div>
<div id="Zec_5_6" style="display:none;" class="ver_select"><b>Zec 5:6</b>  Y dije: ¿Qué es? Y Él dijo: Éste es un efa que sale. Además dijo: Ésta es la semejanza de ellos en toda la tierra. </div>
<div id="Zec_5_7" style="display:none;" class="ver_select"><b>Zec 5:7</b>  Y he aquí, levantaron un talento de plomo, y una mujer estaba sentada en medio de aquel efa. </div>
<div id="Zec_5_8" style="display:none;" class="ver_select"><b>Zec 5:8</b>  Y Él dijo: Ésta es la maldad; y la echó dentro del efa, y echó la masa de plomo en la boca del efa. </div>
<div id="Zec_5_9" style="display:none;" class="ver_select"><b>Zec 5:9</b>  Alcé luego mis ojos, y miré, y he aquí dos mujeres que salían, y traían viento en sus alas, y tenían alas como de cigüeña, y alzaron el efa entre la tierra y el cielo. </div>
<div id="Zec_5_10" style="display:none;" class="ver_select"><b>Zec 5:10</b>  Y dije al Ángel que hablaba conmigo: ¿A dónde llevan el efa? </div>
<div id="Zec_5_11" style="display:none;" class="ver_select"><b>Zec 5:11</b>  Y Él me respondió: Para que le sea edificada casa en tierra de Sinar; y será establecido y puesto allí sobre su base. </div>
<div id="Zec_6_1" style="display:none;" class="ver_select"><b>Zec 6:1</b>  Y me volví, y alcé mis ojos y miré, y he aquí cuatro carros que salían de entre dos montes; y aquellos montes eran montes de bronce. </div>
<div id="Zec_6_2" style="display:none;" class="ver_select"><b>Zec 6:2</b>  En el primer carro había caballos alazanes, y en el segundo carro caballos negros, </div>
<div id="Zec_6_3" style="display:none;" class="ver_select"><b>Zec 6:3</b>  y en el tercer carro caballos blancos, y en el cuarto carro caballos overos bayos rodados. </div>
<div id="Zec_6_4" style="display:none;" class="ver_select"><b>Zec 6:4</b>  Respondí entonces, y dije al Ángel que hablaba conmigo: Señor mío, ¿qué es esto? </div>
<div id="Zec_6_5" style="display:none;" class="ver_select"><b>Zec 6:5</b>  Y el Ángel me respondió, y me dijo: Éstos son los cuatro espíritus de los cielos, que salen después de presentarse ante el Señor de toda la tierra. </div>
<div id="Zec_6_6" style="display:none;" class="ver_select"><b>Zec 6:6</b>  Y  los caballos negros que estaban allí, salían hacia la tierra del norte; y los blancos salían tras ellos; y lo overos salían hacia la tierra del sur. </div>
<div id="Zec_6_7" style="display:none;" class="ver_select"><b>Zec 6:7</b>  Y los bayos salieron, y se afanaron por ir a recorrer la tierra. Y dijo: Id, recorred la tierra. Y recorrieron la tierra. </div>
<div id="Zec_6_8" style="display:none;" class="ver_select"><b>Zec 6:8</b>  Luego me llamó, y me habló diciendo: Mira, los que salieron hacia la tierra del norte hicieron reposar mi Espíritu en la tierra del norte. </div>
<div id="Zec_6_9" style="display:none;" class="ver_select"><b>Zec 6:9</b>  Y vino a mí palabra de Jehová, diciendo: </div>
<div id="Zec_6_10" style="display:none;" class="ver_select"><b>Zec 6:10</b>  Toma de los del cautiverio, de Heldai, y de Tobías, y de Jedaías, los cuales volvieron de Babilonia; y vendrás tú en aquel día, y entrarás en casa de Josías hijo de Sofonías. </div>
<div id="Zec_6_11" style="display:none;" class="ver_select"><b>Zec 6:11</b>  Tomarás, pues, plata y oro, y harás coronas, y las pondrás en la cabeza del sumo sacerdote Josué, hijo de Josadac; </div>
<div id="Zec_6_12" style="display:none;" class="ver_select"><b>Zec 6:12</b>  y le hablarás, diciendo: Así ha hablado Jehová de los ejércitos, diciendo: He aquí el varón cuyo nombre es El Renuevo, el cual brotará de su lugar, y edificará el templo de Jehová: </div>
<div id="Zec_6_13" style="display:none;" class="ver_select"><b>Zec 6:13</b>  Él edificará el templo de Jehová, y Él llevará gloria y se sentará y dominará en su trono; y será sacerdote sobre su trono, y consejo de paz habrá entre ambos. </div>
<div id="Zec_6_14" style="display:none;" class="ver_select"><b>Zec 6:14</b>  Y Helem, y Tobías, y Jedaías, y Hen, hijo de Sofonías, tendrán coronas por memorial en el templo de Jehová. </div>
<div id="Zec_6_15" style="display:none;" class="ver_select"><b>Zec 6:15</b>  Y los que están lejos vendrán y edificarán en el templo de Jehová, y conoceréis que Jehová de los ejércitos me ha enviado a vosotros. Y esto sucederá si con diligencia obedecéis la voz de Jehová vuestro Dios. </div>
<div id="Zec_7_1" style="display:none;" class="ver_select"><b>Zec 7:1</b>  Y aconteció en el año cuarto del rey Darío, que vino palabra de Jehová a Zacarías a los cuatro días del mes noveno, que es Quisleu; </div>
<div id="Zec_7_2" style="display:none;" class="ver_select"><b>Zec 7:2</b>  cuando fue enviado a la casa de Dios, Sarezer, con Regem-melec y sus hombres, a implorar el favor de Jehová, </div>
<div id="Zec_7_3" style="display:none;" class="ver_select"><b>Zec 7:3</b>  y a hablar a los sacerdotes que estaban en la casa de Jehová de los ejércitos, y a los profetas, diciendo: ¿Lloraremos en el mes quinto? ¿Haremos abstinencia como hemos hecho ya algunos años? </div>
<div id="Zec_7_4" style="display:none;" class="ver_select"><b>Zec 7:4</b>  Entonces vino a mí palabra de Jehová de los ejércitos, diciendo: </div>
<div id="Zec_7_5" style="display:none;" class="ver_select"><b>Zec 7:5</b>  Habla a todo el pueblo del país, y a los sacerdotes, diciendo: Cuando ayunasteis y llorasteis en el quinto y en el séptimo mes estos setenta años, ¿habéis ayunado para mí? </div>
<div id="Zec_7_6" style="display:none;" class="ver_select"><b>Zec 7:6</b>  Y cuando comisteis y bebisteis, ¿no comisteis y bebisteis para vosotros mismos? </div>
<div id="Zec_7_7" style="display:none;" class="ver_select"><b>Zec 7:7</b>  ¿No oiréis las palabras que proclamó Jehová por medio de los primeros profetas, cuando Jerusalén estaba habitada y quieta, y sus ciudades en sus alrededores, y el Neguev y la llanura estaban habitados? </div>
<div id="Zec_7_8" style="display:none;" class="ver_select"><b>Zec 7:8</b>  Y vino palabra de Jehová a Zacarías, diciendo: </div>
<div id="Zec_7_9" style="display:none;" class="ver_select"><b>Zec 7:9</b>  Así habló Jehová de los ejércitos, diciendo: Juzgad juicio verdadero, y haced misericordia y piedad cada cual con su hermano: </div>
<div id="Zec_7_10" style="display:none;" class="ver_select"><b>Zec 7:10</b>  No oprimáis a la viuda, ni al huérfano, ni al extranjero, ni al pobre; ni ninguno piense mal en su corazón contra su hermano. </div>
<div id="Zec_7_11" style="display:none;" class="ver_select"><b>Zec 7:11</b>  Pero no quisieron escuchar, antes volvieron la espalda, y taparon sus oídos para no oír; </div>
<div id="Zec_7_12" style="display:none;" class="ver_select"><b>Zec 7:12</b>  Y pusieron su corazón como diamante, para no oír la ley ni las palabras que Jehová de los ejércitos enviaba por su Espíritu, por medio de los profetas primeros; vino, por tanto, grande ira de parte de Jehová de los ejércitos. </div>
<div id="Zec_7_13" style="display:none;" class="ver_select"><b>Zec 7:13</b>  Y aconteció que como Él clamó, y no escucharon, así ellos clamaron, y yo no escuché, dice Jehová de los ejércitos; </div>
<div id="Zec_7_14" style="display:none;" class="ver_select"><b>Zec 7:14</b>  Antes los esparcí con torbellino por todas las naciones que ellos no conocían, y la tierra fue desolada tras ellos, sin quedar quien fuese ni viniese; pues convirtieron en ruinas la tierra deseable. </div>
<div id="Zec_8_1" style="display:none;" class="ver_select"><b>Zec 8:1</b>  Y vino a mí palabra de Jehová de los ejércitos, diciendo: </div>
<div id="Zec_8_2" style="display:none;" class="ver_select"><b>Zec 8:2</b>  Así dice Jehová de los ejércitos: Yo he celado a Sión con grande celo, y con grande ira la celé. </div>
<div id="Zec_8_3" style="display:none;" class="ver_select"><b>Zec 8:3</b>  Así dice Jehová: Yo he retornado a Sión, y moraré en medio de Jerusalén: y Jerusalén se llamará Ciudad de la Verdad, y el monte de Jehová de los ejércitos, Monte de Santidad. </div>
<div id="Zec_8_4" style="display:none;" class="ver_select"><b>Zec 8:4</b>  Así dice Jehová de los ejércitos: Aún han de morar ancianos y ancianas en las plazas de Jerusalén, y cada cual con bordón en su mano por la multitud de los días. </div>
<div id="Zec_8_5" style="display:none;" class="ver_select"><b>Zec 8:5</b>  Y las calles de la ciudad se llenarán de muchachos y muchachas que jugarán en sus calles. </div>
<div id="Zec_8_6" style="display:none;" class="ver_select"><b>Zec 8:6</b>  Así dice Jehová de los ejércitos: Si esto parecerá maravilloso a los ojos del remanente de este pueblo en aquellos días, ¿deberá también ser maravilloso delante de mis ojos? dice Jehová de los ejércitos. </div>
<div id="Zec_8_7" style="display:none;" class="ver_select"><b>Zec 8:7</b>  Así dice Jehová de los ejércitos: He aquí, yo salvo a mi pueblo de la tierra del oriente, y de la tierra del poniente; </div>
<div id="Zec_8_8" style="display:none;" class="ver_select"><b>Zec 8:8</b>  Y los traeré, y habitarán en medio de Jerusalén; y ellos serán mi pueblo, y yo seré su Dios en verdad y en justicia. </div>
<div id="Zec_8_9" style="display:none;" class="ver_select"><b>Zec 8:9</b>  Así dice Jehová de los ejércitos: Fortaleced vuestras manos, vosotros los que oís en estos días estas palabras de la boca de los profetas, desde el día que se echó el cimiento de la casa de Jehová de los ejércitos, para edificar el templo. </div>
<div id="Zec_8_10" style="display:none;" class="ver_select"><b>Zec 8:10</b>  Porque antes de estos días no había paga para el hombre, ni paga para la bestia, ni había paz alguna para el que entraba ni para el que salía, a causa de la aflicción; y yo puse a todo hombre, cada cual contra su compañero. </div>
<div id="Zec_8_11" style="display:none;" class="ver_select"><b>Zec 8:11</b>  Mas ahora no haré con el remanente de este pueblo como en los días pasados, dice Jehová de los ejércitos. </div>
<div id="Zec_8_12" style="display:none;" class="ver_select"><b>Zec 8:12</b>  Porque habrá simiente de paz; la vid dará su fruto, y la tierra dará su producto, y los cielos darán su rocío; y haré que el remanente de este pueblo posea todo esto. </div>
<div id="Zec_8_13" style="display:none;" class="ver_select"><b>Zec 8:13</b>  Y será que como fuisteis maldición entre las naciones, oh casa de Judá y casa de Israel, así os salvaré, y seréis bendición. No temáis, mas esfuércense vuestras manos. </div>
<div id="Zec_8_14" style="display:none;" class="ver_select"><b>Zec 8:14</b>  Porque así dice Jehová de los ejércitos: Como pensé haceros mal cuando vuestros padres me provocaron a ira, dice Jehová de los ejércitos, y no me arrepentí; </div>
<div id="Zec_8_15" style="display:none;" class="ver_select"><b>Zec 8:15</b>  así otra vez he pensado hacer bien a Jerusalén y a la casa de Judá en estos días. No temáis. </div>
<div id="Zec_8_16" style="display:none;" class="ver_select"><b>Zec 8:16</b>  Éstas son las cosas que habéis de hacer: Hablad verdad cada cual con su prójimo; juzgad con verdad y juicio de paz en vuestras puertas. </div>
<div id="Zec_8_17" style="display:none;" class="ver_select"><b>Zec 8:17</b>  Y ninguno de vosotros piense mal en su corazón contra su prójimo, ni améis juramento falso; porque todas éstas son cosas que aborrezco, dice Jehová. </div>
<div id="Zec_8_18" style="display:none;" class="ver_select"><b>Zec 8:18</b>  Y vino a mí palabra de Jehová de los ejércitos, diciendo: </div>
<div id="Zec_8_19" style="display:none;" class="ver_select"><b>Zec 8:19</b>  Así dice Jehová de los ejércitos: El ayuno del cuarto mes, y el ayuno del quinto, y el ayuno del séptimo, y el ayuno del décimo, se convertirán en gozo y alegría para la casa de Judá, y en fiestas de regocijo. Amad, pues, la verdad y la paz. </div>
<div id="Zec_8_20" style="display:none;" class="ver_select"><b>Zec 8:20</b>  Así dice Jehová de los ejércitos: Aún vendrán pueblos, y moradores de muchas ciudades; </div>
<div id="Zec_8_21" style="display:none;" class="ver_select"><b>Zec 8:21</b>  Y vendrán los habitantes de una ciudad a otra, y dirán: Vamos a implorar el favor de Jehová, y a buscar a Jehová de los ejércitos. Yo también iré. </div>
<div id="Zec_8_22" style="display:none;" class="ver_select"><b>Zec 8:22</b>  Y vendrán muchos pueblos y fuertes naciones a buscar a Jehová de los ejércitos en Jerusalén, y a implorar el favor de Jehová. </div>
<div id="Zec_8_23" style="display:none;" class="ver_select"><b>Zec 8:23</b>  Así dice Jehová de los ejércitos: En aquellos días acontecerá que diez hombres de todas las lenguas de las naciones, trabarán del manto de un judío, diciendo: Iremos con vosotros, porque hemos oído que Dios está con vosotros. </div>
<div id="Zec_9_1" style="display:none;" class="ver_select"><b>Zec 9:1</b>  Carga de la palabra de Jehová contra la tierra de Hadrac, y de Damasco, su reposo; cuando los ojos de los hombres y de todas las tribus de Israel se vuelvan a Jehová. </div>
<div id="Zec_9_2" style="display:none;" class="ver_select"><b>Zec 9:2</b>  Y también Hamat tendrá término en ella; Tiro y Sidón, aunque muy sabias sean. </div>
<div id="Zec_9_3" style="display:none;" class="ver_select"><b>Zec 9:3</b>  Bien que Tiro se edificó fortaleza, y amontonó plata como polvo, y oro como lodo de las calles, </div>
<div id="Zec_9_4" style="display:none;" class="ver_select"><b>Zec 9:4</b>  he aquí, el Señor la empobrecerá, y herirá en el mar su fortaleza, y ella será consumida por el fuego. </div>
<div id="Zec_9_5" style="display:none;" class="ver_select"><b>Zec 9:5</b>  Ascalón verá, y temerá; Gaza también, y se dolerá en gran manera: asimismo Ecrón, porque su esperanza será confundida; y de Gaza perecerá el rey, y Ascalón no será habitada. </div>
<div id="Zec_9_6" style="display:none;" class="ver_select"><b>Zec 9:6</b>  Y un bastardo habitará en Asdod, y yo cortaré la soberbia de los filisteos; </div>
<div id="Zec_9_7" style="display:none;" class="ver_select"><b>Zec 9:7</b>  Y quitaré la sangre de su boca, y sus abominaciones de entre sus dientes, mas el que quedare, aun él será para nuestro Dios, y será como capitán en Judá, y Ecrón como el jebuseo. </div>
<div id="Zec_9_8" style="display:none;" class="ver_select"><b>Zec 9:8</b>  Y yo acamparé junto a mi casa a causa del ejército, a causa del que va y del que viene; y no pasará más sobre ellos el opresor; porque ahora he visto con mis ojos. </div>
<div id="Zec_9_9" style="display:none;" class="ver_select"><b>Zec 9:9</b>  Alégrate mucho, hija de Sión; da voces de júbilo, hija de Jerusalén: he aquí, tu Rey vendrá a ti, Él es justo y salvador, humilde, y cabalgando sobre un asno, sobre un pollino hijo de asna. </div>
<div id="Zec_9_10" style="display:none;" class="ver_select"><b>Zec 9:10</b>  Y de Efraín destruiré los carros, y los caballos de Jerusalén; y los arcos de guerra serán quebrados; y hablará paz a las naciones; y su señorío será de mar a mar, y desde el río hasta los confines de la tierra. </div>
<div id="Zec_9_11" style="display:none;" class="ver_select"><b>Zec 9:11</b>  Y tú también por la sangre de tu pacto serás salva; yo he sacado a tus presos de la cisterna en la que no hay agua. </div>
<div id="Zec_9_12" style="display:none;" class="ver_select"><b>Zec 9:12</b>  Volveos a la fortaleza, oh prisioneros de esperanza; hoy también os anuncio que os restauraré el doble. </div>
<div id="Zec_9_13" style="display:none;" class="ver_select"><b>Zec 9:13</b>  Porque he entesado para mí a Judá como arco, llené a Efraín; y despertaré tus hijos, oh Sión, contra tus hijos, oh Grecia, y te haré como espada de valiente. </div>
<div id="Zec_9_14" style="display:none;" class="ver_select"><b>Zec 9:14</b>  Y Jehová será visto sobre ellos, y su saeta saldrá como un relámpago; y Jehová el Señor tocará la trompeta, e irá con torbellinos del sur. </div>
<div id="Zec_9_15" style="display:none;" class="ver_select"><b>Zec 9:15</b>  Jehová de los ejércitos los defenderá, y ellos devorarán y subyugarán con piedras de la honda, y beberán y harán estrépito como embriagados de vino; y se llenarán como tazones, y como las esquinas del altar. </div>
<div id="Zec_9_16" style="display:none;" class="ver_select"><b>Zec 9:16</b>  Y los salvará en aquel día Jehová su Dios como rebaño de su pueblo; porque ellos serán como piedras de corona, enaltecidos como una insignia en su tierra. </div>
<div id="Zec_9_17" style="display:none;" class="ver_select"><b>Zec 9:17</b>  Porque ¡cuán grande es su bondad, y cuán grande su hermosura! El trigo alegrará a los jóvenes, y el vino nuevo a las doncellas. </div>
<div id="Zec_10_1" style="display:none;" class="ver_select"><b>Zec 10:1</b>  Pedid a Jehová lluvia en la estación tardía: Jehová hará relámpagos, y os dará lluvia abundante, y hierba en el campo a cada uno. </div>
<div id="Zec_10_2" style="display:none;" class="ver_select"><b>Zec 10:2</b>  Porque las imágenes han hablado vanidad, y los adivinos han visto mentira, y han hablado sueños vanos, en vano consuelan; por eso ellos vagan como ovejas, fueron afligidos porque no tenían pastor. </div>
<div id="Zec_10_3" style="display:none;" class="ver_select"><b>Zec 10:3</b>  Contra los pastores se ha encendido mi enojo, y castigaré a los machos cabríos; mas Jehová de los ejércitos visitará su rebaño, la casa de Judá, y los hará como su caballo de honor en la batalla. </div>
<div id="Zec_10_4" style="display:none;" class="ver_select"><b>Zec 10:4</b>  De él saldrá la piedra angular, de él la clavija, de él el arco de guerra, de él también todo opresor. </div>
<div id="Zec_10_5" style="display:none;" class="ver_select"><b>Zec 10:5</b>  Y serán como valientes, que en la batalla pisotean al enemigo en el lodo de las calles; y pelearán, porque Jehová será con ellos; y los que cabalgan en caballos serán avergonzados. </div>
<div id="Zec_10_6" style="display:none;" class="ver_select"><b>Zec 10:6</b>  Porque yo fortaleceré la casa de Judá, y guardaré la casa de José; y los volveré a traer porque tendré misericordia de ellos; y serán como si no los hubiera desechado; porque yo soy Jehová su Dios, y los oiré. </div>
<div id="Zec_10_7" style="display:none;" class="ver_select"><b>Zec 10:7</b>  Y será Efraín como valiente, y se alegrará su corazón como por el vino; sus hijos también verán y se alegrarán; su corazón se gozará en Jehová. </div>
<div id="Zec_10_8" style="display:none;" class="ver_select"><b>Zec 10:8</b>  Yo les silbaré y los reuniré, porque los he redimido; y se multiplicarán como antes fueron multiplicados. </div>
<div id="Zec_10_9" style="display:none;" class="ver_select"><b>Zec 10:9</b>  Y los sembraré entre los pueblos, aun en lejanos países se acordarán de mí; y vivirán con sus hijos, y volverán. </div>
<div id="Zec_10_10" style="display:none;" class="ver_select"><b>Zec 10:10</b>  Yo los traeré de la tierra de Egipto, y los recogeré de Asiria; y los traeré a la tierra de Galaad y del Líbano, y no les bastará. </div>
<div id="Zec_10_11" style="display:none;" class="ver_select"><b>Zec 10:11</b>  Y la tribulación pasará por el mar, y en el mar herirá las ondas, y se secarán todas las profundidades del río; y la soberbia de Asiria será derribada, y se perderá el cetro de Egipto. </div>
<div id="Zec_10_12" style="display:none;" class="ver_select"><b>Zec 10:12</b>  Y yo los fortaleceré en Jehová, y caminarán en su nombre, dice Jehová. </div>
<div id="Zec_11_1" style="display:none;" class="ver_select"><b>Zec 11:1</b>  Oh Líbano, abre tus puertas, y que el fuego devore tus cedros. </div>
<div id="Zec_11_2" style="display:none;" class="ver_select"><b>Zec 11:2</b>  Aúlla, oh ciprés, porque el cedro cayó, porque los poderosos son derribados. Aullad, alcornoques de Basán, porque el bosque espeso es derribado. </div>
<div id="Zec_11_3" style="display:none;" class="ver_select"><b>Zec 11:3</b>  Voz de aullido de pastores, porque su magnificencia es asolada; estruendo de rugidos de cachorros de leones, porque la soberbia del Jordán es destruida. </div>
<div id="Zec_11_4" style="display:none;" class="ver_select"><b>Zec 11:4</b>  Así dice Jehová mi Dios: Apacienta las ovejas de la matanza; </div>
<div id="Zec_11_5" style="display:none;" class="ver_select"><b>Zec 11:5</b>  a las cuales matan sus compradores, y no se tienen por culpables; y el que las vende, dice: Bendito sea Jehová, porque me he enriquecido; y sus propios pastores no tenían piedad de ellas. </div>
<div id="Zec_11_6" style="display:none;" class="ver_select"><b>Zec 11:6</b>  Por tanto, no tendré ya más piedad de los moradores de la tierra, dice Jehová: porque he aquí, yo entregaré los hombres, cada cual en mano de su compañero, y en mano de su rey; y herirán la tierra, y yo no los libraré de sus manos. </div>
<div id="Zec_11_7" style="display:none;" class="ver_select"><b>Zec 11:7</b>  Apacentaré, pues, las ovejas de la matanza, esto es, a vosotros los pobres del rebaño. Y tomé para mí dos cayados; al uno puse por nombre Hermosura, y al otro Lazos; y apacenté las ovejas. </div>
<div id="Zec_11_8" style="display:none;" class="ver_select"><b>Zec 11:8</b>  Y destruí a tres pastores en un mes, y mi alma los detestó; y también el alma de ellos me aborreció a mí. </div>
<div id="Zec_11_9" style="display:none;" class="ver_select"><b>Zec 11:9</b>  Y dije: No os apacentaré; la que ha de morir, que muera; y la que se ha de perder, que se pierda; y las que quedaren, que cada una coma la carne de su compañera. </div>
<div id="Zec_11_10" style="display:none;" class="ver_select"><b>Zec 11:10</b>  Tomé luego mi cayado Hermosura, y lo quebré, para deshacer mi pacto que concerté con todos los pueblos. </div>
<div id="Zec_11_11" style="display:none;" class="ver_select"><b>Zec 11:11</b>  Y fue deshecho en ese día, y así conocieron los pobres del rebaño que miraban a mí, que era la palabra de Jehová. </div>
<div id="Zec_11_12" style="display:none;" class="ver_select"><b>Zec 11:12</b>  Y les dije: Si os parece bien, dadme mi salario; y si no, dejadlo. Y pesaron por mi salario treinta piezas de plata. </div>
<div id="Zec_11_13" style="display:none;" class="ver_select"><b>Zec 11:13</b>  Y me dijo Jehová: Échalo al tesoro, ¡hermoso precio con que me han apreciado! Y tomé las treinta piezas de plata, y las eché al tesoro en la casa de Jehová. </div>
<div id="Zec_11_14" style="display:none;" class="ver_select"><b>Zec 11:14</b>  Quebré luego mi segundo cayado, Lazos, para romper la hermandad entre Judá e Israel. </div>
<div id="Zec_11_15" style="display:none;" class="ver_select"><b>Zec 11:15</b>  Y me dijo Jehová: Toma aún los aperos de un pastor insensato; </div>
<div id="Zec_11_16" style="display:none;" class="ver_select"><b>Zec 11:16</b>  porque he aquí, yo levanto pastor en la tierra, que no visitará las perdidas, no buscará la pequeña, no curará la perniquebrada, ni llevará la cansada a cuestas; sino que comerá la carne de la engordada, y romperá sus pezuñas. </div>
<div id="Zec_11_17" style="display:none;" class="ver_select"><b>Zec 11:17</b>  ¡Ay del pastor inútil que abandona el rebaño! Espada caiga sobre su brazo, y sobre su ojo derecho; del todo se secará su brazo, y su ojo derecho será totalmente oscurecido. </div>
<div id="Zec_12_1" style="display:none;" class="ver_select"><b>Zec 12:1</b>  Carga de la palabra de Jehová acerca de Israel. Jehová, que extiende los cielos, y funda la tierra, y forma el espíritu del hombre dentro de él, ha dicho: </div>
<div id="Zec_12_2" style="display:none;" class="ver_select"><b>Zec 12:2</b>  He aquí, yo pongo a Jerusalén por copa de temblor a todos los pueblos de alrededor cuando estén en el sitio contra Judá y contra Jerusalén. </div>
<div id="Zec_12_3" style="display:none;" class="ver_select"><b>Zec 12:3</b>  Y será en aquel día, que yo pondré a Jerusalén por piedra pesada a todos los pueblos; todos los que se la cargaren serán despedazados, aunque todas las naciones de la tierra se junten contra ella. </div>
<div id="Zec_12_4" style="display:none;" class="ver_select"><b>Zec 12:4</b>  En aquel día, dice Jehová, heriré con aturdimiento a todo caballo, y con locura al jinete; mas sobre la casa de Judá abriré mis ojos, y a todo caballo de los pueblos heriré con ceguera. </div>
<div id="Zec_12_5" style="display:none;" class="ver_select"><b>Zec 12:5</b>  Y los capitanes de Judá dirán en su corazón: Los habitantes de Jerusalén serán mi fortaleza en Jehová de los ejércitos su Dios. </div>
<div id="Zec_12_6" style="display:none;" class="ver_select"><b>Zec 12:6</b>  En aquel día pondré a los capitanes de Judá como un brasero de fuego entre la leña, y como una tea de fuego en gavillas; y consumirán a derecha y a izquierda a todos los pueblos alrededor; y Jerusalén será otra vez habitada en su lugar, en Jerusalén. </div>
<div id="Zec_12_7" style="display:none;" class="ver_select"><b>Zec 12:7</b>  Y librará Jehová las tiendas de Judá primero, para que la gloria de la casa de David y la gloria del morador de Jerusalén no se engrandezca sobre Judá. </div>
<div id="Zec_12_8" style="display:none;" class="ver_select"><b>Zec 12:8</b>  En aquel día Jehová defenderá al morador de Jerusalén; y el que entre ellos fuere débil, en aquel tiempo será como David; y la casa de David será como Dios, como el Ángel de Jehová delante de ellos. </div>
<div id="Zec_12_9" style="display:none;" class="ver_select"><b>Zec 12:9</b>  Y será que en aquel día yo procuraré destruir a todas las naciones que vinieren contra Jerusalén. </div>
<div id="Zec_12_10" style="display:none;" class="ver_select"><b>Zec 12:10</b>  Y derramaré sobre la casa de David, y sobre los moradores de Jerusalén, el espíritu de gracia y de oración; y mirarán a mí, a quien traspasaron, y harán llanto sobre Él, como llanto sobre unigénito, afligiéndose sobre Él como quien se aflige sobre primogénito. </div>
<div id="Zec_12_11" style="display:none;" class="ver_select"><b>Zec 12:11</b>  En aquel día habrá gran llanto en Jerusalén, como el llanto de Hadadrimón en el valle de Meguido. </div>
<div id="Zec_12_12" style="display:none;" class="ver_select"><b>Zec 12:12</b>  Y la tierra lamentará, cada linaje de por sí; el linaje de la casa de David por sí, y sus esposas por sí; el linaje de la casa de Natán por sí, y sus esposas por sí; </div>
<div id="Zec_12_13" style="display:none;" class="ver_select"><b>Zec 12:13</b>  el linaje de la casa de Leví por sí, y sus esposas por sí; el linaje de Simeí por sí, y sus esposas por sí; </div>
<div id="Zec_12_14" style="display:none;" class="ver_select"><b>Zec 12:14</b>  todos los linajes que quedaren, cada linaje por sí, y sus esposas por sí. </div>
<div id="Zec_13_1" style="display:none;" class="ver_select"><b>Zec 13:1</b>  En aquel tiempo habrá un manantial abierto para la casa de David y para los moradores de Jerusalén, para lavar el pecado y la inmundicia. </div>
<div id="Zec_13_2" style="display:none;" class="ver_select"><b>Zec 13:2</b>  Y será en aquel día, dice Jehová de los ejércitos, que borraré de la tierra los nombres de los ídolos, y nunca más serán recordados; y también quitaré de la tierra a los profetas y al espíritu inmundo. </div>
<div id="Zec_13_3" style="display:none;" class="ver_select"><b>Zec 13:3</b>  Y será que cuando alguno profetizare todavía, su padre y su madre que lo engendraron le dirán: No vivirás, porque has hablado mentira en el nombre de Jehová; y su padre y su madre que lo engendraron, lo traspasarán cuando profetizare. </div>
<div id="Zec_13_4" style="display:none;" class="ver_select"><b>Zec 13:4</b>  Y será en aquel tiempo, que todos los profetas se avergonzarán de su visión cuando profetizaren; y nunca más se vestirán de manto velloso para mentir. </div>
<div id="Zec_13_5" style="display:none;" class="ver_select"><b>Zec 13:5</b>  Y dirá: No soy profeta; labrador soy de la tierra; porque esto aprendí del hombre desde mi juventud. </div>
<div id="Zec_13_6" style="display:none;" class="ver_select"><b>Zec 13:6</b>  Y le preguntarán: ¿Qué heridas son éstas en tus manos? Y Él responderá: Con ellas fui herido en casa de mis amigos. </div>
<div id="Zec_13_7" style="display:none;" class="ver_select"><b>Zec 13:7</b>  Levántate, oh espada, sobre el pastor, y sobre el hombre compañero mío, dice Jehová de los ejércitos. Hiere al pastor, y se dispersarán las ovejas; y volveré mi mano sobre los pequeñitos. </div>
<div id="Zec_13_8" style="display:none;" class="ver_select"><b>Zec 13:8</b>  Y acontecerá en toda la tierra, dice Jehová, que dos partes serán cortadas en ella, y perecerán; mas la tercera quedará en ella. </div>
<div id="Zec_13_9" style="display:none;" class="ver_select"><b>Zec 13:9</b>  Y meteré en el fuego la tercera parte, y los refinaré como se refina la plata, y los probaré como se prueba el oro. Invocarán mi nombre, y yo les oiré, y diré: Pueblo mío; y ellos dirán: Jehová es mi Dios. </div>
<div id="Zec_14_1" style="display:none;" class="ver_select"><b>Zec 14:1</b>  He aquí, el día de Jehová viene, y tus despojos serán repartidos en medio de ti. </div>
<div id="Zec_14_2" style="display:none;" class="ver_select"><b>Zec 14:2</b>  Porque yo reuniré a todas las naciones en batalla contra Jerusalén; y la ciudad será tomada, y las casas serán saqueadas, y violadas las mujeres; y la mitad de la ciudad irá en cautiverio, mas el resto del pueblo no será cortado de la ciudad. </div>
<div id="Zec_14_3" style="display:none;" class="ver_select"><b>Zec 14:3</b>  Después saldrá Jehová y peleará contra aquellas naciones, como peleó el día de la batalla. </div>
<div id="Zec_14_4" style="display:none;" class="ver_select"><b>Zec 14:4</b>  Y se afirmarán sus pies en aquel día sobre el monte de los Olivos, que está en frente de Jerusalén al oriente; y el monte de los Olivos se partirá por medio de sí hacia el oriente y hacia el occidente haciendo un valle muy grande; y la mitad del monte se apartará hacia el norte, y la otra mitad hacia el sur. </div>
<div id="Zec_14_5" style="display:none;" class="ver_select"><b>Zec 14:5</b>  Y huiréis al valle de los montes; porque el valle de los montes llegará hasta Azel; y huiréis de la manera que huisteis por causa del terremoto en los días de Uzías, rey de Judá: y vendrá Jehová mi Dios, y todos los santos con Él. </div>
<div id="Zec_14_6" style="display:none;" class="ver_select"><b>Zec 14:6</b>  Y acontecerá que en ese día no habrá luz clara, ni oscura. </div>
<div id="Zec_14_7" style="display:none;" class="ver_select"><b>Zec 14:7</b>  Y será un día, el cual es conocido de Jehová, que ni será día ni noche; mas acontecerá que al tiempo de la tarde habrá luz. </div>
<div id="Zec_14_8" style="display:none;" class="ver_select"><b>Zec 14:8</b>  Acontecerá también en aquel día, que saldrán de Jerusalén aguas vivas; la mitad de ellas hacia el mar oriental, y la otra mitad hacia el mar occidental, en verano y en invierno. </div>
<div id="Zec_14_9" style="display:none;" class="ver_select"><b>Zec 14:9</b>  Y Jehová será rey sobre toda la tierra. En aquel día Jehová será uno, y uno su nombre. </div>
<div id="Zec_14_10" style="display:none;" class="ver_select"><b>Zec 14:10</b>  Y toda la tierra se volverá como llanura desde Geba hasta Rimón al sur de Jerusalén; y ésta será enaltecida, y será habitada en su mismo lugar desde la puerta de Benjamín hasta el lugar de la puerta primera, hasta la puerta del Ángulo; y desde la torre de Hananeel hasta los lagares del rey. </div>
<div id="Zec_14_11" style="display:none;" class="ver_select"><b>Zec 14:11</b>  Y morarán en ella, y no habrá allí más destrucción; sino que Jerusalén será habitada confiadamente. </div>
<div id="Zec_14_12" style="display:none;" class="ver_select"><b>Zec 14:12</b>  Y ésta será la plaga con que herirá Jehová a todos los pueblos que pelearon contra Jerusalén: la carne de ellos se disolverá estando ellos sobre sus pies, y se consumirán sus ojos en sus cuencas, y su lengua se les deshará en su boca. </div>
<div id="Zec_14_13" style="display:none;" class="ver_select"><b>Zec 14:13</b>  Y acontecerá en aquel día que habrá en ellos gran quebrantamiento de Jehová; y trabará cada uno de la mano de su compañero, y su mano se levantará contra la mano de su compañero. </div>
<div id="Zec_14_14" style="display:none;" class="ver_select"><b>Zec 14:14</b>  Y Judá también peleará en Jerusalén. Y serán reunidas las riquezas de todas las naciones de alrededor; oro y plata, y ropa de vestir, en gran abundancia. </div>
<div id="Zec_14_15" style="display:none;" class="ver_select"><b>Zec 14:15</b>  Y así será la plaga de los caballos, de los mulos, de los camellos, de los asnos, y de todas las bestias que estuvieren en aquellos campamentos, como esta plaga. </div>
<div id="Zec_14_16" style="display:none;" class="ver_select"><b>Zec 14:16</b>  Y sucederá que todos los que quedaren de las naciones que vinieron contra Jerusalén subirán de año en año a adorar al Rey, Jehová de los ejércitos, y a celebrar la fiesta de los tabernáculos. </div>
<div id="Zec_14_17" style="display:none;" class="ver_select"><b>Zec 14:17</b>  Y acontecerá que los de las familias de la tierra que no subieren a Jerusalén a adorar al Rey, Jehová de los ejércitos, no vendrá sobre ellos lluvia. </div>
<div id="Zec_14_18" style="display:none;" class="ver_select"><b>Zec 14:18</b>  Y si la familia de Egipto no subiere, y no viniere, sobre ellos no habrá lluvia; vendrá la plaga con que Jehová herirá a las naciones que no subieren a celebrar la fiesta de los tabernáculos. </div>
<div id="Zec_14_19" style="display:none;" class="ver_select"><b>Zec 14:19</b>  Éste será el castigo de Egipto, y el castigo de todas las naciones que no subieren a celebrar la fiesta de los tabernáculos. </div>
<div id="Zec_14_20" style="display:none;" class="ver_select"><b>Zec 14:20</b>  En aquel tiempo estará grabado sobre las campanillas de los caballos: SANTIDAD A JEHOVÁ; y las ollas en la casa de Jehová serán como los tazones delante del altar. </div>
<div id="Zec_14_21" style="display:none;" class="ver_select"><b>Zec 14:21</b>  Y toda olla en Jerusalén y en Judá será santificada a Jehová de los ejércitos; y todos los que sacrificaren, vendrán y tomarán de ellas, y cocerán en ellas; y no habrá más cananeo alguno en la casa de Jehová de los ejércitos en aquel tiempo. </div>
