<div id="Zep_1_1" style="display:none;" class="ver_select"><b>Zep 1:1</b>  Palabra de Jehová que vino a Sofonías hijo de Cusi, hijo de Gedalías, hijo de Amarías, hijo de Ezequías, en días de Josías hijo de Amón, rey de Judá. </div>
<div id="Zep_1_2" style="display:none;" class="ver_select"><b>Zep 1:2</b>  Destruiré del todo todas las cosas de sobre la faz de la tierra, dice Jehová. </div>
<div id="Zep_1_3" style="display:none;" class="ver_select"><b>Zep 1:3</b>  Destruiré los hombres y las bestias; destruiré las aves del cielo, y los peces del mar, y las piedras de tropiezo con los impíos; y talaré los hombres de sobre la faz de la tierra, dice Jehová. </div>
<div id="Zep_1_4" style="display:none;" class="ver_select"><b>Zep 1:4</b>  Y extenderé mi mano sobre Judá, y sobre todos los moradores de Jerusalén, y exterminaré de este lugar el remanente de Baal, y el nombre de los ministros idólatras con sus sacerdotes; </div>
<div id="Zep_1_5" style="display:none;" class="ver_select"><b>Zep 1:5</b>  y a los que se inclinan sobre los terrados al ejército del cielo; y a los que se inclinan jurando por Jehová y jurando por Milcom; </div>
<div id="Zep_1_6" style="display:none;" class="ver_select"><b>Zep 1:6</b>  y a los que vuelven atrás de en pos de Jehová; y a los que no buscaron a Jehová, ni preguntaron por Él. </div>
<div id="Zep_1_7" style="display:none;" class="ver_select"><b>Zep 1:7</b>  Calla en la presencia del Señor Jehová, porque el día de Jehová está cercano; porque Jehová ha preparado sacrificio, ha llamado a sus convidados. </div>
<div id="Zep_1_8" style="display:none;" class="ver_select"><b>Zep 1:8</b>  Y será que en el día del sacrificio de Jehová, haré visitación sobre los príncipes, y sobre los hijos del rey, y sobre todos los que visten ropa extranjera. </div>
<div id="Zep_1_9" style="display:none;" class="ver_select"><b>Zep 1:9</b>  Asimismo haré visitación en aquel día sobre todos los que saltan la puerta, los que llenan de robo y de engaño las casas de sus señores. </div>
<div id="Zep_1_10" style="display:none;" class="ver_select"><b>Zep 1:10</b>  Y habrá en aquel día, dice Jehová, voz de clamor desde la puerta del Pescado, y aullido desde la segunda, y grande quebrantamiento desde los collados. </div>
<div id="Zep_1_11" style="display:none;" class="ver_select"><b>Zep 1:11</b>  Aullad, moradores de Mactes, porque todo el pueblo mercader es destruido; talado son todos los que traían dinero. </div>
<div id="Zep_1_12" style="display:none;" class="ver_select"><b>Zep 1:12</b>  Y será en aquel tiempo, que yo escudriñaré a Jerusalén con candiles, y haré visitación sobre los hombres que están sentados sobre sus residuos de vino, los cuales dicen en su corazón: Jehová ni hará bien ni mal. </div>
<div id="Zep_1_13" style="display:none;" class="ver_select"><b>Zep 1:13</b>  Será por tanto saqueada su hacienda, y sus casas asoladas; y edificarán casas, mas no las habitarán; y plantarán viñas, mas no beberán el vino de ellas. </div>
<div id="Zep_1_14" style="display:none;" class="ver_select"><b>Zep 1:14</b>  Cercano está el día grande de Jehová, cercano y muy presuroso; clamor del día de Jehová; amargamente gritará allí el valiente. </div>
<div id="Zep_1_15" style="display:none;" class="ver_select"><b>Zep 1:15</b>  Día de ira aquel día, día de angustia y de aprieto, día de alboroto y de asolamiento, día de tiniebla y de oscuridad, día de nublado y de densa niebla, </div>
<div id="Zep_1_16" style="display:none;" class="ver_select"><b>Zep 1:16</b>  día de trompeta y de pregón de guerra sobre las ciudades fortificadas, y sobre las altas torres. </div>
<div id="Zep_1_17" style="display:none;" class="ver_select"><b>Zep 1:17</b>  Y atribularé a los hombres, y andarán como ciegos, porque pecaron contra Jehová; y la sangre de ellos será derramada como polvo, y su carne como estiércol. </div>
<div id="Zep_1_18" style="display:none;" class="ver_select"><b>Zep 1:18</b>  Ni su plata ni su oro podrá librarlos en el día de la ira de Jehová; pues toda la tierra será consumida con el fuego de su celo; porque ciertamente exterminio apresurado hará con todos los moradores de la tierra. </div>
<div id="Zep_2_1" style="display:none;" class="ver_select"><b>Zep 2:1</b>  Congregaos y meditad, gente indeseable, </div>
<div id="Zep_2_2" style="display:none;" class="ver_select"><b>Zep 2:2</b>  antes que venga a luz el decreto, y el día se pase como el tamo; antes que venga sobre vosotros el furor de la ira de Jehová, antes que el día de la ira de Jehová venga sobre vosotros. </div>
<div id="Zep_2_3" style="display:none;" class="ver_select"><b>Zep 2:3</b>  Buscad a Jehová todos los humildes de la tierra, que pusisteis en obra su juicio; buscad justicia, buscad mansedumbre; quizá seréis guardados en el día del enojo de Jehová. </div>
<div id="Zep_2_4" style="display:none;" class="ver_select"><b>Zep 2:4</b>  Porque Gaza será desamparada, y Ascalón asolada; saquearán a Asdod en el mediodía, y Ecrón será desarraigada. </div>
<div id="Zep_2_5" style="display:none;" class="ver_select"><b>Zep 2:5</b>  ¡Ay de los que habitan en la ribera del mar, de la gente de Ceretim! La palabra de Jehová es contra vosotros, oh Canaán, tierra de filisteos, que te haré destruir hasta no quedar morador. </div>
<div id="Zep_2_6" style="display:none;" class="ver_select"><b>Zep 2:6</b>  Y la ribera del mar será para moradas de cabañas de pastores, y corrales de ovejas. </div>
<div id="Zep_2_7" style="display:none;" class="ver_select"><b>Zep 2:7</b>  Y la ribera será para el resto de la casa de Judá; allí apacentarán: en las casas de Ascalón dormirán a la noche; porque Jehová su Dios los visitará, y hará volver a sus cautivos. </div>
<div id="Zep_2_8" style="display:none;" class="ver_select"><b>Zep 2:8</b>  Yo he oído las afrentas de Moab, y las injurias de los hijos de Amón con que deshonraron a mi pueblo, y se engrandecieron sobre su término. </div>
<div id="Zep_2_9" style="display:none;" class="ver_select"><b>Zep 2:9</b>  Por tanto, vivo yo, dice Jehová de los ejércitos, Dios de Israel, que Moab será como Sodoma, y los hijos de Amón como Gomorra; campo de ortigas, y mina de sal, y asolamiento perpetuo: el remanente de mi pueblo los saqueará, y el resto de mi gente los heredará. </div>
<div id="Zep_2_10" style="display:none;" class="ver_select"><b>Zep 2:10</b>  Esto les vendrá por su soberbia, porque afrentaron, y se engrandecieron contra el pueblo de Jehová de los ejércitos. </div>
<div id="Zep_2_11" style="display:none;" class="ver_select"><b>Zep 2:11</b>  Terrible será Jehová contra ellos, porque hará enflaquecer a todos los dioses de la tierra; y cada uno desde su lugar se inclinará a Él, todas las islas de las naciones. </div>
<div id="Zep_2_12" style="display:none;" class="ver_select"><b>Zep 2:12</b>  También vosotros, etíopes, seréis muertos con mi espada. </div>
<div id="Zep_2_13" style="display:none;" class="ver_select"><b>Zep 2:13</b>  Y extenderá su mano sobre el norte, y destruirá a Asiria, y pondrá a Nínive en asolamiento, y en sequedal como un desierto. </div>
<div id="Zep_2_14" style="display:none;" class="ver_select"><b>Zep 2:14</b>  Y rebaños de ganado reposarán en ella, todas las bestias de las naciones; el pelícano y también el erizo dormirán en sus umbrales; su voz cantará en las ventanas; asolación será en las puertas, porque su enmaderamiento de cedro será descubierto. </div>
<div id="Zep_2_15" style="display:none;" class="ver_select"><b>Zep 2:15</b>  Ésta es la ciudad alegre que estaba confiada, la que decía en su corazón: Yo, y no más. ¡Cómo fue en asolamiento, en cama de bestias! Cualquiera que pasare junto a ella silbará, agitará su mano. </div>
<div id="Zep_3_1" style="display:none;" class="ver_select"><b>Zep 3:1</b>  ¡Ay de la ciudad ensuciada y contaminada y opresora! </div>
<div id="Zep_3_2" style="display:none;" class="ver_select"><b>Zep 3:2</b>  No escuchó la voz, ni recibió la disciplina; no confió en Jehová, no se acercó a su Dios. </div>
<div id="Zep_3_3" style="display:none;" class="ver_select"><b>Zep 3:3</b>  Sus príncipes en medio de ella son leones rugientes; sus jueces, lobos nocturnos que no dejan hueso para la mañana. </div>
<div id="Zep_3_4" style="display:none;" class="ver_select"><b>Zep 3:4</b>  Sus profetas son livianos, hombres prevaricadores; sus sacerdotes contaminaron el santuario, falsearon la ley. </div>
<div id="Zep_3_5" style="display:none;" class="ver_select"><b>Zep 3:5</b>  Jehová justo en medio de ella, no hará iniquidad; cada mañana Él saca a luz su juicio, nunca falta; mas el perverso no tiene vergüenza. </div>
<div id="Zep_3_6" style="display:none;" class="ver_select"><b>Zep 3:6</b>  Hice talar gentes; sus castillos están asolados; hice desiertas sus calles, hasta no quedar quien pase: sus ciudades están asoladas hasta no quedar hombre, hasta no quedar morador. </div>
<div id="Zep_3_7" style="display:none;" class="ver_select"><b>Zep 3:7</b>  Dije: Ciertamente me temerás, recibirás corrección; y así su habitación no será destruida sobre todo aquello por lo cual la castigué. Pero ellos se levantaron de mañana y corrompieron todas sus obras. </div>
<div id="Zep_3_8" style="display:none;" class="ver_select"><b>Zep 3:8</b>  Por tanto, esperadme, dice Jehová, hasta el día que me levante al despojo: porque mi determinación es reunir a las naciones, juntar los reinos, para derramar sobre ellos mi enojo, todo el furor de mi ira; porque del fuego de mi celo será consumida toda la tierra. </div>
<div id="Zep_3_9" style="display:none;" class="ver_select"><b>Zep 3:9</b>  Entonces daré a los pueblos pureza de labios, para que todos invoquen el nombre de Jehová, para que de un consentimiento le sirvan. </div>
<div id="Zep_3_10" style="display:none;" class="ver_select"><b>Zep 3:10</b>  De más allá de los ríos de Etiopía, mis suplicantes, aun la hija de mis esparcidos, me traerán ofrenda. </div>
<div id="Zep_3_11" style="display:none;" class="ver_select"><b>Zep 3:11</b>  En aquel día no serás avergonzada por ninguna de tus obras con que te rebelaste contra mí; porque entonces quitaré de en medio de ti los que se alegran en tu soberbia, y nunca más te ensoberbecerás en mi monte santo. </div>
<div id="Zep_3_12" style="display:none;" class="ver_select"><b>Zep 3:12</b>  Y dejaré en medio de ti un pueblo humilde y pobre, los cuales esperarán en el nombre de Jehová. </div>
<div id="Zep_3_13" style="display:none;" class="ver_select"><b>Zep 3:13</b>  El remanente de Israel no hará iniquidad, ni dirá mentira, ni en boca de ellos se hallará lengua engañosa: porque ellos serán apacentados y dormirán, y no habrá quien los espante. </div>
<div id="Zep_3_14" style="display:none;" class="ver_select"><b>Zep 3:14</b>  Canta, oh hija de Sión; da voces de júbilo, oh Israel; gózate y regocíjate de todo corazón, hija de Jerusalén. </div>
<div id="Zep_3_15" style="display:none;" class="ver_select"><b>Zep 3:15</b>  Jehová ha apartado tus juicios, ha echado fuera tus enemigos: Jehová es Rey de Israel en medio de ti; nunca más verás el mal. </div>
<div id="Zep_3_16" style="display:none;" class="ver_select"><b>Zep 3:16</b>  En aquel tiempo se dirá a Jerusalén: No temas: Sión, no se debiliten tus manos. </div>
<div id="Zep_3_17" style="display:none;" class="ver_select"><b>Zep 3:17</b>  Jehová tu Dios está en medio de ti, poderoso, Él salvará; se gozará sobre ti con alegría, callará de amor, se regocijará sobre ti con cánticos. </div>
<div id="Zep_3_18" style="display:none;" class="ver_select"><b>Zep 3:18</b>  Reuniré a los fastidiados por causa del largo tiempo; tuyos fueron; para quienes el oprobio de ella era una carga. </div>
<div id="Zep_3_19" style="display:none;" class="ver_select"><b>Zep 3:19</b>  He aquí, en aquel tiempo yo desharé a todos tus opresores; y salvaré la coja, y recogeré la descarriada; y los pondré por alabanza y por renombre en todo país de confusión. </div>
<div id="Zep_3_20" style="display:none;" class="ver_select"><b>Zep 3:20</b>  En aquel tiempo yo os traeré, en aquel tiempo yo os reuniré; pues os daré por renombre y por alabanza entre todos los pueblos de la tierra, cuando haga volver vuestra cautividad delante de vuestros ojos, dice Jehová. </div>
